### ISSUE TITLE
[Misc] small and unplanned design requests for Mar 28 sprint

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1003]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by nancyt1** [comment]
Resized hero image for Xavier. **Time Spent:** _20 mins_

**Comment by beccaklam** [comment]
Research Hub Ticket Reviews. **Time Spent**: ~1 hour.

**Comment by nancyt1** [comment]
Added mozfest brand assets into Canva for Kristina G. **Time Spent**: _35 mins_

**Comment by nancyt1** [comment]
Edited webby hero image for Xavier. **Time Spent:** _30 mins_

**Comment by beccaklam** [comment]
Research Hub Meeting with Kasia, Ben, Tibor and Anil. **Time Spent:** _45mins_
