### ISSUE TITLE
[Design Systems] Design Brief + Roadmap

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1022]
- Work on the design brief: 

https://docs.google.com/document/d/1of1_xTOEkVuS5kGwPmGOs84euXbjHtokMzuZpPEMPT0/edit

- Create a roadmap

**Comment by sabrinang** [comment]
Tagged reviewers in the brief: https://docs.google.com/document/d/1of1_xTOEkVuS5kGwPmGOs84euXbjHtokMzuZpPEMPT0/edit?usp=sharing

- a Q2 timeline for milestone 1 is included in the brief (roadmap)

**Comment by kristinashu** [comment]
I think this is done! Are you ok to close it @sabrinang?
