### ISSUE TITLE
Write blog post on PNI mental health graphics

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1029]
[Draft Doc](https://docs.google.com/document/d/1Hnd-mrIgtkW2TqfKyJOUb3zmHiSLyebkJsyCtEDEGBk/edit#heading=h.7zbjekchml9a)
- [x] Create an outline
- [x] Review with Jen or someone to see if there's a story
- [x] Draft post
- [x] Gather artwork
- [ ] Publish

**Comment by nancyt1** [comment]
Wrote a rough [draft](https://docs.google.com/document/d/1Hnd-mrIgtkW2TqfKyJOUb3zmHiSLyebkJsyCtEDEGBk/edit#bookmark=id.2pktipbwupy7) based on the outline Anil created and also started laying out where the art could go. My goal was to write in a voice that didn't include too much complex language and is easily understandable to an audience that might not know PNI or our design process.

**Comment by nancyt1** [comment]
Was able to add in content and save a draft of the blog post but still editing/curating images for it!

**Comment by kristinashu** [comment]
You've done the hard part! Opened a new ticket to publish it https://github.com/MozillaFoundation/Design/issues/1097
