### ISSUE TITLE
Pull 'Best of' Designs & design details into a recap document

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#103]
What were your favorite designs or design details (whether UX, UI, or simply big ideas) that we shipped over the past year or so? Looking for good examples and details to pull into a presentation. 

@flukeout @sabrinang @vazquez @lovegushwa @kristinashu @natalieworth @LauraReynal @xmatthewx – Please dump stuff here as you come across it!

**Comment by lovegushwa** [comment]
@cassiemc 
![screen shot 2015-10-05 at 11 21 43 am](https://cloud.githubusercontent.com/assets/12228435/10289475/4891e45a-6b53-11e5-9734-ef0d588389bc.png)
@flukeout new thimble UI is super nice.

![screen shot 2015-10-05 at 11 24 16 am](https://cloud.githubusercontent.com/assets/12228435/10289541/a8f212b6-6b53-11e5-89e9-7ae0e033411f.png)
@vazquez UI work on Webmaker has many beautiful moments (like tinker mode!)


![screen shot 2015-10-05 at 11 34 29 am](https://cloud.githubusercontent.com/assets/12228435/10289783/17d21716-6b55-11e5-8781-5a1f8d34630f.png)

![screen shot 2015-10-05 at 11 34 17 am](https://cloud.githubusercontent.com/assets/12228435/10289787/1cfc16ec-6b55-11e5-923b-c9ae70f21d63.png)
I love the work illustration work @sabrinang did for the thimble launch!

**Comment by cassiemc** [comment]
Wasn't able to get to this last heartbeat, updating milestone. Thanks for the inspiration @lovegushwa!!

**Comment by cassiemc** [comment]
This has made huge strides today. Work is coming together in this dec: https://docs.google.com/presentation/d/1VWsBYG0t_LUsETTM1VTRvvKFr8NSC-Tm8fzHLJRnHwU/edit#slide=id.gd5c769fa4_0_142

**Comment by cassiemc** [comment]
This is done!
