### ISSUE TITLE
Brownbag Slides: Design system

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1038]
Help make a slide deck for Tailwind work 

- History: why Tailwind, what is and isn’t Tailwind, 
- Design system: how does it fit in with our design system 
- Roadmap: what has been done, in progress, next, 
- Future: clean up

Update: this will now be about both Figma library and tailwind.

**Comment by kristinashu** [comment]
[Sabs and I started a deck here.](https://docs.google.com/presentation/d/1xSWmMy2jV3J5VDGlVoMAvsa1lnPfH6uIlLRug_KsK58/edit#slide=id.g25275a8168_0_260)

**Comment by kristinashu** [comment]
Sabs has filled in a lot of content and has briefed Simon. Next sprint we will get content from Simon, share with Anil for feedback, finalize content and share more widely https://github.com/MozillaFoundation/Design/issues/1045
