### ISSUE TITLE
Add Mozilla Festival assets files to Drive 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#104]
Move all files from old studiomofo dropbox to GDrive Design Assets

**Comment by cassiemc** [comment]
Bumping this to next heartbeat as it's not pressing, these would be old files anyway.

**Comment by cassiemc** [comment]
@sabrinang This seems done, no? Can we close?

**Comment by sabrinang** [comment]
I believe everything has synced 2012-2014 - If there is anything else I find I can throw it into zArchive or appropriate year as I sort out my unsynced files. Closing ticket!

**Comment by cassiemc** [comment]
:boom:
