### ISSUE TITLE
Review Design system pitch deck 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1045]
Continuing issue: https://github.com/mozillafoundation/design/issues/1038

- review contents with team
- revise slides to finalize

**Comment by kristinashu** [comment]
[Link to deck](https://docs.google.com/presentation/d/1xSWmMy2jV3J5VDGlVoMAvsa1lnPfH6uIlLRug_KsK58/edit#slide=id.g25275a8168_0_260)

**Comment by kristinashu** [comment]
@sabrinang I think that what you put in the [Q2 plans deck](https://docs.google.com/presentation/d/177UlA1aFEK4DG84MhPg7LjXCQpLvJoXxJZDSs3OMbLc/edit?usp=sharing) plus your new outline for documentation will be enough. If you agree then please close this ticket or update this ticket to be clearer and more relevant?

**Comment by sabrinang** [comment]
@kristinashu Yes agreed. With the new [outlines for documentation](https://docs.google.com/document/d/1-BYqdl2uM5lRT8zAtoy0Wussj590HAy8dYPs9dFFSPw/edit?usp=sharing) and representation on the recap deck, we will reference the deck information but not update the deck itself. This means we will be extracting relevant information for it to live on either confluence or /design pages. We can also have the relevant content in context in figma so it lives with the other figma files too. Closing!
