### ISSUE TITLE
 Figma Design Library: Typography cont. II

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1054]
continue https://github.com/MozillaFoundation/Design/issues/1036
using the typography elements & typographic styles audit to
- document it in a Figma page
- review with team

**Comment by sabrinang** [comment]
@kristinashu 
Continuing work and review from https://github.com/MozillaFoundation/Design/issues/902#issuecomment-1136334809

- I cleaned and updated the tokens and [figma typography page](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=312%3A396) 
- I also shared it with the team in design jam this week
- We discussed briefly about [token sets](https://docs.tokens.studio/themes/token-sets) but can go over with team in the future when we get into semantic tokens and theming
- I’ve included updates in post-it comments in the figma but will remove them when reviewed so will document them here for future reference in github too

### Things to review and consider:

**Font Size**
- I’ve updated it as a broader scale to be able to cover the range of type styles from the audit  and to be able to accommodate styles in the future
- Added sizes from the last update: 26px, 32px, 34px, 38px, 52px, 60px.
- Change largest range 72px to 64px
- Increases in increment of 2px
- Included upper range 48-64px options and I kept the naming proportionate so if we need to include sizes in between it would be easier in the future

**Font Weight**
- Added a note to the readme: “Some font families may not have certain weights available. This means that if you apply a weight token, it may not visually render for that font family because that weight does not exist.”

**Typography Styles _(composite tokens)_**
- New styles included to increase range: body large, body xsmall, quote base, interface large, interface base, interface small
- Defined styles for form large and base
- Overall mobile note that needs review: 
    - There are many current styles on desktop/mobile that are the same size:
		- do we want to differentiate these size styles for mobile?
		- if so, do we want anything smaller than 12px on mobile? _(if not small and xsmall is the same on mobile as it is the lowest in our current range)_
		- would need to test small type size legibility and accessibility
- excluded _type-accent_ as it seems like we do not use this style anymore


### For future updates

**regarding Links:**
Colors are applied with color tokens (we can create semantic or component tokens for specific uses) _(example names: color-text-link-primary, color-text-link-disabled etc.)_

**regarding States (styles beyond color like hover):**
I believe we would create more typography tokens for them (we could plan where they are organized or if we want them as a separate token set etc.) _(example names: desktop-heading-3-hover)_

**Comment by kristinashu** [comment]
Awesome Sabs! The post-it notes are very helpful.

Having the same, or different, sizes for mobile and desktop makes sense depending on the scenario. Unless something is glaringly not working, I think it's ok for the scope of this work to just be about documenting what we have and not necessarily iterating on it.

**Comment by sabrinang** [comment]
Left the post-it notes in the figma page to keep track of progress for future reference when we iterate on mobile sizes again.
