### ISSUE TITLE
Iterate on background pattern for build/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#106]
We should have a graphic that doesn't require updating with staff changes. Would love to reuse the awesome illustrations Sabrina did - maybe we could just use outlines / dial them down a bit so they work as a background pattern, similar to @natalieworth's background patterns for mozfest.

Old screen:
<img width="1233" alt="screen shot 2015-11-23 at 9 13 28 am" src="https://cloud.githubusercontent.com/assets/1186326/11338533/a9e576be-91c2-11e5-9ff2-07fe0551e2e0.png">

Idea for a new pattern:
<img width="917" alt="screen shot 2015-11-23 at 9 14 12 am" src="https://cloud.githubusercontent.com/assets/1186326/11338529/a2126096-91c2-11e5-8601-75ff0e377a1e.png">

The overlaid text and button should remain the same for now.

**Comment by natalieworth** [comment]
I could probably do this sometime later this week/ early next week? @cassiemc

**Comment by cassiemc** [comment]
Yes! Thanks @natalieworth. Would also be good if we can reduce the overall height of this graphic. We can compress the text a bit vertically when we implement the change.

**Comment by natalieworth** [comment]
Quick update for the progress of this:
![mozilla-foundation-design-banner-illustration-pattern-02](https://cloud.githubusercontent.com/assets/14876567/11987136/cb3a673c-a98e-11e5-8c04-70a39d05a773.png)
I've started to add some icons. I'm still trying to figure out if I'll be able to make the faces work or if I could incorporate them somehow since they were looking a little off in the shades of green. :)

**Comment by cassiemc** [comment]
This looks great @natalieworth, thanks! I know what you mean about the faces. I wonder if they could be part of an icon set that are somehow placed by the other links or headings in the page. It's nice that they do add a bit more 'human' to a sometimes intimidating topic.

**Comment by cassiemc** [comment]
One thing I am wondering. What if all those links and such were also replicated in this repo's readme? I don't want to duplicate effort, but that might be a solution that is more easily updatable. And if it is only Mofos who are using it, I think Github is perfectly acceptable. If we are getting other contributors though, the outward-facing site is great. One other factor is that @mart3ll and team are looking to renew design.mozilla.com. How does this piece fit into that puzzle?

For now, let's keep doing what you're doing @natalieworth but if you have any thoughts about ideal solutions, I'd love to hear them.

**Comment by natalieworth** [comment]
@cassiemc I've got the most recent background iteration for this up on redpen: https://redpen.io/p/spbc191e42bd3ed39e
Totally agree that we could update the links to this repo regarding the above comment. Or perhaps the build/design could relate or migrate to the design.mozilla.com if it is renewed? I'm sure we could streamline it in someway so it is more updatable/ easily accessible for mofo people, but still viewable for people outside of Mofo/ Mozilla. I'll think on it

**Comment by natalieworth** [comment]
@cassiemc I've got the .ai file and an exported svg here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0WXBuS0JVemVUVjQ&usp=drive_web&ddrp=1# Is there dev support for implementing it?

**Comment by cassiemc** [comment]
@natalieworth Yes, probably @vazquez can help make the update it should be a quick one. I'll file a new bug for that.

But re. the files, this is a repeating pattern, no? Might be a smaller file size (if only minutely) to just make an svg of the part that repeats, then we can tile the background, which would be better for responsive too.

**Comment by natalieworth** [comment]
@cassiemc @vazquez good idea, I'll adjust this a bit first so it's a repeating pattern. Right now I've just got it repeating horizontally.

**Comment by natalieworth** [comment]
@cassiemc @vazquez I've created a pattern that works horizontally/ vertically: https://redpen.io/jpc26e9c22650b5d34 It will probably just need adjustment to the background-repeats spacing if that is possible? Here's the google link to the files and an svg: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0QTkyakYxTnhWclk&usp=drive_web&ddrp=1#

**Comment by natalieworth** [comment]
@vazquez I may have to adjust the outer spacing of the svg if it's not possible to manipulate in the background-repeat/ CSS as Illustrator allows me to choose how many pixels I want between the pattern when it's repeated

**Comment by vazquez** [comment]
Beautiful pattern Natalie. I don't think you need to adjust the spacing, it's looking nice. Take a look: http://codepen.io/rvazquez/pen/OMmMXY?editors=100

**Comment by natalieworth** [comment]
Awesome, thanks @vazquez it's looking good. Is there anyway to reduce the horizontal spacing between the repeats (I think I've currently got a bit of a larger gap between the lightbulb and the 'T')

**Comment by vazquez** [comment]
@natalieworth Not possible unfortunately :(

**Comment by natalieworth** [comment]
@vazquez Mind if I update a new svg quickly? I'll try and see if I can fix the spacing

**Comment by vazquez** [comment]
@natalieworth Of course! I won't get to this until next week.

**Comment by natalieworth** [comment]
@vazquez Created a new svg file so it tiles better without having to adjust any spacing: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0Tmp6XzF6ZGpfdGM/view 
I also quickly put it in thimble to see if it would work: https://d157rqmxrxj6ey.cloudfront.net/natalieworth/22912/ Let me know if there's anything I can change or help with for implementing this on the build/design page :)
cc @cassiemc

**Comment by cassiemc** [comment]
Great! Closing this, thanks so much @natalieworth. Moving on to implementation in #122
