### ISSUE TITLE
Figma Design Library: Border, Opacity & Box Shadows

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1060]
- Audit the styles we use
- Create tokens
- Discuss with on usage
- Create documentation

**Comment by sabrinang** [comment]
@kristinashu tokens have been created and figma document pages are ready for discussion/review.

- Border Width & Radius: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=1826%3A1311
  - We commonly use 1px to 4px and we use 6px for the underline in our primary navigation selected/hover states. Do we want a complete range from 0px-6px or simplify the options here?

- Opacity: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=1849%3A1420
  - The opacities we use are a bit all over the place but more commonly rounds to 0.2, 0.3, 0.4, 0.6, 0.8. Do we want to complete scale going by increments of 0.1 or do we want to simplify (example: increments of 0.2)? 
- Box Shadow: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=1849%3A1862
  - After the audit, three box shadow styles are common: blur, bottom and "pop". So I made a set for each with small and large options. Would we need a larger scale or should we consolidate options (see figma file)?

**Comment by kristinashu** [comment]
Looking good! Should this ticket be closed now that you have https://github.com/MozillaFoundation/Design/issues/1070?

**Comment by sabrinang** [comment]
Yes follow up #1070 so closing this!
