### ISSUE TITLE
Figma Design Library: Finalize Design Decisions for Border, Opacity, Box Shadows & Typography

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1070]
Discuss with the design team on design options, scales and names.

- Jam and Design Jam session
- Finalize tokens
- Finalize scales & names
- Finalize figma documentation pages

**Comment by sabrinang** [comment]
@kristinashu figma pages for review:
[Border Width & Radius](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=1826%3A1311)
[Opacity](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=1849%3A1420)
[Box Shadows](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=1849%3A1862)


- We had a good jam session and discussion at design huddle this week
- Shared out audit, token proposals and thinking
- Collected feedback and insight on how we may use our design decisions and options
- Tokens are in [.json in github repo](https://github.com/MozillaFoundation/Design/blob/master/systems/tokens.json) 

____________

**Border Width & Radius**
- For widths, we discussed having a range up to 6px is okay and will cover our needs
- For radiuses, we discussed upcoming PNI use cases and that having: 1px, 4px, 8px, 16px and full would cover our needs
- I made them proportionate to em unit and added a 24px option in case we need to replace the largest radius _(seen in YouTube regrets findings)_

**Opacity**
- For the range, we wanted to simplify options but also have a range of options. So in between increments of 20% vs 5%, we are going for 10% increments (0.1) to have balance a range of options to choose from

**Box Shadows**
- three box shadow types are proposed: blur, bottom and pop
- consolidated each to have small and large options


_Note: We can add semantic or theme tokens in the future for commonly used options that reference this array of global token options so tier 2/3 tokens helps simplify what we use and where we use them_

**Comment by kristinashu** [comment]
Perfect! The jam session was very productive. Thank you for this amazing work and for taking the time to get input from all the designers.
