### ISSUE TITLE
Design Library: /brand Documentation

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1072]
update /brand wagtail pages with updated token and system information

**Comment by sabrinang** [comment]
- unpublished existing color and typography page
- created draft page for design tokens https://foundation.mozilla.org/cms/pages/19029/edit/preview/

**Comment by kristinashu** [comment]
This looks good Sabs! The Figma share settings look correct as well.

**Comment by sabrinang** [comment]
The design tokens page is now published in /brand!
https://foundation.mozilla.org/en/docs/brand/brand-identity/design-tokens/

We have discussed a bit more on documentation during our work week last week and will consider the docs IA (example: how the web style guide, /brand pages, how do I wagtail and figma pages all work together) in future design huddles and jams.
