### ISSUE TITLE
[Misc] small and unplanned design requests for July 18 sprint

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1073]
Wasn't going to have this ticket but some things have come up.

- Update and create additional assets for the WashPost ad promo
- Updates to the IRL t-shirt design based on print proof
- IRL graphic for Apple podcast

**Comment by sabrinang** [comment]
Design review irl tshirt (July 19) and wapo news ad (July 14) — _time spent ~1hr_
