### ISSUE TITLE
Create All Hands stickers

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1078]
Create 3 stickers for all hands by september

- [x] Sketch 3 styles (turtle, minimal, floral)
- [x] Share and Get feedback from Lindsay and Amanda by Aug 18
- [x] Produce designs
- [x] Get final approval by Sept 7
- [x] Send files to Amanda

**Comment by nancyt1** [comment]
Initial drafts in [redpen](https://redpen.io/p/tr516ef8aaa9fac7c8)

**Comment by nancyt1** [comment]
Uploaded to [drive](https://drive.google.com/drive/u/0/folders/1NeCcupkpBiQqU1WE9HxgiJwiC28xtn97) for feedback from social committee/moco. I'll wait for their feedback before producing final designs.

**Comment by nancyt1** [comment]
They want to remove the words from the turtle but all good on the design and requested these sizes: 

- Turtle: 7.5cm wide
- License Plate: 7cm wide (we also want to make this one holographic, but I don’t think you need to do anything for that)
- Arch Sticker: 5cm wide
- Arch Magnet: 6.5cm wide

Next I'll resize and export in a pdf or svg format and give them the final files. They also requested these be made into gifs but that might be made by Shannon instead.

**Comment by nancyt1** [comment]
Final exports are uploaded to [drive](https://drive.google.com/drive/u/0/folders/1P4QVy7-bxK-fVuoPTfYg3Uz_MHZeSrpF)

**Comment by kristinashu** [comment]
w00t w00t!
