### ISSUE TITLE
Design 'open sauce' emblem

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#108]
@xmatthewx and I overhead @vazquez misread a handwritten note on the Mofo calendar wall at Mozlando – someone had written 'open source' but it looked like 'open sauce.' Happy accident? 

Could make a neat swag bag addition for Mozfest, etc. Sriracha bottle label? Or a tshirt. Sticker. etc.

**Comment by xmatthewx** [comment]
We could have the Open Sauce awards, for exemplar demonstration of open source principles.

**Comment by cassiemc** [comment]
This has been cross-posted in the Community Design repo, issue number 7.
