### ISSUE TITLE
Finalize slide template

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1093]
Finalize an updated slide template for staff to use. Request from Lainie is for the slides to look more like our Trustworthy AI work and our [brand expressions](https://foundation.mozilla.org/en/docs/brand/brand-identity/expression/) page.

### To do

- [x] Create/choose a few background styles for the stakeholder to chose from
- [x] Turn all the slides into templates so they can be reused
- [x] Share for feedback
- [ ] Work with moco to add the template to the org

### Links
- A contractor created [these slides](https://docs.google.com/presentation/d/1Nym5ZQCgZ5wy0T2gzaho066_3wI8tGbpBu5rQ8H5euM/edit#slide=id.gf3f0c83eb8_0_77)
- I've been updating them [here](https://docs.google.com/presentation/d/177UlA1aFEK4DG84MhPg7LjXCQpLvJoXxJZDSs3OMbLc/edit#slide=id.p)

**Comment by nancyt1** [comment]
I started adding in more backgrounds in the style of trustworthy AI and slides as templates. It's proving very tedious but making progress!

**Comment by kristinashu** [comment]
Thank you Nancy!

**Comment by kristinashu** [comment]
Thank you Nancy, the slides are looking very nice! I've shared them with Lainie for feedback. 

Just noticed there's was already a ticket for this project https://github.com/MozillaFoundation/Design/issues/981. 

I'll close this ticket and use the original one for finalizing the slides (iterating based on feedback and then adding the template as an official Mozilla template).
