### ISSUE TITLE
Publish blog post on PNI mental health graphics

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1097]
Follow up on https://github.com/MozillaFoundation/Design/issues/1029

via Nancy: The copy is final! Draft is in the cms. Just finalizing the images.

### Todo
- [x] Finalize images
- [x] Publish post!

**Comment by nancyt1** [comment]
Post is [live](https://foundation.mozilla.org/en/blog/the-design-process-behind-privacy-not-included-mental-health-apps/)!

Assets are also in the [drive](https://drive.google.com/drive/u/0/folders/1PYzyQbY3Hze3eeOBonnkIUFyJoO7JHOH)
