### ISSUE TITLE
Spruce up this repo's readme file

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#110]
I was inspired yesterday by @vazquez's readme & wiki for Webmaker – 
https://github.com/mozilla/webmaker-core/blob/develop/README.md
and https://github.com/mozilla/webmaker-core/wiki/Design

So pretty. And useful.

Let's spruce up this one and make this repo more inviting! Could pull from our wiki, and build.webmaker.org/design for visuals.

**Comment by vazquez** [comment]
Closing issue, cause we're done! Improvements to be filed as new issues.
