### ISSUE TITLE
[PNI] Clean up figma file and add tokens

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1107]
Goal is to only see live and most recent designs or current explorations and connect to the design system. Hopefully to have a clean slate for the next time we update designs

- [x] Archive old designs into other figma file, keeping most recent designs and explorations
  - [x] Organize most recent designs, delete extraneous stuff
- [ ] Clean up components 
   - [x] Delete ones we aren't using anymore
   - [ ] Create new components for final designs
   - [x] Add tokens where applicable
   - [x] Create dedicated section for components
- [x] Delete old comments

**Comment by nancyt1** [comment]
Mostly focusing on the "ready for dev" page, I deleted any elements that were hidden and we weren't using, cleaned up components to have correct labels and toggles, and named and grouped layers. I tried to add in tokens mostly to the components since those are reusable but it's very tedious ):

Also, I'm conflicted on whether we should keep making updates in this file or create a new file for additional features bc it's getting big and having 1 big archive file would be really heavy too. My ideal would be if we had one file that was "source of truth" that held PNI components, the live designs, and context/info for the project but make a new file for new features or design changes and we copy into "source of truth" when it's live or ready for development. Maybe we can chat about this later.

**Comment by beccaklam** [comment]
+1 to reorganizing the structure of the PNI file. I would go even further to suggest having one file for components and one file for designs. That way we could just duplicate and archive the design files every time we start a new design year/major project?

**Comment by nancyt1** [comment]
Created a new "master" [PNI file](https://www.figma.com/file/4QFUwtwPN88j74no526S3y/Privacy-Not-Included-Master-File?node-id=0%3A1&t=94g8oT3ujmbCdhXZ-1) and set up some pages I think should be in it. Still a WIP but a start!

**Comment by kristinashu** [comment]
Thank you @nancyt1 for doing all that clean up work! I like the idea of having a Master file! 

I was just looking in Figma and it's clear from the cover image which files are what but perhaps updating the file name would also be helpful. I.e. "*Privacy Not Included Website" to "*Privacy Not Included Archive 2022"

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/1068783/210605081-5c69b76a-5413-425d-925a-bd95efabff36.png">

**Comment by nancyt1** [comment]
Updated! Thank you!
