### ISSUE TITLE
[PNI] Create 'Reflections' Deck

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1108]
Goal:
Create PNI reflection/retro deck and perhaps create a template for retro/reflections based the deck previously created for the YouTube retro.

- [x] Create deck based on YouTube deck
- [x] Add as much content as possible for now
- [x] Get feedback from design
- [x] Share with larger team?

**Comment by beccaklam** [comment]
@nancyt1 I found this [design deck template from femke](https://femke.ck.page/design-deck) that might be useful? I'm going to try it out with our YouTube content. Let me know what you think when you're back? cc: @kristinashu

**Comment by nancyt1** [comment]
We added in all the [content](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=5360%3A99582&t=YelViUpXxk13koYS-1) we could think of and I think it's looking good. I will share with design team for feedback. 

I think this deck would be good as a template for design documentation going forward! Whether this should also be a google slide template is still TBD.

**Comment by kristinashu** [comment]
Amazing, love it! It's super informative but also very concise.

**Comment by nancyt1** [comment]
Tried to templatize the [deck](https://www.figma.com/file/l2sg5G9EoQ8teLLZ1r9sbw/Design-Templates?node-id=0%3A1&t=FwdaOSelUn63nIw7-1) we made for easier access in newer files!

**Comment by nancyt1** [comment]
I would say we're done with this until we get enough data for impact measurement. 

Question still TBD: should we create a version of this in google slides?
