### ISSUE TITLE
Refine YouTube Recap Deck

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#1109]
**Goal:**
Refine YouTube recap deck to have more understandable metrics
- [x] Remove analytic screen caps and describe metrics with more actionable/
"why should I care" framing
- [x] Apply framing to PNI deck

**Comment by beccaklam** [comment]
I started a figma deck for this work [here](https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=1118%3A6960&t=xy1ujh18tgFrjhS4-1) to explore a new format for our design decks. Will discuss with the design team next week. I think there's a plug in that enables you to export these into google slides.

**Comment by beccaklam** [comment]
@kristinashu Would you like us to export this into a google slide deck before marking this ticket as finished?

**Comment by kristinashu** [comment]
That's ok! I think the Figma vs Google slides will be an ongoing pondering.

**Comment by beccaklam** [comment]
This is done for now!
