### ISSUE TITLE
[Jan 20] Design a "Science Fox"

### ISSUE THREAD

**Issue by stephwright** [MozillaFoundation/Design#111]
Science Lab is hosting a training of new project collaborators and a community event in Berlin the first week of Feb.  We are preparing to order swag now to make sure it gets there in time.  We are all in love with Dapper Fox and were wondering if it would be possible to make a "Science" Fox based off Dapper Fox?

Ideas we bandied about...
Dapper Fox in a lab coat? Wearing goggles? Holding an atom, DNA, a beaker... ?

Labtocat could be an inspiration:
![scienceoctocat](https://cloud.githubusercontent.com/assets/14626242/11961786/b695bfe8-a88f-11e5-804d-50ba33a60c7c.png)

What do you think?

**Comment by acabunoc** [comment]
cc @acabunoc - I'm so excited for this!

**Comment by cassiemc** [comment]
cc @kristinashu @natalieworth @lovegushwa

**Comment by zee-moz** [comment]
I love this too! YAY FOXES!
@stephwright  we've been also pushing to shift our language a bit to be less science-focused, and open to Research of all kinds, and Data, too? 
So maybe Data Fox? 
Research Fox-- or is this too vague? 
Or can we consider some kind of ecological research elements, and not just the cold hard lab sciences? Pith helmets? Butterfly nets?

**Comment by stephwright** [comment]
Oooh... I like the idea of Research Fox!  The atom might be good for that, in that case since all things are made up by atoms!  Or am I reaching too far? :)

**Comment by cassiemc** [comment]
@stephwright If this was done by Jan 20, does that sound about right for ordering time?

**Comment by cassiemc** [comment]
@kristinashu @natalieworth @lovegushwa Can any of you link to vector source files for dapper and flower fox please?

**Comment by stephwright** [comment]
@cassiemc that should work!  The sticker folks can get us the stickers in a week... enough time before we fly out to Berlin.

**Comment by flukeout** [comment]
Hello all - I'll be taking this on. I like the idea of varying up the symbolism a bit, how about I try to incorporate 3 elements...

* Data (graph, chart, etc.)
* Hard Science (beaker, atoms, etc.)
* Research (butterfly net, binoculars, etc.)

I'm thinking something along the lines of the larger Dapper fox sticker, with the whole body. Do you want any text on it?

**Comment by flukeout** [comment]
Here's an idea to get the ball rolling. Circular sticker with some stuff sticking out.

![image](https://cloud.githubusercontent.com/assets/25212/12131347/7be3837a-b3c6-11e5-9332-2dad6559d1fc.png)

**Comment by flukeout** [comment]
Here's an option with a full body fox. 

![image](https://cloud.githubusercontent.com/assets/25212/12131454/a174c5e4-b3c7-11e5-838f-40ccd5cf180e.png)

**Comment by cassiemc** [comment]
This is cool @flukeout! I'm partial to the full body fox. @vazquez has something like this going in his research posters too, if you could get this done this week @flukeout we could use it there as well, and @vazquez's version might also inspire!

**Comment by flukeout** [comment]
@vazquez Show me!

**Comment by edrushka** [comment]
I got the Dapper Fox stickers printed at Club Card in Vancouver and they were great.

**Comment by vazquez** [comment]
<img width="417" alt="screenshot 2016-01-06 08 38 32" src="https://cloud.githubusercontent.com/assets/1119821/12143727/08d39fba-b451-11e5-8440-020d90d1f643.png">

**Comment by stephwright** [comment]
This is SO much awesome! :heart_eyes: for the full body fox!

**Comment by kaythaney** [comment]
This makes me tear up a bit with happiness. Thanks, all! :trophy:

**Comment by auremoser** [comment]
:) amaze!

**Comment by arlissc** [comment]
WOW - really incredible :)

**Comment by zee-moz** [comment]
LOVE THIS!

**Comment by flukeout** [comment]
Progress so far.

![image](https://cloud.githubusercontent.com/assets/25212/12158675/d9d40868-b490-11e5-8f6f-abd794b9064a.png)

**Comment by stephwright** [comment]
Is it in appropriate to *SQUEEEEE* in GitHub?

**Comment by natalieworth** [comment]
@vazquez  @flukeout We've gotten suggestions to start a repo of foxes now that the science foxes have also taken off!

**Comment by auremoser** [comment]
here here, a fox-o-dex is in order. :)

**Comment by acabunoc** [comment]
:heart_eyes:

**Comment by flukeout** [comment]
Now with more data & science.

![image](https://cloud.githubusercontent.com/assets/25212/12185459/e09c1068-b54f-11e5-8b2f-d802ce665fd2.png)

**Comment by vazquez** [comment]
Looking amazing @flukeout

**Comment by kaythaney** [comment]
This is terrific. HUGE thanks, team! (also, bet these would be a big hit with the STEM minded Hive members, too!)

**Comment by acabunoc** [comment]
Huge :+1: from me!

**Comment by stephwright** [comment]
Better than anything I could have imagined!!!  LOVE! :heart:

**Comment by froggleston** [comment]
These are completely amazing! \o/

**Comment by bolaram** [comment]
:+1: :+1: :+1: :heart:

**Comment by dpshelio** [comment]
Looks very nice!  :+1: * ∞ 

Just a comment on lab security... shouldn't the fox be wearing the goggles properly when handling an open test tube? :-P

**Comment by MobileMaggie** [comment]
oooh - and a t-shirt please! :)

**Comment by zee-moz** [comment]
From our team meeting, the official feedback on Science Fox:
Test tube should be corked, for lab safety!
Can the binoculars be a little smaller? starting to feel a little too cluttered or crowded.

Otherwise, we love it!

**Comment by flukeout** [comment]
Okay, I'll make the changes!

**Comment by flukeout** [comment]
Corked and ready to science, complete with outline for stickering.
This gives us a tactical edge over the Octocat, who is definitely not following the rules.

![image](https://cloud.githubusercontent.com/assets/25212/12209321/fa7c0ab2-b606-11e5-9b19-0f61e8053006.png)

**Comment by acabunoc** [comment]
I think @stephwright is in charge of ordering - https://github.com/mozillascience/plan/issues/42#issuecomment-169490628

**Comment by flukeout** [comment]
@stephwright We've used Clubcard here in Vancouver for the last batch of dapper fox stickers that @natalieworth created, we can use them again if you'd like and ship them to you, or if you have a local vendor, let me know so I know how to format it.

**Comment by kaythaney** [comment]
thanks, @flukeout! we've used stickermule in the past (die cut), but happy
to do whatever would work best. if clubcard is purely canadian, we can
always have it shipped to @abbycabs or @arlissc in Toronto.

On Fri, Jan 8, 2016 at 4:00 PM, Luke Pacholski <notifications@github.com>
wrote:

> @stephwright <https://github.com/stephwright> We've used Clubcard here in
> Vancouver for the last batch of dapper fox stickers that @natalieworth
> <https://github.com/natalieworth> created, we can use them again if you'd
> like and ship them to you, or if you have a local vendor, let me know so I
> know how to format it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/Design/issues/111#issuecomment-170122360>
> .
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by flukeout** [comment]
Cool, okay here's the sticker prepared to print with Sticker Mule's 3x3 inch die cut option...
https://dl.dropboxusercontent.com/u/109902/science-fox-sticker-3x3-die-cut.pdf

Let me know how it goes!

**Comment by kaythaney** [comment]
Thanks! Will order now. :) (cc @flukeout @stephwright)

sent on the move. apologies for typos.

**Comment by arlissc** [comment]
so happy about this. can't wait to get one !

**Comment by flukeout** [comment]
#ktonthemove

**Comment by froggleston** [comment]
I'd yum up a t-shirt and a whole bunch of stickers. Looks great!

**Comment by kaythaney** [comment]
ordered!

On Fri, Jan 8, 2016 at 4:46 PM, Robert Davey <notifications@github.com>
wrote:

> I'd yum up a t-shirt and a whole bunch of stickers. Looks great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/Design/issues/111#issuecomment-170137010>
> .
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by soapdog** [comment]
This looks sooooooo awesome!!! :+1: also, sign me in for the fox-o-dex :smile_cat:

**Comment by cassiemc** [comment]
Fantastic work everyone, especially @flukeout. Thanks a bunch!

**Comment by stephwright** [comment]
Just want to add my kudos and HUGE thanks!  You guys knocked it out of the park! :baseball: :star2:

**Comment by elioqoshi** [comment]
You guys are a total inspiration! This is how community design should work out!

**Comment by chadsansing** [comment]
Ship me all the foxes. Sweet work, team.

**Comment by dethe** [comment]
These foxes make Grace the [Waterbear](https://github.com/waterbearlang/waterbear) very happy!
![mascot-labcoat](https://cloud.githubusercontent.com/assets/16825/12471228/63d617fc-bfb0-11e5-8547-96b5e7082ff0.jpg)
