### ISSUE TITLE
Write YouTube user control study blog post

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1117]
[Outline Doc](https://docs.google.com/document/d/15YAzFQ9_sOcQLKcSw2yLgQUwsZzrGM3CYErqE2oDv3M/edit#heading=h.uu4dpfn54h7t)
- [x] Decide the main points we want to convey, create an outline
- [x] Write draft
- [x] Review and revise with designers, maybe Anil

Gathering image assets and publishing it will go into another ticket!

**Comment by kristinashu** [comment]
Last I hear, the draft was shared with Becca R for feedback. I think this ticket is done and a new one can be created for making the images and publishing it! 

Amazing job on the draft! I love it!

**Comment by beccaklam** [comment]
Created follow up ticket #1123, closing this ticket!
