### ISSUE TITLE
Post YouTube User Control Study Blog Post

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#1123]
Follow up ticket from #1117
Now that we have a draft written we have some final steps to go through before posting.

**Goals**
- [x] Insert image into draft and finalize choices
- [x] Gather feedback from Becca Ricks (fact checking and any feedback from YouTube)
- [x] Layout post in Wagtail
- [x] Get design and stakeholder reviews
- [x] Post!
- [x] Add the tag `design-team` to the post

**Comment by beccaklam** [comment]
@nancyt1 fyi I've started laying out the post [here](https://foundation.mozilla.org/cms/pages/21266/edit/) in wagtail!

**Comment by kristinashu** [comment]
I'm added our blog posts to our team page https://foundation.mozilla.org/en/docs/brand/. Please add the tag `design-team` to you post so it shows up!

**Comment by beccaklam** [comment]
@nancyt1 I've added in all the illustrations [here](https://foundation.mozilla.org/cms/pages/21266/edit/), do you mind taking a look and giving some feedback? Thank you!

**Comment by beccaklam** [comment]
@nancyt1 Looks like Becca R added some information to the blog and is waiting on Claire to confirm if it's accurate, I'll follow up tomorrow. @kristinashu you can take a look at the post so far on wagtail [here](https://foundation.mozilla.org/cms/pages/21266/edit/) if you want a head start on reviewing it though!

**Comment by kristinashu** [comment]
w00t it's looking good! A few notes:
- Remove the /en from any links e.g https://foundation.mozilla.org/en/youtube/regrets/ should be https://foundation.mozilla.org/youtube/regrets/
- Add the other design blog posts as related posts
- Add your author profiles at the bottom!
