### ISSUE TITLE
[PNI] Finish Reflections Deck with Metrics

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#1124]
Follow up ticket to #1108

After we've added related articles to the PNI site on production let's wait at least a month to see how those additions affect our metrics. After a month, we may have enough data to draw some conclusions about the effectiveness of our designs and we can update the metric slides in the PNI reflection deck.

**Goals**
- [x] Check analytics in a month from the creation of this ticket
- [x] Add metrics to deck

Synced with this [Jira ticket](https://mozilla-hub.atlassian.net/browse/TP1-471)

**Comment by nancyt1** [comment]
Added metrics to the [deck](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Archive-2022?type=design&node-id=5491%3A101489&mode=design&t=I1x6RRtE1z8brsx3-1) comparing 2023 to 2022. tldr, there seems to be growth!
