### ISSUE TITLE
[PNI] Draft outline of what features there are which ones are ready now

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1141]
- Create list of features that are ready now and how to add to use them
- Create list of upcoming features
- Took screenshots of CMS and frontend for documentation and listed basic steps on how to use them in wagtail

**Comment by nancyt1** [comment]
Started my outline [here](https://docs.google.com/document/d/1TkmKvAr2A_I6_agSUUILIX3gHFgXgvdK_bSabIdflYQ/edit#)

**Comment by nancyt1** [comment]
[Document](https://docs.google.com/document/d/1rmpZzsjqXOMHlejF2c3FQncVteWEWc6Hg9AcB3Fj6Y0/edit#)
Added screenshots to each feature and some basic steps on how to change it.

**Comment by kristinashu** [comment]
The doc is awesome, thank you Nancy! I added it to the brownbag meeting invite and I feel good to go!

**Comment by nancyt1** [comment]
Continuing the work with this ticket https://github.com/MozillaFoundation/Design/issues/1145!
