### ISSUE TITLE
[PNI] Product page exploration

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1144]
Goal is to understand the scope of the work
[Link to criteria doc ](https://docs.google.com/document/d/1YoJcigBbP2fKZEmOjlL703SyVtvXPkekhHMteNBNUj4/edit)

- [ ] Benchmark product pages
- [ ] Sketch/wireframe how it all lays out

**Comment by kristinashu** [comment]
I'm going to close this. I don't think we'll get to this for a while.
