### ISSUE TITLE
Transfer ownership of Drive folder

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#115]
Hey @xmatthewx I noticed you are the owner (creator) of the Design Assets folder on Drive. Can you transfer ownership of that folder? Ideally the design team are all co-owners, but if that's not possible maybe just transfer it to me. Thanks!

**Comment by xmatthewx** [comment]
They don't seem to allow co-owners, so I transferred it to you.

**Comment by cassiemc** [comment]
Thanks mw!
