### ISSUE TITLE
[Design System] Draft Documentation Outlines

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1158]
Create an outline or table of contents plan for design systems documentation _(that lives outside of Figma)_. 

This includes:
- [x] web documentation outline _(plans for how it shows up in [/design](https://foundation.mozilla.org/en/docs/design/))_ 
- [x] confluence documentation outline _(how content is linked from internal hub)_

**Comment by sabrinang** [comment]
Reference docs:
- /brand IA: https://www.figma.com/file/t8rWjvPG7Lfgkr3MkS8wiy/Documentation-IA?node-id=0%3A1&t=O3GoUCNOzUCazuPM-1
- design system planning: https://www.figma.com/file/LfxQQzH7fFuiS1m4Gahhfo/Mozilla-Foundation-Design-System-Planning?node-id=0%3A1&t=ZgF4apFOAXgQrvyC-1
- confluence design page: https://docs.google.com/document/d/1o2mdDLgPKc949e3tMWlQHrwuUV0-QP2vp8OxTHq949w/edit

**Comment by sabrinang** [comment]
We are working in this google doc: https://docs.google.com/document/d/1-BYqdl2uM5lRT8zAtoy0Wussj590HAy8dYPs9dFFSPw/edit?usp=sharing

**Comment by sabrinang** [comment]
@kristinashu R? https://docs.google.com/document/d/1-BYqdl2uM5lRT8zAtoy0Wussj590HAy8dYPs9dFFSPw/edit?usp=sharing

Nancy and I have drafted the outlines/table of contents plan for design systems documentation (that lives outside of Figma). Please feel free to leave comments in the doc.

**Comment by kristinashu** [comment]
Love it! It's definitely tricky figuring what to put on /design vs confluence but I like how it's been divided. R+
