### ISSUE TITLE
[Design System] Organize + Structure Figma Files

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1159]
Organizing our Figma files to architect structured pages that outlines a home for where our content goes. There are three main files we want to clean up, rename and restructure:

- [x] Tokens
- [x] Components
- [x] File Presentation

**Comment by sabrinang** [comment]
We will be working in the Figma files themselves:
- Tokens: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=0%3A1&t=Ejf1jSBSC4r9wjZd-1
- Components: https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/Components?node-id=414%3A2644&t=5qWM9tvbFTtThM8i-1
- File Presentation: https://www.figma.com/file/l2sg5G9EoQ8teLLZ1r9sbw/Design-Templates?node-id=104%3A758&t=5aifcExoOtXudaE9-1

We will organize where these live too in our Figma team projects.

**Comment by sabrinang** [comment]
@kristinashu R?

@nancyt1 and I have renamed and organized the pages in the following figma files (please see pages panels for each):

- Tokens: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=0%3A1&t=Ejf1jSBSC4r9wjZd-1
-  Components: https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/Components?node-id=414%3A2644&t=5qWM9tvbFTtThM8i-1
-  File Presentation: https://www.figma.com/file/l2sg5G9EoQ8teLLZ1r9sbw/Design-Templates?node-id=104%3A758&t=5aifcExoOtXudaE9-1

**Comment by kristinashu** [comment]
Beautiful R+! I like the "atomic" section dividers and the black tabs.
