### ISSUE TITLE
Moodboard "Delight & Playful"

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#116]
Related to our design principles discussion in #39, as [documented here](https://docs.google.com/document/d/1a5H9cmUFbPyiOu7Bp5GGlmG7cl6LJIFQSUJugG6Hj1U/edit), we want to explore the theme of "Delight".

> Delight & Playful (Ricardo): Users will experience joy when visiting our stuff, more memorable, building community. 

How does this value or principle inform actual design results? How can it guide design decisions in our process? Let's make a moodboard. Pinterest, google slides, whatever. This should not take more than an hour.

**Comment by cassiemc** [comment]
@vazquez Can you link your moodboard here? Then this is ready to close.

**Comment by vazquez** [comment]
https://docs.google.com/a/mozilla.com/presentation/d/1eIX_HfJCeakjiiMdErBjFTSpefNBevfzfMusTbRY7t4/edit?usp=sharing
