### ISSUE TITLE
[Design Systems] Create Design Systems + Components Delivery Plan

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1160]
We will create a design systems + components delivery plan so we have more specific deliverables mapped to a timeline. We can align with the broader design delivery plan and updated it so that we have a more specific roadmap to reference.

- [x] create delivery plan (high level design system)
- [x] create rubric/guidelines for crafting components (component level)

**Comment by sabrinang** [comment]
@kristinashu R? https://docs.google.com/document/d/1-BYqdl2uM5lRT8zAtoy0Wussj590HAy8dYPs9dFFSPw/edit#bookmark=id.4jf6tqshx877

@nancyt1 and I have drafted the criteria/guidelines for crafting components (component level). Please feel free to leave comments in the doc too.

**Comment by kristinashu** [comment]
The Github project board feels so fancy!
