### ISSUE TITLE
[Atoms] Images

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1169]
# Design
### 1. Audit and research

- [x] Identify all unique use cases
- [x] Gather links to all documentation
- [x] Look up frequency of use to determine priority
- [ ] (Optional) Gather links to useful information on how to craft atom/molecule/component

### 2. Component crafting
- [x] Build: All colors, text styles, and spacing should use defined tokens where applicable
~- [ ] States: Create all the necessary states (Active, hover, disabled)~
- [x] Accessibility: Meet applicable a11y and localization standards (reference the [checklist](https://webflow.com/accessibility/checklist#start))
  - [x] Determine what accessibility issues might come up: none in the Image component itself?
~- [ ] Test against localization needs (content length)~
- [x] Create responsive states (Desktop, tablet, mobile): Would this be defined more in the page template, determined by the grid?
~- [ ] Prototype: If applicable, hook up interactions for prototyping~
~- [ ] Define all editorial/content standards (ex. max characters, min/max width)~

# Documentation
- [x] Layer Naming: Format all layers and name with meaningful values
- [x] Variants and Component Properties Naming: correctly named and consistent _(goal is to make it easy to find in the library e.g. Component / State / Device)_
- [x] Write spec description
   - [x] How and when to use it (explain everything that’s editable, customizable and available in simple and succinct terms)
   - [x] Show all possible variations
     - [x] States
     - [x] Variants
     - [x] Show some examples in context

# Acceptance Criteria

### 1. Audit & Research
- [x] As a Mozilla designer I can find the process work for the logo wrapper in the Audit file

### 2. Design
_As a Mozilla designer I …_

- [x] Build: can update all colors, text styles, and spacing use defined tokens where applicable
- [x] States: can easily swap between states (Active, hover, disabled) and variants
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
~- [ ] Prototype: can easily use the component in a prototype with interactions already preset/hooked up~
~- [ ] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met~

### 3. Documentation
_As a Mozilla designer, I see that:_

- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
~- [ ] All editorial/content standards (ex. max characters, min/max width) have been defined~
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_

- [x] Can easily discover the image component
- [x] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what the component is, how to use it and what edits can be made to it

**Comment by beccaklam** [comment]
@nancyt1 I think this is ready for review. The documentation still feels pretty sparse but I'm still not clear on what to document exactly. Maybe some feedback may help unblock that?

**Comment by nancyt1** [comment]
I love how organized this page is and all the thorough research you did! I added these in the sticky notes into the file but to document here too: 
- I went ahead and removed "Image" from some of the component names since they felt redundant in the asset panel and made folders really long. I also updated some layer names to "Image" since they were still called rectangle and there was only a few instances.
-  For anything that has variants, the property still needs to be renamed in the component panel, (It's currently called "Property 1")
- For the Article & Publication Page Type / Hero half-screen, can you make note of what the solid yellow box means vs the dotted line box?
- I think you could be explicit about which components are meant to be nested somewhere else and not used alone. And for the global streamfield blocks, documenting where and how it might be used or even if it has no particular purpose. Also could be good to add a summarized version of it to the Figma component description thing.

**Comment by beccaklam** [comment]
Thanks @nancyt1 ! I will work on those changes :)

**Comment by beccaklam** [comment]
@nancyt1 I've made the changes you noted, do you mind taking another review?

**Comment by nancyt1** [comment]
Everything looks good to me!

**Comment by beccaklam** [comment]
Okay thank you @nancyt1 ! I'm going to close this ticket for now but we can re-open if there is a need :) cc: @sabrinang @kristinashu

**Comment by sabrinang** [comment]
Great thank you @beccaklam!
We haven't talked about the publishing process that happens after reviews but I selected your image related components and published your changes to the library _(with description of changes)_:

<img width="480" alt="Screenshot 2023-05-01 at 3 24 29 PM" src="https://user-images.githubusercontent.com/2492510/235542443-e62c483e-3057-4378-a304-dfade5a10668.png">

I'm thinking it'll be best practice to fill out the "optional description of changes" as it will appear in our version history if we need to reference/revert anything in the future as it appears like this:
<img width="241" alt="Screenshot 2023-05-01 at 3 26 46 PM" src="https://user-images.githubusercontent.com/2492510/235542626-af0c619d-85a3-4198-a333-56694c3e2168.png">
