### ISSUE TITLE
Moodboard "Meaningful & Effective"

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#117]
Related to our design principles discussion in #39, as [documented here](https://docs.google.com/document/d/1a5H9cmUFbPyiOu7Bp5GGlmG7cl6LJIFQSUJugG6Hj1U/edit), we want to explore the theme of "Meaningful & Effective". 

> Meaningful & Effective (Kristina): Users will care about using our products and it’ll have impact on their lives.

How does this value or principle inform actual design results? How can it guide design decisions in our process? Let's make a moodboard. Pinterest, google slides, whatever. This should not take more than an hour.

**Comment by kristinashu** [comment]
Here's my moodboard https://www.pinterest.com/kristinashu/meaningful-effective/

To me, meaningful means the site makes the user feel an emotion (either through the look and feel or through copy). If the user feels the emotion then the site is effective. Site should also be memorable ie have some personality (not cold and sterile), be accessible to everyone, and be impactful. Sites which met this criteria tended to tell a story or be educational.

**Comment by cassiemc** [comment]
This is fantastic @kristinashu, thanks. Can you (re)share this at our next crit? I think this is ready to close.
