### ISSUE TITLE
[Organisms] Navigation

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1170]
### Design
_1. Audit and research_
- [x] Identify all unique usage instances
- [x] Gather links to all documentation
- [ ] Look up frequency of use to determine priority
- [ ] (Optional) Gather links to useful information on how to craft atom/molecule/component

_2. Component crafting_
- [x] Build: All colors, text styles, and spacing should use defined tokens where applicable
- [x] States: Create all the necessary states (Active, hover, disabled)
- [x] Accessibility: Meet applicable a11y and localization standards (reference the checklist)
- [x] Determine what accessibility issues might come up
- [x] Test against localization needs (content length)
- [x] Create responsive states (Desktop, tablet, mobile)
- [x] Prototype: If applicable, hook up interactions for prototyping
- [x] Define all editorial/content standards (ex. max characters, min/max width)

### Documentation

- [x] Layer Naming: Format all layers and name with meaningful values
- [x] Variants and Component Properties Naming: correctly named and consistent (goal is to make it easy to find in the library e.g. Component / State / Device)
- [x] Write spec description
- [x] How and when to use it (explain everything that’s editable, customizable and available in simple and succinct terms)
- [x] Show all possible variations
   - [x] States
   - [x] Variants
- [ ] Show some examples in context

**Comment by nancyt1** [comment]
I've finished building the component and documentation and since majority of this work is done, I think i'll close this ticket and assign the QA ticket to @sabrinang for her review.
