### ISSUE TITLE
[Atoms] Logos

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1171]
Good to have basically an icon wrapper to swap out logos as needed
**Includes:**
- [ ] Mozfest
- [ ] Pulse?
- [ ] Mozilla logos
- [ ] Favicons

# Design
### 1. Audit and research

- [x] Identify all unique use cases
- [x] Gather links to all documentation
- [x] Look up frequency of use to determine priority
- [ ] (Optional) Gather links to useful information on how to craft atom/molecule/component

### 2. Component crafting
- [x] Build: All colors, text styles, and spacing should use defined tokens where applicable
~- [ ] States: Create all the necessary states (Active, hover, disabled)~
- [x] Accessibility: Meet applicable a11y and localization standards (reference the [checklist](https://webflow.com/accessibility/checklist#start))
  - [x] Determine what accessibility issues might come up
 ~- [ ] Test against localization needs (content length)~
- [x] Create responsive states (Desktop, tablet, mobile)
- [x] Prototype: If applicable, hook up interactions for prototyping
~- [ ] Define all editorial/content standards (ex. max characters, min/max width)~

# Documentation
- [x] Layer Naming: Format all layers and name with meaningful values
- [x] Variants and Component Properties Naming: correctly named and consistent _(goal is to make it easy to find in the library e.g. Component / State / Device)_
- [x] Write spec description
   - [x] How and when to use it (explain everything that’s editable, customizable and available in simple and succinct terms)
   - [x] Show all possible variations
     ~- [ ] States~
     - [x] Variants
     - [ ] Show some examples in context

# Acceptance Criteria

### 1. Audit & Research
- [x] As a Mozilla designer I can find the process work for the logo wrapper in the Audit file

### 2. Design
_As a Mozilla designer I …_

- [x] Build: can update all colors, text styles, and spacing use defined tokens where applicable
- [ ] (n/a) States: can easily swap between states (Active, hover, disabled) and variants
- [ ] (n/a) Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [ ] (n/a) Prototype: can easily use the component in a prototype with interactions already preset/hooked up
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

### 3. Documentation
_As a Mozilla designer, I see that:_

- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined 
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_

- [x] Can easily discover the logo wrapper
- [x] Can easily find this logo wrapper using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what the logo component is, how to use it and what edits can be made to it

**Comment by sabrinang** [comment]
@kristinashu logo page ready for review: https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/Component-Library?node-id=581-5412

**Comment by kristinashu** [comment]
Chatted with Sabs! This looks good R+

**Comment by sabrinang** [comment]
Great thanks Kristina! I published component changes to the library — closing ticket :)

<img width="300" alt="Screenshot 2023-05-03 at 11 50 23 AM" src="https://user-images.githubusercontent.com/2492510/236017107-80a480b0-b6c5-4886-bcde-270852afda8f.png">
