### ISSUE TITLE
[Atoms] Iconography

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1173]
### Design
_1. Audit and research_
- [ ] Identify all unique usage instances
- [ ] Gather links to all documentation
- [ ] Look up frequency of use to determine priority
- [ ] (Optional) Gather links to useful information on how to craft atom/molecule/component

_2. Component crafting_
- [ ] Build: All colors, text styles, and spacing should use defined tokens where applicable
- [ ] States: Create all the necessary states (Active, hover, disabled)
- [ ] Accessibility: Meet applicable a11y and localization standards (reference the checklist)
   - [ ] Determine what accessibility issues might come up
   - [ ] Test against localization needs (content length)
~- [ ] Create responsive states (Desktop, tablet, mobile)~
~- [ ] Prototype: If applicable, hook up interactions for prototyping~
- [ ] Define all editorial/content standards (ex. max characters, min/max width)

### Documentation

- [x] Layer Naming: Format all layers and name with meaningful values
- [x] Variants and Component Properties Naming: correctly named and consistent (goal is to make it easy to find in the library e.g. Component / State / Device)
- [x] Write spec description
- [x] How and when to use it (explain everything that’s editable, customizable and available in simple and succinct terms)
- [x] Show all possible variations
   - [ ] States
   - [ ] Variants
- [x] Show some examples in context

Synced with this [Jira ticket](https://mozilla-hub.atlassian.net/browse/TP1-477)

**Comment by nancyt1** [comment]
Started the documentation of how to use [Icons](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=4484%3A23139&mode=design&t=ANgaGK38fGwfF9US-1). Also publish the current prod icons we have to the library. I think using it would help us identify what icons would be helpful to have since we actually don't use a ton in our current UI.
