### ISSUE TITLE
YouTube RegretsReporter Dataset graphic

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1176]
@kristinashu commented on [Thu Apr 27 2023](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10548)

Related to https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9967

We will need one graphic a several different sizes. The style should align with the existing YouTube RegretsReporter style but represent something about sharing the dataset.

### Links
- [Copy doc](https://docs.google.com/document/d/1c1EBRLs_z6kjFQ0lSkU2R0RWi-3yF7rrY1DGQgPKCmA/edit#heading=h.fc5me87u4tq)
- Thumbnail will appear on [/youtube](https://foundation.mozilla.org/cms/pages/15076/edit/)
- Banner & OG image, for new landing page [/youtube/dataset](https://foundation.mozilla.org/cms/pages/21685/edit/)

### Sizes
- [x] Thumbnail
- [x] OG
- [x] Banner

Deadline for launch is ~May 3~ May 16th.

**Comment by kristinashu** [comment]
Launch data has been pushed back to May 17th!

**Comment by kristinashu** [comment]
@sabrinang so launch date is super early in the morning of May 16 so would be good to get this done by the end of this sprint. Can you please estimate on it?

**Comment by sabrinang** [comment]
@kristinashu R? Ready for review and tested them in context in draft pages where applicable.

**Thumbnail:**
<img width="1714" alt="YouTube Dataset Graphic Thumbnail Preview" src="https://github.com/MozillaFoundation/Design/assets/2492510/49f4d770-9932-4f7c-adf4-8ce8226ec300">

**OG:**
<img width="400" alt="Mozilla-YouTube_Dataset-Graphics_OG-Share-Image_Export" src="https://github.com/MozillaFoundation/Design/assets/2492510/8a505698-1a6a-4a39-8f40-ccdc773fe36c">


**Banner:**



https://github.com/MozillaFoundation/Design/assets/2492510/600a78cd-da1c-46d5-81b8-d990e7fa86ef

**Comment by sabrinang** [comment]
Files in google drive here: https://drive.google.com/open?id=1gKMH15SjxKiQhfnF9yGU7bpUrFT3kHqB&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by kristinashu** [comment]
R+ these look amazing! The images have been added to the draft CMS pages and I've shared links to edit the CMS pages as well as the link to the drive folder with the stakeholders. We might need to add the 'm' to the OG image but will see what Audrey/Shannon say and Shannon can always add it if needed. Thank you!

**Comment by sabrinang** [comment]
Thanks for the review and feedback @kristinashu !  
I forgot about the OG specifications so I checked https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/#og-images which said full logo so I created version of it in the exports gdrive folder as well: 

<img width="400" alt="Mozilla-YouTube_Dataset-Graphics_OG-Share-Image-Logo-Export@2x" src="https://github.com/MozillaFoundation/Design/assets/2492510/edef169d-73a3-417f-aabf-404e2258c3c5">

**Comment by kristinashu** [comment]
Ah perfect! I've replaced the OG image used on the site. Ty!

**Comment by kristinashu** [comment]
Stakeholders are happy with the graphic so this should be good to close!
