### ISSUE TITLE
Moodboard "Coherent"

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#118]
Related to our design principles discussion in #39, as [documented here](https://docs.google.com/document/d/1a5H9cmUFbPyiOu7Bp5GGlmG7cl6LJIFQSUJugG6Hj1U/edit), we want to explore the theme of "Coherent". 

> Coherent (Sabrina): We are smart and efficient with our use of brand and language; people easily understand our messaging and point of view.

How does this value or principle inform actual design results? How can it guide design decisions in our process? Let's make a moodboard. Pinterest, google slides, whatever. This should not take more than an hour.

**Comment by cassiemc** [comment]
@sabrinang Can you link your moodboard here? Then this is ready to close.

**Comment by sabrinang** [comment]
@cassiemc 
Moodboard link: https://www.pinterest.com/sabotage/design-principle-coherence/
