### ISSUE TITLE
[Atoms] Form Validation

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1182]
Incorporating validation in the input field atoms level which will be used to build forms molecule. Progress will be made in https://github.com/mozillafoundation/design/issues/1181

**Comment by sabrinang** [comment]
Validation has been considered and incorporated in #1181 on an atomic input field level and any form level validation will be considered and continued on the molecular form level in https://github.com/mozillafoundation/design/issues/1184
