### ISSUE TITLE
[QA] Input & Form Fields 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1186]
Review and Publish phase for https://github.com/mozillafoundation/design/issues/1181

### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [x] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
- [x] States: can easily swap between states and variants
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [x] Prototype: can easily use the component in a prototype with interactions already preset/hooked up
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

**3. Documentation**

_As a Mozilla designer, I see that:_
- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover this component
- [x] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what this component is, how to use it and what edits can be made to it

### Publishing Procedures
1. Assign original designer to:
- [x] Go to _Publish Library..._ and select relevant changes to publish and fill "Optional description of changes" and select _Publish_
- [ ] Comment and close this ticket when complete

**Comment by nancyt1** [comment]
@sabrinang Works perfectly for me!! I had 2 questions which i put as stickies but I'll add here as well:
- Just curious for our reference, in the beginning did you consider having the input field be it’s own individual component (without the checkbox or supporting texts) and adding it into this bigger component as a “slot”? And maybe why you decided against it?
- For certain layer names you use a hyphen between words and some you don’t, is there a reason behind whether you use it or not? Just want to see if we should both follow the same conventions.

**Comment by sabrinang** [comment]
Thank you @nancyt1 for all the thoughtful feedback! I've addressed them and published the component! 
<img width="467" alt="image" src="https://github.com/MozillaFoundation/Design/assets/2492510/f64da6f4-a13b-456c-8a57-9ad8c28be436">
