### ISSUE TITLE
Moodboard "Opinionated"

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#119]
Related to our design principles discussion in #39, as [documented here](https://docs.google.com/document/d/1a5H9cmUFbPyiOu7Bp5GGlmG7cl6LJIFQSUJugG6Hj1U/edit), we want to explore the theme of "Opinionated". 

> Opinionated (Natalie): Users see us as leaders in design, because our commitment to coherence and expression of our values is authentic.

How does this value or principle inform actual design results? How can it guide design decisions in our process? Let's make a moodboard. Pinterest, google slides, whatever. This should not take more than an hour.

**Comment by natalieworth** [comment]
Files for this mood board are here:
https://www.pinterest.com/nataliejworth/opinionated-moodboard-principles/
https://docs.google.com/presentation/d/1umVz8C-v-KiPgX2gvC6Iip2ZIP1POEFeko7p7ELBx2Q/edit#slide=id.g1062aeecb2_0_10

**Comment by cassiemc** [comment]
Thanks @natalieworth!
