### ISSUE TITLE
Write chapter on Collaboration

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#12]
Depending on what happens in #11 we could have a whole chapter on Collaboration, with sections on:

* Working with engineers – #11
* Working with other designers
* Working with contributors

**Comment by iamjessklein** [comment]
I took a first stab [here](https://github.com/MozillaFoundation/Mofo-Design-Handbook/wiki/Collaboration)
It incorporates issue #11 - but might take some more editing.

**Comment by cassiemc** [comment]
This is great already. Let's close until we are ready for a second draft.
