### ISSUE TITLE
Moodboard "Open"

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#120]
Related to our design principles discussion in #39, as [documented here](https://docs.google.com/document/d/1a5H9cmUFbPyiOu7Bp5GGlmG7cl6LJIFQSUJugG6Hj1U/edit), we want to explore the theme of  "Open". 

> Open (Luke)
* Co-design
* Encouraging contribution
* Involving target users in our process
* We demystify the process of design for the world to see
* With the world as our audience, we strive to maintain an open design collaboration
* Inviting people to our movement
* How do we express fostering community in our work

How does this value or principle inform actual design results? How can it guide design decisions in our process? Let's make a moodboard. Pinterest, google slides, whatever. This should not take more than an hour.

**Comment by flukeout** [comment]
Rought starts - (Open Moodboard)[https://docs.google.com/a/mozilla.com/presentation/d/1BpzXkHqQZltDMUrW6WjEjDcIiPRc9iwhCW6n5wTlAXY/edit?usp=sharing]

**Comment by flukeout** [comment]
Places to look...
* Organizations that invite collaborators & content creators
  * Open source projects?  
* Organizations that share their practices
  * Codepen redesign article 
  * Mailchimp tone guidelines
* Organizations that invite feedback on their work
  * Maybe orgs that have Labs or R&D branches where they showcase work in progress

**Comment by cassiemc** [comment]
@flukeout Can you link your moodboard here?

**Comment by cassiemc** [comment]
Then ready to close...

**Comment by flukeout** [comment]
Here's the [Open Moodboard](https://docs.google.com/a/mozilla.com/presentation/d/1BpzXkHqQZltDMUrW6WjEjDcIiPRc9iwhCW6n5wTlAXY/edit?usp=sharing)
