### ISSUE TITLE
[QA] Search and Dropdown

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1202]
### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [x] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
- [x] States: can easily swap between states (On scroll, Open, Closed) and variants
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [x] Prototype: can easily use the component in a prototype with interactions already preset/hooked up
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

**3. Documentation**

_As a Mozilla designer, I see that:_
- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover the navigation component
- [x] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what this component is, how to use it and what edits can be made to it

**Comment by nancyt1** [comment]
I think everything works well! I left one note which I'll copy here: 

- Submitted might be more clear that it’s after Input? The rest of the names make sense.
- Can you also prototype the “X” to switch back to Default when clicked? If that’s the desired flow?

**Comment by sabrinang** [comment]
Thank you for the reviews @nancyt1! I updated the state name to `Submitted` and I prototyped the "x" to go back to Default. 

For the prototyping, I noted that the the text property preserves the override as it switches back (so it doesn't go back to "Search" placeholder text).

**Comment by nancyt1** [comment]
@sabrinang Nice! I think search is good to publish then!

**Comment by sabrinang** [comment]
Thanks for your reviews Nancy! 
- Published Search to the library.
- I updated dropdown open state to use overlays so it doesn't push elements down in groups and appear on top always. Note: the icon doesn't animate anymore but there is a static state available for use. Published Dropdown to the library.
