### ISSUE TITLE
[Molecules] Cards Audit and Planning

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1203]
### Design
_1. Audit and research_
- [x] Identify all unique usage instances
- [x] Gather links to all documentation
- [x] Look up frequency of use to determine priority
- [ ] (Optional) Gather links to useful information on how to craft atom/molecule/component

**Comment by sabrinang** [comment]
reference [CMS Clean Up](https://github.com/MozillaFoundation/foundation.mozilla.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22cms+clean+up%22) tickets:
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10669
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10670
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10668

**Comment by nancyt1** [comment]
We will continue this ticket through the blog card (#1209) and image text tickets.
