### ISSUE TITLE
[Documentation] Design Systems Page on /design

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1205]
Create outline for the /design page

**Comment by sabrinang** [comment]
continue working in this google doc: https://docs.google.com/document/d/1-BYqdl2uM5lRT8zAtoy0Wussj590HAy8dYPs9dFFSPw/edit?usp=sharing

**Comment by nancyt1** [comment]
Outline is at a good place in the doc and a draft page has been made under /design. Will open another ticket to publish later!
