### ISSUE TITLE
[Molecules] Blog Card

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1209]
### Design
_1. Audit and research_
- [x] Identify all unique usage instances
- [x] Gather links to all documentation
- [x] Look up frequency of use to determine priority
- [ ] (Optional) Gather links to useful information on how to craft atom/molecule/component

_2. Component crafting_
- [x] Build: All colors, text styles, and spacing should use defined tokens where applicable
- [x] States: Create all the necessary states (Active, hover, disabled)
- [ ] Accessibility: Meet applicable a11y and localization standards (reference the checklist)
   - [ ] Determine what accessibility issues might come up
   - [ ] Test against localization needs (content length)
- [x] Create responsive states (Desktop, tablet, mobile)
- [ ] Prototype: If applicable, hook up interactions for prototyping
- [ ] Define all editorial/content standards (ex. max characters, min/max width)

### Documentation

- [x] Layer Naming: Format all layers and name with meaningful values
- [x] Variants and Component Properties Naming: correctly named and consistent (goal is to make it easy to find in the library e.g. Component / State / Device)
- [x] Write spec description
- [x] How and when to use it (explain everything that’s editable, customizable and available in simple and succinct terms)
- [ ] Show all possible variations
   - [ ] States
   - [ ] Variants
- [x] Show some examples in context

**Comment by nancyt1** [comment]
I took this ticket as far as I could but couldn't get hover state for titles working. There's still some kinks to discuss around how we want to architect like having the search card be a variant or on it's own or what nested variable we want to show. I've written stickies around the page of my notes and questions and added documentation for the work I did so far.

**Comment by sabrinang** [comment]
I left some high level pink sticky feedback in the doc that might help! I out of time this sprint to dig into it deeply but great progress on these
