### ISSUE TITLE
Moodboard "Grassroots"

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#121]
Related to our design principles discussion in #39, as [documented here](https://docs.google.com/document/d/1a5H9cmUFbPyiOu7Bp5GGlmG7cl6LJIFQSUJugG6Hj1U/edit), we want to explore the theme of "Grassroots". 

> Grassroots (Jordan)
Things that allow people to have impact without a ton of resources; organizing at the local level; in writing tone, letting people connect with each other, intimate

How does this value or principle inform actual design results? How can it guide design decisions in our process? Let's make a moodboard. Pinterest, google slides, whatever. This should not take more than an hour.

**Comment by lovegushwa** [comment]
@cassiemc https://www.pinterest.com/lovegushwa/grassroots/
