### ISSUE TITLE
[QA] Blog Card and Blog Set

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1219]
### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [x] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
- [x] States: can easily swap between states and variants
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [x] Prototype: can easily use the component in a prototype with interactions already preset/hooked up
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

**3. Documentation**

_As a Mozilla designer, I see that:_
- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover this component
- [x] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what this component is, how to use it and what edits can be made to it

### Publishing Procedures
1. Assign original designer to:
- [x] Go to _Publish Library..._ and select relevant changes to publish and fill "Optional description of changes" and select _Publish_
- [x] Comment and close this ticket when complete

**Comment by sabrinang** [comment]
Hey Nancy, I reviewed the component and left some comments in pink stickies and summarizing here:
_General organization_
- Yeah you can relocate to Cards page if you feel ready to do so and that can simplify the asset naming “Cards/ Blog Card” etc.
- Search type: only exists for size large
- Video Blog Card: possibly a missing variant (or is it considered a customized option)
- .Featured Image: not clear how to find in property panel or consider instance swap property
- Blog Set: Borders and Title text properties do not appear on the panel for Mobile or Tablet
- .Title Text solution looks like it works in cards so feel free to move to “Button & Links” 

_Responsiveness/Widths_
- Consider default widths for Medium/Small
- Consider min/max widths and children frames set to fill for when parent frame for component is adjusted (helpful tutorial on last slide in Additional Examples here: https://www.figma.com/community/file/784448220678228461)

_Editorial/content standards_
- Consider setting max height for preview text truncating after approx three lines height?

_Prototyping_
- Variants should use .Title Text so hover states appear for Search Card and Video Card Variants too

**Comment by nancyt1** [comment]
I was able to fixed most of the issues brought up. I wasn't able to figure out what's happening with the .Topic + Date hover state but I've left some stickies as a reminder to revisit at another time. It's Published!
