### ISSUE TITLE
Implement new bkg pattern for build/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#122]
Design work happening here: https://github.com/MozillaFoundation/Design/issues/106

**Comment by cassiemc** [comment]
@natalieworth created a new svg file for tiling, here: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0Tmp6XzF6ZGpfdGM/view

**Comment by cassiemc** [comment]
@vazquez I'm not sure if this was in the original file (it didn't seem to me like it was on first glance at the source file) or what's happened, but the glasses seem to be darker than the rest of the pattern? 

<img width="715" alt="screen shot 2016-01-12 at 9 18 06 am" src="https://cloud.githubusercontent.com/assets/1186326/12265839/799e9afe-b90d-11e5-903e-2f5b6655e448.png">

cc @natalieworth

**Comment by vazquez** [comment]
I think this happened when I optimized the SVG. I'll look into it.

**Comment by vazquez** [comment]
All fixed now! :smile:

**Comment by cassiemc** [comment]
Perfect! Thanks @vazquez, looks great.
