### ISSUE TITLE
[QA] Banner (Default + Donate) 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1223]
### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [x] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
- [x] States: can easily swap between states and variants
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
~- [ ] Prototype: can easily use the component in a prototype with interactions already preset/hooked up~
~- [ ] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met~

**3. Documentation**

_As a Mozilla designer, I see that:_
- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover this component
- [x] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what this component is, how to use it and what edits can be made to it

### Publishing Procedures
1. Assign original designer to:
- [x] Go to _Publish Library..._ and select relevant changes to publish and fill "Optional description of changes" and select _Publish_
- [x] Comment and close this ticket when complete

**Comment by nancyt1** [comment]
@sabrinang Everything looks good, I left 2 notes that aren't blockers: 
1. Wondering if we should put a placeholder image on the default banner or use the figma default fill to show that it’s suppose to house an image? This keeps it consistent with other placeholders as well.
2. I agree with naming it something more specific like header banner.
3. Small note but i also renamed the text layers to match the content property (ex. Heading, lede).
Other than that, it's ready to publish!

**Comment by sabrinang** [comment]
Thanks for the review @nancyt1 and I made some updates:
- re Default Placeholder: It is a good point and thanks for pointing it out, I went with figma default image fill now to show it should house an image and to be consistent with the donate placeholder!
- re Name: I updated name to Header Banner
- re Page Types: I now noted in the _Header Banner Types_ section that default header banners are used “Banner” page types
- thanks for updating the text layer names and good catch

**Comment by nancyt1** [comment]
All good to publish! assigning back to you

**Comment by sabrinang** [comment]
Thanks, published to library!
