### ISSUE TITLE
[QA] Donate Page Template

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1224]
### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [x] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
~- [ ] States: can easily swap between states and variants~
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
~- [ ] Prototype: can easily use the component in a prototype with interactions already preset/hooked up~
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

**3. Documentation**

_As a Mozilla designer, I see that:_
- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover this template
- [x] Can easily find this template using the MoFo Design’s naming conventions and file organization
- [x] Can easily understand what this template is, how to use it and what edits can be made to it

### Publishing Procedures
1. Assign original designer to:
~- [ ] Go to _Publish Library..._ and select relevant changes to publish and fill "Optional description of changes" and select _Publish_~ Can't "publish" pages as it is not a component
- [ ] Comment and close this ticket when complete

**Comment by nancyt1** [comment]
@sabrinang This page looks really good! I left a few blue sticky notes with comments.

**Comment by sabrinang** [comment]
Thanks Nancy for the review and feedback! I moved the page to a separate template file here https://www.figma.com/file/rK4Nt5dtxizgv4HTOGrlK2/%5BWIP%5D-Templates?type=design&node-id=1%3A26&mode=design&t=MUgqvjW9ubxxRXmM-1

I cleaned up spacing and autolayout groups and put in a placeholder image in the template. I also like the idea of slot component for content/spacing so I filed a separate issue as I think it will also be useful for other page templates: https://github.com/MozillaFoundation/Design/issues/1231

**Comment by nancyt1** [comment]
All good to publish as well! Assigning back to you

I wanted to clarify that the placeholder image I was referring to was for the body content as a potential "slot" component but that can be done in the separate issue.

**Comment by sabrinang** [comment]
Sounds good thanks! I've placed a image 16:9 component in the template for now as a placeholder as well. Since these "templates" are on a page in the [Templates file](https://www.figma.com/file/rK4Nt5dtxizgv4HTOGrlK2/%5BWIP%5D-Templates?type=design&node-id=1%3A26&mode=design&t=FRWlenZzwSMO4sj0-1) there isn't anything to "publish" as they are not components but marked the status as approved.
