### ISSUE TITLE
Brainstorm stickers for All Hands

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1225]
On behalf of the social committee, Stephanie has requests some MoFo stickers and magnets for All Hands in August. Via Steph:

> In terms of ideas, we tossed around a bagel, Mozilla25, a [prism sticker](https://www.etsy.com/ca/market/prism_sticker) and that's about it. I think anything related to Montreal is going to be great, we trust ya'll's creativity.

> The goal is to have 2 stickers, 1 magnet with a similar budget to last year which I believe was $300-$350.

IHR team has also requested some stickers https://docs.google.com/document/d/1A9gLsWvRO9EQ2Zo47O-Ngl5O-73Z1uozJNEoFMaZuQA/edit 

Some todos
- [x] Decide how many to make
- [x] Brainstorm ideas
- [x] Sketch ideas
- [ ] Feedback from stakeholders, narrow down

Finalize in https://github.com/MozillaFoundation/Design/issues/1228

**Comment by nancyt1** [comment]
Our sketches are in the figjam brainstorm [file](https://www.figma.com/file/fxXqvX94EuO57cAl9oru9w/All-Hands-Sticker-Jam?type=whiteboard&node-id=0%3A1&t=fLj4ctGn6DpDMAtS-1)

**Comment by kristinashu** [comment]
Sketches are looking so good and fun, can't wait to have them irl! 

I've clean up the file to separate social committee ones from insights ones. Please add hearts to your favorite ones and I will share with stakeholders for their input!
