### ISSUE TITLE
Interview design candidates 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1226]
#### Review take home assignments
- [x] Sabrina
- [x] Rebecca
- [x] Nancy

#### Write interview questions (with Xavier)
- [x] Write questions and decide who will ask which ([doc](https://docs.google.com/document/d/1DVVVzlsGOAoquuSf3P_IU-lWj8NO5xQCQ1vdi9xhRE8/edit?usp=sharing))

#### Hold interviews and submit feedback in Greenhouse
- [x] Sabrina
- [x] Nancy
- [x] Mavis

**Comment by sabrinang** [comment]
Note: Set up and duplicate take home test by EOD today so it is ready for Chidinma

**Comment by sabrinang** [comment]
Reviewed take home tests and created individual links and passwords in the [gdoc](https://docs.google.com/document/d/1DVVVzlsGOAoquuSf3P_IU-lWj8NO5xQCQ1vdi9xhRE8/edit?usp=sharing)

**Comment by sabrinang** [comment]
working in the [gdoc](https://docs.google.com/document/d/1DVVVzlsGOAoquuSf3P_IU-lWj8NO5xQCQ1vdi9xhRE8/edit) and started slack group with mavis, xavier, nancy to start coordinating

**Comment by sabrinang** [comment]
@kristinashu We have a draft script and interview questions in this doc: https://docs.google.com/document/d/1DVVVzlsGOAoquuSf3P_IU-lWj8NO5xQCQ1vdi9xhRE8/edit?usp=sharing

Please feel free to comment/edit as we wanted to have a draft in place before Monday before our first interview!
