### ISSUE TITLE
PNI product images for cars edition

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1237]
Create 25 product images for upcoming PNI Cars & Privacy guide edition
- [x] Source product images
- [x] Put images on transparent background and crop
- [x] Test image background on staging website 
- [x] Export and put into Google Drive folder for Jen

Deadline: Aug 15
Stakeholder: Jen C

[List of products](https://docs.google.com/spreadsheets/d/1ku8kUeoOCQTlDiBl7nzn8E--v4dhWI7NBeIjkKBnpFU/edit#gid=1764292170)
[Figma file](https://www.figma.com/file/37oqkJjSCf6fhAJWGhAWbE/PNI-Product-Images?type=design&node-id=302%3A3&mode=design&t=yzVlDhQ5XbR3nCmg-1)
[Drive folder](https://drive.google.com/drive/folders/1SP7yL91NEylFhqIsp20Mv5xDrQZgb7Os?usp=sharing)

**Comment by tessheinricks** [comment]
Completed & Ready for Review / Implementation. You can find the final exports [here](https://drive.google.com/drive/folders/1SPeCM21i5SkBF6sP4Zk1jKoJ5zb5fvhb?usp=drive_link) & the source images [here](https://drive.google.com/drive/folders/1SPGaRM5NCgrCya1MKi1wt1ok0FkYVcWI?usp=drive_link) within the google drive

**Comment by kristinashu** [comment]
Thank you @tessheinricks! I've reviewed these and they look great! Stakeholders are also happy with them so you can go ahead and close this ticket 🎉🎉🎉
