### ISSUE TITLE
[misc] IRL Design Review

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1242]
Give design feedback to Shannon for IRL podcast designs

**Comment by sabrinang** [comment]
- reviewed Shannon's [IRL designs](https://drive.google.com/file/d/1n9pCMs9wE8GdkcuHQiDZs9qu1xuy1J1n/view?usp=sharing)
- replied feedback to Shannon in slack channel
- pasted feedback in Eeva's feedback [doc](https://docs.google.com/document/d/1TAWLDqo-3fTV3YUEs8UaRfdD125rrzxpuyAYDym1tzg/edit?usp=sharing) and replied mofo-design too

**Comment by sabrinang** [comment]
- slack check-in with Shannon and revisions
- can follow up at crit tmrw

**Comment by kristinashu** [comment]
Adding that I also gave feedback to add a Donate link to https://irlpodcast.org/ and they will be implementing that.

**Comment by sabrinang** [comment]
Shannon shared her progress last crit and the IRL socials, videos, site etc. are live!
