### ISSUE TITLE
[PNI Privacy Page] Support Dev & QA

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1243]
Continue supporting Mavis as she develops the PNI page

**Comment by kristinashu** [comment]
@nancyt1 @sabrinang and I to QA on staging/prod today!

**Comment by sabrinang** [comment]
Where are we collecting QA feedback? I reviewed [staging](https://foundation.mofostaging.net/en/privacynotincluded/articles/annual-creep-o-meter/) and I'll post feedback here for now:

**Links opening on separate tabs vs same page**
- Some links such as _“privacynotincluded.org”_ in the quiz results and _“our methodology“_ near the end of the page open on the same page but some links open on separate tabs (example: 15 editions of _*Privacy Not Included_ and product links)
- If we want to keep users on the page to complete the other CTAs we may consider opening all links on new tab? (currently inconsistent)

**Quiz result images load speed** 
- They have a bit of a delay on first load but once they have appeared they load instantly. Could these load instantly the first time?

**Quiz copy typo**
- For _Your privacy is so-so_ section “privacynotincluded.org” link is repeated twice in the body

**Missing link in “Our Approach” section**
- “one research report” in the copy doc links to https://foundation.mozilla.org/en/blog/mozilla-study-data-privacy-labels-for-most-top-apps-in-google-play-store-are-false-or-misleading/

**Comment by kristinashu** [comment]
Thank you for catching those! @sabrinang could you please add these to the first comment in https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11185 as actionable checkbox items?
