### ISSUE TITLE
[Misc] small and unplanned design requests for Oct 2 Sprint

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1249]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by tessheinricks** [comment]
- Assisting Shannon with IRL promotional Animation
- Assisting Shannon and Eeva with IRL postcard file preparation for print (urgent request)
-  Assiting Daniel with PR for "Help with Donations" page

**Comment by nancyt1** [comment]
- Created PNI press graphic for Kevin

**Comment by kristinashu** [comment]
Thank you for picking these up! Closing this ticket and opened this one for next sprint https://github.com/MozillaFoundation/Design/issues/1249
