### ISSUE TITLE
[Feb 19] Create office/event swag assets

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#125]
Working with @ldecoursy on a list here: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

So far, we know we need:
- [ ] Dapper Fox patches
- [ ] Dapper Fox stickers
- [ ] X-Ray Goggles stickers – simple logo + URL or something fun
- [ ] Thimble stickers – simple logo + URL or something fun
- [ ] Generic #teachtheweb button

We'd like to have these assets printed and delivered to the Brooklyn office by the first in a series of events beginning February 26.

**Comment by cassiemc** [comment]
I heard there is a Thimble sticker in the works. @flukeout is this true?

**Comment by ldecoursey** [comment]
Cassie,
I am not the person you are looking for..


On Mon, Jan 11, 2016 at 11:59 AM, Cassie McDaniel <notifications@github.com>
wrote:

> Working with @ldecoursey <https://github.com/ldecoursey> on a list here:
> https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0
>
> So far, we know we need:
>
>    - Dapper Fox patches
>    - Dapper Fox stickers
>    - X-Ray Goggles stickers – simple logo + URL or something fun
>    - Thimble stickers – simple logo + URL or something fun
>    - Generic #teachtheweb button
>
> We'd like to have these assets printed and delivered to the Brooklyn
> office by the first in a series of events beginning February 26.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/Design/issues/125>.
>



-- 
Louann DeCoursey
Chief Executive Officer-Open Water Foundation
Acting Executive Director-Colorado Water Innovation Cluster
www.openwaterfoundation.org
320 East Vine Drive, Suite 315
Fort Collins, CO 80524
970-286-7439 Ext. 801 (OWF office)
970-372-8126 (cell)

Open data.  Open software.   Open decisions.... with positive social impact.

**Comment by cassiemc** [comment]
Sorry @ldecoursey. Meant @ldecoursy

**Comment by cassiemc** [comment]
Hoping out @my-le can help out with this, under guidance of @vazquez. We'll need to gather some existing assets for you so will do that today!

**Comment by ldecoursey** [comment]
Again wrong person :)

**Comment by cassiemc** [comment]
@ldecoursey I hadn't mentioned you again - you might be getting notifications because you are subscribed to the issue from the initial faulty mention. Try clicking 'unsubscribe' under Notifications in the righthand bar.

**Comment by cassiemc** [comment]
Closing this. The [meta issue in plan](https://github.com/MozillaFoundation/plan/issues/660) is tracking this work, and granular issues are filed here: https://github.com/MozillaFoundation/Design/labels/swag
