### ISSUE TITLE
PNI product images for holiday 2023 edition

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1251]
Create ~42 images for the new/updated products for the upcoming holiday edition (highlighted in green in the spreadsheet)
- [x] Source product images
- [x] Put images on transparent background and crop
- [x] Export
- [x] Test image background on staging website 
- [x] Create Google Drive folder for all the images
- [x] Compress images
- [x] Share folder with Jen in #2023-pni-production channel 

Deadline: October 30th
Stakeholder: Jen C

[List of products](https://docs.google.com/spreadsheets/d/1gECoPRNbMae6OWnnQUgLTgyUgrt9hwuAfIHWR9CJW28/edit#gid=273266428)
[Figma file](https://www.figma.com/file/37oqkJjSCf6fhAJWGhAWbE/PNI-Product-Images?type=design&node-id=302%3A3&mode=design&t=yzVlDhQ5XbR3nCmg-1)
[Main drive folder](https://drive.google.com/drive/folders/1P8lClhg-ynouGX0NdiMwylhLRqwLHD-c)

**Comment by kristinashu** [comment]
I've pulled all the source images and started a folder [in Drive. ](https://drive.google.com/drive/folders/1TWOQodmmbWyo5bTCnMoFmaB_rTIMm32m?usp=sharing)

Starting to add them to the [Figma file.](https://www.figma.com/file/37oqkJjSCf6fhAJWGhAWbE/PNI-Product-Images?type=design&node-id=302%3A3&mode=design&t=tEt3V5qJYG5uN85U-1)

**Comment by kristinashu** [comment]
I've exported all the images into [this folder. ](https://drive.google.com/drive/folders/1UXHr_o-RTq-fE2h7PcAVoD7v_BcL_znO)

I can't test them because staging is down at the moment.

@nancyt1 when you can, please give these a quick review!

**Comment by nancyt1** [comment]
Looks like the Wyze watch is missing but everything else looks good! Thank you!

**Comment by kristinashu** [comment]
Thank you for catching that Nancy! I've also [compressed all the images](https://drive.google.com/drive/folders/1WRq9pA6xjmXkiVTCIW9kTlsAqZmR0Blg?usp=sharing). Will share with Jen now!
