### ISSUE TITLE
[PNI Privacy Index] Create google tags and setup dashboard for metrics

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1255]
Metrics to track:

- [x] Ratio of people who scroll 75% of the page, and where do those people come from?
- [x] Number of people who finish the quiz
     - [x] For the quiz, it would be good to how many people drop off - so how many clicks the first "See Results" button gets, then the Sign up vs "Skip to Results" button.
- [x] Number of shares button clicks from quiz
- [x] Number of people signed up to email through quiz
- [x] Which email callout gets the most clicks; quiz, upper half, or end, header, or footer?
- [x] Number of people who use the anchor links?

**Comment by nancyt1** [comment]
Created all tags and asked Tyler to publish. Organized them into a dashboard [here](https://lookerstudio.google.com/reporting/23d9e362-4fef-4c35-8a2f-82e297247832)

**Comment by kristinashu** [comment]
Ooooh very nice!

**Comment by nancyt1** [comment]
Tags published!
