### ISSUE TITLE
Update donor care envelopes

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1257]
via Patrick

We need to update the address on the envelopes for both 
- No10 size (4-1/8 x 9-1/2 inch) to send to donors
- No 9 size (3-7/8 x 8-7/8) for donors to return to us (goes inside the No10)

Address is:
Mozilla Foundation
149 New Montgomery St 4th Floor
San Francisco, CA 94501

Our old envelope designs are [here](https://drive.google.com/drive/folders/1G3BJ7hJ6g0LF5lEH4SvmZIP28WxGFV89)  & moco's is [here. ](https://drive.google.com/file/d/0B7Y4FzbuIgbYNUVnYTJnSU9rak0/view?resourcekey=0-ygCjxNDFtGPVhpH69tkgTQ)

Will stick with a simple design since these might change soon with the rebrand.

**Comment by kristinashu** [comment]
Working files and PDFs are in [this Drive folder. ](https://drive.google.com/drive/folders/1VI_mw27pLnW3uT0EuXJgZEspiMgSQN_Y)

**Comment by kristinashu** [comment]
Stakeholder is happy with them so I've [packed the files for print.](https://drive.google.com/drive/folders/1VmiZlq-grYZ4uDEuBdRz2nNjj_G5FloL)

**Comment by sabrinang** [comment]
@kristinashu I took a look at the file for print:

- Can you check if the zip code is correct? _(94501 or 94105 … what is on the file is different than what is listed https://www.mozilla.org/en-US/contact/spaces/san-francisco/)_
- Folder name typo _“Envelops”_ missing an _“e”_
- _Mozilla_No10_Envelope_2023_ file looks like there’s an extra bounding box element (but it doesn’t show up for print anyway so might not matter)

**Comment by kristinashu** [comment]
Amazing catches, thank you @sabrinang! You were right about the zip code. All the updates have been made.
