### ISSUE TITLE
[Misc] small and unplanned design requests for Oct 30 Sprint 🎃

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1258]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by sabrinang** [comment]
- fix empty folders for logos /brand (10min)
- review & tidy donate banner (40 min)
- reply Eeva's UX research inquiry (10 min)

**Comment by nancyt1** [comment]
Edited and exported an IRL sticker file for Eeva (on behalf of Shannon) (1 hr)

**Comment by nancyt1** [comment]
Gathered and exported 3 PNI product images for Jen (1 hr)

**Comment by kristinashu** [comment]
Thank you for helping out with these!

**Comment by sabrinang** [comment]
- mofo-design: research hub thumbnail support for Eeva (20 min)
