### ISSUE TITLE
AI Funding Principles Page pt2

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1262]
Lindsey needs help designing a new page in our CMS.
[Notes doc](https://docs.google.com/document/d/1FpUYQEPu5UeSbQLKOg4vzXEbaW0CBEr1H0QdEaRbW9s/edit#heading=h.e6hawwj66q6e)
[Draft Doc](https://docs.google.com/document/d/1SaxAFIo1yBD8g_49MVxookOtn8OcmVNQea1vP2g7GNc/edit?pli=1)
[Spotlight Image Drive](https://drive.google.com/drive/u/0/folders/1EsZTUMgMJrAO1Ayw2Bx0jNGu6Z5_AaOE?q=parent:1EsZTUMgMJrAO1Ayw2Bx0jNGu6Z5_AaOE)

### Timeline
- Draft copy Oct 18 
- Final copy Oct 31
- Launch Nov 7

### Graphics
Shannon has meet with Lindsay and is ready to start on the graphics as soon as the principles are shared with her

**To do**
- [x] Get graphics from Shannon (Banner, icons, and icon wide images)
- [x] Get spotlight images from Lindsey and crop into circle
- [x] Get final signoff from Lindsey about layout
- [x] Add in principles once Listing block is added
- [ ] Work with stakeholder to add a “call-out” (using an existing cms block) to https://foundation.mozilla.org/en/what-we-fund/ that links to the new page

**Comment by nancyt1** [comment]
Handing off layout to Lindsey to make updates!

**Comment by kristinashu** [comment]
The page is looking great! Unfortunately there are delays in getting exec approval on the copy so this won't be going live today. I think it's ok to close this ticket - stakeholder should be able to add the link to the page themselves. @nancyt1 do you want to re-estimate this to include some of the illustration work?
