### ISSUE TITLE
[Misc] small and unplanned design requests for Jan 8 Sprint 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1263]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by sabrinang** [comment]
- slack check in with Becca _(Jan 5)_ & Jesse re: TikTok app QA mobile device information for testing _(Jan 10)_

note: app launch pushed back to March 12
