### ISSUE TITLE
[Main Navigation Drop Down] & [Work Week] Planning Card Sorting Exercise

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1267]
Prepare and plan the card sorting IA exercise for the tech platforms work week.

Discuss what approach, tools and planning is needed.

**Comment by sabrinang** [comment]
started the discussion planning today and will continue tomorrow at design jam huddle

**Comment by kristinashu** [comment]
I've asked Shing for:
- a whiteboard & whiteboard markers
- a few different colors of stickies
- a few colors of little dot stickers (for voting on the stickies)
- makers 
- maybe some flip chart paper

She will see if we have a whiteboard in the space, and she can provide stickies + stickers + markers + flip chart paper.

**Comment by tessheinricks** [comment]
Documentation of this exercise can be viewed within [Figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=1%3A22&mode=design&t=8Y0cZrZSyF8H1KI5-1)
