### ISSUE TITLE
 [Main Navigation Drop Down] & [Work Week] Card Sorting Exercise (3 hours)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1268]
Participate in the the card sorting exercise at the tech platforms work week.

**Comment by tessheinricks** [comment]
Documentation of this exercise can be viewed within [Figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=1%3A22&mode=design&t=8Y0cZrZSyF8H1KI5-1)
