### ISSUE TITLE
[Design Support] MozFest Site Updates with Torchbox

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#1269]
Provide design reviews and support for MozFest website updates done by Torchbox.

**Comment by kristinashu** [comment]
I've left a few comments on the wireframes and medium fidelity mock ups in [Miro](https://miro.com/app/board/uXjVNMhwh4o=/?moveToWidget=3458764571715013456&cot=14). Medium fidelity [prototype is here.](https://www.figma.com/proto/qfVqiUyj10U1jL6Km50YIh/MozFest-2024?page-id=4102%3A112&type=design&node-id=4-511&viewport=985%2C789%2C0.84&t=wjzIUbcKcW5QqqHZ-8&scaling=scale-down&starting-point-node-id=4%3A511&hide-ui=1) They're still blocked by content but overall it seems like they are sticking to our design styles.

**Comment by kristinashu** [comment]
Staging site is here https://mozfest-foundation-s-integratio-hbhswc.mofostaging.net/

I flagged a few styling issues and they will triage them during stand tomorrow.

Prod push is planned for this Wednesday.

**Comment by kristinashu** [comment]
Updates are live!
