### ISSUE TITLE
[Misc] small and unplanned design requests for Feb 5 Sprint

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1282]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by sabrinang** [comment]
- design support for tech platforms [slides](https://docs.google.com/presentation/d/1vuNOrkQXHirnla-Y_0r5Mzf1z2-rBRbloxwUSoqlZNc/edit#slide=id.g25275a8168_0_260) (3h)
- cms support for Becca

**Comment by kristinashu** [comment]
Thank you so much Sabs for this work. I've increased the estimate to 4.

**Comment by kristinashu** [comment]
Adding our design support for Miguel and the DFL events layout.
