### ISSUE TITLE
PNI V-Day product images due by Feb 1

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1283]
Create ~42 images for the new/updated products for the upcoming holiday edition 
- [x] Source product images
- [x] Put images on transparent background and crop
- [x] Export
- [x] Test image background on staging website 
- [x] Create Google Drive folder in Web Team Drivefor all the images
- [x] Share folder with Jen in #2024-pni-production channel 

Deadline: Feb 1
Stakeholder: Jen C

[List of products](https://docs.google.com/spreadsheets/d/1T4oWtD3IHxoUPO2qHFBTjLqFmXCjszqp3FzaaqDwP1k/edit#gid=475815926)
[Figma file](https://www.figma.com/file/37oqkJjSCf6fhAJWGhAWbE/PNI-Product-Images?type=design&node-id=302%3A3&mode=design&t=yzVlDhQ5XbR3nCmg-1)

**Comment by tessheinricks** [comment]
Images have been exported and stored within a 2024 [*PNI Valentines Day Product Images](https://drive.google.com/drive/folders/1pBUaDJB3pewE8PKJEmDbKWwr3lclx7bD?usp=drive_link) Folder

[PNG](https://drive.google.com/drive/folders/17-dXb6s9XnanVu_WuKzG9_falhDKK7za?usp=drive_link) & [SVG](https://drive.google.com/drive/folders/1SF1Td-y8HbKfZ6UFWdAd-aXLoEmjC2XH?usp=drive_link) formats have been included. 

I will now test these files on staging before sharing with the stakeholder

**Comment by kristinashu** [comment]
Amazing, thank you @tessheinricks! I suspect some of these products are CREEPY!

**Comment by tessheinricks** [comment]
The images have been tested and are now being reviewed by the stakeholder. 

[PNG](https://drive.google.com/drive/folders/17-dXb6s9XnanVu_WuKzG9_falhDKK7za?usp=drive_link)
[SVG](https://drive.google.com/drive/folders/1SF1Td-y8HbKfZ6UFWdAd-aXLoEmjC2XH?usp=drive_link)
[Valentines Folder](https://drive.google.com/drive/folders/1pBUaDJB3pewE8PKJEmDbKWwr3lclx7bD?usp=drive_link)
