### ISSUE TITLE
'In Transparency We Trust?' report graphics

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1288]
## Restyle graphics 
- [x] GenAI Outputs
- [x] Stages of processing
- [x] Taxonomy of disclosure methods (keep this one simple)
- [x] Potential Harms
- [x] Reformat Pros and Cons list
- [x] Chinese AI example screen cap (Resize)
- [x] Example of watermarked photo (might be removed or replaced)
- [x] Example of cryptographic watermarks (screen shop - keep as is)
- [x] Fitness Test Table (Maybe reformat or use data wrapper)
- [x] Visual labels for Fair & Poor barometer
- [x] Maybe a table of the barometer?
- [ ] Maybe graphic for CTA at end?

Rest of the work is happening in https://github.com/MozillaFoundation/Design/issues/1280

**Comment by kristinashu** [comment]
Thank you @nancyt1 for updating this ticket!

**Comment by nancyt1** [comment]
All graphics have been exported and added to PDF and article page
