### ISSUE TITLE
Clean up Board posters Drive folder

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#129]
@lovegushwa This folder is kinda messy / hard to find final files. Seems like we often reference it, particularly when something is needed kinda last minute so would be worthwhile to take 5 min and clean it up. 

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvY0FuX0EzaXVkQ1U&usp=sharing

**Comment by lovegushwa** [comment]
no problem @cassiemc
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvY0FuX0EzaXVkQ1U&usp=sharing

**Comment by cassiemc** [comment]
Also, I moved the board files and the OOH folder out of the Admin folder, which I don't think was entirely intuitive when searching. Thanks so much @lovegushwa!

**Comment by lovegushwa** [comment]
@cassiemc the idea with the _PROJECTS folder is that it contains buckets of work. Admin (we could have a better name for this) is stuff for the Mozilla executive team (like board posters). I agree OOH should probably go somewhere else, we could create a folder that's MOFO/MOCO collaborations. 

Anyhow I think it will get out of hand if individual projects end up in _PROJECTS ... and better if we think of it as _PROJECTS > Bucket(Teach, Advocacy etc.) > Project folder.

We just need to understand and agree on what the buckets are.

**Comment by cassiemc** [comment]
Ah I see, good thinking. Let's revisit it once our larger program map and IA are clearer.
