### ISSUE TITLE
[Main Navigation] Create Miro board for staff feedback and input on future IA ideas

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1297]
Old miro https://miro.com/app/board/uXjVNDiDd-w=/ 
New wip board https://miro.com/app/board/uXjVNm8Qdno=/?share_link_id=87342155434 

Will share this when we socialize new MVP nav more broadly to staff. Miro should include:
- [x] Intro & context
- [x] Space for feedback on MVP prototype
- [x] Space for staff to generate ideas on how to better group and name our content groupings

**Comment by tessheinricks** [comment]
The updated [miro](https://miro.com/app/board/uXjVNm8Qdno=/) board has been completed and shared with stakeholders

**Comment by sabrinang** [comment]
Reviewed the [miro](https://miro.com/app/board/uXjVNm8Qdno=/) board, updated the screenshots and some stickies from gdoc comments.
