### ISSUE TITLE
Retire or update wm.org/style-guide

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#13]
Note to self: As we develop the design handbook and move fwd with branding, we should retire or update and extend https://webmaker.org/style-guide

**Comment by cassiemc** [comment]
@xmatthewx This page seems wildly out of date already. Any reason why we cannot just remove it now?

**Comment by xmatthewx** [comment]
Everything on wm.org will be retired in the next few weeks. Should be soon enough that we don't need to make a task just for this, but I'll keep an eye on it.

**Comment by cassiemc** [comment]
Ok, I'll add this to a later milestone.

**Comment by cassiemc** [comment]
Update @xmatthewx ?

**Comment by xmatthewx** [comment]
Still pending, still inevitable (snippet launch was delayed). I think we can close this since it doesn't actually require us to do anything.
