### ISSUE TITLE
[Pan Mozilla] Docs to onboard agency

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1302]
Consolidate our info to quickly onborad an external agency about our moco IA

**Comment by tessheinricks** [comment]
The team is currently working through multiple documents below to co-design an integrated and collaborative artifact 

[MOCO & MOFO IA: onboarding outline](https://docs.google.com/document/d/1nufgZLEmPRDvqwwQzTVTSV_txCfn0-H56tFQDDdfs8Y/edit?usp=sharing)
[Onboarding slides (MoFo)](https://docs.google.com/presentation/d/1670-cAIy8akM3ujjpKBAdPKaQYUMbt1vusJxHLQ4hBA/edit?usp=sharing)
[Onboarding slides (MoCo)](https://docs.google.com/presentation/d/1yrLjNpicD1u52LKmYzyccMGKgtBf405mo3LGZBD24LM/edit?usp=sharing)

**Comment by kristinashu** [comment]
Made a lot of progress on this! I've shared it with Shing for feedback and we aim to share it with the agency tomorrow. Finalizing this will happen in https://github.com/MozillaFoundation/Design/issues/1310
