### ISSUE TITLE
Follow up on Drive storage space issue

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#131]

**Comment by cassiemc** [comment]
I'd like to audit where we are at with Google Drive storage. Can everyone please check your drive storage by going to https://www.google.com/settings/storage and reporting back here? 

@flukeout:  ...
@vazquez: ...
@sabrinang: ... 
@kristinashu: ... 
@natalieworth: ... 
@lovegushwa: ... 
@cassiemc: 14/30 GB

Here are possibile solutions from Sophana @ moco: 

> **Options:** 
> * First option: We can expand each member of your team up to 200GB of space at $210/year per person. 
> * Second option: Expand 1 person in your team to 1TB of space that everyone will share and upload to for $1068/year. 
> (These are the enterprise prices set by Google and will be charged back to your department)
> 
> To make a decision, first it's helpful to understand how Google Drive uses the storage space . For example: Shared file space will be used by the owner of the file. Any native Google doc files do not use the quota such as gdocs, gsheets, gslides etc. 

I should reply to Sophana soon and let her know, this has been unresolved for some time now and I'd like to sort it out before I go on mat leave.

**Comment by flukeout** [comment]
@cassiemc Are you sure those prices above are correct? This is what I'm seeing...

https://github.com/MozillaFoundation/Design/issues/131#issuecomment-182629373

**Comment by cassiemc** [comment]
fascinating @flukeout. Sophana also said, "(These are the enterprise prices set by Google and will be charged back to your department)" That price disparity is insane though. 

@flukeout Maybe the drive only counts the files you have uploaded. Have you shared all your working files? Maybe you don't have a lot of weight to the files you've shared?

I'll wait for @lovegushwa and @natalieworth to update their numbers but it's looking like we don't have an immediate need to increase our space anyway.

**Comment by cassiemc** [comment]
Upgraded @lovegushwa for more storage space for video files. @natalieworth if you want more storage you'll need to file a service-now, then we can loop in Sophana. You might want to do this before I go on mat leave.
