### ISSUE TITLE
Design dapper fox patches

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#132]
For reference on vendor, etc: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

**Comment by vazquez** [comment]
Dapper Fox available here: https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvZVNibHlPTGpBN1E/view?usp=sharing

**Comment by vazquez** [comment]
![screenshot 2016-02-10 09 54 10](https://cloud.githubusercontent.com/assets/1119821/12950658/3fc66e0c-cfdc-11e5-87c9-e4d37136a176.png)

We need to the add the word Mozilla. I checked with the vendor and they will be able to clearly print this level of fidelity.

**Comment by Raphseck** [comment]
Hey guys, how are you?
Its only add the word Mozilla?
I can help you. : )

**Comment by cassiemc** [comment]
Hi @Raphseck, this issue is already assigned to @my-le but thank you for offering to help! There are lots of unassigned issues in the Mozilla-wide Community Design repo if you want to chip in on anything else: https://github.com/mozilla/Community-Design/issues

**Comment by vazquez** [comment]
Update from @my-le 

![screenshot 2016-02-10 13 28 47](https://cloud.githubusercontent.com/assets/1119821/12957358/4837047a-cffa-11e5-8a1d-49d9a5e79014.png)

cc @ldecoursy

**Comment by Raphseck** [comment]
ok! 
Great @my-le  ! : )

**Comment by cassiemc** [comment]
@my-le @vazquez This wasn't mentioned in crit but we shouldn't bend the mozilla logo on the curve like that. Probably will work better at the top of the fox, straight across.

**Comment by vazquez** [comment]
What about something like this? Dapper fox's arms have been fixed, and mozilla straight across.

![screenshot 2016-02-11 09 39 00](https://cloud.githubusercontent.com/assets/1119821/12979168/71d408ce-d0a3-11e5-9555-c6685fe94204.png)

Some other iterations on Red Pen: https://redpen.io/knee11b621df954828

**Comment by my-le** [comment]
Variant here:
![rgb-dapperfox-patch-lyt03-variant](https://cloud.githubusercontent.com/assets/10426601/12980354/6ad5ce48-d0dc-11e5-9f3c-669708e98a37.jpg)

**Comment by cassiemc** [comment]
Works for me! What do you think @ldecoursy?

**Comment by ldecoursy** [comment]
Looks great - thanks all!

**Comment by my-le** [comment]
Dapper Fox 3" Patch – Final eps and pdf files link:
https://drive.google.com/drive/u/0/folders/0B_itHmpwHBFvTmctZ0xtZ0VBVmc

**Comment by cassiemc** [comment]
Fabulous, thanks @my-le! Appreciate your diligence on these.
