### ISSUE TITLE
Design dapper fox stickers

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#133]
For reference on vendor, etc: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

**Comment by vazquez** [comment]
Dapper Fox available here: https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvZVNibHlPTGpBN1E/view?usp=sharing

**Comment by vazquez** [comment]
![screenshot 2016-02-10 09 54 10](https://cloud.githubusercontent.com/assets/1119821/12950658/3fc66e0c-cfdc-11e5-87c9-e4d37136a176.png)

We need to the add the word Mozilla. I checked with the vendor and they will be able to clearly print this level of fidelity.

**Comment by vazquez** [comment]
![screenshot 2016-02-10 09 56 48](https://cloud.githubusercontent.com/assets/1119821/12950741/9ed7d85e-cfdc-11e5-83fd-98f7a80b23ed.png)

**Comment by my-le** [comment]
New stickers: add "mozilla" (curved and straight across).
![rgb-dapperfox-sticker-2in-lyt03-b](https://cloud.githubusercontent.com/assets/10426601/12979901/2886b392-d0da-11e5-89bb-802c5a0de07c.jpg)

**Comment by my-le** [comment]
New stickers: add "mozilla" (curved and straight across).
![rgb-dapperfox-sticker-2in-lyt03-b](https://cloud.githubusercontent.com/assets/10426601/12980021/d357abb4-d0da-11e5-859a-66bd38351b37.jpg)

**Comment by vazquez** [comment]
The straight across one looks like a winner! :smiley:

**Comment by cassiemc** [comment]
Agreed, I love the bottom right one where the fox is at a slight tilt. Nice work @my-le!

**Comment by ldecoursy** [comment]
+1 to @cassiemc  that's my fave too :)

**Comment by my-le** [comment]
Dapper Fox Sticker – Final eps file link:
https://drive.google.com/drive/u/0/folders/0B_itHmpwHBFvZVpfT1V5VTctaHM
