### ISSUE TITLE
Design x-ray goggles stickers

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#134]
X-Ray Goggles stickers – simple logo + URL or something fun

For reference on vendor, etc: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

**Comment by vazquez** [comment]
X-Ray Goggles available here: https://drive.google.com/open?id=0B4Q8pzCpDS_eNlFGV2pXV1lMODQ

**Comment by vazquez** [comment]
Pattern for X-Ray Goggles available here (will need colour tweaking): https://drive.google.com/open?id=0B20-0lpP23c0S0JFYURsR2VzZTA

**Comment by vazquez** [comment]
Some ideas:

![screenshot 2016-02-10 09 57 31](https://cloud.githubusercontent.com/assets/1119821/12950769/bd2b943a-cfdc-11e5-9776-d9b3f13947da.png)

![screenshot 2016-02-10 09 58 09](https://cloud.githubusercontent.com/assets/1119821/12950778/ccfcab56-cfdc-11e5-888f-2f5357066e57.png)

**Comment by cassiemc** [comment]
@vazquez I don't think the transparency/white is working, though I do prefer the patterned background (more dynamic) over the more corporate looking logo + headline. 

For option 1, can you keep the logo solid please and try a bkg color other than blue? (It's okay if you need to adjust how the logo is constructed to remove the transparency) A lighter purple could work well. Could pull colours and/or illustrations from https://redpen.io/es1c8a6b03b98e56cb (@kristinashu will have assets)

**Comment by kristinashu** [comment]
Here's the ai file for the site mockup: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLSzhwM0NQVm1Va0E/view?usp=sharing

Not sure if it's helpful but here's a messy file where I played around with the logo colours: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLRlNILTliV1J0UGs/view?usp=sharing

**Comment by vazquez** [comment]
From My's Redpen (https://redpen.io/at79251cd1b8e0e7a5)

![screenshot 2016-02-10 12 26 59](https://cloud.githubusercontent.com/assets/1119821/12955571/ada7737a-cff1-11e5-8268-03581da54960.png)

**Comment by ldecoursy** [comment]
Is it worth playing with the the text on the top? Because of the eyes in the logo, it's looking a little like a face.

**Comment by vazquez** [comment]
If we want to achieve consistency with the Thimble Sticker (and general brand guidelines), it is best to keep the text towards the bottom. With that being said, these new colour iterations might help.

![screenshot 2016-02-11 09 41 01](https://cloud.githubusercontent.com/assets/1119821/12979236/c85f31fa-d0a3-11e5-8cc0-15f2eb5f553b.png)

**Comment by cassiemc** [comment]
I love the third one! The colours really pop :)

**Comment by ldecoursy** [comment]
:dancers: +1 Thanks again team!

**Comment by my-le** [comment]
The final eps file link:
https://drive.google.com/drive/u/0/folders/0B_itHmpwHBFvWnh1bGxfdEVxbFE
