### ISSUE TITLE
Design thimble stickers

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#135]
Thimble stickers – simple logo + URL or something fun

For reference on vendor, etc: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

@flukeout is there already a thimble sticker?

**Comment by vazquez** [comment]
Thimble sticker available here: https://drive.google.com/open?id=0B2qu3ExKWIlvN2F0YW40NDVSUms

**Comment by vazquez** [comment]
2" x 2" Template available here: https://www.stickermule.com/templates/circle-stickers

**Comment by vazquez** [comment]
![screenshot 2016-02-10 09 52 57](https://cloud.githubusercontent.com/assets/1119821/12950626/1e01d8ec-cfdc-11e5-9398-00498e7e2b61.png)

**Comment by ldecoursy** [comment]
Thanks @vazquez Is this ready to send to the vendor if we want to order them, or anything else we're waiting on?

**Comment by vazquez** [comment]
This file is ready. @my-le, can you add the finalized .eps file to this ticket?

**Comment by my-le** [comment]
Final eps file for Thimble 2" x 2" Sticker:
https://drive.google.com/a/mozilla.com/file/d/0B_itHmpwHBFvNTRCbVlibDRkUGM/view?usp=sharing

**Comment by vazquez** [comment]
@cassiemc Are we good to close this issue?

**Comment by cassiemc** [comment]
Yes, nice work @my-le and @vazquez! Can you guys make sure the final assets are in a shared Drive folder so @ldecoursy has easy access?

**Comment by vazquez** [comment]
Available in the Design Google Drive inside the Swag folder.

**Comment by cassiemc** [comment]
Perfect. @ldecoursy Here's the link: https://drive.google.com/a/mozilla.com/folderview?id=0BzfN9sXlOXt1SG9wVDY5TzdLUWs&usp=sharing

**Comment by ldecoursy** [comment]
@cassiemc @vazquez Don't we also need a clean version without the stickermule guidelines on it?

**Comment by vazquez** [comment]
@ldecoursy Stickermule asks for people to upload the sticker with the guidelines on.
