### ISSUE TITLE
Design #teachtheweb button

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#136]
We need a simple pin/button with the text #teachtheweb. One option would be to recreate what was done for the gear store pin with sort of grungy looking type: https://redpen.io/p/eqfc9228701f81dae9 (@natalieworth worked on that)

* Size 1.5"
* Should be on brand with teach.mozilla.org (@sabrinang is currently working on a style guide but can answer any Qs you have in the meantime)
* Preferred vendor is http://www.wackybuttons.com/
* Let's put the final assets in Drive / Design Assets / Swag : https://drive.google.com/a/mozilla.com/folderview?id=0BzfN9sXlOXt1SG9wVDY5TzdLUWs&usp=sharing
* Deadline: Feb 12

For reference on vendor, etc: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

**Comment by cassiemc** [comment]
@ldecoursy Any preference for size? Assume it affects price.
@vazquez Please assign this to yourself or @my-le as appropriate :)

**Comment by ldecoursy** [comment]
I'd go with 1.5"

Thanks!

**Comment by cassiemc** [comment]
Thanks @ldecoursy and @vazquez, I updated the description accordingly.

**Comment by vazquez** [comment]
Wacky Buttons Templates available here: http://www.wackybuttons.com/templates.php

**Comment by vazquez** [comment]
This is the Mozilla unified colour palette for colour inspiration:

![mozilla-unified](https://cloud.githubusercontent.com/assets/1119821/12722111/6e754014-c8d1-11e5-8ad9-1ddca92b362c.png)

**Comment by vazquez** [comment]
@ldecoursy This is the button layout for the 2-line hashtag
![screenshot 2016-02-09 09 39 38](https://cloud.githubusercontent.com/assets/1119821/12919226/24606d28-cf11-11e5-8a83-db7f6e66567e.png)

**Comment by ldecoursy** [comment]
Sharing some feedback from the team:
* It is a bit hard to read - can we try another font? (also a mention of the font having a holiday vibe along with some of the cogs that look star/snowflake like)
* Overwhelmingly, people read this as #teach instead of teachtheweb - so think we need to think about an arc or other orientation

**Comment by vazquez** [comment]
Some updates from @my-le 

![screenshot 2016-02-10 12 29 23](https://cloud.githubusercontent.com/assets/1119821/12955671/1ca6409e-cff2-11e5-8c32-2829431134be.png)

**Comment by vazquez** [comment]
Based on feedback, what about the right version @ldecoursy?

**Comment by ldecoursy** [comment]
Much better. In order to avoid the "busy" or "holiday" feel, can we make some minor adjustments to the cogs - maybe less, or less star and holiday lights-type shapes?

**Comment by vazquez** [comment]
Reducing amounts of points. 

![screenshot 2016-02-10 14 35 33](https://cloud.githubusercontent.com/assets/1119821/12959227/8f4d833a-d003-11e5-958f-ad9717f53667.png)

**Comment by cassiemc** [comment]
I think it is the stars (a la the Jewish star) that are actually throwing things off. @vazquez @my-le can we replace the star shapes with other cogs/gears? I would also reduce the text size of 'teach the web' – this font is much clearer, so could be smaller and still readable, and giving it some white space / breathing room should help make it feel a little less busy.

**Comment by vazquez** [comment]
Two iterations from @my-le 

![screenshot 2016-02-11 09 44 41](https://cloud.githubusercontent.com/assets/1119821/12979290/21a87de8-d0a4-11e5-8781-9d23dc8f6313.png)

RedPen available here: https://redpen.io/gpda1198f132710e5e

**Comment by ldecoursy** [comment]
I like the second one, but would change the diamond shape to a circle or hexagon.

**Comment by vazquez** [comment]
Change on its way

**Comment by my-le** [comment]
Diamond changed by hexagon:

![rgb-teachtheweb-1 5in-lyt04-variant](https://cloud.githubusercontent.com/assets/10426601/12980987/1ef652ba-d0df-11e5-899f-ddd9fccf8195.jpg)

**Comment by ldecoursy** [comment]
Looks great to me!

**Comment by vazquez** [comment]
Great! @my-le, add the .EPS Google Drive link to this ticket and we can call this one done! :balloon:

**Comment by my-le** [comment]
Final version eps file here:
https://drive.google.com/drive/u/0/folders/0B_itHmpwHBFvcDhoZGpQclZUV0k

**Comment by cassiemc** [comment]
Excellent work folks. :boom: Please make sure any final assets are all in a shared Drive folder.
