### ISSUE TITLE
Finalize Mofo-wide colour palette

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#139]
See comment from @kristinashu in teach repo: https://github.com/mozilla/teach.mozilla.org/issues/1386#issuecomment-182601596

**Comment by cassiemc** [comment]
@kristinashu can you take this one?

**Comment by kristinashu** [comment]
Yup!

**Comment by kristinashu** [comment]
Plan is to simplify this colour palette http://blog.seanmartell.com/2014/09/17/mozilla-id-project-palette-explorations/

**Comment by kristinashu** [comment]
Just realizing this palette is the same as Mozilla Unified palette https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLZmJhQ1JKMXpzM2s&usp=sharing

**Comment by cassiemc** [comment]
Yes, same thing

**Comment by kristinashu** [comment]
The unified palette uses opacity to create different tints of one colour. For example, this means this red has three unique # values:. 
<img width="217" alt="screen shot 2016-02-16 at 11 24 02 am" src="https://cloud.githubusercontent.com/assets/1068783/13088125/d5143c60-d49f-11e5-9daa-6e9dc091c624.png">

We are trying to see if we can create one hex value per colour (ex red) and then use LESS to create the different two other tints of that same colour. This will make colors easier to update and create for dev.

@flukeout has created a handy tool to test out the colours http://flukeout.github.io/color-generator/

I've create a redpen using screen caps from the original unified colour palette and then two variations generator using the tool: https://redpen.io/p/ug529d26b3188b0c6c

Next step will be to play around with the tool more to see which variation works best, choosing base vs vibrant, and then test out the selected colours in existing and upcoming real projects.

cc @vazquez

**Comment by vazquez** [comment]
Great :) This approach will also work in Sass, the preprocessor that Foxlight is using.

**Comment by kristinashu** [comment]
Updated redpen https://redpen.io/p/ug529d26b3188b0c6c with an audit of the main colours used in each mofo site and comparing them to the nearest colour from the unified palette.

**Comment by cassiemc** [comment]
Holy shit that's awesome @kristinashu! Super clear what we can do to clean things up. I think we should try this via the teach site (and apply it as we build new, ie the science site). Teach site is our second highest traffic property, and I think will apply the foxlight/cms properties the soonest.

Although we don't support it really, it would be cool to see this for Webmaker.org too, which currently has our highest traffic and would be even easier to update than Teach. /cc @hannahkane @xmatthewx

**Comment by cassiemc** [comment]
@kristinashu What do we need to do next to pin down hex values (or whatever values) to start integrating with foxlight?

**Comment by kristinashu** [comment]
Good question! I think we should start narrowing down some of the colours in the unified palette - choose between base vs vibrant (on a colour by colour basis so we will most likely be a mix of the two). Then continue to explore which colours and Sass values work best for creating different tints.

**Comment by cassiemc** [comment]
Sounds like a fine plan. I'll roll this to the next heartbeat and let's plan to finish this up early next week.

**Comment by kristinashu** [comment]
@cassiemc I've updated the colours, here's the general process I took:

To select base vs vibrant for each unified colour I used @flukeout handy tool: 
- this shows all the unified colours to compare: http://flukeout.github.io/master-template/style-guide/?theme=all-unified-final
- this only contains the selected colours: http://flukeout.github.io/master-template/style-guide/?theme=selected-unified-final

I then took the selected colours and put them in the other tool to determine the 3 other tints for each colour: http://flukeout.github.io/color-generator/

Ink dropped those tints to get the hex values and laid them out in illustrator. Last screen called "Selected colours": https://redpen.io/p/ug529d26b3188b0c6c

We can discuss at crit tomorrow but I think the next step will be for everyone to test out the colours on a project they are working on or have worked on to make sure the colours will work for them and see if we need to make any edits.

**Comment by cassiemc** [comment]
New issues filed for testing @kristinashu's proposal. Those can be tracked with this label: https://github.com/MozillaFoundation/Design/labels/colour

**Comment by kristinashu** [comment]
Thank you everyone who tested out the colors and provided feedback. Here's the updated palette: https://redpen.io/aq798f74c9a3ad7266

<img width="1012" alt="screen shot 2016-03-14 at 1 45 58 pm" src="https://cloud.githubusercontent.com/assets/1068783/13760969/1a4bb14c-e9f3-11e5-994e-44a62e517826.png">

To make the tints more consistent across all colors I've adjusted some of the base tones. Lightened dino red, mobile blue, developer blue, nightly blue, aurora purple and also darkened summit teal. Now all the colors have more consistent tints, particularly noticeable in the lightest tint.

Also lightened the Less value of the darkest tint from -15 to -10

Illustrator file with all the colors:
https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLU01lZEprdGgwTnc/view?usp=sharing

You can load the palette with this .ase file:
https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLUkZaQnlSVHVIT1E/view?usp=sharing

@sabrinang @lovegushwa @natalieworth since you are still in the process of testing the colors please use this updated palette. 

We can discuss at crit but I think the colors should be close enough that perhaps we can implement them in MozMaker and then tweak overtime as issues come up.

**Comment by flukeout** [comment]
Thanks @kristinashu - I took the values from the Illustrator file and plugged them into the theme-o-matic:
http://flukeout.github.io/master-template/style-guide/?theme=theme-march-14

You can click through each of the color dots in the top right to see how they interact. I think this set of colors is much better balanced, and the lightest tones are much more uniform. :+1:

**Comment by kristinashu** [comment]
Thanks @flukeout, I think they're working well!

**Comment by kristinashu** [comment]
I'm going to say v1 is done and close this ticket. If anyone has updates we can open a new ticket for edits.

@vazquez did you add these to onesie? Do you need anything else?

**Comment by vazquez** [comment]
No. We're good :)
