### ISSUE TITLE
Conferences

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#140]
I'd love to go to a conference this year and am looking for suggestions. I started a doc so please add any you can think of. 

https://docs.google.com/a/mozilla.com/spreadsheets/d/1oz7o9tpjklZ-GSOJchPTYlYOOx3EIYPT1JA9NL-IM14/edit?usp=sharing

It might even be nice if we could go to one together!?! @cassiemc @vazquez @lovegushwa @flukeout @sabrinang @natalieworth @xmatthewx

**Comment by lovegushwa** [comment]
@kristinashu great idea! I wont get to this until next week, but lets discuss asap.

**Comment by cassiemc** [comment]
@kristinashu Update? Next steps?

**Comment by kristinashu** [comment]
There are a bunch of conference suggestions so thank you to everyone who contributed. If you're are interested, please put your name next to your favs!
