### ISSUE TITLE
Brownbag for engineers

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#144]
### Issue

cc: @vazquez

**Comment by Ohyewlee** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<map>
<string name="EI">352560074356491</string>
<long name="timestamp" value="1455990989697"/>
<string name="DID">352560074356491</string>
<string name="UTDID">VsiozTBPs6YDAEQHLkb2v1QE</string>
<long name="S" value="2490635226"/>
<long name="t2" value="1455990989624"/>
<string name="SI">452019138756591</string>
</map>
