### ISSUE TITLE
Test colour palette with image-heavy campaign work

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#147]
Test @kristinashu's new colour palette with one of your typical use cases. 

Use this palette: https://redpen.io/aq798f74c9a3ad7266

If you feel the need to make further adjustments to the colours, you can use @flukeout's tint generator here: http://flukeout.github.io/color-generator/ but please do document what changes you made and why.

Let me or @kristinashu know if you have any questions!

**Comment by lovegushwa** [comment]
@kristinashu test of the new color system, some notes in the redpen here:
https://redpen.io/qc0299fd159620e153

Let me know what you think.

ORIGINAL
![color-test2](https://cloud.githubusercontent.com/assets/12228435/13941265/485b9092-efa3-11e5-93fc-61876a972755.jpg)

NEW PALLET
![color-test](https://cloud.githubusercontent.com/assets/12228435/13941268/530a7422-efa3-11e5-874e-62373de1e1b7.jpg)

**Comment by kristinashu** [comment]
Thanks @lovegushwa. I don't think we'll be going back and updating past work. The new palette will be more for future campaigns. Were you thinking of continuing to use the encrypt colors for other campaigns?

**Comment by lovegushwa** [comment]
@kristinashu I think we will try to keep the current advocacy colors for other campaigns, the Red in particular is important. 

I originally created a version of the landing page using Sean's MOCO pallet, but we changed directions to make the pallet a bit less gendered. 

![screen shot 2016-03-28 at 12 18 20 pm](https://cloud.githubusercontent.com/assets/12228435/14087588/9822156a-f4df-11e5-8fdc-29a3125e871a.png)

**Comment by lovegushwa** [comment]
@kristinashu I'm sorry you're waiting on me for this.

I tested the new color pallet with a social share (not comprehensive.) I'm sure we could make something work, but I'm also not ready to ditch the colors we are currently using without a bit more brand exploration (this is coming soon!)

If needed, we should be able to customize the right tool for advocacy. Until we know more about where we're headed with the Advocacy brand, and what tools we need, making a decision about if the pallet works for advocacy or not is premature ... So my request would be, build Onesie in a way we can customize later (colors, type, UI elements etc.) 

@simonwex do you have any thoughts on this? 

![screen shot 2016-04-01 at 4 08 28 pm](https://cloud.githubusercontent.com/assets/12228435/14222474/f5452cac-f825-11e5-8fe1-19e97150ccb5.png)

**Comment by kristinashu** [comment]
Thanks @lovegushwa. Onesie will be a "living thing" that we will build on and adapt overtime. Colors, type and elements will definitely change.

**Comment by lovegushwa** [comment]
@kristinashu cool :)
