### ISSUE TITLE
Test colour palette with social share graphics

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#148]
Test @kristinashu's new colour palette with one of your typical use cases. 

Use this palette: https://redpen.io/aq798f74c9a3ad7266

If you feel the need to make further adjustments to the colours, you can use @flukeout's tint generator here: http://flukeout.github.io/color-generator/ but please do document what changes you made and why.

Let me or @kristinashu know if you have any questions!

**Comment by natalieworth** [comment]
<img width="549" alt="screen shot 2016-03-04 at 3 55 55 pm" src="https://cloud.githubusercontent.com/assets/14876567/13543605/9f553f22-e221-11e5-864e-9711581c0c88.png">
Going to test this on our MozFest site from last year too.

**Comment by natalieworth** [comment]
@kristinashu Closing this and moving colour iterations to @lovegushwa 's ticket #147 for the encryption campaign colour explorations

**Comment by kristinashu** [comment]
Ok sounds good
