### ISSUE TITLE
Test colour palette with illustrations

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#149]
Test @kristinashu's new colour palette with one of your typical use cases. 

Use this palette: https://redpen.io/aq798f74c9a3ad7266

If you feel the need to make further adjustments to the colours, you can use @flukeout's tint generator here: http://flukeout.github.io/color-generator/ but please do document what changes you made and why.

Let me or @kristinashu know if you have any questions!

**Comment by kristinashu** [comment]
@sabrinang I think we can close this. We have v1 of the colors https://redpen.io/aq798f74c9a3ad7266 and we can open a new ticket if problems come up and need to tweak something.
