### ISSUE TITLE
Discussion: How to make projects easier to access for designers + contributors

### ISSUE THREAD

**Issue by vazquez** [MozillaFoundation/Design#154]
## Issue

During the engineer interviews I conducted in an effort to learn how designers and engineers can work more effectively, a theme that emerged was the ease to access and run a repo.

A verbatim that came out of the interview was:

> "Setup is the lowest-hanging fruit in terms of challenges. Even a designer that codes needs help in getting a project set-up. That is a flaw in the engineering perspective. Anyone should hop on a project without needing too much work. Absence of engineering is often a barrier and is not the designer's fault."

I will set up a time to chat with @simonwex about this. Our goal will not be to solve this in a heartbeat. We will lay out strategies to have a sustained improvement of repo access + friendliness.

Some low-hanging fruit to get the ball rolling:
- Better documentation
- Pair with a engineer to get set-up
- Brownbag to teach the very basics of `node`, `npm`, and `package.json`

cc: @cassiemc @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez

**Comment by xmatthewx** [comment]
Things a designer might do: 
 - make a copy change
 - add/update images files
 - test a project for designer review (desktop and mobile)
 - poke at CSS to suggest adjustments
 - others??

**Comment by kristinashu** [comment]
@flukeout seems like the best person to take over this issue but we can chat during/post London
