### ISSUE TITLE
Brownbag to Designers

### ISSUE THREAD

**Issue by vazquez** [MozillaFoundation/Design#155]
### Issue

During the engineer interviews I conducted in an effort to learn how designers and engineers can work more effectively, an idea that emerged was to have a brownbag for designers to get acquainted with technical terms.

A verbatim that came out of the interviews was:

> "There are a lot of words that are different in web than in print design (ie. kerning vs. letter-spacing). There are also a lot of limitations on the Web. Having flexibility with how things are tweaked is important. It's always lovely to work with someone that has even rudimentary technical knowledge. They can speak to the design a lot more. They can also create designs that are really possible to achieve."

A brownbag would be useful for us to get our collective knowledge back to baseline. Maybe this will take more than one brownbag.

Are you unsure of a topic in development that you would like to brush up on? Post a comment in this thread.

cc: @cassiemc @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez

**Comment by natalieworth** [comment]
@vazquez Parameters around type (and web equivalents) would be really helpful (e.g. I'd like to be more familiar with column limitations, kerning, tracking, how to deal with orphans/widows, hyphenations, etc. for web specifically). It seems a lot easier to control type when it's for a static screen or print, but not necessarily web so would be awesome to get a dev's perspective on it to better facilitate communication :)
