### ISSUE TITLE
Design Brownbag to Engineers

### ISSUE THREAD

**Issue by vazquez** [MozillaFoundation/Design#156]
### Issue

During the engineer interviews I conducted in an effort to learn how designers and engineers can work more effectively, an idea that emerged was to have a brownbag for developers to get acquainted with design terms and characteristics:

During our brownbag, we can talk about the following things:
- Show visual nuances that might be overlooked
- Demo the software we use to design
- Show the design process so that engineers can offer more empathy towards a design solution 

Before planning the brownbag, I will talk to @simonwex and come up with a shared list of learning outcomes for the brownbag.

cc: @cassiemc @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez

**Comment by simonwex** [comment]
@vazquez may I suggest as part of this brownbag, we're all given a small design challenge? If we're talking about empathy-building, I think there's an applicable saying about walking 1.6kms in designer shoes and being critiqued. I might be proverbially confused, but you get the idea.
