### ISSUE TITLE
Check Pantone colors for dapper fox patches

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Design#157]
Hi - 

Hoping someone can help me confirm these are the correct colors in the mockup for the dapper fox patches. The green looks kinda 80s neon to me but might be my monitor...

![](http://crm-files.thestudio.com/2016/02/25/P124965.jpg)

cc: @cassiemc @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez

**Comment by vazquez** [comment]
Checked back with My. These colours are not accurate.

These are the appropriate values.

![dapper-fox-patch-colors](https://cloud.githubusercontent.com/assets/1119821/13685972/5c42764a-e6e1-11e5-9731-ccf82d73e053.png)

**Comment by kristinashu** [comment]
@ldecoursy did you get this? Guessing this is good to close?

**Comment by vazquez** [comment]
Yep. Good to close.
