### ISSUE TITLE
[MoFo Unified Design] Create a user guide for program staff

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#159]
Members of program staff and of the community occasionally create curriculum and other assets. While this work falls beyond the scope of work that the design team can create, we should find efficient ways to support the work and elevate its quality. 

The design team can support their work via:
- templates (good for a few, highly repeated things)
- style guide (good for other things)
- invitation to design crit (good for everyone)

Tasks:
1. Reach out to @chadsansing @amirad etc to learn about common design challenges
2. Join Luke's review of Teachable 
3. Create a simple style guide (less is more)_ if and only if_  it seems useful based on conversations above. 
   - Make a plan of stuff this could contain. Review the team
   - Gather contributions from other design team members 
   - Include an invitation to design crit. 
   - Explore options for where to put it and how to share it

cc: @lovegushwa

Comments? Thoughts? Concerns?

**Comment by xmatthewx** [comment]
see https://github.com/mozilla/community-teaching-training/issues/1

**Comment by sabrinang** [comment]
**Update on Progress**

I have completed creating a questionnaire for guiding discussion around Creating for Mozilla Learning Network to learn about current design process, needs and challenges staff/community run into while creating and composing projects.

I’m in the process of conducting these interviews and after these initial chats, I'll revise it to be sent out to broader staff/community members via google form to collect responses. I’ll summarize the insight and findings after receiving more (most likely next heartbeat).

In the meantime, I aim to have the initial structure outlined in a short google slide deck to share by early next week and will continue to evolve as the findings help shape this guide for staff.
