### ISSUE TITLE
[MoFo Unified Design] Create UI toolkit for sites

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#160]
Details coming soon. 
 - universal footer
 - navigation options
 - onesie components
 - colors
 - ????

**Comment by sabrinang** [comment]
I’m planning how to structure these wireframe kits.

**Sketch**
For Sketch, I’m planning to include: 
- Symbols library
- Text Styles 
- Shared Styles
- Layout Settings presets
- Example templates and grids of common pages
- Instructions throughout the document

The structure I'm referencing will be similar to existing sketch/bootstrap resources such as:
- symbol library - http://www.sketchappsources.com/free-source/502-bootstrap3-symbol-library-sketch-freebie-resource.html
- ui kit - http://www.sketchappsources.com/free-source/1448-bootsketch-ui-framework-sketch-freebie-resource.html
or http://bootstrapuikit.com/

**Adobe Creative Cloud**
For Adobe CC products, I'm looking into structuring a kit as a Illustrator file and Creative Cloud Library containing:
- colour (swatches, colour groups)
- character styles
- graphics

.ai or .ait file that has:
- example templates of common pages
- grid and various screen sizes
- instructions throughout the document

I'll continue to look for some good illustrator templates/libraries to reference too.
_________

*NOTE:* The design elements themselves will be added as design decisions are decided from issues labelled with MoFo Unified Design.

**Comment by sabrinang** [comment]
Update: We will be focusing on using Sketch mainly and in addition we can include wireframe versions of components (grey boxes, placeholder text etc.)

**Comment by sabrinang** [comment]
reassigning to sketch master @vazquez to further this effort along!

**Comment by vazquez** [comment]
How is this for a start? We can discuss during critique 😊 

https://drive.google.com/open?id=0ByIoeeW0a3R_OGdsdl82STcyelE

cc: @kristinashu @natalieworth @flukeout

**Comment by kristinashu** [comment]
So fast, thanks @vazquez! I think we could add all the color tints to the Document Colors but this is a great foundation and format to follow. I also like how you've incorporated little teachable moments!

**Comment by xmatthewx** [comment]
I love the speedy tag team effort.

**Comment by kristinashu** [comment]
@vazquez can you please add a link to any other onesie/cms/template type sketch files you have? They might be relevant for some of this work. 

Then we can close this ticket and build the rest out in the individual tickets filed under https://github.com/MozillaFoundation/Design/issues/177
