### ISSUE TITLE
Please reply: Actions on Audit and betterfaster

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#161]
Lots of great work lingering from Cassie's [audits and betterfaster](https://github.com/MozillaFoundation/plan/issues?q=is%3Aissue+audit+label%3Abetterfaster) things. 

Questions for each of you:
- What are some easy wins left hanging?
- What would you be most excited to drive?
- What would make you most sad if it were dropped? 

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez

**Comment by xmatthewx** [comment]
- One step from IA is in the works: moving teach to Learning.  
 - Rest of IA needs an action plan: https://github.com/MozillaFoundation/Design/issues/158

**Comment by natalieworth** [comment]
@xmatthewx 
* Would like to keep working on this in the future when the Mozilla branding is updated next year (https://github.com/MozillaFoundation/plan/issues/684)
* @lovegushwa and I are also going to be brainstorming and working on social for upcoming Advocacy campaigns, so that could even be an area that we could add to better/ faster and audit in order to streamline our social creation process for future campaigns or Foundation work

**Comment by vazquez** [comment]
- _What are some easy wins left hanging?_ Not an easy win, but an important win. Identify shared needs for blogs https://github.com/MozillaFoundation/plan/issues/687
 - _What would you be most excited to drive?_ Streamlining footer designs. https://github.com/MozillaFoundation/plan/issues/686
 - _What would make you most sad if it were dropped?_ Align comms messaging with platforms and audiences https://github.com/MozillaFoundation/plan/issues/694

**Comment by sabrinang** [comment]
:raised_hands: **Easy wins:**
- steamline footer https://github.com/MozillaFoundation/plan/issues/686 
- steamline blogs https://github.com/MozillaFoundation/plan/issues/687 

:sparkles: **Currently working on:**
- board slide process/template: https://github.com/MozillaFoundation/plan/issues/740
- convening asset templates: https://github.com/MozillaFoundation/plan/issues/731

:cry: **Sad to be dropped:** 
- cross comms tickets https://github.com/MozillaFoundation/plan/issues/761
- cross promo https://github.com/MozillaFoundation/plan/issues/755 *(these tickets most likely will be effective when things have settled a bit to crossover)*

:horse_racing: **Excited to drive:** 
- Templating and documenting tickets that are in better faster and tie them together. For example, style guide internal docs: https://github.com/MozillaFoundation/plan/issues/736 can help frame the boardslide/convening template work.

:+1: I am also excited for the development of social media channels foundation wide as @natalieworth  mentioned (but not ticketed in better faster)

**Comment by xmatthewx** [comment]
Thanks for all the replies so far. Above and beyond expectations! 🚵 🗻 🚠

**Comment by kristinashu** [comment]
:smirk:**What are some easy wins left hanging?** 

- Echo previous thoughts: footer, blog, some of the URL structures

:heart_eyes: **What would you be most excited to drive?** 

- Onesie work 

- URL/IA follow up work 

:hear_no_evil: **What would make you most sad if it were dropped?** 

- What we're going to drop something? nooooooo!

**Comment by flukeout** [comment]
**Easy & Good**
* Blog
* Footer

**Interested In**
Assisting with the unified style guide in some fashion. We did a nice audit, now we need to identify and design the common pieces. We've started some of that, or at least a process similar to that, in foxlight - but I'm not sure if we're treating those designs as the beginning of the new styleguide.

**Comment by lovegushwa** [comment]
**Easy & Good**

Setup GA for the sites that don’t already have it:

Not sure what’s been updated here
https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=2008361845

Looks like a X-Ray goggles ticket was started but I don’t know if GA was implemented
https://github.com/mozilla/goggles.mozilla.org/issues/277

Consolidate social channels:

For example not sure we’re using https://twitter.com/mozillaadvocacy
Most of the advocacy tweets are happening here https://twitter.com/mozilla
