### ISSUE TITLE
[MoFo Unified Design] Site nav

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#163]
#### Problem

We have so many different types of nav and a many of them are very responsive
<img width="930" alt="screen shot 2016-05-05 at 2 00 01 pm" src="https://cloud.githubusercontent.com/assets/1068783/15057928/39d5ea56-12ce-11e6-86a1-c1d753f11869.png">
#### Considerations & Decisions

Design a nav to use on the majority of our sites. It will be scalable so it works for simple navs (ex. Goggles and Thimble), to more complex with secondary menu items (ex. Advocacy and Science) to complex with third level menu items (ex. Learning). Nav should be responsive. Elements like logo and account sign in should be found in similar locations on every nav.
#### Following steps

This ticket is to decide as a group:
- [ ] which sites will use these buttons
- [ ] design the buttons
- [ ] design review the buttons
- [ ] add buttons to the Tool Kit
- [ ] discuss implementation with engineers

cc: @sabrinang @hannahkane @xmatthewx

**Comment by xmatthewx** [comment]
One topic to consider – what happens when a page starts to break the length barrier with too much content? For example: https://teach.mozilla.org/clubs

There are likely a few different options:
 - Tabs on the page might make it more approachable. 
 - Main page could link to a subpage that doesn't appear in the nav, but does include a clear way back. 
 - In some cases, additional content could warrant a new item on the subnav
 - Lastly, moar content isn't always more better. Can we shorten copy, reduce info, and optimize for users?

**Comment by kristinashu** [comment]
Another note: it would be nice to make the nav as responsive as possible. This is a good example of it: http://codepen.io/chriscoyier/pen/bppOVP/
It should eventually happen in the science site https://github.com/mozilla/science.mozilla.org/issues/243

Also, if a hamburger menu is needed (ideally we try to avoid one) we could animate it (top right icon): http://tympanus.net/Development/AnimatedSVGIcons/

**Comment by xmatthewx** [comment]
Good to see these references @kristinashu. For our nav and footer and other elements, it'd be good to create demo thimble projects for testing and reference after we have draft designs. Could add some subtle animation.

**Comment by xmatthewx** [comment]
A draft of Leadership curriculum is mostly done. We'll have to think about how a multipage thing like this includes its own nav. https://docs.google.com/document/d/1ovVVKv_TlMxIWkEoHbboXvxq4UYHbmYFX3xtgQ40IJQ/edit#

see: https://github.com/MozillaFoundation/plan/issues/757#issuecomment-215839554

**Comment by hannahkane** [comment]
Can the Web Literacy curriculum be a model for this?

**Comment by kristinashu** [comment]
Moved to https://github.com/MozillaFoundation/Design/issues/241
