### ISSUE TITLE
[MoFo Unified Design] Site Footers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#164]
#### Problem

We have so many different types of footers.
<img width="861" alt="screen shot 2016-05-05 at 2 00 21 pm" src="https://cloud.githubusercontent.com/assets/1068783/15057887/fcf68a3c-12cd-11e6-9a89-81f0585e4ed7.png">
#### Progress

We are designing unified site footers across our properties. Please see below on the progress so far:

**Colour:** Charcoal (Lightness -30) #2F2F30 for background
Charcoal (Lightness 30) #C7C7CA for text and 50% opacity for icons and icon text
White #FFFFFF for links and wordmark
**Type:** Fira Sans
**Icons:** from upcoming https://github.com/flukeout/mozmaker-icon-font
![mofo-unified-design_footer](https://cloud.githubusercontent.com/assets/2492510/14653637/bb0524fe-062e-11e6-8371-893b8b910b13.jpg)
#### Considerations & Decisions

Work on responsive versions (tablet, mobile)
What links do we include?
What content do we include?
Legal and localization considerations?
#### Related Issues

Initial ideas, insights and benchmarks: https://github.com/MozillaFoundation/Design/issues/42 
Decision of where site footers are applied: https://github.com/MozillaFoundation/plan/issues/686
#### Following steps

Decide as a group that this will be that standard across properties. Documentation and implementation will follow afterwards.

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez @xmatthewx

**Comment by xmatthewx** [comment]
We will want to loop in @KevZawacki and maybe someone from MLN to help shape the description on the footer. Could include links between our top-level sites. @KevZawacki took a stab at this here: https://github.com/MozillaFoundation/plan/issues/761#issuecomment-197420728

**Comment by lovegushwa** [comment]
@xmatthewx @sabrinang it would be great to have an option without footer text as well.

Codemoji is a great example of a situation were we needed (and created) a simplified footer:
<img width="1692" alt="screen shot 2016-05-04 at 12 16 30 pm" src="https://cloud.githubusercontent.com/assets/12228435/15026217/35121f12-11f2-11e6-929a-42eccdc0df65.png">

**Comment by lovegushwa** [comment]
@xmatthewx @sabrinang a couple small notes on the design:

> Would be nice if the vertical line on the desktop version of the footer aligned with the top and bottom of the text block. 

> We should consider making the "mozilla.org" link a little more subtle. Also, I assume the mozilla logo to the left links to mozilla.org as well?

> We will need to change the links depending on context. For example advocacy wont need a IRC link.
How can we make changes / different link options easy to implement?

![bb0524fe-062e-11e6-8371-893b8b910b13](https://cloud.githubusercontent.com/assets/12228435/15026269/76d34476-11f2-11e6-9e37-89d6129b2f34.jpg)

**Comment by xmatthewx** [comment]
Sounds good. Let's include a few variations in a single comp file. This year, these footers are unlikely to draw from a single coded implementation, so we just need to enable variations design-wise, not tech-wise. Consistent patterns, not rigid rules.

**Comment by xmatthewx** [comment]
We should start linking to Chat rather than IRC for all the sites. Much easier entry for new people.

**Comment by kristinashu** [comment]
We have an implementation ticket for this https://github.com/mozilla/mofo-bootstrap/issues/92
