### ISSUE TITLE
[MoFo Unified Design] Form fields

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#165]
#### Problem

We have so many different types of form fields
<img width="941" alt="screen shot 2016-05-05 at 2 00 37 pm" src="https://cloud.githubusercontent.com/assets/1068783/15057793/883f5bb0-12cd-11e6-86b5-8f5e94d31576.png">
<img width="777" alt="screen shot 2016-05-05 at 2 00 46 pm" src="https://cloud.githubusercontent.com/assets/1068783/15057794/883fcce4-12cd-11e6-9c2b-68f142a6b4b9.png">
#### Progress

We need to design form fields to use on all of our sites. Our starting point is bootstrap http://v4-alpha.getbootstrap.com/components/forms/

I've made some minimal tweaks to it for science: https://redpen.io/dq01e5e243a5cd0634

We will need someone to take this on more in depth to explore other options, make sure it will work for all the sites, add error and active states.
#### Considerations & Decisions

Accessibility, different responsive sizes, errors and validation, email signups...
#### Following steps

This ticket is to decide as a group:
- [ ] which sites will use these fields
- [ ] design the fields
- [ ] design review the fields
- [ ] add fields to the Tool Kit
- [ ] discuss implementation with engineers

cc: @sabrinang

**Comment by sabrinang** [comment]
Updating forms for teach as well using full width field and checkbox structure: https://redpen.io/cg7a422f47a656dd0e

**Comment by sabrinang** [comment]
A progress bar can be considered along with the form fields for long, sequential forms. Example from the Club Captain application form (https://github.com/mozilla/teach.mozilla.org/issues/1822)
<img width="948" alt="screen shot 2016-05-05 at 1 41 23 pm" src="https://cloud.githubusercontent.com/assets/2492510/15056591/33be7ee6-12c7-11e6-8d6c-d7a460b96526.png">

**Comment by kristinashu** [comment]
New ticket https://github.com/mozilla/mofo-bootstrap/issues/93
