### ISSUE TITLE
Consider Design of moz.org/foundation page

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#167]
At some point, we should take a look at the mozilla.org/foundation as an opportunity to tell a unified story about our Advocacy and Leadership Hubs work. Work here could help inform our tiles on the landing page. Filing here to remind us. 

cc: @kristinashu @lovegushwa @hannahkane

**Comment by lovegushwa** [comment]
@xmatthewx we could / should start a conversation with MOCO brand folks since they own the property. I'm not sure if they will have much to say about this yet, but I can surface it.

**Comment by kristinashu** [comment]
I think this was done https://www.mozilla.org/en-US/foundation/

Please reopen if need be.
