### ISSUE TITLE
Game plan for Universal Mofo Styles

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#168]
Make a slide deck to gather our thoughts, make sure we're on the same page, and to come up with a game plan. For now, we will focus on websites and products (excluding social media and print assets).

Below are some things the deck could cover with some initial thoughts:

### Why should we have a universal mofo style?
 - [design audit](https://docs.google.com/a/mozilla.com/presentation/d/13v_Rr2ypxscqSZWksLAzc5TZ8NRy0MuGSP9yK-FEKFo/edit?usp=sharing)

### What's the goal?
- gain clarity and a sense of shared ownership, so we can enthusiastically, intuitively, and consistently leverage the tool.
- steer the tool so it's useful for many use cases
- optimize it for engineering, design, and audience
- lead the web toward a better web!
- make it easier for contributors to contribute

### Who does it affect?
- Learning
- Science
- Advocacy
- Templates

### Who does it not affect?
- Campaigns
- Old sites
- Special unicorns

### What does it effect?
- Footer *
- Icons
- Buttons!
- Nav patterns
- Font/Header standards
- Forms
- email sign up
- Grid
- Type
- blog
- sign in – this will be replaced with a single Mozilla wide solution

### How will it be implemented?
- site tool kit
- design review for components
- onesie
- iterative

### When will it be implemented? 
- is this just an interim brand and how does it fit in with upcoming moco brand?

### List of actionable tickets

cc: @sabrinang @xmatthewx

**Comment by xmatthewx** [comment]
[comms audit](https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=2008361845) for reference

**Comment by kristinashu** [comment]
It's very rough but I'm slowly adding thoughts into a deck https://docs.google.com/a/mozilla.com/presentation/d/1fDZKei9hlHOjp3mjD5FbFYRPDB01ryUxz9iLjY92QVY/edit?usp=sharing

**Comment by kristinashu** [comment]
Jamming with @sabrinang on this. Plan to share with design team at our Tuesday triage. 

cc @hannahkane for resourcing, it would be great to start building out the assets next heartbeat.

**Comment by kristinashu** [comment]
Linking:

https://github.com/MozillaFoundation/Design/issues/161 - what designers are interested in working on and what are the quick wins.

https://github.com/MozillaFoundation/Design/issues/160 - high level creating sketch tool kit

https://github.com/MozillaFoundation/Design/issues/159 - user guide work

**Comment by hannahkane** [comment]
Yup. As discussed, please identify a few tickets for the May 20th heartbeat, and we'll discuss at a kickoff meeting next week (to be scheduled).

**Comment by kristinashu** [comment]
Discussed with design crew and both Simon and Gavin. We are all in agreement that the key to this will be communication between design and engineering. We will attend each others weekly meetings and also have dedicated regular check-ins with the core drivers.

Deck: https://docs.google.com/a/mozilla.com/presentation/d/1fDZKei9hlHOjp3mjD5FbFYRPDB01ryUxz9iLjY92QVY/edit?usp=sharing
