### ISSUE TITLE
Low Resolution on Thimble Sticker

### ISSUE THREAD

**Issue by jamjwait** [MozillaFoundation/Design#169]
### Issue
I just tried ordering a variety of stickers from Sticker Mule using the templates saved in the [swag folder](https://drive.google.com/open?id=0BzfN9sXlOXt1SG9wVDY5TzdLUWs), but ran across an issue with the Thimble sticker. 

For the Thimble sticker, I sent both the design template in the swag folder as well as this [.png file](https://drive.google.com/a/mozilla.com/file/d/0B5jxGZykGTyFVkcxR2U2d3pUS0k/view?usp=sharing) after they came back initially saying they needed a higher resolution image. 

Sticker Mule says the background of the image appears to be low resolution and asked if we could save a version of the design with the background as vector art as well? 

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez @xmatthewx

**Comment by kristinashu** [comment]
@jamjwait I've updated the sticker so now the background pattern is vector and will work at any resolution. Here's the link https://drive.google.com/open?id=0B2irLVDJivhLMHltX2I1MlpqbGM

Let me know if you have any trouble with it.

**Comment by vazquez** [comment]
Thanks so much @kristinashu!

![popkey](https://m.popkey.co/a736e5/K0YkG.gif)

**Comment by jamjwait** [comment]
Thank you!
