### ISSUE TITLE
Is it possibe/desirable to localize the Goggles FTU images?

### ISSUE THREAD

**Issue by chadsansing** [MozillaFoundation/Design#170]
### Is it possibe/desirable to localize the Goggles FTU images?

Use case: 

The web literacy team is running a training for the rp6 veterans' group on June 1st and 2nd. We plan to include the Goggles FTU as part of the agenda. Is it possible/desirable to create a customized/localized version of the activity featuring stylized service uniforms or service members?

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez @xmatthewx & also @anmechung @edrushka @jvallera @carot @hannahkane @ldecoursy @Pomax

**Comment by xmatthewx** [comment]
Given our busy schedules between now and London, I suggest that we split this ticket into: 
 - [ ] Design illustration and use X-ray Goggles to remix FTU page with content that veterans group can remix (without FTU experience). This could be a nice p2 project for a designer (should be limited to a half day or two).
 - [ ] Discuss: Can/should we support multiple FTU experiences? If so, do FTU pages need to be bespoke? Or, could any page be FTU-ized with a little JS?

Bespoke FTU pages should be evergreen for a broad audience. FTU-ization, on the other hand (if possible), could power many small disposable FTU experiences.

**Comment by chadsansing** [comment]
Agreed. I can consult on the former, participate in the latter.

**Comment by Pomax** [comment]
Could? yes. A little? No. It would take considerable work, since the goggles pages were never set up for localization. Especially the images will be a ton of work (regardless of whether we'll generater "a lot of images" or rebuild them without text and then render them as img-background + overlay text)

**Comment by chadsansing** [comment]
Maybe a Thimble homage would be better?

**Comment by hannahkane** [comment]
I'll file a P2 ticket for the custom illustration, and we'll see closer to the end of this heartbeat if we can fit it into the next heartbeat.

Will leave this ticket open for further discussion of the bigger localization/FTU-ization question. Would love to formulate a specific problem statement, as well as more on the value (i.e. other use cases we imagine) so we can determine if it outweighs the effort and how it compares to other projects in the pipeline. 

The problem statement might be something like, "The FTU activity is targeted towards a specific audience, and can be off-putting when trying to engage a different audience."

**Comment by hannahkane** [comment]
Opened a ticket in the Goggles repo: https://github.com/mozilla/goggles.mozilla.org/issues/294
