### ISSUE TITLE
Tame that wily Fox – or not?

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#171]
We have a SRSLY dapper and wily fox on our hands. Remixed for a few different Mozilla purposes, everyone wants a slice of our illustrated fox. New instances of use by staff and community continue to appear. (Kudos to you designers!)

To tame this fox, we need to: 
- prepare an all MoFo email on the fox and why remixes might dilute the brand
- add that statement to the style guide

@lovegushwa – want to take a stab at a first draft or outline? 

**UPDATE**: More foxes appear. Maybe we should run with this. See below.

**Comment by xmatthewx** [comment]
Another fox emerged. This one from the wild. "It was done by a high school senior who was inspired by the research fox!!" https://www.instagram.com/p/BFhtGwRS7Qn/

Instead of resisting this, maybe we should encourage it. 

@flukeout – Maybe we need an online fox maker tool. To keep things fairly well aligned, stay aware of when they're made, and be able to promote successful instances. 

@lovegushwa @kristinashu @sabrinang @natalieworth @flukeout @vazquez

**Comment by natalieworth** [comment]
Ah so cool!

**Comment by xmatthewx** [comment]
The tool could include a bunch of items of clothing and props for people to mix and match. Paper doll style. Maybe visitors could request new items or submit proposed item designs.

**Comment by sabrinang** [comment]
I think that we can unleash the fox (and tame it a bit) by documenting it in a way that octocat has approached has (https://octodex.github.com/) by providing some context, curation and disclaimers if adaptations of the fox keep appearing in the wild. I think we can turn its popularity to promote our presence in a deliberate and positive way. The community chooses what they love so and I think the fox isn't going away anytime soon!

**Comment by xmatthewx** [comment]
That's a great reference @sabrinang. The stream and the FAQ.

**Comment by natalieworth** [comment]
Paper doll style would be great if people want to contribute new items. Kind of similar to https://www.powerpuffyourself.com/#!/en

**Comment by auremoser** [comment]
+1 to paperdoll-style-your-self for viral twitter versioning.

**Comment by xmatthewx** [comment]
@ldecoursy shared a dozen or so people's thoughts on what an education or learning fox might look like. Reposted here: https://public.etherpad-mozilla.org/p/education-fox
