### ISSUE TITLE
[MoFo Unified Design] ToolKit

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#177]
This is a ZenHub 'epic' ticket that will be the parent ticket for all the Toolkit components.

This ticket will have the latest Sketch file everyone should work off of and any high level instructions: based on https://github.com/MozillaFoundation/Design/issues/160
https://drive.google.com/open?id=0ByIoeeW0a3R_OGdsdl82STcyelE

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez @xmatthewx

**Comment by sabrinang** [comment]
Note: for upcoming Mozfest site work, consider a review of last year's site for UI toolkit opportunities

**Comment by kristinashu** [comment]
We will be using Invision's Craft https://github.com/MozillaFoundation/Design/issues/211
