### ISSUE TITLE
Organize our drive folder

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#183]
We need to clean and sort out our drive folder, again. We all need to make sure our files are in there so everyone can access it. We also might need to rethink the Assets folder which has become out of date.

This will also prep us to create one folder we can easily share with community members, other staff, and contractors that contains everything they'll need to start a project. 

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @xmatthewx

**Comment by xmatthewx** [comment]
A couple thoughts as I searched for where to put the new Hive Austin logo. 

1. Will a file likely be used again in 6 months or later without modification? 
 - Yes => Assets
 - No => Projects

2. Within each, I propose we follow the new org structure. 
 - Advocacy
  - Evergreen
  - Campaign
 - Leadership
   - Hub name (e.g. Learning)
     - Program name (e.g. Hive)
 - Insights
 - Ops

3. Within Projects, we could have a top level folder for each year. We can move things from 2016 to 2017 if that project pops up again. 

4. Each folder should have a Misc folder for things that feel like they belong there, but also don't feel very important. Reduce messiness. 

Curious what y'all think.
