### ISSUE TITLE
Learn how to do commits in Github

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#185]
Based on https://github.com/MozillaFoundation/Design/issues/178

Since we're going to use Github for version control of our Sketch Toolkit/Template file we are all going to need to learn how to do pushes and pulls in terminal (hope that's the right terminology). Although some designers already know how to do this, I think it would be a great opportunity to reach out to a dev to teach us, brow bag style.

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @xmatthewx @simonwex

**Comment by xmatthewx** [comment]
You might use this as a test of the leadership curriculum, and then contribute a set of git recipes for common scenarios. 

If we have any open elective time in London, it can be nice to do these things in person. Resolving set up issues remotely is a beast.
