### ISSUE TITLE
Migrate Design page to new build site

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#186]
The former Build site is broken, menu link to design page doesn't work. 

Let's revive this page soon for recruitment of a new designer. Could be as a Github page on this repo or within Matt's new site. We can update content and redesign later. 
- View page: https://build.mozillafoundation.org/design
- Grab content: https://github.com/mozilla/build.webmaker.org/blob/master/app/components/design.jsx

**Comment by xmatthewx** [comment]
assigned to @flukeout

**Comment by xmatthewx** [comment]
Page migrated without the flair. http://mofo.build/design/

**Comment by flukeout** [comment]
I would suggest giving the public at large 'read' access to our Google Drive folders. Without that, many of the links on that page won't work for contributors.

Anyone see any issues with that?

cc @xmatthewx @kristinashu @sabrinang @lovegushwa @natalieworth

**Comment by xmatthewx** [comment]
Yes for general assets folders. Project folders could have sensitive info, but could be open to all in the Moz org. Thanks Luke!!!!!!
