### ISSUE TITLE
Assist with production of "Open Project" presentation/video.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#188]
@zee-moz has created a storyboard for a presentation - [Ingredients of an Open Project](https://drive.google.com/open?id=0BytjEIvMn7SRTzZNNjJrZWhjeE0) - and wants some help creating a polished version that might also include some sound.

We're meeting in the next few days to discuss her specific needs and figure out ways that I or the design team can help out.

![image](https://cloud.githubusercontent.com/assets/25212/16780782/03c4b2aa-482d-11e6-9987-2065a3e20f28.png)

**Comment by flukeout** [comment]
Based on our meeting, here's a list of action items...

* Figure out what kind of formats are embeddable within Teachable content
* Benchmark and compare existing tools & processes for creating presentations and videos
  * Keynote (with export to video)
  * Presi
  * ...others?
* Define and estimate an in-house tool for creating this type of content
  * What are the basic features of the tool
  * How much time will it take to build & maintain
* Create a list of graphics, guidelines or templates required by the Science team to create content like this down the road
  * This will be needed no matter what the ultimate solution for creating the content will be
  * Once we have the list, we can estimate & assign the work as needed
* File an issue for helping create the final version of the _Ingredients of Open_ video listed above

...i'll file issues for these.

cc @zee-moz - did I miss anything?

**Comment by flukeout** [comment]
Adding a reference doc - [Intro to Mozilla Study Groups](https://docs.google.com/document/d/1bn_qNfDLH6lfGqsSyz3QXCSvxW7crjDg33Z7nY7x_NU/edit) - some of this content will be turned into this new format.

**Comment by flukeout** [comment]
Via @zee-moz - also create graphics for a project and how it changes when other people run with the idea.

**Comment by flukeout** [comment]
Okay - plan is to create a rough storyboard that accounts for the type of assets and animations that we might use. Based on this, I'll work with @natalieworth to estimate the production time and move forward.

**Comment by flukeout** [comment]
I broke down the video into the necessary screens and outlined some of the illustrations and animations each screen would need. We'll also need to create transitions between each screen.

**Additional Considerations**
* We might want a voiceover that goes along with the video
* We'll need to add text to the video for each section
  * This will need to transition in and out
* Total length of Zannah's storyboard is 1:16

**Intro**
![image](https://cloud.githubusercontent.com/assets/25212/17072494/96fa3d4a-501d-11e6-9d0e-56efa06e0f0e.png)

* Illustration - lightbulb that acts as metaphor for an idea
  * Might include both an off and an on state
* Animation - light bulbs pops in and is then turned on

**Leader**
![image](https://cloud.githubusercontent.com/assets/25212/17072513/b3fdee0a-501d-11e6-985a-419920273180.png)

* Illustration - a figure for the Leader
  * Miner with a hardhat & pick?
  * Other ideas? An accessory from the research fox?
* Animation - leader pops in

**Wild contributors have appeared**
![image](https://cloud.githubusercontent.com/assets/25212/17072531/d766911c-501d-11e6-9f1d-0ccd06a0bc9f.png)

* Illustration for individual contributor
* Animation for a contributor appearing (with a little pop)
* Illustration for "community" - circle around group of community members
* Animation for the circle.. maybe drawn in

**More communities forming**
![image](https://cloud.githubusercontent.com/assets/25212/17072542/fe273a68-501d-11e6-8187-5e31c0e45cfc.png)

* Animation - View zooms out to show new groups of contributors appearing and community circles are drawn in around them

**Connections between communities**
![image](https://cloud.githubusercontent.com/assets/25212/17072550/0f59ef4c-501e-11e6-9730-b63177d26044.png)

* Illustration - lines that connect the groups
* Animation - dotted lines come in one point at a time to form connection

**Roadmap**
![image](https://cloud.githubusercontent.com/assets/25212/17072559/26e5c172-501e-11e6-8b4d-89d68d6ebbdd.png)

* Illustration - roadmap with signposts along the way
* Animation - road is drawn in and signposts pop in one at a time

**Checklist**
![image](https://cloud.githubusercontent.com/assets/25212/17072564/3b65fc98-501e-11e6-97bf-e74b8e05b3cd.png)

* Illustration - generic bullet points and checkmarks
* Animation - they appear one item at a time and are then checked off before the screen transitions

**Workflow**
![image](https://cloud.githubusercontent.com/assets/25212/17072584/53dbdc34-501e-11e6-9857-b95d73568dd9.png)

* Illustration - Github logo
* Illustration - line that connects communities to Github
* Animation - communities pop in one by one  
* Animation - lines are drawn one by one

**Mentorship**
![image](https://cloud.githubusercontent.com/assets/25212/17072602/77d03806-501e-11e6-8be2-265523c12590.png)

* Illustration - speech bubbles with some kind of non-word content
* Animation - bubbles pop in one at a time, maybe facial expressions change based on exchange?
  * Questions marks hover above heads of contributors, but are turned into new ideas after?

**Welcome Banner**
![image](https://cloud.githubusercontent.com/assets/25212/17072625/a033fe0e-501e-11e6-9c5c-f37041bbedb5.png)

* Illustration - Welcome banner
* Animation - Banner unfurls and contributors pop in one at a time to create a little crowd

**The End**
![image](https://cloud.githubusercontent.com/assets/25212/17072638/b5189564-501e-11e6-8d46-c93cce2c9eaa.png)

* Animation - this idea lightbulb grows in intensity or power to indicate that the reach of the idea is increasing.

**Comment by zee-moz** [comment]
Luke, this is awesome! A couple thoughts...
A few reviewers for the training series have commented on the video outline. The main feedback is that it doesn't quite get at the idea of sharing and community contribution. 
So, can we include: 

- a moment where we show the idea of designating idea for sharing with a license (w/ checklist, roadmap)
- a way of showing how contributors add to and change the project  (maybe thought bubbles from contributors showing lightbulb shape, color, base design, etc, that get incorporated into the lightbulb icon)?  << let me know if this makes sense at all!

**Comment by flukeout** [comment]
For reference & considerations, current science icons are taken from (& inspired by) https://www.iconfinder.com/bloomua

**Comment by xmatthewx** [comment]
Very nice work @flukeout 

Down the line, it could be interesting to look at the state of localized captions in videos. Might be an easy win for this.

**Comment by flukeout** [comment]
@zee-moz Will there be additional narration beyond what is already displayed in your storyboard? Is the text that is displayed in the storyboard roughly in it's final form?

**Comment by flukeout** [comment]
Probably also need some kind of closing slide with some contact details or links.

**Comment by zee-moz** [comment]
@flukeout-- the text isn't final-- just a rough approximation of what might be in the VO. I hadn't thought of it as captions or subtitles, actually. But it will help with comprehension to have onscreen text. Would you want to animate to VO and add screen text after, or vice versa?

**Comment by flukeout** [comment]
@zee-moz I'll check with @natalieworth about what a good process is and let you know. My guess is that we'll want a voiceover first, as it will affect the timing of the video transitions. 

I'm not sure about the text there myself, it might be easier if we don't include it. I think that would make localization a bit easier, someone would just have to do a new voiceover. As matthew, suggested maybe we can use the caption feature in Youtube (for example) to add the text in. If so, we'll leave blank room at the bottom of the video.

Anyway, I'll check back in shortly.

**Comment by flukeout** [comment]
Putting this here for later - the Advocacy team has used [Voicebunny](https://voicebunny.com/) for some of their video voiceover work and has been satisfied with the results.

**Comment by flukeout** [comment]
@hannahkane @zee-moz After chatting with the advocacy team about their video work, we estimated that this video would take about 3 weeks of one person's time to produce. That is assuming a pretty high level of polish and finish.

Let's discuss some options tomorrow for how best to tackle this work.

**Comment by zee-moz** [comment]
@hannahkane @flukeout did you want to jump on a call to discuss? I am free this afternoon!

**Comment by flukeout** [comment]
Let's jump on a call tomorrow. In the meantime...

* @zee-moz, can you start work on the final script?
  * Once we have that, we can figure out how best to approach recording it.
    * In house? 
    * Hire a voice actor via Voicebunny or other service?
* I'll start working on some of the illustrations, we can figure out and sign off on the visual style for this

Once we finalize the look and feel of the video & have the final recording we can start putting it all together. The three week estimate assumes a very high level of polish and rich animations, so we'll have to scale down our expectations.

**Comment by flukeout** [comment]
Additional screens, as mentioned by @zee-moz 

**Community Contributions to Project**
![image](https://cloud.githubusercontent.com/assets/25212/17185974/25722bbe-53e8-11e6-9618-ef3b522b9c99.png)

* Illustrations
  * modifications and add-ons to the 'idea' lightbulb
  * Thought or speech bubbles
* Animations - one by one, each contributor will have an idea, and that idea will be incorporated into the main idea lightbulb

**Adding a license**
![image](https://cloud.githubusercontent.com/assets/25212/17186022/59506036-53e8-11e6-87a6-2b20175a5bda.png)

* Illustrations
  * Creative commons license icons
* Animation - several of the aspects of a CC license will show up, and a few of them will be then enabled one by one

Does this seem about right @zee-moz? Curious if the license one gets the right point across or if it's too specific. Should we maybe instead show a choice between a few different license types instead of just focusing on CC?

**Comment by flukeout** [comment]
First pass at the imagery from the sketches...

![image](https://cloud.githubusercontent.com/assets/25212/17195974/28ae7ebc-5416-11e6-9ef3-460158eca2e6.png)

**Comment by natalieworth** [comment]
Love the first version, but I agree the second could be better if more videos have to be created. If you want to make them more 'illustrative' vs. iconographic, you could add some colours/ shading like in the first example? Or even gradients/ textures could be something that would be easily reproducible in illustrator/ after effects for future? The icon/ line version could also probably be animated a lot quicker.

**Comment by flukeout** [comment]
Thanks for the feedback! I'll iterate a bit on Option 2 with some color & textures.

**Comment by sabrinang** [comment]
+1 to Natalie's feedback too
I enjoy the second "Line-y" direction as it may be more easy to replicate the style and simplicity for production purposes too. For the line art that represents leaders and contributors, they may be a bit too abstract but I enjoy the minimal aesthetic. I think minor adjustments like adding eyes (more obvious faces) and if it is supplemented with voice overs it should be more obvious as a whole.

**Comment by xmatthewx** [comment]
Agreed, but oh my the first version is so good. Maybe worth sharing on wake.io.

**Comment by zee-moz** [comment]
@flukeout  OK, I've revised the script for this little video, per OLTS reader feedback.  I don't believe the assets have changed, but maybe there's some additional configurations here.

@acabunoc please review and comment!

**_An open project starts with a great idea or vision for something cool to make or build… 
And an intention to share that idea and the process of building it freely, under a license that allows anyone to join the project, and to use and reuse what’s made.
The great idea attracts people… we’ll call them contributors… who pitch in to help bring it to life. 
These contributors form a community, using the world wide web to connect and work together.
The community drives the project and shapes the idea, making it better and better.
A project lead guides the process along by helping the contributors plan and collaborate… 
by mentoring new members and growing the community…
and by organizing awesome events for contributors.
Because the idea, the process, and the work are all shared openly on the world wide web, the project is free to spread…
An open project doesn’t just change the world… 
It also can be changed BY the world, remixed and reused by lots of different communities, in unexpected, amazing ways!_**

**Comment by acabunoc** [comment]
Nice @zee-moz! Yes, I think this conveys "working open" and the community aspect a bit more. 👍

**Comment by flukeout** [comment]
Thank you @zee-moz!  Next, one of us should record a first pass so that we have an audio track to work from. The quality doesn't matter, but the pacing should be what we expect for the final version. This will let me start doing some animations.

Are you up for it? Should we flip a coin?

**Comment by zee-moz** [comment]
@flukeout, I can do it, but probably not until late tomorrow-- if it's
going to hold you up, please give it a shot! Otherwise I'll do it tomorrow
afternoon. Thanks! Z

**Comment by flukeout** [comment]
Nope, that will work!

**Comment by flukeout** [comment]
Just wanted to leave an update here with what I think will be closer to the final art-style for the video. It's a bit of a hybrid of the first two approaches with some color...

![image](https://cloud.githubusercontent.com/assets/25212/17531911/ddd132d2-5e32-11e6-80d9-3edf6c8aa400.png)

Up next, I'll refine some of these with feedback from the team and do a quick animation test to go with Zannah's recorded script.

**Comment by zee-moz** [comment]
@flukeout  I love how you've combined these styles! The line weights and the shading looks great.
Did you have a version where the contributors had eyes?  The contributors in option 1 had a bit more personality and movement, now that they're pushed a bit more towards abstract option 2, I'm wanting them to feel more lively, I'm wanting to connect with them by looking in their little eyes.

**Comment by flukeout** [comment]
Eyes incoming shortly :D

**Comment by flukeout** [comment]
Awwwww...

![image](https://cloud.githubusercontent.com/assets/25212/17536122/adc796ac-5e47-11e6-9fc8-1b99c1e20c45.png)

**Comment by zee-moz** [comment]
@flukeout Looks awesome!!! Love these guys.

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/17608226/d6750be0-5fdf-11e6-9750-a9b9bc4adb60.png)

**Comment by flukeout** [comment]
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/SWU0fLixris/0.jpg)](https://www.youtube.com/watch?v=SWU0fLixris)

**Comment by zee-moz** [comment]
@flukeout! I got pulled on to other Science-y things, so I'm sorry for the slow reply on this video test.

I LOVE how this looks. I'm really really excited! I think this will be awesome in the OLTS but also widely shareable to get people to understand open projects in 2 minutes.  @xmatthewx @hannahkane @secretrobotron @kaythaney thoughts?

**Comment by secretrobotron** [comment]
Small update: met with @kaythaney about plans leading up to and after Mozfest. Will clear up with her and post here.

**Comment by natalieworth** [comment]
I created a rough brand google slide deck to share with our 2 video and animation contractors:
https://docs.google.com/presentation/d/1GwevZrxlS6N7U0scTdrsYNdcDoYGJXGAs7tgkcr4UQs/edit#slide=id.gd58133b56_0_69

The brand imagery seems to need to be flushed out a bit more (and I think that will hopefully come in March)—so the above deck is a draft.

**Comment by natalieworth** [comment]
Final video here https://drive.google.com/file/d/0B-9OH_KgSSPxQ1RWMmFtMGpWc1U/view
