### ISSUE TITLE
[MoFo Unified Design] Language Picker

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#189]
#### Problem

As we are localizing our properties across MoFo and we need to design a language/locale UI that will inform users what language they are currently seeing, see available languages, change languages or contribute their language to mozilla's localization effort.
#### Progress

Progress so far is seen on thimble.mozilla.org 
![screen shot 2016-07-12 at 11 43 56 am](https://cloud.githubusercontent.com/assets/2492510/16779253/3de9b2de-4826-11e6-9787-098443634b2a.png)
![screen shot 2016-07-12 at 11 44 11 am](https://cloud.githubusercontent.com/assets/2492510/16779252/3dd64c8a-4826-11e6-80f0-14712b734231.png)
#### Considerations & Decisions
- how we use can invite more contributors to help with this UI
#### Following steps
- [ ] Research use cases/best practices
- [ ] Benchmark examples of locale pickers
- [ ] Decide which sites would use this

This ticket is to decide as a group:
- [ ] Design picker UI
- [ ] Design review 
- [ ] Dev/Implementation review
- [ ] Add to Toolkit
#### Related Issues

https://github.com/mozilla/learning.mozilla.org/issues/1960
https://github.com/mozilla/learning.mozilla.org/issues/1934
https://github.com/mozilla/thimble.mozilla.org/issues/1335

**Comment by xmatthewx** [comment]
Excellent. I'd like this to include recommendations or guidelines on when a language should be used. For logged in users, language is usually a preference, not a persistent UI element taking up valuable real estate.

**Comment by sabrinang** [comment]
Overview of ideas (ideas in context on [redpen](https://redpen.io/p/mte5a684e364f3a1bb))
- left-aligned menu items: if menu items are aligned to the left we can have language displayed in line on the right
- center or right aligned menu items:  if menu items are aligned center or right we can make the height of the heading slightly taller and fit language on the upper right
- in response to @xmatthewx comment above when we think about users that logged in, language can be a preference that appears within the dropdown and not as persistent UI
- when users are logged in we can greet them in their language so it is showcase "Hello, Tim! Bonjour, Tim! 你好, Tim! etc..."
- we can have a popover style alternative of choosing languages if drop downs are not preferred
![mozilla-learning_localization-cta-02](https://cloud.githubusercontent.com/assets/2492510/16887834/4a659772-4a91-11e6-9318-4350325f642d.png)

More to come for recommendations or guidelines on when a language should be used as and I am also brainstorming about footer and mobile ideas of how language appears there too.

**Comment by sabrinang** [comment]
More recent examples of language pickers:

**mozilla.org footer**
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/2492510/34893919-2a6bcfd4-f794-11e7-8334-7d1c6f97766c.png">

**internet health report prototype footer**
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/2492510/34893948-3f70167e-f794-11e7-9624-47747dbe7837.png">

**Comment by kristinashu** [comment]
Closing this since we don't really have more than one language pickers anymore.
