### ISSUE TITLE
Create or assist with assets for Ingredients of Open Projects video

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#190]
@zee-moz has created a storyboard for a presentation - [Ingredients of an Open Project](https://drive.google.com/open?id=0BytjEIvMn7SRTzZNNjJrZWhjeE0) - and wants some help making it look better.

Required assets
- Contributor
- Idea 
- The internet
- Laptops
- Connection between things
  - Like arrows between contributors
- Representations of 'practices'
  - Project roadmap
  - Project checklist
- Speech bubble

Screen Templates
- Title screen
- Section title screen
- Content screen
- Final screen

**Comment by zee-moz** [comment]
@flukeout, glad you're going to make this awesome, per conversations with @hannahkane:

Here are some things that I also wanted to show but didn't have the time or skill to do so: 
- representations of workflow, shared work, conversations, exchange
- representation of mentorship
- representations of events or gatherings suggest interactivity and productivity

please, if you feel like you can find better, more interesting ways to show things that the visuals i drafted, go ahead and experiment and change things!

thanks!
Z

**Comment by zee-moz** [comment]
@flukeout here's a longer example of a visual explainer video, probably more detailed in terms of drawing than what we're doing, but a good reference point. 
https://www.youtube.com/watch?v=L5rVH1KGBCY

**Comment by flukeout** [comment]
Thanks @zee-moz - appreciate the benchmark. From what I can tell, this is a direct, but sped up screen recording from a painting program (like Photoshop, for example) with an illustrator directly manipulating the text elements and adding custom illustrations on the fly. The transitions are him or her zooming and dragging the painting canvas.

Just wanted to call that out because it is pretty much the opposite of what can be achieved with some kind of tool or program, which will rely more on templates and repeatable transitions and a smaller set of pre-defined graphic assets.

I do think the general aesthetic of the presentation is something we could aim for, however. It feels light, casual and approachable.

Sorry for calling that out, but just wanted to make sure we set expectations about which part of that presentation we could reasonably borrow from and reproduce.

**Comment by zee-moz** [comment]
@flukeout yes I agree. Shared the link more for the aesthetic/formal example, not for the how it was produced. Thanks!
