### ISSUE TITLE
[MoFo Unified Design] Notification Bar

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#191]
#### Problem

When we want to promote common CTAs on properties across MoFo and we need to design UI mechanism that will grab user attention to deliver info and be versatile enough to not intrude on the unique qualities of the site.
#### Progress

This UI pattern is an idea for the localization CTA link:
![mozilla-learning_localization-cta-idea](https://cloud.githubusercontent.com/assets/2492510/16815635/6f6a9ee4-48ef-11e6-84a9-e3d113a4b96e.png)
#### Considerations & Decisions
- it is easily integrated across properties if it is appended to the top and highly visible 
- what type of content will use this notification bar?
- cross-property promotion can utilize this so it doesn't look integrated in the site _(perhaps replacing promo banners)_
#### Following steps
- [ ] Research use cases/best practices
- [ ] Benchmark examples of notification bar
- [ ] Decide which sites would use this

This ticket is to decide as a group:
- [ ] Design notification Bar
- [ ] Design review 
- [ ] Dev/Implementation review
- [ ] Add to Toolkit
#### Related Issues

https://github.com/mozilla/learning.mozilla.org/issues/1942

**Comment by sabrinang** [comment]
Some benchmark examples of notification bar:
![benchmark-examples_notification-bar](https://cloud.githubusercontent.com/assets/2492510/16822565/3747f6e2-4912-11e6-9af4-ca726b45c49d.png)

**Comment by sabrinang** [comment]
More recent examples: 

Extended notice on network prototype (https://github.com/mozilla/foundation.mozilla.org/issues/476):
![banner-v4](https://user-images.githubusercontent.com/22157921/27109560-9ab1c61a-5058-11e7-98ae-cb407abe14b3.gif)

**Comment by kristinashu** [comment]
This no longer feels needed but please reopen if you disagree!
