### ISSUE TITLE
Post to Wake.io

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Design#196]
Step1. Post a few design highlights to Wake.io so we can seed our channel.
https://mozillacreative.wake.io/space/2

Step 2. Post new work you're proud of on Fridays around demo time.
cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez @xmatthewx

**Comment by flukeout** [comment]
@natalieworth posted some :fire:

**Comment by vazquez** [comment]
Fuego!
