### ISSUE TITLE
Open Design Meeting 11th August 2016

### ISSUE THREAD

**Issue by elioqoshi** [MozillaFoundation/Design#198]
Duplicating this from here: https://github.com/mozilla/OpenDesign/issues/84
I thought it would be great to unite for our Open Design Meeting tomorrow :)

----------------

We will have our next Open Design Meeting on Vidyo as usual:

Date & Time: Thursday, 11th August 5PM GMT
Duration: 30-45min
Vidyo Room Link: https://v.mozilla.com/flex.html?roomdirect.html&key=NTr7t1TVKnnhKBCVCd74qw8Oo

Agenda/Notes/Questions: 
https://public.etherpad-mozilla.org/p/open-design-meeting

Please add your topics or share-outs to the agenda!
The call will be recorded.

**Comment by xmatthewx** [comment]
Thanks @elioqoshi. How often does this group meet? 

cc @lovegushwa

**Comment by elioqoshi** [comment]
@xmatthewx Hey! We meet once a month, every 2nd Thursday. If we can make it sustainable we can make it also biweekly.

**Comment by xmatthewx** [comment]
Excellent! I shared info with the team.
