### ISSUE TITLE
Add Design/Functionality to Open Canvas Template for OLTS

### ISSUE THREAD

**Issue by zee-moz** [MozillaFoundation/Design#199]
We need some design love and some improved functionality on [Abby's open canvas web app thing](http://acabunoc.github.io/open-canvas/canvas/) which features in the Open Leadership Training series [here.](https://docs.google.com/document/d/1VglRpEUI3YD26Lno_N70V_fLtPEkZw2sIDQZ30-kQR0/edit?usp=sharing) 
- UI is a bit confusing. When you save, your product goes [here](http://acabunoc.github.io/open-canvas/). Is this the best place?
- Link sharing is currently broken.
- Maybe give the option for people to share rather than it happening automatically
- Would be nice to be able to save/print, if you don't want to share your thing right away

cc: @flukeout @hannahkane @acabunoc

**Comment by xmatthewx** [comment]
This is very cool. 

@zee-moz – if you or @acabunoc want to bring this to design crit (next meeting Aug 29th), you might get some quick easy suggestions for improvement. This could (no promises) be a nice bite-sized project when we onboard the new design team member. 

@kristinashu – it'd be interesting to think about how these could optionally show up as a link in Pulse. I search Pulse for privacy, I think both things that have been made alongside a proposal like this. A great way to seed collaboration. A few of the canvas elements could easily fill our existing fields.

**Comment by hannahkane** [comment]
Thanks, @zee-moz, for filing. Can you clarify the timeline for this? I think @xmatthewx is right that this could be a good project for the new design team member, but want to make sure that aligns with your timeline.

**Comment by zee-moz** [comment]
I would say we'd want it by early October. @acabunoc's mentorship cohort is using a draft version of the materials starting next week but it's fine that they use the existing version. Our big launch is around MozFest, so we'd be looking to have everything ready well in advance of that date.

**Comment by acabunoc** [comment]
Yes, I don't think this can (or should) be done in time for the round I'm starting next week! They all have the "draft" disclaimer :)

**Comment by zee-moz** [comment]
@acabunoc can we bring the Open Canvas Template to the design critique next week and talk about how best to polish it up for the OLTS launch? Monday, 1:30?
@secretrobotron @xmatthewx @flukeout

**Comment by acabunoc** [comment]
sounds good! I can be there @zee-moz

**Comment by xmatthewx** [comment]
Excellent. I'm excited to talk about that tool. https://public.etherpad-mozilla.org/p/designcrit
