### ISSUE TITLE
Project Design Brief

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#20]
Here is a checklist you can copy-paste into your planning tickets. Use it to ensure a thorough kickoff conversation and to prep formal briefs for large projects and consulting gigs. 
 
Drop feedback and iterations on this list in the comments below.  

```
#### Project Brief

 - [ ] What problem are you trying to solve?
 - [ ] Who has this problem? 
  - [ ] Have research?
  - [ ] Have user stories? (As a ____, I want ____ so that I can _____.)
 - [ ] When do you plan to launch your solution? How long will it remain active? Describe opportunities, constraints, phases.
 - [ ] What features does an MVP solution include? How will your audience use it?
 - [ ] What is the value to your audience? How many people will be served?
 - [ ] How will you market and distribute the solution? What channels will drive the audience to it? (ex: FF Tiles, Facebook Ads, Hive Network)
 - [ ] How will you measure success? What are the needs and opportunities for...
   - [ ] user testing? 
   - [ ] analytics?
   - [ ] field research?
 - [ ] Who else in the field have addressed similar problems for similar audiences? What benchmarks serve as good reference?
 - [ ] What Mozilla properties or style guides should inform the design? (ex: Material Design ) 
 - [ ] If you overheard someone describing their experience with your project, what would you love to hear? Include 2-4 adjectives that summarize the spirit of the experience.

#### Details

 - [ ] Project URL, repo
 - [ ] Required regions for localization
 - [ ] Visual content (existing assets & requirements)
 - [ ] Written content (existing assets & requirements)
 - [ ] Other requirements or restrictions (ex: consent to terms)

```

cc: @hannahkane @flukeout @edrushka @HPaulJohnson @OpenMatt @cassiemc @secretrobotron @vazquez @sabrinang @lovegushwa  

We can move this to a wiki if it proves useful.

**Comment by hannahkane** [comment]
yay! excited to use this. would be great to have this on a wiki somewhere.

**Comment by secretrobotron** [comment]
:+1: put in wiki!

**Comment by xmatthewx** [comment]
- [ ] Add a link from http://build.webmaker.org/design to here. [PR pending](https://github.com/mozilla/build.webmaker.org/pull/78) 
 - [ ] Test this list for a few heartbeats
 - [ ] Find a suitable home if it proves useful (wiki on this repo?)
 - [ ] Update link FTW

**Comment by cassiemc** [comment]
I'm not sure what wiki we would use, and I thought we were moving away from wikis into build.webmaker.org, no? This handbook IS the wiki. :) @hannahkane @secretrobotron

**Comment by hannahkane** [comment]
Link from build is fine. Just wanted a way to find this easily.

**Comment by xmatthewx** [comment]
some ideas on how to improve the brief:
 - [ ] identify & link to dependencies
 - [ ] specify internal / external for audience
 - [ ] Project destination (URL, repo, print)
 - [ ] Can questions be reframed so they're more flexible
 - [ ] What problem are ~~you~~ _we_ trying to solve?
 - [ ] Project summery (1-2 sentences)

assigning to @lovegushwa to review and improve the language

**Comment by cassiemc** [comment]
@lovegushwa can you help us wrap this one up this heartbeat?

**Comment by lovegushwa** [comment]
@cassiemc 
I worked on organizing and adding to @xmatthewx great start. It probably needs a little bit more editing and collaborative thought (you can do this if you like or we can invite some more folks for feedback?) I think after that we should make a build ticket for it, it would be great to have on build.webmaker.org as a form.

https://docs.google.com/a/mozilla.com/document/d/1H4rDTT7zdvOFhGlgMDIuRLlTRlAxMsU_-mUehv_iEZU/edit?usp=sharing

**Comment by cassiemc** [comment]
@lovegushwa This is great! I find this language a little more human and thus easier to parse, thanks for putting it together. Looking forward to trying it out with folks (@hannahkane has offered to be a guinea pig in the past if we would like to run it by someone).

Looks like my old docs got lost in the kerfuffle, but I had originally planned this out as either 
- a spreadsheet: https://docs.google.com/spreadsheets/d/1qoVyvKHRWpViZJ9iJTGlKy39d8eJ9VQCZEgUfOzy-Z8/edit#gid=0) 
- or a google doc with a bit more process background: https://docs.google.com/document/d/1E6lhyYjty_eNUo2xVAKcde6h7Di2zI_iShcIcmlz9aw/edit **<--** Maybe there is some content here that we can reuse for build/design.

I do like the idea of including it as a form linked to from build. Especially if people can go back and edit their form once they submit it. I'm not sure what happens to the form on the other end though once it is submitted, so I wonder if autogenerating design brief issues on github with this checklist built in would be better, so that everything can live together in harmony happily forever after in github.

**Comment by vazquez** [comment]
I vote in favour of auto generating GitHub issues. It remains open, it's always editable, and everyone can contribute! :cow: :star:

**Comment by cassiemc** [comment]
@lovegushwa I think you were going to document our conversation here from yesterday.

**Comment by davidascher** [comment]
History with planning tickets tells us that people short circuit forms that
generate github issues and bypass the reading and structure that is
"imposed" on them. So watch out for that.

A thing to consider. Also, have y'all explored pros and cons of whether
this should be self service or a structured conversation?

**Comment by cassiemc** [comment]
@davidascher you are right on the money. All things we talked about yesterday, haha. I :heart: the idea of setting these up as structured conversations. We'll have the self-service replicable google doc if people want to look ahead of time, but I think the onus should be on designers to guide their colleagues through the process.

**Comment by lovegushwa** [comment]
@cassiemc @vazquez @flukeout 

I'm not sure who finished editing this document but thank you! ... I'm calling this closed, let's move it do build.webmaker.

So I changed permissions to "Any one at Mozilla can View," ... This should keep people from editing this document making it a template, folk will then need to "Make a copy." @flukeout does this seem like the right way to share this document or did you have a different self duplicating idea in mind?

https://docs.google.com/a/mozilla.com/document/d/1H4rDTT7zdvOFhGlgMDIuRLlTRlAxMsU_-mUehv_iEZU/edit?usp=sharing
