### ISSUE TITLE
Update GitHub lllustrations with updated OLTS graphic style 

### ISSUE THREAD

**Issue by zee-moz** [MozillaFoundation/Design#200]
Sabrina did some [excellent illustrations](https://drive.google.com/open?id=0B4Q8pzCpDS_eOGxtQzJRMDgzczA) for the [GitHub section](https://docs.google.com/document/d/1e2tQ3EDUxC6Vv8JDx9xMqkYZmeMDNky-WKzuMt5HC3A/edit?usp=sharing) of the Open Leadership Training Series; now @flukeout has created a new visual style and new way of visualizing contributors for the "Ingredients of an Open Project" video. 

While we love the cute animals in the first pass, we'd like to update the GitHub illustrations with this new character style for a unified look and feel. 

![sample](https://cloud.githubusercontent.com/assets/25212/17608235/e290d90e-5fdf-11e6-8ae6-edc8ea59faa9.png)

cc: @hannahkane  @flukeout

**Comment by flukeout** [comment]
I count 14 illustrations in that folder, it would take a few days to update them to this new style.

I'm a bit torn though, as that would be way more work than changing stuff I made (which so far amounts to just the diagram above) to match what Sabrina has already created.

I'd recommend we don't do this yet until we do the video test and are happy with how the graphics look and work there. I won't be able to do any of those test animations until next week, however, as I'm away on PTO.

Thoughts?

**Comment by zee-moz** [comment]
While I love (really, I LOVE them) those cute animals, I prefer the new graphics that @flukeout made. The animals don't make a ton of sense if you're not already clued into the Mozilla mythos of dragons and foxes. And the cuteness may be off-putting for those who are expecting a more serious experience (maybe).

We'd talked before about generating a library of simple stylized graphics/icons that could be used for creating diagrams in a sort of quick, drag-and-drop way. Those of us in hubs/programs could use this library to create visuals or add spot illustrations, with minimal input from the production team. 

Would this project be a good place to start building that library? @xmatthewx @hannahkane

**Comment by flukeout** [comment]
I'm off until next Wednesday on PTO, so let's chat when I get back. My original understanding was that we would do a trial run with these new graphics for that one video and evaluate where to go from there. This request is changing the scope of that work a little bit, we didn't even test the new images in the video format yet. 

I think we should meet to figure out...

* How to finish off the video with the new illustrations
* How much content there is in general and what the specific design needs are

Looking forward to chatting!

**Comment by zee-moz** [comment]
OK, let's talk when you're back. Enjoy your time off!
