### ISSUE TITLE
Discuss design strategy for Leadership training assets

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#202]
Recently we've had a few design requests related to training materials that are currently in development...
- Open Leadership Training https://github.com/MozillaFoundation/Design/issues/201
- Github Illustrations https://github.com/MozillaFoundation/Design/issues/200
- Open Canvas Template - https://github.com/MozillaFoundation/Design/issues/199

In addition to this, there is also a Teachable account that will host some (or all?) of this content.

Let's discuss and define a strategy to make sure that these materials have a cohesive visual style that fits within the rest of our properties.

**Questions & Considerations**
- What other materials will be created in the near future that we should consider?
- How will they be organized or grouped?
  - Do these fall under a "Leadership" hub?
- Do we need a unified style for all of these or can we tackle them as one-offs?

cc: @zee-moz @hannahkane Please add additional info or thoughts, thank you!

**Comment by hannahkane** [comment]
Regarding the question about organizing/grouping—my understanding is that github illustrations, the open canvas, and the videos mentioned in #201 are all part of the same Open Leadership Training Series (OLTS). Is that right, @zee-moz? 

Would it be a good solution to have them live in their own place, and be linked to from each of the hub websites?

**Comment by zee-moz** [comment]
@flukeout @hannahkane I know these items were on hold for a bit while we were waiting to understand something about the leadership network design style etc... Now that we've got some clarity on that from @ldecoursy (that this branding will come later in 2017, and will not effect what we do now with the OLTS) what are the next steps on the issues mentioned above? Are there design resources/work hours to create video templates, refine the open canvas interface and template, and (if time) update some illustrations? 

Some of the content has gone up in Teachable-- the remainder could be populated fairly quickly, but I'd also like to have a short discussion of the design template we will use on Teachable-- if it's the same as Clubs, @flukeout can you just give me a tour of that template and maybe we can talk together about how it works with the structure of the OLTS (which has a slightly different organization than Clubs material).  Let me know!

**Comment by hannahkane** [comment]
cc @secretrobotron who might be lending some project management to this effort and @xmatthewx because we've discussed that parts of this might be good for our new design hire who starts Monday

@flukeout @xmatthewx - any reason not to use the existing Teachable template for this?

**Comment by natalieworth** [comment]
Closing this as the curriculum is live, but feel free to open if needed.
