### ISSUE TITLE
Review and Update IA

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#203]
Consider recent and potential future work on sites (clubs, gigabit, maker party). Correct and adjust IA diagram as needed. Consider cross-hub, pan-Mofo, and even Mofo/Moco alliances.

Deliverable: Updated diagram that shows up well in mofo dot build. Review with friends in MoCo. 

How should we slice of the DARCI for this @hannahkane?

**Comment by hannahkane** [comment]
Good ticket. In terms of "potential future work," I'd call out some additional considerations:
 * likely merger of Hive content into Learning site
 * likely creation of Mofo/Moco-wide Clubs platform
 * potential creation of pan-Mofo services for Events and Curriculum (and maybe other things, but those are the two I'd focus on)
 * likely need for an "MLN front door" (that may already be on the IA diagram; I forget)

What about this for the DARCI?
Decider: @xmatthewx 
Accountable: @xmatthewx 
Responsible: @sabrinang (rationale: Go Global team designer)
Consulted: @kristinashu @flukeout @hannahkane; Clubs program managers from Moco and Mofo
Informed: hub leads + @kaythaney
