### ISSUE TITLE
MLN icons

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Design#204]
### Intro

Is it possible to have a repository of icons we have purchased or designed that we can use in MLN documents? 
### Links

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @xmatthewx @taisdesouzalessa

**Comment by xmatthewx** [comment]
We often use font awesome for common things. Not sure how those would translate to non-web or large use cases.

The icons this team has designed for our various sites (like the 3 on the bottom of the science homepage banner) ... it could be good to put all of those in a single folder / file for people to use. Thoughts @kristinashu @sabrinang @flukeout?

@ldecoursy – can you name a couple icons you need?

**Comment by ldecoursy** [comment]
See page two here for George's suggestions, however he notes we need to replace those. https://docs.google.com/document/d/10JRtPlrOQjOSXUnJlMOsipBrPBaTQ0X4Htc_K2mSm6I/edit#heading=h.i5b33lgqngib

**Comment by xmatthewx** [comment]
cc @hannahkane

**Comment by flukeout** [comment]
@ldecoursy - If it helps, I've also just published pretty much all of the icons form our sites to the Foundation Icon Font here - https://mozilla.github.io/foundation-icons/

**Comment by ldecoursy** [comment]
Helpful! Is that also linked to from here: http://mofo.build/design/

**Comment by flukeout** [comment]
It isn't, I'll look into adding it there too.
