### ISSUE TITLE
Mozfest Social/Communications Design

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#206]
@KevZawacki and @KGorr had some ideas for design assets that could be useful for Mozfest comms. List below. We have a lot on our plate right now, but if any designers have an idle moment and want to do something quick and creative, take a look. 

@flukeout – It could be interesting to code an animated infographic on the festival in Thimble (numbers on issues, sessions, attendees, etc). That way updates to the numbers would be easy and we can embed the graphic in various places. And take screenshots when an embed isn't possible. 

Design assets Ideas
- Social
- Infographic (bonus for a template we can reuse)
- .gif of 2015 video footage / photos
- .gif that flips through words (“inspiring” “creative” “chaotic” etc.)
- Goofy = good (learning from encryption)
- gif/logo/image for each space (how many are there? can't remember) so we can promote each of them
- images with quotes from last year or "leaks" for this year overlaid
- short video clips of the planning team giving sneak peeks of what's in store

Email
- We need a button (“click here”)
- "Pinterest" style (Mozilla/festival branded of course) images that say things like "5 reasons you don't want to miss MozFest this year" to align email/medium post subjects?

cc: @kristinashu @sabrinang @flukeout @taisdesouzalessa

**Comment by flukeout** [comment]
@xmatthewx could be interesting if we could pull the data for the infographic from the same source as the schedule app. Would that be possible @mmmavis ?

**Comment by mmmavis** [comment]
We have a plan for enabling GA on the schedule app. Not sure how we can pull data in real time from GA though... via [Google's reporting API](https://developers.google.com/analytics/devguides/reporting/core/v4/)???

**Comment by kristinashu** [comment]
Didn't get to do any of the infographics work but some social assets are in https://github.com/MozillaFoundation/Mozfest2016_production/issues/84 and https://github.com/MozillaFoundation/Mozfest2016_production/issues/213
