### ISSUE TITLE
Create an IA diagram for current Learning Site Iteration

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#208]
Current website:
https://learning.mozilla.org/en-US/

@xmatthewx @hannahkane

**Comment by taisdesouzalessa** [comment]
@xmatthewx and @hannahkane here is the latest iteration of the IA of the current site. I did a mix of sitemap and inventory (describing the content of each page). I think this structure is useful for our discussion because it allow us to see:
1. The relationship between pages
2. The CTAs
3. Links to external content
4. Content in each page (so it allow us to focus on relevancy, is the current content relevant to each page?).

By seeing this structure we can have a base for discussion of the new IA: what to keep, what to remove, what is working, what could be better?

https://redpen.io/p/mf32c73d2cecccd67e

Looking forward to hearing your thoughts on that and please let me know if you see any opportunity for improvement on this map or if I missed something.

**Comment by hannahkane** [comment]
@taisdesouzalessa - the diagram looks great! Thanks for all of your work on it.

I think this, along with the list of questions, will set us up for a very productive call.

Quick note: the Upcoming Office Hours link is no longer broken, as of this morning. Would you mind filing a ticket for the other broken link?

**Comment by xmatthewx** [comment]
This is superb @taisdesouzalessa. Thank you for digging so deep into the details. This reference will really streamline our discussions. Your diagram seems to cover all the tricky scenarios like default tabs, and makes them very clear.

**Comment by taisdesouzalessa** [comment]
Thanks @hannahkane and @xmatthewx, glad the diagram can help with the discussion. 
Hannah, I filed the ticket and also updated the diagram since the Upcoming Office Hours link is now fixed.
https://redpen.io/p/mf32c73d2cecccd67e

**Comment by xmatthewx** [comment]
I think we can call this specific task done. Correct?
