### ISSUE TITLE
Prepare stakeholder questions for Learning Site Iteration

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#209]
Document with questions:
https://docs.google.com/a/mozilla.com/document/d/1JQFmjaWhVJOYl4LKzV-iPXx1zYRQETk6LPbcqGykkUw/edit?usp=sharing

@xmatthewx @hannahkane please feel free to add more questions there or add comments. I will increase the list of questions as I think deeper about the project through this week.

**Comment by hannahkane** [comment]
Thanks, @taisdesouzalessa. Have added one question so far.

**Comment by taisdesouzalessa** [comment]
I added some more new questions there as well!

**Comment by taisdesouzalessa** [comment]
Closing this issue here.
