### ISSUE TITLE
Add Donate button to universal footer

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Design#210]
Not sure if there's a better repo for this. @amjadm61 had a great idea about adding a Donate button to the Science site footer: https://github.com/mozilla/science.mozilla.org/issues/501

Wondering if we should add that to the universal footer design across all Mofo web properties. Any reason not to?

cc: @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @xmatthewx @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
I love the idea and the way it was executed in the screenshot (a subtle copy "Donate" with a heart). It would be nice to track how many people click on the link and the average amount of donation per person.

**Comment by kristinashu** [comment]
Yes, sounds good! We so already have the Donate button in the advocacy footer https://advocacy.mozilla.org/en-US

**Comment by kristinashu** [comment]
Opened a ticket for this https://github.com/mozilla/mofo-bootstrap/issues/92
