### ISSUE TITLE
User testing with designers - Craft

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#212]
Hey team,

I think it would be good for us to test and explore Craft for a bit, using the pattern library we have so far. I would love to get your insights on what works, what doesn't so we can find a system that fits to us all.

Here is a little step-by-step on installing and using Craft:
https://docs.google.com/a/mozilla.com/document/d/1RII8kKpbTh-Ysa-Fg2Xq3Nb1IMgoMjVBdQcAEXGHie8/edit?usp=sharing

I thought it would be good to have a spreadsheet to collect our thoughts while we play with Craft, so we have a document where we can see everybody's challenges and propose ways to make it work better for us. What do you think?

https://docs.google.com/a/mozilla.com/spreadsheets/d/1ZMvbOzCxVeXSU0ymU_DfrQ1pDAJuMmz_vXzu_xWgSjk/edit?usp=sharing

cc: @kristinashu @sabrinang @flukeout @xmatthewx @hannahkane

**Comment by xmatthewx** [comment]
I agree! @taisdesouzalessa - it would be great if you facilitated a time for people to play with it all together as you suggested. Maybe there's an elective time while at All Hands? Let's not block other opportunities, but if people don't have a thing during one slot. Could be nice to also show @natalieworth @beccaklam how awesome this is...
