### ISSUE TITLE
Design paper certificate for Glass Room Training 

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/Design#213]
### Intro
Mozilla is partnering with Tactical Technology Collective to bring an innovative experience where New Yorkers explore how data and technology impact society. In November, we'll open a pop-up tech store with a twist. Instead of selling products, the space – called Glass Room – will offer visitors a “data detox” for the behavior, devices, and interfaces we use everyday. This interactive space will allow visitors to take control of their own data and privacy. The Glass Room will open up shop on November 28th – December 11th.

We have ~20 people who are being trained as experts to facilitate Glass Room workshops, and would like to provide a printed certificate to recognize/congratulate them for completing the Ingenious Training for The Glass Room.

The training ends next Tuesday, Nov. 15.

### Links

We can build off existing examples linked in https://github.com/mozilla/curriculum-localization/issues/2#issuecomment-259042064 

The style guide for Glass Room logo and related elements is here: https://drive.google.com/drive/folders/0B4tVSl8MpvjMME9qcEU5Zm1HTDQ

cc: @kristinashu @sabrinang @flukeout @xmatthewx @taisdesouzalessa

**Comment by xmatthewx** [comment]
cc @hannahkane @gideonthomas – we should align and optimize.

**Comment by hannahkane** [comment]
@ldecoursy - Do we need the certificate tomorrow?

**Comment by ldecoursy** [comment]
If possible! The 4-day training ends tomorrow, so ideally we could give it to them at the end of the day.

**Comment by hannahkane** [comment]
@xmatthewx - what do you think? Since there's a quick turnaround at this point, I'm wondering if we should just adapt the copy on the [Club Captain cert](https://github.com/mozilla/learning.mozilla.org/issues/1849#issuecomment-222023623)?

**Comment by ldecoursy** [comment]
@xmatthewx Think this can still happen today? What additional info would you need from me?

**Comment by xmatthewx** [comment]
@ldecoursy – I've checked to see if any of the designers have spare time from their projects today. Asked them to reach out to you directly. We'd just need to copy changes to update the certificate @hannahkane recommended: https://github.com/mozilla/learning.mozilla.org/issues/1849#issuecomment-222023623

**Comment by flukeout** [comment]
@ldecoursy I'll be working on this today. 

**Questions**
* In how many hours is it due from the timestamp on this comment?
* Will you be filling in the participant names by hand or by editing the file before printing?

I've posted a redpen with the existing certificate so we have a place to identify required changes.

Here it is -> https://redpen.io/fp5db004a1470d2c31

I'll review the assets that you listed in the opening comment. In the meantime, can you please provide the specific copy that you'd like on the certificate?

**Comment by ldecoursy** [comment]
Thanks @flukeout 
I think if we can get it by 4:30pm today that would be great. 
I also think it's better if we can edit the file with their names before printing (I've pinged the folks leading the training to check on that). 

It should have both mozilla and Tactical Tech's logos. 

Copy:
Certification of Completion

This certificate acknowledges that

___________________________
has successfully completed
inGenious training for The Glass Room. 

Congratulations!

**Comment by xmatthewx** [comment]
4:30pm eastern time

**Comment by ldecoursy** [comment]
doh! thanks :)

**Comment by flukeout** [comment]
Okay cool, that should work. Here's something I put together so far, but will update based on your copy requirements.

![image](https://cloud.githubusercontent.com/assets/25212/20316623/71bebd30-ab17-11e6-9152-388554d65b9f.png)

Will an Illustrator file be OK for those who will be editing the names?

The old certificate has Chris' signature on the bottom (see redpen linked earlier) do we want something like that?

**Comment by ldecoursy** [comment]
I don't think we need Chris' signature, but do need the logos. 

Also it's inGenious :)

I'm not sure if they have illustrator (I don't). Can we do it that way and also get a version with a blank for the name in case they just print and write in?

**Comment by flukeout** [comment]
Also, do we want some kind of mozilla logo on this? Maybe I'll put it where Christopher Lawrence's signature is. Can I say something like? 

* Awarded in partnership with Mozilla
* Organized by mozilla etc?

**Comment by flukeout** [comment]
> I don't think we need Chris' signature, but do need the logos.

Which logos?

**Comment by ldecoursy** [comment]
Mozilla and Tactical Technology Collective logos - the latter should be in the style guide link at the top of this ticket. 

This just launched if helpful: https://theglassroomnyc.org/

**Comment by flukeout** [comment]
Hey @ldecoursy here's an update, please advise on any changes you need to copy & information. I have a bit more time so I can try another style variation.

![image](https://cloud.githubusercontent.com/assets/25212/20317652/c593efc6-ab1b-11e6-964e-6827138824c8.png)

When we're done, I can provide a blank template as well for printing.

**Comment by flukeout** [comment]
Also, I guess since this is being printed I should format it to fit a landscape piece of paper, stay tuned!

**Comment by ldecoursy** [comment]
OK thanks!
I think it looks great - only wonder if to simplify, we remove the inGenious training from the very top line, since it's repeated below.

**Comment by flukeout** [comment]
Yeah, feels somewhat redundant. I'll post an update shortly.

**Comment by flukeout** [comment]
Okay, here's the final version...
![image](https://cloud.githubusercontent.com/assets/25212/20318194/24dae76c-ab1e-11e6-9373-7fda5e0af7d7.png)

Here's how it looks printed...
![image](https://cloud.githubusercontent.com/assets/25212/20318185/1a6d0c9c-ab1e-11e6-8375-e3822d820feb.png)

**Files are here...**
* Editable Illustrator version...
  * https://dl.dropboxusercontent.com/u/109902/certificate-print.ai
* Blank PDF version..
  * https://dl.dropboxusercontent.com/u/109902/certificate-print-blank.pdf
* I've outlined all of the text except for the name of the participant, which is set in Fira Sans
  * Get it here - https://github.com/mozilla/Fira/releases/latest

Let me know if you need anything else. Cheers.

**Comment by ldecoursy** [comment]
Thank you!!!

**Comment by flukeout** [comment]
Closing until further notice.

**Comment by xmatthewx** [comment]
Thanks again @flukeout for your speedy work.

**Comment by ldecoursy** [comment]
Sorry to reopen, but wondering if anyone is free to help with one edit to the template, and possibly adding in the names of the recipients - there are 20 - before mid-day tomorrow (Friday).

**Comment by xmatthewx** [comment]
Text is outlined and no longer editable. Original art doesn't seem to be on google drive. I'll have to fix typo on my end.

**Comment by xmatthewx** [comment]
I've fixed the typo. Added AI file to drive here: https://drive.google.com/drive/u/1/folders/0B_rbDAen9prkX3VUdklPOFlOQ3c

**Comment by xmatthewx** [comment]
@ldecoursy – I've added a PDF to the folder linked above. You should be able to edit with Acrobat. The font is FIra light italic, but you can change that if it gives you trouble. You'll probably need to manually center the names.

**Comment by taisdesouzalessa** [comment]
Hi @ldecoursy - for the certificates with the 20 names, should we keep the date awarded "November 15" or should we change for tomorrow's date?
<img width="790" alt="screen shot 2016-12-15 at 9 26 52 am" src="https://cloud.githubusercontent.com/assets/22157921/21234773/e7b0a94c-c2a8-11e6-8626-f5bc3aa452a6.png">
Thanks!

**Comment by ldecoursy** [comment]
Ah, @taisdesouzalessa Great catch. Let's put December 18 - that's the day they'll receive it and the final day of The Glass Room pop-up. And thanks for your help. I just downloaded Acrobat but it's my first time using so suspect it would take me awhile ;)

**Comment by xmatthewx** [comment]
The font on the date is likely Futura @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
@ldecoursy Here is a PDF with the 20 names. Please let me know if you need anything else.

[all-certificates.pdf](https://github.com/MozillaFoundation/Design/files/655709/all-certificates.pdf)

AI file: https://drive.google.com/drive/folders/0B3b1KWRwjxtoeF84V2FDMGNIbm8?usp=sharing

cc: @xmatthewx @sabrinang

**Comment by ldecoursy** [comment]
Thanks you! 🌹
