### ISSUE TITLE
[Hawaii All-Hands 2016] Collaborative Design Session

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#214]
Plan 2-3 hour session using [Design Studio](http://www.bigspaceship.com/design-studio/) as a model - collaborative design process with task of “Design a homepage for the place to protect the internet” 

TASKS BEFORE ALL HANDS:
- [ ] 1. create an agenda and a plan for how we’ll run the session
- [ ] 2. create prompts / materials needed for running the session
- [ ] 3. define personas for people to group around
- [ ] 4. identify key stakeholders and encourage them to attend
- [ ] 5. create a plan for follow-up after this; how we’ll report back and/or incorporate some of the ideas into the final product; how we’ll allow people to be engaged after this session
- [ ] 6. do a test-drive of a mini version of this session with the designers pre All Hands <-- love this idea from Sabrina!

cc: @kristinashu @sabrinang @flukeout  @xmatthewx @hannahkane @simonwex @chrislarry33

**Comment by hannahkane** [comment]
The information being gathered [here](https://github.com/MozillaFoundation/plan/issues/840) can be useful context-setting for this activity.

What do you all think about these as the goals for the activity?
 * Engage staff members in the design process in a fun, collaborative way
 * Gain insights from staff members about audience, motivators, and offerings
 * Surface some of the challenges we'll face during this project by engaging staff directly in the ideation process

**Comment by taisdesouzalessa** [comment]
@hannahkane I think those points are great. They cover most of the goals. Just one suggestion: Sabrina and I talked this morning and one of the outcomes we thought about was:
• produce ideas that will inform prototype of the new page
What do you think about adding this fourth bullet point there? I think one this point is very close to your first bullet point but it is not quite the same...

**Comment by taisdesouzalessa** [comment]
Here is a diagram on how we could run this session (it covers the item 1. of our checklist) based on research we did on how to run Design Studio Sessions. @hannahkane since you already participate in some of those sessions, please let us know if you think this diagram makes sense.

https://redpen.io/p/vz49f28b49b99733e0

The red parts indicates where we still need some further definition and clarity. Please feel free to comment here or in Red Pen. Let us know your thoughts and feedback!

cc: @kristinashu @sabrinang @flukeout @xmatthewx @hannahkane @simonwex @chrislarry33

**Comment by taisdesouzalessa** [comment]
materials for the session:
- sharpies
- butcher paper roll 
- tape
- templates for the sketches (with grid)
- post-its
- water
- snacks
- room

@sabrinang anything I am missing?
