### ISSUE TITLE
[Hawaii All-Hands 2016] Network Offerings

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#218]
For All-Hands, it would be a valuable asset to have a list of network offerings to accompany our activities and discussions.

We will be compile a list of current network offerings and curate short list from it to present with a set of follow up questions. These questions can assess what we currently have, how we can prioritize them, what is working and what isn't. We can also frame an additional set of questions regarding how our offerings address providing our user value to gain insight on any offering gaps or directions to consider.

Work will be captured in this google doc here: https://docs.google.com/a/mozilla.com/document/d/1oQIm0_sqD-g8HUonSPEz-4aslEioVMKGwjM9a1q-hjU/edit?usp=sharing

cc: @xmatthewx @taisdesouzalessa @hannahkane @simonwex @chrislarry33

**Comment by hannahkane** [comment]
I think this is something @kaythaney was working on. Kaitlin - can you please advise? Do you have a similar document somewhere?

**Comment by kaythaney** [comment]
Thanks, Hannah. This is a bigger piece of work as what we mean by "network offerings" are the programs we're streamlining design for (think unified Fellows model, Clubs as a field organizing model, partnership strategy pulling from the work of the Hives, OLTS as onboarding across, WOW as 2-3 day in person workshops as main offering). I'm working on getting this into a high level doc for you all for starters for higher level Network offerings (in some cases, that we're building towards but may not have implemented across all programs just yet).

**Comment by taisdesouzalessa** [comment]
Based on the list @kaythaney provide us, @sabrinang and I developed this activity for our All Hands in Hawaii. This will be a handout. 

The goal of this activity is to learn:
1. What people think about the list of offerings
2. If they would like to reorganize the list/add more items
3. If they have additional feedback
4. What are the top 3 primary offerings they have in mind and how they would organize it in a priority grid
5. Which audiences they have in mind while considering those offers
6. Which action opportunities they see in a secondary level

![offerings activity](https://cloud.githubusercontent.com/assets/22157921/20725570/2478087c-b627-11e6-91f2-a7b6071de7f8.png)

The numbers represent the copy we will place. The document with the copy is here - feel free to add your contributions there (please go to the "offerings" section of the doc - we placed both activities in the same doc):
https://docs.google.com/a/mozilla.com/document/d/1OPQBQsY4S8qAh13Y_wOkeLagdQJfQIAyRLqcqoFNYDw/edit?usp=sharing

@xmatthewx @hannahkane - we would love your input there so we can tweak this document before doing the final version and do the test-drive in our office.

**Comment by taisdesouzalessa** [comment]
**Update:**
We decided as a team to stay away from the activity posted above and instead have a sheet that facilitates our conversation with staff. This new approach will give us more valuable outcomes.

Here is a short description of the new approach:
https://docs.google.com/a/mozilla.com/document/d/1ve8LhxwvUwPPyBPE_0yVGZKT8OTXLS-0d_w4xwP-V_4/edit?usp=sharing

@sabrinang and I worked together in grouping this list in another way. I'll have a more visual display of the 3 ways of grouping this list by Friday and I'll print them out so we can talk about them during All Hands.

@hannahkane @flukeout @xmatthewx @kristinashu - could please take a look at the doc and give your input? Our plan is to get audience's and staff's insights that will guide our website design later on.

**Comment by taisdesouzalessa** [comment]
Here is the deliverable for discussion in our All Hands:

https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoY043eWZxU1g5d1k/view?usp=sharing
