### ISSUE TITLE
Assist with Foundation Strategy Deck Design

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#219]
I'll be helping put together the Foundation Strategy Deck. The main goal is to create images or diagrams for each of the 5 key issues.

**Links**
* [Scope of Work](https://docs.google.com/document/d/1VXYu_VhSU2I24F6R24_QdNKKWHUDjCTRQHkTgVLzfWI)
* [Creative Brief](https://docs.google.com/document/d/18OHuMTdk5-5JEEPxJLnxGny7Hp4dj78ku0DOMwOgzgk/edit?ts=57a8c893#)
* [Presentation Templates, on Mana](https://mana.mozilla.org/wiki/display/IC/Internal+Communications+Home)
* [Current Deck - Long Version](https://docs.google.com/presentation/d/1Tj-wFUZ_X0kP2WjmsnWeaizaEe6UY_V2mETVR2QS2lc/edit?ts=58347f33#slide=id.g1177d323d2_0_0)
* [Current Deck - Short Version](https://docs.google.com/presentation/d/17A7wmjTNRmAvJd3OHBHGmYVt4DoQxE3WUUqOL46W7OU/edit?ts=58348494#slide=id.p4)

**Steps**
* [x] Create a document that outlines each of the five issues, along with a set of key concepts that we want to convey in the diagram
* [x] Pick a couple of the issues and create a few diagrams to explore a visual style & direction
* [x] Based on the above, pick a final style for the rest of the diagrams and complete them
* [ ] Create the final board slides with the new diagrams

**Questions**
* What is the deadline?

cc @Lottarao - Did I miss anything? Feel free to add additional context or details.

**Comment by flukeout** [comment]
Description of the Key Issues and some Ideas [here](https://docs.google.com/document/d/1VTDYXvrPEaG7mjoKDTDwEtoLD7qH1dKNUqjEV-PJzz4/edit)

**Comment by flukeout** [comment]
Did some concepts around Online Privacy & Security - [check them out here](https://docs.google.com/a/mozilla.com/presentation/d/1NeRRnkTRGm4_F8osx_NHnDMnk4YByWX9eDUEnqygFck/edit?usp=sharing).

cc @Lottarao let me know your thoughts.

**Comment by flukeout** [comment]
Will continue to work on ideas for the rest of the key issues today and meet with @Lottarao tomorrow to discuss next steps.

**Comment by flukeout** [comment]
@Lottarao I've started a version two of the deck that has the strongest concepts left in it per issue. In addition, I took a stab at a final style for Online Security & Privacy image.

Let me know your thoughts.

* https://goo.gl/zaIuTG

**Comment by flukeout** [comment]
Hey @Lottarao - when do we need to finish the strategy deck by?

**Comment by kristinashu** [comment]
Closing this ticket but please reopen if necessary.
