### ISSUE TITLE
[Network Design Research] Network User Journey 

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#221]
We would like to do a collaborative User Journey session with different collaborators. That could be done in person or asynchronously. I think an in person session would be beneficial because it would spark some interesting conversations.

**Dependencies:**
1. To have defined Audience Groups #217 (so we know where we should put our focus on)
2. To have defined Network Offerings #218 (so we know the ones we will target and we can focus on them for the user journey)

**Note**
Probably this activity will be done post-Hawaii because of its dependencies described above.

**Nice to have:**
1. After we analyze the Network Benchmarks #220 the learnings from there could inform our own User Journey

If the Audience Groups are the WHO (who are we addressing?), the Network Offerings are the WHAT (what they want to do?), the User Journey is the HOW (how will we help them to discover the offerings, how we support their journey with touch points throughout the experience and so on).

The goal is to have a diagram or storyboard that shows the experience the audience has starting with the first touch point:

• How did they hear about us?
• What was their first interaction with Mozilla?
• How did they first get involved? What was the action or activity?
• Did we maintain or deepen their engagement? How?
• What are their opportunities for continued engagement?

Here is an example from Mozilla Foundation, the basic structure from this storyboard came from [this story](http://storyengine.io/stories/privacy-security/shauna-dillavou/#more-10522) from StoryEngine. Important: this storyboard contains many assumptions about the MLN web presence. We will validate those once the target audience and offerings are more consolidated.
![ussr-journey](https://cloud.githubusercontent.com/assets/22157921/20635771/9cbd3c44-b316-11e6-983f-d57ad4c311fc.png)

cc: @sabrinang @xmatthewx @hannahkane

**Comment by xmatthewx** [comment]
This is excellent. And great to see the dependency on clear audience and prioritized offerings. 

If possible, it'd be good to have an example specific to MoFo. A fellow might be less tricky than other members. Let me know if you want an intro to a staff member who could help you with this.

An iteration on your list:
 - How did they hear about us?
 - What was their first interaction with Mozilla?
 - How did they first get involved? What was the action or activity?
 - Did we maintain or deepen their engagement? How?
 - What are their opportunities for continued engagement?

**Comment by taisdesouzalessa** [comment]
@xmatthewx Great idea on the specific MoFo example. Once we have it I will replace the generic example we have in this ticket. Could you please introduce a staff member for support on this task as you suggested? 
I updated the task description with the iteration you suggested as well, thanks for adding the extra details there.

**Comment by taisdesouzalessa** [comment]
Here is an example of activity we could do as a group to brainstorm users' pain points and opportunities we may have. After collecting the insights with this activity we can have a more detailed user journey map (with all possible touchpoints and opportunities) as well storyboards for each audience group.

![user-journey-detailed](https://cloud.githubusercontent.com/assets/22157921/20635792/ebe5ff72-b316-11e6-8284-6602ab14518d.png)
