### ISSUE TITLE
[Hawaii All-Hands 2016] Process Overview - MLN Web Presence

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#223]
**Context:**
Since we started discussing this project, we evolved the process and the expected outcomes. The discussions we had were very valuable to refine our process and focus on what is really important. This diagram is an overview of the process and it shows the past, the current state and future of the process of collecting the necessary information the design team needs for the MLN Web Presence project.

**Goal:**
The goal of this diagram is to have a clear snapshot of the process and to put us all on the same page. Also, by having an overview it allows us to see if there is any gaps or opportunities to make things better.

The diagram is inside our [Presence Proposal document](https://docs.google.com/a/mozilla.com/document/d/1p01zYPQ0woSphzvpOfE-riV5RyaMwR4xjaLhsAtTEZk/edit?usp=sharing) but I thought it would be valuable to open an issue for it so we can have discussions around the diagram only.
![revised-diagram](https://cloud.githubusercontent.com/assets/22157921/20775832/d21b54da-b711-11e6-99bf-008f332750db.png)

[Red Pen here](https://redpen.io/p/no24c9e60481fa1e95)

cc: @sabrinang @xmatthewx @hannahkane

**Comment by kristinashu** [comment]
Can we close this ticket?
