### ISSUE TITLE
Building our taxonomy of individual engagement + identity in the Network

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#224]
### Intro

During Hawaii All Hands - 2016 we participated in a session called "Building our taxonomy of individual engagement + identity in the Network" (related to OKR#2). [Slide 75](https://docs.google.com/presentation/d/1fcf5N7HiGfZg198qT0lyQrr2HnhgEbRwZqI-wCpYj_M/edit?usp=sharing) of our All Hands slide deck. 

After the session, Sabrina and/or Taís were responsible for making the visualization of the metaphors we discussed in the session.

### Session Assets
- [Pictures](https://drive.google.com/drive/folders/0B3b1KWRwjxtobTB3cGVVaEY2R3c?usp=sharing) from Alan + Henrik's sketch.

### Deliverables
- [Slides](https://docs.google.com/a/mozilla.com/presentation/d/1pt3RqBoH1dh85Jh3pMiTb8Z8Ph_1QOVoOcfzJ6azuhc/edit?usp=sharing) containing overview of the metaphors, Napkin Sketches and pros and cons of each proposal.
- [Red Pen](https://redpen.io/p/eza727f34913e70e17) with the sketches in bigger size so people can comment in different areas.

cc: @sabrinang @xmatthewx @simonwex @hannahkane

**Comment by taisdesouzalessa** [comment]
Hi @simonwex. Here are the Napkin Sketches you requested. I added a Pros and Cons slide so we can think about it for each metaphor. I couldn't find Henrik here in GitHub, could you tag him here too, please? I left the slides open for comments and edits so everybody can add their thoughts there and help to fill in the gaps. 

Please let me know if you need any tweaks in the sketches.

**Comment by xmatthewx** [comment]
@taisdesouzalessa – very cool things in here.

**Comment by taisdesouzalessa** [comment]
@xmatthewx this was a great session to participate. The teams had so many good ideas. Love the metaphors everybody came up with!

**Comment by kristinashu** [comment]
Feedback from Arielle:
- Everyone is on-board with the garden direction. 
- Did some quick googling and found these images helpful https://www.google.de/search?q=community+garden&espv=2&biw=1257&bih=568&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiCnobnjNvRAhVCrRQKHakfCJIQ_AUIBigB#tbm=isch&q=community+garden+design
- Something like this really speaks to me https://www.soils.org/files/images/sssa/discover-soils/community-garden.jpg

I will continue to explore and expand on the garden metaphor.

**Comment by kristinashu** [comment]
I've updated the community garden illustration. Please add any feedback in [redpen](https://redpen.io/p/tp464478ba0334b484) or in the [doc](https://docs.google.com/presentation/d/1pt3RqBoH1dh85Jh3pMiTb8Z8Ph_1QOVoOcfzJ6azuhc/edit?usp=sharing).

**Comment by taisdesouzalessa** [comment]
@kristinashu this illustration is soooo beautiful and meaningful! Love it. 
Left some comments on RedPen.
