### ISSUE TITLE
Create an onboarding page with key milestones.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#225]
We'll be creating a page for ``mofo.build`` that lists all of the major milestones for a new employee.

Here is the [content doc](https://docs.google.com/document/d/1GfZSpDwgrOvoCvn6fDsqa0BSl7ZtL4QHHkd69pH7f_c/edit#heading=h.vdfb5xwqljj7).

I'll be creating some illustrations in the style of the Dapper Fox, will post some some preliminary wireframes shortly.

@MandyRawls is there any additional content or links for this page?

**Comment by MandyRawls** [comment]
@flukeout sounds good! We can link to further information and resources from the main page.

**Comment by flukeout** [comment]
Cool, here's a rough wireframe. Each step will have a little illustration that includes the fox. I'll post some sketches next...

![onboarding-mock](https://cloud.githubusercontent.com/assets/25212/21626823/63c5ef64-d1c8-11e6-9f4a-f838263dde71.png)

**Comment by flukeout** [comment]
Thinking of something like this for the illustration style.

![image](https://cloud.githubusercontent.com/assets/25212/21653199/d2207b72-d264-11e6-9c18-65ffa07ad6c2.png)

I'll post sketches for each milestone next. I think just a cute illustration that relates the milestone will be good.

**Comment by MandyRawls** [comment]
Yes, love it! Would or will it be possible for me to have editing access for the text so I can update and add hyperlinks? Thanks!

**Comment by flukeout** [comment]
@MandyRawls I'm not sure how the mofo.build site is set up, but if you're currently able to edit parts of that, then you'll be able to edit whatever we come up with here.

**Comment by flukeout** [comment]
**Milestone: First Day & Week** - Meeting fellow MoFos

![image](https://cloud.githubusercontent.com/assets/25212/21657375/c914cf4e-d276-11e6-83df-3fff1f08ddbc.png)

**Comment by flukeout** [comment]
**Milestone - First Month** - Staff Call

![image](https://cloud.githubusercontent.com/assets/25212/21658413/62a01656-d27b-11e6-8e2d-66fc8df7fa3c.png)

**Comment by xmatthewx** [comment]
This is amazing. I love the illustrations. 

@MandyRawls – mofo.build is standard Wordress. They have a visual and html editor. Editing words and links is easy. Breaking page layout is also possible, especially in the visual editor. Wordpress keeps revisions history, so you can always rollback to an earlier version and ask for help.

@flukeout –  if you can achieve your layout with the wysiwyg editor, it'll be less fragile. Dotted line would be tricky, but everything else shouldn't be too bad.

**Comment by flukeout** [comment]
**Milestone - 100 Days** - "Boot" camp & Mountainview

![image](https://cloud.githubusercontent.com/assets/25212/21659176/74ae7c04-d27e-11e6-8fe3-fd762424a88e.png)

**Comment by flukeout** [comment]
@xmatthewx Cool - I'll check into what's possible. I can simplify it a bit for sure.

@OpenMatt Can I have write access to mofo.build?

**Comment by OpenMatt** [comment]
Yes! Although it's down for maintenance right now -- should be fixed soon.

**Comment by flukeout** [comment]
Okay, here's the full set of 6 milestone gfx

![image](https://cloud.githubusercontent.com/assets/25212/21661480/1f6c5954-d289-11e6-8ba3-f80f7781bb4b.png)

**Comment by flukeout** [comment]
@OpenMatt - cool, keep me posted. Will my LDAP account work to sign in or will you create an account for me? Are we doing maintenance or is some kind of wordpress-wide thing?

**Comment by flukeout** [comment]
Looks like it will might be available as soon as EOD tomorrow!

**Comment by flukeout** [comment]
Created another graphic in anticipation of the glossary page. We can use it there.

![image](https://cloud.githubusercontent.com/assets/25212/21696577/8dd720c6-d343-11e6-84ef-37a0b0b8daac.png)

**Comment by MandyRawls** [comment]
I love it! Very cute. I'm wondering if we should change the 6 month milestone (attend all hands /celebrate 6 months), I like the graphic a lot, but I'm getting the sense that the fox is leaving to go somewhere, versus continuing on the same journey. What are you thoughts?

**Comment by flukeout** [comment]
Sounds good @MandyRawls - will update.

**Comment by flukeout** [comment]
Header design for ``mofo.build`` along with some updated design for the copy.

![onboarding-page-mock](https://cloud.githubusercontent.com/assets/25212/21699691/c8d1d0c8-d351-11e6-85b3-6933204c1671.png)

**Comment by flukeout** [comment]
@MandyRawls I published the first version of the page here...
 https://mofo.build/onboarding-roadmap/

**I'm still going to**
* Update the Allhands & header image
* Update the layout once I have access to modify the CSS

You can start editing if you want, though.

**Comment by MandyRawls** [comment]
Thanks @flukeout , looks great so far! 

How do I edit? Or @OpenMatt is this something I would need a mofo.build account for? Thanks!

**Comment by flukeout** [comment]
@MandyRawls That's right. I now have admin access to mofo.build so I'll make you an account. You'll receive and email with log in instructions sometime later today.

**Comment by flukeout** [comment]
@MandyRawls You should have received an email with your log-in details, let me know if you haven't. You should be able to edit the page now, you'll find it in the Pages section.

Here's a [direct link](https://mofo.build/wp-admin/post.php?post=698&action=edit) to edit the roadmap.

**Comment by flukeout** [comment]
@MandyRawls any updates or questions on this stuff? Were you able to access & edit it? Do you need help adding it to any of the menus on the site etc? 

Let me know!

**Comment by flukeout** [comment]
Okay, closing. Please file any requests as new issues.

**Comment by MandyRawls** [comment]
@flukeout apologies for the delayed response - was ooo last week. When I click on the the direct link above to edit, it says I don't have access. can you check my permissions? Thank you!

**Comment by flukeout** [comment]
@MandyRawls Check your email for an invite link, i sent it about 8 days ago. Let me know if it's not there.

**Comment by MandyRawls** [comment]
@flukeout I was able to create the account and have access to the .build site. but when I click the direct link above to edit the onboarding page I get this:  
![screen shot 2017-01-17 at 2 27 20 pm](https://cloud.githubusercontent.com/assets/16339140/22036354/31e7ae48-dcc1-11e6-9f4b-f3794368b1f3.png)

**Comment by flukeout** [comment]
@MandyRawls okay - let me double-check!

**Comment by MandyRawls** [comment]
@flukeout - thank you!

**Comment by flukeout** [comment]
@MandyRawls Ok, please try again, I've upgraded you to an "Editor" (sorry, should have done that right away).

![image](https://cloud.githubusercontent.com/assets/25212/22036567/db14fd04-dca8-11e6-8ead-a240a1ffe719.png)

**Comment by MandyRawls** [comment]
@flukeout it worked, thank you! I will start editing/updating and will let you know if I have any issues at all (if that's okay). Were you able to update the 6 month milestone (attend all hands /celebrate 6 months) image? Also, if I create a new page for the MoFo glossary, can you add the studious fox image? Thanks!

**Comment by flukeout** [comment]
Sure thing @MandyRawls - I'll come up with a new image in the next few days. Let me know when you've started the glossary.

**Comment by xmatthewx** [comment]
page looks awesome. we should figure out where to link to it... navigation on the site is a bit weird... but there are a few places we could drop a link.

**Comment by flukeout** [comment]
@MandyRawls Looks like the content has changed, there are no more "Milestone X" headings for the first two items. Is this deliberate and is the final content on the page already? I can update styling.

**Comment by MandyRawls** [comment]
@flukeout yes, I've made some updates and final content is now on the page. Can you please 
    - Update the Allhands & header image
    - Update the layout once I have access to modify the CSS
Also, I've created the glossary page here:  https://mofo.build/onboarding-roadmap/glossary-of-myst…us-mozilla-terms/ I'm still working on making it look better, but in the meantime, can you add the glossary image you created above? Thank you!

**Comment by MandyRawls** [comment]
@flukeout just pinging on this. Thanks!
