### ISSUE TITLE
Create a new "teaching kit" template for Thimble

### ISSUE THREAD

**Issue by chadsansing** [MozillaFoundation/Design#226]
### Intro

Stacy Martin at MoCo regularly produces curriculum with collaboration from community members in privacy and security. She needs a template for a front page that links all the activities in a single module together. We used to have such a "teaching kit" template in Thimble, but now the landing page for each module on [learning.mozilla.org/activities](https://learning.mozilla.org/activities) (/activities) is made by production teammates. There is no module landing page template. We should make one that we can share in Thimble. It should look similar to pages on /activities and go with our current curriculum template. 

### Links

Looking for a page like [https://learning.mozilla.org/en-US/activities/web-lit-basics/](https://learning.mozilla.org/en-US/activities/web-lit-basics/) w/o our sidebar nav.

cc: @flukeout @xmatthewx

**Comment by xmatthewx** [comment]
cc @hannahkane

**Comment by flukeout** [comment]
@chadsansing since we don't really host the activities in Thimble anymore, but in the curriculum-db repo via github should we also make this a github-hosted page type?

**Comment by chadsansing** [comment]
@flukeout, having both would help a wider diversity of users, so yes, please. The ask in this particular case is for Thimble, but there's no reason not to put the teaching kit template in the curriculum-final repo, as well, so far as I can see.

**Comment by hannahkane** [comment]
@flukeout - is this relatively easy to do? anything I can do to help?

**Comment by flukeout** [comment]
Yeah, it shouldn't take too long. I'll create a first pass tomorrow morning.

**Comment by flukeout** [comment]
@chadsansing what components do you need on this page? Looking at the [web lit basics](https://learning.mozilla.org/en-US/activities/web-lit-basics/) page, we've got...

* Title
* Image
* Description
* Learning Objectives
* Heading + List of Activities

Each activity has
* Image
* Title
* Subtitle (_ie. Understanding credibility)
* Description
* Author Credit

Do you want all of the same stuff?

**Comment by chadsansing** [comment]
Yes - same stuff would be great, with the author credit featuring space for a(n open) open license.

**Comment by flukeout** [comment]
@chadsansing check this out and let me know if you need any changes:

**Comment by chadsansing** [comment]
This looks good - I think it suits the need. I will remix, add some tutorial-like comments for Stacy & co., and then share. We can tweak from here. Thanks, @flukeout!

**Comment by flukeout** [comment]
Sounds good, bat it around and then hand it off for tweaks. I'll close this issue now and we'll file another one when you're ready.
