### ISSUE TITLE
Document File Naming Convention on build.wmo/design

### ISSUE THREAD

**Issue by vazquez** [MozillaFoundation/Design#23]
As discussed during our workweek, this is the file name structure we should follow:

**Project-Platform-Discipline-Year-Month-Day.filename**

An example looks like this:  

`Webmaker-Mobile-UX-2015-05-31.sketch`

**Comment by cassiemc** [comment]
To close this bug we need to document it somewhere on build.wmo so I'll update the title to reflect that.

**Comment by cassiemc** [comment]
@lovegushwa Are you still able to close this for this heartbeat?

**Comment by cassiemc** [comment]
@lovegushwa update? is there anything blocking you that you need help sorting out?

**Comment by cassiemc** [comment]
@lovegushwa is going to d-bud this on Thurs with @vazquez.

**Comment by lovegushwa** [comment]
@cassiemc @vazquez @flukeout @sabrinang @kristinashu

Hi everyone, check out the file naming conventions Ricardo and I cranked through today. We split up the conventions based on intended use. Please let me know if the doc is self explanatory, and if you have any questions or concerns before I close this issue tomorrow afternoon. 

https://docs.google.com/a/mozilla.com/document/d/1AZ_TrLkdWVnRT_fAxW-kFT3o2tDgMlg_f65AKKcrtJY/edit?usp=sharing

**Comment by flukeout** [comment]
Great work @lovegushwa and @vazquez 

My only concern is keeping both the date & the version in the filename, they kind of seem to indicate the same thing, like which one was created or edited more recently?

Also, the date is meant to keep track of when the last edit was made, right?

**Comment by kristinashu** [comment]
Nice, this will be great to have. 

I also think the date isn't really necessary and adds a lot of characters to the title. But I'm all for version control so it would be great to have something like "Webmaker_Discovery-UI_01.sketch"
where "_01" is the version.

Also maybe keep to underscores for simplicity, rather than underscores and tildes.

**Comment by lovegushwa** [comment]
@flukeout @kristinashu 
Good call on the removing the date friends. @kristinashu I like your idea for the version as well.
Let me make some tweaks and we will close this puppy.

**Comment by lovegushwa** [comment]
@cassiemc @vazquez @flukeout @sabrinang @kristinashu

Hi all. You will find folder and file naming convention readme doc on the server in the template folder:

![screen shot 2015-09-11 at 10 21 26 am](https://cloud.githubusercontent.com/assets/12228435/9821437/370c88ee-586f-11e5-9aeb-109ba91a212d.png)

https://docs.google.com/document/d/1AZ_TrLkdWVnRT_fAxW-kFT3o2tDgMlg_f65AKKcrtJY/edit?usp=sharing

**Comment by cassiemc** [comment]
Nice work on this @lovegushwa. Filed a new issue to make this information publicly visible. #89
