### ISSUE TITLE
Left align footer content

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Design#233]
Feedback from Brand team: Mozilla is moving to left aligned footer content.

Let's consider the impact this would have on all of our web properties. When ready, an implementation ticket should be filed in the mofo-bootstrap repo.

**Comment by kristinashu** [comment]
🎉 It's finally happening https://redpen.io/sgdf6291a6c77baaa4 & https://github.com/mozilla/foundation.mozilla.org/issues/2546
