### ISSUE TITLE
Update Convenings Posters with new brand.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#234]
We've got some ready-made posters for convenings here: 

* https://drive.google.com/open?id=0B4Q8pzCpDS_eUy1YTkt0U1J1Vnc

**Changes Needed**

* Update them with the new mozilla branding
  * Colors, imagery, logo, type etc...
* Make sure that they print well in both color and black & white

For reference, here's one...

<img width="250" src="https://cloud.githubusercontent.com/assets/25212/26419425/92134568-4074-11e7-8ca5-a11bbe482315.png">

cc @zee-moz

**Comment by flukeout** [comment]
Question for @zee-moz - the source file looks to have three different sizes per poster. Do you know if we need all 3 or why it was set up this way? They look to be roughly the same aspect ratio, so I think if we just make one size, they can be printed at different sizes. Thoughts?

![image](https://cloud.githubusercontent.com/assets/25212/26420158/aa01c468-4076-11e7-9e52-6ff2c223d813.png)

**Comment by flukeout** [comment]
Couple of options...

<img width="300" src="https://cloud.githubusercontent.com/assets/25212/26431308/834173e6-40a8-11e7-819e-482de58e6980.png"/>

<img width="300" src="https://cloud.githubusercontent.com/assets/25212/26431314/8b9936aa-40a8-11e7-8868-3f5a9a6d0f99.png"/>

**Comment by xmatthewx** [comment]
These are great. Perfect. I would test on a not-awesome b&w laser printer. See if graphics work before pursuing that direction. And make sure black text on green is okay.

**Comment by flukeout** [comment]
Just a quick test printing the second version in color & black and white. Looks decent overall, but I think the title could be easier to read in the non-color version, I'll make some updates and test...

![image](https://cloud.githubusercontent.com/assets/25212/26462791/fe59d79c-4136-11e7-801c-fd97ddcae1d5.png)

Otherwise, I'll wait for @zee-moz to chime in on the designs and questions above (have pinged via email too).

**Comment by zee-moz** [comment]
these look great to me! @Saallen and @edrushka can you weigh in, particularly about the sizes? I know these will be used widely by Convenings team. 

Re: copy changes, @xmatthewx would some updated language be available on the network site?

@auremoser do you know how frequently the templates were edited by our communities?

**Comment by auremoser** [comment]
Nope, I provided the drive folder but no analytics on downloads, unless there's a way I can get that info that I'm not aware of.

**Comment by edrushka** [comment]
We originally designed them for people to print on a regular office printer (8.5 x 11) and then scaled up larger versions to be printed in a shop.

**Comment by zee-moz** [comment]
@flukeout here's some copy for the Global Sprint Poster. @stephwright @acabunoc any suggestions? @Saallen?

# Join our world-wide collaboration party for the open Web!
## Mozilla's Global Sprint, June 1st and 2nd, 2017.

#### Our diverse Network-- of scientists, artists, engineers, activists, educators, students, librarians, gamers and more--  is gathering in person and online to innovate in the open! We’ll be collaborating on over 80 awesome open projects– in open science, civic tech, internet policy and advocacy, learning and teaching the web, internet privacy and security, and much more… 

Everyone is welcome— you **don’t** have to be a software engineer or coder to participate. Come Sprint with us for two hours or two days, whatever works for you! 

Your local host site is:
**host:** (host name or site name)
**address:** (local site address)
**hours:** (hours)

For more info, see https://mzl.la/mozsprint       Register for your local site here:  (local site registration)

##### Participants should be aware that their contributions to projects during the Sprint will fall under each project’s own license, and may be be reused, remixed, and shared according to that license. By registering for the Sprint, participants understand and agree that any data they provide will be handled according to Mozilla’s Privacy Policy.

**Comment by flukeout** [comment]
Here are a couple of PDFs to review for you @zee-moz 

* [participation-guildelines.pdf](https://github.com/MozillaFoundation/Design/files/1032593/participation-guildelines.pdf)
* [what-is-mozilla.pdf](https://github.com/MozillaFoundation/Design/files/1032594/what-is-mozilla.pdf)

Please have a look over these and let me know if you want any changes. I'll be working on the Global Sprint poster now.

**Comment by stephwright** [comment]
<3 these @flukeout !!!  wondering if on the What is Moz poster it's worth mentioning "public online spaces" to clarify these are online vs "public spaces" in a geographic sense? 
Adore the look of them!!!

**Comment by edrushka** [comment]
If you're going to adjust the copy, you may consider adding a reference to our network and to internet health in the What is Moz poster.

**Comment by flukeout** [comment]
Thanks @stephwright - I'll make the change. Let me know if you need anything else changed. Right now I'm working on a poster for the content that @zee-moz provided above. However, I think it's way too much content to fit on one page, especially since most people will print these out on 8.5 x 11.

* Do you think we need the ``Participants should...`` disclaimer on the poster?
* Any way to cut down the two introductory paragraphs?

Let me know, in the meantime I'll do my best and post and update shortly.

cc @acabunoc also.

**Comment by flukeout** [comment]
@edrushka I asked about that earlier in the issue also and am happy to make any changes. If you have some ready-made copy to describe it, I can try working it in.

**Comment by stephwright** [comment]
That last part was a request from Abigail Phillips as a legal disclaimer for the Sprint.  I'm not sure it needs to be on this poster considering what it's for.  I'll talk to Abigail and confirm.

How about this for intro para:
Our diverse network of scientists, artists, activists, educators, students, and more is gathering in person and online to innovate in the open! We’ll be collaborating on open projects in open science, learning and teaching the web, internet privacy and security, and much more…

**Comment by flukeout** [comment]
OK, I'll leave out the disclaimer copy. I'm guessing that it's available from the sprint website, right? @acabunoc let me know if that's cool with you.

Thank you for the updated intro paragraph, I'll try that out.

**Comment by flukeout** [comment]
@stephwright @acabunoc @zee-moz Here's my first crack at the Global Sprint poster:

* [globla-sprint.pdf](https://github.com/MozillaFoundation/Design/files/1032675/globla-sprint.pdf)

I guess the idea is that participants will write in the event info into the grey boxes.

Thoughts, comments, changes??

![image](https://cloud.githubusercontent.com/assets/25212/26507535/9b54879e-4205-11e7-83a8-cd2e2d4bca93.png)

**Comment by stephwright** [comment]
FANTASTICO!  Yes, that's what the gray boxes are for. Love it! @zee-moz and @acabunoc thoughts?

**Comment by flukeout** [comment]
I'm stepping out for lunch but will be back in a bit to check in and provide the final versions.

**Comment by zee-moz** [comment]
Hey there this looks awesome! It's perfect. In terms of usability:
Will this look good in b&w?
Can this be a PDF with editable text boxes so people can type and print,
rather than handwrite each flyer?

Thanks again @flukeout

**Comment by flukeout** [comment]
I made an editable version of the poster, please try it out and let me know if it works for you. It works great for me when I open it in Acrobat Reader, less so when I open it with Mac's preview. 

* [global-sprint-editable.pdf](https://github.com/MozillaFoundation/Design/files/1032986/global-sprint-editable.pdf)

Tested in both B&W & color and it looks good. I'll prep the final files now.

**Comment by zee-moz** [comment]
Awesome! I will send them out later tonight.
Thanks again Luke!
:)

**Comment by flukeout** [comment]
Cool, I'll update the issue here with the final versions at both 8.5 x 11 and 11 x 17 in about an hour or so.

**Comment by flukeout** [comment]
Alright, here's a folder that has all three posters in both ``8.5x11`` and ``11x17``. The sprint poster should be editable in both sizes. Please try these out and let me know if there any problems or if you want any changes. I can make some minor adjustments over the weekend.

* [Mozilla Global Sprint on Google Drive](https://drive.google.com/drive/folders/0B_CPRh4f3yyqUkRNY0JpZy1CNFk?usp=sharing)

**Comment by zee-moz** [comment]
These are awesome! No changes from me. I sent them out to our Sprint Site
hosts.
Thanks for you great work on this :)
z

**Comment by flukeout** [comment]
Okay, closing this issue. The source files are in that folder as well.

@zee-moz If you need any changes or updates, please file a new issue and cc me on it.
