### ISSUE TITLE
Plan a sprint to develop Network Personas

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#235]
cc @taisdesouzalessa @sabrinang @kristinashu @flukeout

**Comment by taisdesouzalessa** [comment]
Hey @flukeout @kristinashu @sabrinang I started a draft of this plan. Would you mind taking a look at it and add your thoughts there as well? All of you have editing privileges so feel free to edit or comment. 

Or if you disagree with the whole plan feel free to add new versions below it so we can discuss.

The more eyes and feedback we have on this plan, the better:
https://docs.google.com/a/mozilla.com/document/d/1hdiRv6l7P_oWPw7XvzO__F06WsrGUaoFrXkppkG2WQ4/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
Related tickets:
#237
#238
