### ISSUE TITLE
Stickers for Chad

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#239]
https://github.com/MozillaFoundation/mpa-cryptomancer-challenge/
https://github.com/MozillaFoundation/mpa-iot-escape-room-challenge/
https://github.com/MozillaFoundation/mpa-offline-games-challenge/

**Comment by natalieworth** [comment]
cryptomancer file for reference
[01_Privacy-Arcade-crystal-sticker.pdf](https://github.com/MozillaFoundation/Design/files/1188783/01_Privacy-Arcade-crystal-sticker.pdf)

cc @chadsansing I made the type a bit lighter. I didn't want it to distract too much from the 'crystal' image though. I was going to try a 'Privacy Arcade' type option too :)

**Comment by natalieworth** [comment]
<img width="685" alt="screen shot 2017-07-31 at 1 42 10 pm" src="https://user-images.githubusercontent.com/14876567/28797422-17a56268-75f6-11e7-9c62-bfbd90931949.png">

**Comment by chadsansing** [comment]
+1

**Comment by natalieworth** [comment]
Hey Chad, I did another sticker that just focused on the 'privacy arcade' type. Let me know what you think! 
<img width="695" alt="screen shot 2017-08-21 at 2 31 48 pm" src="https://user-images.githubusercontent.com/14876567/29539198-bd1ea366-867d-11e7-9bce-fd5928015e21.png">

**Comment by chadsansing** [comment]
That's awesome. Very much captures the sentiment, @natalieworth.

**Comment by natalieworth** [comment]
@chadsansing I haven't had time to do a 3rd option yet, been super busy with Advocacy stuff :S If you're okay with these, do you know the resolution/ printing company and I can export them for print?

**Comment by chadsansing** [comment]
This is new territory for me. What's best practice for a) laptop stickers of the usual size and b) signage on a 8 x 11" or so to post outside MPA sessions at MozFest?

**Comment by natalieworth** [comment]
@chadsansing We usually use Sticker Mule (it's pretty cheap and they ship anywhere). They're templates are also easy to use. I could export them for that at maybe 2 inches and then send to you if you want to order them to your address, then just pack em in your luggage for MozFest. If the signage is pretty basic and okay on just regular office paper, I could print them in YVR and take them to MozFest with me? How many posters were you thinking and do you think you'd need help with design on that? :)

**Comment by chadsansing** [comment]
That would be stellar, @natalieworth. Please do export them that way - I'll make the order. I think 3-5 signs would definitely do the trick for MozFest - I'm not planning anything fancy or big, and will like just put those signs into sleeves and post them from session to session.

Many thanks!

**Comment by natalieworth** [comment]
Hey @chadsansing I've got the .ai files for the printer here:
[privacy-arcade-stickers.zip](https://github.com/MozillaFoundation/Design/files/1325590/privacy-arcade-stickers.zip)

The website won't let me select in inches, so I'd suggest just choosing the 7.5cm x 7.5cm stickers, and then noting that they are based on the 2.5in template from their Sticker Mule site: https://www.stickermule.com/products/circle-stickers

Let me know if you have any questions or need help!

**Comment by chadsansing** [comment]
Superb. Thank you, @natalieworth!
