### ISSUE TITLE
Clean up file structure on Drive

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#24]
Let's follow the ```_Sample Folder``` structure in Drive and clean up the stuff that is already there.

**Comment by cassiemc** [comment]
Related: https://github.com/MozillaFoundation/Mofo-Design-Handbook/issues/36

**Comment by cassiemc** [comment]
We decided this wasn't as important as doing the right thing for new projects moving forward, so am moving to a later milestone.

**Comment by lovegushwa** [comment]
all done.

**Comment by cassiemc** [comment]
Woot, thanks for doing this @lovegushwa !

**Comment by lovegushwa** [comment]
Yay, no problem ... Now need to finish documenting naming conventions.
