### ISSUE TITLE
Create logo for the Information Trust Initiative

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#240]
We need a Mozilla logo lockup for the "Information Trust Initiative"

@sabrinang - do you have a few minutes to put this together? Let's try a few quick options to run by Phillip: Mozilla coming first vs second, being larger vs smaller.

**Comment by sabrinang** [comment]
According to the [brand taxonomy guideline](https://mozilla.ninja/logosystem/), the logo is located below for initiatives and that the structure of the lockups are modular and can almost be treated as responsive. Depending on available space, longer names could be on one line or broken into two:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/2492510/29193073-b1e1f366-7dd8-11e7-981f-ea04b5945ee3.png">
If the Information Trust Initiative is a team within the organization or community as well, the logo works on top as well. I am also using the lockup proportions from the brand guide.

@xmatthewx feedback?

**Comment by xmatthewx** [comment]
Thanks @sabrinang. We can use a second color, right? 

@jessevondoom – if I'm reading "logo below" correctly in [the guidelines](https://mozilla.ninja/logosystem/), I think that applies here, but I'm not sure.  

I guess we should go with the bottom-left option, two lines, two colors. I'd nudge to shorten _information_ to _info_ and go with one line, but I don't think it'll fly.

**Comment by sabrinang** [comment]
I don't think we can use a second color (at least it isn't mentioned that we could) but I know mozilla has to be black or the limited use one-color white if it is on a dark background.

**Comment by xmatthewx** [comment]
I looked again and the guidelines don't say we can't. We've also seen lots of two color examples from MoCo for various things. I think it's essential to break up the words.

**Comment by sabrinang** [comment]
@xmatthewx This was left off a while back and I was wondering is it still needed? Let me know what is decided and how I can close this ticket?

**Comment by xmatthewx** [comment]
Nope. I don't think so. We'll re open if needed.
