### ISSUE TITLE
[NSF Initiatives] WINS Showcase & Gigabit Celebration Graphics 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#246]
## Intro
Please refer to the brief here: https://docs.google.com/document/d/1dns6fpvRH0awxF3AqiStm9RndtNL1uwRgcBj1s-PUSY/edit# and we will use this issue to track this work/questions.

We are creating graphics for social, form and email to promote two events that are co-located in Mountain View at Mozilla’s office.

### Event 1
(WINS) Tuesday, August 14
**Description:** the end the WINS Challenges (where the Stage 2 finalists will demo their working prototypes for judges live) 

### Event 2
(Gigabit) Wednesday, August 15 
**Description:** a learning and celebration event for the Gigabit Grantees.

### To Do
- [ ] Language/Copy
- [ ] Social Graphic (for Twitter)
- [ ] Email Graphic
- [ ] Form Banner Graphic

### Deadline
Will send out social on the week of the 15 of January

cc: @sabrinang @xmatthewx @jenntbeard @LindseyFrost @mehan

**Comment by xmatthewx** [comment]
@jenntbeard  @LindseyFrost - Question for ya: Will you be emailing and inviting your lists to both events at once? Or, are there some instances when you'll invite some people to one, but not the other?

**Comment by mehan** [comment]
@xmatthewx i think there will definitely be people who get invited to one and not the other.

**Comment by sabrinang** [comment]
I've iterated on potential styles for these social shares:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/2492510/34699001-fdc6c828-f48f-11e7-9c24-ee7cc354c5e0.png">
You can also comment on redpen here: https://redpen.io/p/nfae68b0f33cf5193f

I do not have the language/copy for the event themselves so I made up placeholder names for them as: "WINS Challenge Showcase" and "Gigabit Community Fund Celebration"

@jenntbeard @mehan Any feedback on what copy should be on these? Is a title and date/time/location enough (assuming these are paired with written posts)?

@xmatthewx Do you have any design feedback or preferences?

**Comment by xmatthewx** [comment]
They're all great. I prefer the two on the right. I think they will pop out a bit more on white background of an email, and hold together more in a busy social media stream. But it's not a huge difference. 

Nice speedy work.

**Comment by sabrinang** [comment]
Redpen is updated here: https://redpen.io/p/nfae68b0f33cf5193f
![image](https://user-images.githubusercontent.com/2492510/34743430-8ae83b5c-f53e-11e7-910c-6d6efe9dd107.png)

Thanks for the feedback @xmatthewx, I made the colours a bit more vibrant to stand out for social and kept the version with more whitespace for email/forms in case we need to insert accompanying text (example placeholder text: "You are invited to the") so this would design could give more hierarchy to the text.

Please let me know what dimensions and final copy is needed for email and forms. These are currently sized for twitter's 1:1 and 2:! in-stream social shares.

**Comment by xmatthewx** [comment]
These are great @sabrinang thanks. For email, all the copy should be repeated as regular text rather than relying on the image since many people will have images blocked.

**Comment by sabrinang** [comment]
@jenntbeard I would like to follow up on these since in the brief you have mentioned you would like to get these out January 17 (tomorrow). 

Have you checked out the designs on [redpen](https://redpen.io/p/nfae68b0f33cf5193f)? If they look good after your review, I can export them so you have them when you send out your communications.

**Comment by jenntbeard** [comment]
Hi, sorry, just got back to the mainland. Reviewing now!

**Comment by jenntbeard** [comment]
@sabrinang - these look awesome! I also really like the distinction in the names, thank you for that! I think the Email 2 designs (shorter/thinner) will work better as an email header. Is there a standard size for an email header? Can we also get a version of the email2 items without the "you are invited to" to use for the registration form (which I believe is being set up via Mozilla Ask - @alanmoo can tell you more about what the requirements are for visuals there, perhaps?). I believe I will be entering the email copy (and just inserting the header for visual cohesion) and creating the form myself. Let me know if I missed anything in the string. Thank you!!

**Comment by sabrinang** [comment]
@jenntbeard Thank you for your review and feedback!

I don't know if there is an e-mail standard but I think it depends on what template or format you are using. Example: mozilla newsletters have these dimensions:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/2492510/35057507-00c51a44-fb6a-11e7-93f1-7b181ec1d32e.png">
Would these dimensions work for you? or you can send me a screenshot of the template you are using?




@alanmoo I'm not familiar with Mozilla Ask so I don't know if it is specific dimensions or requirements form graphics should be?

**Comment by jenntbeard** [comment]
We didn't plan to use a format - just a regular Gmail email with the header embedded. Some of the Gigabit cities use MailChimp, but since this will only be going out to a select number of people, we figured we could just use our regular email inboxes (unless that sounds archaic). So, the dimensions you proposed seem fine to me. Thanks!

**Comment by alanmoo** [comment]
The Ask form will be embedded on the Foundation site, so any images used will simply be uploaded through the CMS for the top of the page. No specific format necessary, though Tais might have a thought on it.

**Comment by sabrinang** [comment]
Thanks for all the feedback team! 

@jenntbeard I have exported the social/email/form graphics in a gdrive folder here that includes a 1200x660 and 1200x330 formats for email or forms and 500x500 for social (with retina versions included): https://drive.google.com/open?id=1gf_s9vuHth_cNp3qxIOhLvNCqC6qOCO3

It should have everything you need, let me know if these work for you!

**Comment by jenntbeard** [comment]
Great - I don't see the "you are invited to" email versions in there - maybe I missed them? Thanks for your help and skills!!

**Comment by jenntbeard** [comment]
Argh, sorry, would it be too giant of a pain to get versions with 'NSF-' for all the WINS Challenge Showcase items so the events read 'NSF-WINS Challenge Showcase'? We want to use the shorter one but anticipate NSF complaining that we're not including them enough. It seems like both logos suffice but I would rather have those versions too just in case.

Thanks for the 'you're invited to' email versions in the folder!

**Comment by sabrinang** [comment]
@jenntbeard No worries, I'll get to the "NSF-" versions this afternoon and give you an update when then are uploaded

**Comment by jenntbeard** [comment]
Sweet, you're the best!!

**Comment by sabrinang** [comment]
@jenntbeard I updated and uploaded them to the grdive: https://drive.google.com/drive/folders/1gf_s9vuHth_cNp3qxIOhLvNCqC6qOCO3?usp=sharing

Can you check them out and let me know if they will work?

**Comment by jenntbeard** [comment]
Yes, those are great, thank you!!

**Comment by taisdesouzalessa** [comment]
Hey @jenntbeard I am working on an image for @KevZawacki  related to this project and I was wondering if you could send me a screenshot of the image that was chosen, so I can keep the communication consistent visually. Thanks!!

**Comment by jenntbeard** [comment]
Just to clarify - these were created for the final events in August. The current comms work around the WINS announcement should stay consistent with the regular WINS graphics found on the website - https://wirelesschallenge.mozilla.org/. I have those somewhere if that's what you were looking for. Otherwise, info on the final event graphics is as follows:

Hi, so far, we are using this version for Gigabit (https://drive.google.com/open?id=1K9SBn7jAePBBnduomXnRWEUvo6vYGpOo) and this version for WINS (https://drive.google.com/open?id=1kEXA1-Llm3tIvtw1LVXkgi8YqhdAECcU). However, these were created for the invites and we will be hiring an external consultant to create the event materials based off these designs, so I can't promise that they will stay exactly the same as we move into other iterations. For full range of items, [see project brief.](https://docs.google.com/document/d/1dns6fpvRH0awxF3AqiStm9RndtNL1uwRgcBj1s-PUSY/edit?pli=1#heading=h.doucrj8sfz1n)

**Comment by taisdesouzalessa** [comment]
Thanks for the clarity here, @jenntbeard. I'll connect with Kevin but I feel it is most likely we stay closer to the site, as you pointed out. Thanks for your help!
