### ISSUE TITLE
[Fellowships Landing Page] Pictures 

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#247]
Task: to get pictures from fellows during the work week that will happen in January, 2018.

Goal: to use those pictures in our fellowship website project.

Dependencies:
- to get approval from fellows to take and use their pictures on the site
- to have a photographer to take the pictures in the work week for us
- to do a list of nice to have compositions (based on the ideas we currently have on the fellowship site)

This issue is related to [this one](https://github.com/mozilla/foundation.mozilla.org/issues/895) in the foundation.mozilla.org repo

@xmatthewx here is the issue, tagging you to keep you in the loop
@jessevondoom @community-impact - do you think it is possible for us to get that? It would be nice to have some pictures so we can use in othe projects as well.

**Comment by community-impact** [comment]
Ann Marie - can you share the photos you put together that are shareable
from the fellows onboarding?

**Comment by taisdesouzalessa** [comment]
Based on Matthew's suggestion, here is a starter list of photo requests that would be very useful to us for future projects: http://bit.ly/2DC1sW1 (@kristinashu @sabrinang @xmatthewx and I will add more items as we see fit).

@community-impact do you think we will have some opportunity to have those pictures takes during the work week?

Thanks!

**Comment by HPaulJohnson** [comment]
Hi, all! I'm not sure if @xmatthewx told you but I've arranged for a photographer to be on site for the workweek next Tuesday, 1/30. I haven't been in the loop on this ticket so the remit so far has been to capture headshots for all fellows in attendance along with some group shots. We have the photographer for a full day so I can easily add in the additional shots you note in the doc above. 

If you have any questions please let me know.

**Comment by taisdesouzalessa** [comment]
This is great! Thank you so much @HPaulJohnson! 

I may add some more ideas in the shot list above  - maybe we can lock down the document by Friday (Jan 26th) EOD... Does that work for you @kristinashu @sabrinang @xmatthewx or you need more time?

**Comment by taisdesouzalessa** [comment]
Thanks for all the help here!
We got the pictures, all [stored here](https://drive.google.com/open?id=11Tr-49LVoZrzPkFhrMQQEfgWskIRrpiI)

Closing the ticket
