### ISSUE TITLE
[Personas] Accessibility and usage

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#248]
Now that we have a draft of our personas we have to think about:

- how can we make it easier for people to access and use them? 

Maybe it is aligned with discussion we had about moving design resources to the foundation site - so personas are all there with other assets

cc: @kristinashu @sabrinang @xmatthewx

**Comment by kristinashu** [comment]
We can also link to them in our design brief and make staff identify which personas they are targeting (we can help them identify which ones if needed).

**Comment by xmatthewx** [comment]
Big +1 to a link from brief to personas. 

We'll want to think about whether to make Personas public or not, via the foundation site. I haven't read the content with that in mind. And... I'd like to get the system working internally before we take on the extra work of going open. It's probably all fine, just wanted to flag it as a consideration.

**Comment by taisdesouzalessa** [comment]
While we may have a new set of personas, this discussion is still relevant. I will open a new ticket, though and attach a doc with the ideas already presented here. So we can add to that doc as new ideas come and it is more organized then a big GitHub thread.
