### ISSUE TITLE
Update design brief

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#249]
We will be moving towards an agency style set up within MoFo where in order for the digital team to start on a project staff must fill out our new brief. 

### Steps and things to consider:
- [Our current brief](https://docs.google.com/document/d/1H4rDTT7zdvOFhGlgMDIuRLlTRlAxMsU_-mUehv_iEZU/edit?usp=sharing)
- Benchmarks: research other briefs and guidelines
- Check in with Jesse, digital team and advocacy digital team
- Possible sections: 
  - RACI
  - Project Goals and Objectives
  - Project Deliverables and Requirements
  - Personas and number of users
  - Deadline and future maintenance/support
- Determine where the form will live (Google form, doc in drive)
- How can we be transparent about the process
- How will it fit in with the pipeline (Sabrina and Matthew)
- Educate staff on important of brief and the process 

cc @xmatthewx @sabrinang @taisdesouzalessa @jessevondoom

**Comment by kristinashu** [comment]
Here's the first draft https://docs.google.com/document/d/1KQnQfM04k5vJLCheV2hkbaRsw7ZrfzW66xrYIRqpt5c/edit?usp=sharing

Please add any feedback/comments! I'm trying to avoid questions about specific deliverables in order to encourage people to approach us with problems rather than solutions.

**Comment by xmatthewx** [comment]
- [ ] Update shortlink when new brief is ready: https://mzl.la/project-brief

**Comment by kristinashu** [comment]
For reference, examples of how staff have been using briefs:
- [EOY Social Creative Test](https://docs.google.com/document/d/1SrEAlwmCLG4c3zk15uyb2MW2gMA9pK5CNg0PAa_oXbk/edit)
- [IHR blog site](https://docs.google.com/document/d/1p6eEeHNRmLGU4os82F9IRZxQDKoVp9GMDcK-L5fcuXw/edit) 
- [NSF Final Showcase](https://docs.google.com/document/d/1dns6fpvRH0awxF3AqiStm9RndtNL1uwRgcBj1s-PUSY/edit#heading=h.doucrj8sfz1n) 
- [MozFest Festival Guide ](https://docs.google.com/document/d/1HrdFapu28ChXPVVmwCZ7lnupDdYyDR3DMxwGwGFu0lE/edit)
- [Science site redesign](https://docs.google.com/document/d/1Z2jNumwfLM0d4cgpeF5-N-mEwiGmcWYo4NXHIUIXr7w/edit#heading=h.dt9co25s45uh)
- [MozFest 2016](https://docs.google.com/document/d/1f-ybB8x6HJ2F4JyDnN8wUdyMcO9b7VpQCLGINGgTKuA/edit)

**Comment by xmatthewx** [comment]
I've also been testing tweaks to the brief with real 2018 requests:
 - [NSF Final Showcase](https://docs.google.com/document/d/1dns6fpvRH0awxF3AqiStm9RndtNL1uwRgcBj1s-PUSY/edit#heading=h.doucrj8sfz1n)  
 - [WebLit](https://docs.google.com/document/d/1a_RK0OcgWxcBShg-4_jmxAE9cgnjFYD5n0WAL0sXzZg/edit#heading=h.jbsf2wnv5omm)
 - [D&D video](https://docs.google.com/document/d/1_N2VanU6SSLNIBY3rIUdDhMcy4QUiAGkElyGZUA1uZM/edit#heading=h.jbsf2wnv5omm)

**Comment by sabrinang** [comment]
I added a few comments on the brief but it looks good 👍

**Comment by jessevondoom** [comment]
Wondering if we should consider using an Ask form for the initial submission of the brief. Any thoughts?

In my head the process we should be hoping to get to looks something like:

1. Request for work comes in via the Ask form
2. We ask any questions needed, format into a proposal that includes time estimates, concerns, and any strategic additions suggested by OKR responsibles, etc. 
3. We work with the stakeholders to turn that proposal into a final brief

**Comment by jessevondoom** [comment]
Oh and the updated brief looks great. The only addition I'd like to see as we move into a proposal/brief format would be a section about success metrics, ideally with some concept of a roll-up to OKR. Don't think we need to request that up front, but it would be nice to know how we can best track the ongoing success of any given project.

**Comment by xmatthewx** [comment]
@alanmoo - we'd like to try using ask for our project briefs. can you help get everyone on the team set up? beyond the brief, it'll get all of us thinking about the tool and how we could be using it more on the site and pulse.

**Comment by alanmoo** [comment]
Sure, accounts for the entire production team? https://github.com/MozillaFoundation/mofo-devops/issues/new

**Comment by kristinashu** [comment]
I've created the Ask form. Here it is as a [stand alone page](https://s3.amazonaws.com/ask-mozilla/5a624bea0719a40001f03e6d.html).

iFrame code to embed the form on foundation site (I don't have admin access yet so I can't add it:
<iframe width="100%" height="580" src="https://s3.amazonaws.com/ask-mozilla/5a624bea0719a40001f03e6d.html"></iframe>

Ask doesn't allow for much styling so there are no section headers or hierarchy. This makes it seem a little longer but still workable.

If you have a mofo Coral account and would like to edit the form or see the submissions, go to https://ask.mofoprod.net/forms

**Comment by kristinashu** [comment]
The brief has been added to: https://foundation.mozilla.org/opportunity/project-brief/

@alanmoo @cadecairos replacing `s3.amazonaws.com/ask-mozilla` with `survey.mofoprod.net` seems to work now. 

@jessevondoom as much as I would like to use and support Ask, it will take some work on their end and our end before it is a good user experience and I have concerns that we will be creating unnecessary barriers for staff.

For people filling out the form: iFrame really isn't ideal and the styling of the form, mainly no section titles, makes the form seem really long.

For staff adding an Ask form (like I just did), it felt cumbersome.
- not intuitive 
- need to start an account
- viewing submissions isn't laid out well
- adding iFrame code to Foundation site isn't straightforward
- noticed users can submit the form even tho the required field was not filled in (but I do see the error when it's hosted on s3)

Would you be ok with using something different?

**Comment by xmatthewx** [comment]
A google form seems better in most ways, less good in acceptable ways.

**Comment by kristinashu** [comment]
I turned the brief into a [google form]( https://docs.google.com/forms/d/e/1FAIpQLSd5HPxYeeXK6wog7YBP9qKM-pE7ntnEid54Ikw0CAkdDZxO5Q/viewform).

If everyone is happy with this then I will add everyone as collaborators.

**Comment by xmatthewx** [comment]
Looks great. Thanks so much for setting this up!!

**Comment by kristinashu** [comment]
Excellent, closing!
