### ISSUE TITLE
Capture benchmarking process

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#25]
* Reusable benchmarks

**Comment by cassiemc** [comment]
We currently have two benchmarking processes (possibly more?) – @lovegushwa uses Pinterest, @flukeout @xmatthewx have enjoyed working in Google slides. We should weigh up the consequences of both processes and see if we can reach consensus on a tool, or at least clarity about how we explain this part of the process externally.

We should show an example and link to said tool/s. 

Note: Benchmarking might be a great way for contributors to easily collaborate with us – low consequence but a super important part of our process.

**Comment by xmatthewx** [comment]
We had success using slides for the [app icon](https://docs.google.com/presentation/d/17GIntGX--znIaTOj--F5JKNH70LvhaaAF1QtEGfB-z0/edit?usp=sharing) and [landing page](https://docs.google.com/presentation/d/1YkUNcI-Qx3Z_BOBubPf6iRaRNGfvM6EK7gtwcx1F_tI/edit?usp=sharing). I tried pinterest with the group before, but didn't get any traction. It seemed a bit inflexible. I'm glad to try it again, but feel inclined to stick with what's working.

**Comment by cassiemc** [comment]
Maybe we don't need to dictate one or the other (like adobe suite vs. sketch) but rather describe how the process works and why it's important. Both @xmatthewx and @lovegushwa have good examples of how diff tools have worked well in their different contexts.

**Comment by cassiemc** [comment]
I will just write a paragraph or two that we can link to from build.webmaker.org/design. Once I'm back from PTO.

**Comment by cassiemc** [comment]
## Benchmarking Methods

Choose whatever method works for you to capture appropriate benchmarks. It is important to annotate what's special about each benchmark. What issues does it raise? What should we be paying attention to? What should we ignore?

Most importantly, **be sure to upload screenshots and insights to the Benchmarks bug** or link to the appropriate place where benchmarks have been captured and annotated.

### A) Pinterest
Repin or upload assets as you find to a new board on Pinterest. The pro to this method is being able to reuse benchmarks across projects and build on assets others have already created. You can also capture design inspiration that isn't solely related to benchmarks. The con is the limited flexibility of the Pinterest format and that the effort is not as focused or contained.
*  Example: https://www.pinterest.com/lovegushwa/webmaker-benchmarks/

### B) Google Presentation
Capture screenshots and annotations via a google presentation. The pro is the amount of flexibility and conversation that can be around elements. The con is the closed nature of the pres and that the doc needs to be made open in order for anyone to be able to see it.
*  Example: https://docs.google.com/presentation/d/1bvMpfcuE5EdIk5MIZE5wJNCYYOiIDxyC1IVmB3ZO5mw/edit#slide=id.g63a9d7045_05

----

### Benchmarking checklist: ###
- [ ] Identify appropriate sites (or themes) to benchmark
- [ ] Identify which method you'll be using (Pinterest, Google Presentations, or Other) and be sure to link your benchmark documents on the bug
- [ ] Write up or annotate what's interesting about each benchmark

**Comment by cassiemc** [comment]
@xmatthewx Can you review the above comment https://github.com/MozillaFoundation/Design/issues/25#issuecomment-127731094 so I can potentially close this bug?

**Comment by cassiemc** [comment]
I'll add this content once reviewed to https://github.com/xmatthewx/Mofo-Design-Handbook/tree/master/Process in order to close this off.

**Comment by xmatthewx** [comment]
Looks good. You might add a bit about why we benchmark at the top. 

I created a wiki page where you can drop this section of process https://github.com/MozillaFoundation/Design/wiki/Process:--Benchmarks

**Comment by xmatthewx** [comment]
Looks good. I added my process chapter to the wiki. It includes a brief intro to benchmarks. I linked from there to your details about how to do them well. https://github.com/MozillaFoundation/Design/wiki/Process#benchmarks

**Comment by cassiemc** [comment]
oops forgot to close this a long time ago.
