### ISSUE TITLE
[MoFo Design Recap 2017] - Shareable Slidedeck

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#250]
### Description
At the end of each year, we summarize and gather the design work we have done into a slide deck. This is to document a broad overview so we can reflect, share and celebrate the projects we have worked on throughout the year!  🙌 ✨

Please refer to the curated work in this gslide link: https://docs.google.com/presentation/d/1rbTzeMy0VGt98g3m-dvfu66LODNtqPuDlngupJ-M9kE/edit#slide=id.g2d4c62b459_0_9

![image](https://user-images.githubusercontent.com/2492510/34751408-4b2a749e-f561-11e7-927e-b29f19afb78e.png)

@taisdesouzalessa @beccaklam @kristinashu @natalieworth Thank you for contributing to the deck and let me know if anything else is missing (but it is looking good to me). 

@xmatthewx Please review R?

**Comment by xmatthewx** [comment]
This is done and shared. Closing.
