### ISSUE TITLE
[MoFo Design 2018] - Progress & Recap Slidedeck

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#251]
### Description
For the start of the year, let's get into the habit of summarizing and documenting our design work progress in a slide deck throughout the year. This will provide more context to the projects we work on and it will serve as a recap document so we don't have to gather when the year comes to an end. 

It will be a document you refer to document, reflect and share the projects we will be working on! We can further check-in on this in our monthly huddles or crits too.

@xmatthewx @taisdesouzalessa @beccaklam @kristinashu @natalieworth Please contribute as you see fit in this slide deck here: https://docs.google.com/presentation/d/1CbqWc0qxfIW4rEZ8HpBbTDDy6ekyd_BMHueYvBbMOCs/edit#slide=id.g2d4c62b459_0_9

**Comment by xmatthewx** [comment]
Thanks @sabrinang for setting this up. Let's all try and add to it as the year progresses. At the end of the year, we could maybe do a recap video as @taisdesouzalessa suggested. 

The animations in the 2017 are great, but do drag down the deck/browser. Let's use them when useful, but maybe more sparingly.

**Comment by sabrinang** [comment]
@sabrinang Note to self: Create a format template so we can unify how we talk about our work (example: goal, impact etc.)

**Comment by xmatthewx** [comment]
A friendly reminder to the team ... try to populate this throughout the year.

**Comment by natalieworth** [comment]
self assigning so i can find the deck/ ticket in future

**Comment by kristinashu** [comment]
What?! It's been a year already!!! Get your stuff in!

**Comment by kristinashu** [comment]
Opened one for 2019 https://github.com/MozillaFoundation/Design/issues/455!
