### ISSUE TITLE
[MoFo Unified Design] Create a space on the Network site for design assets

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#252]
### Intro
Once we have a unified design language we can place assets (like pattern library, color swatches and other things we find useful to share with others) in the Foundation site. We would use the CMS - opportunity page as our "design home".

• A ticket was filed in mofo-devops to give admin access to Sabrina and Kristina.

cc: @kristinashu @sabrinang @xmatthewx

**Comment by xmatthewx** [comment]
Let's flip that. Launch the page first and then add/remove things as time/needs/ideas come up ... rather waiting to find time for a big lift. 

Draft is here (log in required): https://foundation.mozilla.org/opportunity/design/

cc @natalieworth @beccaklam - we can talk about this when we all meeting in a couple of weeks.

**Comment by kristinashu** [comment]
@sabrinang as part of your documenting our new styles, can you please incorporate this content and then delete that opportunity page?

**Comment by kristinashu** [comment]
@sabrinang if you're ok with it I will delete this page from our cms https://foundation.mozilla.org/opportunity/design/ and then close this ticket. That page is very out of date and your new https://foundation.mozilla.org/en/docs/brand/ is way better!

**Comment by kristinashu** [comment]
I'm deleted the out of date https://foundation.mozilla.org/en/opportunity/design/ page but here is all the content if needed.

### Resources
## Principles
The [principles](https://github.com/MozillaFoundation/Design/issues/39) we care about building into our products, our process and our team. This work is ongoing – get involved!
[DESIGN PRINCIPLES](https://github.com/MozillaFoundation/Design/issues/39)

## Templates
Standards and kits for incorporating new work into existing projects. Access our templates for [slide presentations](http://mofobuild.wpengine.com/slide_template/), [annotating designs](https://drive.google.com/a/mozillafoundation.org/folderview?id=0B_rbDAen9prkfmJkOWo4ZzM4UlpBTFVqY3NsSmNEdWdmTUVQUHlQQmZIdEhwV2NpdmQ5dzQ&usp=drive_web&tid=0ByIoeeW0a3R_UjEzdDU4NlMzYXc), creating [social share graphics](https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_efmdTWVlCOXF2b0c3NUJreElJYVphLUtGNHVWemo0aXQyRDB1UFRubXVFdTA&usp=drive_web&tid=0ByIoeeW0a3R_UjEzdDU4NlMzYXc#list), or building upon the [Webmaker UI](https://drive.google.com/a/mozillafoundation.org/folderview?id=0ByIoeeW0a3R_MUpOM1ExM3JMbmc&usp=drive_web&tid=0ByIoeeW0a3R_UjEzdDU4NlMzYXc#list).
[TEMPLATES](https://drive.google.com/open?id=0ByIoeeW0a3R_UjEzdDU4NlMzYXc)

## Assets
[Logos](https://drive.google.com/open?id=0B_rbDAen9prkZjRsMDJMa3h0WUE), [fonts](https://drive.google.com/open?id=0B_rbDAen9prkYkFhOTNBX2RpYUU), [colours](https://drive.google.com/open?id=0B_rbDAen9prkUmd1N1lFM3E0dFk) and [photography](https://www.flickr.com/photos/mozilladrumbeat/favorites/). Access working design files for all of [Mozilla Foundation’s projects](https://drive.google.com/drive/u/1/folders/0BzfN9sXlOXt1OE01ekI2LVA4RGM).
[ASSETS FOLDER](https://drive.google.com/open?id=0ByIoeeW0a3R_STBRYnYzTTJvVkk)

## Process
Learn more about how we work. Use our [design brief template](http://bit.ly/mozdesignbrief) and read about how we relish working with [design contributors](https://github.com/MozillaFoundation/Design/blob/master/README.md).
[DESIGN PROCESS](https://github.com/MozillaFoundation/Design/wiki/Process)
