### ISSUE TITLE
Design standalone site template

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#255]
Sometimes a campaign or initiative requires a standalone site. Special snowflakes. We aspire to have fewer things like this, more integration with foundation site for everyone's mutual benefit (org, and audience), but there will always be exceptions like buyers guide and nsf wins. 

Let's design a template we can hand to an agency to increase visual alignment and improve ux.

**Comment by kristinashu** [comment]
I think this is happening here https://github.com/mozilla/foundation.mozilla.org/issues/2542
