### ISSUE TITLE
Aadhaar page refinement

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#256]
Our Aadhaar campaign pages could use some design TLC. The campaign will launch this weekend, but is likely to have traffic for several weeks. So, incremental improvements can happen now or later. 

https://foundation.mozilla.org/campaigns/aadhaar/

**Comment by xmatthewx** [comment]
@kristinashu - you might collaborate with @natalieworth on this to connect with Jon. It's wildly last minute, but should be worth a little effort given the scale of that campaign. 

Natalie - this is built in the CMS so design will be humble within those constraints. A few images and better type would go a long way....

**Comment by natalieworth** [comment]
@kristinashu do you know timeline for this? I've got some time til Tuesday while waiting for a script review if you need help? We don't have anything new yet (other than the text-based ad that Becca is working on) but I can definitely help if you need?

**Comment by natalieworth** [comment]
@kristinashu oo kk I can work on Mon while you're out. :) Is it just updating the type/ spacing/ css stuff and adding possible images?

**Comment by kristinashu** [comment]
I haven't had much luck at editing the type and spacing but feel free to take a stab at it. I think it's mostly about making the images. I'm also looking for some possible icons now.

**Comment by beccaklam** [comment]
Hi @kristinashu, is there a CMS I should be working with here? Or a sketch file?

**Comment by kristinashu** [comment]
@beccaklam you might be able to login to the [CMS admin here](https://foundation.mozilla.org/admin/). If not then ping @alanmoo, he can give you access. [Here are the CMS guidelines](https://mzl.la/cms-guide).

The CMS is quite restrictive so I'm not sure you need to mock it up. But if you want to, [all Sketch files for the foundation site are here](https://drive.google.com/open?id=0B3b1KWRwjxtoMDh5Vjl1NzJ6T1E ).

And [here is one example](https://foundation.mozilla.org/opportunity/miti/) of the CMS with an image and some icons.

Thanks!

**Comment by beccaklam** [comment]
@kristinashu Okay, yeah agree there's not much that can be done with type. Do we have an icon library, or do we usually custom make them? Nat is working on images. CC: @natalieworth

**Comment by kristinashu** [comment]
No icon library. You can make custom ones or try and find some, whateves! I think the page is fairly temporary so maybe don't send too much time on them.

**Comment by beccaklam** [comment]
@kristinashu ah ok, thanks!

**Comment by xmatthewx** [comment]
We have the icons for mozfest on each issue area if that helps. I agree, let's grab low hanging fruit with quick and easy things. An image or two would go a long way.

**Comment by natalieworth** [comment]
I've got 3 image options here: https://redpen.io/p/nc84222607fb6340d9
I left the "Take Action" and "Blogs and Press" sections image free for now. I think icons maybe could be good to use their as they are more subtle/ content should stand out more on those pages.

cc @xmatthewx @kristinashu @beccaklam 

p.s. who would implement these? I don't know how to use the CMS—but if someone show's me I can definitely implement them.

**Comment by beccaklam** [comment]
@natalieworth I can implement if you like, I got access to the CMS yesterday.

**Comment by xmatthewx** [comment]
👍 👍 👍 @beccaklam - do a quick test of the images on staging or as a new draft page if possible. make sure that they work okay on various screen sizes. you can ping me or Alan or grab an engineer in the office.

**Comment by kristinashu** [comment]
Holy smokes @natalieworth! Those images are awesome.

**Comment by kristinashu** [comment]
I've styles the headings as much as I can. 

@beccaklam if you have made icons then please add them in. But if you haven't done any yet, we can do without!
