### ISSUE TITLE
Fundraising 1-pager

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#258]
Design 1 or 2 templates for 1-pagers used to engage with major funders. Design and build in gdocs for easy edits and remixing.  

Brief: https://docs.google.com/document/d/1DTn4ceC-DzvWCG_fFcCOPb3R5kYHd9yIRiLsWaFgWjk/edit#

**Comment by beccaklam** [comment]
This is done with Jessie's approval.

**Comment by xmatthewx** [comment]
yay! well done.
