### ISSUE TITLE
Meta list of guidelines

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#26]
Develop design guidelines or visual center for...
 - [ ] Webmaker brand
 - [ ] Mozilla Learning Networks
* Teach site
* Hives
* Clubs
* Thimble
 - [ ] Advocacy campaigns
 - [ ] Cross site promotion (https://github.com/mozilla/webmaker-desktop/issues/79)
- [ ] Engagement work
* Fundraising
* Partner content
* Emails
* Social
 - [ ] ... ??

Step one: add missing items to list
Step two: file issue to develop each item

cc @lovegushwa @vazquez @flukeout @sabrinang

**Comment by cassiemc** [comment]
needs an update. @xmatthewx can you link out relevant bugs?

**Comment by cassiemc** [comment]
Didn't get to this and would still like to review. Moving to next heartbeat.

**Comment by cassiemc** [comment]
I don't see any further action on this, so closing. I expect there to be lots of documentation as we move through a templatization exercise in the new year – https://github.com/MozillaFoundation/plan/issues/644
