### ISSUE TITLE
Chattanooga IoT graphic

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#260]
Create a single simple graphic that can be used for an upcoming event. 

This project must be kept short and simple given other critical things on our plate. The event team will need repurpose image for flyer and other materials. 

https://drive.google.com/open?id=1nJjMXZb0pvYsGbTvyXZ8n-QEjhxD8j4gmXkyyMNme1I

**Comment by xmatthewx** [comment]
As I mentioned at the top of the brief: We can design an image (background + title) that you can use for various marketing efforts. We can’t, unfortunately, put together materials with all the content.

**Comment by sabrinang** [comment]
@xmatthewx Design review for these IoT graphics? https://redpen.io/p/qc83a04082341bd103

It wasn't clear from the brief what copy is required but kept it minimal with a title, date and location. I also want to reach out to Katie for her review. Do I do this over slack if she isn't on github?

**Comment by xmatthewx** [comment]
These look great. Thanks! (I had suggested putting the title on there only so that they could be reused for other cities and dates. But these are great and we can revise later _IF_ another even pops up .... so no need to do that now).

Ping Katie on slack. I feel like I've seen her on github before, but her name doesn't pop up.

**Comment by KatieMitch** [comment]
@sabrinang These are great! Could we add the word workshop to the title? Or actually, a better question is, am I able to edit these as needed? I really like the look of them! Thank you so much!

**Comment by sabrinang** [comment]
@KatieMitch These are updated with **Workshop** in the title: https://redpen.io/p/qc83a04082341bd103
Graphics are exported in the folder along with an editable .ai design file that you can download and edit: https://drive.google.com/drive/folders/13mY9mdRezPJbvY43r-QU338mpQye1neC?usp=sharing

**Comment by KatieMitch** [comment]
@sabrinang These are awesome! Thank you so much! If it's okay, I might ping you on slack to see how to download the editable .ai file? When I download it, it goes into preview mode, so I bet I missed a step. Thank you!

**Comment by xmatthewx** [comment]
@KatieMitch - Sabrina is out most of this week. When you go [this folder](https://drive.google.com/drive/u/2/folders/1aeJG10LI5uqowvi4_y8VXrFZfQcP6Fdx), look for the one file `.ai` with a different icon. You can right-click or control-click to see the option to download (or highlight and find the triple dot menu toward the top). Ping me on slack if you have trouble.
