### ISSUE TITLE
Prep global sprint logo

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#261]

**Comment by stephwright** [comment]
I concur with @kristinashu's analysis of keeping logo black & white and going forward with color in the background.  However we can do this simply and quickly now would be best for this year as we really need to get a logo to our partner orgs ASAP as they are running a joint event and need to do their own planning & marketing.

Thanks so much to @kristinashu and @xmatthewx for your help!

**Comment by kristinashu** [comment]
@stephwright let me know if this will work!

Here is a quick screen cap of the logo on white and then on a background (just a placeholder background for now).
<img width="618" alt="screen shot 2018-02-08 at 9 54 34 am" src="https://user-images.githubusercontent.com/1068783/35989508-26c6ac1e-0cb6-11e8-94d0-cac2ef6560af.png">

[Here's a zip file](https://github.com/MozillaFoundation/Design/files/1708210/Logo.zip) with the logo in .eps .png and .svg file formats. But let me know if you need it in different sizes or formats.

**Comment by stephwright** [comment]
LOVE IT, @kristinashu !!!! @zee-moz ... what do you think?

**Comment by zee-moz** [comment]
@kristinashu love the colored background. is the g and p lower edge touching the black frame a reference to highlighting that happens in digital use of type? it feels a bit visually weird, but if it's part of that design idea, that makes sense. :)

**Comment by kristinashu** [comment]
@zee-moz yes, having the descenders touching is part of the typeface design https://fonts.google.com/specimen/Zilla+Slab+Highlight

**Comment by stephwright** [comment]
Sending to our partner for use then... thanks all!
