### ISSUE TITLE
Refine 2-column petition page style 

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#262]
As we prep to launch Equifax campaign today with the new 2-column petition layout, there are a few style improvements we can make. 

In the interest of time, I've made recommendations. cc @kristinashu for sanity check and follow up if needed. At some point, our default form styles would benefit from an engineer and designer tightening things side-by-side to make things click. 

# Recommendations

 - [ ] change form's header to `h2-headings-white`
 - [ ] change form's header text, removing colon
 - [ ] change form's input to `col-md-10`
 - [ ] (confirm with Sara/Jon?) change page's header: move long heading to top of content as an h4. shorten page heading. 

![image](https://user-images.githubusercontent.com/53411/36212307-96f1ec28-1171-11e8-9dd0-b7593dc46d62.png)

# Current build

![image](https://user-images.githubusercontent.com/53411/36211790-3d5984d8-1170-11e8-8d94-a8f551a14824.png)

**Comment by kristinashu** [comment]
Your suggestions look good!

**Comment by ScottDowne** [comment]
List items 2 and 4 can be done in the admin interface, which I've applied to staging here: https://foundation.mofostaging.net/campaigns/equifax-campaign-test/

1 and 3 I'm making a patch for now.

**Comment by ScottDowne** [comment]
Fixes for 1 and 3 here: https://github.com/mozilla/foundation.mozilla.org/pull/1060

**Comment by alanmoo** [comment]
This has landed.
