### ISSUE TITLE
Image Assets for Global Sprint

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#263]
### Running list of possible assets we will need:
- **Social Media**: several different image for Twitter + FB
  - call for projects
  - call for hosts
  - call for participants
- **ti.to:** large background image
- **Pulse:** default image and possibly and overlay for sprint projects
- **Blog posts:** resize photos
- 

I've started a [folder for photos](https://drive.google.com/open?id=1GVXBThqetqucquNaQ6Yb5U0q32LvldXM). I just put a few MozFest images that _might_ work. @zee-moz @tlasadea can you please add any photos you have? 

Also please add any other assets you can think of or any specific requests to the list above.

**Comment by xmatthewx** [comment]
@kristinashu - I wonder if the image on the site should use Zilla for the name of the event. If external assets use that in a moz global sprint logo, it could be confusing to then arrive on the site with a different script style. Maybe worth discussing at crit. 

https://github.com/MozillaFoundation/Design/issues/254#issuecomment-365339807

**Comment by kristinashu** [comment]
Here are comps for all the assets https://redpen.io/p/nfa717fa94ea34e63a 

@zee-moz @tlasadea let me know if you have any specific text or asset needs.

**Comment by tlasadea** [comment]
Left feedback @kristina. Looks ace.

*Temi Lasade-Anderson*
Mozilla Foundation
Slack: @tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by kristinashu** [comment]
Thanks @tlasadea! 

All the images for social media are here https://drive.google.com/open?id=1B3FRBv6Xt_uZAEPqaEsJWoib5Rl3pOwc

**Comment by kristinashu** [comment]
I think so!
