### ISSUE TITLE
Add partner logos to Global Sprint site

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#264]
Based on https://github.com/MozillaFoundation/Design/issues/254#issuecomment-364533652

@stephwright when you have them, just add any partner/supporter logos to this ticket and then I will resize them and add them to the site.

**Comment by stephwright** [comment]
Just requested logo for one confirmed partner ... hopefully will have for you this week or next.  Got a couple more in the pipeline as possibles.  Will add here as confirmed.  Thanks @kristinashu !!!

**Comment by stephwright** [comment]
![elife-full-color-horizontal 3](https://user-images.githubusercontent.com/14626242/36604790-941ef604-1873-11e8-8ef1-355e6b01ca80.jpg)
 Needs to link to: https://elifesciences.org/events/c40798c3/elife-innovation-sprint-2018

**Comment by stephwright** [comment]
Hi @kristinashu ... just checking in to see if you've got a spot figured out for these and when you think they might be available on the site?

**Comment by kristinashu** [comment]
@stephwright oh sorry, I didn't realize you wanted it up now, I was waiting for more logos.

I've just added it at the bottom of the landing page https://foundation.mozilla.org/opportunity/global-sprint/ 

Let me know if that works and if there's any specific copy it should say.

**Comment by kristinashu** [comment]
@stephwright do you have anymore logos to add? I might close this ticket and then you can just open a new one when you have more.

**Comment by stephwright** [comment]
Hi @kristinashu ... I'll go ahead and close.  The potential funders and other partners have not yet committed.  I'll open a new one if necessary.  Thanks!!!!
