### ISSUE TITLE
Add banner tag to all Global Sprint 2018 projects in Pulse

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#265]
Based on comments is https://github.com/MozillaFoundation/Design/issues/254 and design work https://redpen.io/p/nfa717fa94ea34e63a

As projects are added to Pulse we will need to add a banner to the image. I will do this manually as projects are added.

**Comment by xmatthewx** [comment]
This is great. Thanks @kristinashu for the excellent design. 

@stephwright @zee-moz @kristinashu - Should we attempt having participants add this on their own? We could give them a transparent png and a photoshop template. If most can't do it easily, we can help, but I'd like to have a clear process to maximize speed and participation, reduce extra work: 1) they post their own project with plain image. 2) they also share images with you, added to a single g-drive folder. 3) designers batch modify images. 4) we all collaborate to update images via django. Sound okay?

<img width="777" alt="image" src="https://user-images.githubusercontent.com/53411/36492468-3adca04c-16fb-11e8-892a-b3412be21620.png">

cc @acabunoc - we could explore something similar for mentor projects.

**Comment by stephwright** [comment]
That's a good question @xmatthewx ... Your plan sounds good to me.  @zee-moz @kristinashu ?

**Comment by zee-moz** [comment]
I love the banner! So great. Thanks for working on this 😸  
The process sounds OK; I'm not familiar enough with Django for Pulse to do the updating without some instruction, and we have far fewer on-staff wranglers than last year. I'm assuming we don't want non-staff doing this!
But if it's a quick process, it should be OK.
@acabunoc should weigh in as well.

**Comment by xmatthewx** [comment]
It's pretty simple. And we could hop on vidyo to all do it together side-by-side to crunch through it.

**Comment by zee-moz** [comment]
projects tend to trickle in, and people browse and select projects for collaboration well before the sprint, so we might want to do this in a few sessions, in the lead up to the event.

**Comment by xmatthewx** [comment]
Given the effort to wrangle the community and/or apply banner to a bunch of uploaded images, we have decided to skip this. We can look to do it for future sprints, perhaps an automatic overlay based on tag. I love the design!

**Comment by acabunoc** [comment]
Hi @kristinashu! I'd love to add this banner tag to the projects in the interview series. I'm happy to do this manually -- do you have the files?

**Comment by kristinashu** [comment]
@acabunoc here you go!

![pulse-banner-gs 2x](https://user-images.githubusercontent.com/1068783/38882126-44c40d86-421e-11e8-8af8-6a2b365377d6.png)
