### ISSUE TITLE
Design system for foundation graphics

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#267]
Initiate library of patterns/textures for quick campaign page headers and social graphics. Initiate library of icons. Approach as a living tool, start small.

**Comment by xmatthewx** [comment]
Nicely done. 

 - I'd adjust the language slightly so it's less about the site. Useful for email, social, docs, whatever. 
 - I wonder if we should link to flickr and a google drive folder of images. 

> I've also suggested they contact/ ping designers for help—is that an okay suggestion to leave in? 

Yep. We'd much rather share a few minutes for higher quality stuff.

**Comment by natalieworth** [comment]
Thanks @xmatthewx ! I added the feedback and have now published the page here https://foundation.mozilla.org/en/docs/how-do-i-wagtail/photo-and-image-guidelines/

If there are any other changes, feel free to reopen this ticket! :D

**Comment by xmatthewx** [comment]
Thanks. I shared a link with Kevin. I'm thinking the Mozillian is a good way to start socializing this.
