### ISSUE TITLE
Design for Annotated Privacy Policy

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#268]
Description: While reviewing the latest streaming TV devices for the buyer’s guide, Janice discovered that one privacy policy is particularly bad. We want to do an annotated version, that lives on its own page on the Foundation site, so we can drive people to it online, via a Twitter campaign targeting Roku, and asking them to update and improve it. 

## DARCI

 - Driver: @tlasadea 
 - Accountable: Lotta
 - Responsible: Temi, Jen C
 - Consulted: Janice T, Bram (Fellow), Policy Team, Ashley, Legal 
 - Informed: MoCo Social, MoCo Marketing

OKR 4 - Public Messaging
 - 4.3 - grow digital engagement by 25%

Proposed start 3/12/2018
Proposed launch 3/26/2018

Parent Issue: https://github.com/MozillaFoundation/CommsTeam/issues/1

Goals:
 1) Show consumers what a bad (or good) privacy policy looks like and why so they understand a little better what they’re agreeing to.
 2) Get Roku to at a minimum, respond to our campaign, and at best, to update their privacy policy and make it better for users.

Marketed: Email, + Paid Social main channels 

Audience: Indigo, the Influencer, Ari, the Action-taker, 1 of new 4 personas being developed for consumer audiences 

User story: As a consumer of connected devices, I want to understand what makes a good or bad privacy policy, so that I know what to look out for/what products are better when I am in the market for new devices.

**Comment by xmatthewx** [comment]
@tlasadea – This sounds very cool. Could this be set up as page authored via the CMS on the foundation site? Design could support by establishing styles within those constraints. Is there any specific engineering support you see as needed for this?

**Comment by tlasadea** [comment]
Hey@xmatthewx I *think* so. I'd love to understand design/engineering constraints. Re functionality, we're going to need design for the privacy policy itself. Currently thinking it could be a pdf that has the red pen annotations all over it. Or pehaps the page design itself could be so that the page is the policy with the annotations. I've pulled together a quasi-creative brief, [here](https://docs.google.com/presentation/d/1GBFYMxtGlsL2pPqbRW4wmyZLtixd2TuZC9a8ri9Z7xs/edit?userstoinvite=kevin@mozillafoundation.org&ts=5a9ea547&actionButton=1#slide=id.g346d7d91e1_1_1). 

Re engineering, if we go with the former idea, only thinking is how do we embed the pdf within the CMS so that it's scrollable? I know most browsers have inbuilt pdf readers, but not sure if that's possible with the Foundation site? Would it not have to hyperlink to the file? Not an ideal user experience that way. Happy to get on a call this week too!!

**Comment by xmatthewx** [comment]
How long is the policy? Do you plan to annotate the whole thing or just excerpts? It'd be great to avoid a PDF altogether, unless your primary audience is a technical/lawyer audience that will want to download and take it for offline reading. PDFs are pain to download and while there are 3rd party PDF readers, it'll be a task to make this mobile friendly. 

If we can do excerpts, we could do a series of images with some handwritten style to it. Or, we could explore using real text on the page, with annotations as CSS style.

**Comment by tlasadea** [comment]
I'm totally down to take the lead from your team's @xmatthewx. The mobile
question did come to mind this arvo, too.

The policy's pretty fricking long. It's here  Perhaps a series of images?
I'm imagining something akin to those SaaS landing pages (think Stripe)
which are pretty long, but maybe a gallery could work too.

@caltrider ^ see above.

**Comment by tlasadea** [comment]
apparently I don’t know how to finish sentences.

The privacy policy is here:
https://docs.google.com/document/d/1O4xrKn2HtsBPPPoRPR4vTNNV-gPvlsuadM9t3ZMONKs.
The annotations are in draft stage; going through legal review early next
week.

On Tuesday, 6 March 2018, Temi Lasade-Anderson <temi@mozillafoundation.org>
wrote:

> I'm totally down to take the lead from your team's @xmatthewx. The mobile
> question did come to mind this arvo, too.
>
> The policy's pretty fricking long. It's here  Perhaps a series of images?
> I'm imagining something akin to those SaaS landing pages (think Stripe)
> which are pretty long, but maybe a gallery could work too.
>
> @caltrider ^ see above.
>


-- 
*Temi Lasade-Anderson*
Mozilla Foundation
Slack: @tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by tlasadea** [comment]
Hey @natalieworth - I don't have that answer yet re all of the copy.
@caltrider and Janice Tsai and Bram (Fellow) have been working on the
annotations. Let's discuss in the kick owff meeting on Monday!

*Temi Lasade-Anderson*
Mozilla Foundation
Slack: @tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by xmatthewx** [comment]
@tlasadea - will there be a petition for visitors? or another call to action?

**Comment by tlasadea** [comment]
@xmatthewx, we're using Twitter as the mechanic to get people to share, so
the CTA is to have people tweet @Roku that their privacy policy is 💩

**Comment by xmatthewx** [comment]
from kickoff conversation today. what i heard mixed with some opinions: 

 - start with tl;dr. include strong cta tweet this at the top
 - below that, show policy. length is part of the absurdity. 
 - go for real web text, if possible, annotated inline with css style
   - avoid pdf embed. not mobile friendly. harder to get to content for audience. 
   - fall back to images of annotated text if inline web test isn't possible
   - avoid interactive stuff (too complicated to engineer, blocks quick consumption by viewers)
 - offer a few different tweetable bits throughout policy. again, avoid technical complexity. present obvious buttons for audience
 - aim for quick, prototype-y quality. this is meant as a quick hit experiment. 

I encourage @ScottDowne and @natalieworth to try a quick inline annotated paragraph in the CMS to see test possibilities and constraints, before diving deep on an approach or direction. 

Does this all sound right @natalieworth @tlasadea @caltrider ??

**Comment by tlasadea** [comment]
Thanks for the time everyone (except you @ScottDowne, you ditched us).

So next steps were: @caltrider is sending annotations to legal/compliance by Wednesday EOP.
@natalieworth @ScottDowne to experiement what the best way to display the privacy policy, keeping in mind the following:
1) Objective is to drive conversation around privacy policies + how un-consumer friendly they are. they're difficult to understand and so wonky/full of legalese. How are we supposed to understand what/where your data is going/who has access to it? 
2) We want people to be able to share annotations and/or sections of the policy that they think is 💩. CTA/button for people to be able to tweet @Roku. 
3) No pdfs pls
4) Tenative launch Mar 26th!

@natalieworth @ScottDowne when could we see your ideas post experiement/thinking?

@xmatthewx did I miss anything?

**Comment by natalieworth** [comment]
@tlasadea @caltrider Got a start on some rough iterations for the Roku page: https://redpen.io/p/ycc262f5cd69c6bc07
cc @beccaklam @xmatthewx if you want to take a look too. I'm going to revise design in morning again based on the feedback from Tais, Sabs, and Kristina—but feel free to add comments still!
cc @ScottDowne

**Comment by natalieworth** [comment]
Made some updates based on the redpen comments and added an additional option with pdf after discussing purpose of the page with @caltrider 
Let me know what you think in here https://redpen.io/p/ycc262f5cd69c6bc07
cc @xmatthewx @tlasadea @caltrider @ScottDowne 
and design feedback would be awesome too @sabrinang @taisdesouzalessa @beccaklam @kristinashu 
thanks!

**Comment by tlasadea** [comment]
Thanks Nat.

We need to not go down the PDF version - it may be easiest to implement in
terms of annotation, but it adds additional barriers for people to view the
content + engage with it.


*Temi Lasade-Anderson*
Mozilla Foundation
Slack: @tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by caltrider** [comment]
I do think we need to talk through the presentation @tlasadea, @natalieworth , @xmatthewx  . The main goal is to get people to have an emotional response to this and I feel like that is more likely to happen with the red pen, hand-written style of annotation than the scroll over, wall of text style of annotation. After reviewing all the annotations, I think we can pare them down enough to make something like that work.  The goal isn't to have people read all the annotations, it's to get them to feel that privacy policies like these are nuts and companies need to do better and hopefully laugh and share in the process.

**Comment by tlasadea** [comment]
@alanmoo when do you think we'll have a designated developer on this project? I think the only questions re functionality are around Share Progress, and using/linking the main CTA button to share progress as the action - we want people to tweet @ Roku.

@natalieworth thinks design could be done by end of this week.

**Comment by natalieworth** [comment]
Most recent design for this is here (without images as still awaiting finalized content): https://redpen.io/ct6732ac8db46650f2

Since there are limitations with the navigation on this page, I'd suggest that the content is parsed down to the top 5 points (given my time left to do the illustrations). I feel like people are not going to read the entire policy—Temi suggested in the meeting this morning to focus on what privacy policy is and why it's bad. So it could be beneficial to just focus on top 5 points of the policy rather than everything as that requires a lot of work on the users part. And I feel like if people are not able to immediately grasp why it's bad, they'll bounce/ won't share.

cc @tlasadea @caltrider @xmatthewx @ScottDowne

**Comment by natalieworth** [comment]
Also, just a note that the next step before I take designs further is to get the copy finalized as I feel like it is definitely affecting the design and build.

**Comment by tlasadea** [comment]
Hi @natalieworth love this design approach re 5 points. We're still waiting for approval from legal etc. @caltrider once we have content approved - will it fit this 5 point design? Need to ensure it will as I think this is the best approach we have for design, and if not then @natalieworth will have to go back to the drawing board.

**Comment by caltrider** [comment]
@natalieworth @tlasadea Still waiting to hear from the legal/compliance folks. I think they might have had a few other things going on this week with all the Facebook stuff.  Here's how we make this work. There are 7 sections to the policy. Let's break this down by section and do 7 points rather than 5. That will enable us to get all this in so it makes sense yet still break it down to smaller bits.

**Comment by tlasadea** [comment]
Hello @xmatthewx @natalieworth, @caltrider can provide more details on this if necessary, but sadly we're not going to be moving forward with this campaign. Legal's feedback/required framing of this policy and our annotations means that the impact becomes very very weak and it wouldn't be a great ROI. So sorry (and sad) to have to end this work. Apologies for the time wasted; we did bring legal in asap but we're unable to get the greenlight without their approval, and in this instance, their approval would result in work that just doesn't hit the mark.

😔

**Comment by xmatthewx** [comment]
cc @ScottDowne

**Comment by xmatthewx** [comment]
It was gonna be great. Hopefully there's a different chance for something similar down the line. I'm sure we'll find a use for the image share pattern you all developed.

**Comment by kristinashu** [comment]
I'm going to close this ticket now 😕
