### ISSUE TITLE
Net Neutrality Polling Graphic

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#269]
Description: We just got polling back around NN and want to create sharable content around it. 

Proposed start date: 3/5/2018 (not feasible)
Proposed launch date: 3/15/2018

Note: launch date is dependent on getting the content soon, and quick reviews of draft designs. 

## DARCI

 - Driver: @shaghdoosti
 - Accountable: Ashley 
 - Responsible: 
 - Consulted: Kevin
 - Informed: Heather, EJ, everyone on the NN slack channel 

OKR 3 - Rally Citizens

**Comment by sabrinang** [comment]
@shaghdoosti I have a few questions that will help me get started on this polling graphic:

Can you describe the format/dimensions of this sharable content or where it will be shared on? _(twitter, facebook etc.)_

Do you have the finalized copy or content of the NN polling that you want on the graphic or have the accompanying posts/copy it will be seen with? 

Also, are there any existing NN assets or materials this should visually align to?

**Comment by shaghdoosti** [comment]
Hey - 

We'll want to share it on social, twitter and potentially in emails too. 

Almost, working on get that finalized! 

Two things: 

1. Old blog post re polling: https://blog.mozilla.org/blog/2017/06/06/new-mozilla-poll-americans-political-parties-overwhelmingly-support-net-neutrality/

2. Graphics about polling: 
[Net Neutrality The Hill Screenshots(1).pptx](https://github.com/MozillaFoundation/Design/files/1787200/Net.Neutrality.The.Hill.Screenshots.1.pptx)

**Comment by shaghdoosti** [comment]
Hey, we have approved copy. This is ready for design! 

https://docs.google.com/document/d/1h65AA8pyL3DeO67eHJTj-5y4gK7nkvmcUPAZO9wU1Bg/edit?ts=5aa2fad0

**Comment by sabrinang** [comment]
Iterations on graphics for "Dear Ajit Pai:": https://redpen.io/p/tabbd9c6655a2e41b6

**Comment by sabrinang** [comment]
@shaghdoosti Updated more iterations for NN polling graphics. Do I need to add mozilla logo on these? Please leave any feedback on redpen here: https://redpen.io/p/tabbd9c6655a2e41b6

**Comment by shaghdoosti** [comment]
Done! @WillatMozFdn  or Jon will be able to help with email dimensions and ideally we'd put this in the blog post as well. 

Thank you so much for this!

**Comment by WillatMozFdn** [comment]
I'm assuming this graphic will be full-width of the email, @shaghdoosti ?  If so, specs would be 640 wide by however many tall, BUT we also need to account for 2x for retina displays, so ... I think that means 1280 wide at 72 dpi?  (@natalieworth can confirm.)  recent example is here:  https://image.e.mozilla.org/lib/fe9915707361037e75/m/3/V6_pieday-2018.jpg

**Comment by sabrinang** [comment]
@shaghdoosti I adjusted some of the graphics from the feedback: https://redpen.io/p/tabbd9c6655a2e41b6

The first two graphics are to be used with any of the 3 copy options that start with "Dear Ajit Pai". Example in context with copy post:
<img width="581" alt="example 2x" src="https://user-images.githubusercontent.com/2492510/38115602-783e0b88-3361-11e8-9607-ef0d32c19ff1.png">

For the millennials & boomers graphic, I made the arms larger with bolder type to make it easier to read. 
For the stats graphic, I also made the type bolder to make it more legible.

I exported the graphics in the twitter and email (1280px width) folders in gdrive: https://drive.google.com/open?id=11r-g9Sj_kPdnewA25W0_d8sAdaURIpyY

Please let me know if these need anymore adjustments or if there are other specific dimensions to export.

**Comment by shaghdoosti** [comment]
This is great, thank you! We're going to wait to release these once we have information about next steps of the campaign. It's so great that we're ready to go!
