### ISSUE TITLE
Design Facebook banner for top of campaign pages

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#270]
@natalieworth & @sabrinang - we have another facebook campaign page going up soon. Can we do a quick banner for the top of that page? Simple and quick like aadhaar and global sprint. 

We can take this as a chance to figure out those texture templates, brand alignment, and workflows a bit more. 

## DARCI

 - Driver: @sabrinang or @natalieworth 
 - Accountable: @xmatthewx
 - Responsible: @sabrinang or @natalieworth 
 - Consulted: Jon
 - Informed: Sara

**Comment by sabrinang** [comment]
@xmatthewx Is there a brief to this specific facebook campaign or link to the page content?

**Comment by xmatthewx** [comment]
We don't have an extended brief. Campaign is already live here: https://foundation.mozilla.org/campaigns/facebook/. There will additional pages and petitions coming soon, similar topics, similar tone. One graphic can help tie them all together. 

Note: 
 - the misalignment between header and left column is fixed, going to production soon. 
 - campaign pages with a petition on the right can't have a graphic go full width. we can address this with Wagtail, but have to stick within the constraint for now.

**Comment by xmatthewx** [comment]
I've added a DARCI above for clarity on this.

**Comment by sabrinang** [comment]
Ideas for facebook campaign banner here: https://redpen.io/p/de31732beb124711d6
@xmatthewx feedback for this graphic?

**Comment by sabrinang** [comment]
@xmatthewx I updated two more ideas to include full wordmarks so it is less abstract we are referencing CA + FB : https://redpen.io/p/de31732beb124711d6

**Comment by sabrinang** [comment]
@xmatthewx Good feedback after crit today and I adjusted option 5 to have larger wordmarks so it is more legible on mobile: https://redpen.io/ve1c5dc777abbc19b4
I also tried an emoji background version (I prefer the other option though): https://redpen.io/gkddbefaeeb7fdab95
(I also exported this version https://redpen.io/cqddc73fdbd8bb4606 for Jen's fb survey)

Files on gdrive: https://drive.google.com/drive/u/1/folders/112Z8PZJ4DjqmOT-QlY3hSfP7XIeRsdL9

**Comment by xmatthewx** [comment]
This doesn't feel quite there yet. Maybe huge reaction emoji's to fill the space? The containing boxes,  sidebar lines, and background gray feel extraneous. Maybe a plus sign between logos? Or emojis between logos. I'm just spit balling, so no need to execute what I'm saying. I think we can go more loose and editorial on this. 

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/53411/38114191-7382cd22-3375-11e8-8aff-5dbb5692d930.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/53411/38114378-18bc0510-3376-11e8-8b15-6e5d54646857.png">

**Comment by sabrinang** [comment]
@natalieworth Is iterating on this work here: https://redpen.io/p/xfaf84d05582ee00db

**Comment by natalieworth** [comment]
Finished these and we've uploaded them to the foundation site. Assets are here https://drive.google.com/drive/u/0/folders/1pZ_4u-aYoROUy7lSXx_dkw06SWsdiFJg
