### ISSUE TITLE
Design campaign landing

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#271]
After we settle on new site header and nav design, let's take a look at a minified header and nav for /campaign/ pages. The're a bit different than /opportunity/ pages with huge streams of focused incoming traffic.  

I'm thinking:
 - logo + hamburger menu at top (hiding site items)
 - subnav above page content like fellowship pages so we can have sidebar petition (too risky with long page titles?)
 - maybe donate up top somewhere too

@kristinashu - let's add this toward the top of the backlog. or maybe put in up next.

**Comment by xmatthewx** [comment]
This work should also address layout and columns for petition forms, campaign graphic, etc.

**Comment by kristinashu** [comment]
It would also be nice to show some of our other related campaigns at the bottom of the page.

**Comment by kristinashu** [comment]
@beccaklam and Scott did some work here https://redpen.io/p/gz26fa3bd26ec0cb81

**Comment by kristinashu** [comment]
Old benchmarking deck @natalieworth and @beccaklam made https://docs.google.com/presentation/d/1X31GHF9SclchaMY-K4Lo2XvUEAmmGrUjGHht-IHt0Q4/edit#slide=id.g15c71e0009_0_139

**Comment by kristinashu** [comment]
I'm going to close this ticket.

Scott is implementing this initial page https://redpen.io/gf9574a99f7765a29a

Becca will wireframe new possible features and flows in https://github.com/mozilla/foundation.mozilla.org/issues/1366
