### ISSUE TITLE
Design Fundraising Debrief Slides

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#272]
Summary: [Ashley has] a meeting with Beard, Jascha and Surman to review our asks for 2018 fundraising campaign.  We have a 5 slide deck that looks forward with some stats about 2017 which needs some serious design help!                                                    

## Results
 - OKR 6 - Be Sustainable
 - Raise 4.4 million!                  

## DARCI
 - Driver: Ashley
 - Accountable: Ashley     
 - Responsible: TBD
 - Consulted: n/a
 - Informed: n/a

## Dates
 - Proposed start date: 3/26/2018
 - Proposed launch date: 3/28/2018

**Comment by xmatthewx** [comment]
Becca recently developed a slide for major donor conversations. It's could be nice (not essential) to follow style and patterns in [that](https://docs.google.com/presentation/d/1DDBRJUdAkUFFwrlh4hMud92SLA9I7IcQrIyPwy90-8s/edit#slide=id.g34d60b9f3c_0_122).

**Comment by kristinashu** [comment]
I've cleaned up the slide design https://docs.google.com/presentation/d/1xo2etUnsROJH14xwiAxjUYiZ1ZwIsi3BsvBWLRybQHY/edit#slide=id.g2ed559ea01_0_4

Just waiting for one more slide and maybe some feedback.
