### ISSUE TITLE
Sketch Library fixes

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#274]
Library is coming along but there are a couple problems when using more complex components. 

### Issue 1 
Is that the black background isn't scalable

<img width="535" alt="image" src="https://user-images.githubusercontent.com/1068783/38588819-a67dc8c4-3cdc-11e8-92aa-7b0ebf139e04.png">

### Issue 2 
Is how text boxes don't vertically adjust depending on the length of title and paragraph text. (Although horizontally, it's working well. The arrow icon adjusts depending on the link text length!)

<img width="995" alt="image-1" src="https://user-images.githubusercontent.com/1068783/38588840-bdc32d12-3cdc-11e8-8511-99180d548037.png">

@taisdesouzalessa @beccaklam let me know if you find any solutions!

**Comment by beccaklam** [comment]
@kristinashu @taisdesouzalessa Couldn't find any solutions this morning ... but two possible workarounds?
Workaround for Issue 2: Create a one line title component and a two line title component
Workaround for Issue 1: Detach from Symbol after placing and edit. Not ideal but the spacing would already be built in.

**Comment by kristinashu** [comment]
Looks like FF uses different symbols for different numbers of lines.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/1068783/38633663-35c5d1b4-3d75-11e8-8041-1ef926ad5f29.png">

**Comment by beccaklam** [comment]
@kristinashu Nice. Yeah I think that's the only solution we have so far.

**Comment by taisdesouzalessa** [comment]
@kristinashu @beccaklam for the issue 1 we could use a hack, a plugin called [Dynamic Button Plugin](https://github.com/ddwht/sketch-dynamic-button) - the downside is that everybody will have to install this plugin (but it is only 5 of us anyways). The good part is that it makes the process faster! If you like this option let me know and I can apply the change to the library + create some sort of documentation that explains that.
![dynamic-button-hack](https://user-images.githubusercontent.com/22157921/38842335-3977dbf4-419e-11e8-94c1-ed5891aea4be.gif)

For the issue 2, if we have components with different numbers of lines, we just have to keep in mind we will need to update the component 3 times (or whatever variations we may have). I don't think it is a big issue and what FF has in place seems good.

The only thing I could think of was to keep the spacings marked in the layout so we can detach from the symbol and easily snap the new number of lines to the elements. The issue I see with this solution is that the element is now detached from symbol so once we update the symbol, the element won't be updated. I am not sure we want our comps to be automatically updated as we update symbols as things can get messy, but we could discuss that on the next meeting? Here is a demo:
![sketch-long-title-example](https://user-images.githubusercontent.com/22157921/38842426-c4522a7c-419e-11e8-8321-a258a7f8cc86.gif)
