### ISSUE TITLE
IHR graphic for consumer press

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Design#275]
Hi all,

(Also submitted a Project Brief for this issue)

Phase II of IHR press pitching focuses on consumer press: USA Today, Mashable, Teen Vogue, etc. I'm hoping for a simple graphic highlighting the ways the IHR empowers readers. Text would be something like:

_Three ways to make your personal internet experience healthier:_

_Protect yourself and your devices with strong passwords and two-factor authentication_

_Always update your computer and phone software as soon as a security update is available_

_Take an 8-day data detox at https://datadetox.myshadow.org/detox_

_Find more tips at https://internethealthreport.org/2018/participate/_

cc: @kristinashu @sabrinang @natalieworth @xmatthewx @taisdesouzalessa

**Comment by xmatthewx** [comment]
Proposed launch date: 5/1/2018
 - Driver, Accountable: Kevin Zawacki
 - Responsible: TBD
 - Consulted: PKPR (PR agency)

OKRs: 1.2, 1.3, and 4.2

**Comment by natalieworth** [comment]
@KevZawacki Cool! Do you know the resolution I should create for? Or is it open?

**Comment by KevZawacki** [comment]
Hi @natalieworth,

Is there a general resolution we use for social & blog content? That should work just fine.

**Comment by natalieworth** [comment]
@KevZawacki So I'm thinking we could do either a large infographic style image or 3 images for social size. I'm thinking something like this, but let me know what you think:

Option 1:
![artboard 9 copy 3](https://user-images.githubusercontent.com/14876567/39215854-4a7d881e-47ce-11e8-9b6a-4c4d5c8e3474.jpg)


Option 2 (this is pretty rough, but thinking we could do 3 cards for each tip):
![artboard 9 copy 2](https://user-images.githubusercontent.com/14876567/39215871-597643ec-47ce-11e8-81d0-e80ce6db8668.jpg)

**Comment by natalieworth** [comment]
cc @xmatthewx

**Comment by KevZawacki** [comment]
Hi @natalieworth,

These are excellent 😎 Not a single change from me. 

If it's possible to do both, that'd be great. If you only have the bandwidth for one, let's do the larger infographic. Many thanks!

**Comment by natalieworth** [comment]
Hey @KevZawacki Yep! Had time to do both. The smaller 3 images are in social size. I've added them to Redpen if you need to leave any comments https://redpen.io/p/drac47d9b65a7fd574
If they're all good, I can export!

**Comment by KevZawacki** [comment]
@natalieworth Legendary! 

Good to go :-) Many thanks!

**Comment by natalieworth** [comment]
@KevZawacki Sweet! Files are in google drive here :D 
https://drive.google.com/drive/folders/1IXXyUgHYnrxR39c60v5E9QHgQqFG3v6x?usp=sharing

**Comment by KevZawacki** [comment]
😁
