### ISSUE TITLE
Design items for the MoFo All Hands

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#276]
### Description

The request is design help for event materials:
- a color palette and font options 
- signage
- a slide template for the plenary presentations
- maybe a sticker design?  

___________________________
Driver: Erik Westra
cc: @xmatthewx

**Comment by sabrinang** [comment]
Chatted with Erik and we would need:

- Toronto themed all-hands brand to inform all design materials 

Some other event materials include:

- Email header for all-hands emails
- Default screen image for 4 giant TV screens in main room
- sticker or small notebook

Erik will update us with dimensions and deadlines

**Comment by westraco** [comment]
Email header size: MoCo uses a 1600x214 png, I think it'd be fine to follow that sizing.
Email header deadline: May 18

Default Screen image for main TVs: These are widescreen 16:9 HD format, so I'd say 2560×1440px would be a safe size for this.
Screen image deadline: June 1

Slide template: 16x9, based off existing MoFo templates
Slide template deadline: Kevin is hoping to have this by May 28th

Sticker (and possibly small notebook, still waiting on confirmation for that): Will order from Stickermule, but size/shape is up to you!
Sticker deadline: there's a one week turnaround on stickers from StickerMule, so I'd say May 30 to be safe.

Let me know if you need more, or if these don't work for any reason.

**Comment by sabrinang** [comment]
@westraco Sorry for the late response on getting to these assets.

Here are some various colour iterations for the email header and screen background designs: https://redpen.io/p/ry1a841020891ef900

Let me know what palette that is preferred and it can inform the items below.

Slide template (replaced some backgrounds on mozilla template): https://docs.google.com/presentation/d/1COumx-7NoW8sSLwHVuwXLFQ72Zs2OFwUvl9L-jBoGh4/edit#slide=id.g25275a8168_1_72

We can use google slides to make hackable letter-sized signs to print in the office if needed as well (various designs): https://docs.google.com/presentation/d/1_wX8VJCT8aQOG4yNzkzO2AWgVgzoPHi2Ocz1twN06mE/edit#slide=id.g27f059972f_0_0 

I'll be iterating on stickers after this.

**Comment by westraco** [comment]
Hi! Official word: the light blue iteration is the one. 
Can we update to be Foundation specific?

I'll send to Kevin and others once they're final.

Excited to see stickers!

**Comment by sabrinang** [comment]
@westraco I've exported the email headers, tv screen background, slide deck template and sign template here: https://drive.google.com/open?id=1o_oJh-TlT-BscnQ2yJvJzH3S6SnHV2Wq 
Can you review these assets and that the foundation specific wordmark is ok? 

/cc @KevZawacki

**Comment by westraco** [comment]
So, the team here (so, Lainie and I) both think these look great! I guess the foundation specific wordmark decision is one we can't specifically make, though. It seems confusing to have two different 2018 All Hands designs for different cities without the differentiation, which is how this came up.

Angela has basically told us she trusts our judgement on All Hands decisions (aka don't ask unless it's really important... haha), but the wordmark thing is maybe different. Does @xmatthewx have an opinion? I can ask Angela if I need to, but would rather avoid unless it's necessary.

**Comment by xmatthewx** [comment]
I looked at a few of the assets. I see the word foundation, but not a Mozilla Foundation logo. 

We should _not_ create a Foundation logo just for all hands. Someone at the top of the food chain decided that the foundation site should just use the regular mozilla logo. There might be two all hands, but we are one mozilla fo'eva!

**Comment by xmatthewx** [comment]
(the designs look awesome btw! nicely done.)

**Comment by westraco** [comment]
Ok cool... so I just clarified with Matthew that this means these are GREAT AND YAY. Excited to see the sticker.

Re: Swag, just an fyi, I just hopped on the MoCo order for the waterbottles they are doing as swag in SF, so if you wonder where those came from, that's how/why/where.

**Comment by westraco** [comment]
Can I share these assets directly from the google link you gave me, Sabrina? 
https://drive.google.com/open?id=1o_oJh-TlT-BscnQ2yJvJzH3S6SnHV2Wq

**Comment by sabrinang** [comment]
Thank you both for the feedback! @westraco Yes, you can share that gdrive folder directly since it sounds like they are good to go 👍 Good to hear that we will get some swag that they get in SF!

**Comment by sabrinang** [comment]
@westraco If it isn't too late for a sticker, I have exported a design on a [die-cut stickermule template](https://www.stickermule.com/template/die-cut-stickers) here: https://drive.google.com/drive/folders/1rzKyeH-da4PlEgcr9bWZ7FDcS31Bpkmj?usp=sharing 

The dimensions are 75mm x 50mm.

**Comment by westraco** [comment]
These are great. I ordered them yesterday, they'll be delivered by Wed next week, so we'll just give them out midweek. Thank you!

**Comment by KevZawacki** [comment]
Hi Sabrina,

Plenary speakers are sending over their slides today/tomorrow, and I'll be porting them into the [master document](https://docs.google.com/presentation/d/1iUQZHLMkx18u4g7AhWampEGxel6Lx-p8AfsrFhPXiLc/edit#slide=id.g3adbfdef93_0_2) you created.

Once everyone's are in, can I ping you for a design review / tweak?

**Comment by KevZawacki** [comment]
Hi @sabrinang,

The **[master slide deck](https://docs.google.com/presentation/d/1iUQZHLMkx18u4g7AhWampEGxel6Lx-p8AfsrFhPXiLc/edit#slide=id.g3adbfdef93_0_2)** is ready for your review. Thank you again for your help! 

One specific question: For the speaker intro slides (4, 5, 13, 28, 38), I'm having trouble getting headshots to fit in the right-third. What could we do instead? Perhaps we simply use a different format slide?

**Comment by sabrinang** [comment]
@KevZawacki Do you have these headshots somewhere I can access? I can try to put them in the layout or design something that works for the headshots

**Comment by sabrinang** [comment]
I put the headshots in slides 4 (Renee), 14 (Melissa), 29 (Jon) & 40 (Kasia). 
I fixed text alignment on 22-26.

You can delete slide 5 (but you have an assigned comment on it though) and if Linet is not speaking you can delete 6 or 6-12 if that is her entire section? Other than removing these mentioned slides it looks good to me @KevZawacki

**Comment by KevZawacki** [comment]
@sabrinang Heroic! Thank you for your help. I'll make those final changes momentarily.
