### ISSUE TITLE
Design banner ad for Equifax campaign

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#277]
Design a banner ad. Copy and dimensions in [this doc](https://docs.google.com/document/d/14SLkFI5QFw4A6sHnMRD7qqh_mcrUVpP-1s3_1QXvMHg/edit#heading=h.h5gtc7jne0nv)

Driver: Jon L
Accountable: Sara ?
Responsible: Designer TBD
Consulted: n/a? 
Informed: Ashley, ?

@kristinashu -  after you have all the info, let's file a quick brief to capture this. primary metadata is fine, details aren't essential there. thanks!

**Comment by kristinashu** [comment]
I've submitted a brief and asked a few questions in [the doc](https://docs.google.com/document/d/14SLkFI5QFw4A6sHnMRD7qqh_mcrUVpP-1s3_1QXvMHg/edit#heading=h.h5gtc7jne0nv). @beccaklam are you able to work this and is this enough info for you to get started?

They need an image for ads on [Politico](https://www.politico.com/) and an image for our site. There is a lot of text so maybe texture but probably no room for imagery.

#### Ad image should include:
- Mozilla logo
- Heading: #InvestigateEquifax
- Body: It’s worse than we thought. The CFPB must investigate Equifax now.
- optional Button: [need text]

#### Dimensions
- Ads: 728x90, 320x50, 300x250, 300x600, and 970x90
- Foundation site: 1080x800px

**Comment by beccaklam** [comment]
@kristinashu Yes I can work on this and it's enough to get started!

**Comment by beccaklam** [comment]
@kristinashu https://redpen.io/p/xq93f9c1597c029458 First draft, who should I ping to give feedback? Sara?

**Comment by kristinashu** [comment]
Nice! Yeah Sara for feedback/approval.

**Comment by beccaklam** [comment]
Hi @shaghdoosti, can you take a look at these designs for the Equifax campaign? https://redpen.io/p/xq93f9c1597c029458 Let us know if you need any changes. We shortened the copy for one of the ads for legibility reasons.

**Comment by beccaklam** [comment]
This was finished and final jpgs were sent to Jon L.
