### ISSUE TITLE
Button and link states: Foundation site

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#278]
### Intro

Let's do a benchmark and discuss button and link states for our Foundation site. The goal is to make it consistent and more accessible.

For instance: the default `:focus` work great in most of the site, except on our blue ghost buttons 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/22157921/43868045-92cd775a-9b20-11e8-8603-a17c316174c2.png">
It looks very faint there and difficult to identify. 

**Step 1:** benchmarks
**Step 2:** talk to Engineers in our Design Ops meeting (Gavin or Mavis) to collect their thoughts on button states, the role of browsers defaults (e.g. - navigating using tab on Chrome is a different experience than Safari or Firefox), best practices from code standpoint and do a list of changes that could be implemented. Designers and Engineers collaborate at this stage.
**Step 3:** individual tickets are filed and added to the production queue.

cc: @kristinashu @sabrinang @natalieworth @xmatthewx @taisdesouzalessa @beccaklam

**Comment by kristinashu** [comment]
This type of work is happening here https://github.com/MozillaFoundation/Design/issues/317
