### ISSUE TITLE
[Personas] Round 2 - step 1: slide deck and presentation to directors

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#279]
### Intro
Now that we have a draft set of personas, it's time to get some input from directors and see how they could be used in different teams. After meeting with Jesse, Lotta and Becca on August 16, here 
are the next steps. I added some rough plan with deadlines, let me know if the make sense to you and feel free to move them around if needed.

- [x] 1. draft the content for the slide deck to be shown to directors - expected completion date: **Aug 21**
- [x] 2.  prepare the slide deck - expected completion: **Aug 27**
- [ ] 3. review slide deck with Lotta and Jesse and tweak it based on their feedback - expected completion: **Sept 4**
- [ ] 4. Lotta and Jesse show slide deck to Ashley/Sara - expected completion: **Sept 6**
- [ ] 5. tweaks slide deck and finalize to director's meeting - **Sept 7**
- [ ] 6. this plan leaves the week from 10-14 Sept as the one Jesse and Lotta can show the slide deck to the directors (1 week before the retreat).

Meeting document can be found here: https://docs.google.com/document/d/1-6q7GE3teHNJMoU04fdS2MK-0UQcD4WHvqS4zP-y4w0/edit?usp=sharing

@taisdesouzalessa @beccaklam @jessevondoom @Lottarao

**Comment by taisdesouzalessa** [comment]
Feedback form Becca implemented, slide deck draft built. Messaged Jesse and Lotta for feedback. Slide here: https://docs.google.com/presentation/d/1BofVkXa8RhN26P6TED3BK1QEArfJCXBs4TRLk1Yg0R8/edit?usp=sharing

TO DO: Taís/Becca to improve slides visuals. Jesse/Lotta to review and give feedback.

**Comment by beccaklam** [comment]
Closing this ticket for now, opened summary ticket #307, will follow up on this work in 2019.
