### ISSUE TITLE
Buyers Guide: Promo at MozFest

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#281]
[Link to Buyers Guide Promo at MozFest Working Doc](https://docs.google.com/document/d/1u5ptsXqT1ZVU6O9hocSPaB11NongNYxkiCkCHBEHYUE/edit?usp=sharing)

Buyer's Guide is going to show up in a big way at MozFest. There are pieces that we designers need to support beyond the guide itself. 

### 1) Pre-requisites
 - [x] logo lockup #286 
    - Privacy Not Included as title? With Mozilla Buyer's Guide as logo
 - [x] scavenger hunt plan and content

### 2) MozFest

**Physical Things** #287
 - raffle
    - [x] tickets
    - [x] signage
- [x] postcard
    - buyers guide at large
    - version w/ fake sticker to call out raffle
    - (ask Marc for Europe based printer)
 - [x] *privacynotincluded.org stickers (<-- Jen really wants these)

**Digital Things** https://github.com/mozilla/foundation.mozilla.org/issues/1918
- [ ] screens
~~- [ ] mozfest schedule (list as an all day session. check w/ gideon)~~ becca: talked to gideon about this he said it was no longer possible?
- [ ] social images (variation on splash image w/ Nat)
- [x] banner ad for use on mozfest site (play with it as an ad, not as explained content)

TBD
 - [ ] human-scale creep-o-meter
 - [ ] ambition: webcam privacy slider

### 3) Post-MozFest (note: there will be few non-pto work days before launch)
 - [ ] web ads 

@caltrider - drop in any thoughts

**Comment by caltrider** [comment]
Thanks for starting this @xmatthewx . I added a couple. I think the physical presence design, the postcards/stickers, and the scavenger hunt materials will be the biggest priorities. I don't think we'll need web ads for MozFest, but for the later full launch of the guide in mid-November.

**Comment by xmatthewx** [comment]
Nice. I sorted the list into 3 phases.

**Comment by beccaklam** [comment]
### Physical space at MozFest:

- [ ] Ask jlin to see if we can get some iPads for MozFestt

**Comment by caltrider** [comment]
**Prizes and Swag:**

Candy
Stickers (*privacynotincluded.org)
Camera slider
Prizes from the buyer's guide 
       Nintendo Switch
       Harry Potter Kano Coding Kit
       Bose Headphones  
       Apple Watch
       Fitbit (or similar)
       Tile Tracker
       Mini Sphero
       Drone
       Mycroft

**Comment by xmatthewx** [comment]
@beccaklam - let's find time to check in about this when you're ready to switch gears toward promo stuff.

**Comment by beccaklam** [comment]
@xmatthewx Happy to chat this week, I'm already switching gears as the homepage design is wrapped up and we've found most of the product images.

**Comment by kristinashu** [comment]
Some copy for tweeting is [here](https://docs.google.com/document/d/1hRYn2EFAJxGjikeQqsXeeiaPOdJy37dzwi10PJTl_EA/edit#heading=h.j8n12cvme0nu).
