### ISSUE TITLE
Design Impact Statement posters for feedback

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#283]
At MozFest, we will hang a series of posters to gather feedback on MoFo's draft impact statements. 

**Process**
 - [x] create a template based on [sample content](https://docs.google.com/document/d/1TtDwtFRh472n8xprmFKjc9SsfLYNbQRKiFYfSS_yLfM/edit)
 - [x] wait for final statements
 - [ ] plan for mounting and gathering feedback (self service, and in sesssion)
 - [ ] finish in time to print and mount at MozFest

@kristinashu – let's see how things shake out this week and then figure out who can tackle this next week. 

**Description** (via @ldecoursy)

> Need design support for work related to defining MoFo's impact goal for the next few years and how we engage participants at MozFest in this work. There are two parts. First is a set of posters (4-5) with draft impact goal statements and a few prompts for people to respond to via post-it notes/stickers. That will hang in a high-traffic zone and be self-guided. Second is a similar set of posters or ways to engage folks in discussion during a 1 hour session on the same topic. May be science fair style exhibition boards or something similar. (mw: I think the same posters can work to keep things simple. just a question of how they're mounted for feedback)

More info in [planning doc](https://docs.google.com/document/d/1LTbYc2bPDd_J0hC_hZvi2MFG0haQiW29N1iQWNIdPDI/edit)

**Comment by xmatthewx** [comment]
@taisdesouzalessa might work on this depending on things wrap up with Awards/Fellowship stuff.

**Comment by kristinashu** [comment]
Here are the comps https://redpen.io/p/dce6bbbfa46131c548 along with some size references.

**Comment by ldecoursy** [comment]
@kristinashu Just commented on 2-3 minor typos. Other than those design is approved! Thank you :)

**Comment by ldecoursy** [comment]
Can we get two copies of the A1 printed? 

A0 - one copy of each poster
A1 - two copies of each poster

**Comment by ldecoursy** [comment]
Reviewed and approved. 👍 Thank you!
