### ISSUE TITLE
Design slides for board committee meeting

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#284]
This just needs a Mozilla branded template integrated. 4 slides. Contact Ashley with questions about content. 

https://docs.google.com/presentation/d/10uNpetbyC7khr2zGeHk9RG7V99fon76v3ntD3N1khzw/edit#slide=id.g33914562bf_0_621

**Comment by beccaklam** [comment]
Applied a Mozilla branded template and pinged Ashley. She is conferring with Mark and will get back to me if they need changes.

**Comment by beccaklam** [comment]
Ashley approved the designs! This is done.
