### ISSUE TITLE
MoFo print jobs for MozFest

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#285]
This ticket aims to collect all things that need to be printed for MoFo Programs that aren't core MozFest things.  Let's keep project discussion elsewhere, but gather print shop questions and finalized assets here. 

### Initiatives
 - Buyer's guide #281 
 - Impact statements #283 
 - Awards/fellowship #290 

### Job types for print shops
 - Postcard
 - Vinyl banner
 - Posters
 - Other?

### Notes
 - @gideonthomas can help gather print shop recommendations from Marc. 
 - Other than that, we will aim to manage all production on our end. 
 - Jobs should be paid for by the program itself with our coordination.
 - Sarah suggested we _don't_ print at Ravensbourne. Offsite shop can deliver cut and ready for program staff. We can use Rav as a fallback, but that will fall on us to see it through.
 - For each job, we'll need to identify the printer, contact them about specs and timeline.

**Comment by gideonthomas** [comment]
Regarding printing these: Marc suggests we use [Pixart Printing](https://www.pixartprinting.co.uk/). He's willing to share his account for this if it makes it easier. Otherwise, we can also use [SoloPress](https://www.solopress.com) for next day turnarounds if needed, but it's way more expensive.
