### ISSUE TITLE
Logo Lockup for Buyer's Guide

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#286]
Create a logo lockup consisting of '*privacy not included* and the Mozilla logo for the Buyer's Guide to be used on all promotional assets.

**Comment by beccaklam** [comment]
Hi @kristinashu @xmatthewx I mocked up some logo lockups based on the site's UI, you can find them here: https://redpen.io/p/qz6bdb2811e058ffb1 I did a variation with 'a buyers guide' tagline for instances where the logo needs context. Let me know what you think?

**Comment by kristinashu** [comment]
I've added last year's version as well. I like how it gives a different option for hierarchy.

**Comment by beccaklam** [comment]
Made some changes based on Kristina's suggestion: https://redpen.io/ch768007a402cc4ff4 If we're okay with it we can use this for instances when someone asks for a logo lockup?

**Comment by beccaklam** [comment]
Lock up:
![pni-logo-2](https://user-images.githubusercontent.com/20977376/46881255-00ef7f00-ce19-11e8-86e5-b4033fc05a37.png)

Closing ticket!

**Comment by kristinashu** [comment]
Nice! If you haven't already, can you please add this and the working file to Drive https://drive.google.com/drive/folders/1t8ob7y1myaARQ63Kdr73idxQwKeCocd-
