### ISSUE TITLE
Physical Promo for Buyer's Guide

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#287]
- [x] signage
- [x] postcards
- [x] stickers

**Comment by xmatthewx** [comment]
They've been good. Just keep in mind that it could shorten timeline by about a week, depending on when Jen is traveling.

**Comment by beccaklam** [comment]
For signage, some dimensions based on Tais' work for Fellowships and Awards #290 

## 1. Promotional Posters
(Purpose: advertise Buyer's Guide Raffle/booth)
- **Sizes:** A2
- **Content:** ??
- **Amount to print:** ??

## 2. Table Poster/Hanging over balcony poster?
(Purpose: Identify Buyer's Guide base)
- **Sizes:** A0
- **Content:** ??
- **Amount to print:** 1

## 3. Festival Guide Insert 
(Purpose: Advertise Buyer's Guide Raffle/booth)
- **Sizes:** follow these [guidelines](https://github.com/MozillaFoundation/mozfest-design-2018/issues/73#issuecomment-421189516)
- **Content:** ??
- **Amount to print:** ??? (who does this?)


Do we need anything else? Also, could the Festival Guide Insert double as the aforementioned postcard? @xmatthewx @caltrider

**Comment by beccaklam** [comment]
Sticker designs: https://redpen.io/p/yv3237593a82410b77 Hoping to send to stickermule for printer tomorrow.

**Comment by kristinashu** [comment]
Yea! I love the stickers.

**Comment by beccaklam** [comment]
print out creep-o-meter faces

**Comment by xmatthewx** [comment]
For **Fest Guide Insert**, it seems like we'll want either A6 (half letter size), or A5 folded in half to fit in Fest Guide pocket. I'm not sure when they're assembling those, but it looks like if we send to printer next Thursday the 18th, we can have it shipped for arrival Tues or Weds. 

Please double check timeline: https://www.pixartprinting.com/digital-litho-printing/printing-leaflets-flyers/

This would be the same for Awards/Fellows insert. 

I still wonder if a postcard is better (especially for buyers guide) so it can standalone without inserting, but either is fine.

**Comment by beccaklam** [comment]
Stickers have been ordered and will be shipped to Ravensbourne!

**Comment by kristinashu** [comment]
Awesome!

Yea postcards sounds good, as long as Fellowship team is ok with that.

**Comment by beccaklam** [comment]
@xmatthewx @kristinashu Would A6 still be a good size for the postcard?

**Comment by kristinashu** [comment]
Yeah sounds like A6 is the standard postcard size

**Comment by beccaklam** [comment]
@kristinashu @caltrider first draft of PNI postcard for MozFest: https://redpen.io/p/yv3237593a82410b77
@caltrider FYI, this needs to go to print Thursday. Trying to solidify with mandy to figure out what the 'thing' users do is at the Privacy and Security space. Are we missing any content?

**Comment by beccaklam** [comment]
Print files here: https://drive.google.com/drive/folders/1MdINTSq7WwUzCKIKax7-5snjPfUS57SA?usp=sharing

**Comment by beccaklam** [comment]
Just waiting on a higher res image for the A0 poster from Nat.

**Comment by beccaklam** [comment]
Got the updated PNI splash image from Nat and implemented in the A0 poster and updated the google drive. This is all done!
