### ISSUE TITLE
Improve the design brief

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#29]
@xmatthewx where is the feedback we documented today?

If possible (maybe a separate issue), it'd be great to look at examples where this is already being used and incorporate that into our feedback. @hannahkane and @HPaulJohnson have both been willing guinea pigs.

**Comment by cassiemc** [comment]
"From this brief, I know what the problem is that you're trying to solve but I can't actually tell what you're building."

Response: That's okay. This is not a functional spec, it's a creative brief so meant to meant to be a little bit open.

**Comment by hannahkane** [comment]
I took a crack at design briefs for Thimble (http://bit.ly/1fGKViX) and Badges (http://bit.ly/1GuBFFh). Happy to talk through what worked and what didn't.

**Comment by cassiemc** [comment]
I've yet to review @hannahkane's briefs, but one thing I'd really find helpful to explicitly include in the brief is, "What are your user stories? (As a ____, I want ____ so that I can _____.)"

**Comment by xmatthewx** [comment]
Added the (formula) and gave this it's own line in the brief.

**Comment by cassiemc** [comment]
This is a dupe of #20 so closing.
