### ISSUE TITLE
Design for Fellows & Awards at MozFest - master ticket with status of projects

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#290]
Follow up on this ticket:  #280. This is a clean ticket with status of each project.

## Intro

MoFo has merged Fellowships and Awards into a single team for a more aligned suite of programs. While MoFo has done a good job of promoting fellows, we haven't previously promoted the programs themselves as a strategic change-making entity. That's all gonna change at MozFest. 

### 1. **Two Posters** 
 - **Individual ticket:**  #291
 - **Sizes:** A1
- **Copies:** 4
- **Content: [here](https://docs.google.com/document/d/1hh0Nf_-EmIDOT5SG-7Vo0cJZlbKays2CGTv-3robqho/edit?usp=sharing)** - MOZILLA FELLOWS and MOZILLA AWARDS sections
- **STATUS:** A1 posters done. Stakeholder approved.

### 2. **Vinyl banner**
- **Individual ticket:** #292
- **Size:** W85cm x H200 cm - **excluding** bleed. [Template attached here.](https://github.com/MozillaFoundation/mozfest-design-2018/files/2428271/pixartprinting-template-large-format-roll-up-cube.pdf) 
- **Copies:** 1
- **Content: [here](https://docs.google.com/document/d/1hh0Nf_-EmIDOT5SG-7Vo0cJZlbKays2CGTv-3robqho/edit?usp=sharing)** - INVESTING IN LEADERS FOR INTERNET HEALTH section
-  **More info on printing:** [here](https://github.com/MozillaFoundation/mozfest-design-2018/issues/88#issue-364642873)
- **STATUS:** Done. Stakeholder Approved.

### 3. **Paper banner**
- **Individual ticket:** #293  
- **Size:** A0 
- **Copies:** 2
- **Content:** - Title: Investing in Leaders for Internet Health / Body: Visit the Fellowships and Awards booth on level 1 to learn more.
- **STATUS:** Done. Stakeholder approved. Just update to level 1.

### 4. **Festival guide postcard**
- **Individual ticket:**  #294
- **Size:** A6 (follow [these guidelines](https://github.com/MozillaFoundation/mozfest-design-2018/issues/73#issuecomment-421189516))
- **Copies:** 2000 total (about 1500 for Festival Guides and then extras for table...)
- **Content: [here](https://docs.google.com/document/d/1hh0Nf_-EmIDOT5SG-7Vo0cJZlbKays2CGTv-3robqho/edit?usp=sharing)**
- **STATUS:** Shared with stakeholder.

### 5. **Screens**
- **Individual ticket:** Nat will do - https://github.com/MozillaFoundation/mozfest-design-2018/issues/36
- **STATUS:** not started yet

### ~6. **Header artwork for table handout**~ let use the Festival guide insert/postcard for this
- ~**Individual ticket:**~  
- ~**STATUS:** not started yet. Ask Melissa if this is necessary~

### ~7. **EXTRA**~ Won't have time to make this
- ~We may have a request to print a map based on [this one](https://www.google.com/maps/d/u/0/viewer?ll=1.6150302316490137%2C-31.829173150000088&z=2&mid=1GWzr-O_HeP3FAmXjC8JyQnMEdkbvG-pW) -~ 
- ~**Individual ticket:** ~ 
- ~**STATUS:** not started yet. Talk to Ann Marie to confirm if map is necessary.~

If there are too many materials to be produced in a short amount of time, I would recommend to drop items 5 to 7 since the main communication materials would be in place (banners and posters for audience's orientation and insert for individual view).

**NOTE on printing from Gideon (from [here](https://github.com/MozillaFoundation/Design/issues/280#issuecomment-428656571))**: 
Regarding printing these: Marc suggests we use [Pixart Printing](https://www.pixartprinting.co.uk/). He's willing to share his account for this if it makes it easier. Otherwise, we can also use [SoloPress](https://www.solopress.com) for next day turnarounds if needed, but it's way more expensive. Let me know how you would like to proceed.

**Comment by kristinashu** [comment]
Amazing! Thank you for putting this all together. Sooo helpful to see.

It does seem like a lot of pieces to design for, let's all chat after stand tomorrow.

**Comment by xmatthewx** [comment]
For **4. Fest Guide Insert**, it seems like we'll want either A6 (half letter size), or A5 folded in half to fit in Fest Guide pocket. I'm not sure when they're assembling those, but it looks like if we send to printer next Thursday the 18th, we can have in shipped for arrival Tues or Weds.

https://www.pixartprinting.com/digital-litho-printing/printing-leaflets-flyers/

This would be the same for Buyers Guide insert. 

I still wonder if a postcard is better so it can standalone with inserting, but either is fine.

**Comment by kristinashu** [comment]
@xmatthewx I've updated the top comment so the Festival Guide insert is a postcard. Also crossed out the things we won't be able to get to.

**Comment by kristinashu** [comment]
@xmatthewx I've added number of copies the the first comment. Can you please take a look and update as needed?

Also, here's a very quick pass at the postcards: [Postcard A6.pdf](https://github.com/MozillaFoundation/Design/files/2474671/Postcard.A6.pdf)

I think content fits better landscape but might be odd seeing it in the Festival Guide sideways? Might wait and see what we do for the buyers guide postcard.

**Comment by xmatthewx** [comment]
Thanks @kristinashu. I'm not sure if they plan to use `1. two posters` outside of their space. Probably good to have 2 copies, but might not need 4. 

For the `4. fest guide postcard`, do you think the two sides stand okay alone? Or does it need the general content we see on the [vinyl banner](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/screens/325176528_Vinyl-Banner)? Especially since this will replace a handout at their table. Wondering if we should check with the team.  If so, we might need to go with a larger or folded sheet.

**Comment by kristinashu** [comment]
Oh ok, I thought we were using copy from the posters not the banner + poster. I will check with them to see what they want.
