### ISSUE TITLE
[Design for Fellows & Awards at MozFest] Vinyl Banner

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#292]
### For Stakeholder Approval
[Banner in Vinyl](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325176528_Vinyl-Banner)
[Banner in Vinyl in context](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325128724_Vinyl-Banner-In-Context)

### Specs
 - **Size:**  85 cm (width) x 200 cm (height) - **excluding** bleed. [Template attached here.](https://github.com/MozillaFoundation/mozfest-design-2018/files/2428271/pixartprinting-template-large-format-roll-up-cube.pdf) 
- **Content: [here](https://docs.google.com/document/d/1hh0Nf_-EmIDOT5SG-7Vo0cJZlbKays2CGTv-3robqho/edit?usp=sharing)** - INVESTING IN LEADERS FOR INTERNET HEALTH section
-  **Deadline:** Oct 18
- **STATUS:** Done. Waiting on stakeholders' approval

### Editable Artwork (for designers)
[banner in vinyl here](https://drive.google.com/open?id=1OgSJi9uUpbCH1PZ57_ELqiAPTXYVTvhK) < please note the InDesign file has 2 layers: one with the template grid and another with the artwork.

### Printing Info
[More info on printing here](https://github.com/MozillaFoundation/mozfest-design-2018/issues/88#issue-364642873)

### Printing checklist 
I usually follow those steps when sending the material to print. Just leaving those checkboxes here in case they can be useful:
- [ ] approved by stakeholders and design team
- [ ] all images are in CMYK
- [ ] all images are in 300ppi
- [ ] no double spaces between words
- [ ] line break is good and comfortable to read
- [ ] copy is correct (spelling, is there any placeholder copy, punctuation, capital letters rules)
- [ ] bleed marks
- [ ] zoom in/zoom out: any design issues? Alignment, colors?

**Comment by taisdesouzalessa** [comment]
@Melechuga and @annmarie123 here is the banner in vinyl artwork for your approval:
[Banner Vinyl](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325176528_Vinyl-Banner)
[Banner Vinyl in context](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325128724_Vinyl-Banner-In-Context)

**Comment by kristinashu** [comment]
Excellent, thanks!
