### ISSUE TITLE
[Design for Fellows & Awards at MozFest] Paper Banner A0

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#293]
### For Stakeholder Approval
[Paper Banner A0](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325179049_Hanging-Poster-Fellowships_And_Awards_A0)
[Paper Banner A0 in context](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325180326_A0-Banner-Proposal-In-Context-2). IMPORTANT: not sure the proportion related to other posters is exactly as represented in the picture. It's a guess.

### Specs
- **Size:** A0 
- **Content:** - Title: Investing in Leaders for Internet Health / Body: Visit the Fellowships and Awards booth on level (?) to learn more. **IMPORTANT: review copy with Melissa and Ann Marie. This copy is a placeholder.**
-  **Deadline:** ??
- **STATUS:** done. Waiting on feedback from stakeholders.

### Editable Artwork (for designers)
[paper banner here](https://drive.google.com/open?id=1cR5O1iHMP2eQXdqwe8ODO19cBrgfB8ET)

### Printing checklist 
I usually follow those steps when sending the material to print. Just leaving those checkboxes here in case they can be useful:
- [ ] approved by stakeholders and design team
- [ ] all images are in CMYK
- [ ] all images are in 300ppi
- [ ] no double spaces between words
- [ ] line break is good and comfortable to read
- [ ] copy is correct (spelling, is there any placeholder copy, punctuation, capital letters rules)
- [ ] bleed marks
- [ ] zoom in/zoom out: any design issues? Alignment, colors?

**Comment by taisdesouzalessa** [comment]
@Melechuga @annmarie123 here is the hanging paper banner for your approval:
[Paper Banner A0](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325179049_Hanging-Poster-Fellowships_And_Awards_A0)
[Paper Banner A0 in context](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/325180326_A0-Banner-Proposal-In-Context-2). IMPORTANT: not sure the proportion related to other posters is exactly as represented in the picture. It's a guess.

**Comment by annmarie123** [comment]
We will be on Level 1. Feel free to edit the copy and then print.

**Comment by kristinashu** [comment]
Excellent, thanks!
