### ISSUE TITLE
[Design for Fellows & Awards at MozFest] Festival Guide Insert

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#294]
@annmarie123 @xmatthewx here are two, fairly similar version for the insert:
[Postcard A6 v1.pdf](https://github.com/MozillaFoundation/Design/files/2480964/Postcard.A6.v1.pdf)
[Postcard A6 v2.pdf](https://github.com/MozillaFoundation/Design/files/2480965/Postcard.A6.v2.pdf)

I've made them postcard size A6 so they can be the thicker quality. You can also have some on their own at the booth.

Here's a sketch of the Festival Guide, a postcard is the same size as the map:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1068783/46985782-fcd59280-d0a0-11e8-81fe-acfe3903f110.png">

**Comment by xmatthewx** [comment]
Both look great. I'd advocate for fewer words, but both work.

**Comment by annmarie123** [comment]
@kristinashu my team prefers v1. Can we change the copy for Mozilla Fellows to "Mozilla Fellows: A group of technologists, activists, scientists, and policymakers working to create a more secure, inclusive, and decentralized internet." 

Also, nit pickiness warning: Mozilla Fellows appears bolder than Mozilla Awards, can we make sure they are equally bolded?

Also, can the text, Level 1, be bolded on the first page?

**Comment by kristinashu** [comment]
@annmarie123 I've made that copy and boldness updates. 

But I've actually changed the layout as well... I think landscape will actually work better here. Let me know what you think! 

[Postcard A6 v3.pdf](https://github.com/MozillaFoundation/Design/files/2485217/Postcard.A6.v3.pdf)

**Comment by kristinashu** [comment]
Approved!
