### ISSUE TITLE
Open Leadership and Event design banner

### ISSUE THREAD

**Issue by KGorr** [MozillaFoundation/Design#296]
Inquiring about an Open Leadership and Event design banner to add to our Ti.To sign up page. It's quite sad in its current state.

The language can simply say "Open Leadership & Events"

https://ti.to/Mozilla/mozilla-foundation-ole

cc: @xmatthewx @Saallen

**Comment by kristinashu** [comment]
I've pulled specs from https://github.com/MozillaFoundation/mozfest-design-2018/issues/104#issuecomment-432013881

@KGorr will one of these images work?

![tito-pattern](https://user-images.githubusercontent.com/1068783/48099341-22ebdf80-e1d4-11e8-86e7-bda4fd38eecb.jpg)
![tito-people](https://user-images.githubusercontent.com/1068783/48099342-22ebdf80-e1d4-11e8-8e3e-26c5e287ec3c.jpg)

**Comment by KGorr** [comment]
@kristinashu - thank you! I like the one with the people

**Comment by KGorr** [comment]
@kristinashu - I can grab the image but just realized Marc W is no longer on the team and he is the one who has the keys to the page. I'm going to have to figure out how to update it now...get back with you soon!

**Comment by KGorr** [comment]
AHA! Figured it out: https://ti.to/Mozilla/mozilla-foundation-ole It seems small...is that OK?

**Comment by kristinashu** [comment]
Oh weird. I'm not really familiar with tito but thought it would look like the mozfest one https://ti.to/Mozilla/mozilla-festival-2018

**Comment by KGorr** [comment]
@kristinashu - thank you for sharing that link! I poked around a little more and found a different spot to upload the image. It looks much better now! https://ti.to/Mozilla/mozilla-foundation-ole

Thanks for your help.

**Comment by kristinashu** [comment]
Ah awesome!
