### ISSUE TITLE
Prep PR assets for Buyers Guide

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#299]
Next week (Tuesday), we have a press event for the Buyers Guide. The PR agency has requested 2 assets. We can reach out to Lotta with questions, but if answers don't come quickly, we might have to make best guesses.  

cc: @kristinashu to help triage

1) Side by side comparison of a few popular products
 - They suggest: Google Home vs. Amazon Echo; Apple TV vs. Google Chromecast"
 - Format: letter size print 
 - mw: Let's consider a 3rd more unexpected/fun pairing. Maybe ask @caltrider for ideas

2) "Animated gif of the meter moving from Not Creepy to Super Creepy, ideally so you can you can see the name of the product and review" 
 - optimized for sharing
 - mw: We could just capture it from the screen but should probably hide extraneous elements to optimize it
 - mw: we should consider an alt option more optimized for social ... with just title, background product image, and large slider with minimal UI and text. 

<img width="490" alt="image" src="https://user-images.githubusercontent.com/53411/48085845-68ef7600-e1c9-11e8-8f98-0d68de9c2205.png">

**Comment by kristinashu** [comment]
1. Side by side comparison of a few popular products
- Jen recommends we do either Dot Creativity vs Harry Potter Wand and
Switch vs. Playstation (@caltrider please edit comment if you want to update)
- Is there any particular content/criteria they want to highlight? Knowing why the want to compare products in the first place would help guide us.

2. "Animated gif of the meter moving from Not Creepy to Super Creepy, ideally so you can you can see the name of the product and review"
- yeah let's do something custom for this so there isn't all the other noise (just the product image + title + creep-o-meter)
- Possible products are: Nintendo Switch and Bose headphones

cc @natalieworth who will probably be the one mocking these up and @beccaklam for ideas!

**Comment by natalieworth** [comment]
@xmatthewx @kristinashu For the animated Mockup, is this something that is going to be visually displayed at the PR event? Or is it for social? Just wondering what size or the format it'll be displayed on if it's something other than social media.

**Comment by natalieworth** [comment]
Also @xmatthewx @kristinashu are the product 'vs.' images going to be printed at the event? How is everything going to be displayed?

**Comment by kristinashu** [comment]
Will just use social assets https://github.com/mozilla/foundation.mozilla.org/issues/2090
