### ISSUE TITLE
UI for our build.wmo/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#30]
Design: @vazquez 
QA: @cassiemc

Based on the wireframe here: https://cloud.githubusercontent.com/assets/2492510/8342884/98446704-1a84-11e5-956a-b36ae8a21325.JPG

User stories here: https://github.com/MozillaFoundation/Mofo-Design/issues/27#issuecomment-119279919

**Comment by vazquez** [comment]
File: https://drive.google.com/a/mozilla.com/file/d/0ByIoeeW0a3R_Tm94VWthaWxkamM/view?usp=sharing

Current progress and iterations:

![r copy 2](https://cloud.githubusercontent.com/assets/1119821/8384242/922b1cca-1bf4-11e5-82ba-89516e3689f7.png)  
---
![r copy 3](https://cloud.githubusercontent.com/assets/1119821/8384243/922c61de-1bf4-11e5-8763-143204f27a1f.png)  
---
![r copy 4](https://cloud.githubusercontent.com/assets/1119821/8384241/922992e2-1bf4-11e5-86e4-370680780b38.png)

**Comment by cassiemc** [comment]
From the benchmarking exercise @lovegushwa and I did, it seems like the blocks design is A) too similar to material design, B) doesn't grow very well and C) isn't very scannable. Let's also make the colors less googley. :) cc @vazquez

**Comment by cassiemc** [comment]
@vazquez is away this week so I will take over the UI.

**Comment by cassiemc** [comment]
Here's an update, redpen here: https://redpen.io/yv6e5118d61a8af297 (Background illustration TBD, perhaps we could make it seasonal)
Feedback? @lovegushwa @flukeout @xmatthewx @vazquez @sabrinang 

![build-design-v2](https://cloud.githubusercontent.com/assets/1186326/8606302/adfa4a66-2658-11e5-8359-49da0774dfc1.png)

**Comment by xmatthewx** [comment]
Lookin' real nice. 

We previously grouped templates with guidelines. @lovegushwa mentioned in Whistler that guidelines are best baked into templates/tools. The idea rings true. The 4th section could probably just be called process, though I worry that it will be stale content that nobody reads, like my chapter on process.  

As usual, I would reduce the words on this page. 
 - Remove label "popular resources"
 - Shorten the paragraph to: "Questions? Send us a note"

Lastly, we might put our values on this page itself when they're ready.

**Comment by cassiemc** [comment]
@xmatthewx thanks for the feedback! I've worked a bit more on the IA in https://github.com/MozillaFoundation/Mofo-Design/issues/32#issuecomment-119672343. Would love feedback on that aspect there. +1 it might be nice to have an intro to principles right on this page in the future.

I kinda liked a *bit* more of an intro to the team than 'Questions? Send us a note.". The writing could definitely be more exciting.

**Comment by cassiemc** [comment]
I updated the redpen here with the latest design (also below): https://redpen.io/yv6e5118d61a8af297
Feel free to adjust elements as needed in the build for illustration or other needs. Hoping @vazquez and @sabrinang can make those tweaks as they arise, while I'm on PTO.

The .psd and latest png are in Drive / Design Assets / build.webmaker.org

![build-design-v3c](https://cloud.githubusercontent.com/assets/1186326/8759694/9f59029c-2cc8-11e5-9df7-c790b05ed60b.png)

(copying this comment to the build ticket #52)
