### ISSUE TITLE
Build Donate Banner for mozilla.org

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#301]
To foster donations via mozilla.org, we will run a banner on the site similar to what we used last year. 

Goal: Launch 11/27 for Giving Tuesday

 - Design: @kristinashu 
 - Fundraising: @WillatMozFdn 
 - PM: @xmatthewx 
 - Consulted: @jessevondoom 
 - Build: @craigcook

**Comment by xmatthewx** [comment]
Parameters for links

```
utm_source=mozilla.org
utm_medium=referral
utm_content=banner
utm_campaign=2018wk1
```

**Comment by xmatthewx** [comment]
Localization

 - Dollar sign for US, Canada, Australia and NZ
 - Euro version for use in the EU
 - Everyone else gets the no-suggested-amounts version with just the donate button

**Comment by xmatthewx** [comment]
### Responsive Design Comps

## Mobile

<img width="398" alt="image" src="https://user-images.githubusercontent.com/53411/48792446-4a59a680-ecc2-11e8-8ea2-96c5c177113d.png">


## Desktop

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/53411/48792395-25fdca00-ecc2-11e8-98f3-885047569f3c.png">

## Mid-sized screen

<img width="870" alt="image" src="https://user-images.githubusercontent.com/53411/48792421-3ada5d80-ecc2-11e8-9f5a-c5c64301aa6d.png">

**Comment by xmatthewx** [comment]
### Localized Comp

 - No suggested amounts outside US, Canada, Australia, NZ, EU

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/53411/48792363-12526380-ecc2-11e8-876d-93b52888c0a0.png">

**Comment by xmatthewx** [comment]
### Background image file

![heart-pattern](https://user-images.githubusercontent.com/53411/48792792-2c407600-ecc3-11e8-9bb7-60141f739d2d.jpg)

**Comment by kristinashu** [comment]
Here's the Sketch for the comps and the Illustrator file for the background pattern: https://drive.google.com/drive/folders/1O96mYtGhCqrQGTUjtGODG9jdzIO2Qngz?usp=sharing

**Comment by kristinashu** [comment]
Hi @craigcook, Matthew shared your progress with me https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/ It's looking good and I much prefer the square buttons!

Just a few thoughts:

1) The banner text should say with the grid of the main site (for all screen widths). 

2) Please reduce the gap between the body copy and the radio buttons (so it has a similar amount of gap above and below the radio buttons).

Screen cap from staging:
![desktop](https://user-images.githubusercontent.com/1068783/48807051-2ce00900-ecd1-11e8-9716-f73f5914b261.jpg)

Comp with grid view:
<img width="1360" alt="screen shot 2018-11-20 at 2 16 07 pm" src="https://user-images.githubusercontent.com/1068783/48806773-3c128700-ecd0-11e8-8775-d63c5e1a6e51.png">

3) The $20 and $10 buttons are just slight over to the right, please make the line up with the test of the content.

Screen cap from staging:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1068783/48807265-de7f3a00-ecd1-11e8-9529-15611d1caa21.png">

Thanks!

**Comment by craigcook** [comment]
I've pushed updates to https://bedrock-demo-craigcook.oregon-b.moz.works

I also wanted to ask about UTM parameters we're passing through to donate.m.o. Here's what I have at the moment:

```
<input type="hidden" name="ref" value="EOYFR2018">
<input type="hidden" name="utm_campaign" value="EOYFR2018">
<input type="hidden" name="utm_source" value="mozilla.org">
<input type="hidden" name="utm_medium" value="referral">
<input type="hidden" name="utm_content" value="banner">
```

Will that work for your purposes? It's identical to last year except for updating "EOYFR2017" to "EOYFR2018".

**Comment by craigcook** [comment]
Oh and now I see you provided params above... oops! I'll update.

**Comment by kristinashu** [comment]
Banner is looking sweet! I like how you've put the radio buttons on one line.

**Comment by xmatthewx** [comment]
This _is_ looking sweet. Very slick. 

Two tiny things, neither should be a blocker to launch. 
  1) At some screen widths, the X-to-close button touches the header text. Text could use a little right margin. 
  2) Second row amount buttons are bumped toward the right. 

Thanks again for the great speedy work!

<img width="676" alt="image" src="https://user-images.githubusercontent.com/53411/49041043-2b5f8680-f192-11e8-82cf-014e3d08de48.png">

**Comment by kristinashu** [comment]
It's live and looking good!
