### ISSUE TITLE
Prep for Global Sprint

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#302]
Let's prep for Global Sprint! This is a temporary planning ticket based on a conversation with Zannah. 

It'll be a bit earlier this year: 
 - Sprint: March 29-30
 - Announced: mid-January

Tasks
 - [ ] Design a banner with name and artwork to match current site/brand
    - Let's start this soon so it is ready in December if needed for video title cards
    - Just title. Don't let content be a blocker. We can add that later as stuff is confirmed and needed.
 - [ ] get list of key milestone & dates
 - [ ] gather list of graphic design assets
 - [ ] help diagram and streamline the workflow
   - priority is to simplify for participants. hosts and project leads have more support from staff
   - increase the content captured and shared on the site and pulse for more long-term exposure of people and projects

cc @sabrinang @kristinashu @alanmoo

**Comment by kristinashu** [comment]
Err what's happening with this? Do we still need to do anything for Global Sprint?

**Comment by xmatthewx** [comment]
Gideon has been primary facilitator. Last I asked he said we didn't need any design things. We can discuss at design huddle.

**Comment by kristinashu** [comment]
Going to close this and we can open a new ticket if Global Sprint team opens a brief for some work.
