### ISSUE TITLE
Update buyers guide grahpic on medium

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#303]
From slack:

Mozilla, when used in a sentence should not be logo style. Should just be written. I think the way you’ve got it is a fine exception and more impactful … but maybe remove the word “by” and move the logo to the bottom? or just type the name out.

https://medium.com/@harraton/how-we-evaluated-the-products-in-mozillas-privacy-not-included-buyer-s-guide-2018-6b122f885de0

**Comment by kristinashu** [comment]
No rush on this! Just give Jen the image next week and she can update the Medium post.

**Comment by kristinashu** [comment]
Nat did it! https://github.com/mozilla/foundation.mozilla.org/issues/2090#issuecomment-440839670

**Comment by beccaklam** [comment]
Thanks @natalieworth !

**Comment by natalieworth** [comment]
@caltrider When you're back from turkey times, I've got the image in here to update on the blog:
https://drive.google.com/open?id=15qh86j_OgQN84urpeZef3eJNgZjuACQk&authuser=natalie@mozillafoundation.org

**Comment by natalieworth** [comment]
![medium-background-pni](https://user-images.githubusercontent.com/14876567/48918653-e1e60300-ee42-11e8-8bee-adb87fd7eeca.jpg)

**Comment by caltrider** [comment]
Medium blog post updated. Thanks @natalieworth

**Comment by kristinashu** [comment]
@caltrider can you please ask Janice to update the image in this post? https://medium.com/@harraton/how-we-evaluated-the-products-in-mozillas-privacy-not-included-buyer-s-guide-2018-6b122f885de0

**Comment by caltrider** [comment]
@kristinashu Done! She said she was at an appointment but would have it done in a couple hours. Is there anywhere else that image needs to be replaced?

**Comment by kristinashu** [comment]
Looks like there's at the bottom here https://medium.com/read-write-participate/tips-to-avoid-buying-the-creepiest-gifts-this-holiday-season-ab269c3b68df

**Comment by caltrider** [comment]
Oh, good catch. What a weird place for me to stick that image. I've swapped it out now.

**Comment by kristinashu** [comment]
Found this one! But I think we can leave it. https://medium.com/@moz2000tw/%E5%B9%B4%E7%B5%82%E8%B3%BC%E7%89%A9%E9%9A%B1%E7%A7%81%E9%98%B2%E8%AD%B7%E6%8C%87%E5%8D%97-1d95c9e81819

**Comment by caltrider** [comment]
Ha! I would have no idea how to go about getting that one changed. Go Taiwan.
