### ISSUE TITLE
Spruce up new Leadership Giving page

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#306]
We have a new staff authored page for major donors. It could use a little design TLC. 

 - [x] Clean up headers. add bullets. a table or two might be useful. does wagtail let us do tables?
 - [x] Consider a graphic or two (let's talk with stakeholder first). no need to block part 1. 

Consulted: Jesse Ward

 - url: https://foundation.mozilla.org/en/initiatives/leadershipgiving/
 - cms: https://foundation.mozilla.org/cms/pages/253/edit/

cc: @kristinashu to triage

**Comment by xmatthewx** [comment]
Jesse W says: 

> We were hoping to include the link to a small group of prospects we are emailing this week (likely Thursday morning), but no worries if that isn't feasible. After this week's send, the next target date would be for some end-of-year follow-up starting next Wednesday.

**Comment by xmatthewx** [comment]
Jesse W prepped [a doc](
https://docs.google.com/document/d/1DTgg1X1AIrfW5lQgiyr-uqSzlbMVvODVzfon4PvKSac/edit) with a bit more layout than we see in the CMS. If we can't yet do tables in wagtail, we should discuss it with Alan.

**Comment by kristinashu** [comment]
We can't make tables. I think the best way (and only way) to style it is if we add images but it's definitely tough to make it look good. I'm playing around with it here https://foundation.mofostaging.net/en/initiatives/leadership-giving-program-test/ (image are of course FPO).

**Comment by kristinashu** [comment]
Actually, I've updated spacing and copy formatting on the prod site. I think it's looking better, especially the bottom part that used to be super spaced out. Now I think we could just add images to the Become an Internet Health Leader section:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/1068783/49839218-fabb4780-fd62-11e8-8440-bf02b926fd84.png">

**Comment by xmatthewx** [comment]
👍

**Comment by xmatthewx** [comment]
Looks great. I love that it's quick and easy to knock out graphics with that style.
