### ISSUE TITLE
Follow up on Personas work

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#307]
Work was started by @taisdesouzalessa in July 2017 and debuted at the Dec 2017 All Hands with a call for feedback post All Hands. Creation and process of this work is documented [here](https://github.com/mozilla/foundation.mozilla.org/issues/566) and feedback [here](https://github.com/mozilla/foundation.mozilla.org/issues/945). 

Next steps were to show this work to directors to gather input about how teams could use these personas. This work is documented [here](https://github.com/MozillaFoundation/Design/issues/279).

**Comment by taisdesouzalessa** [comment]
I think for this one we should connect with @anilkanji to understand our focus on new audiences. We may need a new set of personas - maybe we can set a little team to work together on that @kristinashu?

**Comment by kristinashu** [comment]
Absolutely Tais! I see this as one of the many projects listed in the "H2 design goals and projects #425" ticket. Designers are all meeting this Thurs at the "Design goals & projects" to begin to scope out projects, define projects, and see how wants to work on what. Once we are all up to speed on possible projects and our personal goals, then we can meet with Anil to further define each project, write a brief, and prioritize!

**Comment by taisdesouzalessa** [comment]
As we may have to reiterate on Personas, I'll close this ticket and create a new Personas Master ticket, adding the links that @beccaklam posted above.
