### ISSUE TITLE
Continue User Testing on Foundation site

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#308]
Continue to iterate and do testing on Foundation site. Work started by @taisdesouzalessa and documented [here](https://github.com/mozilla/foundation.mozilla.org/issues/1655). This could align with our Metrics and Reporting OKR goals.

**Comment by kristinashu** [comment]
Might be time to revive this ticket lol!

**Comment by kristinashu** [comment]
I think this work is better represented here https://github.com/mozilla/foundation.mozilla.org/issues/3975 and through individual projects.
