### ISSUE TITLE
Illustration (animation?!) for our build.wmo/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#31]
In tandem with https://github.com/MozillaFoundation/Mofo-Design-Handbook/issues/30

Bonus: Make it mooooooovvvveeeee!

**Comment by cassiemc** [comment]
@sabrinang Thought you might like this one if you have the bandwidth this heartbeat! I'll be taking on the UI in issue https://github.com/MozillaFoundation/Mofo-Design-Handbook/issues/30 so we can collaborate. Maybe with @flukeout too. If you think you'll be able to to it, feel free to assign it to yourself.

**Comment by cassiemc** [comment]
Here's a cute little guy from We Transfer. I like the way the computer becomes him. :)
![redmons_1680x1050](https://cloud.githubusercontent.com/assets/1186326/8536954/1f82c6ac-2426-11e5-888d-7fd8733596ae.jpg)

**Comment by cassiemc** [comment]
@sabrinang Loved the heads you drew of the design team! Could you update this ticket with that sketch? Maybe we could vectorize them and make a pattern, heads/faces + design tools? Might work as a background in the current UI design in #30

**Comment by cassiemc** [comment]
Any updates on this @sabrinang ?

**Comment by sabrinang** [comment]
<img width="1440" alt="screen shot 2015-07-20 at 5 43 09 pm" src="https://cloud.githubusercontent.com/assets/2492510/8791028/04d1add4-2f0a-11e5-9b89-88ae5c11f723.png">
Work in progress on the heads and will integrate this in a pattern with design tools to be used as a background.

**Comment by vazquez** [comment]
Hey @sabrinang, what about this layout?

![screenshot 2015-07-23 11 37 53](https://cloud.githubusercontent.com/assets/1119821/8854836/040bcef2-3130-11e5-9f88-50987ae1c8b9.png)

**Comment by flukeout** [comment]
Yeah!!! This is sweet. Can we have a speech bubble hoverstate with our names and twitter handles or something like that?

**Comment by vazquez** [comment]
@flukeout For sure, good idea!

**Comment by sabrinang** [comment]
@vazquez  Yup that layout works for me :) ...Ooo I like the hoverstate idea too haha

**Comment by vazquez** [comment]
@sabrinang - Is it possible to get every face as a separate SVG?

**Comment by sabrinang** [comment]
polished off the illustrations
<img width="1362" alt="screen shot 2015-07-27 at 4 11 39 am" src="https://cloud.githubusercontent.com/assets/2492510/8904609/ba74fe56-3415-11e5-89d4-b30addc52cf5.png">

and exported each as .svg here: https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvb0Jpa0hLbDY0c1U&usp=sharing
