### ISSUE TITLE
Blue Sky Designs for Foundation Site

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#313]
### Description

Provide an overview of the iterations of blue sky visual concepts for the foundation site. This issue will track the future vision of the site which will help inform how we update the current site.

### Process
We are planning to slowly test and integrate the blue sky designs by breaking it up into elements and components in 1-2 week sprints. We have divided and prioritized them into: 

- Line System https://github.com/MozillaFoundation/Design/issues/314
- Image & Text Components https://github.com/MozillaFoundation/Design/issues/315
- Promotion Components https://github.com/MozillaFoundation/Design/issues/316
- Buttons & Links https://github.com/MozillaFoundation/Design/issues/317
- Sign Up Component https://github.com/MozillaFoundation/Design/issues/318

By breaking up the blue sky vision into sections, we are able to examine/audit what is currently being used, then mocking up the new idea in context of the existing site and collect feedback during a review process. Once passed review, we can prepare it for implementation. This way we can continue to work with existing styles and move systematically forward to a new design.

**Comment by natalieworth** [comment]
Updated the homepage in Redpen here:
https://redpen.io/zyb1715539e7379499

Added the new blue/ purple color based on Sabrina's work (to the links, buttons, and footer area).

**Comment by kristinashu** [comment]
Is all this work done or accounted for in other tickets?

**Comment by kristinashu** [comment]
Big blue sky direction inspired our baby steps to get there! I believe all the work is represented in separate tickets so I'm going to close this one, but please reopen if you think it's needed!
