### ISSUE TITLE
Foundation Site: Line System

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#314]
### Description

Audit the current line and dividers on the site and examine where we can align (widths, colours) by referring to new blue sky ideas. Mockup new ideas in context of existing site and collect feedback. After successful review, we can prepare for implementation.

**Line system may include:**
- horizontal rules
     - hero or footer dividers, main section dividers, secondary dividers
- box shadows
  - cards, components
- border bottom or top
    - navigation, hove underline, shadow, tables
- text underlines
   - links

**Comment by natalieworth** [comment]
Notes on rule styling:
- full width dividers/ rules: grey w/ 1 px weight (e.g. menu border-bottom)
- h2 heading dividers: black, 4px (e.g. latest news)
- anything other than h1 and h2: black w/ 1 px weight
- card shadows : black, 4px (e.g. latest news card)
- less than full width of page/ not a header: black, 2 px (e.g. News section)
- accordian: 1px weight, black (e.g. about page)
- call-out rules: maintain grey w/ 1 px weight (e.g. at bottom of this page: https://redpen.io/bwf8586ae9c69ab04c)
block/ pull-quote: #000000, 4px weight

**Comment by kristinashu** [comment]
@sabrinang is this done, if not then what are the next steps?

**Comment by sabrinang** [comment]
Note: @sabrinang to review

**Comment by sabrinang** [comment]
Note: align shadow styles too

**Comment by sabrinang** [comment]
@beccaklam @natalieworth feedback for https://redpen.io/p/ys4594fedace293c98

Some thoughts about when we use grey 4px lines and when we use black 4px lines. I think when it is grey it acts like an underline shadow for elements, previously the homepage overlaps cards were gray and I would like to update that so it is again so it doesn't look like a section divider. If we distinguish this, then we use black 4px lines as full width section dividers. I mocked up how the alignment may be so the edges could be less visually busy.
![line ideas](https://user-images.githubusercontent.com/2492510/56319416-7d3f8380-6116-11e9-9eb6-bc58304c610f.png)

Also, should the thin hr match? Instead of black, we can make it look less heavy on the page to be in grey to match the dividers on the homepage and to give the text more hierarchy:

![line ideas 2](https://user-images.githubusercontent.com/2492510/56319861-a01e6780-6117-11e9-9fef-f0e7c7b87cb8.png)

**Comment by beccaklam** [comment]
Updated line for Primary/Bannered Campaign Page based on crit: https://redpen.io/p/ys4594fedace293c98

**Comment by kristinashu** [comment]
Based on our chats the rules have been updated and simplified to:

- **subtle divider** 
  - 1px 
  - grey
  - full width/wide/narrow 
  - e.g. menu border-bottom, between news items, accordions...

- **cta divider**
  - 1px black
  - narrow 
  - e.g. Image Text & Image Text Mini component, IH CTA... (these could be grey for simplicity but would need to mock up to make sure it looked good)

- **large homepage section divider** 
  - 4px
  - black
  - wide
  - e.g. above h2 divider, above block quote on homepage

- **card shadow** 
  - 4px 
  - grey 
  - narrow
  - e.g. latest news card, cards on /participate

If everyone is good with this then I can update sketch file and open implementation tickets.

**Comment by kristinashu** [comment]
Ok so I'm going to use this a case study for our process... next steps I will do are:
- update sketch file with the above recommendations 
- update our brand [doc](https://foundation.mozilla.org/en/docs/brand/) _(not sure this is needed?)_
- get R+ from another design to have them confirm (might open a new ticket for this):
  - new rules look good in situ
  - all instances of this component have been updated in sketch
  - confirm there won't be any unintended consequences on the site
- open an "update existing style" implementation ticket for site updates
- open an implementation ticket for dev to updates their [style guide](https://foundation.mozilla.org/en/style-guide/)  _(not sure this is needed?)_

**Comment by kristinashu** [comment]
Checklist from  https://github.com/MozillaFoundation/Design/issues/355

# Updating an existing style

## 1. What element/ style is being changed?
All dividing lines and solid shadows.

- **subtle divider** 
  - 1px 
  - grey
  - full width/wide/narrow 
  - e.g. menu border-bottom, between news items, accordions...

- **cta divider**
  - 1px black
  - narrow 
  - e.g. Image Text & Image Text Mini component, IH CTA... (these could be grey for simplicity but would need to mock up to make sure it looked good)

- **large homepage section divider** 
  - 2px
  - black
  - wide
  - e.g. above h2 divider, above block quote on homepage

- **card shadow** 
  - 4px 
  - grey 
  - narrow
  - e.g. latest news card, cards on /participate

## 2. Why it is needed?
- For clear and consistency rules around our line system. 

- [ ] Post proposed brand update in Redpen (for desktop, tablet, mobile)
- [ ] Request design review from design team via R+/R- in Github ticket
- [ ] Get feedback from devs

**After Approval:**
- [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
- [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
- [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

- [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
- [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

# Design Reviewer Checklist
- [ ] Is this change justified or are we able to use existing brand elements?
- [ ] Is the development time viable?
- [ ] Provide an R+ or R- in the ticket
- [ ] List reasons for approving or denying changes

**Comment by kristinashu** [comment]
@natalieworth can I please get a design review on this?

## Design Reviewer Checklist
- [ ] Is this change justified or are we able to use existing brand elements?
- [ ] Is the development time viable?
- [ ] Provide an R+ or R- in the ticket
- [ ] List reasons for approving or denying changes

**Comment by natalieworth** [comment]
R+
I think the differences in rule styling and thickness provides better hierarchy on the page. The 4px black clearly separates each section and the lighter grey rules separate content. 
The grey option also provides a more subtle/ cleaner alternative to the solid black.
