### ISSUE TITLE
Foundation Site: Image & Text Components

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#315]
### Description

Audit the current image/text components on the site and how we can align cut out overlap styles (proportion of cut and ratio of image) by referring to new blue sky ideas. Mockup new ideas in context of existing site and collect feedback. After successful review, we can prepare for implementation.

**Image & text components to consider:**
- various widths
   - full, narrow, mobile
- various multiples
   - 4, 3, 2 or 1 cards for the width of screen
   - no card style 
  - horizontal, vertical stacking
- how it works on white, light grey and pattern backgrounds
- recommended usages

**Comment by natalieworth** [comment]
Notes:
This page includes examples of updated imagery (photography + illustration):
https://redpen.io/zyb1715539e7379499

Ideally:
- untreated photography (in terms of no color overlays or filters)
- primarily use photography over illustrations (maybe 70% photography, 30% illustration?)
- bright/ high contrast/ high res photos
- I think we should leave it fairly open-ended for illustration interpretations so it doesn't feel too repetitive on the homepage/ primary nav pages
- for smaller/ less traffic illustration creation: * need to update and add an illustration file/ assets for quick 1-off images

**Comment by kristinashu** [comment]
I _think_ the only things left to do here would be the provide guidelines on how much the white cutout box overlaps an images and when (and then update sketch file and production site to match this).

**Comment by kristinashu** [comment]
@mmmavis could you please let us know what rules devs are using to set the white cutout boxes (desktop and mobile) and then we'll update sketch to match?

Homepage
<img width="572" alt="image" src="https://user-images.githubusercontent.com/1068783/59129193-fa21f900-8920-11e9-802a-89a352c33075.png">

Participate
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/1068783/59129223-0f972300-8921-11e9-8aac-86529ce0add9.png">

Primary banner 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1068783/59129257-2b022e00-8921-11e9-9da0-563b1fc74ab3.png">

MozFest
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1068783/59129305-5553eb80-8921-11e9-91dc-9847e695f3f2.png">

**Comment by mmmavis** [comment]
I'll get back to you next week as this requires some investigation 😂

**Comment by mmmavis** [comment]
(Assigning myself this ticket so it shows up on my GitHub issue queue. Will reassign myself after)

**Comment by mmmavis** [comment]
I tried adding annotations to screencaps of the components above but it's just taking too long especially we have mobile/medium/desktop views to annotate. If our ultimate goal is to update Sketch file, @kristinashu it would be a lot easier if I could work with a designer side by side to update the Sketch file directly.

**Comment by kristinashu** [comment]
Makes sense, definitely don't spend too much time on it! Can you just give us a better sense of how you built it? Are the proportions fairly consistent across on the site? How did you do it: is it a percentage or ratio or fixed number?

**Comment by mmmavis** [comment]
I'm not sure which part we are talking about here. Is it the height of the part where the image box and the content box are overlapping? Or in terms of how much narrower the content box is compared to the image box?

I did a quick check and it seemed like devs implemented the design using fixed number (`px` or `rem` or `em`).

**Comment by mmmavis** [comment]
Related to this Pulse ticket: https://github.com/mozilla/network-pulse/issues/1152

**Comment by kristinashu** [comment]
Closing this ticket since it is very old.
