### ISSUE TITLE
Foundation Site: Promotion Components

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#316]
### Description

Audit the current promotion components (similar to image/text) and examine where we can evolve this by referring to new blue sky ideas. Mockup new ideas in context of existing site and collect feedback. After successful review, we can prepare for implementation.

**Promotional components may include:**
- full width call to action sections
   - large, small
- imagery or iconography with text
- button or links

**Comment by sabrinang** [comment]
This one is harder to describe but some existing examples are:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/2492510/51217253-34401f00-18dc-11e9-8b15-8c1601dc0863.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/2492510/51217270-40c47780-18dc-11e9-920b-5b113753842d.png">
<img width="890" alt="image" src="https://user-images.githubusercontent.com/2492510/51217277-46ba5880-18dc-11e9-8c72-b207012627bd.png">
<img width="614" alt="image" src="https://user-images.githubusercontent.com/2492510/51217301-59cd2880-18dc-11e9-8839-084637cd3867.png">

**Comment by kristinashu** [comment]
I've opened a ticket to align the IH callout with the Image Text Mini component https://github.com/mozilla/foundation.mozilla.org/issues/2900 and the fellowships example no longer exists.

@sabrinang do you think there's anything else to be done here?

**Comment by sabrinang** [comment]
👍 with the updated image text & image text mini components in wagtail they don't have the buttons and black icons moving forward sounds good to me and if we won't have large gray cta as a component it's good to close @kristinashu

**Comment by kristinashu** [comment]
w00t!
