### ISSUE TITLE
Foundation Site: Sign Up Component

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#318]
### Description

Audit the sign-up component on the site and examine how this can be updated by referring to new blue sky ideas. Mockup new ideas in context of existing site and collect feedback. After successful review, we can prepare for implementation.

**Sign up component may consider:**
- where it may show up other than home page
- various widths
- how it works with other components near footer
- how it could inform other form elements

**Comment by natalieworth** [comment]
Original 'blue sky' iteration for the sign-up/ footer area:
<img width="1041" alt="screen shot 2019-01-21 at 3 52 21 pm" src="https://user-images.githubusercontent.com/14876567/51504211-9f826900-1d94-11e9-9880-26cedc1a63a3.png">

**Comment by natalieworth** [comment]
I think to scale it back (and avoid it feeling too much like a redesign), we could update the sign-up/ form sections as follows:

<img width="963" alt="screen shot 2019-01-21 at 3 55 05 pm" src="https://user-images.githubusercontent.com/14876567/51504266-f4be7a80-1d94-11e9-957f-457dafcf06e1.png">

**Comment by natalieworth** [comment]
Simplified the form on the campaign pages: https://redpen.io/tf35889d74f7ce2ff9

**Comment by natalieworth** [comment]
![multipage copy 2x](https://user-images.githubusercontent.com/14876567/51504723-4d8f1280-1d97-11e9-8947-688dabd94fef.jpg)

**Comment by natalieworth** [comment]
Updates to the footer and donation ask feel like they cover this ticket @sabrinang ? Wondering if we could reference #2564 and close this ticket? And I think Becca has been working on updating the petition UI too, which also feels relevant and inline with the new brand work (but we'll still have to update link and highlight colors on the form):

<img width="977" alt="Screen Shot 2019-03-18 at 10 30 55 PM" src="https://user-images.githubusercontent.com/14876567/54582340-9648fd80-49cd-11e9-8b17-b9ff9e758142.png">

<img width="574" alt="Screen Shot 2019-03-18 at 10 33 15 PM" src="https://user-images.githubusercontent.com/14876567/54582416-df994d00-49cd-11e9-9ff6-5b5f87b75a14.png">

**Comment by kristinashu** [comment]
Forms are feeling pretty aligned! I think we can close this but please reopen if needed.

Here's a list of some for the signup work being done https://github.com/mozilla/foundation.mozilla.org/issues/1436#issuecomment-476461293
