### ISSUE TITLE
Write content and gather links for build.wmo/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#32]
We probably need some introductory content to describe what aim this documentation serves. Should be an improvement to what's there. The bulk of this work will be link gathering. Let's list out the assets we want to include here.

**Comment by cassiemc** [comment]
Feel free to update this comment as you find stuff.

* [Promo guidelines for Webmaker.org](https://github.com/mozilla/webmaker-browser/issues/79)

**Comment by cassiemc** [comment]
Oh! Just discovered this: https://docs.google.com/document/d/1aby1ntPPbIqhZLBd7MLDz3gAT83v3TYFOFh1ZnrV_pw/edit Now we need links for everything that currently exists.

**Comment by cassiemc** [comment]
From @xmatthewx: maybe move templates (and toolkits) into Guidelines. Should we rename "guidelines" then?

**Comment by cassiemc** [comment]
Made the above change. Now we just need links for all these things.

**Comment by cassiemc** [comment]
@vazquez can you help with sourcing some links here / identifying which pieces aren't yet done? Shouldn't take long but would be a *huge* help! If you can do it, please self-assign.

**Comment by vazquez** [comment]
Done! :lollipop:  We are missing a couple of Learning Networks specific design files. 

@sabrinang, could you link to the Teach project on Google Drive? If you also happen to have a file on Learning Networks branding that would be stellar.

**Comment by cassiemc** [comment]
A bunch of stuff that is missing here from individual projects, when you guys get a chance to update @sabrinang @lovegushwa.

**Comment by cassiemc** [comment]
Moving to the next milestone.

**Comment by sabrinang** [comment]
Learning Network site assets on Google Drive: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eR2dpNnJXRTR1UVU&usp=sharing

There currently isn't a file on MLN branding yet as it is being discussed and to be developed after MLN team has finalized more of their plans; I will update Google Drive when it comes along.

**Comment by vazquez** [comment]
Links have been placed on website. Closing.

**Comment by lovegushwa** [comment]
@vazquez Sorry Ricardo, I tried to set up another issue for you but I have a list of people I can assign and your not on it.

Webmaker brand Assets & Deliverables:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvZ1lwMHVXaHZpMHc&usp=sharing

Brand / Assets Deck (WIP):
https://docs.google.com/a/mozilla.com/presentation/d/1-HCOlHYow12vnJqH6vHEjRXCCtLUbfF02WEVPN1NDcA/edit?usp=sharing
