### ISSUE TITLE
V-Day Buyers Guide graphics

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#321]
Need a few image options for Twitter posts, blog, and press press kit.

### References:
- original social graphics https://redpen.io/p/dud88d7ca8c480714a
- v-day themes for site https://redpen.io/p/mg0194f75b80b2008e
- v-day brief https://docs.google.com/document/d/1wQxWgvsh6dujLxrxDCJgo2WQeD4xmBPDdafoZyQO670/edit
- copy for blog post https://docs.google.com/document/d/1BCABlmxXckvQTAsDwnSY3nFkxcvwFSPDAv5_JjqqHPE/edit

cc @beccaklam @caltrider

**Comment by natalieworth** [comment]
Got a start on these and added some draft options in here https://redpen.io/p/yg5faa4931a3fe3418

I've also mocked up a quick 'press kit' kind of as a blue-sky option of where to house everything for the site. What do you guys think? I was think if PNI site is something that's frequently updated every year, it'd be easier to have cms access and we can just swap out images/ content?

**Comment by natalieworth** [comment]
For documentation, the V-day social graphics are being added here: https://drive.google.com/open?id=1KR0zYn1ncQAhDKY9BQGadsGD9LvBBaI_&authuser=natalie@mozillafoundation.org

The gifs are still to come!

**Comment by natalieworth** [comment]
All social files are [here](https://drive.google.com/drive/folders/1KR0zYn1ncQAhDKY9BQGadsGD9LvBBaI_?usp=sharing)! 

Let me know if there are any additional/ last changes 👍

**Comment by kristinashu** [comment]
Awesome, Kevin and Jen approved! And the have your files.

❤️ ❤️ ❤️
