### ISSUE TITLE
Update Color in Design (Sketch) Files

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#322]
By referring to colors in issue https://github.com/MozillaFoundation/Design/issues/312#issuecomment-458746752 and color audit slides on https://goo.gl/jwnocf, update and clean up our design sketch files to ensure they are using the correct swatch palettes and corresponding symbols. These files include:

- Style Guide.sketch
- Foundation Site.sketch
- Buyers Guide.sketch

If you download this sketch plug-in: https://github.com/andrewfiorillo/sketch-palettes
You can load each palette separately here: https://drive.google.com/open?id=1-ErfVub39JB7-DToCPg0Ogj3yS1ZU8yZ

Other design files include:
- adobe CC library

cc: @kristinashu @natalieworth @xmatthewx @beccaklam

**Comment by sabrinang** [comment]
Note: It would be useful too to have an updated adobe CC library of the colours too

**Comment by sabrinang** [comment]
I created the CC library of Mozilla Foundation brand standard colours here: https://adobe.ly/2UpZPhZ

**Comment by kristinashu** [comment]
How is this coming along? What is left to do?

**Comment by natalieworth** [comment]
So far I've added the Foundation Site Color palette in the Style Guide and Foundation Site Sketch files:
<img width="772" alt="Screen Shot 2019-03-18 at 10 42 30 PM" src="https://user-images.githubusercontent.com/14876567/54582793-4834f980-49cf-11e9-9c9e-2dc64d4322f2.png">
<img width="235" alt="Screen Shot 2019-03-18 at 10 42 55 PM" src="https://user-images.githubusercontent.com/14876567/54582795-49662680-49cf-11e9-9a6b-afca04ec115e.png">

Need to adjust the Buyer's Guide file colors in Sketch and (maybe?) add the Mozilla Palette to each document (?) if that will be useful. I'm apprehensive about adding too many colors again, so maybe we can just document it in the brand guidelines but not include in our Sketch File if we aren't using any of the colors in our site UI.

**Comment by natalieworth** [comment]
All the main Foundation site colours are available in the Sketch file, with the full palette available on https://foundation.mozilla.org/en/style-guide/ 

I have only included the site-wide colours in the brand documents to maintain consistency and help us streamline everything (so we don't diverge into using infrequently used colours).

<img width="232" alt="Screen Shot 2019-05-06 at 10 08 58 PM" src="https://user-images.githubusercontent.com/14876567/57273288-0a0d9b00-704c-11e9-9cf1-1a9dc7576d48.png">
<img width="887" alt="Screen Shot 2019-05-06 at 10 10 04 PM" src="https://user-images.githubusercontent.com/14876567/57273289-0a0d9b00-704c-11e9-92e9-45eebbf792f6.png">
