### ISSUE TITLE
Guideline & Template for Donor Letters

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#323]
Provide style guidelines and a template for our payment process vendor so they can produce cohesive branded thank you, rejection or thunderbird letters.

Style guidelines may include:
- page margins
- font style and size
- logo placement and footer
- signature

Template will be create as a google doc template.

Consider including various footers/headers for confidential letters as a template option.
_________________
Current letter for reference: https://drive.google.com/file/d/0B-3ObAUfqddcR3J0RG9PWG5oR2s/view

/cc @stephaniemcv

**Comment by sabrinang** [comment]
working on template on gdoc here: https://docs.google.com/document/d/1Z9yVc5unkva3Y1axCZ5j3CmwISBIFDBbcbTqYaxkNoM/edit

**Comment by stephaniemcv** [comment]
My sincerest apologies @sabrinang, I gave you the old version of the acknowledgement. The most up to date version is here: https://drive.google.com/file/d/0B-3ObAUfqddcMmJhVWR2T2J2OEhuSnp4WGUwSFA1NjNvZmRZ/view?usp=sharing

**Comment by stephaniemcv** [comment]
Here is also the reject letter: https://drive.google.com/file/d/0B-3ObAUfqddcSm85TElnOG4tZkUxQjcxVENOdXpxV1BaYUY0/view?usp=sharing

**Comment by stephaniemcv** [comment]
Just checking in on this. I have a standing meeting with the vendor every Tuesday and wanted to know if there where any updates I can pass along. Thanks!

**Comment by sabrinang** [comment]
@stephaniemcv Do we need Will's signature for the reject letter? (I made Mark's a vector) and will these be printed on printers that can print to the edge of the page?

**Comment by stephaniemcv** [comment]
No signature needed for Will. I assume yes, but here are the [Fulfillment Machine Specs](https://docs.google.com/document/d/1ViSOa4Je_1eLSfjs5Vl6mML-3tZD60x3oA_X7B_r4EI/edit?usp=sharing)

**Comment by sabrinang** [comment]
Ok sounds good. I did some test prints with the office printer and even if the printer has a non printable region around the edge it looks fine. I tried looking at the specs and they definitely can print larger than letter size but I don't know if would need a specific bleeds or if they can set to print with 0 margins.

Letter with non-printable area margins vs. without
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/2492510/53051280-4ddf0400-3450-11e9-8e57-d4ef2e116efa.png">

Template is here: https://docs.google.com/document/d/1Z9yVc5unkva3Y1axCZ5j3CmwISBIFDBbcbTqYaxkNoM/edit

If you are sending letters or docs more than one page in length, here is a template with a lighter footer (I find the black footer can be a bit disruptive for long docs): https://docs.google.com/document/d/1XTa4lBHPcbPUfJXniXVew5DTo5c72gS4UNi2d9dtL4Q/edit?usp=sharing

@stephaniemcv Let me know if you need anything else from me

**Comment by sabrinang** [comment]
If you need a specific file export @stephaniemcv  please let me know as there were 5 printers listed in the specs doc

**Comment by stephaniemcv** [comment]
Hey Sabrina, they are asking for the Light Footer template in a .docx file. I tried to export from GDoc and the header margin went wonky, so I'll leave it to the pros. And can't you point me to image file for Mark's signature? They need that separate in jpg or png.

**Comment by sabrinang** [comment]
@stephaniemcv .docx file (I exported from pages to fix the margins as it also changed when I exported it from gdocs) and .png of Mark's signature are exported here: https://drive.google.com/open?id=1-df51ugjmMkGQGWiKM8ANPK5iH-tPU1C

**Comment by gideonthomas** [comment]
@sabrinang can this be closed now?

**Comment by sabrinang** [comment]
Checked in with Steph and it is good to close 👍 

I also made generic templates (placeholder copy and no signatures) and submitted to google docs mozilla templates and pending approval from AV so I captured in on https://foundation.mozilla.org/en/docs/brand/design/templates/ for reference in the meantime
