### ISSUE TITLE
Assets for Fellowship recruitment - March 12

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#325]
Fellowship recruitment opens March 12 so we will need graphics for social media and blog posts.

@annmarie123 is compiling a list in [this doc](https://docs.google.com/document/d/1i4p-_dSY1MHyCkI1OLt3r9di0bmmz-uruzvYVDj1_7Y/edit?ts=5c5b70b5) that will include dimensions and content.

**Comment by kristinashu** [comment]
Hi @annmarie123 will you be able to get this sepc list done this week?

**Comment by kristinashu** [comment]
Summary:

Need one image (likely group photo of fellows) with the text Mozilla Fellows over it similar to this made last year. This should reflect our new brand style.

Example of old image:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1068783/53759704-d2c91500-3e75-11e9-828e-d78a4950454e.png">

High res version of new photo:
![springmorrisphoto_mozilla_fellow_32a9759](https://user-images.githubusercontent.com/1068783/53759743-e6747b80-3e75-11e9-83ba-e8dfc3f5fbf7.jpg)

**Comment by xmatthewx** [comment]
As @kristinashu mentioned on slack, Fellowships at MozFest [stuff](https://drive.google.com/drive/folders/1-I-wXcO8V_H3H35mQ80c8ZjchqY7aHMv?usp=sharing) is more recent. So... design should fall somewhere between that and the aesthetic we see on [/initiatives](https://foundation.mozilla.org/initiatives/). 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/53411/53991373-6f024e80-40f8-11e9-8083-f5fa12e205d2.png">

<img width="726" alt="image" src="https://user-images.githubusercontent.com/53411/53991395-7f1a2e00-40f8-11e9-8665-d37a3c67d0ed.png">

**Comment by xmatthewx** [comment]
If we're in a pinch on time, I think it's reasonable to keep it simple, using a rad texture we have on hand with nice and punchy text. Note: I just made up this content. If there's another plan in place, ignore me. If there isn't, we should run this by the fellows team. 

```
mozilla
Fellows
Join today, redefine tomorrow.
foundation.mozilla.org/fellowships
```

**Comment by kristinashu** [comment]
We have settled on this version and Fellowships now as an official lockup! 
https://redpen.io/de6c08efaafef543ea

![mozilla-foundation-fellows@2x](https://user-images.githubusercontent.com/1068783/54161841-c19d7c80-4410-11e9-952b-092116840949.jpg)
