### ISSUE TITLE
Design Template for Misinfo Campaign Resources

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#326]
The Misinfo Campaign will have resources for partners to use on how to campaign on the topic of misinformation. These resources will be google docs that are mostly text. The design team has been tasked with coming up with simple styling for headings and body type. This is also a good opportunity to use the letterhead work @sabrinang has started with mozfest.

**Comment by beccaklam** [comment]
@sabrinang Can you send me links (google docs) to the work you've already started?

**Comment by sabrinang** [comment]
**GDoc Examples**
Donor Letters: https://docs.google.com/document/d/1Z9yVc5unkva3Y1axCZ5j3CmwISBIFDBbcbTqYaxkNoM/edit

MozFest Sponsorship Package: https://docs.google.com/document/d/1qHA73B_1idkAfldOk-wb3ftNfR3Xmg2TTuQhnHLkoOk/edit#heading=h.9dtxhg3nt1qp

**Comment by beccaklam** [comment]
> **GDoc Examples**
> Donor Letters: https://docs.google.com/document/d/1Z9yVc5unkva3Y1axCZ5j3CmwISBIFDBbcbTqYaxkNoM/edit
> 
> MozFest Sponsorship Package: https://docs.google.com/document/d/1qHA73B_1idkAfldOk-wb3ftNfR3Xmg2TTuQhnHLkoOk/edit#heading=h.9dtxhg3nt1qp

Thanks Sabrina! These are awesome 💯

**Comment by beccaklam** [comment]
Starting mocking up the resource template based on Sabrina's work and the Foundation Site style guide: https://docs.google.com/document/d/1eQNvNPFoAhOpUf9oCK8vCAqi0At_uXzFWml9vI-e2MQ/edit?usp=sharing

**Comment by beccaklam** [comment]
Sabrina gave some awesome feedback and now I've shared the above doc with Brandi and Jon to get their thoughts/they can start using it if nothing needs to be changed.

**Comment by kristinashu** [comment]
Sounds like @xmatthewx isn't seeing the header so will need to do some troubleshooting...
<img width="853" alt="image" src="https://user-images.githubusercontent.com/1068783/53840121-29a21d80-3f4e-11e9-8091-a03276c6cafc.png">

**Comment by xmatthewx** [comment]
For some reason, I had to click in the header area to see the header image. Now, it appears in other docs that use the header. So, so weird. I wonder if other staff will have this issue. Hopefully it's just me. But I think we're good to close this issue. Yay. Nice work.

**Comment by sabrinang** [comment]
FYI: I made this into a generic long template (any name suggestions?) and documented it in our brand home: https://foundation.mozilla.org/en/docs/brand/design/templates/

I made a some adjustments: I made the header to appear only on the first page only, Heading 1 to be in medium weight and body copy to have space after built in afterwards. Please comment on the template docs if you have feedback on changes or want more changes.
