### ISSUE TITLE
Buyers Guide evergreen banner

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#327]
No rush but we will need an evergreen banner that will be on the site for the rest of the year.

Dimensions 2480 × 606px

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1068783/53055033-30fbfe00-345b-11e9-852f-3c8dec4aa763.png">

**Comment by natalieworth** [comment]
![pni-evergreen-v2](https://user-images.githubusercontent.com/14876567/53213222-efa35400-35fc-11e9-95f5-147b4d9ba8a1.jpg)

Have mockup up an option for this here:
https://redpen.io/p/pecf13a6495b04d79e

**Comment by natalieworth** [comment]
Assets are also here for documentation:
https://drive.google.com/drive/folders/1MSmi1zoCYQhsR3HMFdbz6qCD32ibgvfA?usp=sharing

**Comment by kristinashu** [comment]
Lovely! Thank you Nat! Implementation ticket has been opened.
