### ISSUE TITLE
Generic MoFo google form style

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#329]
Fellowships team is using [this google form](https://docs.google.com/forms/d/e/1FAIpQLSdTUqJ9Z4xdcVr4IMzd9UESqm7XwcpVdrIXDeeFNIHUc_vhvQ/viewform) which is very out of date looking. Perhaps we could create a generic style for all MoFo staff to use. @sabrinang what do you think, this seems to fit into your brand work?

**Comment by sabrinang** [comment]
@kristinashu Good call to make a generic one for google forms, I'll work on this. Let me know if there are any examples or other use cases coming up that are needed.

**Comment by kristinashu** [comment]
Hmm I can't think of any right now but I'm sure some will come up!

**Comment by sabrinang** [comment]
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/2492510/53209125-4f463300-35ee-11e9-96ce-0e599e5b512a.png">

https://docs.google.com/forms/d/1EJirDSgi0IztPW4ozPT9GoYpkPNbvV6Dw1hCYtwzYLw/edit
https://docs.google.com/forms/d/1qtXC2XGrZDffzjqpC-oIMBb7jyZqQIITbzyFBXX5epg/edit

Any preferences if we want the mozilla logo in the banner itself or as an image inserted in the form (can't insert image above form title though)? We can have a few graphics as options for header or to insert though

**Comment by kristinashu** [comment]
Sooo much better! I like the look of the logo in the header for desktop but it doesn't quite work at narrower widths so we might have to put it within the form.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/1068783/53210435-a4844380-35f2-11e9-9ebd-409920d39ae1.png">

**Comment by sabrinang** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/2492510/53261059-ef9c6600-3687-11e9-89f5-5cb2b3ee90b8.png">
Yeah, on preview it's less obscured but I can make it sit higher so I'll play around with the placement but focus on in form logo placement so it is more visible all the time.

**Comment by xmatthewx** [comment]
this is great. when it's ready, let's release it to mofo in the staff channel.

**Comment by kristinashu** [comment]
Ah nice! Logo in the banner it is!

**Comment by sabrinang** [comment]
Tested a better placement of the logo:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2492510/53276746-56844400-36b5-11e9-9eee-2394e58cb747.gif)

Template 1 (Logo only transparent png): https://docs.google.com/forms/d/1EJirDSgi0IztPW4ozPT9GoYpkPNbvV6Dw1hCYtwzYLw/edit
![screen shot 2019-02-22 at 3 05 06 pm](https://user-images.githubusercontent.com/2492510/53276395-ac57ec80-36b3-11e9-804e-0e431d012e05.png)

Template 2 (Banner texture): https://docs.google.com/forms/d/1qtXC2XGrZDffzjqpC-oIMBb7jyZqQIITbzyFBXX5epg/edit
![screen shot 2019-02-22 at 3 05 20 pm](https://user-images.githubusercontent.com/2492510/53276399-aeba4680-36b3-11e9-801f-28fa944d28e3.png)

I iterated on other headers as well for options with logos that work on mobile too: 
https://redpen.io/p/zj4a888aa1e2e33332
PNGs exported here for anyone who wants to change out the header: https://drive.google.com/open?id=10Qs8u-55IH5Ih89igzNBG0yFysxrpqzb

_____________________

I tried submitting template 1 (logo only) too the Google Form Template Gallery and it says:
![screen shot 2019-02-22 at 3 07 58 pm](https://user-images.githubusercontent.com/2492510/53276657-e8d81800-36b4-11e9-9c42-5e5e51c46cc9.png)

Unsure who approves it but once it does it should be seen by all Mozilla staff under the Mozilla Tab which currently has one under the tab: 
![screen shot 2019-02-22 at 3 18 33 pm](https://user-images.githubusercontent.com/2492510/53276717-2b015980-36b5-11e9-86d6-eed0da91289d.png)

**Comment by sabrinang** [comment]
![image](https://user-images.githubusercontent.com/2492510/53277845-00b29a80-36bb-11e9-9c92-fecccda9eb42.png)

It got approved AV admin now so you should be able to see it under the Mozilla tab now. I think we only need one template as everything else is the same so users just need to switch out heading image if they want something different from our drive folder https://drive.google.com/open?id=10Qs8u-55IH5Ih89igzNBG0yFysxrpqzb

I tried looking if we can link it to an album to the selecting header form interface but don't think you can.

**Comment by kristinashu** [comment]
Awesome, I see it! I've shared it with Fellowships team to use.

**Comment by kristinashu** [comment]
Fellowships team have updated [their form](https://docs.google.com/forms/d/e/1FAIpQLSdTUqJ9Z4xdcVr4IMzd9UESqm7XwcpVdrIXDeeFNIHUc_vhvQ/viewform)!

**Comment by sabrinang** [comment]
I removed the form doc links since it can be found as a template to be used on forms: 
[Google Forms](https://docs.google.com/forms) > Template Gallery > Mozilla > Mozilla Form Template - Logo Only

Additional google form theme headers can be found on gdrive here for variation: https://drive.google.com/open?id=10Qs8u-55IH5Ih89igzNBG0yFysxrpqzb

Documented for reference on https://foundation.mozilla.org/en/docs/brand/design/templates/
