### ISSUE TITLE
Design currency for Ministry of Fun

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#33]

**Comment by cassiemc** [comment]
I wonder if this could relate to Fundraising somehow. How would a system of mozbucks work? cc @flukeout @lovegushwa

**Comment by cassiemc** [comment]
@secretrobotron recalls using "mozbucks" at Mozfest but it never got off the ground. I suspect what is crucial is having a small system of rewards that people can use these for from the get-go. For example:
* get out of demos, presenting demos, or other meetings
* buy someone else's time. more like a barter agreement.
* extra PTO? (might be controversial with HR!)
* special swag
* order a puppies visit
* maybe extra somethings when you travel

Up for additional ideas...

**Comment by secretrobotron** [comment]
![monopoliez](http://vignette2.wikia.nocookie.net/monopoly/images/d/de/$100.jpg/revision/latest?cb=20110413031024)

Mozbucks was a cryptocurrency we were going to set up. For now though, I propose we do something physical so that hilarious interactions and IOU systems are the norm.

**Comment by cassiemc** [comment]
+1 on physical! And let's set up a few sample 'stores' like we discussed earlier. With cheeky things you can buy. Get ready to print money, @secretrobotron ...

**Comment by secretrobotron** [comment]
Something like this? https://d157rqmxrxj6ey.cloudfront.net/cepheid/7788/

**Comment by kristinashu** [comment]
This ticket is almost a year old, I'm going to close it but please feel free to reopen if anyone thinks it is still relevant.
