### ISSUE TITLE
Generic Mozilla Print Ad

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#330]
### Description

We are sponsoring an event so let's make an advertising for us that will go in a program.
Page size: 8.5” x 5.5”,
Margins: 0.25”
Trim: 0.125”
Full color

It can contain a logo and web address. This is for a small event.

**Comment by sabrinang** [comment]
@xmatthewx  @anilkanji Here is a redpen of some ideas: https://redpen.io/p/ape3cf0e358aa1c96f

![image](https://user-images.githubusercontent.com/2492510/53529913-1224e980-3aa3-11e9-8cec-05f25e7394a8.png)
By looking at the specs, it looks like we have half of letter size page of program so I iterated and assumed a horizontal ad for now (I can easily make it vertical). These include the logo and foundation's URL at foundation.mozilla.org. No content exceeds the 0.25" margins and I can export it with a 0.125" trim/bleed once we choose a design. These are black and white that can be printed by any printer.

**Comment by sabrinang** [comment]
This was the selected design: 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/2492510/53592516-4eac2000-3b4b-11e9-99d7-de91583c00c8.png">


I exported the it as PDFs (with and without bleeds) here: https://drive.google.com/open?id=1QHF8DJHJgb0ndQ8KRxyvO6J1BascdeXo

**Comment by sabrinang** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/2492510/53660157-0f94d200-3c12-11e9-93cc-0ea01a3e7def.png">

I updated the gdrive folder with vertical versions: 
https://drive.google.com/open?id=1QHF8DJHJgb0ndQ8KRxyvO6J1BascdeXo

**Comment by kristinashu** [comment]
Nice! Is this good to close?

**Comment by kristinashu** [comment]
Lotta says this is done!
