### ISSUE TITLE
Welcome series emails

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/Design#331]
### Intro

We will be sending out a series of 2-3 emails when someone new subscribes to foundation emails using the Foundation website (ties in with https://github.com/mozilla/foundation.mozilla.org/issues/2757). 

The template used will be one that already exists in SalesForce (@stephaniemcv to share) so a designer just needs to choose one. There might be graphics needed to complement the text (@kristinashu to guide) and @caltrider will be coming up with content for this.

### Links

1. [Planning Doc](https://docs.google.com/document/d/1Se4FH_H2wPGhT0O5jgEDr53EocZ-fgCN3tbQGznWpls/edit#)

cc: @kristinashu @beccaklam

**Comment by kristinashu** [comment]
Rebecca and I have been visualizing the newsletter prep work in [this deck](https://docs.google.com/presentation/d/1JclSarFbhlPbkbDTlojphdvBR-VBViMHug4aSuA_os4/edit?usp=sharing).

Rebecca will start on designs soon.

@caltrider please let us know here or in Slack when you have initial copy (no rush)! Then we can put it into the mockups and share designs for some feedback.

**Comment by beccaklam** [comment]
Designs (UX and preliminary UI) can be found here: https://redpen.io/p/uvd561910fde4f4bc9

**Comment by kristinashu** [comment]
Designs are coming along:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/1068783/54859373-95fc7b00-4cc9-11e9-8c01-4a10095f7c97.png">

### Next steps:
- Design needs to create welcome and banner graphic https://github.com/MozillaFoundation/Design/issues/336
- Jen, Anil, Rebecca, and I need to meet early next week to make final decisions on
  - What content/links should the second email feature?
  - Should we have a third email?
- once decisions are made, we can share with moco

**Comment by kristinashu** [comment]
_Final_ next steps based on Anil's decisions:

### P1:

- Go with the four image version as mocked up here: https://redpen.io/jk055e12c47577a191
  - Mozilla Foundation: The heart of Mozilla. We work for a better internet for all.
  - *Privacy Not Included: A buyer’s guide to help you shop safe for connected products
  - Advocacy: We bring people together from around the world to fight for a better internet
  - IRL Podcast: Real stories of life online and real talk about the future of the web
- Links below blocks: (I think with text?)
  - Internet Health Report
  - Facebook Container
- Update “Mozilla Foundation” links to something other than our homepage (can we link this to an “about us “or something more compelling?)

### P2
- explore different image options for the four image blocks
- Mockup a no image option to test (with all other variables being identical) to test their efficacy in achieving our goals

**Comment by beccaklam** [comment]
Updates to the designs in this red pen:
https://redpen.io/p/uvd561910fde4f4bc9

Still need to work on finding better images for the four graphics.

## Part 1
![Welcome Series Pt 1 Copy 5](https://user-images.githubusercontent.com/20977376/55263338-00239b80-5247-11e9-8463-5de0cea157f7.jpg)

## Part 2
![Welcome Series Pt 2 Copy 11](https://user-images.githubusercontent.com/20977376/55263337-00239b80-5247-11e9-89c2-85fe8f0566d1.jpg)

Just text
![Welcome Series Pt 2 Copy 14](https://user-images.githubusercontent.com/20977376/55263339-00239b80-5247-11e9-8667-5085cc587846.jpg)

**Comment by beccaklam** [comment]
Part 1 is remaining the same. Pt 2 options here (with updated images, graphics, and layout):
https://redpen.io/p/uvd561910fde4f4bc9

## With Images in Body
![Welcome Series Pt 2 Copy 11](https://user-images.githubusercontent.com/20977376/55410843-8cc5a680-5532-11e9-8c5b-f2a18a5e40e8.jpg)

## With No Images in Body
![Welcome Series Pt 2 Copy 14](https://user-images.githubusercontent.com/20977376/55410868-964f0e80-5532-11e9-8c80-c111fa26d92d.jpg)

Closing this ticket for now but please reopen if needed. We're still waiting on Ashley's signature (probably get this by end of week?), I think that's the only outstanding asset but otherwise this is done. @kristinashu
