### ISSUE TITLE
Bi-weekly engagement newsletter template design

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/Design#332]
### Intro

We will be launching a bi-weekly newsletter that will go out to everyone (within the English locale), that will talk about the work we do and how people can participate with us through different opportunities.

We need to design a template that will contain this content and be used in Salesforce. @Sydette will be responsible for content and getting it approved by legal, compliance, etc. Alex Z. can advise on what we can and can't do with templates.

### Links

1. [Planning doc](https://docs.google.com/document/d/1Se4FH_H2wPGhT0O5jgEDr53EocZ-fgCN3tbQGznWpls/edit#heading=h.ck72teds5nw)
2. [WIP Content doc](https://docs.google.com/document/d/1B9ZWNoyr4deB3WrYsynwOOQUJ4f3qkYbYbeqBQ7ft-A/edit)

cc: @kristinashu @beccaklam

**Comment by kristinashu** [comment]
Rebecca and I have been visualizing the newsletter prep work in [this deck](https://docs.google.com/presentation/d/1JclSarFbhlPbkbDTlojphdvBR-VBViMHug4aSuA_os4/edit?usp=sharing).

Rebecca is mocking up (WIP) potential layouts and working with Steph to understand the restrictions.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/1068783/54311749-79a66300-4592-11e9-9045-b5876d2fb91d.png">

@Sydette please let us know here or in Slack when you have initial copy. Then we can put it into the mockups and share designs for some feedback.

**Comment by beccaklam** [comment]
Designs (UX and preliminary UI) can be found here: https://redpen.io/p/uvd561910fde4f4bc9
Plus initial copy from Sydette: https://docs.google.com/document/d/1DqEGThW7efdDa-20Qo4qVRdH4piHXhgDIT4uXobzzfU/edit?usp=sharing

**Comment by kristinashu** [comment]
I love these! Possible next steps are: mockup mobile version, share with design team, share with Steph for feasibility, share Sydette and Anil.

**Comment by natalieworth** [comment]
This looks beautiful Becs! Really nice with the images in context.

**Comment by beccaklam** [comment]
Mobile here and on redpen: https://redpen.io/rd93a2e3a104759f57
![Small and Extra Small (≥576px) - using 320px for mobile Copy](https://user-images.githubusercontent.com/20977376/54541187-d11c4880-496f-11e9-847f-c4c1ca3f5e9b.jpg)

**Comment by kristinashu** [comment]
Feedback from Anil was that there was too much content so we now have two options. 
3 sections with 2 articles each vs 2 sections with 3 articles (the decision will be up to Sydette):
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1068783/54859325-1c648d00-4cc9-11e9-8947-11c3387b8cca.png">


### Next steps:
- Design needs to make the banner graphic https://github.com/MozillaFoundation/Design/issues/336
- Sydette needs to get content approved
- Sydette needs to decide on 2 vs 3 sections

**Comment by kristinashu** [comment]
_Final_ next steps:

- Sydette has prefers the 2 sections with 3 articles each version so let's run with that one
- Team the black/white zig-zag banner so choose that one

Otherwise, this is on hold while Anil talked with moco about their newsletter.

**Comment by beccaklam** [comment]
Final design:
![Newsletter 2 sections@2x](https://user-images.githubusercontent.com/20977376/55411015-dc0bd700-5532-11e9-8883-1bdefa2d2c19.jpg)

**Comment by kristinashu** [comment]
This is good to close too! We can open a new ticket if something comes up.
