### ISSUE TITLE
Mozilla Branded Notebooks

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#333]
### Description
Create Mozilla Foundation notebooks and leave an area for programs/initiatives to customize with typography etc.

Size: TBD
Vendor/Print Specs: TBD 

cc: @kristinashu @natalieworth @xmatthewx @beccaklam

**Comment by sabrinang** [comment]
Hi @jenntbeard if there are any specific file type and size deliverables you'll need, please let us know. If you can provide any vendor specifications or templates for the notebooks you are looking to produce that would be great as well.

**Comment by xmatthewx** [comment]
Excellent! I'd suggest that we actually have one standard way for program name to show up. And maybe one alternative for a more expressive phrase.

**Comment by jenntbeard** [comment]
All I know is that the guy at Social Imprints asked for a vectorized PDF of the image. I am looking at light grey Moleskine notebooks for production, something like this: https://www.amazon.com/Moleskine-Cover-Notebook-Professional-Large/dp/B079ZS9PCN/ref=asc_df_B079ZS9PCN/

**Comment by sabrinang** [comment]
Oh nice moleskines! Would vector files of the logo do? 
Black and white: https://drive.google.com/open?id=1S6WbnsWpE63ZQs8ehsrtxO2-7e6xMBP9
If it is a grey color, the one colour black logo would be great: https://drive.google.com/open?id=1SCyIAztasPOrdjnuUf1UXgPrNWQ3ww5N

I didn't receive any attached images in my email since I was added so I don't know which image you are referring to but feel free to share

**Comment by jenntbeard** [comment]
Oh sorry - I was actually asking for the Responsible Computer Science Challenge banner itself. 
![hero-cs-challenge](https://user-images.githubusercontent.com/17835013/53982539-c8f41b80-40da-11e9-8062-6159528675f9.jpg)

**Comment by sabrinang** [comment]
@jenntbeard I exported the responsible computer science challenge text here: https://drive.google.com/open?id=1_OMCtLvvFM4NWR8ISmk4DjY9HpsjWjnI

I only have the background as a raster file sorry but if you need it i exported here as a jpg: https://drive.google.com/file/d/1ZABLFSHdyOebg6YLOIWu9lutE9shULSw/view?usp=sharing

**Comment by jenntbeard** [comment]
Great - I will pass these along to see what he says. Thank you!
