### ISSUE TITLE
 Update Type in Design (Sketch) Files

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#335]
By referring to type in issue #319, update and clean up our design sketch files to ensure they are using the correct type and corresponding symbols. These files include:

    Style Guide.sketch
    Foundation Site.sketch

cc: @kristinashu @natalieworth @xmatthewx @beccaklam

**Comment by natalieworth** [comment]
Cleaned up type Style Guide and the Text Styles:
<img width="931" alt="Screen Shot 2019-05-06 at 10 18 07 PM" src="https://user-images.githubusercontent.com/14876567/57273684-9cfb0500-704d-11e9-8603-b70f75014084.png">
<img width="895" alt="Screen Shot 2019-05-06 at 10 22 05 PM" src="https://user-images.githubusercontent.com/14876567/57273690-a1bfb900-704d-11e9-9919-5ed57edeabc1.png">
<img width="840" alt="Screen Shot 2019-05-06 at 10 23 28 PM" src="https://user-images.githubusercontent.com/14876567/57273691-a1bfb900-704d-11e9-84e0-899e6a04e694.png">
