### ISSUE TITLE
Graphics for newsletter/emails

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#336]
Content and layout are still wip and I will update once they are final, but we will need a banner graphic of the newsletter and the 2nd email as well as a "floating" graphic for the 1st welcome email.

https://redpen.io/p/uvd561910fde4f4bc9

![Welcome Series Pt 1 @2x](https://user-images.githubusercontent.com/1068783/54716589-4d02c600-4b13-11e9-85b9-77ae4cd8007c.jpg)
![Welcome Series Pt 2 @2x](https://user-images.githubusercontent.com/1068783/54716590-4d02c600-4b13-11e9-889e-9e46426d0c8d.jpg)

**Comment by beccaklam** [comment]
I can help with this if needed? @kristinashu not sure if it's already been assigned

**Comment by kristinashu** [comment]
Would be amazing if you worked on this!

**Comment by beccaklam** [comment]
@kristinashu do we know when we need these by?

**Comment by kristinashu** [comment]
Let's say by this Thursday. Content for both emails and newsletters aren't finalized yet and they still need to go through the moco RACII so we have some time but it would also be nice to get them out of the way.

**Comment by beccaklam** [comment]
Graphics in situ in the redpen: https://redpen.io/p/uvd561910fde4f4bc9
Came up with some options ... not happy yet with the Welcomes Series: Pt. 2 graphic so could use some feedback there @kristinashu Still working on a graphic for the Newsletter, hopefully will have something by my lunchtime tomorrow!

## Welcome Series: Part 1
![Welcome Series Pt 1](https://user-images.githubusercontent.com/20977376/55112588-4ea03100-50b3-11e9-9ecd-f55e7c9507f1.jpg)

## Welcome Series: Part 2
![Welcome Series Pt 2](https://user-images.githubusercontent.com/20977376/55112645-65df1e80-50b3-11e9-9d9a-d67cf9466a7b.jpg)
![Welcome Series Pt 2 Copy 3](https://user-images.githubusercontent.com/20977376/55112650-6972a580-50b3-11e9-81ab-09f89acd24d8.jpg)
![Welcome Series Pt 2 Copy 7](https://user-images.githubusercontent.com/20977376/55112659-6c6d9600-50b3-11e9-853e-3289f7e0a5c2.jpg)

**Comment by beccaklam** [comment]
## Newsletter Grahpic Options:
![Newsletter 3 sections Copy 3@2x](https://user-images.githubusercontent.com/20977376/55169676-95da0080-514b-11e9-888e-a3b5e1300d2d.jpg)
![Newsletter 3 sections Copy 2@2x](https://user-images.githubusercontent.com/20977376/55169677-95da0080-514b-11e9-8ccd-e8c35117018b.jpg)
![Newsletter 3 sections Copy@2x](https://user-images.githubusercontent.com/20977376/55169679-95da0080-514b-11e9-9f9a-f9ac11dd90f7.jpg)

**Comment by beccaklam** [comment]
Ok! So I _think_ designs for these graphics are done: https://redpen.io/p/uvd561910fde4f4bc9

## Welcome Series Pt 1
![Welcome Series Pt 1 Copy 5](https://user-images.githubusercontent.com/20977376/55410406-cb0e9600-5531-11e9-9be1-e4f7c20fb82e.jpg)

## Welcome Series Pt 2 (We have two options to test)
With Images in the body:
![Welcome Series Pt 2 Copy 11](https://user-images.githubusercontent.com/20977376/55410460-e4174700-5531-11e9-8f84-6dce5fd70323.jpg)

With no images in the body:
![Welcome Series Pt 2 Copy 14](https://user-images.githubusercontent.com/20977376/55410492-ef6a7280-5531-11e9-9760-fed983987587.jpg)

## Newsletter
And we decided to go with this graphic for the Newsletter:
![Newsletter 2 sections@2x](https://user-images.githubusercontent.com/20977376/55410558-0a3ce700-5532-11e9-9050-8342980b4466.jpg)

I'm going to close this ticket for now, but feel free to reopen if needed @kristinashu
