### ISSUE TITLE
Prepare graphic for Platform Transparency

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#337]
We need to produce/update a graphic for MisInfo. Let's aim to recycle existing design rather than creating something from scratch if possible. The campaign is focused less on misinfo and more on platform transparency (misinfo is symptom, transparency is the solution). The graphic doesn't need say that, but it should be less about the scary crisis. 

Once we have the design, graphic should be prepared for these uses: 
 - email
 - twitter
 - landing page banner
 - fo'mo homepage feature

cc: @kristinashu

**Comment by kristinashu** [comment]
Went through redpen and found a few things... 

IHR graphic https://redpen.io/p/gka6009d0942feb584
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1068783/55011668-73a57e80-4fa3-11e9-9f65-3843959717b8.png">

Blue-sky hero image https://redpen.io/hm62232a96e5871599
<img width="848" alt="image" src="https://user-images.githubusercontent.com/1068783/55011886-d0a13480-4fa3-11e9-9601-6059f11ced89.png">

Initiatives page https://redpen.io/p/to117fbc5e037ba354
<img width="580" alt="image" src="https://user-images.githubusercontent.com/1068783/55012040-080fe100-4fa4-11e9-85ed-1b88d6de5bb6.png">

Redacted text https://redpen.io/hq6093e62102b2ac36
<img width="908" alt="image" src="https://user-images.githubusercontent.com/1068783/55012186-3ee5f700-4fa4-11e9-85e6-fc574fd59253.png">

This style but with a magnifying glass https://redpen.io/p/bn7bb8801c7cf1b44f
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1068783/55012505-bfa4f300-4fa4-11e9-8d08-cb97ec8816dc.png">

Abstract image with treatment https://redpen.io/ua28f0ef5bd3ed3858
<img width="859" alt="image" src="https://user-images.githubusercontent.com/1068783/55012613-e95e1a00-4fa4-11e9-888a-c358ce2f3d9d.png">

Fist https://redpen.io/p/zj3a03844f39d2841c
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/1068783/55012772-275b3e00-4fa5-11e9-94cc-c6efb8a9dfca.png">

Abstract textures https://redpen.io/p/fwd6e45324b8a54452
<img width="296" alt="image" src="https://user-images.githubusercontent.com/1068783/55012896-5d002700-4fa5-11e9-8db2-bf4ae521ace3.png">

**Comment by xmatthewx** [comment]
Also maybe this works? Kinda hints at idea of transparency behind the platforms. 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/53411/55020927-415d4680-4fce-11e9-944e-40807e097c95.png">

**Comment by kristinashu** [comment]
Rebecca's link to working files for this graphic are [here](https://drive.google.com/drive/folders/1LwqNseUG6-cWIDBnMTF8mlQ3Cy1IDyDy).

@xmatthewx please confirm but I believe next steps are:
- Remove +/- from graphic above
- Crop it for 
  - email (need dimensions)
  - twitter
  - landing page banner
  - fo'mo homepage feature
- Advocacy team will add content to the cms page
- Create 3 graphics for the [key resources](https://docs.google.com/spreadsheets/d/1lVFihNhCQBP3dzNdr_zOjdKTNWqw43zk9DddX7XXNHE/edit#gid=444707780) 

You probably don't know but please add any deadlines if you have them.

**Comment by xmatthewx** [comment]
Your list looks good. One small edit: I think we'll post content for resource page as it'll need some design thinking for best presentation. 

I'm looking to confirm right now if this will be a new page or an update on existing page at [/campaigns/eu-misinformation/](https://foundation.mozilla.org/en/campaigns/eu-misinformation/).

Deadline: we will post stuff as soon as it's ready this week, improve next week if necessary.

**Comment by kristinashu** [comment]
Ok I've update the comment above and some links, please let me know if anything changes!

**Comment by kristinashu** [comment]
All graphics are here https://drive.google.com/drive/folders/1XbzAhP1QmJL0Z4_FPeHYu_BmRvNbG_Zd?usp=sharing

For social, OG, and fo'mo page:
![social](https://user-images.githubusercontent.com/1068783/55188749-51edf800-5159-11e9-8c45-702ca488a83f.jpg)

Banner (already uploaded):
![website banner](https://user-images.githubusercontent.com/1068783/55188750-52868e80-5159-11e9-9d99-c7ee759752a3.jpg)

Resources (all pretty terrible but we can iterate lol):
![resource-europa](https://user-images.githubusercontent.com/1068783/55189406-16ecc400-515b-11e9-962c-c3e89f077170.jpg)
![resource-mozillablog](https://user-images.githubusercontent.com/1068783/55189407-16ecc400-515b-11e9-8183-93cfaa66c833.jpg)
![resource-whotargetsme01](https://user-images.githubusercontent.com/1068783/55189409-16ecc400-515b-11e9-92c4-2585513dcb7a.jpg)
![resource-whotargetsme02](https://user-images.githubusercontent.com/1068783/55189410-16ecc400-515b-11e9-800b-6c1344ea8d9c.jpg)

**Comment by xmatthewx** [comment]
Thanks for the speedy work @kristinashu and @beccaklam. I think we can close this and open new tickets if anything pops up.
