### ISSUE TITLE
Update Sketch library components to reflect design changes from brand work

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#338]
Moving @natalieworth's lovely ticket https://github.com/mozilla/foundation.mozilla.org/issues/2548 from Foundation site repo to the Design repo since it seems more design-y.

This ticket is to document the 2019 changes based on the brand work our team has been doing. For design, we can keep the Sketch updates in this master file—then create new implementation tickets based on changes that have been updated.

Sketch Library updates: 
P1's 
- [x] Change rules from the gradient to black #000000
- [x] Update link colors
- [x] Update greys based on Sabrina's color updates
- [x] Update link text to sentence case
- [x] Update 'document' color swatches with new colors

P2's
- [x] Add new ghost button style
- [x] Update button colors and hover states
- [x] Implement banner pattern background
- [ ] Update Promotion components

P3's
- [ ] Edit and upload brighter photographs/ review illustrations and images of each page and curate based on updated branding work
- [ ] Evaluate static/ evergreen illustrations and adjust to fit within the growing brand direction
- [ ] Document visual changes (after implementation) on the Foundation brand site
- [ ] Updates to typography (if needed)
- [ ] Design/ illustration template for quick image creation
- [ ] Other templates? (maybe a downloadable template section on the Brand Guide page would be useful? Social templates, patterns, etc.?)

P4's
- [x] Footer orientation and layout
- [ ] Card styles and layout
- [ ] Increase spacing
- [ ] Review UX language on site

**Comment by natalieworth** [comment]
Going to close this tic as some of the P3's/ P4's of this are changing based on UI, Pulse, and potential homepage context/ design updates.
