### ISSUE TITLE
Foundation Site: Buttons & Links con't

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#339]
Follow up from - Foundation Site: Buttons & Links #317. 

Summary of the buttons UI components are in wagtail: https://foundation.mozilla.org/en/docs/brand/design/ui-components/

This ticket is to finish off the still work in progress button elements:  
- [x] Disabled Button State
- [x] In-line Icon Button
- [x] Grouped Buttons
- [x] Social Buttons

**Comment by kristinashu** [comment]
@beccaklam your blog design introduces some new button styles. Since those buttons are so lovely looking we should incorporate them into our existing styles and guidelines and retire some of our older styles.

New style:

<img width="109" alt="image" src="https://user-images.githubusercontent.com/1068783/55917565-99867200-5ba4-11e9-813b-a161eb2dc496.png">

<img width="628" alt="image" src="https://user-images.githubusercontent.com/1068783/55917559-925f6400-5ba4-11e9-9083-704076472083.png">

Old style on /participate
<img width="211" alt="image" src="https://user-images.githubusercontent.com/1068783/55917621-cfc3f180-5ba4-11e9-9abd-6251dd88bc6f.png">

@sabrinang has also just pointed out that the square adjacent buttons in your comp are all the same width and one row which is not in our current guidelines. Could you please check-in with Mavis to see if that's possible?

**Comment by sabrinang** [comment]
social button audit examples on slide 48-49 for reference: https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit?usp=sharing

**Comment by beccaklam** [comment]
@kristinashu @sabrinang sorry about that! i just copied the style from what we did for PNI since it was similar to our current foundation site button styles. @mmmavis would we be able to incorporate this style into the foundation site's style guide? 
![image](https://user-images.githubusercontent.com/20977376/55966468-77453080-5c46-11e9-9c2b-b0e33733322f.png)

**Comment by mmmavis** [comment]
@beccaklam so far only three types of buttons have been cleaned up, and yes, we can add more styles to the set.

### Implemented
1. .btn-primary (the old .btn-normal)
2. .btn-secondary (the old .btn-ghost)
3. .btn-pop

--- 

> would we be able to incorporate this style into the foundation site's style guide?

By "style", did you mean a button group where

- buttons are equal width
- individual button is styled as `btn-primary`
- individual button has a social icon before the button text

**Comment by kristinashu** [comment]
@beccaklam assigning this one to you so you can also test out our processes around adding/updating the style guide.

**Comment by kristinashu** [comment]
One more thing to consider is our external icon in buttons and links https://github.com/mozilla/foundation.mozilla.org/issues/3219

**Comment by beccaklam** [comment]
> @beccaklam so far only three types of buttons have been cleaned up, and yes, we can add more styles to the set.
> ### Implemented
> 
>     1. .btn-primary (the old .btn-normal)
> 
>     2. .btn-secondary (the old .btn-ghost)
> 
>     3. .btn-pop
> 
> 
> > would we be able to incorporate this style into the foundation site's style guide?
> 
> By "style", did you mean a button group where
> 
>     * buttons are equal width,
> 
>     * individual button is styled as `btn-primary`,
> 
>     * and individual button has a social icon before the button text

Hi @mmmavis sorry for the really late reply. Yes, that is what I mean by "style". Though I'm not sure it's much of a style? @sabrinang can you clarify what you meant by that style not being in our current guidelines?

**Comment by beccaklam** [comment]
Also, @kristinashu can you clarify what we're hoping for in a disabled button state and in-line button? Do we currently have a standard disabled button style for the foundation site?

**Comment by kristinashu** [comment]
[Sabrina's audit deck](https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit#slide=id.g4fbe379a6a_0_18) might be useful, starting at slide 46.

We don't currently have a standard for disabled buttons. We have a disabled button on PNI tho:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/1068783/58899408-ba090f00-86b1-11e9-9700-9c39ba455883.png">


In-line icon in a button of as text link would be like:
<img width="147" alt="image" src="https://user-images.githubusercontent.com/1068783/58899471-df961880-86b1-11e9-8f0c-fd3cd53dcf87.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1068783/58899492-ede43480-86b1-11e9-89e0-f23e75f74bb7.png">
<img width="107" alt="image" src="https://user-images.githubusercontent.com/1068783/58899513-fccae700-86b1-11e9-9b8b-965727bb43aa.png">
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1068783/58899485-e886ea00-86b1-11e9-847b-7b4c35f0d8fa.png">

**Comment by kristinashu** [comment]
Sabrina's icon ticket https://github.com/MozillaFoundation/Design/issues/346

**Comment by beccaklam** [comment]
@sabrinang from your ticket ^ it seems like you also scaled the extra small icons from 12px to 16px to fit the buttons, right? That's the size I'm thinking works the best for the social buttons being discussed in this ticket.

**Comment by sabrinang** [comment]
@beccaklam I scaled small icons down 24px to 16px but I think @natalieworth is making a 16px set as I think she updated the grid for it

**Comment by beccaklam** [comment]
Brand update ticket started here:  #339.
