### ISSUE TITLE
Figure out how "Design Buddies" work

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#34]
- [ ] Come up with a better name
- [ ] How does this work with our team
- [ ] Could this work with contributors
- [ ] Assign the first cohort

**Comment by cassiemc** [comment]
Notes beginning to percolate here: https://etherpad.mozilla.org/Nqu0FLMbSL

**Comment by lovegushwa** [comment]
A WIP deck on how d-buds work. @vazquez  and I will discuss in weekly critique next week. We can create a new issue or revise the deck as needed. I'm calling this one closed!

https://docs.google.com/a/mozilla.com/presentation/d/1WBfEj5ac7Y3aT4PUT5zF6iHlFzUEjZ8GOzglhtXXDzs/edit?usp=sharing
CC @cassiemc
