### ISSUE TITLE
IHR promo material - Deadline April 17

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#340]
Update designs for IHR promo material based on 2019 site design and content. You can see the site design at https://internethealthreport.org/2019/ 

@beccaklam to kick-off this project with Jarius later this week or early next week.

## Need to get from Jairus
- [x] high res version of these assets, if needed
- [x] finalize list based on last year's assets https://wiki.mozilla.org/Internet_Health_Report (English only)
- [ ] content for all assets

### For Easy Printing & Use
**P1**
- [x] Internet Health Report postcard (print-ready, pdf)(content doc) 

**P2**
- [x] Internet Health Report One-Pager - color (but should be legible in black & white) (print-ready, pdf) (content doc)
- [x] Internet Health Report One-Pager - color, with hyperlinks (but should is legible withno hyperlinks and in black & white) (google doc)
- [x] Flyers

**P3** 
- [x] Sticker Template (for sticker mule)

**P4**
- [ ] Graphics for social or print (Reusable design system components) 

 
### For Events and Workshops
- [x] Internet Health Report Slide Deck (google doc) (content doc) _I think Jairus is working on this_

### Rough Feedback Schedule:
- [x] First draft Thursday, April 11
- [ ] Revised stuff by EOD Monday, April 15
- [ ] Final stuff by Wed, April 17

**Comment by beccaklam** [comment]
Kick off doc notes: https://docs.google.com/document/d/1bHDM_Qeo7vdn7H7covga9xTkUfGdC1gm8-UdeMt4a3E/edit?usp=sharing

**Comment by beccaklam** [comment]
WIP First draft:
Google docs: https://drive.google.com/drive/folders/1fxxCRf7aN-vsKaOub_xOJCSQFu0AnqlO?usp=sharing
redpen with sticker templates and postcards: https://redpen.io/p/uk8c2dc004a57c7153

**Comment by beccaklam** [comment]
@kristinashu Did Jairus ask for How To Run An Internet Health Report Discussion Group (content doc)? He didn't mention it in our meeting and I just looked at the doc and it doesn't look like it needs any design?

**Comment by kristinashu** [comment]
I haven't hear or seen anything about that!

**Comment by beccaklam** [comment]
Ok, I'm going to remove it from the checklist then!

**Comment by beccaklam** [comment]
Final folder with assets: https://drive.google.com/drive/folders/1cxqF3Z9eMz_TlQ1VtLuPM6eL_fGu9U-a?usp=sharing

Going to call this work finished for now ... will reopen if Jairus needs changes? cc: @kristinashu

**Comment by kristinashu** [comment]
Looks good!
