### ISSUE TITLE
Design pass of IHR intro page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#342]
@annmarie123 is moving content from an [infogram](https://infogram.com/1pyxjevv5rxqpdf39lmxmr0zresyw35zjxp?live) to a cms page. Once she has done that it will need a design pass to make sure it's on brand. 

This needs to be done by EOD Wednesday April 10 for an email going out the next morning.

cc @xmatthewx

**Comment by annmarie123** [comment]
@kristinashu Here is the site for review: https://foundation.mozilla.org/en/opportunity/what-is-the-internet-health-report/

How do I add a snippet for the sign up for IHR newsletter? I would like it to be on the bottom of the page.

**Comment by kristinashu** [comment]
Thanks @annmarie123 I'll work on the page later today.

We are in the middle of updating all our newsletter signups so we can't actually add that snippet right now. We can work on it but doubt it will be ready for Thursday morning. Is it something you would like to have added long-term?

**Comment by kristinashu** [comment]
After talking to Matthew and Anil about this page I have a little more context... since users are coming to the page via email and this page will be short lived it sounds like adding the signup should not be a priority.

**Comment by annmarie123** [comment]
Understood. As long as there is someway to track engagement on the page then I believe it meets the criteria for fundraising.

**Comment by kristinashu** [comment]
Are analytics on how many people visited the page enough? Do you still want the link to https://internethealthreport.org/ like you have in the infogram?

One more question... which sections are the more important?  
- What's in the report?
- Why we produce the report?
- How is it used?
- How to use the report?
- Who reads the report?

**Comment by kristinashu** [comment]
Here's the first pass at design https://foundation.mozilla.org/en/opportunity/what-is-the-internet-health-report/
I've updated the graphics to use ones from the report. I would still like to update the map to one the report uses but that shouldn't change things too much.

**Comment by annmarie123** [comment]
If there is already a map, lets definitely use it. :) This looks great. Thanks, Kristina!

**Comment by kristinashu** [comment]
w00t! I updated the map to one used in the IHR and I think we are all done! But let me know if you need anything else.
