### ISSUE TITLE
OLE newsletter and wagtail pages

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#343]
Kristina G and the OLE team are looking to launch a newsletter to OLE past participants, and invite new folks interested in that work to sign up. They need (in order of priority):

### Newsletter
A newsletter template they can add content to. 
- [Strategy doc](https://docs.google.com/document/d/1zaYrSNTKRxWYExJwuhRQPQokvk-A1Pdq7AF61GViyac/edit#heading=h.6pxbvixzqyu6)
- design should follow our general newsletter layout https://redpen.io/ks8bc539b21350e632

### Newsletter signup on site
A sign up form that persists on the OLE pages at foundation.mozilla.org 
- [Website strategy doc](https://docs.google.com/document/d/176YLUcGYB_UXTyMSV0K9ikDXiesCvGOa6aMbBTB0LKo/edit?ts=5c9a0c1e)
- design should ideally follow the same layout as MozFest signup https://redpen.io/so93f080dbd1e492ad but we need to make content work without any sub-pages

### Site design
Some design support to make the OLE pages even more engaging, and bringing them in line with the rest of foundation.mozilla.org.
- Kristina G's initial pass at [Wagtail pages](https://foundation.mozilla.org/en/initiatives/mozilla-open-leadership--events/)

### Sunset old OLE pages
Rredirect and delete old pages.
- Kristina G to confirm

cc @xmatthewx

**Comment by kristinashu** [comment]
Comps are here https://redpen.io/p/hpd125097a02f591fb

**Comment by kristinashu** [comment]
Note Kristina has also asked for:

Global Sprint: https://foundation.mozilla.org/en/opportunity/global-sprint/

- We would like to redirect this page to push people here: https://foundation.mozilla.org/en/initiatives/mozilla-open-leadership--events/collaborate-with-us/sprint-for-internet-health/ 
- The old page's content can be archived.

Open Leaders: https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/

- This is going to be updated soon for the next round/iteration for H2, so can remain as-is 
- We'll reassess after we know exactly what the plan/next steps for the program are

I also wanted to ask, is there space for the Open Leadership & Events page to get a direct link somewhere on the foundation site? I know the planning and strategy initially did not include its presence. Now that we have our footing and a solid page with great content for building a movement and raising up open leaders, it would be great to put it up for reconsideration. More specifically, as we strive to work open as an organization, sharing the people, processes, and resources we are using to get us there is important. In other words, it's showing that we walk the talk.

**Comment by kristinashu** [comment]
Kristina G says she will have feedback on Monday.

@alanmoo if they go with [this template style](https://foundation.mozilla.org/en/campaigns/open-leadership--events/) will we be able to put it at /initiative instead of /campaign? If not then I guess it could be a parent like https://foundation.mozilla.org/en/mozfest/

**Comment by alanmoo** [comment]
We should be able to. I filed https://github.com/mozilla/foundation.mozilla.org/issues/3061

**Comment by kristinashu** [comment]
Thank you Alan! 

### Newsletter
I've updated the newsletter comps with the latest copy https://redpen.io/p/hpd125097a02f591fb. 
Next steps:
- [ ] get approval from Kristina G
- [ ] meet with Alex for him to build it

### Website
Webpages are here https://foundation.mozilla.org/en/initiatives/open-leadership--events/. 
Next steps:
- [ ] get approval from Kristina G
- [ ] get confirmation from @stephaniemcv that list is set up 
- [ ] test the signup
- [ ] redirect https://foundation.mozilla.org/en/opportunity/global-sprint/ to https://foundation.mozilla.org/en/initiatives/open-leadership--events/
- [ ] delete pages 
  - https://foundation.mozilla.org/en/initiatives/mozilla-open-leadership--events/ (was only used internally) 
  - https://foundation.mozilla.org/en/campaigns/open-leadership--events/ (was only used internally) 
  - https://foundation.mozilla.org/en/opportunity/global-sprint/ (will redirect)

**Comment by kristinashu** [comment]
Update the list above ^

[Form](https://foundation.mozilla.org/en/initiatives/open-leadership-events/.) is set up so people can sign up and they will be added to the OLE list. The welcome email is build but not hooked up yet so people will receive confirmation and the general mozilla welcome email but won't receive OLE's welcome email yet.

@stephaniemcv won't get to this this week but once she has set up the journey then I will get updated newsletter content from @KGorr, update the comps, and then Alex can build it.

**Comment by gideonthomas** [comment]
@stephaniemcv any updates on this?

**Comment by gideonthomas** [comment]
There hasn't been any movement on this yet. Let's check in next week again.
