### ISSUE TITLE
Foundation Site: Forms

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#344]
### Description

Audit our forms and examine where we can align styles. Mockup refined ideas in context of existing site (or upcoming projects like Join Us page or MozFest CFP) and collect feedback. After successful review, we can prepare to clean up our forms for implementation and document them.

### Form system may include:

- form field container (filled text, empty text, validated text)
- form field styles (single field, multi-line field, text area field)
- form field states (inactive, focused, active, hover, error, disabled) 
- form headings, labels and input text
- help assistive text (required text, hints, character limit counter)
- validation text (error, success)
- disclaimer and checkbox text
- check boxes and radio buttons
- icons (leading, trailing)

### Links to audit and reference
Petition form ([open letter to fb example](https://foundation.mozilla.org/en/campaigns/eu-misinformation-facebook/))
Email newsletter form ([header](https://redpen.io/fdd22341e79a61e590), & [footer](https://redpen.io/qjc31269b9f9bf17f0))
Donate form ([donate.mozilla.org](https://donate.mozilla.org/en-US/?utm_source=foundation.mozilla.org&utm_medium=referral&utm_content=header))
Pulse form ([add entry](https://www.mozillapulse.org/add))
Call for Proposals form ([MozFest 2018 Screencap](https://user-images.githubusercontent.com/2896608/39336759-0db0e132-496e-11e8-9dfe-38b3106d74e5.jpg))
Mozilla.org forms ([email sign up](https://www.mozilla.org/))

cc: @kristinashu @sabrinang @natalieworth @beccaklam @mmmavis

**Comment by mmmavis** [comment]
Thanks for creating this helpful list, @sabrinang . Can we add dark theme design to this ticket as well? Two things I ran into when I implemented the footer sign up form (on black background) are border color for fields and colour/behaviour for links appear in field label.

**Comment by natalieworth** [comment]
I've created a forms WIP page in Foundation sketch and have added notes/ examples [to redpen here.](https://redpen.io/p/bv7967653dd95106e0)

<img width="1000" alt="Screen Shot 2019-05-06 at 11 26 34 PM" src="https://user-images.githubusercontent.com/14876567/57276421-6d042f80-7056-11e9-8752-5ae93b81cc19.png">

**Comment by natalieworth** [comment]
@kristinashu @sabrinang @beccaklam @xmatthewx Want to talk about this tomorrow or in person on Wednesday? If we are good on the form styles then I can update in sketch/ library and close this tic.

**Comment by kristinashu** [comment]
Design-wise there look great but we should talk to @mmmavis @youriwims about implementation and how this will affect our other forms. Maybe chat after stand on Thursday?

**Comment by mmmavis** [comment]
Yea we should chat. Forms on Pulse and Foundation site are implemented differently (e.g., Pulse uses an external form library). It will require quite a bit of effort to rewrite the code if we want them all to follow the same design.

**Comment by xmatthewx** [comment]
Given the amount of work, let's pause this until after we get a sense of our next priorities at all hands.

**Comment by kristinashu** [comment]
Closing this ticket since it is very old and out of date.
