### ISSUE TITLE
Graphic for iPhone campaign - deadline EOD today 😭

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#345]
Image that plays on the look and feel of Apple's campaign to help make the campaign point.

Their concept comp:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1068783/56056304-9f00cb00-5d10-11e9-93c2-5f03886dcec4.png">

Here's what Abigail said from Legal about the image:
> If this is done with our own image and font (i.e., not taking an actual apple ad image), it's probably okay. Ideally the use would be limited to displaying it only on the petition page
^^So those criteria are key to making sure it works from a legal perspective. 

Copy: `Privacy. Is that iphone?`
Localised copy for you too soon.

Deadlines: Email on Monday

Will go on petition page: https://foundation.mozilla.org/cms/login/?next=/cms/pages/372/edit

**Comment by TheoChevalier** [comment]
Alright, here’s the French slogan: `Respect de la vie privée. C’est (presque) ça l’iPhone.`

**Comment by TheoChevalier** [comment]
And here’s German copy: `iPhone. Das ist (halbwegs) Privatsphäre.`

**Comment by kristinashu** [comment]
Thanks @TheoChevalier. Not sure which graphic we will be using but here is an example of the translations https://redpen.io/p/hjb61198b1121dce13

**Comment by TheoChevalier** [comment]
Great work @kristinashu! Translations look great :)

(Looks like there was a small capitalization mistake in the English copy above, the P in iPhone should be capitalized)

**Comment by kristinashu** [comment]
Nice catch, thank you!
