### ISSUE TITLE
Foundation Site: Iconography

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#346]
### Description

Audit our icons and examine where we can align styles. Mockup ideas and recommendations and collect feedback. After successful review, we can prepare to clean up our icons or make new ones for implementation and document them.

### Icon system may include:
- in-line icons glyphs for text and buttons (before, after)
- small icons for image text mini component
- large icons for image text component
- mozilla festival spaces/experience icons / internet health icons
- UI functionalities (form validation, favs etc.)
- animation? motion?
- hover states, interactive state

**Design**
- size (small, medium, large)
- icon grid
- shape
- fill style vs outline style
- stroke cap (round, square)
- stroke angle and curves
- corner radius
- margin and depth
- colors (dark theme)
- visual density, detail and fidelity
- emojis???

**Application**
- document design tips/template and usage best practices
 
### Links to audit and reference
https://design.firefox.com/photon/visuals/iconography.html
https://mozilla.github.io/foundation-icons/

http://foundation.mozilla.org/
https://foundation.mozilla.org/en/privacynotincluded/
https://internethealthreport.org/
http://mozillafestival.org/
https://www.mozillapulse.org
https://www.mozilla.org

cc: @kristinashu @sabrinang @natalieworth @beccaklam @mmmavis

**Comment by sabrinang** [comment]
Iconography audit in [google slides](https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit?usp=sharing) _(slide 63-70)_

**Comment by sabrinang** [comment]
@natalieworth I think in some of your new pulse and donation footer UI work you are experimenting with some iconography? let's coordinate

**Comment by sabrinang** [comment]
I've made an update to abstract with updated icon progress so far.
I created an icon grid for:
- X-Small (12px)
- Small (24px)
- Medium (48px)
- Large (96px)

**Icon Style**
Border: center
 Width: 2  (0.5 for x-small icons)
Ends: round cap
Joins: round
Corner radius: 2 or 0
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/2492510/56932452-c093dd80-6a98-11e9-88d4-0d643be8e09a.png">

![Screen Shot 2019-04-29 at 4 08 27 PM](https://user-images.githubusercontent.com/2492510/56932547-15cfef00-6a99-11e9-863e-59a86c8b73d7.png)

Next step to mockup icons in-line with text should be iterated upon next so I can see how the corners and caps look with Zilla Slab or Nunito Sans in context. 

@kristinashu @natalieworth @beccaklam Please share any feedback on style, visual metaphor and upcoming icons that would be needed. It'd be great if you can test these out in mockups as well if they apply.

@mmmavis I'll also be reaching out again how to prepare this for implementation and any feedback is appreciated at this point.

**Comment by sabrinang** [comment]
Reference: Some small icons were adapted from https://feathericons.com/

**Comment by natalieworth** [comment]
Hey @sabrinang I used your icons for the Pulse page here https://redpen.io/p/pwa30a89c875d0d841

I think it looks nice!!

Just making a note too that we may need 'small' sizes for the social icons within the footer in order to streamline and make sure everything is the same size. I think currently they only exist in extra small, but I can update when I get time. :)

**Comment by natalieworth** [comment]
<img width="602" alt="Screen Shot 2019-05-08 at 8 17 38 PM" src="https://user-images.githubusercontent.com/14876567/57424964-5a146b00-71ce-11e9-8504-1b5f1779c13f.png">

added our footer icons as 'small' size in the iconography doc

**Comment by natalieworth** [comment]
@sabrinang I think you covered all the icons that we need and they look great! I think the sizing seems to be working to. I think we can close this ticket and open a dev/implementation tic when we get time over the next few weeks?

**Comment by sabrinang** [comment]
For sizing, I've been testing them in MozFest mockups before and after buttons:

and have been scaling down the 24px small to 16px to fit
<img width="500" alt="Screen Shot 2019-05-15 at 9 49 34 AM" src="https://user-images.githubusercontent.com/2492510/57793708-d4754b80-76f6-11e9-8382-b6e10b11b62e.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2492510/57793582-84968480-76f6-11e9-8b53-17416f03aec6.png">

In my branch I also added some x-smalls for youtube, medium and mail and white versions for them:
<img width="100" alt="image" src="https://user-images.githubusercontent.com/2492510/57793841-2c13b700-76f7-11e9-988b-bad7ed3c222a.png">
but I also ended up scaling them up to 24px instead of 12px cause they were too small. So I'll need to remake them as small icons 
<img width="964" alt="Screen Shot 2019-05-15 at 9 53 35 AM" src="https://user-images.githubusercontent.com/2492510/57793946-62e9cd00-76f7-11e9-8b29-3dc4574f2882.png">

**Comment by sabrinang** [comment]
Organized the sketch file a bit more and we can continue to refine and test icons, for example for external links:
<img width="229" alt="image" src="https://user-images.githubusercontent.com/2492510/58135549-c84e2a00-7bdf-11e9-92fe-07c93907812f.png">

Documented the bulk of what we have on https://foundation.mozilla.org/en/docs/brand/design/iconography/
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/2492510/58135679-3561bf80-7be0-11e9-99b0-250c5d310cf6.png">

@natalieworth I think we can close this ticket too and continue to add colour variants and refine as we need or use them.
