### ISSUE TITLE
Fellowship Alumni newsletter & signup page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#348]
Similar to #343

~Deadline: May 2 launch~

From Ann Marie: 
> We need to have a Salesforce newsletter created for fellow + awards alumni (~300 people). The goal is to have this newsletter be a way to remain engaged with our alums and share opportunities only available to them as we currently have no way of staying in touch with our community on a large scale. 

[Strategy & content doc](https://docs.google.com/document/d/1z6uGaYKGJSgVeUO8zUElwtBvqAin4n5pFLQY1_rwwP4/edit?ts=5cb62902)

### Newsletter
- Welcome email (copy in doc) 
- Newsletter template (need example copy)
- Design should follow our general newsletter layout https://redpen.io/ks8bc539b21350e632

### Newsletter signup on site
- Design should follow the same layout as MozFest & OLE signup and look something like https://redpen.io/rk0f873e082c22348f 
- Content https://foundation.mozilla.org/en/opportunity/mozilla-fellows-and-awardees-newsletter/
- Would need to add form fields:
  - Subscriber’s First name
  - Subscriber’s Last name
  - If Subscriber was/is a Fellow or Awardee

cc @annmarie123 @stephaniemcv @anilkanji

**Comment by kristinashu** [comment]
Comps are coming along here https://redpen.io/p/xg01340660ab6e67f8

**Comment by stephaniemcv** [comment]
@annmarie123 has Fellowships signed off on the design of the Welcome Email? If yes, @kristinashu can you get the banner asset to Alexander to code up? The LCM team and I are wrapping some of this work up in MoCo's project Trailhead.

**Comment by kristinashu** [comment]
Excellent! Ann Marie is on PTO today but yes the design and copy are approved. I will send Alexander the banner and copy doc now.

**Comment by kristinashu** [comment]
### Emails
- [x] comp https://redpen.io/p/xg01340660ab6e67f8. 
- [x] get approval from Ann Marie
- [x] Alex to build out welcome email
- [x] @stephaniemcv to set up basket
- [ ] @stephaniemcv to set up journey
- [ ] Alex to build out newsletter (might need to update content since it's been so long)
- [ ] @stephaniemcv to train Ann Marie

### Website
- [x] webpage is set up https://foundation.mozilla.org/en/fellowships/newsletter/
- [x] get approval from Ann Marie
- [ ] add optional first/last name capture to signup snippet #3106 (Alan is working on now)
- [ ] test the signup
- [x] redirect https://foundation.mozilla.org/en/opportunity/global-sprint/ to https://foundation.mozilla.org/en/initiatives/open-leadership-events/
- [x] delete pages 
  - https://foundation.mozilla.org/en/initiatives/mozilla-open-leadership-events/ (was only used internally) 
  - https://foundation.mozilla.org/en/campaigns/open-leadership-events/ (was only used internally) 
  - https://foundation.mozilla.org/en/opportunity/global-sprint/ (will redirect)

Sooo the [form](https://foundation.mozilla.org/en/fellowships/newsletter/) is set up so people can sign up and they will be added to the Fellowships list. The welcome email is build but not hooked up yet so people will receive confirmation and the general mozilla welcome email but not Fellowships's welcome email yet.

@stephaniemcv won't get to this this week but once she has set up the journey then I will get updated newsletter content from @annmarie123, update the comps, and then Alex can build it.

**Comment by stephaniemcv** [comment]
Confirm Trigger and Journey canvas are built and running. I am ready to test the form.

**Comment by kristinashu** [comment]
💃

**Comment by gideonthomas** [comment]
The website work is done (I updated the tasks in the main comment). All that's remaining are the email tasks which include setting up the templates, creating sender profiles for the team, documentation, and training Ann Marie.
