### ISSUE TITLE
Set up a Screenshot tumblr

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#35]
- [x] Set up tumblr: http://desktopdailies.tumblr.com/
- [x] Create IFTTT recipe to collect screenshots in a dropbox (@xmatthewx I can't remember the value of this, or why not Drive?)
- [x] ~~Cancel Dribbble account (???)~~ – Filed as new issue https://github.com/MozillaFoundation/Mofo-Design-Handbook/issues/41
- [x] Walk-through with designers to make sure everyone understands and has a good workflow 
- [x] Update the tumblr aesthetics
- [x] Spread the word about the tumblr via twitter
- [x] Spread the word about the tumblr via emails to all@ and mofodesign
- [ ] ~~Spread the word about the tumblr via #livedesign on IRC~~ will leave this to happen organically
- [x] Show tumblr at demos
- [x] figure out commenting
- [x] change title to 'mozilla foundation designers'

Goal: Have a "drive by" design culture that works with remote environments. Invite casual glances into what we're working on.

**Comment by xmatthewx** [comment]
@cassiemc - I just followed the blog. Can you add me as a member? Note: I believe that you can only add members to a secondary blog, not your primary.

**Comment by cassiemc** [comment]
I added mw@mozillafoundation.org, is there another address I should've used? @xmatthewx

**Comment by cassiemc** [comment]
I've invited @xmatthewx and @flukeout by request. If anyone else wants to join I believe you can do taht here: https://www.tumblr.com/join/01YajuFEoK cc @lovegushwa @vazquez @sabrinang

**Comment by xmatthewx** [comment]
success! :boom:

**Comment by vazquez** [comment]
I clicked on the link but nothing quite happens. I'm a Tumblr noobie, so I may not be seeing something.

**Comment by flukeout** [comment]
Let's include our twitter handles or something in front of our posts so people know who's posting.

**Comment by cassiemc** [comment]
I've added @sabrinang and @lovegushwa to the tumblr now as well (let me know if you guys want me to use a different email than your mofo addresses).
And I've created an IFTTT recipe – going to use it today to see how it works! https://ifttt.com/recipes/304718-desktop-dailies-dropbox-to-tumblr

**Comment by cassiemc** [comment]
I tried setting up an IFTTT recipe but it didn't work. Will need to troubleshoot this next week. cc @xmatthewx maybe you can help.

**Comment by cassiemc** [comment]
I'm not loving that we can't comment on individual tumblr posts. This came to light when @vazquez asked for feedback on his daily desktop but there was no way to easily leave a comment.

Wondering if there is specific to the default theme, and could another theme make this easier, or perhaps there's a way to post on separate tumblrs but aggregate them together in one stream. I don't want to overcomplicate this and am not familiar enough with tumblr to know the best solution for this. Feedback welcome. It does seem important that we make this easy, as the two-way communication was part of the goal.

**Comment by xmatthewx** [comment]
You can turn replies on/off.  https://www.tumblr.com/settings/blog/twothickthumbs/desktopdailies

**Comment by cassiemc** [comment]
The replies option is only to allow replies from someone following the blog for more than two weeks. So I guess we have to wait two weeks to see if it worked. (I also updated the settings to show the user avatar of the person who posted)

**Comment by flukeout** [comment]
That two-week wait period is pretty funny.

**Comment by cassiemc** [comment]
I added disqus to the tumblr but I guess I don't really get how that works b/c it didn't change the interface at all to allow commenting. wtf!

**Comment by vazquez** [comment]
I can see it! It works for me.

<img width="798" alt="screenshot 2015-07-15 21 30 58" src="https://cloud.githubusercontent.com/assets/1119821/8713631/0fab0d88-2b39-11e5-88ed-2417c45834c6.png">

**Comment by cassiemc** [comment]
Oh ok, cool! I see it too if click on permalink. Feels a bit hidden but at least it's there, thanks @vazquez!

**Comment by flukeout** [comment]
Nice work @cassiemc - this is good. For me I'm finding that I'd rather post a crop of my screen, sometimes the desktop is too big to show the thing I actually want people to notice, hope it's cool with everyone that I deviate from the plan a bit.

Next up, tilted, blurry on one edge UI photos a la Dribbbbbbble!!!

**Comment by cassiemc** [comment]
All those boxes are checked so I am marking this baby resolved!
