### ISSUE TITLE
Foundation Site: Navigation 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#350]
### Description

Examine where we can align navigation styles. Mockup ideas and recommendations and collect feedback. After successful review, we can prepare to clean up typography, lines and class names for implementation and document them.

### Navigation system may include
**Nav design**
- primary navigation
- secondary horizontal navigation
- secondary vertical navigation
- tertiary filter (annual years etc.)
- mobile/responsive versions

**Nav item design**
- nav item types (child page, external link etc.)
- nav item states (hover, active etc.)

**Other**
- typography (size, line height, underlines, color etc.)
- iconography
- line system
- class names

### Links to audit and reference
primary nav: https://foundation.mozilla.org/
secondary nav & tertiary filter: https://foundation.mozilla.org/en/fellowships/meet-our-fellows/
vertical nav: https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/
https://foundation.mozilla.org/en/privacynotincluded/
https://www.mozilla.org/

### Related issues
#319 typography
#346 iconography
#314 line system

cc: @kristinashu @sabrinang @natalieworth @beccaklam @mmmavis

**Comment by mmmavis** [comment]
Let's also talk about how we can tidy up styling for special links/buttons that are on nav (e.g., the Donate button etc).

**Comment by kristinashu** [comment]
We will be tackling this soon but will open new tickets for the work.
