### ISSUE TITLE
CS Challenge Winners CMS page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#351]
Deadline: 8am EDT on Tuesday, April 30

Jenn have populated it with the winners and links to the schools' websites but would like some design TLC to it.

https://foundation.mozilla.org/en/initiatives/responsible-cs/winners/

**Comment by sabrinang** [comment]
I revised the draft page with school logos and title banner: https://foundation.mozilla.org/cms/pages/183/edit/preview/

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2492510/56774805-10ad3000-6779-11e9-9094-6bf44ad9d1a6.png">

@jenntbeard I left your original text untouched at the bottom (we can delete if the revised sections look good)

**Comment by jenntbeard** [comment]
Hi! Is it possible to not have 'Winners' listed twice (so maybe lose the text version but keep the graphic)? Also, we don't have approvals to use the school's logos, so I didn't add those - that additional round of approvals wasn't possible given the slow processing time on the agreements. Sorry, I should have mentioned sooner. Thank you for all your help!

**Comment by sabrinang** [comment]
We can’t remove the title (required field) and it is also best to have it present from an accessibility standpoint too. I can remove the banner if it is redundant or we can keep it if you have alternative copy? Okay, I removed the school logos. 

There's not much more design adjustments for me to do but let me know if you have feedback, I’ll revisit this on Monday

**Comment by jenntbeard** [comment]
Okay, no problem - sorry about the school logos (that does look nicer). Thanks for your help! I plan to publish once I've seen Kevin's blog post go live on Tuesday morning.
