### ISSUE TITLE
Typography: Bold for Copy Styles

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#353]
Currently, @mmmavis has mentioned `<b>` is one font weight heavier than the parent element (among the available weights of the font).

- determine what font weight bold should be and are we consistently doing this in sketch
- create system that works for .body-small, .body, .body-large, .quote to not have overrides

cc: @kristinashu @sabrinang @natalieworth @beccaklam

**Comment by sabrinang** [comment]
@beccaklam This might be related to some of the typography in your blog work. Is one font weight heavier than the original bold enough for your use cases or do we need heavier weights than that?

**Comment by beccaklam** [comment]
@sabrinang I think so? .body-large is Nunito Light, and the next heavier weight is Nunito SemiBold, and it looks good. The contrast isn't as stark but I think maybe that works better? You can still scan but it doesn't look as abrupt.

**SemiBold in action:**

![Screen Shot 2019-04-29 at 11 06 53 AM](https://user-images.githubusercontent.com/20977376/56905978-5ca8ef00-6a6f-11e9-9cc0-1aa110881d1d.png)

**Comment by sabrinang** [comment]
@beccaklam Nice, yes +1 that `.body-large` should be Nunito Sans Light 300 for normal weight and Nunito Sans Semibold 600 for bold weight so it has good contrast for scanning and obvious emphasis.

As for `.body` and `.body-small` their normal weight are Nunito Sans Regular 400 so their bold should be Nunito Sans Bold 700 if it isn't already.

For the CMS, body copy is currently also Nunito Sans Regular 400 and Nunito Sans Bold 700 when bolded so it looks fine (we don't have small and large options here). All headings are in similar bold proportions except `.h2-heading` where we should change the its bold to ZIlla Slab Semibold 600 to match.

<img width="810" alt="Screen Shot 2019-05-01 at 7 25 46 AM" src="https://user-images.githubusercontent.com/2492510/57021928-7880d200-6be2-11e9-8877-a7458fc202a8.png">

So it seems like a majourity of body copy (and headings) are two font weights heavier than normal already but we need to revise to be consistent with that proportion everywhere.

**Comment by mmmavis** [comment]
Sorry, forgot to specify. By "one font weight bolder" it does not always mean `100` font weight more.

This is the **default browser behaviour** for bold text (aka without special CSS style reinforcement):
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Meaning_of_relative_weights

<img width="300" alt="image" src="https://user-images.githubusercontent.com/2896608/57050962-ebfeff80-6c33-11e9-9f77-ff8eb3e0853f.png">


e.g., on CMS, if the component you are editing has default font weight `400`, bolded text in that component by default will appear in font weight `700` (and not `500`)

**Comment by kristinashu** [comment]
To limit our overrides let's stick to the defaults, even if they aren't as bold as we would like then to be.

How does this sound for next steps?
- open a dev ticket to add examples of bold text to the [style guide ](https://foundation.mozilla.org/en/style-guide/)
- update abstract file with default bold weights

**Comment by beccaklam** [comment]
> To limit our overrides let's stick to the defaults, even if they aren't as bold as we would like then to be.
> 
> How does this sound for next steps?
> 
>     * open a dev ticket to add examples of bold text to the [style guide ](https://foundation.mozilla.org/en/style-guide/)
> 
>     * update abstract file with default bold weights

Hmm, the only thing override I would push for is for .body-large. I know keeping our code clean is a good thing, but this actually affects the usability for our blog posts. I think scanning is important to reading and from experience, staff _love_ to bold. Just wanted to voice that consideration before we move forward. Thoughts, @kristinashu ?

**Comment by beccaklam** [comment]
So, just took a look at our current blog. Bolding .body-large right now results in a font-weight of 700, is this the default or did we override here? @mmmavis

**Comment by mmmavis** [comment]
We have SCSS override just for bold text on the blog body to make it have font weight `700`. Check out the gif below to see how bold text (`<b>`) will look like with and without the override.

![blog-bold](https://user-images.githubusercontent.com/2896608/58919504-31a36200-86e3-11e9-8913-a4862ee26240.gif)

**Comment by kristinashu** [comment]
@beccaklam your next steps sound good and I'm ok with an override for the blog's body if you think it's necessary.

**Comment by beccaklam** [comment]
Okay I take back my push back. Looking over some professional articles (NYT, Atlantic) and blogs (Medium) bolding doesn't seem to be a prominent feature. It may be good to encourage staff to add emphasis in other ways that are less intrusive than using bolding (it's a bit too much sometimes). So in that case, we'll just go ahead with Kristina's next steps:

- open a dev ticket to add examples of bold text to the style guide
- update abstract file with default bold weights

**Comment by kristinashu** [comment]
Yay for defaults!

**Comment by beccaklam** [comment]
@kristinashu Which repo do I open the dev tickets in? The foundation site repo?

**Comment by kristinashu** [comment]
Yup!

**Comment by beccaklam** [comment]
Dev ticket to add examples of bold text to style guide here: https://github.com/mozilla/foundation.mozilla.org/issues/3303
Dev ticket to make blog the default bold weight here: https://github.com/mozilla/foundation.mozilla.org/issues/3304
