### ISSUE TITLE
Establish process for future Brand updates/changes

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#355]
### Intro

Creating a ticket to track brand updates/ changes and how we can create a good process for this between designers and developers.

**Comment by natalieworth** [comment]
https://redpen.io/p/da7fb982eedd9ba047

**Comment by sabrinang** [comment]
Thanks for this issue Nat, I have some process ideas to consider:

- create brand standard update, change or override issue (with label brand standards)
    - include annotated redpen or screenshots, notes on use cases or impact etc.
    - request design review
    - get dev feedback
    - comment, approve or request changes
- update https://foundation.mozilla.org/en/docs/brand/ and https://foundation.mozilla.org/en/style-guide/ (if applicable) to reflect decisions
- update sketch file style guide
- update impacted designs in corresponding sketch files where change applies

**Comment by natalieworth** [comment]
Redpen and GitHub ticket proposal (with review)
Developer/ design review
update brand guidelines and Sketch file
update pages in Sketch
Implementation ticket

**Comment by natalieworth** [comment]
Github template to update the style guide w/ checklist

**Comment by natalieworth** [comment]
More formal approval for small/ big things R+ review from designers

**Comment by natalieworth** [comment]
Comb through Sketch document to update symbols (and unlinked symbols)

**Comment by natalieworth** [comment]
Using Mavis' awesome design to dev handoff for inspiration to create a future brand standard changes in our ticket. I'm thinking based on [Sabrina's notes and meeting ](https://docs.google.com/document/d/14jCcjRCqVlFXMSwhGuw-xKpZoQWbJlbxu11S5u-sEZg/edit#heading=h.a9fvyh5rdcla)that we could create an issue template in the Design Ops repo for each type of update (e.g. Override, Updating an Existing style, and Introducing a New Style). 

Draft:


Enter actual ticket description here

---

**### 🗒  Brand Update Checklist**
(Feel free to remove items that are not applicable.)

### Override an existing style _(exception)_
- [ ] Post proposed brand update in Redpen
- [ ] Request design review from design team via R+/R- in Github ticket
- [ ] Why it is needed
- [ ] What else might be affected
- [ ] Check overrides are annotated
- [ ] Consider if override can improve the rest of brand system
- [ ] Consider dev implementation time
- [ ] If approved, update and merge the Sketch library, comps, and documentation _(make sure to comb through and look for unlinked symbols that may be affected)_
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

### Updating an existing style
- [ ] Post proposed brand update in Redpen
- [ ] Request design review from design team via R+/R- in Github ticket
- [ ] Why it is needed
- [ ] If approved, update and merge the Sketch library, comps, and documentation _(make sure to comb through and look for unlinked symbols that may be affected)_
- [ ] Update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

### Introducing a new style
- [ ] Post proposed brand update in Redpen
- [ ] Request design review from design team via R+/R- in Github ticket
- [ ] Why it is needed
- [ ] If approved, update and merge the Sketch library, comps, and documentation _(make sure to comb through and look for unlinked symbols that may be affected)_
- [ ] Update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)


### Design Reviewer Checklist
_An issue template in github_
**For design review:**
- [ ] Is this change justified or are we able to use existing brand elements?
- [ ] Is the development time viable?
- [ ] Provide an R+ or R- in the ticket
- [ ] List reasons for approving or denying changes

@kristinashu @sabrinang @beccaklam @xmatthewx Feel free to edit/ hack on this list.

**Comment by beccaklam** [comment]
Draft:


Enter actual ticket description here

---

**### 🗒  Brand Update Checklist**
(Feel free to remove items that are not applicable.)

### Override an existing style _(exception)_
What element/ style is being changed?
Why is it an override versus a new style/improved style for the whole Foundation site? 
What else might be affected? 
- [ ] Post proposed brand update in Redpen
- [ ] Request design review from design team via R+/R- in Github ticket
- [ ] Check overrides are annotated
- [ ] Get feedback from devs

**After Approval**
- [ ] Update and merge the Sketch library _(make sure to comb through and look for unlinked symbols that may be affected)_
- [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

### Updating an existing style
What element/ style is being changed?
Why it is needed?
- [ ] Post proposed brand update in Redpen
- [ ] Request design review from design team via R+/R- in Github ticket

**After Approval:**
- [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
- [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
- [ ] Update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

### Introducing a new style
What element/ style is being changed?
Why it is needed?
- [ ] Post proposed brand update in Redpen
- [ ] Request design review from design team via R+/R- in Github ticket

**After Approval**
- [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
- [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
- [ ] Update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
- [ ] Create a dev implementation ticket (following the design to dev hand-off outline)


### Design Reviewer Checklist
_An issue template in github_
**For design review:**
- [ ] Is this change justified or are we able to use existing brand elements?
- [ ] Is the development time viable?
- [ ] Provide an R+ or R- in the ticket
- [ ] List reasons for approving or denying changes

@kristinashu @sabrinang @beccaklam @xmatthewx Feel free to edit/ hack on this list.

**Comment by kristinashu** [comment]
For simplicity, we talked about how this could be one ticket template and people can just delete what isn't relevant.

**Comment by natalieworth** [comment]
I created a template ticket (pull request/ awaiting review) here: https://github.com/MozillaFoundation/Design/pull/360

**Comment by natalieworth** [comment]
Just adding for tomorrow that we need to add desktop/ mobile mockup and checks for the style changes/ updates.

**Comment by natalieworth** [comment]
Updated new issue template #362

**Comment by natalieworth** [comment]
Issue template is live here! https://github.com/MozillaFoundation/Design/issues/new/choose
Closing this tic!
