### ISSUE TITLE
Graphic for Amazon campaign

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#356]
#### Deadline
In editorial calendar for May 9 (before Mothers Day on May 12)

#### Copy
Aiming for approval on Monday 6 
https://docs.google.com/document/d/1FDqHf-EPexLUES6owrWS-3HUlS6acGyhV0-eahcdLVk/edit
They will test two different version of the copy but let's try to make one graphic that will work for both so the only variable is copy.

#### From Kaili in Slack

> Campaign targeting Amazon to require third party vendors selling IoT products on its platform to provide a privacy policy for connected devices.

> As background, during PNI research it became clear that a privacy policy was almost a litmus test for if a company was "real" – that is products that tended not to have a privacy policy also didn't have good costumer service, webpages or thought through security systems – and this is true for a number of popular products sold on Amazon. An initial list that Becca has compiled is below. Given that many of the devices are marketed as baby monitors, and some of these products like the FREDI have been in the news for their privacy flaws, we think a hook around Mothers Day would make for a good campaign launch.

Might be a chance to revive some of the cloudpets concepts https://redpen.io/p/hkd825b18079a13112!

cc @natalieworth @beccaklam @xmatthewx

**Comment by kristinashu** [comment]
Designers will brainstorm a few ideas on Monday, narrow it down to 3 concepts, share ideas (maybe sketches) with advocacy team and legal for feedback, then create the one graphic.

**Comment by kristinashu** [comment]
Matthew and I chatted and we agree that we would like this campaign to have an image to help it stand out. 

Here are a few ideas we had for upcycling some graphics:
- a version of the white iot banner image from http://privacynotincluded.org/
- a version using assets from misinfo campaign but with the amazon logo https://foundation.mozilla.org/en/campaigns/eu-misinformation/ (something in the family of this youtube one https://github.com/MozillaFoundation/Design/issues/349#issuecomment-484706042)
- an adaptation of the cloud pets graphic https://redpen.io/p/hkd825b18079a13112 but to be more related to either amazon or connected devices in general (maybe mixing the video frame with the kid silhouette?? but as is, none of those cloudpets graphics quite make sense for this campaign)

Rebecca will do some quick mockups of these, share them with Kaili and Abigail, and then we can refine the selected version.

**Comment by beccaklam** [comment]
Very rough mock ups here: https://redpen.io/p/fq3038f60c920958f6 I'll reach out to Kaili and Abigail tomorrow!

**Comment by beccaklam** [comment]
@kristinashu let me know if you have any feedback! ☝️

**Comment by kristinashu** [comment]
These look great @beccaklam!

@kaili09 do you have any preferences or feedback?

**Comment by kaili09** [comment]
I think I prefer the first one, and like the second one a lot too, but I also wonder about using Amazon's logo without risk of copyright issues?

**Comment by kristinashu** [comment]
Ok excellent! So tomorrow morning, @beccaklam could you please delete the CloudPets direction from redpen and share the other two with Abigail to see if she has concerns about either of them?

**Comment by beccaklam** [comment]
Hi @kristinashu @kaili09, so I chatted with Abigail and she says even with the context of the petition text she would avoid using the amazon logo here for legal reasons. She also said we can set up a time to talk more about how to use logos with less legal risk for future cases.

**Comment by kristinashu** [comment]
Sounds good! Let's roll with the first graphic. Can you add a high res version here?

@kaili09 do you need any help creating the petition page in wagtail?

**Comment by beccaklam** [comment]
I've attached the file size export of the first graphic [here]([https://drive.google.com/open?id=1Rx9HnyUfoqTyQD6Xmq5lqrultYjowJ_y]). @kaili09 please let me know if you need anything else!

**Comment by kristinashu** [comment]
Closing this ticket but yes, just let us know if you need anything else.
