### ISSUE TITLE
Update to an existing style: H4 line height

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#357]
Using this ticket to test the '**Updating an existing style**' template proposal for Design repo issues regarding the brand standards. 

Style to change: The **line height of H4** in our brand standards for the Foundation site.

[Redpen link is here with the original and proposed change.](https://redpen.io/p/gk2682339c5647f381)

The current H4 leading feels quite large and difficult to read. The CSS line-height is currently 1.5. I am proposing 1.2—or alternatively, we could adjust the CSS so it aligns with our standards of 24/30px for heading and 22/28px for mobile and uses px measurements?

### Updating an existing style
- [x] What element/ style is being changed?

- [x] Post proposed brand update in Redpen (for desktop and mobile)

- [x] Why it is needed?

- [x] Request design review from design team via R+/R- in Github ticket

- [x] If approved, update and merge the Sketch library, comps, and documentation _(make sure to comb through and look for unlinked symbols that may be affected)_

- [x] Update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)

- [x] Create a dev implementation ticket (following the design to dev hand-off outline)

cc: @kristinashu @sabrinang @natalieworth @xmatthewx @beccaklam

**Comment by kristinashu** [comment]
Nice @natalieworth! Is there an example of H4 line height on the live site? I'm having trouble finding a real example...

**Comment by natalieworth** [comment]
@kristinashu I don't think there is one on the foundation.mozilla.org site right now actually? I can't find one either. But wondering if we should also update the 'Trending project' cards so they match the Pulse style?

**Comment by kristinashu** [comment]
R+ for line height update, it definitely looks much better in the comp!

It would be nice to align the Pulse cards on Foundation site and Pulse but I think that should be a new ticket and would need to be mocked up 😊.

**Comment by kristinashu** [comment]
I just noticed in the [style guide](https://foundation.mozilla.org/en/style-guide/) that h4 has different line height for desktop vs mobile, it's slightly less on mobile (not in this case but _sometimes_ a font size is smaller on mobile than desktop). Maybe we should add a step around checking it at desktop, tablet, and mobile and maybe also a step around running past the suggested change with a dev for feedback?

**Comment by natalieworth** [comment]
Also @kristinashu wondering how many R+'s I should get on this? Do you think it just requires one?

**Comment by kristinashu** [comment]
I think one is good but others should speak up if they foresee any issues!

**Comment by beccaklam** [comment]
I'm good with this! R+ for fixing the H4 line height.

**Comment by natalieworth** [comment]
These have been approved. Just working on updating Sketch file:
**desktop**
<img width="403" alt="Screen Shot 2019-05-27 at 2 33 44 PM" src="https://user-images.githubusercontent.com/14876567/58440464-09868400-808f-11e9-9284-ff965bcbf9db.png">

**mobile**
<img width="317" alt="Screen Shot 2019-05-27 at 2 33 16 PM" src="https://user-images.githubusercontent.com/14876567/58440467-0db2a180-808f-11e9-955e-2aeb254e5915.png">

**Comment by natalieworth** [comment]
Need to update the Pulse cards on the Foundation site (so it matches Pulse styling)

**Comment by natalieworth** [comment]
Hey @mmmavis @youriwims do you know what the **h4** 1.25 line-height means or what unit of measurement that is? I tried converting it to px using rems/ ems but it says that it is 20px—but the type is 24px. Not sure if it's decreasing by a %? I can explain tomorrow or hop on a call if that didn't make sense.

**Comment by mmmavis** [comment]
@natalieworth `1.25` is a multiplier. So if the font size is 10px by having `1.25` as line height it means the line height will be `10px*1.25=1.25`.

Let us know what font size and line height you want to change `h4-heading` to for both mobile and desktop. You can list the line height in `px` and we can do the conversion ourselves. 👍

**Comment by youriwims** [comment]
Just to add on to Mavis' comment, the 1.25 line-height is more of a relative measurement that offers more flexibility/visual consistency when updating font size later rather than using an absolute value(what you see in Sketch in `px`).
Also, if you're curious how we calculate our line-height, it's `line-height(px)/font-size(px)= relative line-height(no specific unit)`.I hope that made sense and didn't confuse you more @natalieworth lol I used to always be confused with the line height value we used in code vs what I saw in Abstract/Sketch too.
Line-height reference (quick read if you're interested 😸 ): https://www.thejtsite.com/blog/single/how-to-calculate-relative-css-line-height

**Comment by natalieworth** [comment]
So currently our Sketch library is updated and has h4 set to **desktop 24px/30px** and **mobile at 22px/28px**. So could we update the **desktop h4 to 1.25 and mobile to 1.28**? This would apply across all our brand standards (both the Foundation and Pulse site).

**Comment by natalieworth** [comment]
I can create a dev tic for this @mmmavis based on your design to dev hand off? So we can update https://foundation.mozilla.org/en/style-guide/

**Comment by natalieworth** [comment]
Filed a dev ticket for this, so closing https://github.com/mozilla/foundation.mozilla.org/issues/3270

**Comment by natalieworth** [comment]
wait no, opening again so I can check off dev updates when they are completed

**Comment by kristinashu** [comment]
I think this is good to close! Mavis update the style guide and foundation site https://github.com/mozilla/foundation.mozilla.org/pull/3288 and Youri has a ticket for Pulse.
