### ISSUE TITLE
MozFest: Welcome email design template

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/Design#358]
### Intro

When people sign up to MozFest, they (are supposed to) get a welcome email. Asking for a design for the template.

### Links

Copy: https://docs.google.com/document/d/1Soo-lCbjQ1Ty5ruK27NiDeHRbYK4F5msKNSGwiLSjq0/edit

cc: @sabrinang and @stephaniemcv

**Comment by sabrinang** [comment]
Closing - continuing this work on https://github.com/MozillaFoundation/mozfest-design-2019/issues/18
