### ISSUE TITLE
Document ideal file structure for Drive

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#36]

**Comment by cassiemc** [comment]
We have a sample folder, but we need to tweak it so it works well, need to ensure it is backed up appropriated, and then documented so other people know how to use it.

**Comment by lovegushwa** [comment]
Here is the first pass. I kicked it around with @thisandagain to shape the language a structure and conventions a bit more.

Check out Webmaker > Webmaker-brand-2015
I'm going to continue to put up other projects and refine the structure over next week.

https://drive.google.com/a/mozilla.com/folderview?id=0BzfN9sXlOXt1OE01ekI2LVA4RGM&usp=sharing
