### ISSUE TITLE
Share templates with staff

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#363]
Based on convo with @sabrinang, we would like to make a few small updates and then share out our templates with staff. 

### Updates to [guide](https://foundation.mozilla.org/en/docs/brand/design/templates/)
- [x] Add link to moco slide deck (mozfest slides when available) [Sabrina]
- [x] move /templates as secondary item (so url will be https://foundation.mozilla.org/en/docs/brand/templates/) [Sabrina]
- [x] create a short link http://mzl.la/templates [@xmatthewx]
- [x] resubmit google doc template to moco [Sabrina]
- [x] add intro text (include a link to "Request a new template" that will link to https://mzl.la/project-brief) [Kristina - but will be similar to copy below]

### Socializing the page
- [x] Sabrina will share in Slack #mofo-staff 
- [x] Rough copy (please edit)
> In an effort to standard and streamline our one cohesive brand we have complied our templates http://mzl.la/tempates. These are for internal and external use and include letterheads for print or digital use, google forms, and slides. If you have a template request for something you think other staff could use, please request it at https://mzl.la/project-brief. Feel free to ping me here or in #mofo-design if you have questions, feedback, ideas, or requests.

**Comment by xmatthewx** [comment]
Excellent. Here's a slight rewrite. Feel free to reject any bits you don't like. 

> Hi staff. tl;dr - We've got fresh Mozilla branded doc templates for you. Check out http://mzl.la/tempates. 

> In an effort to advance the MoFo brand, we created & gathered templates for your use. These are for internal and external use, print and digital, and include letterhead, google forms, slides, and more. 

> If you need a template you think other staff could use, please request it at https://mzl.la/project-brief. Feel free to ping me or any designer in #mofo-design if you have questions, feedback, ideas, or requests.

**Comment by xmatthewx** [comment]
Could we add a note on the template page that MoFo slide is coming soon? Should we drop in last year's mozfest or all hands deck?

**Comment by kristinashu** [comment]
Yeah we could add a link to those two slide desk with a note that 2019 versions are in the works.. But for simplicity, we decided against a full general MoFo specific slide deck.

**Comment by kristinashu** [comment]
@xmatthewx how do you make the short link? Do you need to know the account login?

**Comment by xmatthewx** [comment]
Shortlink is ready: https://mzl.la/templates

**Comment by kristinashu** [comment]
Awesome thank you!

I've added the intro text along with links to the 2018 MozFest (I could only find slides for Dialogue & Debates) and 2018 All Hands slide decks. @sabrinang please update as you see fit and share the page when you are ready!

**Comment by xmatthewx** [comment]
I suggest you share Tuesday morning after the long weekend. You'll probably get more eyeballs than on a Friday.

**Comment by sabrinang** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/2492510/57945902-e3433600-788f-11e9-96f0-73f29ce46572.png">
updated to generic template 2018 mozfest (removed dialogue and debate it seems too specific for staff)

**Comment by sabrinang** [comment]
Posted on slack - closing issue!
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2492510/58117494-9030f200-7bb3-11e9-9b25-30de7bdc3b97.png">

**Comment by kristinashu** [comment]
It's already getting some nice reactions!
<img width="240" alt="image" src="https://user-images.githubusercontent.com/1068783/58118127-11d54f80-7bb5-11e9-9048-5db2e5ed93c6.png">
