### ISSUE TITLE
Assets for All Hands

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#364]
Deadline May 24

#### Create a new graphic for All Hands and then update assets.

- [x] new direction for the graphic
- [x] update last year's slide deck with new graphic
- [x] advise on colors for the photobooth backdrop
- [x] scale graphic to make a sticker
- [x] name tag template
- [x] update http://mzl.la/templates with image and link to new slide deck

Last year's assets are [here](https://drive.google.com/drive/folders/1o_oJh-TlT-BscnQ2yJvJzH3S6SnHV2Wq?usp=sharing).

@xmatthewx @sabrinang @natalieworth any inspiration for the graphic? Something from our new branding or something cool we've made in the past but was never used? I wanna cool sticker!

**Comment by kristinashu** [comment]
Note: Phia has suggested use just update last year's graphic with new colors so if no one is feeling inspired we can just do that...

**Comment by xmatthewx** [comment]
minimal refresh on last year's graphic is great. or, porting over new brand stuff is great. investing too much time beyond that, not so great.

**Comment by natalieworth** [comment]
Added a graphic direction with previous assets and our new brand colours. Let me know what you think here: https://redpen.io/p/pnf157d2880884859a
cc @kristinashu @xmatthewx @sabrinang @beccaklam 

Need to create stickers still. Also is the deck ready to be updated (or is that in June?) and is there example of the photobooth backdrop?

**Comment by natalieworth** [comment]
![Artboard 3](https://user-images.githubusercontent.com/14876567/58121801-1271e400-7bbd-11e9-86d1-5fa38443a055.png)
![Artboard 4](https://user-images.githubusercontent.com/14876567/58121802-1271e400-7bbd-11e9-8438-27fe015097a0.png)

**Comment by kristinashu** [comment]
Wow this is sooo beautiful, I love it! 

I started a folder for the 2019 assets and made a copy of last year's slide deck https://drive.google.com/drive/folders/1MjdlLPe0_QY6HtjBImErRUrDwxlyo5Sc?usp=sharing You should just be able to swap out last year's blue background stuff with your new direction (could even delete some of the similar slides to simplify things).

I'll check with Phia but I'm pretty sure she just needs the color codes for the photobooth.

**Comment by kristinashu** [comment]
@natalieworth Phia and Amanda are happy with the direction so I think you can move ahead with updating the slide deck. She says they'll also need name tags and you can use the same dimensions as last year. We're not totally sure who should approve the stickers so I'll share it with Anil and let him decide!

**Comment by kristinashu** [comment]
Here are the colors we can share with Phia for the photobooth:
Black and White
Red #ff4f5e
Light Blue #b7b9fa
Blue #595cf3
Dark Blue #0d10bf

![colors](https://user-images.githubusercontent.com/1068783/58352157-9f1bdc80-7e1f-11e9-98cc-9987ae6cd313.jpg)

Just need the name tag and then I'll share with Phia and see if we can get all three stickers printed!

**Comment by natalieworth** [comment]
Updated CMS with new slide deck https://foundation.mozilla.org/en/docs/brand/templates/

Sticker has been added to the drive folder:
<img width="537" alt="Screen Shot 2019-05-26 at 12 14 42 PM" src="https://user-images.githubusercontent.com/14876567/58386109-dfaa6000-7faf-11e9-900f-6886e7aea7e9.png">

Just waiting on sticker approval!

**Comment by kristinashu** [comment]
@natalieworth Phia says they'll be using Sticker Mule so please follow their specs. She's wondering what sizes you want? She's meeting with Angela tomorrow and will find out if all of them can be printed or not!

<img width="348" alt="image" src="https://user-images.githubusercontent.com/1068783/58500781-b9173100-8137-11e9-92e7-8a9df7af27ff.png">

**Comment by natalieworth** [comment]
Thanks @kristinashu Just sent an email to phia with the exported template files for Sticker Mule and cc'd you

**Comment by natalieworth** [comment]
@kristinashu Do you know if the sticker gets printed via sticker mule? Or how that is co-ordinated?

**Comment by kristinashu** [comment]
w00t thank you for sending the stickers and specs to Phia! I think this is all done.

We should incorporate some elements from your lovely slide template into our graphics template https://github.com/MozillaFoundation/Design/issues/365!
