### ISSUE TITLE
Content benchmarks

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#366]
Let's get inspired to make some cool stuff! I've started a [benchmarking deck](https://docs.google.com/presentation/d/1002p6cVXgcpSdSnvjMo7AdQsPJdNJVknLFqVRmoDIDc/edit?usp=sharing) for us to gathering the type of stuff we would like to make. @kristinashu @sabrinang @natalieworth @xmatthewx @beccaklam please drop some stuff in. It can be activist-y, internet-y, design-y, or whatever you think is cool and would want to work on.

**Comment by xmatthewx** [comment]
Excellent. Keep an eye out for things that you think will be impactful and do-able. Think about different channels (email, social, web). Consider mostly text/image content, but also great to grab a few not-too-complicated examples of engagement content (like the creep-o-meter).

**Comment by kristinashu** [comment]
@beccaklam did you get any new benchmarks from the session at all hands?

**Comment by kristinashu** [comment]
@natalieworth please add your Insta work with Jen to this deck!

**Comment by xmatthewx** [comment]
Work on the instagram style is here: #389
