### ISSUE TITLE
Design for next misinfo fundraising email

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#367]
design a quick image for use on blog email twitter etc. likely simple words on texture. 

@caltrider - can you provide info?

**Comment by caltrider** [comment]
Just got the questions off to Renee. Should have a draft of the email/blog tomorrow that will give me a better idea for the graphic. The email/blog launch got pushed back to next Thursday, so we have an extra day for this. Still, should be super simple like the last graphic. I'll ping when i have something.

**Comment by caltrider** [comment]
@xmatthewx  I have the text for the graphic! Here's the deal:
Same design as what Natalie did for the last misinfo email/blog/twitter graphic.

Email header text should read:
>Great Information About Misinformation

Blog and Twitter text should read
>Great Information About Misinformation
>Renée DiResta
>Mozilla Fellow on Misinformation 
>Answers Your Questions

Thanks! Let me know if there are any questions or problems or better ideas.

**Comment by xmatthewx** [comment]
@kristinashu can you help figure out who has the bandwidth? It can be text on a texture again like last time ... that'll help audience know it's related to prior message.

**Comment by kristinashu** [comment]
@beccaklam is back so she can do this!

**Comment by beccaklam** [comment]
Got a rough redpen going here: https://redpen.io/p/hwfaa8b1f9f330cd9d <-- Let me know if the dimensions seem right? Copied over from what Natalie did for the last email/blog/twitter graphic. @caltrider

**Comment by beccaklam** [comment]
Final graphics here: https://redpen.io/p/hwfaa8b1f9f330cd9d, approved by @caltrider

**Comment by beccaklam** [comment]
Sent Jen the graphics via slack. Also attaching it here and closing ticket!
[misinfo-fundraising-graphics.zip](https://github.com/MozillaFoundation/Design/files/3248815/misinfo-fundraising-graphics.zip)

**Comment by kristinashu** [comment]
Awesome, thank you!
