### ISSUE TITLE
Evaluate heading link color

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#368]
(Feel free to remove items that are not applicable.)
 
## Updating an existing style
_Please answer the following:_

1. What element/ style is being changed?
Proposing that we update the heading links to be dark blue.

2. Why it is needed?
Currently heading links (on the foundation/ pulse site) don't communicate that they are links until hover. Dark blue color will be more consistent with our small link color and more clearly communicate where links are in headings.

  - [ ] Post proposed brand update in Redpen (for desktop, tablet, mobile)
  - [ ] Request design review from design team via R+/R- in Github ticket
  - [ ] Get feedback from devs

**After Approval:**
  - [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

-----

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by kristinashu** [comment]
I'm going to close this since https://github.com/MozillaFoundation/Design/issues/428 seem to cover it.
