### ISSUE TITLE
Update Social Button Styles on Participate Page

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#369]
## Updating an existing style
_Please answer the following:_

1. What element/ style is being changed?
The circular social buttons on the Participate page (and anywhere else they're used?).
2. Why it is needed?
To provide consistency in button styles across the Foundation site.

  - [x] Post proposed brand update in Redpen (for desktop, tablet, mobile)
  - [x] Request design review from design team via R+/R- in Github ticket
  - [x] Get feedback from devs

**After Approval:**
  - [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by beccaklam** [comment]
Redpen for circular social button update: https://redpen.io/yu391c28dca11c0b31

**Comment by beccaklam** [comment]
Can I get a review @kristinashu? Not sure where else the buttons show up besides the blog.

**Comment by kristinashu** [comment]
R+ buttons look much better in black and white!

**Comment by beccaklam** [comment]
@mmmavis Can I get some feedback on this update?

**Comment by beccaklam** [comment]
Closing this ticket and combining it with this one: #371
