### ISSUE TITLE
Github Labels for design & build handshake

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#37]
@xmatthewx mentioned something today about our issue labels reflecting where we are at in the design process. Let's document what that looks like.

**Comment by xmatthewx** [comment]
- `needs design`
 - `design`
  - `needs design review`
   - `in design review`
  - `needs tech review`
   - `in tech review`
 - `PR needs design review`

Tech reviews will help us catch a pile of problems for better designs and better builds, particularly with responsive views and interaction design.  

cc: @vazquez @flukeout @k88hudson @sabrinang @gvn @simonwex

**Comment by xmatthewx** [comment]
- `help wanted`
 - `good first design issue`

**Comment by vazquez** [comment]
- **`help wanted`** Any designer can take this issue!

 - **`good first design issue`** is applied to an issue that is identified as being suitable for a contributor.

 - **`needs design`** is applied to an issue that hasn't yet been triaged by a design team member. The issue could lead to more issues being filed, as the design team member sees fit.  

 - **`design`** is applied to an issue that has an Assignee and is being worked on.  

   - **`needs design review`** is applied when a design team member has iterations for considerations. The team member will assign another team member the issue.  

   - **`in design review`** This label is applied while the review round is occurring.  

   - **`needs tech review`** Tech reviews will help us catch a pile of problems for better designs and better builds, particularly with responsive views and interaction design.  

   - **`in tech review`**  This label is applied when a developer takes over tech review.

 - **`PR needs design review`** This label is applied when a developer is finished with their PR and has front-end heavy code. In such case, a designer will review their PR for design quality.

**Comment by vazquez** [comment]
Closing this issue and filing new bugs as needed. :earth_africa:

**Comment by xmatthewx** [comment]
i added some of these labels to webmaker-core. probably would be good to add them to thimble, teach, advocacy repos.
