### ISSUE TITLE
Cleaning up Button Styles

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#371]
## Introducing a new style
Related ticket:  #339

1. What element/ style is being changed?
We are fleshing out our button styles and defining:
- Disabled button style
![Dsiabled Button Style@2x](https://user-images.githubusercontent.com/20977376/59202510-a276ce00-8b6a-11e9-8bd0-57a5c6bb83c0.jpg)

- Grouped button style
![Grouped Button Style](https://user-images.githubusercontent.com/20977376/59126995-75d97100-8934-11e9-809c-9d1a134c0785.jpg)

This update will affect the post-sign share on campaigns:
![campaign post sign share@2x](https://user-images.githubusercontent.com/20977376/59132425-28b0cb80-8943-11e9-80c8-2485885f07f3.jpg)

- Inline icon button style
![Inline Icon Button Style](https://user-images.githubusercontent.com/20977376/59127011-7a9e2500-8934-11e9-92c0-b2c17f112fdf.jpg)

- Circular Social Buttons
![Circular Social Buttons@2x](https://user-images.githubusercontent.com/20977376/59130555-c0132000-893d-11e9-9d1a-696d8d8699e7.jpg)

This change will affect the Participate page:
![participate@2x](https://user-images.githubusercontent.com/20977376/59132443-349c8d80-8943-11e9-8864-84a1f6eb5655.jpg)

Redpen link here: https://redpen.io/p/knefb82f90a4716342

2. Why it is needed?
So we know what our brand standard is when we need to implement these buttons

  - [x] Post proposed brand update in Redpen (for desktop, tablet, mobile)
  - [x] Request design review from design team via R+/R- in Github ticket
  - [ ] Get feedback from devs

**After Approval**
  - [x] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [x] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [x] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [x] Create a dev implementation ticket (following the design to dev hand-off outline)

**Implementation Tickets**
Circular Buttons Dev Ticket Started here: 

## Design Reviewer Checklist
_An issue template in github_
**For design review:**
  - [x] Is this change justified or are we able to use existing brand elements?
  - [x] Is the development time viable?
  - [x] Provide an R+ or R- in the ticket
  - [x] List reasons for approving or denying changes

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by beccaklam** [comment]
Ah, did it wrong again. Need to open up dev tickets ...

**Comment by beccaklam** [comment]
@kristinashu @sabrinang Can I get an R+?

**Comment by kristinashu** [comment]
@beccaklam can you please link to comps?

**Comment by beccaklam** [comment]
Oh weird I thought I did that but I guess my changes weren't saved ... anyway updated now!

**Comment by kristinashu** [comment]
Thanks! Buttons look good but I've added a few comments in redpen to add more context for devs. 

Should the round social buttons also be included here? I think those would be used on the blog and in Nat's new pulse entry design https://redpen.io/zw3d9fad50ec628d2b.

**Comment by kristinashu** [comment]
I've opened a separate ticket to determine rules around adding an external link icon https://github.com/MozillaFoundation/Design/issues/372

**Comment by sabrinang** [comment]
round social icons could also be updated on participate:
![image](https://user-images.githubusercontent.com/2492510/59129917-f0999080-8922-11e9-8e55-e05420fafc0c.png)

**Comment by beccaklam** [comment]
@kristinashu and @sabrinang Added affected pages in the initial comment ☝️

**Comment by kristinashu** [comment]
R+ 🎉

**Comment by beccaklam** [comment]
@mmmavis Can I get some feedback on these button updates, please? 😄

**Comment by beccaklam** [comment]
@kristinashu updated disabled button styles to include inverse buttons

**Comment by beccaklam** [comment]
☝️ All Implementation tickets have been opened! Closing this ticket!

**Comment by mmmavis** [comment]
Sorry I'm late to this. Design looks good!

Two questions that's sorta implementation related

1. do these four buttons always come as a set?
2. do we need a "copied" state for the link icon? (see PNI example)
![PNI-buttons](https://user-images.githubusercontent.com/2896608/59391956-ce40b200-8d2a-11e9-90b5-d9d7691416fd.gif)

**Comment by beccaklam** [comment]
@mmmavis oh that's a good point, will mock that up!

**Comment by beccaklam** [comment]
@kristinashu @sabrinang @mmmavis What do you think of this for the copied link button? Changed the link button to a check mark so there's some further feedback for the user:
![social-buttons](https://user-images.githubusercontent.com/20977376/59453424-ddcd0300-8ddd-11e9-891a-521a6aa220da.jpg)

**Comment by kristinashu** [comment]
Oooh I love it! So simple.

**Comment by beccaklam** [comment]
Also, circular social buttons: 
![circular-social-buttons](https://user-images.githubusercontent.com/20977376/59519715-7757eb80-8e96-11e9-8023-073cfe7bd112.jpg)
@kristinashu @sabrinang @mmmavis 

I've updated the implementation ticket so I'm closing this one again :)
