### ISSUE TITLE
Determine when to use external link icon

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#372]
Which buttons and links should have the external link icon? Right now the rules are inconsistent. 

Example: 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1068783/59128198-25571900-891e-11e9-9bcb-6f651a70f540.png">

A few locations to consider:
- sub nav items like on /about
- main nav item like Donate
- primary button
- secondary button
- in body link
- link with arrow icon

**Comment by xmatthewx** [comment]
Good topic. I think we can be conservative and use them sparingly. A few opinions: 

When to probably _not_ include an arrow: 
 - **buttons** - buttons naturally signal that something special is gonna happen. it's not surprising when a new window pops open. i'd avoid arrows in them. 
 - **link to our core platforms** - now that we have UIs alignment (ihr, pni, soon pulse), we can consider these platforms local, and i don't think links there need the arrow. 
 - **context signals exit** - if context signals exit, we don't need the icon. e.g. links in a blog, or a list of resources, or news features that identity an external source.

**Comment by kristinashu** [comment]
Closing this ticket since it is very old and out of date.
