### ISSUE TITLE
Update and create evergreen Foundation illustration style

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#376]
Based on our brand meetings before All Hands, we want to align and explore the illustration style that Mozilla Foundation is currently using. From the brand deck, the key elements that we liked were: strong use of colour, texture, and the simplified vector designs. These illustrations will set the tone for our branding and also be an evergreen version that can differ from a campaign, one-off/ individual page graphics, and other unique styles. Areas, where we may use these evergreen styles, include the Initiatives page, email, Becca's donation page work, etc.

cc: @kristinashu @sabrinang @natalieworth @xmatthewx @taisdesouzalessa @beccaklam

**Comment by natalieworth** [comment]
Most recent iterations for this are in here: https://redpen.io/vz8402feacd3249e95

**Comment by natalieworth** [comment]
I have updated the Initiatives page with the new header and added illustrations. Going to get final design review tomorrow and then will close this ticket.

**Comment by natalieworth** [comment]
https://foundation.mozilla.org/en/initiatives/

**Comment by kristinashu** [comment]
Beautiful!!!
