### ISSUE TITLE
Write a value prop

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#377]
### Goal
To grow our audience we need an engaging and captivating sentence on our site to better onboard users on who we are, what we do, and why they should care.

[Notes](https://docs.google.com/document/d/1txC3guawnjoeXUvFbFABhR32kPNDtx2O0MKGP8OzTJs/edit#heading=h.5ytjhhc3jl0q) from meeting with Juan.

### Audience
We should be aware of two types of audience -- those who know our cause or are internet-savvy and those who don't know us or are not internet-savvy

### Plan of attack
@caltrider could we please talk about this at our next content strategy meeting, then write up a brief, and jam on a bunch of ideas? Then we can choose the top few to share with a limited internal audience and do some external user testing on them to choose one.

### Examples
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1068783/60687677-f1134180-9e64-11e9-9737-e6677b7d0147.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1068783/60687640-9aa60300-9e64-11e9-9d74-cf7cc64daecb.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1068783/60687646-aabde280-9e64-11e9-9ed9-845a7a99560b.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/1068783/60687650-b4474a80-9e64-11e9-86f9-90385f9a703a.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1068783/60687663-c45f2a00-9e64-11e9-808b-95b720b7795c.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/1068783/60687671-d3de7300-9e64-11e9-847c-fa306f22afef.png">

### Comp of how it could look on our site

https://redpen.io/qr7e80679a5c55f97f

![image](https://user-images.githubusercontent.com/1068783/60687744-5a935000-9e65-11e9-9d1f-4140f4a80878.png)

Related to https://github.com/mozilla/foundation.mozilla.org/issues/3142

cc @anilkanji

**Comment by anilkanji** [comment]
Thanks @kristinashu - @caltrider I can provide wider context at our next Content meeting - this will live on our site but connects to a case for support paragraph that Juan is preparing, and t- the why (and where this came from) at our next Content meeting.

**Comment by kristinashu** [comment]
cc @Sydette

**Comment by kristinashu** [comment]
Notes from our content meeting:
- @anilkanji needs to write a Jen style project brief (should include Goal, Audience, Emotion)
- Then we will generate a bunch of ideas and then narrow it down
  - Jen has already suggested "Your friend in the tech industry"

**Comment by kristinashu** [comment]
Reviving this!

Old comps and benchmarks are [here](https://redpen.io/p/fm1aa86db66594fc47) and IA benchmarks are [here](https://redpen.io/p/hf62c1a6c9ba6c5262).

Anil will be write something and share it with Lotta.

**Comment by kristinashu** [comment]
Closing this! This work can be done as part of the bigger ticket - IA: gather website content #4458

cc @taisdesouzalessa since there are a few homepage benchmarks [here](https://redpen.io/p/fm1aa86db66594fc47).
