### ISSUE TITLE
Onboarding slides - deadline July 24

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#381]
MoFo needs to update our slides for the MoCo/MoFo onboarding. It's our chance to really sell the work of the Foundation to new staff coming in, so it needs to be super compelling.

The presentation is July 29 so we will need to be ready several days before then and submitted to the moco onboarding team. Lotta is working on content and I will add the updated link as soon as she is done. Angela will most likely want to make some edits next week.

Existing deck at: https://docs.google.com/presentation/d/1QG3P2xSUEgQU04zv9yFllV42vAelwz5qB6Tk8kzJit8/edit#slide=id.g523fc24f60_0_0

Link to board slide template: https://docs.google.com/presentation/d/1mK5gZthu0zsbI3ZyLQj9qVdoCSf-tKKwFrMy3YpcVw0/edit?usp=sharing (aren't allowed to see the final presentation)

Link to All Hands slides: https://docs.google.com/presentation/d/1VZ3qx4SaWOrMkwQtt2XmlsYle-j1df-onStaGfiupSo/edit#slide=id.g586441deca_0_0

Ticket to make All Hands slide reusable #384

**Comment by kristinashu** [comment]
@beccaklam Lotta says she is updating the slides [here](https://docs.google.com/presentation/d/1LIcEz6FgiuhDn-IgnPUxa275DohlvYHnd9aTOsOiA00/edit?usp=sharing). Just ping her before you start working on it to see where it's at.

**Comment by beccaklam** [comment]
This is mostly done, just waiting for Lotta to show Angela and to see if she needs any changes! @kristinashu

**Comment by kristinashu** [comment]
Awesome!

**Comment by beccaklam** [comment]
This is done unless Lotta comes back with feedback from Angela.
