### ISSUE TITLE
MozFest Anniversary Book: Writing on Design Contribution/Culture - Deadline July 31

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#382]
### Intro
Write a piece for the 10th Anniversary Mozilla Festival book about the contributions of design at the festival and it's impact on culture and community. 

### Reference Links
Book objective and outline: https://docs.google.com/document/d/1ANxMXAFH9UoQbYn1V7KGH6Ey6s8IDocNKc_cjrPNRhY/edit?usp=sharing

cc: @kristinashu @xmatthewx

**Comment by xmatthewx** [comment]
As I believe I mentioned, I'd like us to start with an outline of rough summary of the piece before we jump fulling into writing. Glad to help or stay out of the way.

**Comment by sabrinang** [comment]
We can use google doc for the outline, please put whatever ideas/summary/writing you have here @xmatthewx, any help is appreciated :) https://docs.google.com/document/d/1LUKH6ySbrK_lGxQM1SlDFvwKkuJCphpJ3mJeQ15WybQ/edit?usp=sharing

**Comment by edrushka** [comment]
Oh haaaai @sabrinang @xmatthewx @kristinashu 👋 Look who's checking out your tickets!!

I've just started helping Sarah & Kristina G with the book project. I'll be spending the next couple weeks helping wrangle copy. Would you be so kind as to give me access to your GDoc?

**Comment by xmatthewx** [comment]
AHHHH. What is happening! Hello stranger!

**Comment by edrushka** [comment]
Hey MW! I'm sneaking back into the fold in all sorts of different ways these days. Having a great time so far working on the MozFest book (I'm just around for couple weeks helping to polish up the copy).

**Comment by xmatthewx** [comment]
@edrushka - yay. also, do you have mozilla email? or slack? i sent you a message on skype. please connect with @sabrinang to catch up on her piece. thanks!!

**Comment by sabrinang** [comment]
@xmatthewx I revised my writing https://docs.google.com/document/d/1LUKH6ySbrK_lGxQM1SlDFvwKkuJCphpJ3mJeQ15WybQ/edit?usp=sharing
@edrushka I shared the gdoc with you and I was so delightfully surprised to see your comment! YAY 🙌 

I'd love any feedback and help with the content or writing. I've revised it this weekend and would appreciate some eyes on it to know if I'm on the right track. Feel free to leave comments or suggestions directly in the doc!

**Comment by edrushka** [comment]
Hey @sabrinang We loved this piece! Kristina may get in touch with some minor edits (if she has any) and we might remove the bolding just to keep consistent with the other contributions, but overall it looks great. Nice job!!

**Comment by sabrinang** [comment]
I made some suggestions to the doc based on some feedback from @xmatthewx. I split up some run-on sentences and removed excessive phrases to make sentences easier to digest. I also unbolded the text.

@KGorr and @Saallen I shared editing access with you. Feel free to amend sentences so they flow better with the book.

**Comment by sabrinang** [comment]
@KGorr Did you also want photos at this point? Sorry, I just caught the email where you mentioned about pulling photos but the ones in the doc don't exactly correspond with the sections as I collected them before I wrote a draft. I can collect imagery that corresponds with the writing if you need that too (if there are specific image specs let me know).

**Comment by KGorr** [comment]
@sabrinang Thank you! You did such a wonderful job. I made some suggested edits for clarity and have left some comments for your consideration too. We are hoping to have all content finalized this week so we can send to our designers. Are you able to fit in work on this today/tomorrow? 

And yes, photos would be amazing that help tell your story! No specific image specs at the moment.

**Comment by sabrinang** [comment]
Writing has been reviewed (in legal/design phase now). Images gathered for designer to use if they need any here (mix of images from 2016-2019): https://drive.google.com/drive/folders/1SjzktV22tkOG7Ct4T3yW7VwzF5Jc19L0?usp=sharing
