### ISSUE TITLE
Make the All Hands slide graphic reusable 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#384]
From the master style guide ticket https://github.com/MozillaFoundation/Design/issues/373. @natalieworth please turn your lovely All Hands slide into something reusable/remixable so we can use for other slides and even for social graphics.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1068783/61420166-2c2a6180-a8b6-11e9-9697-3663eaf839bc.png">

**Comment by natalieworth** [comment]
Didn't have time to get to this this week, but can do definitely for next sprint @kristinashu @gideonthomas

**Comment by xmatthewx** [comment]
Is there definitely a use case for this? The slide feels like a playful spin on the brand style, but not super applicable to campaign stuff or even other slide decks.

**Comment by kristinashu** [comment]
Definite as in right now, no. But as part of our [benchmarking and audit](https://github.com/MozillaFoundation/Design/issues/373) we decided this would be a great reusable and easily remixable creative direction for when we need a quick generic mofo graphic for social or a blog post (for things like Fellowship proposals, Creative Media award announcement, quick petition page...). You can see more in the [master slide deck.](https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit)

I had put this into this sprint to be used for the on-boarding slides but I don't think it will be ready in time and since YouTube work has ramped up, I will take this out of this sprint.

**Comment by natalieworth** [comment]
I've been working slowly on a general slide deck that could be used [across foundation here](https://docs.google.com/presentation/d/1OQBWkDqf4U5kzarklz1O2Pcb1TLjlzupphldJRfAu-g/edit#slide=id.g25275a8168_0_260). It's not in an official moz theme yet. We could review at the next design huddle/ design meeting and once R+'d I can add it to our [templates](https://foundation.mozilla.org/en/docs/brand/templates/)

**Comment by kristinashu** [comment]
cc @taisdesouzalessa @sabrinang

**Comment by kristinashu** [comment]
This feels sooo close to being done! @sabrinang do you think we can just replace the All Hands slide on [the templates link](https://foundation.mozilla.org/en/docs/brand/templates/) with the [more general one](https://docs.google.com/presentation/d/1OQBWkDqf4U5kzarklz1O2Pcb1TLjlzupphldJRfAu-g/edit#slide=id.g25275a8168_0_260) and then call this done? Might just need to add a sentence about when to use the boring moco version vs our fun one.

**Comment by natalieworth** [comment]
I organized and named all the files in layout. I tried to organize them from:
1) Main/ large titles (with mozilla logo)
2) Title introductions (with/ without mozilla logos)
3) Agenda
4) Content type slides

https://docs.google.com/presentation/d/1OQBWkDqf4U5kzarklz1O2Pcb1TLjlzupphldJRfAu-g/edit?usp=sharing

cc @sabrinang

**Comment by natalieworth** [comment]
Going to leave this in 'review/qa' until Sabrina's back to do brand review and R+.

**Comment by sabrinang** [comment]
Thanks for organizing the slides Nat, some feedback notes:

- for type, consider using Nunito Sans instead of Open Sans

- blue angle version of the red ones (20, 21, 27)
<img width="297" alt="image" src="https://user-images.githubusercontent.com/2492510/86401430-0e891000-bc5f-11ea-8e98-d59321fbfce1.png">

- light version of agenda 
<img width="134" alt="image" src="https://user-images.githubusercontent.com/2492510/86401776-a38c0900-bc5f-11ea-9db7-dc377451ec95.png">

- centred blue slide to be gradient to match the red version  (doesn’t need the blobs to simplify)
<img width="268" alt="image" src="https://user-images.githubusercontent.com/2492510/86401585-57d95f80-bc5f-11ea-9c77-15182c0689e5.png">

**Comment by natalieworth** [comment]
Updated this based on Sab's final comments and closing :)

[Final file is here.](https://docs.google.com/presentation/d/1OQBWkDqf4U5kzarklz1O2Pcb1TLjlzupphldJRfAu-g/edit?usp=sharing)
