### ISSUE TITLE
Create 2 Participate illustrations for Foundation Site

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#386]
### Intro
Create the 2 illustrations for the [participate](https://foundation.mozilla.org/en/participate/) call outs (social media/ donate) based on the illustration styles created for [initiatives](https://foundation.mozilla.org/en/initiatives/). 

cc: @kristinashu @gideonthomas

**Comment by kristinashu** [comment]
Participate page might not be around for much longer... gonna close this ticket since it doesn't seem worth it to invest more in it.
