### ISSUE TITLE
Document MoFo brand

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#388]
From epic ticket #373

- [ ] Add minimal documentation in [brand deck here](https://docs.google.com/presentation/d/1oMRxQ2NZiebhMnwGkDJQPC6-iD8xYqBeopJhO3uEBT4/edit#slide=id.g1ea5ab4fd9_0_139) 
- [ ] Add file and screen caps to [wagtail page](https://foundation.mozilla.org/en/docs/brand/design/)
- [ ] Compile and organize master file and [folder](https://drive.google.com/drive/folders/1FsYaAToeHrueI4kQvqYwNHSnm8idrgh1?usp=sharing)

**Comment by xmatthewx** [comment]
> Add minimal documentation in brand deck here

Will we maintain documentation in both a deck and docs on the site? Is one easier or better than the other?

**Comment by kristinashu** [comment]
Closing this since work is represented in other tickets.
