### ISSUE TITLE
Defining our instagram style and post types

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#389]
Based on [benchmarks](https://docs.google.com/presentation/d/1jUWU5j7yR2JWt0ZnVgLg4J5pbw0i9V9awEADgdH8wHQ/edit#slide=id.p) and [doc](https://docs.google.com/document/d/1bPNKLDEivv6YZv_o32964bfd9RhoAzz2ikGA4TA2tTU/edit), put together a visual style/ story boards for potential instagram posts.

### Links
[Redpen for visual style is here.](https://redpen.io/p/rvfdd4560c2fb38b57)

cc: @kristinashu @sabrinang @natalieworth @xmatthewx @beccaklam @gideonthomas

**Comment by kristinashu** [comment]
Combining Instagram related tickets into one https://github.com/MozillaFoundation/Design/issues/453.
