### ISSUE TITLE
Document our Design Principles

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#39]
We made some good headway on defining what values and principles we want embodied in our design process and experiences we design.

**Strategic**
* How can our work meet the goals of mozilla and open up new opportunities

**Ambitious**
* We are willing to tackle hard problems and come up with unexpected solutions

**Meaningful & Effective**
* Users will care about using our products and it’ll have impact on their lives

**Empathetic**
* Our users are never going to get stuck

**Holistic**
* We design systems & experiences with integrated perspectives & disciplines with a view to the big picture 

**Delight & Playful**
* Users will experience joy when visiting our stuff, more memorable, building community
* Using our products is low risk, our users won't make drastic mistakes or accidental actions that they can't recover from
* We provide a safe space to play and experiment

**Craft**
* We approach our work with skill, efficiency & pride, & will share these skills with our community

**Expressive & Flexible**
* Our tools are flexible enough to allow our users to express themselves in varied and personal ways

**Comment by cassiemc** [comment]
Related: the [Firefox design values](https://blog.mozilla.org/ux/2014/04/firefox-design-values/) linked from issue #1 I'll copy and paste them here:

![ff-design-values](https://cloud.githubusercontent.com/assets/1186326/8573949/43a5eba8-2562-11e5-905c-8cf11c037344.png)

**Takes care of you** – Firefox champions you – your security, privacy, and the quality of your online life.

**You help make it** – Firefox is only a perfect fit once it’s in your hands and can make it your own.

**Plays well with others** – Firefox never locks you into particular services or providers; instead, it gives you choice and independence, along with great suggestions.

**Exuberant** – Firefox is human, fun, whimsical, and joyful.

**Global** – There’s a real diversity of use and need across the globe, and Firefox cares about these differences.

**Finely Crafted** – Firefox is made by people who care about the details.

**Balances power and simplicity** – Firefox will never overwhelm you with interface, but it will also give you the satisfaction of using the web with mastery.

**Makes sense of the web** – Firefox focuses on real human goals and activities and gives you the tools you need to accomplish your ends.

**High user-performance** – Firefox is viscerally responsive; highly tuned and eager to browse.

-------

This is worth a look before design crit today @flukeout @sabrinang @xmatthewx @lovegushwa (and @vazquez when you get a chance).
* Short description: https://blog.mozilla.org/ux/2014/04/firefox-design-values/
* Long description: http://people.mozilla.org/~madhava/FDV/
* [PDF download] (http://people.mozilla.org/~madhava/FDV/FirefoxDesignValuesBooklet.pdf)

**Comment by xmatthewx** [comment]
It'd be nice to include a few of these and maybe visually extend this. These resonate: You help make it, Finely crafted, Global, Makes sense of the web. The phrasing on some of this is a bit awkward.

**Comment by lovegushwa** [comment]
When I met Tim Murray at Whistler he said the marketing team was working on a list of brand attributes. The way he expressed it, it's something similar to  Firefox design values. External facing attributes that are flexed depending on the intended communication (you don't need to express all the attributes, all the time.)

It would be great to see what they come up with (Cassie do you want to reach out to Tim, or should I?)
Also I think we could / should develop two different lists:

1. Our studio/design values: the values that keep us all on the same page, moving towards the same goal.

2. Our brand attributes: The external facing qualities of our brand we communicate through products and design.

**Comment by cassiemc** [comment]
We punted on discussing this as a group to this Wednesday so all team members could be present. @lovegushwa it'd be great if you could reach out to Tim, and I'd love to be included. Thanks!

I'm torn on separating this into two value sets though. The one I'd most like to focus on is the first of your groups. The brand attributes for all the other products should come from there / relate once we have reached consensus on the first set.

**Comment by cassiemc** [comment]
We didn't get a chance to do this last week because of our guest critiquer. Will plan on it for July 29.

**Comment by xmatthewx** [comment]
nice approach: https://fundraising.mozilla.org/fundraising-team-charter/

**Comment by cassiemc** [comment]
Agreed regarding the fundraising charter! Also had a nice chat today with Tim Murray about how when he was at Target the team identified four main principles which were: 

* joyful
* authentic
* suprising
* designed

And then these four could be applied to different projects in varied proportions depending on the objective and the audience, i.e. credit card payment system should be more authentic than surprising. For kids, joyful and surprising were dialled up. They became a flexible tool that allowed consistency as a brand.

**Comment by cassiemc** [comment]
Tim also suggested 'view source' as a design principle. Maybe that means being able to find out who made it, grab the design, use it themselves – we'd need to dig a little deeper into that one to figure out how to apply it.

**Comment by cassiemc** [comment]
To be clear, this bug is just about documenting the conversation that we will have on July 29 in a place that can be linked to from build.webmaker.org/design. We can iterate on its presentation later. cc @lovegushwa

**Comment by cassiemc** [comment]
This has been pushed to the backburner. Will update the milestone.

**Comment by cassiemc** [comment]
This seems like a good way to kick off the new year. Moving to Jan 15.

**Comment by cassiemc** [comment]
We're going to wrap this up on Wed Jan 6 during our weekly critique call.

**Comment by lovegushwa** [comment]
New doc of principals. Some benchmarking happening around visualizing external principals that's rolling into separate tickets. Going to close this now:

https://docs.google.com/a/mozilla.com/document/d/1a5H9cmUFbPyiOu7Bp5GGlmG7cl6LJIFQSUJugG6Hj1U/edit?usp=sharing
