### ISSUE TITLE
Refresh major gift gdoc

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#391]
### Intro

 - **Problem**: we need to raise bucks to achieve our mission
 - **Solution**: update fundraising 2-page google doc
 - **Audience**: Prospective major gift donors
 - **Proposed due date**: August 9
 - Current doc: [Leadership Giving Program](https://docs.google.com/document/d/1DTgg1X1AIrfW5lQgiyr-uqSzlbMVvODVzfon4PvKSac/edit)

Jesse W says: 

> I'm hoping for a design update the print version of the Leadership Giving (major gifts) program description to assist with fundraising. I don't think the current layout/formatting is particularly good at grabbing the attention of donors nor does it matches with the web based version (https://foundation.mozilla.org/en/initiatives/leadershipgiving/). If there is something you could do to make this snazzier, it would be super helpful.

cc: @kristinashu @sabrinang @natalieworth @beccaklam

**Comment by xmatthewx** [comment]
@sabrinang let's discuss when you have a moment

**Comment by xmatthewx** [comment]
Adding @beccaklam in case she has more bandwidth to triage or do this.

**Comment by sabrinang** [comment]
Print design version of Leadership Giving google doc here: https://docs.google.com/document/d/1rBx9FL_wgnFuLXhSPdXA-OhHNIw4QPbIqy5DeKZdBs8/edit?usp=sharing

I used Mozilla gdoc template, used illustration/brand assets for header image and coloured the web graphics/tables with brand colours:
<img width="400" alt="Screen Shot 2019-08-06 at 6 38 37 PM" src="https://user-images.githubusercontent.com/2492510/62588146-8ac17a80-b879-11e9-8312-a16c5e7c7f4b.png">
<img width="400" alt="Screen Shot 2019-08-06 at 6 39 01 PM" src="https://user-images.githubusercontent.com/2492510/62588147-8ac17a80-b879-11e9-841c-cca6e471eacc.png">

@xmatthewx Let me know if you have any feedback or if Jesse W has any feedback.

**Comment by beccaklam** [comment]
@xmatthewx looks like Sabs has a handle on this ☝️ so I'm going to focus on other things at the moment. Let me know if the need changes and there's work for me to do here.

**Comment by xmatthewx** [comment]
This looks amazing! We'll have to see if he's keen to keep it down to 2 pages. Not sure if he shares as PDF or 2-sided print thing. I'll start a thread.

**Comment by xmatthewx** [comment]
Let's see what he says before you do more work. But if we do need to squeeze into 2 pages, you might try tables width going into the margins, maybe to match the dots up top.

**Comment by jessedward** [comment]
This looks great! Two pages would be preferable if that is possible. I could try to shave some text off as well if that would be helpful.

**Comment by sabrinang** [comment]
@xmatthewx @jessedward I decreased the font sizes a bit and removed the images (couldn't fit them on 2 pages). New 2 page google gdoc here: https://docs.google.com/document/d/1Wjx02zhyTb_sUj42R5VGfKtItfrFVUMTkacBrFKUIVE/edit?usp=sharing

**Comment by jessedward** [comment]
This looks great! Thank you! Sorry, if this creates more work, but anyway I could have this 2 page version and the previous 3 page version as well? The design elements with the pictures did look really nice. The two-pager is great when I need to print, but if I am sending as a PDF for some reason the 3 page version would probably be better.

**Comment by sabrinang** [comment]
@jessedward Yes whatever works for you as they are both separate links/docs (I left the 3 page one unchanged) so you can use them however you wish!

Same links:
3 page version: https://docs.google.com/document/d/1rBx9FL_wgnFuLXhSPdXA-OhHNIw4QPbIqy5DeKZdBs8/edit?usp=sharing
2 page version: https://docs.google.com/document/d/1Wjx02zhyTb_sUj42R5VGfKtItfrFVUMTkacBrFKUIVE/edit?usp=sharing

If you have everything you need, feel free to close this issue or if there is anything else for this let me know.

**Comment by jessedward** [comment]
This looks great. Thank you!

**Comment by jessedward** [comment]
Let me know if there is something I'm suppose to do on this page to close this out (not seeing anything, but first time using github).

**Comment by xmatthewx** [comment]
Thanks! I'll close this now. Let us know if you get any feedback from donors!
