### ISSUE TITLE
Mock YouTube Generator Ideas

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#392]
Flesh out and wireframe 2-3  ideas for the mock YouTube generator that highlights the opaque nature of YouTube's algorithm. Starting ideas outlined in the gdoc linked below. See these ideas as starting points, and feel free to go wide with ideas before contracting down due to feasibility.

**Key things to note:** Try to keep it simple, like a one-liner. Doesn't need to reflect the algorithm's complexity, just that it sends people down a rabbit hole to unexpected places. But keep in mind it may need to be punchy enough to capture the press. 

**Tone:** Humorous 

**Audience:** _(This is kinda vague, but do your best. Maybe even define who you think this would be impactful to reach as 'new users!')_
Primary: New users (who are YT users)
Secondary: Press who can help direct to new users
Third: Our existing audiences

**Goals:**
- A light and funny way to show the problems of YouTube’s algorithm 
- To garner press coverage
- Engage new audiences 

_Through line goal_: Drive people to put pressure on YouTube

**Current ideas:** (refer to the section the link opens in the doc, section ends before "Step #3: Education") https://docs.google.com/document/d/1c_y4r35YI2zGAw0g4h6Y9ijgkkuNwbbPuRCc8ihXZKg/edit#bookmark=id.sfj1soaetvgi

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by gideonthomas** [comment]
@beccaklam there's feedback in the doc now so once designers settle on an idea, can you either file a new ticket or morph this ticket into a wireframing/sketching one and add it to the Aug 19 milestone please?

**Comment by beccaklam** [comment]
@sabrinang @natalieworth I think most of the feedback/excitement right now is centered around the comments on "6 degrees of Kevin Bacon" so perhaps try fleshing that one out plus 1-2 other ideas you may have?

**Comment by beccaklam** [comment]
An article from Brandi that talks about how the YT algorithm works: https://blog.hootsuite.com/how-the-youtube-algorithm-works/ Might be helpful? @sabrinang @natalieworth

**Comment by xmatthewx** [comment]
Oohh cool. Thanks @beccaklam! Use for inspiration @sabrinang @natalieworth if you want, but don't worry about a) needing to convey this or b) needing our thing to be technical accurate. It's most import that we capture people's attention and pull them in to take action and learn more.

**Comment by beccaklam** [comment]
Sabrina has come up with two great ideas we will show at a feedback meeting tomorrow!
https://docs.google.com/presentation/d/1qEhEMWi46UD2uPZeLUM9qY5gKmNh1K12MwZmPP8paEU/edit?usp=sharing
