### ISSUE TITLE
Creative Collaboration MVP

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#393]
I've drafted a deck to articulate the process for other teams to work with design on larger public campaigns. 
 - The goal: Create time for creative to guide decisions; Reduce confusion; Increase productivity of group meetings; Zap stifling video+gdoc brainstorms.   
 - The audience: Anil, Jen, Ashley, Juan, and other collaborators 

Steps:
 1. @kristinashu @sabrinang @natalieworth @beccaklam to revise and improve the [draft deck](https://docs.google.com/presentation/d/1Gx_iWfDGT9QMJSrrcSJCpx-5-G_D9Yq4-9JWWq1xwwg/edit). Change my suggestions. Keep it simple. Brevity is important for our audience.  
 2. Matthew to review with Anil, Jen, Gideon
 3. Revise
 4. Anil/Matthew to share with other teams

**Comment by kristinashu** [comment]
Ok we have not made much progress on this but here we go! @sabrinang @beccaklam and I will meet on Monday to brainstorm a short MVP list of content we would like to include on a Wagtail page.

Here's the working doc for the meeting and our plan https://docs.google.com/document/d/1K0KaFU_-0Mi49RZW_mGCLY9UPOGWc68Pg-TfFZm_sNY/edit?usp=sharing

**Comment by kristinashu** [comment]
Okay okay okay we're getting there! 
- Anil is going to do one more pass of the copy
- Natalie has made a lovely graphic here for the page and the OG image: [files are here] 
![image](https://user-images.githubusercontent.com/1068783/76916245-1c1bb500-687d-11ea-8484-9b42d4ef936e.png)

- @gideonthomas I don't seem to have permissions to add a new page in docs. Do you? Could you please either give me permission or create a page called "process" directly under docs? <img width="709" alt="image" src="https://user-images.githubusercontent.com/1068783/76916063-91d35100-687c-11ea-8b71-2e1918b3c770.png">

- THEN I will add all the copy and we'll share it out!!!

**Comment by gideonthomas** [comment]
@kristinashu I gave you a bunch of permissions. Hope that works.

**Comment by kristinashu** [comment]
Thank you @gideonthomas! It works now.

**Comment by kristinashu** [comment]
I've added the content to wagtail https://foundation.mozilla.org/docs/process/ but I think it needs some more sprucing up!

**Comment by sabrinang** [comment]
note: related to meta-ticket for /docs content #515

**Comment by kristinashu** [comment]
Soooo close https://foundation.mozilla.org/docs/process/. Anil will be sharing this with the directors and then all staff later this week.

**Comment by kristinashu** [comment]
All mofo-email send! Thank you all for helping with this. Already getting some nice comments back.  

<img width="749" alt="image" src="https://user-images.githubusercontent.com/1068783/81439558-673aa180-9123-11ea-8501-180fd92b646d.png">
