### ISSUE TITLE
Infographic for Voice Assistants

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#394]
The Advocacy team has asked us to come up with an infographic that highlights which voice assistants listen to voice recordings, what users' opt-out options are, and what each company is doing in light of users being concerned about these voice recordings. Copy needs to be pared down.

**Due Date:** Monday, August 11
**Content:** https://docs.google.com/document/d/1vckyBUBfePDL9YP_vvzX_M3eYoKoVeZWWAFz9qdQtnQ/edit?usp=sharing

cc: @kristinashu @sabrinang @natalieworth @xmatthewx @taisdesouzalessa @beccaklam

**Comment by beccaklam** [comment]
First draft sent to stakeholders: https://redpen.io/p/ny1532827ff26fd1ef

**Comment by beccaklam** [comment]
Made edits and posted in redpen above. Kaili is circulating the graphics now, this is basically done unless they ask for edits!

**Comment by gideonthomas** [comment]
waiting for l10n

**Comment by beccaklam** [comment]
EN graphics are finished here: 
[Final.zip](https://github.com/MozillaFoundation/Design/files/3506338/Final.zip)

Will close this ticket once I'm done making the French and German graphics.

**Comment by kristinashu** [comment]
@beccaklam have you done these translations? I was looking at https://foundation.mozilla.org/en/campaigns/how-opt-out-human-review-your-voice-assistant-recordings and the graphics look awesome but I find the font size a little small (even on desktop). When you do the translations, if you haven't done them yet, could you make the type a little bigger?

**Comment by beccaklam** [comment]
Updated font sizes! This should be done. Alexander is going to populate the FR and DE posts with the new images. I've also attached the files here for reference.
[FR.zip](https://github.com/MozillaFoundation/Design/files/3526222/FR.zip)
[DE.zip](https://github.com/MozillaFoundation/Design/files/3526223/DE.zip)
[EN.zip](https://github.com/MozillaFoundation/Design/files/3526224/EN.zip)

**Comment by kristinashu** [comment]
Awesome, thank you!
