### ISSUE TITLE
Font weight for h5-heading

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/Design#395]
Hey @sabrinang ,

Wondering if we have changed `h5-heading`'s font weight from semi-bold (600) to bold(700)? It looks like on Sketch it's set to 700 now which is different than what [it used to be](https://github.com/MozillaFoundation/Design/issues/319#issuecomment-469926270). 👀 

<img width="621" alt="image" src="https://user-images.githubusercontent.com/2896608/62897924-1408ff00-bd09-11e9-8e30-851ad767e0c3.png">

**Comment by kristinashu** [comment]
I agree that it should be 600! I can update the sketch file.

**Comment by kristinashu** [comment]
Ok sketch style guide has been updated!

<img width="793" alt="image" src="https://user-images.githubusercontent.com/1068783/72581534-96878300-3894-11ea-8c66-fb0cc2990d09.png">
