### ISSUE TITLE
Finalize YouTube "Mock Generator" Designs

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#397]
_Note: I'm probably going to give the "Mock Generator" a new name after we figure out what direction we're going in. Doesn't seem like an apt name anymore!_

After we get feedback on @sabrinang's ideas: https://docs.google.com/presentation/d/1qEhEMWi46UD2uPZeLUM9qY5gKmNh1K12MwZmPP8paEU/edit?usp=sharing we need to firm up the design and get it ready for final review and development starting next Monday, August 26.

**Proposed Checklist**
- [ ] Gather feedback on ideas from larger YT team and choose a direction
- [ ] Flesh out and wireframe chosen direction (work with Jen Caltrider or Brandi for content)
- [ ] Gather content from Jen C and put into wireframes
- [ ] Gather feedback on wireframes with real content from YT stakeholders and devs
- [ ] Do the visual design once wireframes are good to go
- [ ] Create dev implementation ticket

cc: @kristinashu @sabrinang @natalieworth @xmatthewx

**Comment by natalieworth** [comment]
[Youtube Whiteboard Ideas.zip](https://github.com/MozillaFoundation/Design/files/3536196/Youtube.Whiteboard.Ideas.zip)

**Comment by natalieworth** [comment]
I put them in a redpen too—but they keep getting rotated? They're not rotated in the original files, but redpen's flipping them! https://redpen.io/p/cp556bf3f32b716f56

**Comment by natalieworth** [comment]
[Nat's rough sketches.zip](https://github.com/MozillaFoundation/Design/files/3536211/Nat.s.rough.sketches.zip)
