### ISSUE TITLE
Video branding & style template

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#399]
Hi team, I've head several teams talking about doing video. Some might involve us creating graphics (advocacy), others are less likely (awards). All might be produced by someone external even if we're providing some artwork. So...

Let's build a super minimal mvp template for intro, outro, title, and text. High production videos can hack it for something bespoke, but other should be able to just run with it. This should be simple so it's flexible. It also be simple because we don't yet know how much it would be used. 

@kristinashu

**Comment by kristinashu** [comment]
@natalieworth since you'll be working on this https://github.com/MozillaFoundation/Design/issues/432, might as well make it as re-usable and templatized as possible.

**Comment by kristinashu** [comment]
Natalie has made intro, bumpers, and outro for this video https://drive.google.com/open?id=1kVCgZszXHArHz-dtikhnrmWFnAhYHU3e which is reusable of other videos! @natalieworth unless there's something else you want to do for this, I'm going to mark this as closed!
