### ISSUE TITLE
Design-build "handshake" process

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#40]
Clarity in ~~handoff~~ handshake process, gh labels, ...

Designers should:
 - redline the specs
 - improve annotations on responsive behavior, gestures, interactions, animations
 - create a states checklist (hover, active, loading, error, ...) 
 - proactively link to assets
 - flag designs for tech review

Devs should:
 - flag staged builds for design review
 - flag designers when tech limitations emerge during a build so we can redesign to achieve highest quality within limitations
 - share UX ideas for discussion

More notes in https://docs.google.com/document/d/1MyI2PJ1s073JSkJdC4fx-x1DwNrcqI2iBK7m_VW0Ws8/edit

To do:
 - [ ] refine these notes
 - [ ] test this stuff
 - [ ] post a link here from design page on build dot webmaker

cc @gvn @flukeout @simonwex @vazquez @k88hudson @pomax @mmmavis @sabrinang @cassiemc

**Comment by cassiemc** [comment]
I would reverse the order of those to-do's. Let's link here from build asap so that it is shared, can update it later once we've had time to practice it. cc @xmatthewx @vazquez

**Comment by cassiemc** [comment]
Let's just add this copy to https://github.com/xmatthewx/Mofo-Design-Handbook/tree/master/Process and call it a day!
@xmatthewx can you do this this heartbeat?

**Comment by xmatthewx** [comment]
Yes. And we should probably migrate the text to the wiki for easier updates by everyone.

**Comment by xmatthewx** [comment]
Added to wiki for posterity!! https://github.com/MozillaFoundation/Design/wiki/Process#hand-off
