### ISSUE TITLE
YouTube fundraising graphic - Sept 4

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#401]
From parent ticket - YouTube fundraising graphics #390 

Sept 4: Email 3 -- Alison/Ethan’s responses to Qs

- [ ] Copy from Jen
- [ ] @natalieworth to make graphic

From Jen: the email will be the report back out on the answers to the question from the mom and son. jessie and i are culling questions today to get them to mom/son. jessie has given them a deadline of friday to get their responses back to us. i’ll try and draft something as place holder until i get their responses. but probably won’t have ready for review email copy on that until late friday or tuesday morning (monday is a holiday for the US)

**Comment by natalieworth** [comment]
I've exported blog and email sizes here: https://drive.google.com/drive/folders/1OJGAq9z9_RLLmL6h5ZmyvpCvPNXx3s3D?usp=sharing

Since I'll be on PTO/ conference next week, and we don't have the copy yet, I've kept the graphic a bit more abstract/ ominous, but still related to the email 2 graphic :D

**Comment by natalieworth** [comment]
Final assets for this [are here](https://drive.google.com/drive/folders/1OeGCWSP-GeaQkDnXc8EwDMTVaSud0kXA?usp=sharing).

[Email 3 illustrations.zip](https://github.com/MozillaFoundation/Design/files/3561851/Email.3.illustrations.zip)

**Comment by natalieworth** [comment]
There is a back up option (that could be used for something else), and a 'general' image if [needed here](https://drive.google.com/drive/folders/1OtEgv91DnihKzmAEGqLNcZhqbz18M1gF?usp=sharing).
