### ISSUE TITLE
YouTube Regrets graphic - Sept 9

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#402]
From parent ticket - YouTube fundraising graphics #390 

Email is going out Sept 10 is needed by Sept afternoon.

YouTube story submission

- [x] [Copy from Jen](https://docs.google.com/document/d/1ys9mzBO511kZq9b0DVerV5KxC3XFEdXcs-WhgOe5JFE/edit)
- [ ] Graphic for email, social, and blog (same dimensions as YouTube fundraising graphics - [template](https://drive.google.com/file/d/1Ngj1TPtsY7WzfguhfNOLg7yZdB02DJba/view?usp=sharing))

**Comment by kristinashu** [comment]
We could use Natalie's backup image or create something new. 

![backup-image-V1](https://user-images.githubusercontent.com/1068783/64198904-09d8ad00-ce3e-11e9-88ef-9d8e48ff705e.jpg)

**Comment by kristinashu** [comment]
We have also discussed using the See No Evil vector icons style:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1068783/64451370-ef4e4000-d098-11e9-9223-a60db3001104.png">

But without the "See No Evil" text and adding in a tear drop to the eye.

**Comment by sabrinang** [comment]
@kristinashu design review? https://redpen.io/p/fb63281792d5fa8afb

Iterations of youtube regrets + tears on redpen, let me know if more tears are needed 😭 
Updated the email-blog-template.ai file with this and will be exporting them [here](https://drive.google.com/open?id=1Vwjd6npmClJD2Rbw28IpcXPipbA5Vl5W&authuser=sabrina@mozillafoundation.org&usp=drive_fs) in gdrive

**Comment by kristinashu** [comment]
These are awesome! I'll share them with Jen now and let's see what @beccaklam on Monday.

**Comment by sabrinang** [comment]
Thanks for the feedback/review, @kristinashu @beccaklam I removed the close eyelid symbol in all designs.

Redpen updated: https://redpen.io/p/fb63281792d5fa8afb

Updated the email-blog-template.ai file and jpg exports in gdrive [folder](https://drive.google.com/open?id=1Vwjd6npmClJD2Rbw28IpcXPipbA5Vl5W&authuser=sabrina@mozillafoundation.org&usp=drive_fs)

**Comment by kristinashu** [comment]
Thank you Sabs! There are awesome. I've shared this version with Jen to use. I think this is good to close! There's a small chance we might need to remove the tear but I can do that if it comes up.

![image](https://user-images.githubusercontent.com/1068783/64557645-dcd14200-d2f6-11e9-8dff-106e040d6e6e.png)


![image](https://user-images.githubusercontent.com/1068783/64557633-d216ad00-d2f6-11e9-9e9a-d24a73ca1542.png)
