### ISSUE TITLE
YouTube fundraising graphic - Sept 13

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#403]
From parent ticket - YouTube fundraising graphics #390 

Sept 16: Email 5 -- Fundraising 

Launch date Tuesday 17 but would need the graphic a day early.

Jen should have copy by Thursday/Friday but the theme is that it's the last donate ask and the last YouTube fundraising email.

**Comment by kristinashu** [comment]
@natalieworth I know the deadline has been pushed back but is the graphic done? Can you just attached it here and then close this ticket?

**Comment by natalieworth** [comment]
For sure! I've uploaded the 2 blog and email versions for testing in here:
https://drive.google.com/drive/folders/1QrUdXujtWN2a6EwxxJA-cQdqnYNLWTI2?usp=sharing

**Comment by kristinashu** [comment]
Sweet! Curious to find out which one preforms better!
