### ISSUE TITLE
YouTube Story Submission Sketches

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#405]
Rebecca will create a brief here https://github.com/MozillaFoundation/Design/issues/407

**Comment by kristinashu** [comment]
@beccaklam can you please add your photos of your sketches here for future reference? Then I think you can close this.

**Comment by beccaklam** [comment]
Sketches here:
![YT-ideas-1](https://user-images.githubusercontent.com/20977376/64621964-93dfc300-d3b4-11e9-8b5f-1d0c057453e1.jpg)
![YT-ideas-2](https://user-images.githubusercontent.com/20977376/64621963-93472c80-d3b4-11e9-90c6-748bfa09e25d.jpg)
