### ISSUE TITLE
Venmo campaign ads

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#406]
## Goal of campaign
Engage a new audience (millennials) by highlighting embarassing stories of having Venmo purchases public

## CTA
"Learn how to change your privacy settings and sign the petition so that Venmo makes privacy by default"

## Launch date
- January, but we will prepare for the launch in December

## Notes
- There is money for a paid ad campaign
- Potential idea testing on Twitter before building out campaign
- Kaili is interested in doing something playing off of ["Lucas uses Venmo" memes](https://www.google.com/search?q=lucas+uses+venmo&tbm=isch&source=iu&ictx=1&fir=6iW7-_SJOPWcoM%253A%252CZdgbH1M-U7Z_TM%252C_&vet=1&usg=AI4_-kQ3xuBCZZilNXRf4ra8MwBxiGiUzQ&sa=X&ved=2ahUKEwi_v-ajseXlAhWJg-AKHeVRBsIQ9QEwCHoECAYQFA#imgrc=6iW7-_SJOPWcoM)
- Briefing [notes](https://docs.google.com/document/d/18JdXFbhJQuvbwKbK-O6EHefg-n7-s3s0r6IgrpUwJ5E/edit?usp=sharing)
- Anil sees the scope of this project as a designer helping to create ads.

**Comment by beccaklam** [comment]
[Notes from November 18 meeting](https://docs.google.com/document/d/1B5O8PIBdK-Avx1OtvDVdmKQMurb7IcxxoaXfR_1VhnQ/edit?usp=sharing)

**Comment by kristinashu** [comment]
Thanks for the notes! I'll move this to the milestone starting on Dec 10 and ending on Dec 24. But please move it back if you think there is design work to do before then!

**Comment by beccaklam** [comment]
Just documenting here that Will turned down the idea for College GameDay so that won't be happening!

**Comment by kristinashu** [comment]
Closing this in lieu of the new direction https://github.com/mozilla/foundation.mozilla.org/issues/4116
