### ISSUE TITLE
Brief for YouTube Story Submissions

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#407]
Please work with Brandi (and loop in Anil) on creating a brief for this project.

**Comment by beccaklam** [comment]
Brief template here: 
https://docs.google.com/document/d/1jusaUES0KtXOy5HYB3e9-SAPDd35z_3JdJ7U4bmEW4w/edit?usp=sharing

Will have the briefing meeting on Friday, Sept 6

**Comment by beccaklam** [comment]
This briefing should also inform ticket #409

**Comment by kristinashu** [comment]
Brief worked, it helped surfaced some alignment issues lol. Going to close this ticket since we won't be working on it in this shape or form.
