### ISSUE TITLE
Trustworthy AI email graphic - Sep 10

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#408]
Mozilla will be sending an survey email out to it's list to measure the increase in Mozilla subscribers awareness of our commitment to trustworthy AI (KR:25% increase in Mozilla supporters’ awareness of 1) MoFo’s commitment to ‘trustworthyhealthier AI’ and 2) their self-reported ‘concern’ about the topic.

We need one "trustworthy AI" email graphic.

**Comment by kristinashu** [comment]
Copy from Anil:


### Objective
Setting a baseline in order to measure the increase in Mozilla subscribers awareness of our commitment to trustworthy AI (KR:25% increase in Mozilla supporters’ awareness of 1) MoFo’s commitment to ‘trustworthyhealthier AI’ and 2) their self-reported ‘concern’ about the topic.  

### Sent to
All Mozilla List (English, German, French, Spanish)

### Send date
Monday, September 9th

### Subject Line
"A 5 second action for Mozilla"
OR "Quick Question"

### Body
As artificial intelligence increasingly becomes part of our online and offline lives, we’ve been working to lift up the issues to navigate this new world.As one of our community of over 2M Mozillians around the world, we want to get your perspective on how we can bring this issue to the forefront. You’ve likely been seeing our focus on this in our recent campaigns, emails and blogs

To help us improve, let us know: **Have you noticed Mozilla’s recent emphasis on how we can make Artificial Intelligence support our goals of a healthy internet?**

OR **On a scale of 1-5, how vocal do you think we’ve been on the importance of “trustworthy AI” 
1 | 2 | 3 | 4 | 5**

**Comment by kristinashu** [comment]
Would be nice to have a generic enough graphic that we could also use on the "Trustworthy AI" webpage (formerly called "AI & Internet Health").

https://redpen.io/jo68b087c3fcb1e905

**Comment by kristinashu** [comment]
Updated the above comment with the actual copy that is going through approvals. Email send has been delayed from Sept 9 to Sept 10.

**Comment by sabrinang** [comment]
Email graphic iterations on redpen here: https://redpen.io/p/mvaccf135a620e98de
I can also remove the Trustworthy AI text too as it may be to literal for the email

**Comment by sabrinang** [comment]
Revised iterations on redpen: https://redpen.io/p/mvaccf135a620e98de
- adjusted the type to be larger (maybe small for mobile still)
- included no text versions

**Comment by sabrinang** [comment]
jpg, mockups and working file will be in this gdrive here: https://drive.google.com/open?id=1_SNHRIq_67oc7tbWc9pFvfOJ88PQZ8Pw&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
@kristinashu Design Review?

**Comment by kristinashu** [comment]
Yes these are awesome! I'll let Anil decide tomorrow which one to use but this is good to close! And I will also use one of these for the Impact Theme page on the site.

**Comment by kristinashu** [comment]
This will _finally_ go out this Friday. Decided to keep the text but it needed to be updated to `Artificial Intelligence` and I adjusted the dimensions to fit our existing email layout.

![Trustworthy AI stack@2](https://user-images.githubusercontent.com/1068783/65188448-4d790c80-da23-11e9-9e1b-c83e2c9a6f1d.jpg)

Graphic is also on the thank you page the buttons link to https://foundation.mozilla.org/en/campaigns/thank-you-for-your-response/
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/1068783/65188485-608bdc80-da23-11e9-80e6-0f4a91449963.png">
