### ISSUE TITLE
YouTube Regrets Social Graphics - due Oct 3

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#409]
We'll probably need some social graphics to promote story submissions once the action goes live after the Sept 10 email. Details to come after Sept 6 meeting with Brandi.

**Comment by kristinashu** [comment]
Assigning to Rebecca to _gather info_.

**Comment by beccaklam** [comment]
@kristinashu Brandi says maybe just one to promote the site itself.

**Comment by kristinashu** [comment]
Ok awesome! So one graphic at two dimension:
- one cropped for email
- one cropped for blog, social, media

Let's say it's due for the media / soft-launch on Oct 3.

**Comment by kristinashu** [comment]
@natalieworth this seems like a nice opportunity to test some stuff out on Instagram!

**Comment by natalieworth** [comment]
Got a start on these today and added facebook, twitter, adn instagram options here: https://redpen.io/p/vo2ab21e6e17b0c110

Working .ai file is here: https://drive.google.com/drive/u/0/folders/1662ZFbdRlQ6iq5Ue2XZNhxNVjGieQtHG

cc @kristinashu @beccaklam
