### ISSUE TITLE
Create a design contract

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#410]
We would like to develop a more official sign-off and brief process for when we are working on bigger/cross-team projects.

@beccaklam's [brief](https://docs.google.com/document/d/1bCB4dorY2VjBC8KfL5p-QrAsoBbu7FgeSDWmCTI34XY/edit?usp=sharing) is a good start and a way the listen to what a stakeholder wants. But once we have that info, we should take what we learnt and interpret it with our lenses and expertise. We should then present this back to the stakeholder(s) and get sign-off on it before starting.

Let's do a little bit of research and benchmarking, [start a doc with all our ideas](https://docs.google.com/document/d/1Z8YSLRZ4uT9c6b0QocbmymCfeWyXDjAkj9Bymy70-8I/edit?usp=sharing), then cut it down, and then test it on YouTube Stories + PNI.

Related links
- [Example Email RASCI ](https://docs.google.com/document/d/1Jw9ukVaLz3eTN2bFLoN47a389oX55z8I-BagDhAxVxc/edit)
- [Old MoFo Design Brief](https://docs.google.com/document/d/1H4rDTT7zdvOFhGlgMDIuRLlTRlAxMsU_-mUehv_iEZU/edit)

cc @sabrinang @xmatthewx

**Comment by kristinashu** [comment]
@beccaklam and I are testing it with PNI [here](https://docs.google.com/document/d/1uYHSB0JvmjzmZc_iYZmoz2ABKJoBrDXSeq_f2Xf3GOU/edit?usp=sharing).

**Comment by kristinashu** [comment]
We just need a _template_ version of this then it should be good to close!

**Comment by beccaklam** [comment]
@kristinashu I've made a [template](https://docs.google.com/document/d/1gq69upw8EQZG1QvdNAnaTI9ZoxeOuXE225wRtUyCUwQ/edit?usp=sharing) of the PNI brief, can I get a design review?

**Comment by kristinashu** [comment]
Thank you! R+

Is it in Drive somewhere? If you haven't already, please put this template along with your interview template in a folder together.

**Comment by beccaklam** [comment]
Yeah they're both in Design Assets > Briefs @kristinashu 👍

**Comment by xmatthewx** [comment]
Probably good to add to fo'mo/docs as well!

**Comment by beccaklam** [comment]
> Nice! Probably good to add to fo'mo/docs as well!

Where can I find that folder @xmatthewx ?

**Comment by xmatthewx** [comment]
Oops. I mean on the site: https://foundation.mozilla.org/en/docs/brand/design/

**Comment by beccaklam** [comment]
Done!
