### ISSUE TITLE
Instagram: Strategy/Stats for KR Numbers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#411]
**Related to KR 1.3**

Gather existing baseline numbers to create a slide for ![How We Measure](https://docs.google.com/presentation/d/1oAave-1pzUWkDho9DCctz2r7LKcRCfOiw6zy7c4lXcQ/edit?usp=sharing) deck
- research how we gather info for dashboard (manually put in numbers on slide or screenshots)
- coordinate how we compare and count instagram data

Plan what activities we measure and how we measure the numbers 
- access account and set up business profile
- set up and analyze our activities (instagram insight, promote, scheduler etc.)

Related Docs: ![Content Brief](https://docs.google.com/document/d/1bPNKLDEivv6YZv_o32964bfd9RhoAzz2ikGA4TA2tTU/edit?usp=sharing)

cc: @natalieworth @caltrider

**Comment by kristinashu** [comment]
For some rudimentary numbers... here's a screen cap I took on Oct 16 shortly after YouTube Regrets was posted:
<img width="1141" alt="Screen Shot 2019-10-16 at 11 51 16 AM" src="https://user-images.githubusercontent.com/1068783/68825287-74804300-064e-11ea-93a1-a190d43c26fb.png">

And now: Numbers are ⬆️ 📈
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/1068783/68825378-bf01bf80-064e-11ea-8dd9-0c2928cb17fc.png">

**Comment by kristinashu** [comment]
Combining Instagram related tickets into one https://github.com/MozillaFoundation/Design/issues/453.
