### ISSUE TITLE
Fundraising AI campaign: Report out

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#412]
Will need graphics. Instead of waiting each week for copy let's make some generic ones all at once!

Style should be similar to Sabrina's https://github.com/MozillaFoundation/Design/issues/408

Planning doc https://docs.google.com/document/d/1633Goa0lDE4zrFSQ2Vg021QAJ8GsDBWwZTtpiXtiPL0/edit

See notes below...

**Comment by sabrinang** [comment]
Sept 24 - Kick off with Jen @caltrider

**Additional Reference Docs**
Campaign Summary Brief: https://docs.google.com/document/d/1TK7C9xu50JmdtXJyaeeXbb88zlaIi-CxUFeenKIZ_1g/edit
Survey Draft: https://docs.google.com/document/d/1lPR4vqQ4cl7Z-p-_xP2tTfPuWKuOAXoqkHs1_CMf4ew/edit

Design backgrounds similar direction to Artificial Intelligence emails (no text needed so we don't need to localize)

3 Sets of Email/Blog/Social

SurveyGizmodo
  - banner dimensions
  - simple mozilla branded

Survey Result Graphics
  - dependent on the results it would be around 8 graphics
  - after English draft it needs to localized for German & French graphics

Donation/Fundraising graphics
  - currently testing [youtube donate graphics](https://drive.google.com/drive/u/0/folders/1QrUdXujtWN2a6EwxxJA-cQdqnYNLWTI2) and will learn from finidings how to approach this

Jen to confrim with Will about timelines

**Comment by sabrinang** [comment]
Jen clarified schedule with Will on [summary briefing doc](https://docs.google.com/document/d/1TK7C9xu50JmdtXJyaeeXbb88zlaIi-CxUFeenKIZ_1g/edit).

I included a design checklist here to the Planned Schedule:

**October 9:** Email 1 — Survey (Localize French, German, Spanish)
- [ ] Survey Gizmo Banner ([recommended header image sizes](https://help.surveygizmo.com/help/recommended-header-image-size))
- [ ] Graphic in Email / Blog / Social dimensions

**October 15:** Email 2 — Kick the Survey (email, twitter, other social, etc. )
- [ ] Graphic in Email / Blog / Social dimensions

**October 23:** Email 3 — Lotta email 2-3 messages that highlight the work we’re already investing in
- [ ] Graphic in Email / Blog / Social dimensions

**November 5:** Email 4 — Survey report back
- [ ]  ~8 Survey result graphics for Blog dimensions
- [ ] German version
- [ ] French version
- [ ] Spanish version

**November 7:** Email 5 — Fundraising ask
- [ ] Donation/Fundraising graphic in Email / Blog dimensions

**November 9:** Email 6 — Kicker Ask=donate
- [ ] Donation/Fundraising graphic in Email / Blog dimensions

**November 11:** (possible) Fundraiser kicker 2
- [ ] Donation/Fundraising graphic in Email / Blog dimensions

**Comment by sabrinang** [comment]
I'll be working on iterations in redpen (will be continuing to working on it this week): https://redpen.io/p/ynffa05fa8846be564

Note: The previous Oct 2 email date has changed to Oct 9 brief doc

**Comment by sabrinang** [comment]
Revised images in redpen: https://redpen.io/p/ynffa05fa8846be564

This includes images from Oct 9 - Nov 7. Survey result images are examples of style types as we don't have the responses yet.

I included an alternative header image style as I wasn't sure if it needed to be different from the banner header image.

@caltrider @kristinashu Design Review?

**Comment by kristinashu** [comment]
R++ 

These are so beautiful! We will have to find ways to use these throughout the site!

**Comment by sabrinang** [comment]
.ai file and exports in JPG folder here: https://drive.google.com/open?id=14qs99ymIiUEJ9bF4C12urEvCZqeDN0cP&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by kristinashu** [comment]
@taisdesouzalessa for the report out, @caltrider should have the results and copy ready for the email and blog post by EOD tomorrow. Since you're off Friday you should reserve Monday to do this work since Alexander will need to graphics on Tuesday to build the email.

**Comment by caltrider** [comment]
@taisdesouzalessa @kristinashu Just chatted with Will. Small shuffle of emails going out next week. Now the survey report back is scheduled to go out on Thursday, November 7th. I will have copy done by Monday as Arliss is still digging into the data.

**Comment by kristinashu** [comment]
@beccaklam will do the survey results for the email and blog post!
- She will meet with Jen today
- Jen's content doc is [here](https://docs.google.com/document/d/1sd-cQzqZqOj4E1XH3yJqhQCKWS8zqxxMWP3sDoyKVGQ/edit). 
- Sabrina has already established the style for the graphics. Working files are [here](https://drive.google.com/open?id=14qs99ymIiUEJ9bF4C12urEvCZqeDN0cP&authuser=sabrina@mozillafoundation.org&usp=drive_fs).

**Comment by beccaklam** [comment]
@caltrider @kristinashu First draft of graphics here:
https://redpen.io/p/jqe508e1c2bb7af621 I'll work on revisions first thing tomorrow!

**Comment by beccaklam** [comment]
Revisions are done and sent to Jen. I've put the graphics and illustrator working file onto the drive: https://drive.google.com/open?id=1SLS5Ei_kmkp44-EJbmPI1gpbSWBHMAcn

**Comment by beccaklam** [comment]
@caltrider did we need translations for these? cc: @kristinashu Was just looking at the checklist ☝️ but not sure if that's up to date ...

**Comment by caltrider** [comment]
@beccaklam @kristinashu Just ran the localization question by Will and Jessie. They said yes, we should plan to localize. Will is going to get with Theo to see about getting that done. I'll shoot you all and update when I know more.

**Comment by beccaklam** [comment]
@TheoChevalier got me the localized strings and here are the translated graphics on the drive:
[German](https://drive.google.com/open?id=1VTe7cie-YxcuUo9-UkJVtTuaarPf9yP3)
[French](https://drive.google.com/open?id=1CGXQnF5YR2i9G9yP2kbTr6lV8fMUpMLw) 
[Spanish](https://drive.google.com/open?id=12hcSFHcBqYUNwEeIwpIa1OXkLxrgBC0Z) 

@kristinashu Not sure if we can close this ticket yet? Have all the donation/fundraising graphics for blog/email been made?

**Comment by TheoChevalier** [comment]
Thanks Becca!

**Comment by kristinashu** [comment]
@caltrider do you know if additional graphics are needed? I think all these emails have gone out.

**Comment by caltrider** [comment]
Yes, all the email for this campaign have gone out. These localized graphics should be the last for this campaign.
