### ISSUE TITLE
Fellowships/Pulse onboarding slide deck

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/Design#413]
@sabrinang to add more info about what the deliverable is here by Oct 7. Actual design can happen in the next milestone.

**Comment by gideonthomas** [comment]
@gideonthomas to schedule call with Anil and Sabrina to figure out what is going into this.

**Comment by taisdesouzalessa** [comment]
Met with Gideon and Anil on Oct 9th. Here are the notes:
• [Here is the outline](https://docs.google.com/document/d/1q5rSLTNQzkaF_Ti5hewroM1F2TmOTbThRbeEuB7neKA/edit?ts=5d9d3473) and also where content will be posted - Anil to post content there by Friday (Oct 11th)
• Taís to start working on generic template and add specifics once content is defined
• Taís to partner with Anil for presentation during MozFest
• DEADLINE for slides: Oct 21

@gideonthomas @anilkanji here are the notes from the meeting, feel free to edit my post if I missed something.

**Comment by taisdesouzalessa** [comment]
IMPORTANT! Format of the presentation - things to keep in mind:

- [ ] Duration of each interaction: 12min
- [ ] Repetition: 5 times (small groups of Fellows)
- [ ] Format: everything offline and pre-loaded on your own device, prepared on paper
- [ ] Restriction: not a lot of time to set up, keep it simple
- [ ] Conversation style (rather than a formal presentation)

**Comment by taisdesouzalessa** [comment]
Met with @anilkanji , we will put some content together by Thursday, Oct 17th. I could advance the slides a bit by adding questions we could ask Fellows ans selecting some case studies/screenshots we could display.

**Comment by taisdesouzalessa** [comment]
Slides are [here](https://docs.google.com/presentation/d/1jTbBfQq7MkgzhcmqdAkewB1RYO8YjkazG5CqH-4N4uk/edit?usp=sharing)

@anilkanji could you please take a look at my comments in the slides and add the missing content when you have a chance? I added labels on the top right corner of every slide so you know what is needed from each one. 

@gideonthomas tagging you here for visibility on status of this project.

**Comment by taisdesouzalessa** [comment]
Presentation was done during MozFest. Closing this ticket.
