### ISSUE TITLE
Fellowships/Pulse research experiment

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/Design#414]
Research the problem space of fellowships updates by having conversations with key stakeholders. 

Deliverable: A strategy for how Pulse (or any other solution) might fit into solving this problem.

New tickets might come out of this.

**Comment by sabrinang** [comment]
@jamjwait @annmarie123 Tracking some updates from slack here so it's visible for @gideonthomas too

**Notes:** 
- Fellowships start today (October 1) 
- Page where Fellowship updates are shared: https://foundation.mozilla.org/en/fellowships/fellowship-and-award-updates/

**Pulse Updates to Slack Channel _(request)_**
- pulling the updates the fellows will be posting to Pulse (tagged #mozfellows19) into the #mofo_fellowships channel on slack
- similar to the posts being pulled into the pulse slack channel, but limited only to posts with the fellowship tag...)

**Pulse Guide for Fellows**
- https://docs.google.com/document/d/1B0BOLwJMWiYOYotv6g-KbcyBFQwn0T_CBiwfO_4HGV0/edit?usp=sharing
- how to guide for fellow to post their regular project updates
- @sabrinang has left review comments

**Comment by gideonthomas** [comment]
@gideonthomas to onboard @taisdesouzalessa onto this and have this be a shared activity with Sabrina while Sabrina focuses on MozFest

**Comment by taisdesouzalessa** [comment]
Met with Sabrina and Gideon to get the context of this task.

**Comment by taisdesouzalessa** [comment]
Received template from Gideon and modified it a bit to adjust it to our project's needs. Started to fill in the gaps with info and sent to Sabrina and Gideon for feedback. New template here: https://docs.google.com/document/d/1ize5UE_C8UUAIA9Yy4I-U46hcj8_0Yt2viw56K1tdeE/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
Kristina found a great summary of the goal on Airtable (thanks, @kristinashu!). I'll open a new ticket centered on this goal so we keep focused on it. 
Closing this ticket and the new one is here: #424

**Comment by taisdesouzalessa** [comment]
After meeting with team, this project is on hold as we gather more info from the Fellowships team.

**Comment by kristinashu** [comment]
Closing this ticket. The short-term work is done and we can open a new ticket for any long-term work we decide to do.
