### ISSUE TITLE
Small bug in Docs template 

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#415]
Whenever i use the [docs template](https://docs.google.com/document/d/1K0KaFU_-0Mi49RZW_mGCLY9UPOGWc68Pg-TfFZm_sNY/edit), I hit a small bug. The logo falls behind the header dots image and gets cut off. 

Google docs doesn't have a way to explicitly change the stack order. It'd be better if the dots either had a transparent cutout or if it included the logo as a single file.

**Comment by xmatthewx** [comment]
I use this template often. This still happens to me occasionally for no reason. What do you think @sabrinang? I think a single image file would fix this.  

<img width="821" alt="image" src="https://user-images.githubusercontent.com/53411/74484897-7fce4f00-4e87-11ea-85ce-9cb64ecb626d.png">

**Comment by kristinashu** [comment]
Tais, Sabrina, and I don't see this issue and don't understand how it could happen since it's a png. Sorry but closing this as "won't fix".
