### ISSUE TITLE
Design a less obtrusive donate pop over

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#416]
There's been some discussion on hackernews about our big donate pop-over CTA, and whether it aligns with the web we're trying to foster. Dogmatic debates aside. We should explore ways to make it effective, but less annoying to users. In my own personal experience, things like this annoy the crap out of me. 

Something bright but slim at the bottom of the screen?  Or a slide down from the top that moves content down rather than covering it up? 

cc: @kristinashu @alanmoo

**Comment by kristinashu** [comment]
Yes. I'll put this as a design ticket and in the meantime I believe Pomax is hiding the prompt.

**Comment by anilkanji** [comment]
Interesting - does anyone have a link to the discussion?

**Comment by xmatthewx** [comment]
I think it was in hacker news about the web monetization partnership. One person mentioned that FF might block those pop-overs. I just tried but couldn't find it. 

I think our donate ask should be bold and loud, but it shouldn't block people. the internet has become an endless stream of modals to dismiss. it's just not the web we want. it makes apps more desirable despite their other drawbacks.
