### ISSUE TITLE
Voice assistant graphic update

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#417]
placeholder for Kaili's updates

https://foundation.mozilla.org/en/campaigns/how-opt-out-human-review-your-voice-assistant-recordings/

**Comment by kristinashu** [comment]
Kaili's going to give the copy updates here https://redpen.io/p/ny1532827ff26fd1ef

**Comment by kristinashu** [comment]
@beccaklam hey, I was going to do this but I can't seen to find the working files in drive? Kaili has commented in redpen with the copy updates, could you please update the graphics Monday morning and then share it with her?

**Comment by beccaklam** [comment]
@kristinashu sorry just saw this, was deep in donate QA, I'll do this now.

**Comment by beccaklam** [comment]
Updated graphic and also put all the files on the drive: https://drive.google.com/file/d/1SzjBo5W037ctjuY7BChWnQA8TsnvmguL/view?usp=sharing Waiting for Kaili's approval.

**Comment by kristinashu** [comment]
Thank you!!!

**Comment by kristinashu** [comment]
This is done, right?

**Comment by beccaklam** [comment]
This is done!
