### ISSUE TITLE
PNI at MozFest

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#418]
## PNI at MozFest
- Last years tickets: 
  - Buyers Guide: Promo at MozFest #281
  - Digital Things mozilla/foundation.mozilla.org#1918
  - Physical Promo for Buyer's Guide #287
- Maybe we can find some inspiration from Nat's [all-hands slide deck](https://docs.google.com/presentation/d/13640VNmHQku6hiiUbp1X0DMeKGglAepKKO9hs0dttNw/edit#slide=id.p)
- Here's an inspirational photo lol

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1068783/66351150-efe52b00-e911-11e9-8e87-1ce13f53615d.png">

### Digital Assets
- [x] holiday homepage banner
- [x] try to incorporate stars in the Meets Minimum Security Standards badge

### Print Assets
Comps from last year https://redpen.io/p/yv3237593a82410b77 
- [x] stickers ~~(Order **Tuesday Oct 15** to receive no earlier than Oct 23 since Ravensbourne can't receive things until then)~~ Ordered Oct 9, delivering to London office
- [x] posters
  - last year we had both A2 and A0 - do we need both again this year? 
  - ?? copies
- [x] postcard 
  - A6
  - 500 copies

### Raffle
- Jen will organize the raffle [please add a link to your future doc here]. _(here is the [old doc](https://docs.google.com/document/d/1u5ptsXqT1ZVU6O9hocSPaB11NongNYxkiCkCHBEHYUE/edit#heading=h.ieulo3kx9eeh))_

### Moved main launch stuff here https://github.com/MozillaFoundation/Design/issues/423

**Comment by kristinashu** [comment]
@beccaklam @natalieworth @caltrider [here](https://docs.google.com/document/d/1hHOMw3DBfPD9dpcETxrpKhU_LsjRhsv6ZYtPYUbIQmA/edit#) are the notes from kick-off. I've also updated the [first comment in this ticket](https://github.com/MozillaFoundation/Design/issues/418#issue-499542402) to better reflect what we need to do. Some questions in there what we can discuss at stand.

**Comment by beccaklam** [comment]
FYI @natalieworth if you want to make a cool sticker I think the latest we should order is by this Friday, but I need to make sure Amanda is coming into the office that day too. Did you still want to do it or should I just reorder the old ones?

**Comment by natalieworth** [comment]
I've added the start on posters, the banner, and potential badge updates here: https://redpen.io/p/qw3028b6e45cf35e64

**Comment by beccaklam** [comment]
Jen, Natalie and I met and went over Nat's designs ☝️ We were all pretty happy with what she had so far. Decided Nat would continue to play around with the MSS badge just to see what else she could come up with. Jen is happy with the posters, just mentioned that people love the creep-o-meter if we could incorporate that at all. Though we said that other assets would have plenty of creep-o-meter faces. Becca to give nat an example of what she means by movie trailer star ratings.

**Comment by kristinashu** [comment]
Ok, did you decide if we need postcards or not? If not then how are we going to let people know what the raffle rules are?

**Comment by caltrider** [comment]
I think since it will pretty easy to tweak last year's postcards, let's go ahead and do them to have as handouts on the table and maybe at check in. I don't think we need to print quite as many as we did last year though. If I recall, we had extras last year.

**Comment by natalieworth** [comment]
postcards would be cute!

**Comment by kristinashu** [comment]
Yeah we had a ton of postcards last year because they were in every festival guide but we won't be doing this year. We could print the postcards and the posters with www.solopress.com (same as last year). Roughly £35 for 500 postcards. Does 500 sound good? Once the artwork is done, @beccaklam could you order it with the magic credit card?  They seem to have about a one week turnaround time.

**Comment by caltrider** [comment]
500 postcards sounds like plenty. Thank you!

**Comment by beccaklam** [comment]
Lol what magic credit card? You mean Ashley's? I shall try ... @caltrider do we need to give Ashley another heads up?

**Comment by caltrider** [comment]
Yes, Ashley's credit card should work. We don't need to give Ashley another heads up as she has already approved spending for us in the same range (or a little more) as last year. I think so far we're on a good track to be spending just about the same as last year with our printing and raffle prizes.

**Comment by beccaklam** [comment]
Okay sounds good. @natalieworth Let me know when the postcards are ready to print and I'll coordinate with Amanda to place the order. Btw, also ordered the stickers today! 😄

**Comment by natalieworth** [comment]
@beccaklam Have all the poster/ [print files in here](https://drive.google.com/drive/folders/1cUB6TWg0BFKaryobm4zRtvkQN1TZjfCv?usp=sharing). Just waiting on R+'s from design, so almost good to send to print!

**Comment by kristinashu** [comment]
Lookin good!

### Site assets
Please export the banner and the badge and add them to this ticket - PNI: implement updated homepage copy and banner #3752 (make sure to use the same dimensions as on the current site and make the the file size isn't too big).

### MozFest assets
Looks like there are a few edits but once that is done please export the print ready files and we can do one final review.

What size are the posters? How many copies do you think we need of each?

**Comment by caltrider** [comment]
I think for all the posters, the sizes we did last year worked well. 
Maybe like 4-5 of the big ones for our table area. 
And 30-40 of the smaller posters we put up around MozFest announcing the table & raffle. 
That sound about right to you all?

**Comment by beccaklam** [comment]
@natalieworth Here's a doc that refernces the sizes we used last year: https://docs.google.com/document/d/155cHkadlziL9dOLRjkmvoevFDHA1CUqioLE92ic6MjM/edit?usp=sharing if you could prep and export the print files that would be **great**. Then I'll make the order.

**Comment by beccaklam** [comment]
Okay, so postcards, posters for the raffle, and posters for our table have all been ordered! cc: @natalieworth @kristinashu @caltrider

**Comment by kristinashu** [comment]
😮 Amazing!

**Comment by kristinashu** [comment]
So last step @natalieworth is to add the banner background to https://github.com/mozilla/foundation.mozilla.org/issues/3752 and the badges to https://github.com/mozilla/foundation.mozilla.org/issues/3767.

**Comment by caltrider** [comment]
Thank you all for getting that stuff ordered here at the last minute!

**Comment by natalieworth** [comment]
> So last step @natalieworth is to add the banner background to [mozilla/foundation.mozilla.org#3752](https://github.com/mozilla/foundation.mozilla.org/issues/3752) and the badges to [mozilla/foundation.mozilla.org#3767](https://github.com/mozilla/foundation.mozilla.org/issues/3767).

Updated the above links, but also dropping them here if needed for future reference:
[Header image](url)
[Badge and mini badge](https://drive.google.com/drive/folders/1hQmCYTr7pI16-lGwPKKWLwgDDvaIwLmZ?usp=sharing)

**Comment by natalieworth** [comment]
2019 Mozfest print assets [are here for reference](https://drive.google.com/drive/folders/1qH-k9JBfJxxIElsjaXTuDpGpBKN-pwlh?usp=sharing).

**Comment by natalieworth** [comment]
Hey @kristinashu do you think we should update the general social share:
<img width="544" alt="Screen Shot 2019-10-15 at 2 27 52 PM" src="https://user-images.githubusercontent.com/14876567/66838199-306d2600-ef5c-11e9-915b-b94cb970c5e0.png">


![pni-2019-social-share](https://user-images.githubusercontent.com/14876567/66838185-2b0fdb80-ef5c-11e9-9dda-b7d3f8e9b957.jpg)

**Comment by natalieworth** [comment]
Maybe something like this:
![Screen Shot 2019-10-15 at 2 27 52 PM-2](https://user-images.githubusercontent.com/14876567/66838336-69a59600-ef5c-11e9-88c6-ad52102decfa.jpg)

**Comment by caltrider** [comment]
Ooohh! I love that @natalieworth!

**Comment by kristinashu** [comment]
Nice Nat! @caltrider do you have some new share/OG copy? Once we have the copy we can open a dev ticket to update this.

**Comment by kristinashu** [comment]
Let's add the image and copy here #3785 so we can close this one!
