### ISSUE TITLE
Standardize Mofo site footers designs

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#42]
Luke is going to tackle this with the new Thimble homepage in https://github.com/mozilla/thimble.webmaker.org/issues/655

**Comment by cassiemc** [comment]
We'll need a separate ticket for the tech side of this.

**Comment by cassiemc** [comment]
@flukeout anything you can share here from the teach gallery designs?

**Comment by flukeout** [comment]
For sure, here's what we've got so far for the Thimble homepage designs, which are in progress here:
https://redpen.io/or0f6e3e18912fc780

![image](https://cloud.githubusercontent.com/assets/25212/8555253/a6a0515e-24a3-11e5-8d83-d75eca3b135a.png)

I'll update this ticket with the current footers from:
* Teach
* Webmaker Beta
* Advocacy
* ... others?

Then we can get started on the unification.

**Comment by cassiemc** [comment]
How's this going @flukeout? Have you managed to collect the other footers?

**Comment by flukeout** [comment]
**Advocacy Footer**

![image](https://cloud.githubusercontent.com/assets/25212/8734616/0e053d6e-2bc0-11e5-9e9c-1947e81995fc.png)

**Webmaker Beta**

![image](https://cloud.githubusercontent.com/assets/25212/8734702/8b021b66-2bc0-11e5-985c-a2d5c64a322f.png)


**Teach**

![image](https://cloud.githubusercontent.com/assets/25212/8734713/9c422880-2bc0-11e5-83e9-b55e939e6041.png)

**Comment by cassiemc** [comment]
This is fantastic @flukeout. Maybe the next step here is to set up a meeting with the product managers of each of these sites to present these and so we can ask questions to understand how the differences might be important. I'd be happy to drive that when I'm back from PTO. 

In the meantime, perhaps we can do some benchmarking of other modern footer design trends?

**Comment by cassiemc** [comment]
Next step: Benchmarks of other footers! cc @flukeout

**Comment by cassiemc** [comment]
@flukeout Want me to help source some benchmarks?

**Comment by cassiemc** [comment]
@flukeout did indeed want my help putting some benchmarks in. I started collecting a few. 

<img width="1371" alt="screen shot 2015-08-25 at 12 35 01 pm" src="https://cloud.githubusercontent.com/assets/1186326/9553621/45b6307a-4d8e-11e5-8894-1b5cb4fffbca.png">
<img width="1388" alt="screen shot 2015-08-25 at 12 34 08 pm" src="https://cloud.githubusercontent.com/assets/1186326/9553624/4910e832-4d8e-11e5-91d2-f72348de40e0.png">
<img width="1307" alt="screen shot 2015-08-25 at 12 17 23 pm" src="https://cloud.githubusercontent.com/assets/1186326/9553627/4c124288-4d8e-11e5-9b4a-957078ebb335.png">

For the most part modern designs seem really simple compared to what we have now. I am going to put this bug on the backburner though until we have more of an overall tempating plan and can figure out where this sits in the list of priorities.

**Comment by cassiemc** [comment]
There is some good work here, and it relates to https://github.com/MozillaFoundation/plan/issues/644 in the Plan repo. I expect this work to get prioritized in the new year, so adding to a late Jan milestone.

**Comment by cassiemc** [comment]
We've actually made some good progress on this front since this bug was last updated. @kristinashu can  you add some thoughts here based on what you've discovered in the mofo design audit? Would love to unearth a crisp list of next steps in order to close out this bug. Might require working with lots of different stakeholders but I suspect it's not actually that hard to make happen. 

/cc @simonwex b/c eventually will need some dev support. Also might just make sense to make this a part of the CMS rollout.

**Comment by cassiemc** [comment]
Likely some insights from @kristinashu's Mofo design audit doc: https://docs.google.com/presentation/d/13v_Rr2ypxscqSZWksLAzc5TZ8NRy0MuGSP9yK-FEKFo/edit#slide=id.p

@flukeout If you find you have extra time this heartbeat this would be a good place to make progress as well. Would be great to sync up and build into Calypso plans.

**Comment by sabrinang** [comment]
design decisions will be made on #164
