### ISSUE TITLE
Unlock Instagram

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#420]
We should start testing out some post on Instagram and establish our account. Strategy is happening here https://github.com/MozillaFoundation/Design/issues/389 and KR tracking is happening here https://github.com/MozillaFoundation/Design/issues/411 but let's no let that block this work. 

- [x] Anil to get log in
- [ ] Get account verified check-mark
- [ ] Get business account?
- [ ] Follow stats/analytics https://github.com/MozillaFoundation/Design/issues/411
- [x] Test posts with YouTube, MozFest, PNI

**Comment by kristinashu** [comment]
@natalieworth please add Liz's and your thoughts here!

**Comment by natalieworth** [comment]
Updates:
Started to put together a [rough strategy doc here](https://docs.google.com/document/d/1kCqjVwCpTXDAYpi70Fn6xfEr6wY8Nsa-BcnatN4MFH0/edit?usp=sharing).

After further refining this, I'm meeting w/ Jen and Audrey on Thursday this week to go over everything.

**Comment by kristinashu** [comment]
Combining Instagram related tickets into one https://github.com/MozillaFoundation/Design/issues/453.
