### ISSUE TITLE
Update colour of body-small text and H6

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#422]
## Updating an existing style

_1. What element/ style is being changed?_ 
The body-small style and H6

_2. Why it is needed?_
Currently the colour of body-small style and H6 is #999999. Doing a web aim contrast check for accessibility yields a complete fail result for #999999 on a white background. We should change the colour to make the text more accessible and legible.

![image (3)](https://user-images.githubusercontent.com/20977376/66239900-0482b280-e6c9-11e9-8acd-56ee22a451ca.png)

  - [ ] Post proposed brand update in Redpen (for desktop, tablet, mobile)
  - [ ] Request design review from design team via R+/R- in Github ticket
  - [ ] Get feedback from devs

**After Approval:**
  - [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

## Design Reviewer Checklist
_An issue template in github_
**For design review:**
  - [ ] Is this change justified or are we able to use existing brand elements?
  - [ ] Is the development time viable?
  - [ ] Provide an R+ or R- in the ticket
  - [ ] List reasons for approving or denying changes

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by sabrinang** [comment]
Exploring this colour/legibility issue:

- comparing existing gray-40 `#999999` to gray-60 `#666666` and gray-80 `#333333`
- included comparison of scaling 12px to 14px (in gray-60) which may be related to https://github.com/MozillaFoundation/Design/issues/429 if we scale up body copy proportions we can consider it here too that may help with legibility

I'm taking screenshots for comparison and using pages from foundation.mozilla.org and privacynotincluded.org as examples: https://redpen.io/p/er265a5aff7f47d8be

**Comment by sabrinang** [comment]
After crit, we decided on `#666666`

**Comment by sabrinang** [comment]
**Text Style Sketch Library Updates to Style Guide.sketch file**
- changed mobile/desktop h6 and body-small (`#666666`)
- created h6-heading dark-theme and updated body-small dark theme (`#999999`) to keep contrast as it was previously shared
- cleaned up text style names and typography documentation

**Comment by sabrinang** [comment]
Created dev ticket here: https://github.com/mozilla/foundation.mozilla.org/issues/4136
Closing this design issue.
