### ISSUE TITLE
PNI marketing launch - Nov 20

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#423]
Will be meeting about this tomorrow. Anil is compiling a list here https://airtable.com/tblsj6kaxzOJ7paaz/viwx45L8UughVaWvi?blocks=hide

###  Email Nov 13
- [x] holiday email graphic

### Launch Nov 20
- [x] social and media assets similar to last year https://redpen.io/p/aj7f2e09f704b2e4ee

### Press event Nov 20
- [x] handout
  - URL
  - couple products (2 good / 2 bad)
  - postcard or Letter size
- [ ] video: if we have a videographer, let’s scope out what a promo video might look like and resource visual elements to help package a nice video for different platforms

**Comment by kristinashu** [comment]
@anilkanji please let Natalie know what you need for the snippet. Also please included her in any upcoming PNI marketing meetings. Also also, how involved will Audrey be?

@natalieworth for now, you can start with the email graphic due Nov 12 and start to explore some ideas for social media.

cc @caltrider

**Comment by natalieworth** [comment]
Email graphics are in here @caltrider https://drive.google.com/drive/folders/1U_LCsG4-R3aOMWTlyxSjM0rqfnd2y3km?usp=sharing

**Comment by natalieworth** [comment]
@anilkanji @caltrider For the handout listed above, do you know the content that we will need? I think we should design these today as we'll need to accommodate print time (usually takes about 1 week).

cc @kristinashu

**Comment by caltrider** [comment]
@natalieworth I say we ask Kevin/Lotta about this. Let me start a slack thread on that. Good call to get them started today so we have time to print.

**Comment by natalieworth** [comment]
Handout is [here](https://drive.google.com/open?id=1cpZELs4WhVaiTgN6H7wEAjp0pPLbWid0).

**Comment by natalieworth** [comment]
Assets for the marketing launch are in [the drive here](https://drive.google.com/open?id=108TA8lUHfo9A4MO4qoMaKMkSqJw1kOCE).

So far, they include images for mozilla.org/ foundation site hero, social/ instagram stories, the press handout, and posters (if needed).

**Comment by natalieworth** [comment]
I don't think we had time for videographer, so closing this ticket for now.

**Comment by anilkanji** [comment]
@natalieworth we did get a videographer - but they went ahead and packaged a quick video - you can ping Audrey to see it.

If still possible would love the image/GIF for internal screens!

**Comment by KevZawacki** [comment]
Here's the video: https://www.youtube.com/watch?v=0eY1OLYqQus

**Comment by natalieworth** [comment]
The Pinterest ad exports are here: https://drive.google.com/drive/folders/1YS1bgFKGzJTO99ZI_HE5xrgYQslg5kkj?usp=sharing

**Comment by natalieworth** [comment]
Internal screen [is here](https://docs.google.com/presentation/d/1hShowOdGG8HM6fuIKA9qq6jlq2zeYxUywcmnMYoy5FM/edit?usp=sharing)

cc @anilkanji

**Comment by beccaklam** [comment]
@natalieworth that animated gif is so cute! after effects?
