### ISSUE TITLE
Nat's H2 Goal Tracking

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#426]
### Intro

**Goal 1:** 
Learn/ harness the instagram business metrics platform in order to grow our Mozilla instagram account
--

**Goal 2** 
Continue to build out the Mozilla brand by adding external docs to the Foundation site.
--

### Links

cc: @kristinashu @sabrinang @natalieworth @taisdesouzalessa @beccaklam

**Comment by natalieworth** [comment]
Goal 1 Instagram Tracking: I've set up a [google sheet data doc](https://docs.google.com/spreadsheets/d/1Upoh2AjMpGMn0bWRuCwDfFUZ1XCpHnAPcrVVzS77IJ4/edit?usp=sharing) to track our Instagram OKR goals for 2020. For now, it's free, easy to share, easy to use, and only uses the lean data from the Instagram platform—but once we grow bigger it could be good to possibly look into something paid (maybe in 2021)?

**Comment by kristinashu** [comment]
@natalieworth is this ticket all done?!
