### ISSUE TITLE
Increase size of .body

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#429]
## Updating an existing style

**1. What element/ style is being changed?**
The body copy of the Foundation Site 

**2. Why it is needed?**

There have been at least two instances where the body copy has been interpreted as too small. 

1. For the Privacy Included work, the Internet Health Report team preferred the blog pages because it had a larger text for reading. 

2. [One user at MozFest](https://docs.google.com/spreadsheets/d/1QAUZ4KHlygLbz4oLGt1zXoFtyPPEHfdXkfrE3ISwyq8/edit?usp=sharing)(a youth!) noted that the typeface is too small. 

**To do:**
  - [ ] Post proposed brand update in Redpen (for desktop, tablet, mobile)
  - [ ] Request design review from design team via R+/R- in Github ticket
  - [ ] Get feedback from devs

**After Approval:**
  - [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

## Design Reviewer Checklist
_An issue template in github_
**For design review:**
  - [ ] Is this change justified or are we able to use existing brand elements?
  - [ ] Is the development time viable?
  - [ ] Provide an R+ or R- in the ticket
  - [ ] List reasons for approving or denying changes

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by sabrinang** [comment]
Exploring this .body size issue: 
- comparing an increase by 2px = 18px _(to keep with even measurements and still less than body large that is 20px)_ 
- comparing 400 and 300 font weight _(body large uses 300 compared to our body copy 400)_

I'm taking screenshots for comparison and using pages from foundation.mozilla.org and privacynotincluded.org as examples: https://redpen.io/p/bz6ab062f30893cb10

**Comment by sabrinang** [comment]
**Note:** I'll need to continue to examine anchor links and dark theme versions as well as all type proportions as I believe our defined styles are relative measurements 1rem (currently 16px) as well as to ensure that everything looks balanced together in scale (body small may look visually even smaller etc.)

/cc @mmmavis I'll be consulting you some time next week as I have questions before getting to far

**Comment by sabrinang** [comment]
Consider 2px increase for all body (body small, body, body large)

**Comment by sabrinang** [comment]
**Text Style Sketch Library Updates to Style Guide.sketch file**
- Mobile typography unchanged
- Desktop changes only because body large on mobile is 18/27 (increasing mobile body will be equal to mobile body-large)
- body was 16/24 and updated to 18/27 / dark mode updated too
- button labels was 16/20 and updated to 18/22 / dark mode updated too
- body-links and cta-link was 16/24 and updated to 18/27 / dark mode updated too

**Comment by sabrinang** [comment]
Created dev ticket here: https://github.com/mozilla/foundation.mozilla.org/issues/4158
Redpen updated: https://redpen.io/cg793b57e89f97b5f6
Closing this design issue.

**Comment by kristinashu** [comment]
Yay!
