### ISSUE TITLE
Diagram our overarching design process

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#43]
Should include:
* Design brief
* User research
* User testing
* Design QA
* Handshake process
* where to design reviews take place

**Comment by cassiemc** [comment]
@xmatthewx you interested in this one? feel free to take it if you have the bandwidth.

**Comment by xmatthewx** [comment]
Yes. I'll take a stab at this.

**Comment by cassiemc** [comment]
@xmatthewx any updates?

**Comment by xmatthewx** [comment]
No progress here. Slightly concerned about creating something truly useful, but haven't had time to dig into this yet.

**Comment by cassiemc** [comment]
Moving to the next heartbeat.

**Comment by xmatthewx** [comment]
This requires a bit more thought and scoping by me. I was going to post the text below, but I think it might be nonsense. 

> I've thought about this and how it connects to my draft chapter: https://github.com/xmatthewx/Mofo-Design-Handbook/tree/master/Process

> I'm concerned about investing too much in a complicated diagram that will either be too simple or too complicated, uninformative or too prescriptive and unrealistic. 

> Solution: the design brief checklist is solid and usable distillation of this stuff. It deliberately includes all the major process touchpoints.  

Unlikely to be done by July 31.

**Comment by cassiemc** [comment]
Moving to the next milestone. Let's discuss / triage when I'm back from PTO.

**Comment by cassiemc** [comment]
What I really want from this is a process map that:
* Shows what our process looks like for new designers who are joining or contracting with us
* Shows PMs what a good design process looks like, so they can help support and reinforce it
* Links to resources for each step in the process. So if I'm stuck on a project, I can find my place again and quickly get started again by using supporting docs. ie. design brief, QA checklist. I want a visual way to find those docs quickly based on knowing where I am in a project.

Found a couple examples of related tasks, thought it could be handy. Map could be linking out to deeper resources if necessary (different bugs than this).

![design-brief-process-v3-lowres](https://cloud.githubusercontent.com/assets/1186326/8959062/accca2d2-35d6-11e5-95b8-e089a9f4d1fe.png)
![heartbeat-diagram-v5](https://cloud.githubusercontent.com/assets/1186326/8959113/fde4f854-35d6-11e5-81af-2a591bd4d01e.png)

**Comment by xmatthewx** [comment]
Diagram should reflect [process chapter in wiki](https://github.com/MozillaFoundation/Design/wiki/Process). Diagram should [initially be quick and simple](https://github.com/MozillaFoundation/Design/issues/58) to first make sure it's actually useful.

**Comment by cassiemc** [comment]
Didn't get to this in this heartbeat. Moving to the next.

**Comment by cassiemc** [comment]
No way this is going to happen with the Chicago Report hanging over me! Moving to the backlog.

**Comment by cassiemc** [comment]
This seems like something we could do in #110. Closing this for now as won't-fix, it's clearly not gotten any love recently.
