### ISSUE TITLE
Major Givings AI Postcard

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#431]
**Proposed deadline:** Nov 20 (is this the print deadline?)

**Print specs:** needed

**From Jesse W**
I would like some postcard (approximately) sized cards that highlight our major giving program and can be handed out at events. These will help increase donation conversion rates for our major giving prospects and educate people about our key initiatives. The cards need to have professional looking design elements on the front and back so that people find them interesting to read and  easy to take with them. Ideally, each card would take up 1/4 of a page so that they are easy to print on card stock and cut to size at an office or home office.

**Copy doc** https://docs.google.com/document/d/11NfYDnmgaV1OLqn30cY-vzdvAq19uDfsHDOkuFpTV1I/edit?usp=sharing 

cc @sabrinang can you please link to any relevant past work?

**Comment by sabrinang** [comment]
Major gift google doc: https://github.com/MozillaFoundation/Design/issues/391#issuecomment-519727304

**Comment by taisdesouzalessa** [comment]
Had a chat with Jesse and completed [the design brief](https://docs.google.com/document/d/1R97y_w71d7qZCPeZ8fJSfdW15CqheMPqtf6gwkL-pXg/edit?usp=sharing)

Deadline by Nov 29th - they don't have a hard deadline but it would be good to have this done in a couple of weeks so they can send it with the holiday cards.

**Comment by kristinashu** [comment]
The Trustworthy AI email series is also probably relevant and more recent.

Ticket https://github.com/MozillaFoundation/Design/issues/412

Working files https://drive.google.com/open?id=14qs99ymIiUEJ9bF4C12urEvCZqeDN0cP&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by taisdesouzalessa** [comment]
I worked on 2 versions of this card - subtle differences (V2 is lighter than V1 and the shapes are cropped in another way)
v1 here: https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/394839409_front_v1
v2 here: https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/394839542_front_v2

**Next steps:** 
1. collect designers feedback
@kristinashu @sabrinang @natalieworth @beccaklam could you please send me some design feedback via InVision? 
2. once feedback is received, send to stakeholder

**Comment by taisdesouzalessa** [comment]
Final version here:
https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/395081703_Display-Shot

Front: https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/395081705_Info_Cards_AI_Front
Back: https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/395081704_Info_Cards_AI_Back

I will send those to Jesse via email to get feedback.

**Comment by taisdesouzalessa** [comment]
Copy was updated by Jesse and revised by Lotta.

Here is the new version:

**Front and back:** https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/396189702_Display-Shot-V2
**Front:** https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/396186695_Info_Cards_AI_V2_Front
**Back:** https://mozilla.invisionapp.com/share/Y6UZ5YIKRPH#/396186653_Info_Cards_AI_V2_Back

**Comment by taisdesouzalessa** [comment]
Here is the final layout:

**to print:** https://drive.google.com/file/d/1dIDVx8lCIG54zCVPhxcQ8zbaugojJety/view?usp=sharing

**digital files here** (to send via email, post online and so on): https://drive.google.com/drive/folders/1QBI5DBf9oFVqLxyvrcGthIM2s0VC0sVv?usp=sharing

**Comment by kristinashu** [comment]
w00t w00t 🎉
