### ISSUE TITLE
Video explainer

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#432]
Template for video lower third for some videos. 

@anilkanji to add more context.

**Comment by anilkanji** [comment]
Seeking graphic packaging/bumpers/elements for explainer videos.

* example bumper here: https://www.youtube.com/watch?v=M2mlWjSXT5w
* example of elements incorporated into video (rebecca ricks): https://blog.mozilla.org/internetcitizen/2018/03/23/rebecca-ricks-documenting-corporate-surveillance/

* FIRST EXPLAINER VIDEO rough cut: https://drive.google.com/file/d/1Nlw8yUCIyhktVjhCLneb1nWAMjX7zkwn/view

**Comment by kristinashu** [comment]
@natalieworth [here's a link to the interview doc](https://docs.google.com/document/d/1bCB4dorY2VjBC8KfL5p-QrAsoBbu7FgeSDWmCTI34XY/edit), please make a copy of this template, fill it in with Audrey, and make sure Lotta sees it so we know everyone is on the same page.

**Comment by natalieworth** [comment]
Started the [interview doc here](https://docs.google.com/document/d/13tGpew5FQrZxIsWK0vcwcPa9Z2D-yFWnveYjOuWMke8/edit?usp=sharing). It's quite rough but feel free to add to it (before I send to Lotta on Friday) 

cc @anilkanji @kristinashu and I sent to Audrey too.

**Comment by natalieworth** [comment]
Update:
Video with simple front and end bumpers/ idents is here: https://drive.google.com/file/d/129VNVqFNRv1SDV6JG3wzOnlPY4o73zuD/view?usp=sharing

Working folder is here: https://drive.google.com/drive/u/0/folders/1XKVOSGF0nqwDn5K5d_ZFqElQ9AyuQIrb

Still need to create the lower-thirds to introduce Noah and the project/ role.

**Comment by natalieworth** [comment]
Have added the lower thirds [option here (with beginning and end bumpers).](https://drive.google.com/open?id=1HpAONV8jP6OEdTK8u_ceSCmsdd4whePS)

cc @kristinashu @beccaklam @sabrinang @taisdesouzalessa @anilkanji  Let me know what you think! :)

**Comment by beccaklam** [comment]
It looks great @natalieworth ! So cool. Only feedback I have is on timing. Feels a _little_ slow in some parts (that last bit of the lower thirds phasing out). Could speed some parts of the animation up to make it feel more snappy?

**Comment by natalieworth** [comment]
> It looks great @natalieworth ! So cool. Only feedback I have is on timing. Feels a _little_ slow in some parts (that last bit of the lower thirds phasing out). Could speed some parts of the animation up to make it feel more snappy?

Thanks Becs! I've adjusted!

**Comment by natalieworth** [comment]
Adjust timing to be a bit faster on the lower thirds outro! https://drive.google.com/open?id=1kVCgZszXHArHz-dtikhnrmWFnAhYHU3e

**Comment by kristinashu** [comment]
So good Nat! I'll move this ticket to "blocked" column until you hear back from Lotta.

**Comment by natalieworth** [comment]
Heard back from Lotta and Audrey and have updated the latest version here https://drive.google.com/open?id=1C-KwauFE2yv937QSsIAFmc6pM_PUximN

Just awaiting second round of review on this, then will export/ package and upload to the drive!

**Comment by natalieworth** [comment]
Final [video is here](https://drive.google.com/open?id=1C-KwauFE2yv937QSsIAFmc6pM_PUximN)

Working [files/ assets](https://drive.google.com/open?id=1fOLNAu_PVJaXvzFGe2CR4_1vfr3dY5oK) (with the bumper and lower thirds) are here.

**Comment by natalieworth** [comment]
Sorry! I forgot about the bumper audio at the beginning. It is still an example file. Are we allowed to purchase for up to 1 million broadcast audience ($19). cc @Lottarao @anilkanji

**Comment by anilkanji** [comment]
Thanks for all the cool motiongraphics @natalieworth ! Looks great! Yes to licensing fee.

**Comment by natalieworth** [comment]
Purchased audio and have added to [Noah's interview video](https://drive.google.com/open?id=1_lRm6s7gXdoilEe8fxsab3uXKy0cP7FJ)!

Working files [are here](https://drive.google.com/open?id=173GaG23kjqzYegITG6G4rMKRf-HkdBvq) for future reference.

Done this one for now! :D
