### ISSUE TITLE
Gather analytics for PNI

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#438]
@taisdesouzalessa to add more context 😊

**Comment by taisdesouzalessa** [comment]
### Issue:
Create a Data Studio Dashboard for PNI

### Data points to consider:
• input from team [collected here](https://docs.google.com/document/d/1qHYtR5agZE8z5e8IRcl0BGa4PxSJEYM7y_xs7E_nCIw/edit?usp=sharing)
• think about other important points
• consider points from [Marketing Strategy](https://docs.google.com/document/d/13p3vd-dxqE26zBP6tVP1cBM2zY6b5IPvMsHmpEs4aBQ/edit?usp=sharing)

### Help: 
Ask for @arlissc and @mmmavis help to make sure this board is gathering the right data.

### Deadline: 
Nov 20th

**Comment by taisdesouzalessa** [comment]
V1.0 is ready! 
thanks to @arliss for offering her expert advice! 

**Considerations:**
1. Some people have "DO NOT TRACK" installed so we have to consider that not all of our audience is represented on this board.
2. Arliss will take a look at Newsletter Signup and Shares in our non GA platforms so we have a more accurate idea of the numbers (in GA, we are currently using proxis for it, like "Form Submit Tap" label).
3. This is a WIP, @mavis is doing some investigation there too and we can add more data as the team needs, just let us know what you would like to see.


Finally, the dashboard (it has 3 pages): https://datastudio.google.com/open/1P-8u-IWUNYs6Fi-KFZEWH8W0sKUKDBCF

**Next steps:** 
- Team feedback: anything else they would like to add? Any modification?
- Mavis to figure out if we can calculate conversion rate as requested by Gideon.

**Comment by taisdesouzalessa** [comment]
This project is done - we may have to add new metrics/modify the board as the team needs but the core of it is ready to go. If we need to add more features, we can create new tickets for it.

Findings from #444 will affect this board.
