### ISSUE TITLE
Gather analytics for YouTube Regrets

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#439]
@taisdesouzalessa to add more context 😊

**Comment by taisdesouzalessa** [comment]
### Issue:
Create a Data Studio Dashboard for YouTube Regrets Site

### Data points to consider:
• how many people signed up for newsletter from there
• think about other important points
• outside analytics, ask for Kevin's help on Communications data (shares, mentions on social media)

### Help: 
Ask for @arlissc and @mmmavis help to make sure this board is gathering the right data.

### Deadline: 
Nov 24th

**Comment by taisdesouzalessa** [comment]
**Dashboard** is here: https://datastudio.google.com/open/11x5Bqc01F9viRaiHV0ttjVp4mDvaU5Z2

**Next Steps:**
- Waiting on Arliss reply on Newsletter numbers (Salesforce)
- Feedback from @kristinashu - any other info needed?

**Comment by kristinashu** [comment]
Thank you, this is so great Tais! Were you able to get a sense of donations or shares?

**Comment by taisdesouzalessa** [comment]
I can take a look at both and add there. One thing to consider on them is that we only know a piece of the story: we know the person clicked on "donate" for instance. We don't know (once they go to Donate page) if they filled in their info and actually donated. Same for sharing, we know the click of the button but nothing else. Just want to make sure this is clear so we don't make assumptions :).

**Comment by kristinashu** [comment]
Have you asked Will about it? He might know some actual numbers? Would actually be good to know for PNI as well, if possible!

**Comment by taisdesouzalessa** [comment]
That is a good point :). I'll collect this data and send his way to see how close GA numbers are.

**Comment by kristinashu** [comment]
Thanks! In general, I think it will be interesting to know how things translate (clicks vs actual actions), both for newsletter signups and for donations.

**Comment by taisdesouzalessa** [comment]
Yep, I agree 👍 Arliss is taking a look at the signups in Salesforce. I'll connect with Will on Donations then.

**Comment by taisdesouzalessa** [comment]
Dashboard is ready https://datastudio.google.com/open/11x5Bqc01F9viRaiHV0ttjVp4mDvaU5Z2

By working on this project we found an issue that is now described here: #444
