### ISSUE TITLE
Ensure metrics are in place for build.webmaker.org/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#44]
This is really super simple, but needs to happen in order to do more complex measuring down the road. We are aiming to achieve:
* 100% increase in traffic
* 7+ unique visitors, return visits

**Comment by cassiemc** [comment]
This one has no owner yet and we are tight on resources this week. Moving to the next milestone.

**Comment by cassiemc** [comment]
@vazquez are you able to add this in? Would be happy to make a new analytics property if we need it. Let me know!

**Comment by vazquez** [comment]
@cassiemc - I don't have enough clearance to create an analytics property on Google Analytics. Could you create a new property? I can certainly add it in after that :)

**Comment by cassiemc** [comment]
Fab. I wasn't sure if Build already had analytics. Here is the tracking code: https://docs.google.com/a/mozilla.com/document/d/1WOoWKsvLB-tCo0O0g_2aMt7TAH6ojjoXqgeS47watJQ/edit?usp=sharing

**Comment by vazquez** [comment]
We are going to add Adam's https://github.com/mozilla/react-ga Google Analytics module to get this done.
