### ISSUE TITLE
Pre-roll ads - deadline Nov 27

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#441]
PNI graphic for short paid pre-roll ads on Youtube and Twitter.

Natalie to meet with Audrey for more context and then update this ticket.

**Comment by natalieworth** [comment]
[Preroll-Ad.zip](https://github.com/MozillaFoundation/Design/files/3893587/Preroll-Ad.zip)
 Most recent version of preroll-ad is in the .zip folder

**Comment by natalieworth** [comment]
Final pre-roll ad file is here: https://drive.google.com/drive/folders/1xTIhCEsuWxP6RRzvioXoDiZ1S7BFICFV?usp=sharing
