### ISSUE TITLE
Holiday card for donors

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#442]
Natalie to checkin with Jesse W about print and web specs and any additional info before starting on this.

From Jesse:
I would like some holiday cards that can be sent to our major donors and some prospects (both a print version and electronic version). This will serve as both donor cultivation of prospects and stewardship of existing donors and will help us secure more end of year donations while educating donors about some of our initiatives. The design can be very similar to the ones for the Privacy Not Included buyers guide.

Deadline: hoping to have it done by Nov 28

Copy [doc](https://docs.google.com/document/d/1SW_vDkui8N61rCJmGRZuTb_s8fqAlmsSYAANhfaCaFE/edit).

Would be great to reuse this look https://redpen.io/qf5e24a69524b2a8d9. Personally, I think it shouldn't be too Christmas-y so that it's inclusive to all our donors.

**Comment by natalieworth** [comment]
Final Print File is here: https://drive.google.com/open?id=1_qlfvTWohMmnBFArHSO_pptYYHtTbZq9
Assets are all in here: https://drive.google.com/drive/folders/1uTZby8RrmUQELt_IJ06bJ7C8acXoWXHA?usp=sharing
