### ISSUE TITLE
Slide deck for partners

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#443]
Jon is asking for some design help in explain advocacy work to partners in this slide deck. Sections that need an image are highlighted in yellow. Please have a quick chat with Jon before starting on this.

https://docs.google.com/presentation/d/12eTWmvpRpnn9S-2idxjRKM-bwDIgoxgpw6hR84LZTvY/edit?usp=sharing

Deadline: ideally Nov 29 but Dec 6 would be ok

**Comment by beccaklam** [comment]
Met with Jon this morning will begin this work today. Link to [meeting notes](https://docs.google.com/document/d/1hjI8WOrOt3WovmDUQ7oD5sQajLZNb_Z8LG2RLvSaTWM/edit?usp=sharing).

**Comment by beccaklam** [comment]
Graphics have been inserted, waiting for Jon's feedback.

**Comment by beccaklam** [comment]
Jon gave approval so this is done.
