### ISSUE TITLE
[Analytics] GA and Salesforce newsletter numbers match

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#444]
### Issue
After working together with Arliss on Google Data Studio we noticed a significant difference between Newsletter Sign up numbers in Salesforce and Google Analytics.

### Solution
We have to do some more exploration to figure out why the numbers don't match. 

We may involve Arliss and engineers on this project in order to take a deeper look on how we are collecting numbers in both platforms

@arlissc , feel free to add more context to this ticket.

@kristinashu - assigning you for triage but we also depend on Arliss availability for this work
cc: @gideonthomas

**Comment by gideonthomas** [comment]
Which one is more? Typically GA and CRM numbers should not match because so many people use DNT or ad blockers. If they did (or if GA was more), I would actually be worried that we're losing subscriptions.

**Comment by taisdesouzalessa** [comment]
GA has way more...we can talk about details in our retro today and we should connect with Arliss to work on that together. I agree with you the numbers won't match 100% but I feel there is a huge misalignment and we could do better by focusing on improving our data collecting processes :).

**Comment by kristinashu** [comment]
I thought we don't actually know what the Salesfoces numbers are. That we only know signups that happened from users who signed up by going directly to https://foundation.mozilla.org/campaigns/youtube-regrets but we don't know the number of signups from people who arrived at the site via https://mzl.la/youtuberegrets or https://mzl.la/2Vqk1lG or https://t.co/qe2T3QGAnZ or other shorted urls. Is that right? If so then we don't actually know which one is higher.

@alanmoo do you have any recommendation on what we can do on our end to make these numbers more accurate or easier for Arliss to track?

**Comment by taisdesouzalessa** [comment]
Yep, that is a good point, Kristina. I think having a sprint focused on tracking would be great, as Alan suggested. We should collaborate with Arliss on it. I feel we need a small team working on that for a sprint so we can all align and understand the issue better.
