### ISSUE TITLE
[Audience] Research and exploration

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#446]
### Background
After meeting with Anil, Gideon and Kristina, we decided to focus our effort on Audiences first because it is a broader concept that is currently a bottleneck for things like: adding Value Proposition to our page, effectively targeting campaigns, update IA of our site, customize user journeys and so on.

The first step on this project is research. 

**Questions the research is trying to answer:**
- What is the difference between target audience, buyer persona, ux persona? How do they relate and apply to our context?
- Who is our current audience? GA can help on that as well as some research.
- Considering the ToC, what types of audiences seem promising for us to target? And why?
- In which audiences we can have the most impact on (as Engagement team)?
- Consider more than one target audience: primary/secondary/tertiary

### Goal
To offer options of target audience for the Engagement team based on informed decisions.

### Process
-  Research about best practices around the process of figuring out target audience (other companies, online articles, books, research papers). 
-  Talk to Venetia and Jen about the subject and collect their thoughts.
-  Explore the Theory of Change as a starting point to figure out potential audiences
-  Write down a report with recommendations and reasoning behind them 
-  During steps 1-4 loop Anil and Gideon for input and insights. We can collaborate asynchronously in a doc.

### Deliverables
Write down a report with recommendations and reasoning behind them. The report will offer options of target audience for the Engagement team to explore.

cc: @gideonthomas @kristinashu @anilkanji @beccaklam

**Comment by taisdesouzalessa** [comment]
Phase 1 is now completed. Met with Anil and Gideon to present my findings.

The Deliverables are in [this folder](https://drive.google.com/drive/folders/1egf9UeBvE3cr1aHVKkCbh6RZfLHU7IGd?usp=sharing).

Closing this ticket and we can open new ones as we move this project forward.

@gideonthomas @kristinashu

**Comment by kristinashu** [comment]
Amazing Tais! Let's pick this up again in the new year!
