### ISSUE TITLE
Design & Content for frontdoor campaign test

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#447]
Original and long-term idea for the campaign is [here](https://docs.google.com/document/d/1QG6qe0lyMzYYFA5ZibqEkcbsNeiViG-y4npBzXCK_Hg/edit#heading=h.q2g7ah7tymg9).

Short-term goal for Dec 2019 is to run some quick and lean tests to inform some bigger plans we have for 2020, doc [here](https://docs.google.com/document/d/198E6NkEEzdjRRUkvLHgGMMJSA4_zhzC35zp2yAJtDOM/edit?ts=5de01e2d).

## Simplified user journey
Ad or media: Statement with button 
-> Links to Donate or Newsletter signup page 
-> [Standard](https://redpen.io/eq0f253e8d6da9700f) first email

## 1) Design & Content

**Week of Dec 9**
- Define key audiences _(Gideon, Jen, Jon)_
  - link to Tais audience work https://github.com/MozillaFoundation/Design/issues/446
  - refer to media/ad placements and countries 
- Define messaging _(Gideon, Jen, Jon)_
  - kick-off meeting (Anil to scheduled) 
  - make sure it's localizable  
  - finalize ad copy _(Jen)_
- Explore graphics direction _(Nat)_
- List of final asset dimensions _(Gideon)_

**Week of Dec 16**
- Newsletter signup landing page
  - anything else (social, press, blog...)
- Finalize, crop, localize, and export all assets _(All designers)_
- Make sure we're tracking analytics properly

## 2) Ad/Media Buy & Placement
- Anil, Gideon, and Jon
- At the same time but in a separate ticket [need link]

cc @anilkanji @gideonthomas @beccaklam @TheoChevalier

**Comment by kristinashu** [comment]
Update from Gideon:
- Initial copy is [here](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit?ts=5defd006)
- Copy still needs to be approved
- Jen is gather photos of people
- Gideon is working on a master Airtable with all the ad specs (dimensions, requirements, copy, languages)
  - rough idea of ad placements: Twitter ad, YouTube display ad, Reddit ad, Twitch ad, Out magazine digital ad)

I think next steps for design are:
- explore image treatment for photos
- explore layouts
  - Image only (text and link are separate)
  - Image with text in the image
  - Image with text in the image and a button
- once we have ad specs, stress test the smallest and the biggest ad sizes

**Comment by kristinashu** [comment]
Since we'll be using head shots and text, I wonder if we could re-use this mozfest speaker style https://redpen.io/p/zx91d236f07477e39f? cc @sabrinang @natalieworth @beccaklam 

![image](https://user-images.githubusercontent.com/1068783/70580469-c3939800-1b68-11ea-9d26-70dfc97ed1b0.png)
![image](https://user-images.githubusercontent.com/1068783/70580482-d1e1b400-1b68-11ea-8ba4-08e3cfceb48f.png)

**Comment by gideonthomas** [comment]
Copy for L10n on the way, but maybe let's start with English.

Final copy tracked - https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit

Signup and donation message required for each message group.

### Confirmed Media specs

#### Pride Media (needed by Dec 17th latest)
   - Details: https://www.pridemedia.com/ad-specs
   - Dimensions needed: 970x250, 728x90, 300x250, 300x600, and 320x50.
   - Max file size: 50kb
   - File type: .jpg/.png
   - Notes: Messages must be embedded in graphic
   - Message groups:
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.9picim78bs5r)


#### Twitter
   - Dimensions: use the same as PNI, otherwise specs are [here](https://marketing.twitter.com/na/en/solutions/ad-format-specs/promoted-tweet)
   - Note about the messages: I have commented on each message to indicate the text that needs to go in the image -- just one sentence. Otherwise, the rest of the text doesn't need to be in the image.
   - Message groups:
      - [EN, FR, DE](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.e7zir61bze6h)
      - [EN, FR, DE](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.e7rymzwytyt3)
      - [EN, DE](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.9picim78bs5r)
      - [EN, FR](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.5k22m6nyvzng)
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.1nboygl9zfk7)
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.2pvw26r4pvk7)

#### Youtube
   - Dimensions: I think let's do 300x250, 970x250, and 300x50
   - Max file size: 150kb
   - File type: .jpg/.png
   - Notes: Messages must be embedded in graphic
   - Message groups:
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.e7zir61bze6h)
      - [EN, FR](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.5k22m6nyvzng)
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.9picim78bs5r)
      - [EN, FR](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.2pvw26r4pvk7)

#### Reddit
   - Details: https://www.reddithelp.com/en/categories/advertising/creating-ads/ad-unit-specifications
   - Dimensions:
        - 400x300, 4:3, 500kb max size
        - 1200x628, 1.91:1, 3mb max size
   - File type: .png/.jpg
   - Notes: Message does not need to be embedded in the graphic
   - Message groups:
      - [EN, DE](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.e7zir61bze6h)

#### Pinterest
   - Dimensions: 1000x1500, 2:3, 32mb max size
   - File type: .png/.jpg
   - Notes: Ideally, like twitter, that one sentence goes into the graphic.
   - Message groups:
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.2pvw26r4pvk7)

### Unconfirmed Media specs

#### Daily Kos
   - Dimensions: Awaiting info
   - Notes: Messages must be embedded in graphic
   - Message groups: 
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.1nboygl9zfk7)

#### National Geographic
   - Details: https://www.nationalgeographic.com/mediakit/assets/img/downloads/2019/2019_Advertising_Specs.pdf
   - Dimensions needed: 970x250, 300x250, and 320x50 (50kb max for the last one)
   - File size: 200kb max except the last size.
   - File type: .png/.jpg
   - Notes: 
      - Messages must be embedded in graphic
      - All ads must have a visible 1x1 pixel border; banner corners cannot be rounded
   - Message groups:
      - [EN only](https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit#bookmark=id.e7rymzwytyt3)

**Comment by kristinashu** [comment]
Thank you Gideon for putting this together! This is a lot!

Versions at 320x50 will not be possible with embedded text so we won't be able to do those.

Do you have the profile photos?

I think we should start with the Pride Media ones since that has the tightest deadline. Will ping @beccaklam and @natalieworth to see who has time either today or Monday.

**Comment by gideonthomas** [comment]
Let's not do 320x50. I'm collecting photos in https://drive.google.com/drive/u/0/folders/1B2qTr6XLyQcOwTWHSZ_axlH_LF_2wgsp

Pride media photos should be in the drive since it's just me.

**Comment by TheoChevalier** [comment]
l10n update: I should receive FR/DE translations tomorrow (Tuesday) morning PST time. I’ll post them here and on Slack

**Comment by gideonthomas** [comment]
Update -- all photos collected.

**Comment by beccaklam** [comment]
@gideonthomas Here are the assets for Pride Media: https://drive.google.com/open?id=10buzc8vE0jT056bWZb6a0AZmHjoDeVmQ

**Comment by beccaklam** [comment]
@kristinashu Here are the files I've started for this on the drive: https://drive.google.com/drive/folders/1nY-MdkLJekHxE0ArwsfwfLK-TVHSL3hm?usp=sharing

**Comment by kristinashu** [comment]
Ok it took a while to find the best way to reduce the files sizes to less than 50kb. I simplified the background pattern a bunch and used Photoshop's Save-for-Web feature to get each image as close to 50kb as possible.

@gideonthomas the images are in Drive [here](https://drive.google.com/open?id=1CzLYETRxZtf5FOPqh7oXkm7-Cu8OKfCI).

@beccaklam all the files are in Drive [here](https://drive.google.com/open?id=1nY-MdkLJekHxE0ArwsfwfLK-TVHSL3hm).

**Comment by gideonthomas** [comment]
Thank you so much @kristinashu! Pride media submitted.

**Comment by TheoChevalier** [comment]
Hi there, we have FR/DE translations!
FR: https://docs.google.com/document/d/16tzYU76uYXadXlBhML4P-O2xJVfH_oai7wZKDyewfl8/edit?usp=sharing
DE: https://docs.google.com/document/d/1rQt7BSVZnBtygRhGQxsWJIsl4Oqe7fmeLnw5NRD0pUg/edit?usp=sharing

Unfortunately some translations are too long for Twitter, despite the length limits being sent to the vendor, I will try to get them fix this by tomorrow…

**Comment by beccaklam** [comment]
Thanks @TheoChevalier!

@gideonthomas Twitter is done with the final exports here: https://drive.google.com/open?id=1fJ0Qgl7d1G46gL0_cQrOD1q1DIRaltAS

**Comment by kristinashu** [comment]
@gideonthomas here are the graphics for YouTube https://redpen.io/p/pka760d8c68e6ddc06. Text is pretty tight on some of the 300x250 ads, any chance some of the copy can be reduced? I still need to reduce the files size on these to below 150kb but will do that once they've been finalized.

**Comment by gideonthomas** [comment]
@kristinashu commented in the long text graphic on redpen.

@beccaklam -- one small change -- most of the copy in the image stays the same across different audiences. The only ones that are different are: https://docs.google.com/document/d/1n9TrzwNEhIj6RdW8pr3Xfg8O7s_PhWrFd6geZmPrRVk/edit?disco=AAAAEDtViVk (for Jen and Hilary) and the one that Theo mentioned about Alizee being a volunteer.

**Comment by beccaklam** [comment]
@gideonthomas Ok, the Twitter images have been updated!

**Comment by beccaklam** [comment]
@gideonthomas reddit images added: https://drive.google.com/open?id=1WPhF1Z9rTz-mLu61b6ucO5x3QB1yVP9l I'm also updated the checklist with links to the completed images as well.

**Comment by beccaklam** [comment]
@gideonthomas pinterest image here: https://drive.google.com/open?id=1CjGfOtDm-uP4LK9xnowz8DX1gF4T5fvU

**Comment by kristinashu** [comment]
@gideonthomas updated and compressed youtube images are here: https://drive.google.com/drive/folders/1H0-SRAR_X08oi8Ferdep_XwMYTyEU0XY?usp=sharing

**Comment by beccaklam** [comment]
@gideonthomas Twitch images are here: https://drive.google.com/open?id=1mY5ZeBvRwv5x9xEfqUJEjQcvvIM01GiF

**Comment by beccaklam** [comment]
@gideonthomas Daily Kos images are here: https://drive.google.com/open?id=1JftIkAIlWNmIo3clzPjzuxCKmDroiYjl

**Comment by beccaklam** [comment]
This should be done after @gideonthomas has reviewed all the assets. cc: @kristinashu

**Comment by gideonthomas** [comment]
I think most of them look good @beccaklam and @kristinashu! Thank you for doing it so quickly.

@beccaklam I noticed that some of the french twitter assets don't have the right translations in them -- any chance you can update them? Specifically:
1. climate-FR should say: Je travaille chez Mozilla et nous avons besoin de gens comme vous.
2. girl-gamer-FR and non-binary-gamer-FR should say: Je travaille chez Mozilla et je veux faire en sorte qu’Internet et la culture du gaming ne soient plus accaparés par les hommes.
3. privacy-FR should say: Je travaille chez Mozilla et nous avons besoin de gens comme vous.

**Comment by beccaklam** [comment]
@gideonthomas Okay I've updated all the ones you mentioned above plus the privacy german one. Sorry about that, and thanks for catching those! No worries about Twitch.

**Comment by gideonthomas** [comment]
Thanks @beccaklam! Looks great!

**Comment by beccaklam** [comment]
@gideonthomas Is this good to close then?

**Comment by gideonthomas** [comment]
Yes, thanks @beccaklam!
