### ISSUE TITLE
Board slide updates - deadline Dec 11

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#449]
Deadline: Dec 11

Sarah W has requested some update and improvements to one board recruitment slide titled "MoFo Board Candidate Profile". Original slides are here https://blog.lizardwrangler.com/2016/06/14/expanding-mozillas-boards/.

@sabrinang to meet with Sarah Thursday to discuss her needs before starting to work on them.

**Comment by sabrinang** [comment]
I met with Sarah W earlier today and I've referenced the [old MoFo Board Candidate Profile slide](https://1yhd4l3kqqrh3lvuxk1m6ixu-wpengine.netdna-ssl.com/files/2016/06/Board-Recruitment-MoFo-Board-Profile-1.jpg) and created an updated version that matches the board deck style and is editable here (on slide 39): https://docs.google.com/presentation/d/1_eD6G8vCYoQPcia3iJ6XuPNP18NTXTbvV4toUJ03r0g/edit?usp=sharing

I will slack her the link to review as I don't know her github handle.

**Comment by sabrinang** [comment]
Sarah reviewed on slack and it is good to go!

**Comment by kristinashu** [comment]
Sweet!
