### ISSUE TITLE
Design UX templates

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#45]
Would love to keep a set of templates on build.webmaker.org/design for us and contributors to grab as needed, so that when anyone sees a piece of UX work it screams "I am UX!" Off the top of my head, I see a limited text and color palette with a set grid. Similar to architectural drawings.

@xmatthewx Can you own this? We can adjust the milestone for this as needed but for now, because we have a UX contributor at the table, I'm going to mark it July 31.

- [ ] Mobile file
- [ ] Tablet file
- [ ] Desktop file
- [ ] each of the above in svg (or another universal format? would like to avoid duplicating sketch, psd and illustrator files if possible)
- [ ] should include headlines, image boxes, illustration placeholder, buttons, lists, etc.
- [ ] we can benchmark other omnigraffle starter kits for reference on the types of elements we'll need

**Comment by cassiemc** [comment]
Glad you are owning this @sabrinang! Looking forward to seeing what you can do here.

**Comment by xmatthewx** [comment]
thanks @sabrinang! Glad to discuss how to make these as useful as possible before you dive in if you want. 

I'd like to take advantage of the symbols for common elements. That will mean using sketch and illustrator. I also think that a single file that places devices side by side will help us think more about responsive from the get go.

**Comment by cassiemc** [comment]
Update @sabrinang ?
Symbols are a good idea. Would love to see some progress on some actual reference documents. We can start with Sketch and mobile (or desktop, since that might be more practical for Webmaker atm), if it's easier to narrow the scope.

**Comment by cassiemc** [comment]
@sabrinang Update? I know you already have a couple tasks this heartbeat so we can either swap with @flukeout (who doesn't have anything in this repo this heartbeat), or assign to the following one. 

Thoughts @flukeout @sabrinang?

**Comment by sabrinang** [comment]
I'll be doing the social templates first before I get to this one - If @flukeout has some time this heartbeat it would be great if he can take this over.

**Comment by cassiemc** [comment]
Resassigning to @flukeout - Luke let me know if you think this is too much.

**Comment by cassiemc** [comment]
@flukeout update?

**Comment by cassiemc** [comment]
@flukeout :bell:

**Comment by cassiemc** [comment]
@flukeout :bell: 

Updating the milestone.

**Comment by flukeout** [comment]
Currently updating the work started by @xmatthewx with some template UI elements...

![image](https://cloud.githubusercontent.com/assets/25212/10143009/8da216e6-65db-11e5-98b6-f6a70459bd9c.png)

**Comment by flukeout** [comment]
Screenshot of some recent work...

![image](https://cloud.githubusercontent.com/assets/25212/10382827/e6ac3880-6ddc-11e5-85b3-24fcca1acf09.png)

**Comment by cassiemc** [comment]
Nice! This is exactly what we're after. Thanks @flukeout

**Comment by cassiemc** [comment]
@flukeout Are these linked to from build/design? If not, we should file a follow-up ticket. And I think we should close this unless there's anything else that needs doing immediately.

**Comment by cassiemc** [comment]
Closing. Followup ticket filed #114
