### ISSUE TITLE
[Brand] Research and User Interviews

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#450]
### Intro
To start the research phase of the brand project, we want to conduct some internal staff interviews to gather qualitative insight and feedback on the Mozilla Foundation brand.

### Goal
To gain insight and involve staff early in the branding project.

This will inform how we structure our content, features, process and collaboration. We will observe how they perceive the brand system and it will help us understand current processes, onboarding, expectations, pain points, bottlenecks, ideals and ideas. We can also collect any related resources and tools currently being used as well.

### Process
- Prepare any related brand materials/brief to share as context
- Research interview practices
- Generate list of possible interviewees
- Prepare set of interview questions and doc
- Review and feedback on questions
- Schedule calls
- Report back findings and document

### Related Issues
Brand Brief: https://github.com/MozillaFoundation/Design/issues/445
Brand Planning Outline: https://github.com/MozillaFoundation/Design/issues/427

cc: @kristinashu @natalieworth @anilkanji

**Comment by Pomax** [comment]
@sabrinang do we want to keep this one open, or does it make sense to close/file new issues for the various parts that we might still want to follow up on?

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
