### ISSUE TITLE
[Brand] IA and Sitemap Proposal

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#452]
### Intro
From the knowledge we gather from our research, user interviews #450 and audits #451, we can start synthesizing our findings to inform our content structure for the brand system in the form of IA/Sitemap proposal.

### Goal
To produce a draft that outlines how we want to structure the content for the central brand home.

### Process
- Synthesize research and produce IA proposal
- Create sitemap draft to visualize hierarchy on website
- Review and gather feedback from collaborators
- Revise and refine

### Related Issues
Brand Brief: https://github.com/MozillaFoundation/Design/issues/445
Brand Planning Outline: https://github.com/MozillaFoundation/Design/issues/427

cc: @kristinashu @natalieworth @anilkanji

**Comment by sabrinang** [comment]
Adding pages/draft pages for the Identity section of the proposed IA on wagtail: https://foundation.mozilla.org/en/docs/brand/
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2492510/72490187-5f996a80-37cb-11ea-81f1-e454a8386946.png">


Extended brand IA draft idea on abstract: https://share.goabstract.com/14014136-00a7-4a0a-b999-13c132f8d78d?mode=design&sha=fa805ac6cef47eb4bf1024c0846137890c71b6d7
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2492510/72490087-fe719700-37ca-11ea-8785-a8ea7dffc3a0.png">

**Comment by sabrinang** [comment]
Adding draft pages such as Expression, Photograph, Imagery, Pattern & Texture, UI components, UX artifacts.

@natalieworth I worked on adding images to the gallery example for Expression so far, it is currently live and feel free to edit/revise: https://foundation.mozilla.org/en/docs/brand/design/expression/

![Screenshot_2020-01-15 Expression](https://user-images.githubusercontent.com/2492510/72490530-47761b00-37cc-11ea-9f0c-093d4947b29f.jpg)

**Comment by sabrinang** [comment]
The IA proposal idea is seen as the vertical navigation in design file in abstract. Draft pages in wagtail will build out these sections as we go and we currently will focus on the visual identity section.

This proposal has been done independent of knowledge from user research/interviews #450 but we will gather feedback and recommendations from users then and can use this as a point of reference and starting point for the research/discussion. After we gather the findings and feedback, we can revise and refine this evolving piece with collaborators. The IA work can continue with our research in #450

**Comment by kristinashu** [comment]
⭐ super star ⭐
