### ISSUE TITLE
Instagram strategy

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#453]
**Deadline: Dec 20**

### Documents 
Jen's original brief [doc](https://docs.google.com/document/d/1bPNKLDEivv6YZv_o32964bfd9RhoAzz2ikGA4TA2tTU/edit).

Natalie's WIP combined strategy [doc](https://docs.google.com/document/d/1kCqjVwCpTXDAYpi70Fn6xfEr6wY8Nsa-BcnatN4MFH0/edit).

- [x] [Audrey's ppt ](https://drive.google.com/open?id=1JKnh6_uGzCz3LeDgyHGIBAsvLYH0qR-o)
- [x] [Nat to add master note doc](https://drive.google.com/open?id=1fOv7WiNZ2WViEmCkZH84EuCANnc8UWswU6TOl-FncTY) _(Natalie)_
- [x] Nat to set up stands twice a week (Jen, Audrey, Nat, Sabrina) _(Natalie)_
- [x] Slack communication _(Natalie to create channel)_

### Use the account
From #420 
- [x] Anil to get log in
- [x] Designers to get log in access _(Natalie)_
- [x] Switch account to Natalie _(Natalie)_
- [x] Start testing out some post on Instagram
- [x] Consider account verified check-mark _(Natalie working with Audrey and Gideon)_ **Audrey has sent information and address to Instagram—so waiting to hear back about this in new year.
- [x] Consider a business account
- [ :( ] Access to Buffer the post schedule app _(Natalie)_ *There are only a limited number of seats/ Anil is the only person with access right now 

### Stats, analytics, and KRs 
From #411 (and related to KR 1.3)
- [x] Audrey to share screen caps of all analytics _(Sabrina to ask Audrey)_ (Google Drive folder here: https://drive.google.com/open?id=1bJmv8asEGyDJM0sGD-8RfQsYxNv4HC0W&authuser=sabrina@mozillafoundation.org&usp=drive_fs)
- [x] Add existing baseline numbers to ![How We Measure](https://docs.google.com/presentation/d/1oAave-1pzUWkDho9DCctz2r7LKcRCfOiw6zy7c4lXcQ/edit?usp=sharing) _(Sabrina)_
- [x] Determine how we gather info for dashboard (manually put in numbers on slide or screenshots)  _(Sabrina)_
- [x] Determine which activities we measure and how  _(Sabrina)_
- [x] Set up and analyze our activities (instagram insight, promote, scheduler etc.)  _(Sabrina)_

### Define our style and post types 
From #389
- [x] [Benchmarks](https://docs.google.com/presentation/d/1jUWU5j7yR2JWt0ZnVgLg4J5pbw0i9V9awEADgdH8wHQ/edit#slide=id.g5d0cf22a88_0_0) _(Natalie)_ Pinterest [doc here](https://www.pinterest.ca/nataliejworth/moz-instagram/) 
- [x] Visual style for potential posts https://redpen.io/p/rvfdd4560c2fb38b57 _(Natalie)_

### Finalize strategy
[Natalie's WIP strategy doc](https://docs.google.com/document/d/1kCqjVwCpTXDAYpi70Fn6xfEr6wY8Nsa-BcnatN4MFH0/edit).
- [x] Jen & Audrey to finalize "Platforms & Content Strategy" content  _(Natalie)_
- [x] Sabrina to finalize "Business Goals & KPIS"  _(Sabrina but blocked)_ Audrey was able to help us define new goals and KPIs from the business account metrics on [slide 5](https://docs.google.com/presentation/d/1OIrXGRCvwDXybAM6K2cZi9fyIQfe6kdItoT3FcP5TC4/edit#slide=id.g7ac800a1cb_0_166).
- [x] Guidelines for visual style _(Natalie & Sabrina)_ *Set up rough outline for this with Sabrina [here](https://docs.google.com/document/d/1tdSDEyRAPLemZf3AQ2A4gAHFYmIF9KNYOfF6koHpU7U/edit?usp=sharing)
- [x] Share with Anil for feedback _(Natalie)_ *Shared the Strategy google doc with Anil in December/ before break.

Going to set up a new ticket for these tickets to go over strategy presentation with the Instagram team in 2020 in #460 :
- [ ] Finalize strategy _(Natalie)_
- [ ] Socialize strategy _(Natalie)_

**Comment by sabrinang** [comment]
**Stats, analytics and KR updates**

- I’ve created a folder _Instagram > Insights & Metrics_ and made a folder with screencaps from Audrey with the date it was captured. I plan to continuing organizing and uploading them here: https://drive.google.com/open?id=1bJmv8asEGyDJM0sGD-8RfQsYxNv4HC0W&authuser=sabrina@mozillafoundation.org&usp=drive_fs
- Added numbers with screenshots to [How We Measure](https://docs.google.com/presentation/d/1oAave-1pzUWkDho9DCctz2r7LKcRCfOiw6zy7c4lXcQ/edit#slide=id.g5e79b44cc4_0_5)
- Ideas for activities we want to measure for future stretch goals (with Instagram Business Insights):
    - improve female ratio
    - improve follower growth
    - improve interactions
- I have logged in successfully via Natalie’s email now so I can analyze our activities via Instagram Insights

**Comment by natalieworth** [comment]
Update:
I'm consolidating all of our strategies, content, benchmarks, and examples posts into a strategy proposal [doc here](https://docs.google.com/presentation/d/1OIrXGRCvwDXybAM6K2cZi9fyIQfe6kdItoT3FcP5TC4/edit?usp=sharing) for 2020 when we return.

Going to work on adding the visual assets for the remainder of the day.

**Comment by natalieworth** [comment]
I have moved left over items and things to follow up on in 2020 to #460
