### ISSUE TITLE
PNI marketing: graphics for fitness blog post

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#454]
https://docs.google.com/document/d/1-xN3vTGcDtTgP8o0u5H25ahKzhi31nWIRXJ4xQ2O7nQ/edit?ts=5dee80e4

**Comment by kristinashu** [comment]
Draft is here https://foundation.mozilla.org/cms/pages/686/edit/. @natalieworth could you please double check the images to R+ this?

**Comment by natalieworth** [comment]
Nice! R+ @kristinashu

**Comment by kristinashu** [comment]
Thanks!
