### ISSUE TITLE
2019 Recap deck

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#455]
It's that time of year again! Here's the deck we can start to populate it https://docs.google.com/presentation/d/1R-UjWmyPSHd1dvaT2OXIa2Soj10CqG3bhCxNYkbSQmo/edit?usp=sharing

We can work on it async but could also meet for an hour this Friday or next Friday and all work on it together. Let's add visuals but also try to write a sentence on the value and impact the work had.

cc: @sabrinang @natalieworth @taisdesouzalessa @beccaklam

**Comment by taisdesouzalessa** [comment]
How will we share this work within the company? We could have a highlight video with the main projects and metrics with a link for the full report. That would be cool!

**Comment by gideonthomas** [comment]
@kristinashu this needs a milestone update

**Comment by kristinashu** [comment]
We will be linking to his as part of our [creative colab page](https://foundation.mozilla.org/en/docs/process/work-us/) which will be shared the all staff this week.
