### ISSUE TITLE
Request: consider adding a new ".btn-link" style for buttons

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/Design#456]
(Please feel free to edit my ticket. The "Brand Update Checklist" issue template is too overwhelming for a dev to fill out. So I went free form instead. 😂 )

---

Hi friends,

For our next style guide update, can we consider adding a new button style for **buttons** that styled like hyperlinks?

### Some technical context:

We want to write semantic HTML so that our site is easy for both human and non-human (search engine, assistive technology etc) to read and parse info from. In semantic HTML, anchor tag `<a>` should only be used for hyperlinks. Other controls should be implemented using the `<button>` HTML tag and currently, our style guide only has 3 official styles for buttons -- `.btn-primary`, `btn-secondary`, and `.btn-pop`.

#### Pulse Edit New Profile Modal (`I'll do this later` control)

e.g., https://www.mozillapulse.org/?edit_new_profile=true

<img width="607" alt="image" src="https://user-images.githubusercontent.com/2896608/70759102-09cc3100-1cfa-11ea-8909-a6c3ecf56fe9.png">

#### PNI Product Page (`copy & share link` control)

e.g., https://foundation.mozilla.org/en/privacynotincluded/products/harry-potter-kano-coding-kit/

<img width="482" alt="image" src="https://user-images.githubusercontent.com/2896608/70759318-d6d66d00-1cfa-11ea-97e3-a89890f914d5.png">

#### PNI Product Page, Voting Section, Signup Screen (`CLOSE` control) (currently being implemented)

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2896608/70759950-e6ef4c00-1cfc-11ea-92d9-630099691c67.png">

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
