### ISSUE TITLE
PNI marketing: graphic for Ring doorbell

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#458]
There was a last minute request for a graphic for this blog post https://docs.google.com/document/d/1u7sxsZNWdD38id5V7ktJjyx3NpH6ucXljfLSW5O1dD8/edit

Here's a comp https://redpen.io/p/wp55c515c43857dee4

Working file are here https://drive.google.com/drive/folders/1Afey0qm9KIsFtyOolsv-aUoCwLZsTcDp?usp=sharing

I was user of what colors to use because it's for PNI but there's also another Ring Doorbell campaign going out at the same time https://github.com/MozillaFoundation/Design/issues/457. The original purple was nice so I just stuck with that.

![Google Home copy 3@2x-100](https://user-images.githubusercontent.com/1068783/70761643-bca08d00-1d02-11ea-9ce0-9fdfa55067c0.jpg)

@beccaklam please make any improvements to the graphic you can think of. I did it really quickly and there's a lot of text. I think this is going out tomorrow morning so Amy or Anil might ping you for some updates. Thank you and sorry.

cc: @natalieworth

**Comment by natalieworth** [comment]
Adding the link for email/ petition graphic options here https://drive.google.com/drive/folders/1zpl9XkTLH3WKyqeUvCzWy4dB6BU790aX?usp=sharing

**Comment by beccaklam** [comment]
@kristinashu @natalieworth I simplified the graphic to match more of the previous illustration style, let me know what you think! https://redpen.io/npbdc1e68ff684c57e Anil is just contacting me now about cop changes.

**Comment by kristinashu** [comment]
Thank you both!!!

**Comment by beccaklam** [comment]
Final graphic that I sent to Anil:
![Ring@2x-100](https://user-images.githubusercontent.com/20977376/70821406-017eff00-1da9-11ea-99be-e9eb0432c7bc.jpg)
@kristinashu is this done?
