### ISSUE TITLE
Updates to voice assistant graphic

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#459]
Update images in https://foundation.mozilla.org/en/campaigns/how-opt-out-human-review-your-voice-assistant-recordings/

Copy doc https://docs.google.com/document/d/1vckyBUBfePDL9YP_vvzX_M3eYoKoVeZWWAFz9qdQtnQ/edit

Note of where copy updates should be https://redpen.io/p/ny1532827ff26fd1ef

@beccaklam are there only a dedicated graphics of Alexa and Google, and not one for Siri (only the group image)?

**Comment by beccaklam** [comment]
@kristinashu Yes, there is no dedicated graphic for Siri.

**Comment by kristinashu** [comment]
Updated the graphics and make an Apple one https://redpen.io/p/ny1532827ff26fd1ef

**Comment by kristinashu** [comment]
Post has been updated https://foundation.mozilla.org/en/campaigns/how-opt-out-human-review-your-voice-assistant-recordings/

@TheoChevalier I can update the DE and FR versions if you have updated copy!

**Comment by TheoChevalier** [comment]
Thanks @kristinashu ! I had no idea this was happening, so I just exposed strings now: https://github.com/mozilla-l10n/engagement-l10n/commit/26ee4a5a57b321d5c57e945bfa1cd9302e5eee1c

I’ll take care of French shortly and post an update here

**Comment by TheoChevalier** [comment]
@kristinashu French and German translations are live! https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2019/voice_assistants_graphics.lang&action=translate&show

Two notes:
- Step 2 for Alexa has been updated in French (the UI has changed), while English stayed the same
- Waiting some confirmation from Becca R for Alexa step 3, as I see two different toggles in French, and I’m not sure what should say to people. Depending on what she says, I’ll probably have to update step 3

**Comment by kristinashu** [comment]
Thank you @TheoChevalier! I've updated all the graphics and will update the Alexa version once you have that new copy. Please review them here https://redpen.io/p/ny1532827ff26fd1ef.

**Comment by TheoChevalier** [comment]
Thanks Kristina! Here are my updates:

- Left a few comments in Red Pen
- Siri graphic in German is missing
- French translations have been updated for Alexa (German might be there by the time you see this comment) https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2019/voice_assistants_graphics.lang&action=translate&show

**Comment by TheoChevalier** [comment]
German is in https://github.com/mozilla-l10n/engagement-l10n/commit/9b6b0387c8e66dc370ad286cff8d2afa6be0d989

**Comment by kristinashu** [comment]
Thank you @TheoChevalier! All the updates should be there now https://redpen.io/p/ny1532827ff26fd1ef. 

All the jpgs are also in Drive here https://drive.google.com/drive/folders/14h4B1kbx2Z_Z2CDB77hswL6xmQhgKDWS?usp=sharing.
