### ISSUE TITLE
UX/UI annotation practices

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#46]
Draft UX annotation practices. To discuss with @flukeout.

**Comment by xmatthewx** [comment]
# Webmaker project viewer

Notes for consistent build across Android and browser, touch device and desktop. 

![project-viewer](https://cloud.githubusercontent.com/assets/53411/8558099/fd89f0f2-24cf-11e5-80c5-6c180ee7c941.png)

**Comment by xmatthewx** [comment]
# Webmaker page viewer

Notes for consistent build across Android and browser, touch device and desktop. 

![page-viewer](https://cloud.githubusercontent.com/assets/53411/8558129/2e7f495a-24d0-11e5-9f9d-da406beb221d.png)

**Comment by xmatthewx** [comment]
Notes on images updated above:
 - posting multiple comments to organize material & for easy linking
 - posting as image, including date on header
 - #ff00ff for annotations
 - using [gesture symbols](http://www.google.com/design/spec/patterns/gestures.html) to reduce copy
 - placing comments inline
 - referencing minimal notes only when necessary
 - fira sans everywhere

**Comment by flukeout** [comment]
Here's my attempt at FTU, but it feels like a different type of document.
https://dl.dropboxusercontent.com/u/109902/tiles/ftu-editing.pdf

I suggest we lower the opacity to 40% on the lines.

**Comment by cassiemc** [comment]
This doesn't feel like a UX design, rather it feels like documentation guidelines. Have I mistaken this issue @xmatthewx? Not sure how it relates to #45.

I think the header can be improved – H1, H2, H3s. I prefer inline notes rather than having to visually connect labels with footnotes.

I liked the style @flukeout has been working with in Thimble notes: https://redpen.io/wo889e2e3abea83b34 and also what @vazquez did with the guidelines: https://github.com/mozilla/webmaker-browser/issues/79 Something about the white on dark makes it feel more like a behind-the-scenes comment.

**Comment by xmatthewx** [comment]
I changed the title of this issue. Twice! It's about how we annotate things for the build. 

I like the Thimble notes and promo guidelines as well. I think they are too stylized for our effort to generalize things. 

Here are some goals for our annotations:
 - standardized - for easier reading by others
 - flexible - so they can adapt to particular projects
 - lightweight - so they can be made quickly for big projects and small tasks
 - modular - so they can posted as a comments for agile iteration in github

Lastly, I'd like to consider this a perpetual work in progress. We should keep this simple and  improve these as we use 'em.

**Comment by xmatthewx** [comment]
A couple more goals for our annotations:
 - brevity - brief, inline notes are best whenever possible
 - comprehensive - anything unspecified is a debt we will repay with interest:
  - responsive
  - interactions
  - transitions
  - loading
  - error states
  - edge cases

cc @lovegushwa @sabrinang @vazquez

**Comment by xmatthewx** [comment]
> Lower the opacity to 40% on the lines.
> Use a more legible date format - August 2, 2015
> Increase the font size of the small black titles above screens (which I forgot to include, btw) 

Agreed. 

What if you divided your doc into a few pages (or gh comments). Use the white on black header to replace your pink headers (such as FTU: User edits a page). Lengthier notes are probably better in dark gray, saving fuscia for inline notes.

**Comment by flukeout** [comment]
Here's an attempt at the quicker add-a-photo flow for Webmaker.
Full PDF - https://dl.dropboxusercontent.com/u/109902/tiles/camera-flow-simplified.pdf

![image](https://cloud.githubusercontent.com/assets/25212/8579374/0db17970-2569-11e5-85a0-6aabf8bac3f3.png)

**Comment by xmatthewx** [comment]
A little cleaner? 

![project-viewer](https://cloud.githubusercontent.com/assets/53411/8583173/92cf1d62-2599-11e5-9f3f-5335b406b970.png)

**Comment by flukeout** [comment]
@xmatthewx Yeah, def!

**Comment by xmatthewx** [comment]
>pan

You could add arrows as needed. Although, the icon is for the gesture swipe/drag. Panning is the result. 

> line + label alignment 

Noted

> black behind screen titles

It's a pain in Sketch too. Might be worth it for visibility. Might not. 

Here's a nicer header and simplified reference:

![annotations](https://cloud.githubusercontent.com/assets/53411/8600409/d6f8be4a-2633-11e5-899b-c7d1378a69b7.png)

**Comment by xmatthewx** [comment]
Solid progress. Deliverables:
- [ ] sketch template
- [ ] illustrator template

eps tempalte won't allow us to use symbols that will be very useful for this.

**Comment by cassiemc** [comment]
Much progress has been made here! Can we wrap this one up and close it off, @xmatthewx ? We can file a new issue to link to it from Build. Or just add the files to Drive.

**Comment by xmatthewx** [comment]
Working template files are now on gDrive in the Annotation folder under Templates and Guidelines, alredy nicely linked from build.
