### ISSUE TITLE
Instagram Strategy Presentation Doc

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#460]
### Intro

Continuing the Instagram work started in 2019 (#453) , I am consolidating our brief, strategy, and Audrey's powerpoint into a google doc to share out and get feedback on our Instagram strategy for 2020. 

The [working deck is here (WIP)](https://drive.google.com/open?id=1OIrXGRCvwDXybAM6K2cZi9fyIQfe6kdItoT3FcP5TC4).

Things to follow up on in January 2020:
- [x] Consider account verified check-mark _(Natalie working with Audrey and Gideon)_ 
- [x] Finalize strategy _(Natalie)_
- [x] Metrics/ Analytic tracking _(Natalie/ Sabrina)_
*Create post schedule _(Natalie)_TBD after we track and review our first posts. I'll probably need help from Audrey on this too when she comes back after all hands.
- [x] Continue visual guidelines for Instagram _(Natalie/ Sabrina)_

cc: @kristinashu @sabrinang @natalieworth @caltrider

**Comment by natalieworth** [comment]
Most recent version of the deck is here: https://docs.google.com/presentation/d/1OIrXGRCvwDXybAM6K2cZi9fyIQfe6kdItoT3FcP5TC4/edit#slide=id.g25275a8168_1_627

**Comment by natalieworth** [comment]
*Blocked/ need to meet with the instagram team next week to go over everything and create our schedule.

**Comment by kristinashu** [comment]
@natalieworth @sabrinang is this almost done? What's left to do?

**Comment by natalieworth** [comment]
[Final doc is here](https://docs.google.com/presentation/d/1OIrXGRCvwDXybAM6K2cZi9fyIQfe6kdItoT3FcP5TC4/edit?usp=sharing). I've added in updated relevant analytics Sabs, but feel free to change or add more. :D 

cc @kristinashu @sabrinang
