### ISSUE TITLE
Mockup for All Hands Plenary: Privacy Not Included 2025 - Due Wed Jan 22

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#461]
**Deadline: Wed Jan 22**

**Kick off meeting: Mon 20**

From Kevin:

Mark Surman has requested a custom image for his presentation at the Jan. 28 MoCo All Hands plenary.

Specifically: Mark will imagine what an AI-focused 2025 version of *Privacy Not Included will look like. He'd like an image -- a marketing poster, a web page mock-up, etc. -- to illustrate this. 

I've pasted the relevant portion of his script below for inspiration:

As AI is folded into more consumer products, devices will gather more and more personal data -- and make more and more decisions for us and about us. Smart speakers will become smarter, yes, but the privacy and security stakes will get higher, too

The world needs more work that empowers consumers and scrutinizes manufacturers. So we’re going to keep publishing *Privacy Not Included 

In the 2019 edition, we already examined lots of products with AI-powered features. For example: Facebook Portal and Google Nest Max use face and object tracking. And all the voice assistants in the guide are powered by AI 

It’s easy to imagine how our grading rubric might evolve in 2020 -- we might ask questions like, “Are some of the features of this device powered by AI?” Or, “Will the data collected from this device be used to train a model?”

But let’s look a bit deeper into the future. What might Mozilla’s 2025 *Privacy Not Included guide look like? What AI-powered products will be in it, and what questions will we ask? 

Maybe we’ll ask, “Can the latest Amazon Echo its owners voice? And, does it need to get your explicit permission each time it does this?” Or, “Can Facebook Portal 5 infer when you’re happy and when you’re depressed? And who does it share that information with?” 

Maybe the guide will feature reviews of personal AIs: digital assistants that aren’t controlled by Amazon and Google, but rather used by consumers to interact with corporate AIs, and put the user’s well-being first. These AI might be built and sold by fiduciaries -- maybe Mozilla! -- and could filter out misinformation, guard our personal data, swat away invasive ads, and spot algorithmic discrimination 

Richard Whitt, a Mozilla Fellow, is thinking about products just like this, and how the market could actually support personal, ethical AI assistants. Richard says Jarvis from “Iron Man” may not be too far-fetched

**Comment by natalieworth** [comment]
Adding that the deck needs some edits and Mark is also wanting the 3 PNI products updated to show their futures in 2025 in addition to the graphic. Deadline also was moved by MoCo to Wednesday (tomorrow). [Deck draft/ copy is here](https://docs.google.com/presentation/d/1Do4QPrMRDkR-zdOkS601JB4zxgWHCW8tPStv1GP4wJ0/edit?usp=sharing). Most of the slides need graphics updating/ everything is placeholder.

cc @kristinashu
