### ISSUE TITLE
All Hands plenary slides

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#465]
Do a quick design pass of the plenary slides.

https://docs.google.com/presentation/d/1Do4QPrMRDkR-zdOkS601JB4zxgWHCW8tPStv1GP4wJ0/edit?usp=sharing

**Comment by kristinashu** [comment]
@natalieworth are you able to do this? Seems like you're more in the loop and have some time???

**Comment by kristinashu** [comment]
@natalieworth did Kevin mention this to you? He just opened a request to have a design review all the mofo speaker slides (so not just Mark's but also the fellows who are speaking). Would you be ok with doing this as well?

**Summary of requests**
- Design pass [of all the slide](https://docs.google.com/presentation/d/1wOx9CeXxU1H-3vLdjEwRd1RuJphfiVRqKhGIJd1lnFE/edit#slide=id.g473d95022b_0_220) on Monday, January 27 once all the content is in
- Go to the rehearsal on Tuesday, January 28 from 6:30pm - 8pm (I think we can say no to this since it conflicts with the dine around) 
- Update any tweaks on Tuesday eve

**Everything from Kevin**

The morning of Wednesday, Jan. 29 at All Hands will be the MoFo plenary. Mark Surman is emcee, and there are four speakers.

We're currently collecting speakers' slides. Once that's complete, Mark has requested a designer to review the full slide deck. No original design content is needed; instead, we need a sharp eye to polish and format slides, tweak text, etc.

I plan to have all slides by Monday, January 27. It would also be helpful if a designer could attend a portion of the plenary rehearsal on Tuesday, January 28 from 6:30pm - 8pm, to finalize any last-minute input from Mark. 

cc @gideonthomas

**Comment by natalieworth** [comment]
@kristinashu Yes! I can for sure do!
