### ISSUE TITLE
[Brand] Create and Publish Identity Pages

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#466]
### Intro
From the IA proposal https://github.com/MozillaFoundation/Design/issues/452, we have a draft of the visual identity section for brand. We want to create content for these pages and gather existing resources so they are discoverable and documented. We will publish them live so we have a reference point of what we intend to create for the central brand home on wagtail.

### Goal
To publish and populate the visual identity section of the brand page. This includes:
- [x] Identity (Parent Page) #481 
- [x] Photography
- [x] Illustration
- [x] Pattern & Texture
- [x] UI Components
- [x] UX Artifacts #472 

We will revise and refine as we review and gather feedback from collaborators.

### Related/Reference Issues
Brand Brief: https://github.com/MozillaFoundation/Design/issues/445
Brand Planning Outline: https://github.com/MozillaFoundation/Design/issues/427
Brand IA Proposal: https://github.com/MozillaFoundation/Design/issues/452

cc @kristinashu @natalieworth

**Comment by sabrinang** [comment]
@natalieworth Fill out and gather content for the Illustration section of identity brand pages.

**Comment by kristinashu** [comment]
Do you both think you'll be able to finish this this sprint, aka by EOD Monday?

**Comment by natalieworth** [comment]
@sabrinang I added the illustration points to the [Wagtail](https://foundation.mozilla.org/cms/pages/716/edit/) and I've also created a refined asset .ai file (based on the foundation brand + some of the most popular assets that we have been using for illustrations based on your MozFest style guide. I've added it to [Redpen here](https://redpen.io/qj5d293c1db66b155b). 

We can talk/ meet when you're back on Monday?

**Comment by natalieworth** [comment]
@sabrinang Also got a start on the [pattern/ texture page](https://foundation.mozilla.org/cms/pages/717/edit/preview/)

We can meet when you're back on Monday :)

**Comment by xmatthewx** [comment]
This documentation is awesome. 

Small suggestion: let's put Templates and Process toward the top of the nav, since it's the most important stuff for non-design staff.

**Comment by natalieworth** [comment]
Hey @sabrinang I updated the [illustration page based on our tahttps://foundation.mozilla.org/cms/pages/716/edit/lks](). Let me know if you have anymore suggestions :)

**Comment by sabrinang** [comment]
Pattern & Texture page is made into a section on Illustration page. Illustration, Photography and UI Component pages published. The UX artifact page is privately published under Process section now as work in progress of the research pages issue https://github.com/MozillaFoundation/Design/issues/472 as the work will continue there. 

I filed a separate issue for the Identity parent page https://github.com/MozillaFoundation/Design/issues/481 Ideally, this could just be a heading in the nav to denote the section and doesn’t need to be a page but will work on putting context on the separate issue to close this meta ticket.
