### ISSUE TITLE
Matrix Design and Template for Instagram

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#467]
### Intro
Create a Mozilla matrix template to use weekly/ monthly on Instagram.

**Comment by kristinashu** [comment]
@natalieworth can you please add an estimate to this?

**Comment by natalieworth** [comment]
Most recent iterations for these are here: https://redpen.io/p/xa6b3e7e1946fc93c7
But pausing this until we talk more about it on Monday :)

**Comment by natalieworth** [comment]
Final Beat design is here! https://redpen.io/ys2a55083bbff8caac

Template (.ai) [file for this is here](https://drive.google.com/open?id=1Fs8HfD1c8shI7jl_i-WRCCjLpV7zbB_A) 

We're going to do a test post this week and see how it performs :) and tweak based on that. Closing this issue for now.
