### ISSUE TITLE
Instagram Brainstorming and Post Planning

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#470]
Brainstorming with Audrey this week (in person) on Instagram weekly and monthly posts.

**Comment by kristinashu** [comment]
How's this coming along?

**Comment by natalieworth** [comment]
Updates:
- Instagram meetings are now 45 minutes on Monday to accommodate for a longer brainstorm session and short check-in stands on Thursday. 
- We got the first Matrix off and are hoping to do 1 per week
- On Monday (after work week), we'll resume our brainstorm for non-news related posts.


More notes/ ideas can be [found in our huddle doc](https://docs.google.com/document/d/1fOv7WiNZ2WViEmCkZH84EuCANnc8UWswU6TOl-FncTY/edit).
