### ISSUE TITLE
[Brand] Position and Communications

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#471]
### Intro
After chatting with Lotta at all hands, we plan to check-in and coordinate how to create and add brand positioning and communications content on to the brand wagtail docs.

### Goal
To publish and populate the positioning section of the brand page. This IA and content is dependent on what Lotta has created and collected.

### Process
- Meetings every 2 weeks with Lotta to coordinate
- Guide Lotta to create/update content on wagtail
- Review and gather feedback from collaborators
- Revise, refine and publish

### Related Issues
Brand Brief: https://github.com/MozillaFoundation/Design/issues/445
Brand Planning Outline: https://github.com/MozillaFoundation/Design/issues/427

cc: @kristinashu @natalieworth @Lottarao

**Comment by kristinashu** [comment]
We met with Lotta and Sabrina has set up a bi-weekly meeting for the three of us. Work for this sprint is done and we can continue the work in this ticket - https://github.com/MozillaFoundation/Design/issues/497.
