### ISSUE TITLE
Improving Stakeholder Interview Cheat Sheet 

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#474]
See if any improvements can be made to the [Stakeholder Interview Cheat Sheet](https://docs.google.com/document/d/1bCB4dorY2VjBC8KfL5p-QrAsoBbu7FgeSDWmCTI34XY/edit?usp=sharing)

- [x] Interview Kaili, a frequent collaborator on this cheat sheet, to see if any part of the interview can be improved 
- [x] Make improvements to cheat sheet

**Comment by beccaklam** [comment]
Notes from meeting with Kaili: https://docs.google.com/document/d/1nwSJ-hv8-rikrhs6MxVhISqKQORD04altwsjgPOX1Do/edit?usp=sharing

**Comment by beccaklam** [comment]
Edited the stakeholder interview cheat sheet to make the "Release Date" portion more discussion-like. 

Also added a "Collaboration/Brainstorm Minute" to highlight collaboration and provide a moment for brainstorming within the interview. I may need to refine this question. I'll show this at crit this week and if all goes well will close this ticket!

**Comment by kristinashu** [comment]
Copy updates are great! But style wise, can you please update it to our template https://docs.google.com/document/d/1PTdSrNA7-2LiTmAISEOzWmPEhUZvbDPjaYp2-JFc8T8/edit?

**Comment by beccaklam** [comment]
Changed template and shared with design team at crit. This is done for now!
