### ISSUE TITLE
Style Guide for MozFest 2020: Part I

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#475]
Create one slide deck with links to the working files. See full list of deliverables in [Project Brief.](https://docs.google.com/document/d/1VWB85eRkoOIdUTgiJ6iaTLkM_3ncX_jUggvJJuMnJbQ/edit#heading=h.3yg45s8xm4qj)

### Goals for this Sprint
- [x] Festival Narrative
- [x] Visual Direction
- [x] Lockup (Logo, Wordmark) 
- [x] Typography 
- [x] Colour 
- [x] Iconography 

### Goals for next Sprint (#483)
- Textures, Patterns & Art Accents 
- Imagery (illustrative and photographic examples)
- Guidelines for working open, blog post/brand doc ref on open design

**Comment by kristinashu** [comment]
Sabrina and I met with Sarah and are all on the same page! This is unblocked.

**Comment by sabrinang** [comment]
Style guide for MozFest 2020 resources created:

**Google Slide** https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit?usp=sharing

**Google Drive Folder** https://drive.google.com/open?id=18hovyS3uDAc4JuxqEr1IwCzclzdVf4az&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Adobe CC Library** https://adobe.ly/2HSiPBE
_______

Narrative
- Text was taken from on of the AI theory of change [ama docs](https://drive.google.com/file/d/1VB0iSEqjMjOzRDxy4TL18-TdUmwh0dFl/view?usp=sharing) for context and placed in the speaker notes section of the slides _(to be reviewed/revised)_

Visual Direction + Moodboard
- Describes approach, adjectives and visual examples of direction
- Describes the inspiration and visual metaphors behind the direction
- Application examples from photos and link to flickr in speaker notes

Lockups
- ai/svg/png updated and exported to google drive and adobe cc library
- Removed house lockups

Colour
- ai/ase updated exported to google drive and adobe cc library
- Adjusted tints/shades/gradients 
- Updated focused colour palette

Typography
- Aligned Barlow to Nunito Sans
- Google font web links included and in adobe cc library

Iconography
- ai updated to include past examples or space icons/grid/style
- svg/png exported of 5 issue area icons in google drive and adobe cc library
- Incorporated extended documentation of MoFo UI iconography and link to sketch file

Will continue style guide WIP pages in #483 and lockup usage will be part working open guidelines work. I'll track any further revisions to the style guide in part II issue as well.

**Comment by kristinashu** [comment]
Yay so awesome @sabrinang! Very organized and also looks incredible. Such a nice evolution of the brand.
