### ISSUE TITLE
Instagram Shareable Stats

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#477]
### Intro

**Share Stats**
- Make instagram analytics shareable so it accessible for the broader team _(slack, slide etc.)_
- Make it visible as a design and decision making support tool

**Tools**
- Learn if we are still using Buffer (or other social media tools) and what it can do
- Learn what stats we can get from it _(twitter or other?)_

**Comment by sabrinang** [comment]
cc/ @natalieworth

**Comment by natalieworth** [comment]
@sabrinang So I talked to Audrey and Buffer doesn't provide stats (or at least with the plan that we have). It's more for scheduling posts. For now though I've created a [google sheet](https://docs.google.com/spreadsheets/d/1Upoh2AjMpGMn0bWRuCwDfFUZ1XCpHnAPcrVVzS77IJ4/edit?usp=sharing) (it's free :D) to track our 2020 goals and growth.

**Comment by kristinashu** [comment]
Cross posting with this ticket https://github.com/MozillaFoundation/Design/issues/426#issuecomment-589160381

From Nat:
> I've set up a [google sheet data doc](https://docs.google.com/spreadsheets/d/1Upoh2AjMpGMn0bWRuCwDfFUZ1XCpHnAPcrVVzS77IJ4/edit?usp=sharing) to track our Instagram OKR goals for 2020. For now, it's free, easy to share, easy to use, and only uses the lean data from the Instagram platform—but once we grow bigger it could be good to possibly look into something paid (maybe in 2021)?

**Comment by kristinashu** [comment]
Awesome looking sheet!

**Comment by natalieworth** [comment]
I think good to close this ticket for now?
