### ISSUE TITLE
[Brand] Social Media Identity Guideline Pages on Wagtail

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#478]
### Intro

Coordinate with @natalieworth on how to create and add social media guideline content and pages to the brand wagtail docs.

### Goal
To publish and populate social media guidelines to the content or process sections of the brand doc.

### Process
- collect or create content
- create drafts for review and gather feedback from collaborators (Audrey and Jen)
- revise, refine and publish

### Related Issues
Brand Brief: https://github.com/MozillaFoundation/Design/issues/445
Brand Planning Outline: https://github.com/MozillaFoundation/Design/issues/427

**Comment by natalieworth** [comment]
I've started a google doc for the Social Media brand guidelines. I still want to run it past Audrey and Jen, but [posting/ documenting here for now](https://docs.google.com/document/d/1S3gh0ZE2kzskOGTjP7PLjfXYNhQGrF0QhKRbN764YsA/edit?usp=sharing).

**Comment by natalieworth** [comment]
I know @sabrinang is out this week, but I've added what I have so [far to wagtail](https://foundation.mozilla.org/cms/pages/793/edit/)

Going to meet with Jen/ Audrey tomorrow for our stand and hopefully also run it by them either this week or next Monday.

**Comment by sabrinang** [comment]
Overall @natalieworth  this is really good at providing more context to social channels and branded/external type posts!

I have some suggestions and ideas on things we could include that could be useful reference:

**Social Media Brand Voice**
- I know that content team has put together that really awesome [2020 Org-Wide Content Strategy](https://docs.google.com/document/d/1aXW5vfkhDmdo6UbIsNdFYwSG1ZFfcnemQh-TbQ9pn9M/edit?usp=sharing) gdoc and it contains great insight to voice/tone/stats/audience that could inform social brand voice. Could that be shared or is it still WIP? I think calling out some version of the text could be useful for alignment

**Sharing on Social**
- If staff and collaborators want to post or broadcast to their own networks, are their any hashtag guidelines, sample posts or guidelines that could inform how they promote us or our initiatives on their own social networks? (example: like the [MozFest Comms Cheat Sheet](https://docs.google.com/document/d/1g4VrFRHjT1zlf_iaYYarLqOvz0LMstWJnfCOsR7KCDs/edit?usp=sharing) is handy to align community voices too and I wonder if there is something similar MoFo wide)
- Perhaps including sample images for thumbnail and link shares (like simple Mozilla word mark) could be useful too

**Social Post Types and Formatting**
- Describe what the post types we use (feed, stories, video, gif etc.) and/or examples (like News Beat)
- Any best practices or tip links for each (how much text, text size, when/where to use lockup, margins, tags etc.)
- Template for dimensions and exporting standards (use case: if another foundation designer picks up social for an initiative to promote they can use same file to start)

**Social Stats**
- Link to [instagram stat sheet](https://docs.google.com/spreadsheets/d/1Upoh2AjMpGMn0bWRuCwDfFUZ1XCpHnAPcrVVzS77IJ4/edit?usp=sharing)
- [2020 Org-Wide Content Strategy](https://docs.google.com/document/d/1aXW5vfkhDmdo6UbIsNdFYwSG1ZFfcnemQh-TbQ9pn9M/edit?usp=sharing) also has some stats

**Collaboration**
It isn't entirely clear how staff can contribute or collaborate with potential requests. It may be helpful on describing what they can expect and what the content team may be looking for.
- What is the best way for the content team to be reached? (slack channel or other contact info)
- What is the preferred method to take in requests or process? (is their a queue or calendar)

**Other**
- For links to Firefox social media, I think we should link to [https://www.mozilla.org/en-US/firefox/](https://www.mozilla.org/en-US/firefox/) directly, not mozilla.org

___________
The _Social Post Types and Formatting_  stuff is designy so we can consider that but I think it would be good to go over the rest of ideas with Content Team as most of it is content based.

**Comment by natalieworth** [comment]
I'll run this by Audrey/ Jen since they'll be responsible for the copy. So going to leave this ticket open for now and meet with them next week for this.

**Comment by natalieworth** [comment]
Also changing this to 8 estimate. Taking a bit longer than expected and talking to Jen and Audrey about their process/ adding it will take a bit of time to figure out.

**Comment by sabrinang** [comment]
I filed a separate issue for content guidelines here: https://github.com/MozillaFoundation/Design/issues/528

For this issue, the feedback that applies to identity is now: 

**Sharing on Social**
- Perhaps including sample images for thumbnail and link shares (like simple Mozilla wordmark image) could be useful too

**Social Post Types and Formatting**
- Describe what the post types we use (feed, stories, video, gif etc.) and/or examples (like News Beat)
- Any best practices or tip links for each (how much text, text size, when/where to use lockup, margins, tags etc.)
- Template for dimensions and exporting standards (use case: if another foundation designer picks up social for an initiative to promote they can use same file to start)

**Comment by sabrinang** [comment]
Note: on stand today, there was mention of stories that will be reposted by partners/community and how can we should put watermark/logo and frame start/end of posts (case study: zoom stories). 

This can be useful to include in guidelines for stories (how sections could be screenshotted or distributed should contain mozilla branding or handle)

**Comment by kristinashu** [comment]
@nancyt1 will cover this as part of https://github.com/MozillaFoundation/Design/issues/998
