### ISSUE TITLE
*WIP* - Contributor Task - Usertesting Video Review - 

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#48]
![task-force](https://cloud.githubusercontent.com/assets/25212/8605547/e4c5ca84-263a-11e5-98b9-31b3dd787fca.png)

## Welcome, UX Recruit
Thank you for volunteering for the UX Video Task Force! We've recently got our hands on some top-secret, classified video of someone using the new code editor we're working on, [Thimble](http://bramble.mofostaging.net). This video was hard to obtain, and we believe that it is full of valuable information we can use to make Thimble even better.

**Your mission, if you choose to accept it..**
...is to watch the video we've obtained, make detailed and careful observations and report your findings.

**Why is this important?**
Watching people use our products is one of the best ways to see if we're meeting their needs. Based on what we see, we can determine if the changes we've made are helping our users. We can also identify other of improvement for the future.

**What you'll learn**
* The role of user observation in product development
* How the usertesting.com service works
* How to translate observations into actionable tickets & feature requests
* How to file issues and contribute to Mozilla products in Github
* How awesome user observation is

**Reading**
Check out some of these articles to help you along your way.
* ...

## Ready, GO!
Now that you've been briefed, it's time to get started. Follow the steps below to complete your assignment.

**Follow these Steps**
* Familiarize yourself with the [Thimble Editor](http://bramble.mofostaging.net)
* Read over the script that the user in the video will be performing
  * You can also see the tasks on the right side of the video player
* Watch one of the videos
  * https://www.usertesting.com/videos/7G01FCy9egMkyjajgbYYFg
  * https://www.usertesting.com/videos/-5pqNnpTm2y3c3PdOBxJCQ
  * https://www.usertesting.com/videos/O3ZeciLzTXur_PB245HufA
  * https://www.usertesting.com/videos/hzx3CbnwanUwIij9V8v8Yg
  * https://www.usertesting.com/videos/8Tux0p49gCoLD3kg30TqRA
 * https://www.usertesting.com/videos/t-cDhAT6lavtU51v7rIRdg
  * https://www.usertesting.com/videos/l2w6h9-v5N1aBa8MOqMYmg
  * https://www.usertesting.com/videos/kHhr5NLSk7rxO8F9B6Kwzw
* While watching, make notes about...
  * What the user liked & disliked
  * Which tasks were easy to complete and which were difficult
  * Things the user thought should be different
  * Which tasks could be made clearer or explained better
* Summarize your findings and add them to a [new issue](https://github.com/mozilla/thimble.webmaker.org/issues/new)
  * Here's a [sample issue](https://github.com/MozillaFoundation/Mofo-Design/issues/49) you can use for reference
 * Add the **feedback** label to it

**Need help?**
* Drop by the #webmaker channel on irc.mozilla.org
* Tweet us [@MozTeach](https://twitter.com/MozTeach)

**What next?**
Once you've filed your issue, one of our team members will review it and help you prioritize your findings and create issues that our team can begin work on.

**Comment by xmatthewx** [comment]
This is excellent. Very excited to test this out. 

 - It'd be helpful to have an example review, or a few sample notes. 
 - Might suggest they include timestamp as they take notes.
 - "Keep the notes objective. You can add a summary of your perspective at the end." 

Ideally two volunteers view each video so that we can validate the observations easily. In fact, we should launch a site called usertestingviewer.com where anonymous people from around the world take notes on usertesting.com videos...

**Comment by cassiemc** [comment]
Some good thinking here. Not sure what is actionable though. I am going to close this, and suggest @flukeout @xmatthewx if you don't want to lose it, perhaps you document it in the design repo wiki.
