### ISSUE TITLE
MozFest city announcement graphics

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#480]
Request from @marcwalsh:

> A reusable image / design that we can use for both the announcement and follow up engagements (like an AMA) after we've shared details of the new city.

> Our initial ideas are something similar to either the office stickers or a stylised skyline - that is in keeping with the MozFest design. But it would include options to have text as a header / footer / caption for dates / text etc.

> If this is posted publicly please do not include the name of the city in what is shared.

[Link to spreadsheet.](https://docs.google.com/spreadsheets/d/1e4c3YoAVeLwIpFumAER7Lh5ZXKt8IhDwSZOPB_zhvyA/edit?ts=5e4d3565#gid=0)

Initial ideas are a graphic cropped for:
- Twitter (1200 x 628)
- Instagram (1080 x 1080)
- Email (1280x660)
- Blog (1400x600)
- Press Release (TBC)
- ~Website homepage~ will use video instead

@sabrinang and I to meet with @marcwalsh before starting this work to get a better understanding of what assets are needed.

**Comment by kristinashu** [comment]
Sabrina will be working on this today and will share out her first version this afternoon for feedback from the design team and Marc.

**Comment by natalieworth** [comment]
Me and Kristina's working file for this is [here for reference](https://drive.google.com/open?id=13czAkSdc8zxEoxQgu7M6bc6f4-gCsg_p).

**Comment by natalieworth** [comment]
Final files for [these are here](https://drive.google.com/drive/folders/15qWIlGBDjpa4l0TVLE7SI6ZgiB014anO?usp=sharing)

cc @marcwalsh @kristinashu
