### ISSUE TITLE
MozFest website graphics and video

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#482]
Based on - Style Guide for MozFest 2020 #475, the website will need a new homepage background graphic and X number banner graphic for the secondary pages.

Ideally, this coincides with the launch of - MozFest city announcement graphics #480 

[Link to spreadsheet.](https://docs.google.com/spreadsheets/d/1e4c3YoAVeLwIpFumAER7Lh5ZXKt8IhDwSZOPB_zhvyA/edit?ts=5e4d3565#gid=0)

@sabrinang and I to meet with @marcwalsh before starting this work.

**Comment by kristinashu** [comment]
Looks like this ticket should be more about creating the background video rather than just graphics https://redpen.io/p/rhbb6e67da007091f2. 

@marcwalsh is gathering possible footage.

For accessibility reasons, @beccaklam is recommending footage should only have subtle movements.

@beccaklam or @natalieworth could work on this next week.

**Comment by kristinashu** [comment]
@natalieworth can work on this this week!

@marcwalsh should have some footage tomorrow.

**Comment by kristinashu** [comment]
@marcwalsh do you have some footage?

In the meantime Mavis is using this old video as a placeholder https://drive.google.com/open?id=1OPYaq_hyvnQbBBBUJw-O44SR_G6ac52o&authuser=sabrina@mozillafoundation.org&usp=drive_fs.

@natalieworth will you be able to work on this today? @mmmavis says the "MozFest homepage banner section already has a layer of gradient applied (using CSS). We can keep it if that makes it easier." Nat, what do you think? Is it easier for you to make the video with or without the gradient?

**Comment by mmmavis** [comment]
Note: We should try making the video size smaller to ease loading time. 🕐

**Comment by marcwalsh** [comment]
@kristinashu - the footage is in a folder on the [Footage Archive Team Drive](https://drive.google.com/drive/u/0/folders/17cQ9sf0d3cAXzZyKdPhcRoX-isD1OttF)

The previous video has a few shots which I think we should try to keep in. @natalieworth did you make this previously and still have the project files for it?

**Comment by mmmavis** [comment]
@natalieworth when you export the video, could you make sure its audio is removed (instead of volume 0 etc)? Most browsers have strict rules for autoplaying video with sound so we want to make sure our video is truly muted.

**Comment by mmmavis** [comment]
@natalieworth when you export the video, could you also export an image?

Reason: We should have a default image to show when the video is being loaded to the page. (Currently, we only see a layer of gradient). Pomax suggested grabbing the first frame of the video as the placeholder image and I thought that would work out great. @natalieworth thoughts?

**Comment by natalieworth** [comment]
@mmmavis I've [exported the final video and 3 still images](https://drive.google.com/drive/folders/1H0ZmMUWr3x78Ef92VBlnHhhdP-9gk61m?usp=sharing) options here.

My preference for the [still image is this one](https://drive.google.com/open?id=1IYdxcYUPvAmm33IgAlW1EHxRDBwOEmOv) (unless anyone else objects). :)

Thanks Mavis!
