### ISSUE TITLE
 Style Guide for MozFest 2020: Part II

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#483]
Follow up from https://github.com/MozillaFoundation/Design/issues/475

Deadline: March 13

[Project Brief](https://docs.google.com/document/d/1VWB85eRkoOIdUTgiJ6iaTLkM_3ncX_jUggvJJuMnJbQ/edit#heading=h.3yg45s8xm4qj)

### Goals for this Sprint
- [x] Textures, Patterns & Art Accents 
- [x] Imagery (illustrative and photographic examples)
- [ ] Guidelines for working open, blog post/brand doc ref on open design

cc @sabrinang

**Comment by kristinashu** [comment]
Website and social assets are almost ready for the city announcement. We've pushed back the deadline for this to March 13.

**Comment by sabrinang** [comment]
Updated https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit?usp=sharing with: 

- Imagery (illustrative, photographic and motion examples)
- Textures, Patterns & Art Accents (and .ai file)
- Collaboration notes (style guide and logo usage and process flow)

I messaged KGorr for feedback on comms/brand name and I will collect some working open/open design links to add to collaboration resource links slide. I can follow up on this Monday afternoon.

**Comment by sabrinang** [comment]
**Follow up from Friday:**

- @KGorr replied that she has some stuff to add to brand name usage/capitalization _(slide 39)_ 
- I added links to some open design references _(slide 41)_ and also asked KGorr if she has any working open reference links to feel free add as well
- The rest of the structure is ready; those slides are to be WIP to be reviewed/revised with additional content that she suggests or gives feedback on

**Comment by kristinashu** [comment]
Amazing! I think this ticket is good to close and then you can follow up with Kristina G in this ticket next sprint https://github.com/MozillaFoundation/Design/issues/489

**Comment by sabrinang** [comment]
Ok great, continuing on #489
