### ISSUE TITLE
Update /brand with latest MozFest assets

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#489]
Once the new style guide https://github.com/MozillaFoundation/Design/issues/483 is done we will need to update our /brand page. 

[need to add more info]

cc @sabrinang

**Comment by kristinashu** [comment]
Note: follow up on this note from Sabrina in https://github.com/MozillaFoundation/Design/issues/483

> I messaged KGorr for feedback on comms/brand name and I will collect some working open/open design links to add to collaboration resource links slide. I can follow up on this Monday afternoon.

[Link to style guide.](Updated https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit?usp=sharing)

**Comment by KGorr** [comment]
Just acknowledging that I am working on this. I have some content to contribute - waiting on Sarah's approval before sharing.

**Comment by sabrinang** [comment]
Updated [/docs/brand/](https://foundation.mozilla.org/en/docs/brand/) with MozFest links and corresponding assets:

    Logos
        - MozFest House lockups and logos removed
        - Updated MozFest 2021 lockup overview image and link
    Color
        - Adobe CC and Sketch palette files and links updated
        - MozFest colours, tints/shades, gradient image swatches updated
        - Fixed missing light red in Foundation colour palette image 
    Iconography
        - Included link to sketch file for reference
    Photography
        - Mozilla-Foundation_Portrait-Gradient-Filter-Template.psd file includes more MozFest-y filters in the layers as options
    Reference
        - Includes slide style guide 2021 link

**Comment by sabrinang** [comment]
@KGorr Thanks for helping and working on the style guide comms/language, do you have any updates for this week? Let me know if you need any help!

**Comment by KGorr** [comment]
Sorry, still waiting for approval but I'll ping Sarah again. Thanks!

**Comment by sabrinang** [comment]
@KGorr Thanks for sharing that the Comms/Voice Guide is being worked on page 6 in this overview document: https://docs.google.com/document/d/10VqdPgGJ94EuA3hfTj5DtDpQbYJLGBNGc1yVfuTV0fc/edit?usp=sharing

Style guide slide updates:
- I revised slide 39 to include the link to this document
- I also updated slide 4 so the festival narrative in the speaker notes reflects what is noted in that overview document

@kristinashu R?

**Comment by kristinashu** [comment]
Excellent, R+!

@marcwalsh @KGorr between the two of you, could you please make sure your team is aware of the [finished style guide](https://docs.google.com/document/d/10VqdPgGJ94EuA3hfTj5DtDpQbYJLGBNGc1yVfuTV0fc/edit?usp=sharing) and the [update brand pages](https://foundation.mozilla.org/en/docs/brand/) (specifically the pages called Logos, Color, Iconography, Photography, and Reference)?

**Comment by KGorr** [comment]
Yes, will do!

**Comment by kristinashu** [comment]
One more nudge to @marcwalsh! But I think this is good to close, thanks all!
