### ISSUE TITLE
*Sample* Usertesting Video Observation Feedback

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#49]
**Note** - This is a sample user video observation ticket. Scan through it to get a sense of how to organize your feedback. Then, copy and paste the contents into a new issue.

**Video reviewed** - https://www.usertesting.com/videos/8Tux0p49gCoLD3kg30TqRA

**Summary**
Overall, the user was able to complete the assigned tasks easily, but struggled a little with changing the source of the image tag.

**What worked**
What was easy or enjoyable for the user?
* Really liked the live-preview
* Easily adjusted the font size and theme in the editor
* Easily found the project rename UI
* Easily identified where they would publish their project

**What Didn't**
What was difficult for the user, what were they confused by or didn't like?
* Confused by what the Refresh icon did in the preview, seemed to have no effect - *5:04*
* Unable to find a way to resize the editor
* Had trouble figuring out how to add a new file to a project - *12:31*

**Bugs Observed**
Things you saw that weren't working as planned, but that the user didn't.
* Project renaming didn't work

**Issues Filed**
List of issues related to this user testing report that you filed.
* Issue 1
* Issue 2

**Comment by cassiemc** [comment]
@flukeout I wonder if this is the best place for this to live? Feel like it gets a little lost in github.

**Comment by cassiemc** [comment]
@flukeout I'm closing this, please reopen and rename if you need to do anything else here.
