### ISSUE TITLE
Moz News Beat email format

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#490]
### Intro

Will was wanting to test the Moz News Beat in an email format as a new piece of content we can send to our email audience.

Met with Will and Jen to go over design needs for this. For the mockup to run through approvals, Will needs:

- [x] MozBeat Email Header image

- [x] Exported emojis in png format

- [x] Awesome to awful titles exported as png images

- [x] 6 colour gradient hex codes for awesome to awful

**Comment by natalieworth** [comment]
Moving this to next milestone as Anil needs to co-ordinate approvals for this to happen via email.

**Comment by natalieworth** [comment]
Met with Will and Jen to go over design needs for this. For the mockup to run through approvals, Will needs:

- [ ] MozBeat Email Header image

- [ ] Exported emojis in png format

- [ ] Awesome to awful titles exported as png images

- [ ] 6 colour gradient hex codes for awesome to awful

**Comment by natalieworth** [comment]
I [mocked up a rough version](https://redpen.io/p/fj122a0a8e46fafaaf) of how I'm thinking the Email News Beat could look with each color block. Can you let me know if this is do-able @WillatMozFdn ?

cc @caltrider @audreymofo

**Comment by WillatMozFdn** [comment]
Generally, yes, I think so.  The only part I'm not sure about is the circular graphics, we'll need to experiment with those some.  Not sure if a .png will let the background color of the table cell effortlessly show through on the corners around this circle, or if we would need to separately prep each icon on each BG color.  Well, send me some icon files and some hex values, and we'll find out!

**Comment by natalieworth** [comment]
Hey @WillatMozFdn , can you try these emoji pngs?:
[Emoji-Pngs.zip](https://github.com/MozillaFoundation/Design/files/4412947/Emoji-Pngs.zip)

**Comment by natalieworth** [comment]
And here are the hexcode colours to try:

01: #FFC8CE
02: #F8ADC6
03: #DDA2CF
04: #E7CBEB
05: #C6C1F7
06: #A9A9FF

**Comment by natalieworth** [comment]
Header image options:
[Header.zip](https://github.com/MozillaFoundation/Design/files/4422677/Header.zip)

Emojis:
[emoji-pngs.zip](https://github.com/MozillaFoundation/Design/files/4422679/emoji-pngs.zip)

cc @WillatMozFdn

**Comment by natalieworth** [comment]
[News-beat-header@2x.jpg.zip](https://github.com/MozillaFoundation/Design/files/4422925/News-beat-header%402x.jpg.zip)

Hey @WillatMozFdn added one more header option as Audrey suggested adding something visual around the beats in.
