### ISSUE TITLE
Goals for 2020 H1

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#496]
Everyone needs to write they H1 goals for 2020 by Fri March 13. Please write some ideas down by Thurs March 12. You can take some inspiration from the All Hands team KR doc https://docs.google.com/document/d/18wb6n_vGUXP1wr-GdF0P24YbisCAHCKy7QLl7WJs1vQ/edit#heading=h.2wivsb1hg2x8.

**Comment by natalieworth** [comment]
[Goal doc is here](https://docs.google.com/document/d/1uXPMSm6riY9_E7I3bLo-hT5OUrYRRevJRgHw0OTak-I/edit).

**Comment by beccaklam** [comment]
[Goal doc here](https://docs.google.com/document/d/1hy-hAxCisWb9Gjalqw4I1XF5XAb0g4hU-9Yxb2NQ5k8/edit?usp=sharing)!
