### ISSUE TITLE
[Brand] Position and Communications meeting

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#497]
Follow up from @sabrinang's ticket - [Brand] Position and Communications #471

### Intro
Bi-weekly check-in and coordination with Lotta on how to create and add brand positioning and communications content on to the brand wagtail docs. Meeting [notes doc](https://docs.google.com/document/d/1lJtLUbW3PRJ7kA8JWWRIgtIP_UTMYbrBwqlPBwNgU_U/edit).

### Goal
To publish and populate the positioning section of the brand page. This IA and content is dependent on what Lotta has created and collected.

### Process
- Meetings every 2 weeks with Lotta to coordinate
- Guide Lotta to create/update content on wagtail
- Review and gather feedback from collaborators
- Revise, refine and publish

### Related Issues
Brand Brief: https://github.com/MozillaFoundation/Design/issues/445
Brand Planning Outline: https://github.com/MozillaFoundation/Design/issues/427

**Comment by sabrinang** [comment]
We had our meeting with Lotta today to coordinate collateral requests from her here: https://docs.google.com/document/d/1vu14K7tv9DA_vNkUqaz0Hg7WT4szvnsLcMx5EZdZw3E/edit?usp=sharing 

Process wise, we will collect copy in doc above and once approved we will file corresponding design issues. We have our bi-weekly check-ins scheduled already.

I’m keeping this ticket open as a reminder to also meet with content team on the content team stand on Monday to inform them that this comms work is coming along so they're aware – will close once we meet.

**Comment by kristinashu** [comment]
Good idea, thank you Sabs for keeping content team in the loop!

**Comment by sabrinang** [comment]
At content stand this morning I informed them that comms work is being collected and will keep them informed as it comes along. Closing issue.
