### ISSUE TITLE
Graphic for creative collab page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#498]
[Copy](https://docs.google.com/document/d/1K0KaFU_-0Mi49RZW_mGCLY9UPOGWc68Pg-TfFZm_sNY/edit#heading=h.fs3gtczc7i18) is almost final, then I'll put it as a wagtail page, and we would like to add a "splashy graphic" to lure staff in. 

@xmatthewx has suggested something like "Need Stuff? Start here: [link]"

**Comment by natalieworth** [comment]
@xmatthewx Here's the Collab image I'm thinking of: https://redpen.io/p/ms524ede252754f3b2

**Comment by natalieworth** [comment]
@xmatthewx @kristinashu Final file [for this is here](https://drive.google.com/open?id=12ap2YrsNmz2mqzDCAnHmah2wIcOh7VyE).
