### ISSUE TITLE
Write a "volunteer job description" for design contributor

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#50]
There's some awesome thinking going on in https://github.com/MozillaFoundation/plan/issues/482. Would love to see how design can get involved in this.

**Comment by cassiemc** [comment]
@vazquez I'd love if you could just barf out some thoughts here, I'm sure it would be brilliant. :) Doable in this heartbeat?

**Comment by vazquez** [comment]
Definitely doable this heartbeat and I apologize for the delay!

**Comment by vazquez** [comment]
@cassiemc What do you think? :arrow_down: 

##### Volunteer Job Title

Open-Source Designer, Mozilla Foundation

##### Volunteer Job Description

At Mozilla Foundation, we spend a lot of our energy promoting web literacy. We’ve been hard at work the past year building innovative tools, supporting communities, teaching, learning, and shaping the environments in which the open web is made possible. We want everyone in the world to create, not just consume, the Web around them.

As an Open-Source Designer, you will be immersed in the world of products such as Thimble and Webmaker for Android, communities such as Mozilla Learning Networks and Mozilla Hive groups, and initiatives such as Mozilla Advocacy and Fundraising.

During your time with us, you will learn how to:

- Approach design through an iterative process with our growing user base and community
- Design and implement interfaces and collateral work for our products and initiatives
- Illustrate collateral work for our products and initiatives
- Create and conduct user testing research to generate insights of our products
- Prototype and implement work using HTML, CSS, and JavaScript 

Of course, you don't need to do it all. Even if you wish to focus on one discipline of design, we would love to have you on board. Ready to become an Open-Source Designer? Apply below!

[Magical apply button that goes nowhere right now]()

**Comment by cassiemc** [comment]
Fantastic @vazquez thanks! Very curious to hear what @openmatt and others think of this. I posted this in https://github.com/MozillaFoundation/plan/issues/482 as well, but I'm very curious about what the process for this would look like. 
* where do we post a description like this 
* What does the application process look like? (what is the volunteer criteria, who assesses the criteria, how is that person notified) 
* how does this volunteer get onboarded?

**Comment by cassiemc** [comment]
(I think we can actually close this ticket now and file new ones for implementation)

**Comment by vazquez** [comment]
Cool!
