### ISSUE TITLE
Instagram grid link on Wagtail: stakeholder interview

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#503]
### Intro

Interview Instagram stakeholders to find out the requirements, audience, etc. for the Instagram grid page that will host the weekly News Beat content.

I'll update this tic later in the week when I get more info and can outline interview questions/ doc.

### Links
TBD

**Comment by natalieworth** [comment]
[Doc for this is here](https://docs.google.com/document/d/1D6Vk6QTips4S6PQoua3q2HNYKEzrHm4WZhvUgD-WYWI/edit)

**Comment by natalieworth** [comment]
Hey @kristinashu , there were 2 questions [Audrey left highlighted in the interview brief doc](https://docs.google.com/document/d/1D6Vk6QTips4S6PQoua3q2HNYKEzrHm4WZhvUgD-WYWI/edit). They feel a bit more dependent on us (e.g. timing, dates, etc.) and Instagram grid link completion date still fairly open-ended.

**Comment by kristinashu** [comment]
Thanks for doing the interview @natalieworth! I think timing would really depend on if it requires dev time or not? Do you have any designs in mind? We could start with something simple like a standard wagtail page using the image grid component. And then if it gets a lot of traffic then we could do something more exciting? Would you want to mockup some layouts next sprint?

**Comment by kristinashu** [comment]
Opened a ticket for next sprint (I've grouped it with the News beat landing page work) https://github.com/mozilla/foundation.mozilla.org/issues/4375
