### ISSUE TITLE
Sunset Codemoji on the Foundation Site

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#506]
### Intro

Codemoji will be no more!—so we should create a page to archive/ sunset it's memory.

@xmatthewx Were you thinking something similar to [Thimble/ the other past projects pages](https://mozilla.invisionapp.com/share/AWW3BL4MNTB#/screens/407078957_Screencapture-Foundation-Mofostaging-Net-Cms-Pages)? It wasn't technically coded by Mozilla (it was external agency), but just trying to think where it should live?

### Links
Tbd

cc: @kristinashu @xmatthewx

**Comment by xmatthewx** [comment]
Yes, but you have broad license to steer toward whatever you think is appropriate. 

You can give credit o whoever coded it. But either way, it was a mozilla project, no? and can be framed as that.

**Comment by kristinashu** [comment]
I'd recommend this goes under /campaigns since it was more of a short lived campaign than a product we worked on for years and years like most of the work on /artifacts.

**Comment by natalieworth** [comment]
Draft of sunset-ed Codemoji is here https://foundation.mozilla.org/cms/pages/899/edit/ .

**Comment by natalieworth** [comment]
@patjouk Tagging you here that it can probably be sunset-ed dev-wise :) I got a bunch of screenshots for it. 
cc @cadecairos

**Comment by natalieworth** [comment]
<iframe src="https://giphy.com/embed/7tn6Y2NgbLw8o" width="480" height="325" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/bye-7tn6Y2NgbLw8o">via GIPHY</a></p>
