### ISSUE TITLE
Create Thank You Card Template for Staff Anniversaries

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#508]
Placeholder ticket to track work for creating a Thank you card template for staff anniversaries.
Stakeholder interview with Mandy [here](https://docs.google.com/document/d/1qBGP2EXrrehJoigm1CpT3zNIR8YtVMcE5XVX32Jp4wg/edit?usp=sharing).
Mandy has mentioned that digital cards would be the priority at this point.
cc: @kristinashu

**Comment by beccaklam** [comment]
@natalieworth Can i get your old thank you card files please? The fancy line art ones? 😃

**Comment by beccaklam** [comment]
First draft here: https://redpen.io/p/vjced5cda8395333c4 @natalieworth @kristinashu @taisdesouzalessa @sabrinang Could I get some feedback please? Don't really think the white is working but wanted to show y'all the option. Tried using the brand colours but they didn't really go with the gold foil look. Black seemed too strong so I made it a dark blue instead.

**Comment by beccaklam** [comment]
Web files are [here](https://drive.google.com/drive/folders/1A5lg1lyg6JigWs7lhDbSdA1FFNwpuqI7?usp=sharing) on the drive and have been shared with Mandy. 
Print files are still WIP and will be finished when offices reopen and we can test colour and sizing. @kristinashu Should I close this ticket for now or move to blocked?

**Comment by kristinashu** [comment]
Please open a new ticket to test the print version and then close this one. We can move the new ticket into a sprint when the offices open.

**Comment by beccaklam** [comment]
Follow up ticket for the print work opened here at #527. Closing this ticket!
