### ISSUE TITLE
Add Instagram link to emails

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#509]
### Intro

Our emails only currently link to the Twitter and Youtube channels. Let's also add our Instagram! :)

- Need to create an Instagram logo svg to be added to emails (Will can add)

**Comment by natalieworth** [comment]
@WillatMozFdn Would this icon work for the email footer:
<img width="38" alt="Instagram-email-icon" src="https://user-images.githubusercontent.com/14876567/77503175-3b38ba80-6e1a-11ea-9a5c-4714d40405a0.png">

[Instagram-email-icon.png.zip](https://github.com/MozillaFoundation/Design/files/4379108/Instagram-email-icon.png.zip)

**Comment by WillatMozFdn** [comment]
yep, looks good to me!  @natalieworth 
![image](https://user-images.githubusercontent.com/23637882/77549830-b3d56080-6e86-11ea-842b-f2adc17b279a.png)
