### ISSUE TITLE
Set up 'programming' for Monthly Design Crit

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#51]
We should talk about who we want to invite to and have inform our design culture.
High bar inspiration: http://mailchimp.com/about/coffee-hour/

**Comment by cassiemc** [comment]
Had our first guest Madhava, was great! Gave our own work some new context and made connections between Mofo-Moco.

Other ideas on the table:
* Parsons people (via @xmatthewx)
* other instructors?
* Aaron Walter (mailchimp)
* design/dev hybrid industry leaders
* illustrator
* contributor
* student/s

What I'd actually like to do with this ticket is create a more general 'programming', not just guests. So what I propose is a 4 week cycle:

**Week 1:** In-depth topic discussion, no critique (e.g. design principles)
**Week 2:** Article discussion. 1 designer presents on an article they've read or conference they attended. We discuss briefly then proceed to regular critique.
**Week 3:** Article discussion. 1 designer presents on an article they've read or conference they attended. We discuss briefly then proceed to regular critique.
**Week 4:** Invite a guest to our regular critique

Hopefully this creates a cycle where our design work cumulatively improves from the discussions we have so by the time we invite a guest we have some great work to share.

Thoughts @flukeout @vazquez @sabrinang @lovegushwa @xmatthewx ?

**Comment by vazquez** [comment]
Yes! I like that :) Sort of a critique meets book club, :boom:

**Comment by cassiemc** [comment]
I added this frame to https://etherpad.mozilla.org/designcrit so we can use it as a model on an ongoing basis. Closing now.
