### ISSUE TITLE
Develop user journey map: write a brief

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#513]
Goal this sprint: Brainstorm scope and process in a [google doc](https://docs.google.com/document/d/14MCesZOzEEtrClWMbe_6Nmej5mz9MDDeiaAmzwD13zE/edit#). When that work is done, we can update this ticket.  

Goal next sprint: Start the work. 

cc: @kristinashu

**Comment by beccaklam** [comment]
Hi @xmatthewx, I've taken a first pass at the design brief for this work [here](https://docs.google.com/document/d/1bTp_tcpXI_YWPkidbPoqEBKx10nGfJJWmUZXxtfL-O0/edit?usp=sharing). Please feel free to edit and add your thoughts!

**Comment by kristinashu** [comment]
@beccaklam when you get the chance, please open a ticket with the next steps for this work.

**Comment by beccaklam** [comment]
Follow up ticket for Phase 1 of this work opened here: #4485

**Comment by beccaklam** [comment]
@xmatthewx I'm going to close this ticket for now but feel free to still edit the brief: https://docs.google.com/document/d/1bTp_tcpXI_YWPkidbPoqEBKx10nGfJJWmUZXxtfL-O0/edit?usp=sharing

**Comment by xmatthewx** [comment]
the brief looks fantastic @beccaklam. 

I wonder if it should include journey map in the intro pieces, rather just as part of deliverables. I think it's okay they they're focused on internal use, still legit. Fine either way. Just thinking out loud here.
