### ISSUE TITLE
Instagram Post: March 25/26

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#514]
### Intro

Instagram post for _'Thank Goodness for the Internet'_

### Links
TBD

**Comment by natalieworth** [comment]
@audreymofo @caltrider How do you feel about these options for the 'Thank Goodness for the Internet'
https://drive.google.com/drive/folders/1DfXtaUA5j2fRubB3QdN9_blcVap7AuH0?usp=sharing

**Comment by caltrider** [comment]
@natalieworth It feels to me like it's missing the human element. The gist we're trying to covey is "Thank goodness for the internet as it keeps us humans connected right now while we must be physically apart." Feels like we need to see those humans and convey that feeling of connection if we can. (for example, two stick figure people standing 6 feet apart with a like coming out connecting them that represents the internet and a red heart beating in the middle when they connect). Audrey, what do you think?
