### ISSUE TITLE
[Brand] /photography HQ photo library for staff use

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#516]
### Intro

Curate and collect photography that staff can use for publishing wagtail pages or projects across MoFo. This can help encourage the use of more photography and help us store and easily find photography from various gatherings and events across the org.

This can help show more people behind the initiatives, help visualize what we do and make pages feel more personal for visitors.

cc: @kristinashu @sabrinang @natalieworth @taisdesouzalessa

**Comment by kristinashu** [comment]
Some links have already been gathered at the bottom of [this page](https://foundation.mozilla.org/en/docs/brand/design/photography/).

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1068783/81594338-98121500-9375-11ea-975f-2d470237faef.png">

**Comment by beccaklam** [comment]
@kristinashu Selected some photos for the fundraising test [here](https://drive.google.com/open?id=14sA-T4qv_VDbKcB3pyl74juAQ8vJ1bpW).
More choices in this [folder as well](https://drive.google.com/drive/folders/1TwtZK8D1Mc50bOKpyKfeiLdp8lN63SDM?usp=sharing) (of people using tech).

**Comment by beccaklam** [comment]
I have a folder of images going [here](https://drive.google.com/drive/folders/19X6F-Eij3KXKqS45DukS75O6Ambd0QBb?usp=sharing).

**Comment by beccaklam** [comment]
Started a folder on google drive as shared above, will link again here: [Photography HQ](https://drive.google.com/drive/folders/19X6F-Eij3KXKqS45DukS75O6Ambd0QBb?usp=sharing)
Will close this ticket for now but we can keep adding to it!
