### ISSUE TITLE
Stakeholder Interview/Brief: Comms Collateral for Fundraising

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#520]
### Intro

Fundraising collateral has been requested to be shared among relevant audiences specifically current and prospective Mozilla donors.

### Process

- [x] Schedule to meet Jesse W.
- [x] Conduct [Stakeholder Interview](https://docs.google.com/document/d/1Mfc9aVtCVds3CEdRpzY95k4DI8h7SBSXtXxfhOXIz1s/edit?usp=sharing)
- [ ] Fill out [Project Brief](https://docs.google.com/document/d/1yrvS5o4RzoPZ_cDQZkvWSZy82nDCkUvU6xFJCxlPMzQ/edit?usp=sharing)

### Links

Collateral List: https://docs.google.com/document/d/1vu14K7tv9DA_vNkUqaz0Hg7WT4szvnsLcMx5EZdZw3E/edit?usp=sharing

cc: @kristinashu

**Comment by sabrinang** [comment]
I had our kick-off chat with Jesse today (stakeholder interview). 

I'm filling out the design brief after based on the convo: https://docs.google.com/document/d/1yrvS5o4RzoPZ_cDQZkvWSZy82nDCkUvU6xFJCxlPMzQ/edit?usp=sharing

I slacked Jesse to check if I've missed anything. After I hear back that he's reviewed it, I can wrap up this issue.

**Comment by kristinashu** [comment]
Excellent interview. Jesse's views seem very aligned with our.

**Comment by sabrinang** [comment]
Jesse has reviewed it and he's sharing it with Lotta/Kevin too since they are also responsible for the work. He's helping to sort out the content process: "...once we mark the "Copy Status" as "approved" it will signal that it is ready for the design team to work on it."

AFAIK the brief is done, if Kevin/Lotta have adjustments to the brief it'll be updated in doc and I can note here – closing.
