### ISSUE TITLE
Comms Collateral: MozFest One-pager (digital)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#521]
### Intro

Design MozFest One-pager to be shareable on the web.

Output ideas: Wagtail page (that is formatted for print pdf as well).

### Links
Approved Copy: https://docs.google.com/document/d/1j43TbEUHx6iSWcYtczm-FjCllKWJFfUR_swHzM8x0c8/edit?usp=sharing
Print version _(refined google doc)_: https://docs.google.com/document/d/1j43TbEUHx6iSWcYtczm-FjCllKWJFfUR_swHzM8x0c8/edit?usp=sharing

cc: @kristinashu

**Comment by kristinashu** [comment]
@sabrinang any progress on this?

**Comment by kristinashu** [comment]
@sabrinang I just moved this into this milestone since the general Mozilla one-pager is blocked and it seemed like you had already start on this a little.

**Comment by sabrinang** [comment]
Saved draft here: https://foundation.mozilla.org/cms/pages/808/edit/preview/

Should we keep the top and bottom simple? I tried versions with images near header with footer text included to reflect the contents of the refined one pager and a version without. Redpen here: https://redpen.io/p/qo79d6125ef8487fd0

**Comment by sabrinang** [comment]
Yeah good points, children of /brand do appear in the nav so I think one pagers should just be children of _/docs_ itself and this helps keep URLs shorter and so it won’t have the vertical nav appear on the one pager page. When we publish the link would be – https://foundation.mozilla.org/docs/mozilla-festival

Links can be collected in brand comms so I moved the page and included one-pagers in brand comms page for now: https://foundation.mozilla.org/cms/pages/900/view_draft/   _(this page will be updated perhaps renamed when we have more comms collateral)_

I can definitely revisit hierarchy more in /docs home ticket #515 

For the page itself, I'm leaning towards not having the image strip but including MozFest logo, and footer copy _(though I wish it could be in body-small but style not available in cms)_: 
https://redpen.io/jye369defa59133ff5

**Comment by kristinashu** [comment]
Nice! This feels much better. I think this is ready to be published and link to it [collateral doc](https://docs.google.com/document/d/1vu14K7tv9DA_vNkUqaz0Hg7WT4szvnsLcMx5EZdZw3E/edit#).

Then this should be ready to close but let's revisit it once the print styles ticket is done https://github.com/mozilla/foundation.mozilla.org/issues/4378 and once we have made a few more digital one-pagers. If print styles aren't amazing, then we should consider adding a Download PDF button.

**Comment by sabrinang** [comment]
Published: https://foundation.mozilla.org/en/docs/mozilla-festival/
- linked in collateral doc

Sounds good to follow up with print styles later on as well
