### ISSUE TITLE
Comms Collateral: Mozilla One-pager (print/digital)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#522]
### Intro

Design Mozilla One-pager to be shareable on the web and in print.

Output ideas: Wagtail page (that is formatted for print pdf as well) or refined Google Doc.

### Links
Approved Copy: https://docs.google.com/document/d/1sjPGr3gdy1g2Fgn-wU2xNFozIVrxvXMstakPV3WxAfM/edit?usp=sharing

cc: @kristinashu

**Comment by kristinashu** [comment]
@sabrinang any thoughts on where these one-pagers should live? I think once you've decided that then we should put this as blocked.

**Comment by kristinashu** [comment]
Seems like this is no longer happening.
