### ISSUE TITLE
Graphic for "Privacy, pandemics and the AI era" blog post

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#525]
Graphic of Mark's blog post https://foundation.mozilla.org/en/blog/privacy-pandemics-and-ai-era/

Last minute request. Rebecca is working on a graphic for this. 

cc FYI @TheoChevalier

**Comment by beccaklam** [comment]
Graphic is [here](https://drive.google.com/open?id=1sXMlDsRDvdKv-xbvmxUVV3_mTkOuypJQ) on the drive and was uploaded to the Foundation site last Friday. Blog sent out Saturday. Closing this ticket!
