### ISSUE TITLE
[Brand] Social Media Content Guideline Pages on Wagtail 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#528]
### Intro
I'm splitting up the social media guidelines issue https://github.com/MozillaFoundation/Design/issues/478 into two tickets. The previous will be focused on brand identity and this one will focus on content.

### Guideline Ideas

**Social Media Brand Voice**
I know that content team has put together that really awesome [2020 Org-Wide Content Strategy](https://docs.google.com/document/d/1aXW5vfkhDmdo6UbIsNdFYwSG1ZFfcnemQh-TbQ9pn9M/edit?usp=sharing) gdoc and it contains great insight to voice/tone/stats/audience that could inform social brand voice. Could that be shared or is it still WIP? I think calling out some version of the text could be useful for alignment

**Sharing on Social**
If staff and collaborators want to post or broadcast to their own networks, are their any hashtag guidelines, sample posts or guidelines that could inform how they promote us or our initiatives on their own social networks? (example: like the [MozFest Comms Cheat Sheet](https://docs.google.com/document/d/1g4VrFRHjT1zlf_iaYYarLqOvz0LMstWJnfCOsR7KCDs/edit?usp=sharing) is handy to align community voices too and I wonder if there is something similar MoFo wide)

**Social Stats**
- Link to [instagram stat sheet](https://docs.google.com/spreadsheets/d/1Upoh2AjMpGMn0bWRuCwDfFUZ1XCpHnAPcrVVzS77IJ4/edit?usp=sharing)
- [2020 Org-Wide Content Strategy](https://docs.google.com/document/d/1aXW5vfkhDmdo6UbIsNdFYwSG1ZFfcnemQh-TbQ9pn9M/edit?usp=sharing) also has some stats

**Collaboration**
It isn't entirely clear how staff can contribute or collaborate with potential requests. It may be helpful on describing what they can expect and what the content team may be looking for.
- What is the best way for the content team to be reached? (slack channel or other contact info)
- What is the preferred method to take in requests or process? (is their a queue or calendar)

**Other**
For links to Firefox social media, I think we should link to [https://www.mozilla.org/en-US/firefox/](https://www.mozilla.org/en-US/firefox/) directly, not mozilla.org

### Links
This could also live with social media identity guidelines: https://foundation.mozilla.org/cms/pages/793/edit/ 

cc: @kristinashu @natalieworth @caltrider @audreymofo

**Comment by kristinashu** [comment]
Relevant info is being updated in https://github.com/MozillaFoundation/Design/issues/998 cc @nancyt1
