### ISSUE TITLE
User Journey Phase 1: Functional UX system map and User journey map

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#535]
Follow up ticket from #513
Phase one of the User Journey work:
- [x] Create Functional UX system map
- [x] Create User journey for 2-3 audiences

More details about this work can be found [here](https://docs.google.com/document/d/1bTp_tcpXI_YWPkidbPoqEBKx10nGfJJWmUZXxtfL-O0/edit?usp=sharing).

Tool that I've decided to use is Miro.com. The goal for this stage is to keep the work rough, finish small pieces and iterate. ~Hoping to collaborate with @taisdesouzalessa on this stage of the work.~ Collaborating with @sabrinang on this work while @taisdesouzalessa and @natalieworth work on audience.

**Comment by kristinashu** [comment]
@sabrinang @beccaklam can you please link to your process work and deliverables here? And then open separate tickets for next steps for User journey map and the Concept map.

**Comment by beccaklam** [comment]
## Functional Map
Process: [Miro](https://miro.com/app/board/o9J_kuOF7Zc=/)
Deliverable: [Spreadsheet](https://docs.google.com/spreadsheets/d/1u-YFU-z1oQyCy7m2ihIhWUzyuFN8JYokvUm8N4NlPeQ/edit?usp=sharing)

## User Journey Map
Process: [Miro](https://miro.com/app/board/o9J_kuOF7Zc=/), [Slide 14 in scrapbook](https://docs.google.com/presentation/d/1FDuF07ScQ8yr4TefhfHCNMdHgKt9hNUaQIeiPw3222A/edit?usp=sharing)
Deliverable: [Spreadsheet](https://docs.google.com/spreadsheets/d/1u-YFU-z1oQyCy7m2ihIhWUzyuFN8JYokvUm8N4NlPeQ/edit?usp=sharing)

## Concept Map
Process: [Documented in Scrapbook](https://docs.google.com/presentation/d/1FDuF07ScQ8yr4TefhfHCNMdHgKt9hNUaQIeiPw3222A/edit?usp=sharing)

**Comment by beccaklam** [comment]
Follow up ticket for User Journey Map Next Steps #553
Follow up ticket for Concept Map Next Steps #554

**Comment by beccaklam** [comment]
Closing this ticket for now! Please re-open if anyone needs.

**Comment by kristinashu** [comment]
Awesome! Thank you for adding the links and opening those tickets! 

I think the tickets are a little ambitious for this sprint so I've opened this one - Define next steps for user journey work #555 - for this sprint and then your follow up tickets can be done in a following sprint.
