### ISSUE TITLE
Misinformation Post

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#536]
### Intro
Instagram post for Misinformation. More info TBD.

### Links
TBD

**Comment by kristinashu** [comment]
@natalieworth was this [this post](https://www.instagram.com/p/B_AzeE_jQrf/)?

**Comment by natalieworth** [comment]
Oh yep! Final files are here for documentation :)
https://drive.google.com/drive/folders/1iAlSfvmXfqma2VV0bWNef4HazRTj4Pl9?usp=sharing
