### ISSUE TITLE
Design recap 2020

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#537]
[Starting a recap deck](https://docs.google.com/presentation/d/1Haea7saoXXGxaCD9W54ZsO6P9-EWtWSrzFMATs2G9mE/edit?usp=sharing) that we can update quarterly. I will put this into our next sprint but if you feel like working on it now the please go for it!

cc: @sabrinang @natalieworth @taisdesouzalessa @beccaklam

**Comment by phildexter** [comment]
Working session in June 2nd Sprint. @kristinashu to schedule.

**Comment by kristinashu** [comment]
Thank you everyone who has already added to the deck!

Note it is now called the "Design Collaboration" rather than "Design Recap" so that it is more inclusive and meaningful to other teams as well.

### Goals & Audience
- Celebrate and remissness about all the work we did this year
- Show both the depth and breadth of our work 
  - Depth: Highlight a few key projects to show our impact
  - Breath: all the things, show how we touch on a lot of different types of work all across to org
- Share with Ashley, Anil, and the rest of the org to show off both the importance of our contributions but also how much we have achieved
- Use it to guide our 2021 planning - what types of work do we do, what did we enjoy working on the most, where did we have the most impact

### Process
- Everyone add the projects they worked on
- Kristina to review Github / Airtable to see if anything was missed
- Get together and fill in the gaps (were and what metrics can we add, what story do we want to tell...)
- See if devs want to add to it as well
- Share with Ashely and Anil
- Share with rest of the org

### Deadline: Add for next huddle and we can discuss/finalise there

**Comment by natalieworth** [comment]
I'm wondering if we could do badges for these on some of the pages (I can make them in illustrator): 
Most likely to go viral

Most likely to inspire global change

Most likely to start a fight in the Twitter comments

Most likely to win an Oscar

Most likely to make Amazon cry

Innovator

Superstar

Best Collaboration

Most localized

**Comment by taisdesouzalessa** [comment]
I love the idea of badges, @natalieworth. It reminds me of the Apple fitness does:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/22157921/104214624-88f3d300-53ec-11eb-9582-b1fe36056454.png">

Since we're talking about events that already happened I wonder if we could rephrase the "most likely" to things that actually happened or that have potential to do so? Like "Started a fight on Twitter comments" (if any), "inspiration for global change", "made Amazon cry", "potential to win a future Oscar" and so on.

**Comment by kristinashu** [comment]
I've made a follow up ticket https://github.com/MozillaFoundation/Design/issues/744 to share out the deck so this ticket can be closed at the end of this sprint (today)!
