### ISSUE TITLE
Design Holiday Card thank you list

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#54]
mentor= @cassiemc

Thinking about how we say thanks to people at the end of the year for being amazing to and for Mozilla. Personally I'd like to add our design contractors, contributors, our intern, maybe final interview candidates and past employees. Could also add top donors, Mozfest session leaders. This could be a great list for our shiny new CRM @adamlofting!

Maybe it's not a holiday card, but *something* fun and design-y.

I am happy to be mentor on this bug should anyone want to bat ideas around or has further questions.

**Comment by adamlofting** [comment]
:+1:

**Comment by cassiemc** [comment]
If we don't think about this now, we never will! Anyone have cool ideas for a holiday card / thank you project? @flukeout @sabrinang @lovegushwa @kristinashu @vazquez

**Comment by sabrinang** [comment]
Can donors request something? for example something they like to be drawn like http://iwanttodrawacatforyou.com/

or can we send them something tangible like http://www.potatoparcel.com/

or is it just a one way interaction where we simply can email them something?

**Comment by cassiemc** [comment]
I :heart: the idea of making it more interactive!

**Comment by kristinashu** [comment]
Could do a year in review landing page - sort of a "thanks for all your help, here's some of what we've accomplished together". Kinda like Mailchimp's By the Numbers annual report http://mailchimp.com/2013/#by-the-numbers

**Comment by cassiemc** [comment]
I'm wondering if this could tie into the End of Year stuff at all. These are all great ideas. 

@lovegushwa @edrushka What do you guys have planned for a digital thank you post-campaign?

**Comment by edrushka** [comment]
Perfect timing to think about this @cassiemc - and yes, it would be :dizzy: FANTASTIC :dizzy: to  integrate this into the EOY fundraising! We brainstormed some [fun thank you ideas] (https://fundraising.etherpad.mozilla.org/FR-meetup-Session7) with @hpauljohnson during our fundraising meetup in San Francisco last month. Here's a round-up of when/why we might connect with our donors to thank them:
- early November Impact Email. This is a message to kick off our EOY fundraising. It highlights the work Mozilla has done over the year and primes people to donate later in the month when we officially start asking.
- donation form thank you. This is a short thank you message that's part of the donation flow. (See [Page 5] (https://www.dropbox.com/s/80ciummg00gvc1z/One-time%20individual%20donation%20flow.pdf?dl=0) ). Lots of room to improve this. 
- automated thank you email from Mark. This is a BSD (soon to be Exact Target) thank you email from Mark that everyone who gives their email receives immediately after donating. (See [Page 9] (https://www.dropbox.com/s/80ciummg00gvc1z/One-time%20individual%20donation%20flow.pdf?dl=0) ). Lots of room to improve this as well. 
- January follow-up email. Another thank you, and a way to let everyone know how our campaign did (and what we'll do with the money).

A few more details to keep in mind:
- L10N. We want to thank donors in their language. Or at least in many languages (like the current MozFest video)
- Culturally diverse. Given our global audience, we avoid focusing on Christmas, snow, and North American holiday things.

I love the "year in review" graphic idea. It's something we discussed as well!
cc @valianttry

**Comment by natalieworth** [comment]
Hey @cassiemc , I also assigned myself to this to work on at the beginning when I wasn't too busy (did some quick benchmarking https://www.pinterest.com/nataliejworth/mozilla-design-holiday-card-benchmarks/). Just wanted to check the timeline and if it would be okay for me to work on this when the other priorities are done. If not, I can un-assign myself. Thanks.

**Comment by cassiemc** [comment]
yes @natalieworth other priorities should def come first, unless this somehow resurfaces in the EOY campaign plans :)

**Comment by edrushka** [comment]
We'll be sending a "thank you for donating, this is how much we raised in our campaign" email from Mark in mid January.

**Comment by natalieworth** [comment]
@cassiemc Do we have one's from previous years for this?

**Comment by cassiemc** [comment]
@natalieworth Nothing from previous years. We're starting from scratch (fun right?). Feel free to setup a meeting with interested folks to brainstorm & scope this out.

**Comment by cassiemc** [comment]
We are going to scrap this for this year. Too far along in the year to begin this work, lack of clarity will make that difficult. To reopen next year if relevant!
