### ISSUE TITLE
PNI Marketing Materials

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#540]
### Intro

Marketing/ design ticket for the PNI materials needed for social this week.

### Links
Content from @audreymofo is in [doc here](https://docs.google.com/document/d/1Ydj0_HLO8ExPYVECacQghe3rcMuPQ6RKTB9rYQy-suc/edit).

Tagging you too @sabrinang :)

**Comment by sabrinang** [comment]
I worked on instagram image series based on direction and text from that google doc. 

Redpen here: https://redpen.io/auc29f1caff0e0ff11

@audreymofo do you want the meter to be connected across posts or separate? I left a screenshot of both variations of creep-o-meter for feedback. 
@natalieworth for some iterations, I made a seamless background from the video app icons, is it okay to do that or should we keep it plain?

**Comment by sabrinang** [comment]
@natalieworth working .ai file (and exports) are in the google drive here: https://drive.google.com/open?id=1LyBDaRzNs_Fh3TCCQCqdBq6WLW4SNk0L&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
Thanks for the feedback, I revised the type in the second version seen in redpen: https://redpen.io/p/gkbbba1fd6136676ac

**Comment by natalieworth** [comment]
@audreymofo Final [files are in here](https://drive.google.com/drive/folders/1MNFVTHCY9EIHQBUpyI02yFNUbb2FGKVi?usp=sharing) from me and @sabrinang :)
