### ISSUE TITLE
Differentiate Blog + Pulse Feed Components

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#542]
### Intro
Mentioned from https://github.com/MozillaFoundation/Design/issues/428#issuecomment-615482738, explore how we differentiate pulse and blog feed content.

- currently headings are different (h4 h5)
- consider if we align the heading styles or distinguish pulse cards more differently because it isn’t clear to the user what type of content the cards leads too (exp: to add pulse “category” etc.)

### Links
Blog feed example: https://foundation.mozilla.org/en/blog/
Pulse feed example: https://foundation.mozilla.org/en/fellowships/fellowship-and-award-updates/ and https://www.mozillapulse.org/projects?keyword=mozfellows19

cc: @kristinashu

**Comment by kristinashu** [comment]
We will be updating better integrating Pulse with our site later this year and will open new tickets for that.
