### ISSUE TITLE
Formatting Blog information: category, byline and date

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#543]
### Intro
Mentioned from https://github.com/MozillaFoundation/Design/issues/428#issuecomment-615482738, explore how we format the blog category, byline and date on posts and feeds.

- currently uses h6 both in posts and uses h6 and body-small in feeds
- explore how we can align and/or make them more distinct
- category could potentially be part of breadcrumb showing/linking from blog category etc.

### Links
blog content on home page example: https://foundation.mozilla.org/en/
blog: https://foundation.mozilla.org/en/blog/
blog category home example: https://foundation.mozilla.org/en/blog/category/advocacy/
blog post example: https://foundation.mozilla.org/en/blog/tips-make-your-zoom-gatherings-more-private/

cc: @kristinashu

**Comment by kristinashu** [comment]
cc @nancyt1 on this since she is currently working on the blog refresh but going to close this ticket.
