### ISSUE TITLE
Create simple audience cards

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#545]
**Goal**
A source of truth with the goal to increase stakeholder understanding of our audience

**Why**
- To give guidance on how to speak to people
- To guide the content and user experience of our channels
- To provide the Content Team with a collective understanding of our audience so we know how to speak to and engage them in our new audience with our work

**Process**
Focused sprint. Progress is tracked [here](https://docs.google.com/presentation/d/1hJuWDkO7G3zt8ZwhWPorj8Kq3uHsHHLdyPUmh983kdM/edit#slide=id.g25275a8168_0_260).

**Comment by kristinashu** [comment]
@natalieworth @taisdesouzalessa can you please link to your process work and deliverables here? And then open a new ticket(s) for next steps?

**Comment by kristinashu** [comment]
I've opened a ticket for next steps for this sprint - Define next steps for audience work #556

Please just add links your process work ad deliverables to this ticket then close it!

**Comment by natalieworth** [comment]
**### Process & Research**
[**Audience Scrapbook**](https://docs.google.com/presentation/d/1hJuWDkO7G3zt8ZwhWPorj8Kq3uHsHHLdyPUmh983kdM/edit#slide=id.g25275a8168_0_260)

[**Audience Spreadsheet**](https://docs.google.com/spreadsheets/d/1FlM8TAD2cpgJmaVrMSmaKO1Npk7C6mec17sSzF2R3R8/edit#gid=0)

**### Deliverables**
[**The Final Presentation**](https://docs.google.com/presentation/d/12yG85s3ptgosQZyvBQYpiLrvp98OgWlsaRjt2Auf1vk/edit#slide=id.g25275a8168_0_600)

[**Shortened Presentation**](https://docs.google.com/presentation/d/1IMRIrr3_eSg7yHW72Eosn6p0cGpKkhVmxJ-TLw8OMdE/edit#slide=id.g25275a8168_0_600)

[**Empathy Maps (Artifacts)**](https://redpen.io/p/qg2170facc4f09a222)
The drafted ‘empathy maps’ for the [Novice/ Observing audience](https://redpen.io/tse32332f203796afb) and the [Would-be-activist/ Following audience](https://redpen.io/xt01fbd09265b02f35) can be found in the red pen.
