### ISSUE TITLE
Triage by design

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#55]
How can we improve a team's experience and success with setting priorities on features and bug fixes? How can we increase visibility to the decisions that drive our work? How can we provide a clearer path for research and metrics to inform iteration? 

Thinking out loud...

# 1

How much does a feature or bug impact users? How hard is it to implement or fix?

![1 cost benefit](https://cloud.githubusercontent.com/assets/53411/8728086/32232eea-2bb1-11e5-905d-f71b05395a26.png)

# 2

Triage it

![2 triage](https://cloud.githubusercontent.com/assets/53411/8728089/32267640-2bb1-11e5-9399-fd5065531f50.png)

Evaluate along a spectrum 

![3 evaluate](https://cloud.githubusercontent.com/assets/53411/8728088/3225e590-2bb1-11e5-939b-9dda56ffab7e.png)

# 4

It's all relative (example of how it could be applied to current work on webmaker)

![4 iterate](https://cloud.githubusercontent.com/assets/53411/8728087/3225e05e-2bb1-11e5-8941-8fc56908c740.png)

---------

Visual triage and roadmapping could help a group set short-term and long-term goals. Day-to-day, github labels could be used to mark things according to cost (`high cost` `medium cost` `low cost`) and impact (`high impact` `medium impact` `low impact`). Either approach would give more visibility to the decisions that drive our work. They could also provide a more clear path for research and metrics to inform iteration.   

@cassiemc @flukeout @sabrinang @vazquez @lovegushwa

**Comment by vazquez** [comment]
I really dig this visual approach to prioritizing the work in a heartbeat. This diagram can also be very easy to refer to during the heartbeat. I have found myself asking "What was the important thing we are working on this heartbeat?" mid-sprint as I forget sometimes. This would be a very good resource to validate our priorities.

**Comment by cassiemc** [comment]
@xmatthewx How do you want to move forward / close this bug? Would be cool to document it in our process docs.

**Comment by cassiemc** [comment]
@xmatthewx update please? Would like to close this one up soon.

**Comment by xmatthewx** [comment]
Closed by #61
