### ISSUE TITLE
AI ToC slide update

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#550]
Two tasks to help Lainie with. We will have a quick kick-off meeting with her shortly.

1. Update slides 4 & 5 (color and B/W) in [this slide deck](https://slack-redir.net/link?url=https%3A%2F%2Fdocs.google.com%2Fpresentation%2Fd%2F1mqgZb0jKhHx2i061mpLWSamkajzlLZqTPWTrRf9qDZ0%2Fedit%23slide%3Did.g6c6c240c88_0_875&v=3)

- Design is limited since there's a lot of content but we will do our best!
- Needs to remain easily editable by any staff
- Ideally by the end of week would be ideal

2. Help to make sure it appears properly on the wiki https://wiki.mozilla.org/Foundation/AI

- @taisdesouzalessa to provide recommendations for image quality

Notes from kick-off:
- Deadline: this Friday or Monday
- Link to [white paper](https://docs.google.com/presentation/d/1d3UQy3vCmiCmxZRlyWIex-DnC1KrM5RKlQZh--tv-hs/edit#slide=id.g739347d7fa_0_3545)
- Stick to short term -> long term order
- Numbers are optional
- _(Sabrina, you probably have more notes!)_

**Comment by taisdesouzalessa** [comment]
**Dimensions:** 1920px X 1080px

**Comment by sabrinang** [comment]
Iterating in black and white first to focus on structure and I'm making it in [gslides](https://docs.google.com/presentation/d/15d_ufLf4o5GuqZep4XIerBSCpVssIywSfD6oEzlnNSU/edit?usp=sharing) and exporting horizontal/vertical structure ideas in redpen: https://redpen.io/p/yo40ff16fdf2e5fe01

- Information is kept the same as v0.92 ToC
- I'll explore some colour options later this week
- once refined I can export for wiki (thanks for dimensions Tais)

**Comment by sabrinang** [comment]
There has been comments of using ToC design beyond slide update _(example: google docs)_ so I’ve made them in google drawings of same design in: 
- Landscape https://docs.google.com/drawings/d/1uU-SRPw6_FYiA_ILQigdKfX8l4DPVEalLjtm4dA1Ggo/edit?usp=sharing
- Portrait https://docs.google.com/drawings/d/1hsKBNs8TAE2WBGY0hSlqHtd7dS57htZsB_ZztnoIbfE/edit?usp=sharing

**Comment by sabrinang** [comment]
I've created the google slide, doc and drawings formats of the ToC diagram on google drive here: https://drive.google.com/open?id=1Qp58jX-9cJAZN8KfBdsIY-NQHSgZiWj4

They include a mozilla logo in the upper left corner as well.
