### ISSUE TITLE
[Brand] Conversation Outline and Planning

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#552]
### Intro
Prepare a doc of what we want to discuss and prepare to share where we are at with brand. Coordinate with designers and schedule a pre-checkin discussion.

**Ideas/Discussion Points** 
- current state, ownership, vision, desires, collab/unification ideas, setting parametres etc.
- collect links/docs to share, process

### Links
- ongoing brand planning doc: https://docs.google.com/document/d/1lJtLUbW3PRJ7kA8JWWRIgtIP_UTMYbrBwqlPBwNgU_U/edit?usp=sharing
- brand project brief: https://docs.google.com/document/d/1naepEoy1Y8jZ0TQ_MNFsz68AhfuoFM6zVvHknt-7JGY/edit?usp=sharing
- brand research audit/benchmarks: https://docs.google.com/presentation/d/18hqNyB7JnRsjdwoogpQelcX7NFKocagxBSB_GXWUgAU/edit?usp=sharing

cc: @kristinashu

**Comment by sabrinang** [comment]
Brainstormed some points to get prepared. We met today to get familiar and I recalled some points from the meeting and noted them on the same brand convo planning doc here: https://docs.google.com/document/d/1SEO1s-P4kI_LOh4s9cQ_ssr8FV1W4UZuNFvRQHSTe4E/edit#

@kristinashu if I missing anything feel free to add

**Comment by kristinashu** [comment]
Looks good, thank you Sabs for representing us!
