### ISSUE TITLE
PNI for Mother's Day graphic

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#557]
cc: @sabrinang @natalieworth

**Comment by natalieworth** [comment]
[Content is here](https://docs.google.com/document/d/1Sdnq8fNJbVJ9j7YKMgpwH5VtrMUF_F-bryVtdT57NT4/edit)

**Comment by natalieworth** [comment]
Drafts for this are here https://redpen.io/p/gs6e42d892a8c6946a

**Comment by natalieworth** [comment]
[Final exports will be in here ](https://drive.google.com/drive/u/0/folders/1ZGIgAZ-sTNmFSGNxsOWw4HowIgJQ2Uyo)

**Comment by natalieworth** [comment]
Final files [are in here](https://drive.google.com/drive/folders/1ZGIgAZ-sTNmFSGNxsOWw4HowIgJQ2Uyo?usp=sharing).
