### ISSUE TITLE
Homepage design: benchmarks

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#559]
Gather homepage benchmarks and design ideas for our homepage refresh. 

Note: [homepage wireframe](https://mozilla.invisionapp.com/share/AWWX8UPC6ES#/screens/414160261) and [some older benchmarks](https://redpen.io/p/fm1aa86db66594fc47).

**Comment by sabrinang** [comment]
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/2492510/81592578-086b6700-9373-11ea-9562-9a00e53b0c3c.png">
I included some brand benchmarks (slide 22-25) of org that had a type of social impact/charitable/non-profit arm in prep for brand convo that I think could be useful reference here too: https://docs.google.com/presentation/d/18hqNyB7JnRsjdwoogpQelcX7NFKocagxBSB_GXWUgAU/edit?usp=sharing

**Comment by kristinashu** [comment]
Ah super interesting!

**Comment by kristinashu** [comment]
@natalieworth has started adding some more examples [here](https://redpen.io/p/fm1aa86db66594fc47).
