### ISSUE TITLE
Build Static Page (no external links)

### ISSUE THREAD

**Issue by vazquez** [MozillaFoundation/Design#56]
The first step to building this page is to build the page with no external links, just copy.

**Note:** First iteration of this page will not include the Popular Resources section that currently appears above the fold.

The main meta-issue for this issue is #52

**Comment by cassiemc** [comment]
Here's the latest UI from #30. 

I updated the redpen here with the latest design (also below): https://redpen.io/yv6e5118d61a8af297
Feel free to adjust elements as needed in the build for illustration or other needs. Hoping @vazquez and @sabrinang can make those tweaks as they arise, while I'm on PTO.

The .psd and latest png are in Drive / Design Assets / build.webmaker.org

![build-design-v3c](https://cloud.githubusercontent.com/assets/1186326/8759694/9f59029c-2cc8-11e5-9df7-c790b05ed60b.png)

**Comment by vazquez** [comment]
Boom!! :boom: Slam dunk :basketball:
