### ISSUE TITLE
Update share buttons style guide for 320px width mobile screens

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#565]
Related to https://github.com/mozilla/foundation.mozilla.org/pull/4630#issuecomment-628913089

## Introducing a new style
_Please answer the following:_

1. What element/ style is being changed?
Share buttons for screen widths at 320px width
2. Why it is needed?
The current styles are breaking at this width

  - [ ] Post proposed brand update in Redpen (for desktop, tablet, mobile)
  - [ ] Request design review from design team via R+/R- in Github ticket
  - [ ] Get feedback from devs

**After Approval**
  - [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

## Design Reviewer Checklist
_An issue template in github_
**For design review:**
  - [ ] Is this change justified or are we able to use existing brand elements?
  - [ ] Is the development time viable?
  - [ ] Provide an R+ or R- in the ticket
  - [ ] List reasons for approving or denying changes

cc @kristinashu @sabrinang @beccaklam @natalieworth

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
