### ISSUE TITLE
Mozilla News Beat: May 22, 2020

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#566]
Creating placeholder ticket for this weeks Mozilla News Beat (May 22, 2020)

### Links
Content TBD on Thursday

@sabrinang

**Comment by sabrinang** [comment]
Content: https://docs.google.com/document/d/1JOqDN-4Uh3DV7NXhCn4sSJnoRv0KU_sIfwoBS_zmZeI/edit

Redpen: https://redpen.io/p/nrd4174ad88e710618

Google Drive Folder: https://drive.google.com/open?id=1QwbRrfiaVe5NbqgSb24yEzx-I2Fyfymz&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
Reviewed by Jen/Audrey on slack – closing issue.
