### ISSUE TITLE
Brand & Wagtail Staff Reps Planning Outline

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#567]
### Intro
We want to empower staff to publish content on our website. For this to happen, we want to help prepare members from each team so that they can help be reps to align with brand and to be familiar with our wagtail CMS. 

The intention here is to improve staff understanding and output of producing quality content that is aligned. This will be insightful for us to know how staff use our resources, how to better help them and what their baseline familiarity is so far.

**Ideas**
- this is a collaborative opportunity to team up with engineers as they are developing the CMS platform
- we can use the monthly MoFo staff calls as a platform to expose and promote this work across the org teams 

### Related KR
Design: 100% of staff reps (one rep from each team) know how to use our brand guidelines and our Wagtail CMS (track via a survey)

cc: @kristinashu @cadecairos

**Comment by sabrinang** [comment]
Worked on slides for cade's wagtail presentation this week: https://github.com/MozillaFoundation/mofo-devops/issues/755#issuecomment-632951478 and got more familiar with the tool.

I'll get to focusing on the outline itself next week.

**Comment by sabrinang** [comment]
WIP planning in google doc here: https://docs.google.com/document/d/1KwSZ1UoKp2GWK7wiNEuEijX67waWRdWIv-AlwdzhEs8/edit?usp=sharing

**Comment by sabrinang** [comment]
Draft outline and ideas updated in google doc: https://docs.google.com/document/d/1KwSZ1UoKp2GWK7wiNEuEijX67waWRdWIv-AlwdzhEs8/edit?usp=sharing

@kristinashu @taisdesouzalessa @beccaklam @natalieworth If you have any ideas or comments on brand/wagtail reps please feel free to add and if you have any thoughts on the outline that'd be helpful since it ties pretty closely to our design KR.

**Comment by kristinashu** [comment]
This is great Sabs! Thanks for all your thinking on this. I've left a few comments in the doc.

You could start breaking up that outline into individual tickets.

**Comment by sabrinang** [comment]
Thanks for adding the comments @kristinashu, I'll bring this up in crit tomorrow too. 

**Individual tickets opened:**
- Identify Brand/Wagtail Staff Reps #572  
- Onboarding Presentation for Brand/Wagtail Staff Reps #573 
- Survey for Brand/Wagtail Staff Reps #574 
- Ongoing Relationship with Brand/Wagtail Staff Reps #575

**Comment by sabrinang** [comment]
Shared the doc in engagement team slack channel so the team is aware of this progress and can contribute ideas to the plan – the outline doc can be revised as we go and since individual tickets are are opened, I'll be closing this issue.
