### ISSUE TITLE
Elections hub graphic

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#568]
Creating a placeholder ticket for the election work with the content team. We are meeting on Wednesday and I will update the ticket.
https://docs.google.com/document/d/1ZXUXbFX4LdqAYLfzGihOmkQp-gVJzt0p5WxexuaKsCI/edit#

cc @kristinashu @sabrinang

**Comment by natalieworth** [comment]
[Content strategy doc is here](https://docs.google.com/document/d/1ZXUXbFX4LdqAYLfzGihOmkQp-gVJzt0p5WxexuaKsCI/edit#)

**Comment by kristinashu** [comment]
Here is the [stakeholder interview](https://docs.google.com/document/d/1dWSaDZvP97_dEkIWLFqfDvtlbxZtNYjSmdrSzg3g-_A/edit?ts=5f33edbe#) for an elections hub.

I've set up a hub here https://foundation.mozilla.org/en/campaigns/elections/ and Audrey will add content to.

I think the only design need is to create a graphic for the banner.

**Comment by natalieworth** [comment]
[Banner and icons are here](https://foundation.mofostaging.net/cms/pages/1096/edit/)
[
Also in Redpen here for specific comments](https://redpen.io/p/aecd54fc2a20c511c0)

**Comment by natalieworth** [comment]
Hey @kristinashu , Audrey is good with the election hub site. I'm having trouble seeing it live on the site outside of Wagtail though? I'm not sure what I'm doing wrong ah! 

[Here is the page in wagtail](https://foundation.mofostaging.net/cms/pages/1096/edit/)

[But the live page isn't updating](https://foundation.mozilla.org/en/campaigns/elections/) (not sure if it's a permission thing?)

**Comment by kristinashu** [comment]
Oh it looks like you're new version was done on staging, not production.

**Comment by natalieworth** [comment]
DED. Ty! 

I've updated and images and header [are now live](https://foundation.mozilla.org/en/campaigns/elections/). 

cc @audreymofo
