### ISSUE TITLE
Evaluate After Action Pages / Share Flow

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#569]
## Intro
After talking to Kaili regarding advocacy tools two weeks ago https://docs.google.com/document/d/1iTasgajM-iv7PZNThTsjHVOrJKOFi8YgwUaroT6CUqQ/edit#heading=h.lir8ufsrfjkb, there are a few things to consider.

### After Action Pages:
Here are current examples of after action flows:
**Form**
<img width="1526" alt="Screen Shot 2020-05-25 at 4 01 50 PM" src="https://user-images.githubusercontent.com/2492510/82847922-9d0eb280-9ea5-11ea-953d-29549c4e1663.png">

**Petition**
<img width="1588" alt="Screen Shot 2020-05-25 at 4 02 00 PM" src="https://user-images.githubusercontent.com/2492510/82847934-b0218280-9ea5-11ea-9194-5ffe88d9d677.png">

Some feedback we got is that in some cases they want:

- To make buttons more prominent
- To make confirmation more obvious you signed
- To change share language copy
- To change share actions (example: share blog post?)
- To not want share language/buttons (just confirmation? redundant language)

### Benchmarks:
Kaili share a benchmark https://weareultraviolet.org/ I think the assumption here is that they use [ShareProgress](https://www.shareprogress.org/) but they use [EveryAction](https://www.everyaction.com/get-demo) integrated in their website. This an example of prominent share actions and the flow is pretty straight forward for reference:
<img width="1583" alt="Screen Shot 2020-05-25 at 4 01 40 PM" src="https://user-images.githubusercontent.com/2492510/82848034-5e2d2c80-9ea6-11ea-9a77-b092c3cd0b88.png">

### ShareProgress:
I believe this is related and I think we should evaluate the utility and purpose of ShareProgress (to fill out an up to date brief) and go through security/legal review. It seems like this was a tool introduced ages ago, been unmaintained and left unutilized so we should understand the value of it in today’s contexts/goals now that we have our own website. We can consider downsizing the plan as well as it doesn’t seem like it has good return on investment in past page/button usages.

After becoming familiar with shareprogress via template pages, we should think about the overall desired share userflow and how this fits: 
- Consider alternative options like if we revamp our after action pages on our site is it necessary to redirect users elsewhere to shareprogress (I don’t think we want to lead them off our site) 
- Consider if the tool is up to standard in terms of accessibility and maintenance (flagging that some of the design/code standards are out of date)
- Buttons: Can we A/B test share language without using shareprogress? (which seems like the main value add) 

cc: @kristinashu @mmmavis

**Comment by sabrinang** [comment]
reposting some ShareProgress concerns from https://github.com/MozillaFoundation/Design/issues/517#issuecomment-632959999

> **Things to note:**
> - ShareProgress’ privacy policy is very dated (2013) 
> - There is an assumption it has been reviewed in the past if a contract was signed but isn’t clear if this has passed security review – can we check this? _(the tool and practices just feel very out of date)_
> - Use case still aren’t that clear to me if these pages will divert traffic away from our main website from existing email supporters since these pages are not connected to our website in anyway – should we connect this back to foundation.mozilla.org? 
> - Even though if it is used with existing subscriber/followers, we’d want them to be pulled into our website somehow or in case new audiences stumble upon this share page too 
> - We can’t change the content / share method itself (example: if we want to include instagram as a method to share instead)
> - Not sure if there is a better solution to share than this but I'd consider downsizing since the analytics show these pages don’t get a lot of traffic for the monthly 1000usd billed

**Comment by sabrinang** [comment]
I met with Kaili and @mmmavis to chat about advocacy tools. See meeting notes captured here: https://docs.google.com/document/d/1iTasgajM-iv7PZNThTsjHVOrJKOFi8YgwUaroT6CUqQ/edit?usp=sharing)

**ShareProgress:**
- Kaili asked if we should clean up old pages and templates _(lots of dated content present)_
- Share buttons: The ability to a/b test various social messages, see analytics and have automatic traffic allocation to best message is the main value add for main email use case for ShareProgress
- Share pages: These are not frequently used but for email asks and cta they want to link to a share ask rather than linking to the content itself _(example: blogs or pages don’t have prominent share options or customizable ones and rather have a focused share page ask)_
- ShareProgress seems like the main third-party tool the advocacy team is using and I mentioned that it doesn’t have up to date design/dev practices, unclear if it has passed security review and feels detached from our website
- Regardless of tool, the main goal is about engaging people to share the content itself 

**Some ideas for next steps:**
- We got some good feedback on what our site could do better with sharing _(consider if share options or share pages could be integrated on our site experience more or improved)_
    - ideas: improving share options on wagtail page content, improving after action share flow or create a wagtail sharepage template on fo.mo
    - Consider benchmarking ideal tools that help engage people to share the content or strategize how to leverage and shareprogress better
- I’d follow up to ensure share progress is good for security/legal stuff _(Mavis found an old bugzilla issue for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1249282)_
- ShareProgress is a small team of ~5 to reach out to if you have questions

cc/ @anilkanji

**Comment by kristinashu** [comment]
Closing this! I believe Shing will **eventually** be re-evaluating our petitions and flows with the campaigners.
