### ISSUE TITLE
Display the Webby Award badge on PNI Homepage

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#570]
### Intro
*Privacy Not Included won People's Voice Winner 2020 in the [Activism Website Category](https://winners.webbyawards.com/#/winners/websites/general-websites/activism). We want to display and recognize that we've won this on the homepage for visitors to see.

### Links
Webby Logo and Site Badges: https://www.webbyawards.com/resources/logos-and-site-badges/

cc: @kristinashu @natalieworth

**Comment by phildexter** [comment]
Hey @mmmavis we're hoping you can implement this in this sprint also - can you factor that in when adding your final tickets please?

**Comment by mmmavis** [comment]
Yup can do!

**Comment by mmmavis** [comment]
@phildexter do we want to create a dev ticket for this? Or simply label it with an additional "engineering" label is enough?

**Comment by phildexter** [comment]
@mmmavis what would you prefer?

If we have a single ticket we should up the estimate so it includes your time also.

**Comment by mmmavis** [comment]
Hey @phildexter I prefer having them separate. I'll create a dev ticket and assign it to myself. I'll have to leave the estimate blank until I see the actual design / specs.

**Comment by beccaklam** [comment]
@sabrinang @kristinashu can I get some feedback on the placement of the award?

[Desktop](https://mozilla.invisionapp.com/share/SNXLA6DM2H8)
[Mobile](https://mozilla.invisionapp.com/share/6YXLA6V32MC)

**Comment by sabrinang** [comment]
Nice iterations Becca, I'm leaning towards the badge being on the banner (not overlapping). Not sure if the guide is localized or not but if the heading becomes longer I think it would interfere with the overlapped badge above content box. Not having it overlap might transition better from desktop to mobile as well (maybe less jumpy relocation of it being half overlapped to quarter overlapped). I think I prefer the black so the yellow visual attention goes to the emoji.

**Comment by beccaklam** [comment]
Thanks @sabrinang! Looking at the designs again I agree with you, let's go with the badge on the banner without the overlap. I actually prefer the gold haha, I feel that it connects well and guides your eye to the emoji. But we can show Jen and see what she thinks?

**Comment by beccaklam** [comment]
Just slacked Jen this [redpen](https://redpen.io/p/pf8b9ed17a7d55d6a7).

**Comment by beccaklam** [comment]
Got feedback from Jen:
- Use "webby award winner - people's choice" badge
- Use black version
- Mock up left side placement
[Redpen updated here](https://redpen.io/p/pf8b9ed17a7d55d6a7)

@sabrinang @kristinashu thoughts? Will also slack Jen!

**Comment by beccaklam** [comment]
Updated Mavis' design to dev ticket #4736. This is done!
