### ISSUE TITLE
Identify Brand/Wagtail Staff Reps

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#572]
### Intro
Identify staff that could be informed representatives to champion brand and CMS usage on their team. 

**Ideas:**
- check out who is active on wagtail currently 
- check with individuals and their team
- ideally we will have reps across various teams

### Links
Related outline issue: https://github.com/MozillaFoundation/Design/issues/567

cc: @kristinashu

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
