### ISSUE TITLE
Virtual Dialogues and Debates: Video branding assets

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#576]
### Intro

Plans for June 30 D&D: https://docs.google.com/document/d/1jWiB60eVkq8YND0EIS_BWiKUCWL70JkgPEp3WAXt2-M/edit?usp=sharing

- Read the plan doc
- Look into what we current have and have done (potentially related tickets https://github.com/MozillaFoundation/Design/issues/432 or https://github.com/MozillaFoundation/Design/issues/479)
- Consider any D&D or Mozilla branding directly in the broadcast (lower thirds, etc.)
- Create assets

cc: @kristinashu @KevZawacki

**Comment by sabrinang** [comment]
@KevZawacki 
I reviewed what we currently have and mocked up some design ideas: https://docs.google.com/presentation/d/1nSM9vL7ruoM_j3xaBgU6x2YlQASkKm5RIXXHyUhBBeo/edit?usp=sharing

I left some questions, ideas and suggestions in the doc as I'm not quite sure what the the live stream implementation limitations are so feel free to leave and comments and feedback

**Comment by KevZawacki** [comment]
Hi @sabrinang, these are fantastic -- thank you! I left some comments, but ultimately defer to your design judgement. Whichever options you think work best, let's do. 

Just one change: Let's not include a donation ask on the end card. I can some speakers being uncomfortable with that.

As to what is technically possible, I've tagged @marcwalsh into the document. @marcwalsh, can you let us know if @sabrinang's suggestions are / aren't possible in AirMo?

**Comment by sabrinang** [comment]
@KevZawacki @marcwalsh Do you have any specs on how to technically help implement these pieces?
- I can export screen cards as jpg/png. 
- For overlay elements, how should I export the assets (svgs)? 
- For elements like typography and layout, would providing dimensions and sizes be helpful or illustrator mockups enough?

**Comment by marcwalsh** [comment]
Hey @sabrinang 

Could we get
- PNGs for Title Cards (1920 x 1080px)
- PNGs with an Alpha Channel for overlay elements
- Font sizing would be great for the typography (when used on a 1920x1080 px canvas size) and just an example would be great for where to position text 

- If we could get AI files to use as templates that would be great, especially for lower thirds / overlays

**Comment by KevZawacki** [comment]
Thank you, @sabrinang! These are fantastic. 

I've attached speaker headshots here. And, the panel is slated for 11am PT / 2pm ET / 7pm BST.
<img width="182" alt="AO" src="https://user-images.githubusercontent.com/11045250/84380281-15b78380-abb5-11ea-925c-d2f2cf1dbce8.png">
<img width="286" alt="MD" src="https://user-images.githubusercontent.com/11045250/84380283-16501a00-abb5-11ea-8a15-52aff55eb498.png">
![SF](https://user-images.githubusercontent.com/11045250/84380286-16e8b080-abb5-11ea-819f-7455387b5ddb.png)
![XH](https://user-images.githubusercontent.com/11045250/84380288-16e8b080-abb5-11ea-9d8b-7641cfc0c69b.jpg)

**Comment by sabrinang** [comment]
**Screens**
@KevZawacki @marcwalsh Updated D&D screen cards and thumbnail here: https://drive.google.com/open?id=1lBiBqkYzzSF8ECpuKYllHpp64LI6ozx-&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Social**
@audreymofo Here are the social assets (instagram/twitter): https://drive.google.com/open?id=1ksK7TEyvJ-jJgYOayi1cJBsn2GzYeADz&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Video Assets**
@airmoandy Overlay elements, png/ai specs, bumper clip are here: https://drive.google.com/open?id=1f0CPZN7HgvihjFmYm29UwGUtfOBhaH8i&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Please review and all of these assets will be stored in this [gdrive folder](https://drive.google.com/open?id=1Z0E7oV7uLvKxEV5N2Qi-WwAXFb8yadxj&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) for reference

**Comment by sabrinang** [comment]
Thumbnails on AirMo and YouTube can be updated with the [exported thumbnail](https://drive.google.com/file/d/1fi-a7-ugChRzbVtI2e0Epy0Vfgp8PZ-w/view?usp=sharing):

<img width="351" alt="image" src="https://user-images.githubusercontent.com/2492510/85323140-58fad780-b47c-11ea-89b6-c7ab3d384bd8.png">

<img width="214" alt="image" src="https://user-images.githubusercontent.com/2492510/85322297-f523df00-b47a-11ea-8bff-ac60e123b53e.png">

For the video branding, I've exported the logo and gave type specs but wasn't applied for this round, background was used for a border though?:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/2492510/85323029-2b159300-b47c-11ea-8e6b-e42afb3fd51c.png">

@KevZawacki Is there any other video branding assets you need? or any other specs I can help provide to be applied? (it wasn't really clear what can or can't be done so any tips or feedback would be great to know how I can wrap up this issue)

**Comment by KevZawacki** [comment]
Hi @sabrinang, thanks as always for the excellent design :-)

No further assets that I can think of, but @marcwalsh can confirm.

**Comment by phildexter** [comment]
Hi guys - we're going to close this ticket as we feel like it's done - if you need anything more please create a new ticket and assign it to @kristinashu
