### ISSUE TITLE
Smell test (is a design resource worth the investment?)

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#58]
Creating a design team resource is great, but only if it saves more work than it creates. Maybe we review this list first:

 - [ ] Can we create it quickly to validate its usefulness?
 - [ ] Can we create it while working on a specific design project to help specifically with that project?
 - [ ] Will it be easy to update and maintain?
 - [ ] Can it be made as a tool rather than a reference or guide?

**Comment by cassiemc** [comment]
I love this list but not sure how to close this bug. Feels like we are already doing this when opportunities arise but could possibly be more systematic about it. Either way we should probably document this list elsewhere. Thoughts @xmatthewx?

**Comment by xmatthewx** [comment]
Maybe there's a statement at the bottom of http://build.webmaker.org/design? A manifesto or reminder to create easy to validate and maintain tools, not dusty documentation.

**Comment by xmatthewx** [comment]
Or just close this!!

**Comment by cassiemc** [comment]
I think it's a cultural thing. Let's stay on top of it.
