### ISSUE TITLE
PNI: Revise Heading Styles (a11y improvement/style alignment)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#585]
### Intro

Related to PR https://github.com/mozilla/foundation.mozilla.org/pull/4734#pullrequestreview-424030062. As devs are cleaning up code and doing accessibility checks on PNI, there is a question around headings particularly around improving semantic tag usage and aligning or using style classes that exist in the style guide. 

The example use cases in discussion are the more text heavy, about pages: https://foundation.mozilla.org/en/privacynotincluded/about/why 
Notice headings like `Our Minimum Security Standards`, `There is a Creep-O-Meter.`, `Bigger and better.` etc are styled and implemented as bold paragraph instead of a proper heading.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/2896608/83912532-ddcabf00-a722-11ea-9800-6921a3d6339d.png">

Some suggestions were: 
- avoid adding a new heading style that looks like bold paragraph as that is the style for `<p><b>` already (which semantically shouldn't be used as we opt for HTML heading tags instead)
- to revise and test established hierarchy of headings in sketch to reflect semantic and style classes to see if introducing a new style or overrides are necessary
- update sketch files to reflect what is live

cc: @kristinashu @Pomax @mmmavis

**Comment by mmmavis** [comment]
If webpages are implemented more semantically*, the outcome of the HTML outline gets better and more meaningful. This helps not only for a11y but also for bots, apps, and services to look up for content more easily.

To test HTML outline of our webpage, you can go to https://validator.w3.org/#validate_by_uri+with_options and select the "Show Outline" option.

---

**Semantic HTML**
One example would be implement headings using the dedicated HTML heading tags `<h1>` `<h2>` ... to `<h6>`

More resource for semantic HTML: https://en.wikipedia.org/wiki/Semantic_HTML

**Comment by Pomax** [comment]
I think one reason why things look different is that PNI sort-of-is and sort-of-isn't its own website still. It would be nice if we could start to enforce the same styleguide we use for the main fomo site on PNI as well, in which case using `<h1 class="h1-heading">` through `<h3 class="h3-heading">` (I don't think we nest deeper than 3 in the PNI content) would be quite nice.
