### ISSUE TITLE
Dialogues and Debates: June 30, 2020

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#588]
### Intro
Create assets for the upcoming D&D, requests from the last talk included:
- Screen title cards (Intro, End)
- Social Media (Instagram (post and story), Twitter)
- Thumbnails (new tab, youtube/airmo)

### Links
Content here: https://docs.google.com/document/d/1jWiB60eVkq8YND0EIS_BWiKUCWL70JkgPEp3WAXt2-M/edit?usp=sharing

Related to https://github.com/MozillaFoundation/Design/issues/576# but getting too large with video stream branding asset and June 12th assets so separating issue tracking here.

cc: @KevZawacki @kristinashu

**Comment by KevZawacki** [comment]
Thank you, @sabrinang!

You can find copy + images for the graphic [here](https://docs.google.com/document/d/1jWiB60eVkq8YND0EIS_BWiKUCWL70JkgPEp3WAXt2-M/edit#bookmark=id.3ovbp3trkjzs).  

Do you think it's possible to have an image ready one week from today (June 25)?

**Comment by KevZawacki** [comment]
Hi @sabrinang, we finally have all our speakers confirmed and content finalized 😅 I've pasted it below.

Please let me know if you need anything further!

[Mozilla logo]
Dialogues & Debates
**Protests, the Pandemic, and Misinformation**
with Camille François, Dia Kayyali, Julie Owono, and Neema Iyer
Tuesday, June 30 at 8am PT / 11am ET / 4pm BST

![Camille](https://user-images.githubusercontent.com/11045250/85460233-05b68100-b571-11ea-9c5a-93953132cbd6.jpg)
![Neema](https://user-images.githubusercontent.com/11045250/85460238-064f1780-b571-11ea-88da-ef41b049bfc6.jpg)
![Julie](https://user-images.githubusercontent.com/11045250/85460245-06e7ae00-b571-11ea-86af-ab5c6ea21abd.jpg)
![Dia](https://user-images.githubusercontent.com/11045250/85460248-06e7ae00-b571-11ea-9313-05809503368a.png)

**Comment by sabrinang** [comment]
@KevZawacki Please review D&D June 30 graphics on redpen: https://redpen.io/p/wv51eef5a5c523427b

**Includes:** Title card, end card, background, youtube/airmo thumbnail, twitter post, instagram post, instagram story and new tab thumbnail 

All graphic assets exported in gdrive here: https://drive.google.com/open?id=1p9z0X2OGI9VN5J6qSEB-2COw_Z6jhwxT&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by KevZawacki** [comment]
These are perfect -- thank you, @sabrinang ! 😄😄😄

**Comment by sabrinang** [comment]
**Note:** Photo and name orders updated after review.

Redpen revised: https://redpen.io/p/wv51eef5a5c523427b

All graphic assets updated in gdrive: https://drive.google.com/open?id=1p9z0X2OGI9VN5J6qSEB-2COw_Z6jhwxT&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
