### ISSUE TITLE
Open design feedback 

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#59]
@LauraReynal asked if she could stop by here for some design feedback. I thought, why not? Let's welcome design projects that have no obvious home, from MoFo or in the world beyond.   

cc @flukeout @vazquez @sabrinang @lovegushwa @cassiemc

**Comment by LauraReynal** [comment]
YAY I love the fun label :-) 

Do you folks have any recommendation for this diagram below ? This is due for thursday CET timezone, so no need to spend extra time on it, but quick feedback that I can implement would be truly, greatly appreciated :smile: 

Context: 
this diagram illustrates 1 year of research methods for a future project, it will be inserted in a proposal. 
Goal:
Make the reader understand in 1 glimpse what is going to happen, and the different parts of the project (product, curriculum, interview, coms, metrics)


![gates - digital skills observatory - new page](https://cloud.githubusercontent.com/assets/8261945/8809293/11878768-2fe8-11e5-914b-08b9681e95f7.png)

**Comment by xmatthewx** [comment]
Looks good. Consider reducing the elements so it's a quicker read: 

 - align your horizontal rows
  - unify box heights and align across columns
  - fit things within quarters
 - reduce boxes and columns
  - "Group A&B" should be between the groups. Remove the header box. Add an arrow down from "150 participants."  
   - "Proto products intro" and "monthly digi skills tranings" could be one box with two halves. One arrow entering and one leaving.
 - reduce the text
  - Monthly blog posts is repeated many times. Can this be generalized?
  - Remove "...for the first 3 months." Q1 label says that. 
  - Make quarter labels much much bigger. Remove "of the study"

**Comment by LauraReynal** [comment]
This is terrific. Thank you so much ! 

I made changes according to your feedback and also on content according to the team. 

* Group A&B: I'd like to keep the quantitative research aside from the qualitative experimental research, so I think it should stay appart on the side. The message is : "In parralelle, data collection will happen all the time for both groups". So I added the label "Quantitative study" to make that point clearer. 

* Arrows: I tried without arrows everywhere to see if better. 

thoughts ? 
![gates - digital skills observatory - new page 1](https://cloud.githubusercontent.com/assets/8261945/8812334/c0b97788-2ffb-11e5-966e-7fc2f8511733.png)

**Comment by xmatthewx** [comment]
Now that's the stuff. 
 - Quantitative column makes sense
 - Little back arrows are fine
 - You could state "continuous documentation" once at the top of Q1 and then just use two longer yellow arrows. 
 - "Research closing" should be centered on "150 participants"   

Minor bits. This looks super fine.

**Comment by LauraReynal** [comment]
Thank you so much for the feedback :yellow_heart: 
This ticket can be closed - I shipped the graphic !

**Comment by cassiemc** [comment]
Sounds good, I like the process!
