### ISSUE TITLE
Images and content mozilla.org

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#590]
Tais has organized everything [in this copy doc](https://docs.google.com/document/d/1brUYaxkHv8xQEsfjnmcLd60rjgDrSOhRhMr15uF0YOA/edit?usp=sharing).

> Anil requested Xavier and Tais come up with suggestions for content to add to MoCo page. The deadline is Monday (June 22nd) afternoon.

> The mockups' links are in this doc (page 2): https://docs.google.com/document/d/1brUYaxkHv8xQEsfjnmcLd60rjgDrSOhRhMr15uF0YOA/edit?usp=sharing

> There are 2 things to be done, from the design perspective:
• Once Xavier shortens the title copy for the last card (How do we collaboratively...), we should place it in the layout (ideally it should be a 2 lines title) - there are 2 mockups: one for blurb 1 and one for blurb 2.
• Once we have the blurb copy for the same card (now we have a "lorem ipsum" placeholder, place it there too. Same thing, place it in the 2 mockups.

Working files are in [Drive here](https://drive.google.com/drive/folders/1q_NzEuUn6fgUDeHeqxSn86NKFqZ8KJBR
).

**Comment by taisdesouzalessa** [comment]
Made some edits on Tuesday (June 23) and had some revisions by MJ and Xavier on June 24th. Also exported the images to the final sizes.

Final mockup:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/22157921/85630697-fabf2780-b628-11ea-8095-6f3d3a2b552f.png">

Final doc (source of truth for copy and links to final mockups) - https://docs.google.com/document/d/1brUYaxkHv8xQEsfjnmcLd60rjgDrSOhRhMr15uF0YOA/edit?usp=sharing
