### ISSUE TITLE
Graphic: Opt out of FB political adverts 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#591]
Create multiple graphics for facebook 'opt-out' of political ads for instagram. (estimating 6-8 screens for the post and also possibly story, but need to confirm with Audrey tomorrow)

https://docs.google.com/document/d/1HKEb2F_dT3ZI4A1iGD5CoiXraSyEHsVw7EZHoNV84dg/edit

**Comment by natalieworth** [comment]
Waiting on copy still, but I got a start on brainstorming 2 directions for this on Friday:
<img width="560" alt="Screen Shot 2020-06-28 at 9 11 49 PM" src="https://user-images.githubusercontent.com/14876567/85972175-12c5dc80-b984-11ea-8b8b-5f1c861031c8.png">
<img width="560" alt="Screen Shot 2020-06-28 at 9 11 56 PM" src="https://user-images.githubusercontent.com/14876567/85972177-135e7300-b984-11ea-87d6-dc58e5999e46.png">
<img width="559" alt="Screen Shot 2020-06-28 at 9 12 22 PM" src="https://user-images.githubusercontent.com/14876567/85972178-13f70980-b984-11ea-98ca-c2646c85efc8.png">

cc @audreymofo

**Comment by Audreymofo** [comment]
Thanks @natalieworth ! I've got copy now here: https://docs.google.com/document/d/1HKEb2F_dT3ZI4A1iGD5CoiXraSyEHsVw7EZHoNV84dg/edit. I like the thumbs down an the very Facebooky colour scheme, but I think it would be good if the first screen looks more explicitly like a Facebook advert.

**Comment by natalieworth** [comment]
Most recent version [(draft 1) is here](https://redpen.io/p/cu50842c9b3c42747e)

**Comment by natalieworth** [comment]
[Draft 2 is here](https://redpen.io/afec1b78fe66241f2d) and just waiting on screenshots (and possible content changes depending on if this feature is available to everyone in the US).

**Comment by natalieworth** [comment]
Final [files are in here](https://drive.google.com/drive/u/1/folders/1g0Qz0chSEtZulmiZMzxIIS-8CSNDm8rd) and have sent to Audrey for posting on Monday.
