### ISSUE TITLE
Graphic: Stop advertising on FB

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#592]
Instagram post asking people/ companies to stop Facebook advertising. 

Graphic ask:  One square image that illustrates people not buying Facebook adverts because of hate speech, disinformation

[Copy is here.](https://docs.google.com/document/d/1rY6UJA26ryg8JGXW3QQ7VT5Pgx_oCNlsag8VaaRuOe0/edit)

**Comment by natalieworth** [comment]
Final files are in here: https://drive.google.com/drive/folders/1ZdVpPHtyrtK2GjcG4nCkOKfBO0g1b2AJ?usp=sharing
