### ISSUE TITLE
Graphic: EARN IT - due June 29

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#594]
Request from Kaili: 

We're launching a campaign telling U.S. Congress to stop the EARN IT Act which would jeopardize encryption.

https://docs.google.com/document/d/1MXLfUDwL2f9OYEwEiAkxLsen0rRjS1PHQ5ZEQV_BEaI/edit

**Comment by sabrinang** [comment]
Met with Kaili today to go over strategy brief: https://docs.google.com/document/d/1KkpoBFu_f6P_8U69K6-RIPeysO1O-wLT8co4GKtVMi8/edit

**Launch date:** July 1 (I'll be on holiday next week so I aim to finish this week)

**Graphic assets to produce:**
- [ ] Email graphic _(call out box template with graphic - style b)_
- [ ] Wagtail petition page promote tab image (_share thumbnail - can be used for shareprogress, twitter etc.)_
- [ ] Social for instagram _(post / story - can check with Audrey if there is preferred format)_

**Comment by sabrinang** [comment]
Iterated some design options and shared at crit for feedback. Refined two options from crit feedback and shared redpen with Kaili: https://redpen.io/p/fkb1b5c6f91d1a1c3a

She'll share it for feedback from Heather (MoCo) as well as they are working on this too.

**Comment by sabrinang** [comment]
Kaili gave her feedback this morning so we are moving forward with dark theme designs with varied messaging content so we can test against each other and switch up the content.

I've updated the redpen with the additional version: https://redpen.io/p/fkb1b5c6f91d1a1c3a

I exported three copy versions in gdrive here: https://drive.google.com/open?id=1wNX8dFrXijFC0d4P1-G_JsIEnaJ5PgHO&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Kaili has reviewed — closing issue.

**Comment by kristinashu** [comment]
Nice! This style will be a useful edition to our library.
