### ISSUE TITLE
Create Gifs for Giphy: Part I

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#598]
Request from Audrey to start creating gifs for Giphy that we can use to set up our own channel and use on Instagram. For now, this is tactical, but gifs could become part of marketing plans in the future (for example, MozFest gifs, PNI gifs, or as part of social media toolkits for for campaigns shared with partners). More in this doc https://docs.google.com/document/d/1R-mrqlHAckdPWg9ER_YDBWjFt-ofy82YmsnxsKVojt8/edit

### Goals
- Create fun gifs we can use for appointment content on Instagram like News Beat
- Create fun gifs that people can use in Instagram stories to talk about Mozilla

### Todo
- Kick-off with Audrey
- Create some Gifs!
- Determine next steps

**Comment by kristinashu** [comment]
I think this is done https://redpen.io/p/ou882e791c7a07f643 and ready to close!

https://media.giphy.com/media/vA4EnqvJxDv2g/giphy.gif

Part II happening here https://github.com/MozillaFoundation/Design/issues/615

**Comment by natalieworth** [comment]
Yep! [File's are in here for reference](https://drive.google.com/drive/folders/1zyKcPDU2WS2DSMRVt6ARFdKUYn7D5DXW?usp=sharing) :)
