### ISSUE TITLE
Banner Layout

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#605]
### Intro
Based on the banner direction, we intend to accommodate the inclusion of photography and iterating on the banner height on various devices will help showing more of the images without being cropped. We can also iterate on the cut out style by the banner in the layout.

### Links
related to https://github.com/MozillaFoundation/Design/issues/578

cc: @kristinashu @natalieworth

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
