### ISSUE TITLE
Try out visual triage on Webmaker

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#61]
I've added a bunch of Webmaker features to a triage matrix to see if it helps us set priorities. 

 1. find [the slide](https://docs.google.com/presentation/d/1-BDvdjNd8GAfgG4IV_iy_0TfxevxbfJTyejv6YzAQiE/edit#slide=id.gc36892fe0_0_0) with your name on it 
 2. sort items on grid
 3. compare with each others and discuss over Vidyo

cc @vazquez @LauraReynal @flukeout

**Comment by LauraReynal** [comment]
Hey @xmatthewx this is awesome -- while trying it I realise that I have little idea of the cost of a project. 
For example, I would suspect that stickers are a high cost ?

Do we have a way of assessing what is high cost and what is less costly ?

**Comment by LauraReynal** [comment]
Would be nice to add " video " or "vine support" in the list

**Comment by xmatthewx** [comment]
Some things would be more complicated to design and test, but cost is often best guessed by engineers. We can focus on the vertical axis.

**Comment by LauraReynal** [comment]
Ok 2 comments 
1. the exercice is awesome, we should do it regularly during the UX Jam force
2. its really hard to do ! :imp:

**Comment by xmatthewx** [comment]
> Would be nice to add " video " or "vine support" in the list

Feel free to add a couple missing items if they're important

> its really hard to do ! :imp: 

Surprisingly so!! I just added a grid. Made it easier for me by reducing the infinite options.   

--
related to: #55

**Comment by LauraReynal** [comment]
Agree with the grid, there was too much space.

**Comment by xmatthewx** [comment]
### Visual triage test results 

@vazquez @flukeout @LauraReynal and myself sorted potential features based on our expected impact on users (high, medium, low).  

Twelve out of sixteen features were rated as high impact by 2 or more people. Of these: 
 - Three features were rated as high impact by 3 people. 
 - One feature was unanimously viewed as high impact. 

Sorting was done independently and quickly. It might have been a bit too quick, but I think it was an adequate gut check that could realistically be repeated twice a month. 

1) 3 out 4 of us rated FTU prompts as high impact. @vazquez, rated it as medium impact. He has already designed it the UI. I’m Glad that this is in motion for the build next heartbeat. `build`

2) 3 out 4 of us rated Send element to front/back as high impact. I said it was medium. The z-index bug has been squashed. It would be good to ask/test users to see if they want this new feature. `validate/test`

3) 3 out 4 of us rated the removal of the pencil icon as high impact (replaced with page tap-to-edit). I rated it as medium. User tests showed ambiguity around this feature depending on user origin/experience/device. But, the change would align somewhat with the last feature... `validate/test`

4) All of us agreed that reducing the steps it takes to add a feature would be high impact on user experience. We have a UX spec. I don’t believe it requires any new UI. Building it should be relatively simple and low risk since it involves removing steps, not adding new functions. I suggested we elevate this issue and implement it as soon as possible. https://github.com/mozilla/webmaker-core/issues/238 `build`

Overall, the process was quick, painless, informal, and informative.  

[1] Features - high impact votes 
 * FTU Prompts - 4
 * Send to Front/Back - 3
 * Reduce Add steps - 3
 * Tap vs pencil edit pg - 3
 * Android header - 2
 * Try it w/o login - 2
 * Link to other proj - 2
 * Move pages - 2
 * Stickers - 2
 * Copy elmnt/pg - 2
 * Page bkgrnd color - 2
 * Welcome screens - 2
 * Set start page - 1
 * Link to URL - 1
 * Animated GIFs - 0
 * Transparent PNGs - 0

**Comment by xmatthewx** [comment]
My review of results was crazy long. Here's a visual summary of the features rated with the highest impact for users: 

<img width="970" alt="screenshot 2015-08-04 10 53 45" src="https://cloud.githubusercontent.com/assets/53411/9063868/b8034442-3a97-11e5-9be3-8f0cf37bb52c.png">

#### Ricardo's perspective

<img width="970" alt="screenshot 2015-08-04 10 56 51" src="https://cloud.githubusercontent.com/assets/53411/9063867/b7f5a206-3a97-11e5-9212-d48d3c5c8d0c.png">

**Comment by cassiemc** [comment]
@xmatthewx have you gotten what you need from this bug? can we close? next steps here?

**Comment by xmatthewx** [comment]
Totally. I should blog about it some day, but today is not that day. :smile:
