### ISSUE TITLE
Graphics: #stophateforprofit Day of Action

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#611]
### Intro

Modify or adjust graphics from Stop Hate for Profit set: https://github.com/MozillaFoundation/Design/issues/604
This will accompany social, blog, email launching July 24th, 2020. Consult Audrey on what needs to be modified but it should match the original set.

### Links
RASCI Campaign doc: https://docs.google.com/document/d/1fYS3jlMNFTv5CLfZIJyRYTduqX0yIvHrBpm3XwCQn9o/edit?usp=sharing

cc: @kristinashu

**Comment by sabrinang** [comment]
@audreymofo has given more details via slack:

She's requesting an iteration of this image: https://drive.google.com/file/d/1hNhiDbDmohxQYZ4DsGCKue3CJ6y2QpBh/view for: 
- blog + link preview image _(this will need to be translated)_
- Instagram story
- Instagram feed 

But that says #StopHateForProfit Day Of Action

We'll also need "Day Of Action" translated for the link preview and blog version. Theo says we should have FR/DE  later today, ES/PT tomorrow evening our time.

**Comment by TheoChevalier** [comment]
Hi everyone,

Here are the first translations for `#StopHateForProfit Day Of Action`:

FR: `Journée de mobilisation #StopHateForProfit`
DE: `#StopHateForProfit Aktionstag`

**Comment by natalieworth** [comment]
English, German and French are done and [in this working file](https://drive.google.com/open?id=1n8JcrMhoFQ-oVnH0qJ1fnAIRQtaCTaqD&authuser=natalie%40mozillafoundation.org&usp=drive_fs). 

Theo said we can complete/ wait until Thursday when I'm back, so no rush on these (since we still have to wait for another translation to come in). 

ccing @kristinashu and @sabrinang in case you need this file while I'm out tomorrow

**Comment by natalieworth** [comment]
https://redpen.io/p/xv1f854f951a542f5f

**Comment by Audreymofo** [comment]
Thanks Natalie! Only the blog and link preview images need to be translated. Instagram content is only needed in English if that saves you some time.

**Comment by TheoChevalier** [comment]
@natalieworth  Alright, here are the remaining translations:

ES: `Jornada de acción #StopHateForProfit`
PT: `Dia da Ação #StopHateForProfit`

Also one ask, would you mind updating the French one with the following translation? I wasn’t too fond of the literal translation in the first place, but I am now convinced this is the way to go:

FR: `Journée d’action #StopHateForProfit`

Many thanks! 🙏

**Comment by natalieworth** [comment]
Exports are in here https://drive.google.com/open?id=1nVTaYEgHlAxujzzZtLq4WdGaXRIz5Jjx&authuser=natalie%40mozillafoundation.org&usp=drive_fs

**Comment by natalieworth** [comment]
[Final assets are in here](https://drive.google.com/open?id=1n5HTjLm0J8QvGA-UlFneavmw9MRkjBtB&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
