### ISSUE TITLE
Facebook Video

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#612]
### Intro
A video addressing facebook issues is being planned across content/advocacy/MoCo teams. There is no set date to launch but it will be posted after July 27th and videos take a while to produce. Audrey has more context as this project develops.

### Links
WIP content doc: https://docs.google.com/document/d/1GvxuDyjDF8Spl6tjkNuawBFcwnL2nyTy0JY2VMSYqac/edit?usp=sharing

cc: @kristinashu

**Comment by natalieworth** [comment]
I haven't heard any updates on this other than it's delayed. 

@kristinashu Should I icebox until the content is approved/ ready?

**Comment by kristinashu** [comment]
Yeah icebox 💀
