### ISSUE TITLE
Create Gifs for Giphy: Part II

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#615]
Continuing the work from last sprint, we're going to make some more gifs to add to our channel. The concepts (that need animation still) [are in here](https://redpen.io/p/nh4d42605a9fb96bd6).

_Original brief (from Part I ticket):_
Request from Audrey to start creating gifs for Giphy that we can use to set up our own channel and use on Instagram. For now, this is tactical, but gifs could become part of marketing plans in the future (for example, MozFest gifs, PNI gifs, or as part of social media toolkits for for campaigns shared with partners). More in this doc https://docs.google.com/document/d/1R-mrqlHAckdPWg9ER_YDBWjFt-ofy82YmsnxsKVojt8/edit
Goals

- Create fun gifs we can use for appointment content on Instagram like News Beat
- Create fun gifs that people can use in Instagram stories to talk about Mozilla

**Comment by natalieworth** [comment]
Was able to get a few more gifs done in this sprint last week (but adding this to next sprint as a stretch again).

https://redpen.io/p/ou882e791c7a07f643

**Comment by kristinashu** [comment]
@natalieworth do you still have work to do on this?

**Comment by natalieworth** [comment]
I'll close!
