### ISSUE TITLE
Create Onboarding Slides for Brand/Wagtail Staff Reps

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#616]
### Intro
Related to #573, create the google slide deck that will be used for the brownbag when we onboard our prospective reps. 

### Links
Presentation agenda/outline to reference: https://docs.google.com/document/d/1ushCsUWsDVAGYPns9nsHKN9OFwa6hQ1Dr5zaxeN8DUc/edit#

cc: @kristinashu

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
