### ISSUE TITLE
Create Survey for Brand/Wagtail Staff Reps

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#617]
### Intro
Related to #574, create the google form that will be used to track the understanding of brand guidelines and wagtail cms from reps.

### Links
Survey questions/outline to reference: https://docs.google.com/document/d/1KwSZ1UoKp2GWK7wiNEuEijX67waWRdWIv-AlwdzhEs8/edit?usp=sharing

cc: @kristinashu

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
