### ISSUE TITLE
Feedback from Engagement Team for Brand/Wagtail Staff Reps

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#618]
### Intro
Get team feedback on reps doc/relationship, onboarding slides and tracking survey before we approach reps to get on the same page.

### Links
Doc: https://docs.google.com/document/d/1ushCsUWsDVAGYPns9nsHKN9OFwa6hQ1Dr5zaxeN8DUc/edit?usp=sharing
Slides: TBD
Form: TBD

cc: @kristinashu

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
