### ISSUE TITLE
Write a job posting

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#619]
- [x] Write a draft
- [x] Share with Anil and design team of feedback
- [x] Brainstorm places to post it
- [ ] Share with HR

**Comment by kristinashu** [comment]
@anilkanji @beccaklam @sabrinang @taisdesouzalessa @natalieworth [here's my first draft](https://docs.google.com/document/d/1HqG1-ppYe19Ncm9YAgUNKmuV-uUPR9pS1iZfnbMSDEo/edit#heading=h.47v9vkiuaqul) of the job posting. Please add your thoughts/feedback when you can!

**Comment by anilkanji** [comment]
Good draft, I've left a few comments. Let's try to get this to HR before EOW.
