### ISSUE TITLE
Create wireframe for Teach Like Mozilla page

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#62]
The Teach like Mozilla page needs to be wireframed – this is its current state: https://teach.mozilla.org/teach-like-mozilla/ page

Hannah will provide all of the content (which is being gathered here: https://teach.etherpad.mozilla.org/tlmcontent). Right now the page is a bunch of pieces and needs to be pulled together into a single coherent concept. This content doc lists all the various pieces that fall under our pedagogy and processes around how to teach open, and this is an exercise in figuring out what kinds of content fit there / tell the best story. Bonus if it addresses what happens when someone signs up.

**Comment by cassiemc** [comment]
We did this. Thanks for your hard work on this @kristinashu @sabrinang and @flukeout!
* Final wireframe below and on redpen – 1/2 is here: https://redpen.io/nv3bec9dc89d965a44 and 2/2: https://redpen.io/ok1c17622f5e4114af
* Process work leading up to the final version is here: https://redpen.io/p/tr51322d9d221d45be

![final-pg1-red-pen-c621810c-0030-4799-db69-140e241a2727](https://cloud.githubusercontent.com/assets/1186326/9069733/eab6845a-3ab8-11e5-81a3-ad94ffd45500.jpg)
![final-pg2-red-pen-1d79ccba-bcc3-4404-bc5d-255bfef729ef](https://cloud.githubusercontent.com/assets/1186326/9069732/eab5f698-3ab8-11e5-997a-c01447cbb6d6.jpg)

@hannahkane Do you need to document this anywhere else?

**Comment by hannahkane** [comment]
Thanks, @cassiemc. Will move this work over to the Teach repo now. Really appreciate all the work on this!
