### ISSUE TITLE
Dialogues and Debates - due Tue Aug 18

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#621]
### Intro
Create graphic assets for the upcoming D&D. Assets may include:
- Screen title cards (Intro, End)
- Social Media (Instagram (post and story), Twitter)
- Thumbnails (new tab, youtube/airmo, blog)

### Links
Content TBD

cc: @KevZawacki @kristinashu

**Comment by KevZawacki** [comment]
Hi @sabrinang, the line up for our August 25 D&D is finalized, and we're ready to create graphics. Thank you as always!

Would it be possible to have one graphic done by end-of-day Tuesday, August 18, to accompany the blog post announcing the D&D? The information is below:

Mozilla
Dialogues & Debates
Alternative Business Models for the Web
with Harriet Kingaby, Nathalie Maréchal, and Akintunde Sultan
Tuesday, August 25, 8am PT / 11 am ET / 4pm BST

Headshots (note: Sultan's is intentionally vague for privacy reasons):

![image](https://user-images.githubusercontent.com/11045250/90180053-69dd1080-dd7c-11ea-89c9-0da041154a50.png)

![image](https://user-images.githubusercontent.com/11045250/90180156-92650a80-dd7c-11ea-8b41-cafaf62cb511.png)

![Harriet](https://user-images.githubusercontent.com/11045250/90180240-ae68ac00-dd7c-11ea-96e5-9c69721b01b2.jpg)

**Comment by kristinashu** [comment]
Thanks for the info Kevin! Sabrina is busy with another big project right now but @natalieworth should be able to help you with this!

**Comment by natalieworth** [comment]
Yep! I'll have this Monday afternoon for you to review @KevZawacki

**Comment by KevZawacki** [comment]
Thank you, @natalieworth  🙌 🙌 🙌

And, one small update. Can we update the "Dialogues & Debates" header to "MozFest Dialogues & Debates"? Thanks!

**Comment by natalieworth** [comment]
Hey @KevZawacki , I have the [August 25 D&D slides here for review](https://redpen.io/p/wv4e6aed705ad39873)

Did I catch everything or do you need anything additional?

cc-ing @sabrinang too if you could do a brand check (since you did the previous ones)

Thanks :)

**Comment by KevZawacki** [comment]
Hi @natalieworth, these are perfect -- thank you kindly! :-)

Could you share a link to the final, downloadable versions when you have a chance?

**Comment by natalieworth** [comment]
@KevZawacki Yep! [Final files are exported in here](https://drive.google.com/drive/folders/1whhhoPS8Yyt0jR0R8A0rnYia3d9oVSfO?usp=sharing)
