### ISSUE TITLE
Encryption: Brazil Fake News

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#628]
### Intro

Similar design style to the 2 bills designs that "emphasizes the importance of encryption in images, one could be in EN about the U.S. bills and one could be in Portuguese and about the Brazilian bill."

### Links
TBD

cc:  @taisdesouzalessa to help with translation/ proofreading :D

**Comment by natalieworth** [comment]
This has been postponed until next sprint (pending). I'll move it to there and if it's still not needed, we can icebox/ reassess.

**Comment by phildexter** [comment]
Audrey is unsure if this is going ahead. Especially with MoCo announcements this week. Based on this we're going to icebox rather than leave in sprint.
