### ISSUE TITLE
Add EOY 2014 asset files to drive

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Design#63]
@sabrinang Please add any relevant EOY 2014 digital files to _PROJECTS > Fundraising
Thank you!

**Comment by lovegushwa** [comment]
@sabrinang so for the DE campaign end of August I will be creating the following:

Facebook
Mozilla.org
Snippet
Tile
Twitter
Doner-Funnel (this is already documented ... if you have a wireframe file it would be handy otherwise I will build one.)

If you have the final best version of each of these items we can use them as a baseline. They can be dropped to the drive here:

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvVFNZQ01JYi1VR1U&usp=sharing

**Comment by sabrinang** [comment]
mozilla fundraising folder: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efllrYXowOHBhcU9xRlltLXZGcXNyM3FxbkNzTjlXNEFLekRKNlBOU0FlLTQ&usp=sharing
