### ISSUE TITLE
Becca's portion of the recap deck

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#630]
Becca to populate this year's [recap deck](https://docs.google.com/presentation/d/1Haea7saoXXGxaCD9W54ZsO6P9-EWtWSrzFMATs2G9mE/edit?usp=sharing) with her work.

Rest of the work will be done here https://github.com/MozillaFoundation/Design/issues/537.

**Comment by beccaklam** [comment]
This is done!
