### ISSUE TITLE
Donor letter and envelope 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#631]
Request from: Stephanie Lowry

For Donor acknowledgement 

1) #10 window envelope with black logo and return address

> Mozilla Foundation
Attn: Donor Care
2 Harrison Street, Suite 175
San Francisco, CA 94105-6130
USA

2) #9 no-window envelope with black logo and send-to address (address the same as above)

3) Letterhead 
Can use on of these https://foundation.mozilla.org/en/docs/brand/templates/

She will get them printer at her local print shop, most likely Staples.

Note: Jesse W has also requested a branded folder design.

**Comment by natalieworth** [comment]
Started envelopes this week [and working files are in here](https://drive.google.com/drive/folders/1LxDdwuXXBkDGdo9rizyxfBPMexFWZiRJ?usp=sharing)

**Comment by natalieworth** [comment]
Sent the envelopes for Jesse to review and he is showing his team in their meeting tomorrow morning.

[Initial drafts are in the Redpen here](https://redpen.io/p/wv7f08c5fffd3f308a)

**Comment by natalieworth** [comment]
Received feedback from Jesse and the fundraising team. There were a couple minor edits, but envelop designs are done. Going to make a new ticket for the next sprint to create print ready files. 

[Final redpen designs are in here.](https://redpen.io/p/wv7f08c5fffd3f308a)

[Final working files are in here.](https://drive.google.com/open?id=1bmg_IZd3LWhTXoobxyPP83SqE4b6NQS2&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
