### ISSUE TITLE
Donor folder

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#632]
Request from Jesse W

> Branded folders to send with major gift acknowledgments (we'd put the acknowledgment letter and some collateral inside). Something like this https://www.jukeboxprint.com/presentation-folders (though their minimum quantity is more than I need so might need to find another company).

Natalie to ping Jesse when she's ready to work on this to get more info. Make sure a printer and quote is lined up before starting the design! 

Note: this can be done at the same time as https://github.com/MozillaFoundation/Design/issues/631

**Comment by natalieworth** [comment]
[Draft for this is here (although it's not needed by Fundraising team for use yet).](https://redpen.io/p/wv7f08c5fffd3f308a)

[Working file is in here](https://drive.google.com/open?id=1cJLQfZ71zgAzgLLIOOPNPj5DgPFYT70a&authuser=natalie%40mozillafoundation.org&usp=drive_fs) for when the team is ready to implement.
