### ISSUE TITLE
Foundation Site: Card Styles

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#637]
**Audit existing styles**
Card styles that contain links and/linked images to help establish consistent pattern for users while browsing the site to better expect what part of the card is linked and what is not. Capture any guidelines when to use which style (cutout style, all linked, text linked only etc.)

  - [ ] Post proposed any new update or audit findings in Redpen (for desktop, tablet, mobile)
  - [ ] Request design review from design team via R+/R- in Github ticket
  - [ ] Get feedback from devs
  - [ ] Update and merge the Sketch library _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [ ] Create a dev implementation ticket (following the design to dev hand-off outline)
 

cc @taisdesouzalessa

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
