### ISSUE TITLE
Re-design of Leadership Giving assets

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#638]
**Updated version (based on chat with Jesse on Sept 03)-edited by Taís:**

He wants the illustrations to have a more "VIP" feeling (I suggested the look and fell of [Nat's work](https://redpen.io/rq98612f386c145afa)). Also he will send the PDFs to a print company so we will need to transfer the doc to InDesign and prepare for higher print quality (he is aware that if we design those via InDesign he won't be able to edit the copy without our help and he is okay with that, he doens't think the copy will change for a while).

**Deliverables:**
- [ ] Updated illustrations for [this page](https://foundation.mozilla.org/en/initiatives/leadershipgiving/)
- [x] 1 PDF with content from [this doc](https://docs.google.com/document/d/11Iy8rekUMk8rXkwQYO9As3K5XdEX3Uo7jFxL_VD4cRg/edit?usp=sharing): probably a foldable 4 pages.
- [x] 1 PDF with r[educed content](https://docs.google.com/document/d/1vgs9CoPExwTgq9Jtz_-SLNAQRfUltxC0uFfBFzawKjU/edit) from the doc above - layout will be the same, just with reduced content. Jesse mentioned this is less important than the 4 pager.

**Deadline:** Sept 14th

_______

Original ticket:

From Jesse W
> We recently re-brand our major giving program with new language and benefits. Next step, is to bring it all together with a snazzy new design. I'm looking to have a print and web version of this new overview. This is something that I want to send with major gift acknowledgments, use at in-person events (one-day) and link in my emails so it will benefit by having a very on-brand and professional design. Ideally, for print, we'd create a full version and a two-page version (just the top paragraph with the last page and a half).
> - (new text with some old design elements): https://docs.google.com/document/d/11Iy8rekUMk8rXkwQYO9As3K5XdEX3Uo7jFxL_VD4cRg/edit?usp=sharing
> - (old text and design on web): https://foundation.mozilla.org/en/initiatives/leadershipgiving/

**Comment by taisdesouzalessa** [comment]
Started the 4 pages PDF. Once that is done we can use the same illustrations for site and same artwork for front/back PDF.
[Work in progress here](https://drive.google.com/drive/folders/1UnFvb2bAX2ZvIEBaBk_T4lPEevsDEkGN?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Sent a draft of the 4 pages layout to Jesse, who gave me some feedback. 

Second iteration here:
• [Outside ](https://redpen.io/fy32503436a43b12ee)
• [Inside](https://redpen.io/nv09ed499824fae530)

I am seeing some issues with the black highlight Zilla but once I Zoom in in PDF I don't see any issues. Jesse may print one to check if it is all good and we can do some QA.

**To do:** send for design review + second review by Jesse; based on that create the 2 pager; ask Jesse to update the site content so we can use the same images there.

**Comment by taisdesouzalessa** [comment]
- [x] 4 pages PDF is ready. Mockup here: https://redpen.io/nx69c58355362384ee. PDFs were sent to Jesse (he will print one as a test and if it is all good, he will send the final version to print company).

**Comment by taisdesouzalessa** [comment]
Reduced content (2 pages) mockup sent to Jesse. 

**To do:** final design QA on the 2 pages collateral, try to move page to a "/donors" URL and update images there (Jesse is working on updating the current page on the CMS).

**Comment by taisdesouzalessa** [comment]
Half of this task is done. I'll close this ticket and add a new one to the next sprint.
