### ISSUE TITLE
Video: YouTube Regrets Part I

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#639]
[placeholder ticket] 

Part I
- Decide on concept and copy for the video (add link to Audrey's doc)
- Natalie to create a few example frames
- Storyboard 

Part II (next sprint)
- Still image at 1.91:1 and 1:1 for Twitter and Instagram, as well as an Instagram story 9:16
- 2 cuts of the video, one 6 seconds and one 20 seconds (need to confirm dimensions - assuming we aren't doing [all of these listed](https://docs.google.com/presentation/d/1nyJNZY9oeOqe5oQqf22CPy_tgDksvczMDad_uZTL6Q4/edit?ts=5f1975d2#slide=id.p)?)

**Comment by natalieworth** [comment]
[Content/ ideas from Audrey are here](https://docs.google.com/document/d/1vWOi8wUGwRUAc9hzy3XkQcRKntHxuVLqv3CBa54Qc9s/edit).

**Comment by natalieworth** [comment]
[Ads for review are here](https://redpen.io/p/vq0c120d8a94b3de34)

Sent to Brandi and will follow up with her tomorrow.

**Comment by natalieworth** [comment]
[Mockups are here](https://lindsay970727.invisionapp.com/console/share/T41BYHZU8Y/479637009)

**Comment by natalieworth** [comment]
[Sizes are here](https://docs.google.com/presentation/d/1nyJNZY9oeOqe5oQqf22CPy_tgDksvczMDad_uZTL6Q4/edit?ts=5f1975d2#slide=id.p)

**Comment by natalieworth** [comment]
[Video concepts are here for the 6/20 second pre-roll videos](https://docs.google.com/presentation/d/1sFrYyo8UQWp-XhAPKX3ZnAY6gTB-oeywfA39fqp-5g4/edit#slide=id.g25275a8168_0_425)

**Comment by natalieworth** [comment]
[Final ad exports for the agency are here](https://drive.google.com/open?id=1kctwp-u-PL88LGEElqP9umPj1H8gTicE&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

We also received approval from Ashley and Emily for the video concepts—contigent on the videos/ imagery needing review when they are finalized.

Going to talk to Brandi and Audrey tomorrow to decide on a direction for the pre-rolls. :)
