### ISSUE TITLE
Video: Donor thank you

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#640]
Jesse W has shared Rainer's video file. Natalie to animate in the headlines.

From Jesse:

> Here are the video files for the donor thank you video project. Rainer cut two different versions. The first one is my primary use case and features a reference to them being larger donors. The second version is something Will/Stephanie could potentially use for grassroots donors. Both have a version with music and one without. I like the version with music, but don't have a strong preference.

>Just to reiterate, what I'm hoping you will be able to do is add in some animations of headlines and screenshots that highlight Mozilla's work. So, basically cut away from Mark's face a bit to help them visualize what we've been working on. I've included a list of things I think are interesting in [this project overview document](https://docs.google.com/document/d/14L5myQGrwMuxKnshYRUhIlte0vg_Nvkuo74eXX8Xp94/edit), but I'm open to other suggestions as well.

> Obviously, if you can repurpose graphics or video cuts you've already worked on that is more than fine (I just want some visuals -- not that picky about what they are). There is a cut in the video around the 1:04 mark and another around the 1:24 mark so, ideally, you could cut away to the animations shortly before and after those cuts. This way, it gives off a stronger impression to the viewer that the whole thing was one take.

**Comment by natalieworth** [comment]
Just waiting for Jesse and Juan to provide feedback tomorrow.

**Comment by natalieworth** [comment]
[Updated the donor video files and exported the 2nd versions here](https://drive.google.com/drive/folders/1M3Jkn4ooAzar1YQ-lymfIFc25X7NeNSV?usp=sharing)

Sent to Jesse for review tomorrow.

**Comment by natalieworth** [comment]
[Most recent links for these are here](https://drive.google.com/drive/u/1/folders/1M3Jkn4ooAzar1YQ-lymfIFc25X7NeNSV)

Just need final sign off on Tuesday for these.

**Comment by natalieworth** [comment]
[Final link for these is here](https://drive.google.com/drive/folders/1M3Jkn4ooAzar1YQ-lymfIFc25X7NeNSV?usp=sharing)

[Working Files are in here](https://drive.google.com/open?id=1eGGwTPaWLPvHFhK6C2Pes9Zui9qaEQGl&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
