### ISSUE TITLE
Video: YouTube Regrets Part II

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#652]
Based on https://github.com/MozillaFoundation/Design/issues/639 where the design direction was established.

Related to static ads #653

- Get final approved copy
- Confirm video dimensions
- Create the 2 cuts of the video: one 6 seconds and one 20 seconds

**Comment by natalieworth** [comment]
Quick *Rough* cuts for [the short and long pre-roll videos are here](https://drive.google.com/drive/folders/1iOjfJ_SCmzS3vDdt0vE-s0uHptjb2fum?usp=sharing)

Next step is getting approval of the stock footage used, voice over script, and music licensing for the videos from:

- [ ] Anil
- [ ] Ashley
- [ ] Audrey
- [ ] Brandi
- [ ] Emily

**Comment by natalieworth** [comment]
[Most recent video exports are here](https://drive.google.com/drive/folders/1iOjfJ_SCmzS3vDdt0vE-s0uHptjb2fum?usp=sharing)

**Comment by natalieworth** [comment]
Blocked on Voice over approval from Brandi/ Audrey. Spoke today and after feedback from design team and Brandi, we're going to test 1 last voice over option.

**Comment by natalieworth** [comment]
[Long version is here ](https://drive.google.com/drive/u/1/folders/1AUBq7ThUhfAM9eQv6VOgksbtdgHzL4Uk)

Just coordinating with the voice actor to finish the last short video.

So close!

**Comment by natalieworth** [comment]
Just received the 2nd voice over and have the [videos here for review](https://drive.google.com/drive/folders/1iOjfJ_SCmzS3vDdt0vE-s0uHptjb2fum?usp=sharing) (and sent to Brandi)
