### ISSUE TITLE
Untrend Twitter 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#654]
Edited by Taís: kick off with Kaili was done.

**Background**
> We launched this campaign last week and it's not performing very well. We want to kick it and were thinking about testing a graphic email as one way to bolster signatures. 

> [Doc](https://docs.google.com/document/d/1hB10q9oqkG5cwAv92ZAMc_-gGQWUa0MaoX4qSD29EnQ/edit)

Via Audrey: graphic for email and resized for OG image.

This was used originally and should just be an iteration of it. 

![image](https://user-images.githubusercontent.com/1068783/93243626-50ddcb80-f73d-11ea-835b-c68ad12de75b.png)

**Copy:** https://docs.google.com/document/d/1iSbkep2MAIu0ZsKsD2Su21QhYUZI5_kNWNXpUcOzr2Q/edit?usp=sharing

**To do:**
Kaili wants to test a more visual type of email to bump the response of the campaign. She will talk to Alexander (sending him an example of what she means) to gauge feasibility before we start designing it. Due to the complexity, our deadline was extended. If that is not possible we will do the simple version.

Simple version:
- [x] Kaili wants an image more "election-like" (red/white/blue) - I'll follow guidelines from Nat's election illustration. Keep in mind we will do a Facebook image later on so if we can do something that we can quickly adjust to another company that would be ideal.
- [x] Dimensions: email call out box. Similar to "Earn it". Kaili will send copy.
- [x] Audrey request a square icon for this campaign (size "text-image"), red, white and blue so she can add it to her page. 

Complex version:
- [x] Kaili to check with Alexander if possible
- [x] If so, Taís to adjust the concept developed in simple version.

**Deadline** - Sept 28

@kristinashu fyi this brief changed a bit and I am estimating this task bigger, considering we will get a green light from Alexander.

**Comment by taisdesouzalessa** [comment]
- [Full graphic: email (placed in context)](https://redpen.io/ora816703de5f6dd9a)
- [Full graphic: email (isolated)](https://redpen.io/fm354cd027f1adb4b3)
- [Callout box V1: email (placed in context)](https://redpen.io/wn058bb97aae0dbbe4)
- [Callout box V2: email (placed in context)](https://redpen.io/kb9733cb5e15cd72d8)

**Comment by taisdesouzalessa** [comment]
Final mockups:
[Full graphic email](https://redpen.io/pj19bc51455eb4ae4b)
[Callout box email](https://redpen.io/sd2144eed01cc18ea5)

**Comment by taisdesouzalessa** [comment]
Icon for elections page was placed in the page:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/22157921/94289105-1201ff80-ff0d-11ea-81a4-bdb16069345d.png">

**Comment by taisdesouzalessa** [comment]
Closing ticket, everything was shipped 🚀
