### ISSUE TITLE
Fundraising collateral 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#655]
**Edited by Taís on Wed, Oct 2nd**

**To do (we will proceed with only 2 of the collaterals):**
- Mozilla one-pager
- [x] send to design team then Jesse for feedback
- [x] Receive OK from Jesse's team
- [x] Prepare file to print

- PNI postcard
- [x] send to design team then Jesse for feedback
- [x] Receive OK from Jesse's team
- [x] Prepare file to print

all linked in this doc: https://docs.google.com/document/d/1ZGxG2GzaQnYtqP9cVbw4KOP6E9LhW_S8McsaSh8MK6U/edit

**Comment by sabrinang** [comment]
This is probably relevant to where the one-pagers left off for reference: https://docs.google.com/document/d/1vu14K7tv9DA_vNkUqaz0Hg7WT4szvnsLcMx5EZdZw3E/edit#

- there are links to print design + digital versions within it
- previous design brief for comms collateral probably similar to fundraising collateral

**Comment by kristinashu** [comment]
Thanks Sabs!

This is what Jesse has in his doc:
- Mozilla One-Pager - pamphlet, brochure or front and back flyer that highlights our mission and key initiatives (https://github.com/MozillaFoundation/Design/issues/522)
- Advocacy One-Pager - pamphlet, brochure or front and back flyer that highlights our advocacy program
- Fellowships and Awards One-Pager - pamphlet, brochure or front and back flyer that highlights our fellowship and awards program
- PNI Postcard - short front and back postcard that highlights the goals and impact of our Privacy Not Included Buyers Guide
- IHR Postcard - short front and back postcard that highlights the goals and impact of our Internet Health Report

The one-pages should follow our template https://docs.google.com/document/d/1PTdSrNA7-2LiTmAISEOzWmPEhUZvbDPjaYp2-JFc8T8/edit and some version of the the postcards may have been made in the past and just need updating - please check the drive folder of ask in the design channel when you're ready to start on them.

**Comment by taisdesouzalessa** [comment]
UPDATE: Jesse mention he may get some answer about this during this week. I told him we will be doing this next sprint only (starting at Sept 29) and he is okay with that. Moving this ticket.

**Comment by taisdesouzalessa** [comment]
Blocked by content _[to be unblocked on Tuesday, 29th]_
Jesse needs to finalize some text updates, but will have that finished by next Tuesday

**To do (we will proceed with only 2 of the collaterals):**
- [ ] Mozilla one-pager
- [ ]  PNI postcard

all linked in this doc: https://docs.google.com/document/d/1ZGxG2GzaQnYtqP9cVbw4KOP6E9LhW_S8McsaSh8MK6U/edit

**Comment by taisdesouzalessa** [comment]
Content ready and approved.

**Comment by taisdesouzalessa** [comment]
Two pager sent to design for review after a first round of critique.

**Comment by taisdesouzalessa** [comment]
**Mozilla one-pager (status: sent for Jesse's feedback):**
• [Front](https://redpen.io/zu26aa380e58c46a2b)
• [Back](https://redpen.io/nq3ac1006572fcb2dc)

**Comment by taisdesouzalessa** [comment]
**PNI postcard (status: sent for Jesse's feedback):**
• [Front](https://redpen.io/mua91ac69644f6fb9f)
• [Back](https://redpen.io/fc08e0391a9e880430)

**Comment by taisdesouzalessa** [comment]
**Files to print:**

[Mozilla Foundation flyer](https://drive.google.com/file/d/1uyqwfOJRc5-ZdTeTJnUFz2rKoiDj7rCU/view?usp=sharing)

[PNI Postcard](https://drive.google.com/file/d/1Ltd6rXUuo9shvAwLrtZ4xGthoZqur8xi/view?usp=sharing)

Next steps: double check with Jesse if there isn't any additional feedback from PNI and if not, this ticket will be good to close

**Comment by taisdesouzalessa** [comment]
All good with Jesse, closing!
