### ISSUE TITLE
Vote 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#657]
Same style as the election hub but square and story size. Square one just says "REGISTER TO VOTE", story says “REGISTER TO VOTE swipe up for this and more things you should know and do ahead of the 2020 Elections."

**Comment by natalieworth** [comment]
https://redpen.io/p/ex3e911a2862827d9c

**Comment by natalieworth** [comment]
[Sent to Audrey and final assets are in here](https://drive.google.com/open?id=1rWWAt4YxPyXSD-JxBWQVqEl6ZZOYDO4o&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
