### ISSUE TITLE
Misinformation scorecard / Platform Tracker

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#659]
Campaigns team finally has the go ahead to move forward with this project. 

They would like to use this direction Rebecca stated on last year - comps https://redpen.io/p/tafd9bccd2cd92a146.

### Todo
- Meet with someone from the advocacy team to kick-off this work
- Update this todo list based on that kick-off
- Decided on a URL
- Advocacy team to: Create the pages in Wagtail using bannered template
- Design to update the banner image and provide the grade and graph graphics once advocacy has populated the pages
- Create promo graphics (need to know plateforms)

### Links
- [Advocacy brief](https://docs.google.com/document/d/1SNxxhHX0hBiJgAzswEgGUTSzPfpkTn9Vvy68rIeOhaI/edit)
- Copy doc [advocacy or Anil to add]
- Sketch working file is [in Drive here](https://drive.google.com/drive/folders/1yoo3RZh_Sl-6e3nDerFYggxyJteyU8wZ?usp=sharing).
- Rebecca's ticket for the original work https://github.com/mozilla/foundation.mozilla.org/issues/2643
- Not sure how related this campaign is but good to reference https://foundation.mozilla.org/en/campaigns/eu-misinformation/

**Comment by phildexter** [comment]
More info coming in hot...

**Comment by jamilasnell** [comment]
This has been tabled for after the election so I will move this ticket to a different sprint.

**Comment by jamilasnell** [comment]
This has NOT been tabled, I will talk to Jon Lloyd tomorrow for more info.

**Comment by kristinashu** [comment]
Pages are here https://foundation.mozilla.org/en/campaigns/platform-tracker/ and Kaili will be adding [this content ](https://docs.google.com/document/d/1Y1LPeoX4bzw6ChCVHClGj-DICrtMrPE5gvjDvwRg_Yk/edit)to the pages tonight.

@natalieworth tomorrow (Friday) could you please:
- Create graphics to replace the grey boxed - work with Kaili to figure out what would make sense i.e. star rating, grade, yes/no, or company logo
- Create a graphic for social and for the landing page (equivalent to [this](https://assets.mofoprod.net/network/images/red-pen-c4fa2b66-898b-4322-bf85-6e238181212a_AD.original.jpg) - could use this old style https://redpen.io/p/tafd9bccd2cd92a146)
- Do a design pass of the content Kaili added to the pages

If you need any help with this please let me know and we can see if Tais or I can help you with this!

**Comment by natalieworth** [comment]
Sweet!

Final [exported assets for these are in here](https://drive.google.com/open?id=1HRPC8N6TXJA5rQ7CYH2x1w6ruArskzgg&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

And the [working file is in here](https://drive.google.com/open?id=1JQNXKuiyeVVnmJIt4i1zvUiCOVzNimb_&authuser=natalie%40mozillafoundation.org&usp=drive_fs) (in case it's needed for next week)

**Comment by kristinashu** [comment]
Thank you Nat!!!

Sorry @taisdesouzalessa but Nat and I will be off on Tue/Wed and Kaili might need some help with wagtail. She should have all the assets, and the pages are set up here https://foundation.mozilla.org/en/campaigns/election-policy-tracker/ but she might need help [setting up some page anchors](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/creating-anchor-links/) and other wagtail stuff but she is quite familiar with it.

**Comment by jamilasnell** [comment]
@kristinashu @natalieworth @taisdesouzalessa Advocacy team decided to NOT put graphics and details into Wagtail. They are sticking with using google doc that will be uploaded to site. Need design help but will ask for detailed list of what is asked of us and what new ETA is.

**Comment by kristinashu** [comment]
Page is [here](https://foundation.mozilla.org/en/campaigns/election-policy-tracker/).

Doc is [here](https://docs.google.com/document/d/1-b5b_AgJhz7rAXaSpekwBwZWHx_A7iSleoOGxK0lZto/edit).

Nat's graphics are [here](https://drive.google.com/drive/folders/1HX_cTB4dObvrFQbauvya1x9wazz27O9B?usp=sharing).

I think this is done 🙃
