### ISSUE TITLE
Design sessions for mozfest

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#66]

**Comment by xmatthewx** [comment]
cc @xmatthewx

**Comment by cassiemc** [comment]
Deadline was last friday, so marking closed. Incidentally I did get a submission in. Anyone else? @lovegushwa @xmatthewx @flukeout @vazquez @sabrinang + @kristinashu  – you might be able to still submit something if you ask Sarah really nicely and do it TODAY/TOMORROW.

https://2015.mozillafestival.org/proposals

**Comment by vazquez** [comment]
Robert, Matthew are taking what we learned on Hour of Design/Ride With me to the streets!

Participants in the session will identify the most scalable contributions to an open-source technology project (in particular) and co-construct a framework for engaging professional volunteers.
