### ISSUE TITLE
Regrets Reporter Election Hub Image

### ISSUE THREAD

**Issue by jamilasnell** [MozillaFoundation/Design#661]
### Intro

Via Audrey: We are adding Regrets Reporter to the Election Hub so it needs a RWB icon. Here is a placeholder image for the time being > https://assets.mofoprod.net/network/images/regretsreporter.original.jpg

### Links

cc: @kristinashu @natalieworth

**Comment by jamilasnell** [comment]
Audrey is OOO next week so please contact Xavier when it's ready!

**Comment by jamilasnell** [comment]
@natalieworth RWB means Red White and Blue!

**Comment by natalieworth** [comment]
[RR election hub image is here](https://drive.google.com/open?id=1zWu3ISeL9GmmbrqB3kVaX7-5Mrl_yJ8h&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

**Comment by natalieworth** [comment]
Sent this to Audrey to add with the content.
