### ISSUE TITLE
Data Futures - collateral

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#662]
**Intro**
A/B Partners worked with Bob and team in this slide deck [for a Data Futures Lab pitch](https://docs.google.com/presentation/d/1EErrjipWEt_2myfe3U3nyNXI9OP4CuAA3A7m4Q1txHA/edit?usp=sharing)

They also worked on this [2 pager](https://drive.google.com/file/d/1fd_wS_pyVhMCalhkCz9Z0Ju46Kkxrciv/view?usp=sharing) to accompany the deck

**To do:**
- [x] We have a [proposal doc](https://docs.google.com/document/d/1mu5VNe05T9Mnhdz9qXyHq0dzOk88jdlFghuQ-q1DPqA/edit?usp=sharing) that will need to be visually aligned with the work done by A/B Partners. 
- [x] Send to Bob for approval
- [ ] Once it is all good, add all stakeholders from previous doc to this new copy + transfer ownership of the doc to Bob

**Deadline:**
Oct 29

cc: @jamilasnell

**Comment by taisdesouzalessa** [comment]
@jamilasnell can you please ask Bob if she needs this sooner or if this can wait until the 26th? Thanks!

**Comment by jamilasnell** [comment]
Jam will let J.Bob know that this will be done by Thursday (10/29)

**Comment by taisdesouzalessa** [comment]
[Document here](https://docs.google.com/document/d/1A3s54hUvfelow5N8BXNKAttquNZQm1_wVuJYS-p_tKQ/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Bob to confirm if we want to have Mozilla + Luminate for this version. Once she has the answer she will ping us to do the adjustment.

cc: @jamilasnell

**Comment by taisdesouzalessa** [comment]
Closing this ticket because if we have any logo changes it will be a very quick task that won't require ticket. 
@jamilasnell keep me posted if Bob pings you on the logo issue and I'll do the same (keep you posted) if she pings me.
