### ISSUE TITLE
Design review of streaming platform video

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#668]
Audrey to share progress with Natalie for feedback.

**Comment by natalieworth** [comment]
Tyler (contractor) has sent 3 versions of video directions over. Kaili is tweaking some of the copy and also coordinating the footage/ voice-over purchasing—but draft video is looking good so far!

**Comment by jamilasnell** [comment]
@natalieworth Audrey requested bumpers for beginning and end of video https://vimeo.com/467831903. ETA for week of the 19th. Moving this to next sprint.

**Comment by natalieworth** [comment]
[Video assets are here](https://drive.google.com/drive/u/1/folders/1QPWLTQI36ssqD1zUWWhbS5IpI9VWhegt)

**Comment by kristinashu** [comment]
Related to - Email graphic for platform streaming video #677

**Comment by natalieworth** [comment]
https://drive.google.com/drive/u/1/folders/1QPWLTQI36ssqD1zUWWhbS5IpI9VWhegt

**Comment by natalieworth** [comment]
[The updated version is here](https://drive.google.com/file/d/17jxRBxuBj7g4jWl878VaGcnwPRyhtwoh/view?usp=sharing) and have sent to the team for review( Kaili, Tyler, Anil, and Audrey).

**Comment by natalieworth** [comment]
Bumpers are added and video is signed off from Audrey and Kaili.

[Final file is in here.](https://drive.google.com/file/d/13rAr4TnzO8jttAMnsO256ESGB9w8I2wp/view?usp=sharing)
