### ISSUE TITLE
Localized assets for Facebook Groups email

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Design#669]
Hi team,

We’re going to do a global launch of a slightly modified version of [the Facebook email sent lest week in EN](https://docs.google.com/document/d/10VeWPTymzOqs7J1wtxnBKZasWZ-bz2koRsKVob0H_84/edit). This image was part of the email, would it be possible to produce localized versions of this in DE, ES, FR, PT?
Timing-wise, the new email should go through approval soon, for a send ASAP.
I will start getting some of these translations ready early next week.

<img width="337" alt="Capture d’écran 2020-10-02 à 17 16 42" src="https://user-images.githubusercontent.com/1294206/94956164-993e0d00-04e3-11eb-8a60-c26bf1aa0db3.png">

cc @kristinashu , please hit me up if I’m missing something (it could very well be)

**Comment by kristinashu** [comment]
Sure, just let me know when you have the translated text!

**Comment by taisdesouzalessa** [comment]
@TheoChevalier I'll do this work. Do you have the translated copy already? If so, could you please add it here? Even if you have only some of them you can add here so I can start. Thanks!

**Comment by TheoChevalier** [comment]
Thanks both!

@taisdesouzalessa yes! I have French, German and Portuguese ready here:
https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2020/fb_groups_graphic.lang&action=translate&show

I should have Spanish ready in a couple days, I will post an update here when I do

**Comment by taisdesouzalessa** [comment]
@TheoChevalier Here they are:
https://drive.google.com/drive/folders/1DVHB2FXJORUCps4hXgYQJQ5ZP-m4cW7J?usp=sharing

Preview:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/22157921/95262417-f33f1b00-07e0-11eb-8a23-4a6c59df6258.png"> <img width="200" alt="image" src="https://user-images.githubusercontent.com/22157921/95262435-f934fc00-07e0-11eb-86c6-8979e1cbb681.png"> <img width="200" alt="image" src="https://user-images.githubusercontent.com/22157921/95262449-ff2add00-07e0-11eb-9f0f-13f6a61ed30e.png">

**Next step:** Do the Spanish version once copy is ready :)

**Comment by TheoChevalier** [comment]
Thanks @taisdesouzalessa!
I just noticed a couple mistakes in the FR graphic:

- There’s a missing space between Zuckerberg and the semi-colon (French typographic rule)
- There’s a typo in `résultats` (vs. `résuaats` in the graphic)

Is it possible to fix?
Thanks!

**Comment by taisdesouzalessa** [comment]
> There’s a missing space between Zuckerberg and the semi-colon (French typographic rule)

@TheoChevalier I had removed the spacing thinking it was a typo but I was actually creating a typo...haha. Sorry for that! Thanks for teaching me a new thing :)

The Google Drive was updated with the new version. Here is the preview:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/22157921/95606477-3c74b200-0a0f-11eb-8a56-a0033b1d5ab0.png">

**Comment by TheoChevalier** [comment]
Thank you!
And yes, you can expect to see all kind of weird stuff :)

**Comment by TheoChevalier** [comment]
@taisdesouzalessa Spanish is ready! (Same link https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2020/fb_groups_graphic.lang&action=translate&show)

**Comment by taisdesouzalessa** [comment]
@TheoChevalier Spanish version created. Updated in Google Drive and here is the preview:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/22157921/95621432-861cc700-0a26-11eb-98f6-af20a7cd08fc.png">

Closing this ticket :). Please reopen if any fix is needed.

**Comment by TheoChevalier** [comment]
Hey @taisdesouzalessa , our localization vendor caught a couple things to fix in the German graphic during the email QA phase, would it be possible to update please?



![mozilla DE email part 1_corr](https://user-images.githubusercontent.com/1294206/95893778-0cffd580-0d80-11eb-9083-cb19d6ffb006.jpg)

One typo:
> Vorgeschlagende

Vorgeschlagene



And one change for consistency:
> Falschinfo-Gruppe

Falschinfogruppe


Thank you!

**Comment by taisdesouzalessa** [comment]
@TheoChevalier asset updated in our folder in Google Drive. Preview here:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/22157921/95925770-80e5b200-0d6f-11eb-87a0-f975431055be.png">
