### ISSUE TITLE
Complete application for user testing intern

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#67]
cc @flukeout

**Comment by flukeout** [comment]
@cassiemc What do we need to do for this? I can start by writing a short job description. Do we have a specific deadline in mind?

**Comment by cassiemc** [comment]
I think we should aim for end of week. Here's the application: http://yid.vcn.bc.ca/host-site-application/

**Comment by flukeout** [comment]
I've started a draft of the application here:
https://docs.google.com/document/d/1lJ4Nb4kZloqiDik_gLpJK5hthkKcVuGgc3Ng9UEIHq0/edit?usp=sharing

**Comment by cassiemc** [comment]
Fabulous. Left a few comments. @flukeout

**Comment by cassiemc** [comment]
Submitted this today. Thanks for the help @flukeout!
