### ISSUE TITLE
Major Donor Preference Card

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#671]
Via Jesse W

> Deadline Oct 16

> Currently, if a major donors sends a check without their email in the memo line, we usually have no way of connecting with them further. I'd like to fix this by providing them with a short return questionnaire in their acknowledgment materials. This will make it possible for a major donor to tell us how we can connect further. The questionnaire will need to fit in a provided no. 9 return envelope to make it as easy as possible for the donor.

> I don't need this to have a super fancy design, but since it will accompany previously designed major donor related collateral pieces it is important to have a professional look and print. The key is to make sure it fits (without additional folding) in a no.9 envelope (3-7/8 x 8-7/8 inches). I plan to use Jukeboxprinting.com so need a design file with that in mind. Here is the text I want: https://docs.google.com/document/d/1BzodocSfket_2ju20BhWyqQQ8eHh8yrKqw9lBWGbVGo/edit?usp=sharing

> Online version: https://docs.google.com/forms/d/11eI-Z5N976ndQel3nBgkKSrLXQQRNjQdWzzkiyojMX8/edit

> I also did a mock-up in Publisher if that is helpful, though it doesn't have any design elements as I was just making sure the text would fit given the size constraints.

**Comment by taisdesouzalessa** [comment]
**Print card:**
[Mockup here](https://redpen.io/mz0081d1068301d3ce) (please use the keyboard arrows to see the 4 pieces of work)
**Jesse** - I have some questions for you there on the third page (Major donor preference card inside)


**Online card:**
• the experience of the only card should be as similar to the print card as possible. The copy should be adjusted to reflect what we have in the print card and there is a typo on "Change Makers" circle. 
**To Jesse:** If you give me the editing access to this form I can style it for you with a header (purple lines + logo) - unless there is a strong reason for us to have the very big logo on top.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/22157921/96291057-680e1400-0f9c-11eb-8ab0-de50e823cd3b.png">

@sabrinang @kristinashu @natalieworth please let me know if you have any feedback before I send it to Jesse's way.

**Comment by taisdesouzalessa** [comment]
Sent to Jesse for review

**Comment by taisdesouzalessa** [comment]
Sent print version to Jesse + asked questions about the online form (to double check if he needs any action item from us)
