### ISSUE TITLE
#StopGroupRecs FB petition delivery

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#672]
#StopGroupRecs FB petition delivery

Via Audrey and Kaili

>Brief is here: https://docs.google.com/document/d/1GTE7gRndbRhpyOGDE1jwOrYmgxBQKSiFgxMIm3IRuoU/edit

> An Instagram post and story to support this campaign > https://foundation.mozilla.org/en/campaigns/facebook-stop-group-recommendations/

Once we have a list of names we will create a pdf similar to this [Untrend Twitter one](https://drive.google.com/drive/folders/1oiQNDNDOy6W9XBhnwpJJTCKh5fFINTyN).
 
Blocked until we have:
- Deadline
- Intro text
- List of names in a spreadsheet

**Comment by Audreymofo** [comment]
This is for Instagram, it doesn't need signatures on it or any intro text, just the images described in the document. The deadline is ASAP - it's election content so it gets increasingly less relevant as time goes on. If there isn't time to complete it within the next two weeks, I think we'd need to table the idea. Thanks! @kristinashu

**Comment by Audreymofo** [comment]
Or maybe you've put the wrong brief into this github ticket?

**Comment by jamilasnell** [comment]
@Audreymofo So this needs to be two tickets correct?

One for [FB petition](https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/recbESnvEgFpFAglD?blocks=hide) 
One for [instagram](https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/recIMmRyY40bgigeN?blocks=hide)

**Comment by Audreymofo** [comment]
@jamilasnell  Yes this needs to be two tickets. Please check with Kaili about the signatures image. I know that is quite important.

This one is important but not AS important. ASAP means, if it can't be done in the next two weeks, we shouldn't bother. It's election related so the absolute latest I could post it to Instagram is w/c 26th of October. After that it is a bit pointless.

**Comment by jamilasnell** [comment]
Created a new ticket for Instagram work: https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/5443
