### ISSUE TITLE
Email graphic for platform streaming video

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#677]
Related to - Design review of streaming platform video #668

via Kaili and Audrey

> We plan to send an email to supporters asking them to watch and share an ad we produced about streaming TV services. We will need some graphics for the email (and share pages) including notably a screenshot from the video with a play button on it to embed in the email so that people can click and it will bring them to the page with the video to play. 

Audrey will provide a still image from the video and design should add a play button and crop the image. But check-in with Kaili and Audrey before starting.

**Comment by natalieworth** [comment]
[Rough graphic ideas are in here](https://redpen.io/p/uva0b6e8be01a81274)

**Comment by natalieworth** [comment]
[final exports in here](https://drive.google.com/open?id=1wcgbhXVJq0DxGgZxT_BTEFaxbdWTXOA8&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
