### ISSUE TITLE
Co-Branded IG Election Content

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#678]
I don't think much work is needed for this. tl;dr make room next to the Mozilla logo for a logo of another company.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/1068783/96292807-9ee52980-0f9e-11eb-9c3c-2361310922cb.png">

Check-in with Lindsay before starting.

Via Lindsay Dearlove

> Co-Branded IG Election Content

> A while ago we posted on our social a “how to see fewer political ads” post using a carousel of images (I will link the images below). I have some organizations in mind that I would like to share this content with, and ask them to share it on their social channels. Ideally, I would love it if we could get the first image tweaked in a way that would leave room for an org to add their logo alongside ours (co-branded). The rest of the images should be okay the way they are! I just want there to be room for an organization to insert their logo if they choose to on the first image.

> Here it the link to the images use: https://drive.google.com/drive/u/0/folders/1g0Qz0chSEtZulmiZMzxIIS-8CSNDm8rd

> Here is how we posted on instagram: https://www.instagram.com/p/CCoj3Ibg3zV/

**Comment by natalieworth** [comment]
I moved the logo to the bottom so there is more space for mozilla + [insert] a partner logo. 

[A partner working file and exports (jpg's) are in here](https://drive.google.com/drive/folders/1mkedWyCCb8Cd-CAp5gTG35SeAgRSC3Vk?usp=sharing).
