### ISSUE TITLE
Misinfo Monday: Election Results Still Loading

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#679]
Proposed launch date: October 29, 2020

Contact person: Audrey

Gifs to tell people to wait for the election results to be counted in full.

[Ideas doc.](https://docs.google.com/document/d/1vkjNZTgBADm4Gn4j0a-E-_zcPAG58L2NlN6njzPkQhk/edit)

**Comment by natalieworth** [comment]
[Sent static versions to Audrey to review](https://redpen.io/p/pe2d09472be8ce071a)

**Comment by natalieworth** [comment]
[Final assets sent to Audrey and in here](https://drive.google.com/drive/folders/1wPbOs3tyRfKvDSoNPjYEFMtGYAzGBQ0J?usp=sharing)
