### ISSUE TITLE
PNI: Design review for marketing video

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#680]
Part of epic: https://github.com/MozillaFoundation/Design/issues/682

Contact person: Lindsay Dearlove

Lindsay will hire a contractor to create a video for PNI marketing. We will need to brief the contractor on our brand and then review the progress of the video.

> I would like to get a six-second video created for this year's Privacy Not Included marketing. I envision this video being used on social media and used on YouTube as a pre-roll advertisement.

Brief from creative director: coming soon

Note: [This is the PNI video from last year for reference.](https://www.youtube.com/watch?v=VSCkrvtVt3Y&amp;force_ad_encrypted=6INLEJxnq6yCsLEQuk2XgTm2axWhS02Gc8-GcVoOJl8RNK_tpagG3r_-xIwai9UEZgQ6eLl0RB546-v_RXUwEkjqs_DphssDrfjHOZkIpkzPt-LGNTH0VDOD4c_wnVejxWmPCGSl0PDkTHo0U6JS7TIOb1fzbJ7bHgJ0kDs-dWqqWpXyM-LLlEQ6e1OkkHlKWprXOfGbGVvTx84NLAUVtYmO1KvCDtdiTcgkvbbvU8nXzl8NO6ReOEYtyx0vvulUcfQ4TbGUXJTe_v8MdOoUkSdxA-xdzy7hy_duoFb3d8m9tO_oxColYDGpFWd7dqbOi8hFt-PVwttNvdA7-kL6Vbx5bUEYcACk)

**Comment by natalieworth** [comment]
Moving this to next sprint since it's not started yet.
