### ISSUE TITLE
PNI: Design review for marketing graphics

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#681]
Part of epic: https://github.com/MozillaFoundation/Design/issues/682

Contact person: Lindsay Dearlove

Lindsay will hire a contractor (maybe Torchbox) to create all the graphics for PNI marketing. We will need to brief the contractor on our brand and then review the progress of the assets.

Brief from creative director: coming soon

**Comment by kristinashu** [comment]
Note that this should also include an email image and a hero image for the foundation site.

**Comment by natalieworth** [comment]
Compiled first round of feedback with Audrey and Lindsey. [It is in here.](https://docs.google.com/document/d/1a3uYNBBj48XhAcDIhfP-7V240Pqg1jG89oKFjPgRNfw/edit?usp=sharing)

[Redpen assets are in here](https://redpen.io/p/ydcbef77b41612dc32)
