### ISSUE TITLE
PNI: Create GIFs for marketing

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#683]
Part of epic: https://github.com/MozillaFoundation/Design/issues/682

Contact person: Lindsay Dearlove

Lindsay will hire a contractor (maybe Torchbox) to create all the graphics for PNI marketing. We will need to brief the contractor on our brand and then review the progress of the assets.

Brief from creative director: coming soon

**Comment by natalieworth** [comment]
These aren't finished yet, so moving to next sprint.

**Comment by natalieworth** [comment]
[Final files are in here and sent to Audrey for upload to Giphy](https://drive.google.com/drive/folders/1ZKLf4kFuXTn4va-PdUGGY38febDcPKi4?usp=sharing)
