### ISSUE TITLE
Mozilla News Beat: November 6, 2020

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#685]
Create assets for weekly News Beat _(social, email, blog)_. 
Content TBD on Thursday to be published on Friday.

**Comment by natalieworth** [comment]
[Content for this week's NB isi here](https://docs.google.com/document/d/1JOqDN-4Uh3DV7NXhCn4sSJnoRv0KU_sIfwoBS_zmZeI/edit)
