### ISSUE TITLE
Misinfo Monday: November 9, 2020

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#687]
Placeholder issue for Misinfo Monday post.

**Comment by natalieworth** [comment]
[Content is here](https://docs.google.com/document/d/1a6HZx4lS_B4dfOLYEnf9qKDlLVRiCv6FMoRXrdsT9OM/edit)

[Final assets are here](https://drive.google.com/open?id=17VWcmCPXl2PoUBoQj7Gq4t2xBVEv6J6g&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
