### ISSUE TITLE
Virtual panel: October 28, 2020

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#688]
### Intro
Create graphic assets for the upcoming D&D. Assets may include:
- Screen title cards (Intro, End)
- Social Media (Instagram (post and story), Twitter)
- Blog Post 
- Thumbnails (new tab, youtube/airmo, blog)

Update design so it is the same as the typical D&D graphics we make but **without D&D title**.

### Links
[Planning doc](https://docs.google.com/document/d/1pY4ACLu-BCXKtUJDlEGvICloo0fDW65gGLnrB-VEKYI/edit#)

### Content

@KevZawacki to share the speaker headshots shortly. 

The text is:

> A Mozilla virtual panel: 

> Building Better Online Communities
How do we create safer, more inclusive digital spaces when we need them most?
Featuring Caroline Sinders, Sarah Matthew, Fei Liu, and TK

> Friday, October 30, 2020 @ 11am ET
Watch on Twitter: @MozillaFoundation/core-mozfest

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa and @sabrinang, thank you again for your help. I wanted to share the final text plus 2 of the 4 headshots:

**TEXT** 

(Mozilla logo)
**Building Better Online Communities**
_How do we create safer, more inclusive digital spaces when we need them most?_
![Caroline](https://user-images.githubusercontent.com/11045250/97348715-ebfdb100-1864-11eb-86a9-c09cd4fab2d6.png)

Featuring Shawné Holloway, Sarah Mathews, Fei Liu, and Caroline Sinders

Friday, October 30, 2020 @ 11am ET
Watch on Twitter: @mozilla


**HEADSHOTS**

![Shawne](https://user-images.githubusercontent.com/11045250/97348458-8b6e7400-1864-11eb-8efc-288846719fe3.png)

![Caroline](https://user-images.githubusercontent.com/11045250/97348784-0899e900-1865-11eb-8711-b98c53430155.png)


(I should have the remaining 2 by tomorrow morning)

**Comment by KevZawacki** [comment]
@sabrinang, the design is perfect as always. Thank you for the quick work!

And, here are the two outstanding headshots:

![Fei Liu - headshot](https://user-images.githubusercontent.com/11045250/97447065-8a415380-1905-11eb-945d-0c471e279450.jpg)
![image](https://user-images.githubusercontent.com/11045250/97447067-8ad9ea00-1905-11eb-8462-359feda66331.png)

**Comment by taisdesouzalessa** [comment]
@KevZawacki all done and exported. 
RedPen link was updated: https://redpen.io/p/aw0862c01ff1e49f66
Google Drive Folder as well: https://drive.google.com/drive/folders/1BDdJBQjqUt_HZ43dxlO4THTAn6Pw3Ch0?usp=sharing

Let me know if you need anything else. Tks!

cc: @sabrinang

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa,

Apologies -- we need to make an edit to our graphics. This is my fault for not clarifying a detail with the panelist and then alerting you, the designer 😞 

SHAWNÉ has noted her name needs to be styled like so: 

SHAWNÉ MICHAELAIN HOLLOWAY

i.e. All uppercase, and with the middle name included. 

Would it be possible to update the relevant graphics before tomorrow's panel?

**Comment by taisdesouzalessa** [comment]
no problem, Kevin :). I can do the change and send your way.

**Comment by taisdesouzalessa** [comment]
@KevZawacki the files were updated.
RedPen link: https://redpen.io/p/aw0862c01ff1e49f66
Google Drive Folder as well: https://drive.google.com/drive/folders/1BDdJBQjqUt_HZ43dxlO4THTAn6Pw3Ch0?usp=sharing
