### ISSUE TITLE
Plan a QA day for Webmaker

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#69]
Similar to our Kristina Shu day, let's have a focused day with multiple designers together lookin' at stuff.

**Comment by cassiemc** [comment]
@xmatthewx is this something that would be handy? We could plan something for the next heartbeat, or whenever it might be useful.

**Comment by xmatthewx** [comment]
I have an idea that could be fun but will know more later this week if it's useful. I'll loop back early next week.

**Comment by cassiemc** [comment]
Exciting :) Will add this to the Sept 11 milestone.

**Comment by cassiemc** [comment]
@xmatthewx can we close this?

**Comment by cassiemc** [comment]
I'm-a-close this. Reopen @xmatthewx if needed.
