### ISSUE TITLE
[Dialogues & Debates] Platforms and the Election: An Autopsy - deadline Nov 17

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#698]
### Four images for the D&D
 
- [x] 16:9 image with the following information and images of the panelists (@KevZawacki to add as a comment below)
- [x] 16:9 image with "thank you for joining us", and our social channels to tend the live stream
- [x] header image for the blog post
- [x]  OG image for the blog post

### Doc
https://docs.google.com/document/d/1ssXdct0JdA_JkjchKG8MCBWvQzWz6cpN5N77GSveJVk/edit#

**Comment by KevZawacki** [comment]
Hi @kristinashu, thank you for your help. Here's the text for the graphic:

[Mozilla logo]
Platforms and the Election: An Autopsy
with Ifeoma Ozoma, Davey Alba, and Karen Kornbluh 

Thursday, November 19
8am PT / 11am ET / 4pm BST

and here are the images: 
![Ifeoma](https://user-images.githubusercontent.com/11045250/99267155-94ae8900-27f1-11eb-8e63-90d516719776.jpeg)
![Davey](https://user-images.githubusercontent.com/11045250/99267196-a1cb7800-27f1-11eb-855f-ed5a174624c3.png)
![Karen](https://user-images.githubusercontent.com/11045250/99267206-a4c66880-27f1-11eb-936a-2101350d31b0.JPG)

**Comment by KevZawacki** [comment]
@kristinashu 

We may be adding one more panelist... I will know for sure before the end of the day, and also share the relevant details.

**Comment by kristinashu** [comment]
Thank you Kevin! Nat can work on this later today. Just let us know about the panelist once you know.

**Comment by KevZawacki** [comment]
Hi @kristinashu & @natalieworth, no fourth panelist after all -- so all info is here in this ticket. Thanks!

**Comment by natalieworth** [comment]
@KevZawacki I've got these for [review in Redpen](https://redpen.io/p/bra25d7df5e6f3a57d), and if they are all good then the [final files are in here](https://drive.google.com/open?id=1Dpf3y5GTHfTkl1jGb4AaWlJuTPKSNP8s&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

**Comment by KevZawacki** [comment]
Perfect as always -- thank you, @natalieworth!

**Comment by Audreymofo** [comment]
Thanks @natalieworth. The only images I need for social are the
16:9 image with the following information and images of the panelists and the following information:
Platforms and the Election: An Autopsy
with Ifeoma Ozoma, Davey Alba, and Karen Kornbluh

Thursday, November 19
8am PT / 11am ET / 4pm BST

16:9 image with "thank you for joining us" image for the end of the stream

I don't need square or any other sizes going forward.
