### ISSUE TITLE
Slides for PNI moco presentation

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#699]
Jen will be presenting at the moco staff call tomorrow and needs 3-4 slides done today.

She really wants the team slide like last year's but the other slides can be very simple.

For reference, [here's the full deck](https://docs.google.com/presentation/d/1-iGy0XqJc349JMUF2iY5MNj7jgS5xq9IWPGPriJQ14M/edit#slide=id.ga51e097e7a_0_397) - they don’t make things too elaborate so feel free to keep it simple.

#### 2. By the #s slide: 
- 136 products
- 7 categories
- 22 products in our Best Of category
- 36 products get our *Privacy Not Included warning label
- 78 companies contacted

#### 3. PNI warning label slide
- Does it meet our Minimum Security Standards?
- How does the product use the data it collects?
- How can you control that data? 
- What is the company’s known track record of protecting user’s data. 

#### 4. PNI Team slide

**Comment by natalieworth** [comment]
PNI slides are done and Jen is adding them to the MoCo document this afternoon. [Original slide designs are here.](https://docs.google.com/presentation/d/1GAPZ-7U97ohX0lxluv8EVim6VYBJqrDsjFQl7Rsg-Bo/edit?usp=sharing)
