### ISSUE TITLE
Write chapter on Resources

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#7]
Resources
* Colour palettes
* Layout templates
* UI Elements (icons)
* Fonts

(It's possible that this doesn't need to be an extensive chapter and should just point to build.webmaker.org)

**Comment by xmatthewx** [comment]
I've collected a few things in google drive. note: it's viewable by the public, editable by staff. https://drive.google.com/folderview?id=0B_rbDAen9prkS0N4MXRqaGo4bEE&usp=sharing

**Comment by sabrinang** [comment]
## Colour Palettes
#### Current Overview
* Upcoming extended [Mozilla & Mozilla ID Palette](http://blog.seanmartell.com/wp-content/uploads/2014/09/colors-and-shapes.png) _(still in the works and not fully locked down yet)_ being explored by Mozilla's [Creative team] (https://blog.mozilla.org/creative/) - used by various Mozilla campaigns (i.e. [End of Year](http://fundraising.mozilla.org/))
* [Mozilla Colours] (https://www.mozilla.org/en-US/styleguide/identity/mozilla/color/) _aka Sandstone_  - used by [Mozilla Foundation] (https://www.mozilla.org/en-US/foundation/), [Mozilla Advocacy] (https://advocacy.mozilla.org/)
* [Makerstrap] (http://mozilla.github.io/makerstrap/demo/#/) - used by [Mozilla Webmaker] (https://webmaker.org), [Web Literacy Map] (https://webmaker.org/en-US/resources)
* [Hive Color Palette] (http://hivelearningnetworks.org/wp-content/themes/hive-learning-networks/resources/Hive_2014_BrandGuidelines_10_5.pdf#page=15&zoom=auto,-13,769) - used by [Hive Learning Networks] (http://hivelearningnetworks.org/)
* [MozFest Colours]  (https://www.dropbox.com/sh/mtrh1oj0epg0zb1/AADPDpjMPRgE_PFtvn3WeIYva/Mozilla%20Festival%202014/MozFest%20Design%20Assets?dl=0#/) - used by [Mozilla Festival] (mozillafestival.org)
* [Maker Party Palette] (https://party.webmaker.org/party-resources/MakerPartyBrandPalette.png) - used by [Maker Party] (https://party.webmaker.org)
* [Training Palette] (https://www.dropbox.com/sh/8xxn7a71rxyamwn/AAAiO5o730Z2hYuJzNwywOI1a?dl=0) _aka #TeachtheWeb Palette_ - used by [Webmaker Training] (https://training.webmakerprototypes.org/en/) teaching kits
* No documented of palettes/swatches used by [Knight-Mozilla OpenNews] (http://opennews.org/) & [Mozilla Science Lab] (http://mozillascience.org/) yet

![mofo_design_handbook_resources_colour](https://cloud.githubusercontent.com/assets/2492510/5689815/7ba18378-9822-11e4-959e-86474c47abd2.png) 
#### Future Ideas
* Unify & document colours
* Swatch files, HEX value & Colour variables for stylesheets
* Organizing colours used that are outside primary palettes (i.e. UI colours, states, backgrounds, borders, social media etc.) - [_lonely planet's palette example_] (http://rizzo.lonelyplanet.com/styleguide/design-elements/ui-colours)

**Comment by cassiemc** [comment]
Hmmm. This work has come along way with the teach and Mofo-wide design audits. I'm going to close and we can reopen smaller issues as they become relevant.
