### ISSUE TITLE
Templatize social share graphics for Facebook and Twitter

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#70]

**Comment by cassiemc** [comment]
@sabrinang updates on this?

**Comment by sabrinang** [comment]
<img width="1440" alt="screen shot 2015-08-17 at 12 49 02 pm" src="https://cloud.githubusercontent.com/assets/2492510/9314607/bfba08dc-44de-11e5-85f5-b03337278453.png">
I added this template to the assets folder which includes email callout, twitter, facebook and directory tiles. I included notes and examples on separate layers for reference.
You can find it Design Assets › Templates & Guidelines › Social Sharing: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eT0g1OFZxU2txSmM/view?usp=sharing

Any feedback on this @cassiemc if I should separate the files (maybe directory tiles should belong elsewhere?) or other documentation I should include?

**Comment by cassiemc** [comment]
Awesome @sabrinang! I'm okay with them being altogether but it does make them slightly harder to update whenever there are changes to individual platforms. For that reason, I would separate them out. 

And then the only thing I would change is to add what they look like in context, so what does the image look like in a Facebook post, etc.

If you have other notes about placing elements I think that'd be awesomely helpful, but we can probably improve and streamline them further through follow-up tickets.

**Comment by cassiemc** [comment]
@sabrinang Any update on this?

**Comment by sabrinang** [comment]
Yeah it makes sense to separate the files and I will do this approach after I get the thimble assets complete (next week) and include in context examples. Also been referencing http://sproutsocial.com/insights/social-media-image-sizes-guide/ as a resource.

**Comment by cassiemc** [comment]
@sabrinang is super busy with the Thimble launch materials so I am going to move this to the next heartbeat.

**Comment by kristinashu** [comment]
@sabrinang I can make these updates if you want?

**Comment by sabrinang** [comment]
@kristinashu - I can update these from my thimble social files that are in progress already which I think will save work. Thanks though! 

I will update this ticket again before the end of this heartbeat.

**Comment by cassiemc** [comment]
@sabrinang is on PTO this week, so moving to the next heartbeat.

**Comment by cassiemc** [comment]
@sabrinang think you'll be able to get to this next week? (is more important than the illustration work in #75

**Comment by sabrinang** [comment]
All templates can be found in Design Assets gdrive folder as .ait files:
Design Assets > Templates & Guidelines > Social Sharing

<img width="1329" alt="screen shot 2015-09-21 at 10 36 36 am" src="https://cloud.githubusercontent.com/assets/2492510/9999835/633d3a54-604d-11e5-81d7-efe34664b837.png">
Twitter social share template: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSzl2UE9IZmtsQTA/view?usp=sharing

<img width="1329" alt="screen shot 2015-09-21 at 10 35 00 am" src="https://cloud.githubusercontent.com/assets/2492510/9999843/725e86fa-604d-11e5-9b13-0309c3aa8c72.png">
Facebook social shares template: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eZy0ySG9DUWU0Z2c/view?usp=sharing

<img width="1329" alt="screen shot 2015-09-21 at 10 36 28 am" src="https://cloud.githubusercontent.com/assets/2492510/9999860/888b3676-604d-11e5-9020-f1814db64197.png">
Open Graph social tag template: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eS2NpbGNCNnh5d3M/view?usp=sharing

<img width="1329" alt="screen shot 2015-09-21 at 10 34 30 am" src="https://cloud.githubusercontent.com/assets/2492510/9999865/8ea55604-604d-11e5-99ff-febf35eb7c9f.png">
Directory Tile template: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eS2RQdTlXRHJWcFE/view?usp=sharing

Feedback? @cassiemc 
Is there anything to add to these templates that you have used in your social shares @lovegushwa?

**Comment by cassiemc** [comment]
@cassiemc Look!
