### ISSUE TITLE
[MozFest] 2021 space icons 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#701]
MozFest 2021 will have a couple new spaces so we need to create new icons for them that will align [our established ones](https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit#slide=id.g402a7d20d2_1_0) (see slide 20).

@jamilasnell @marcwalsh could you please add any info you have about the new spaces as well as who would need to approve the new icon design?

**Comment by marcwalsh** [comment]
Thanks Kristina, here is the link to the Space Names and Descriptions:

https://www.mozillafestival.org/en/uniquely-mozfest/spaces/

**Comment by kristinashu** [comment]
Sabrina to work on this with @nancyt1 (still working on getting her permission to this repo...).

**Comment by sabrinang** [comment]
Started a gslide deck to collaborate and capture process with Nancy here: https://docs.google.com/presentation/d/1Lo-E0bFEcx5_KLJtmfyaNnnGsKMu0nfLE2de1ZMoLMI/edit?usp=sharing

**Comment by kristinashu** [comment]
Amazing context, thank you Sabs!

@marcwalsh do you know what the applications will be for this, as in where will they appear and how will they be used?

**Comment by marcwalsh** [comment]
Thanks @sabrinang 

@kristinashu - We'll be using this on our website and in comms, and then also in the virtual spaces, but those are quite still tbc, it might be virtual wayfinding or for zoom backgrounds etc. We may also use them if we're having a small virtual event in Amsterdam in March. 

Alongside the icons - it would also be good to have the associated colours like we've had in the style guide in previous years.

**Comment by sabrinang** [comment]
Nancy and I have developed space icons for the seven new space themes for MozFest this year:

- AI IRL
- AI Wellness
- Creative AI
- Global Culture and Heritage
- Shifting Power in Tech
- Sustainability
- Tech for Social Activism

@stephwright @marcwalsh Please review redpen: https://redpen.io/p/hr4dd8bc059ab682da and leave any preferences or feedback on the new icons by Monday end of day.

After hearing back from you, we will continue the process of refining and narrowing it down to have one icon for each space. Next week, we will finalize icons and pair associated colours to wrap up the set to include in the style guide.

**Comment by sabrinang** [comment]
@nancyt1 I'm cleaning up a [file](https://drive.google.com/open?id=1H_BkT7XoyYXUWnAOz9nb5VOO_5W7wuPT&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) to refine and pull in our icons from the feedback we got. Let's sync up this week.

_Note to discuss so I don't forget: color pairing + style guide exporting too_

**Comment by sabrinang** [comment]
Thanks for all the feedback last week, Nancy and I refined the icons based on the feedback and cleaned up icons for visual consistency. We also paired icons with associated colours if needed for wayfinding and more _(used palette from previous MozFest and existing spaces have kept their colours)._

@stephwright Please review revised redpen:  https://redpen.io/p/hr4dd8bc059ab682da

**Comment by stephwright** [comment]
FANTASTIC!  Thumbs up on all of them!

**Comment by sabrinang** [comment]
- Updated style guide ([slide 20 + 22](https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit#slide=id.g7e72147856_0_150))
- Exported .svg/.png in black/white assets and exported .ai file and .jpeg overview image in google drive here: https://drive.google.com/open?id=16cRmXIQQ9e8VR3OLfsNK6XaO95heYZqT&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Space icons are good to go! @stephwright is there anything else related to this ticket outstanding or we good to close?

**Comment by stephwright** [comment]
Nothing else... this is perfect!  Thanks @sabrinang ... Closing.
