### ISSUE TITLE
Ring video support

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#705]
Onboard agency to our video bumpers and give feedback.

**Comment by kristinashu** [comment]
@natalieworth could you please compile all the possible info they will need in one place and make sure they have permissions to view it.

List of assets P&G will provide is here https://docs.google.com/document/d/1PiRYdffju3NI-idk8hRL0KetOnJeb0Wbl6XaStf0Be4/edit#

Possible things to include (please add anything else you can think of)
- Kaili's video 
- Note that she wants Silent Night as the music
- Dimensions for our blog
- Files for our bumpers
- Confirm with Kaili what the text should be (CTA at the end)
- ...

**Comment by natalieworth** [comment]
I put [together a slide document with relevant branding and video assets](https://docs.google.com/presentation/d/1b0-KBHzZ0HXBZeuJZWB7O34_795e36V8CDrQiBjmGFE/edit?usp=sharing). Kaili and I met with Carly today to go over the requirements and hand-off the design and video assets. Carly will reach out to me and cc Kristina if there are any questions from their designer or animator.

The first round of review will be approved by me, Kristina, and Kaili (and shared with Audrey). The final review will have to be approved by Ashley.

Kaili has reached out to Ashley to confirm if we need the ring.com watermark to go through legal, or if it's okay to include.

**Comment by natalieworth** [comment]
This campaign and email have gone out! Final [deliverables from the agency are in here](https://drive.google.com/open?id=1WRFsllPSlbW6ssMEyoWHZpOJ_z3n1o6P&authuser=natalie%40mozillafoundation.org&usp=drive_fs).
