### ISSUE TITLE
PNI contest graphic - due Nov 27

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#708]
Audrey needs a very simple graphic based on our PNI images in square and Twitter size 1.91:1 to promote our competition. It should say:

____sees you when you're ____. ____ knows when you're ____. ____ knows if you've been ____ or ____, so be ____for goodness sake.

**Comment by natalieworth** [comment]
[Final files for this are in here](https://drive.google.com/open?id=1MamZnmPzaGUwYm_RZDklLaQ3UNoIYso_&authuser=natalie%40mozillafoundation.org&usp=drive_fs) @AudreyMofo
