### ISSUE TITLE
Zoom e2e: email and blog graphics on how to enable it - agency support deadline Nov 30

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#709]
Related to - Zoom e2e: social graphics on why encryption is important #707 

Blog post and promo of that post about how to enable e2e.

Stakeholder: Kaili

Deadline for Nat to give to agency: Nov 30

Deadline for agency: Dec 7

Design agency will create the graphics but Natalie will prepare all the assets they need.

Graphics will be based on [Zoom's instructions](https://support.zoom.us/hc/en-us/articles/360048660871-End-to-end-E2E-encryption-for-meetings).

Deliverables for agency
- Multiple visuals showing how to do it for the blog post
- Assets for promoting it on 
  - Social (Twitter & LinkedIn)
  - Email (Nat to add specs)
  - Mozilla blog (Nat to add specs)
- Text in graphics will need to be localised

### Natalie to
- [ ] Review similar work we've done suggest visual direction to agency
- [ ] Share all working files with agency
- [ ] Give agency specs to assets they won't know - email and blog
- [ ] Gather final copy and make sure it is organized in a clear way
- [ ] Confirm and localisation needs
- [ ] Can you think of anything else?

**Comment by natalieworth** [comment]
We talked about this briefly with the agency today—Kaili said we're still waiting on Zoom to release the e2e, but I'll have all files prepped here when it's ready to go.

**Comment by natalieworth** [comment]
Have a doc [started with notes and assets](https://docs.google.com/document/d/1kdcbPgj2w4gbfe2CXHzQ0zFhu894-EKkcNh3bBD6de8/edit#) in here but still awaiting Zoom to release the feature from beta.

**Comment by kristinashu** [comment]
Thanks for prepping all this Nat! Moving this to icebox tho since it sounds like the feature won't be available until March or so.
