### ISSUE TITLE
[Dialogues & Debates] December - Deadline Dec 10

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#711]
Via @KevZawacki 

Panelists still TBD; here's the proposed line-up:
https://docs.google.com/document/d/1MsxekosrJU5Sxv4isJyZDMWmypqxUQV-UWgypDjwo94/edit#bookmark=kix.43lkjnhrlppd

Will be shared on the blog, Instagram, Twitter and LinkedIn so I believe we need:
- [x] 16:9 image with the following information and images of the panelists (see bottom of doc)
- [ ] 16:9 image with "thank you for joining us", and our social channels to tend the live stream
- [ ] Header image for the blog post
- [ ] OG image for the blog post

**Comment by KevZawacki** [comment]
Hi there @natalieworth. The text for the D&D graphic is now final:

[Mozilla logo]
MozFest Dialogues & Debates
*Privacy Not Included
with Jen Caltrider, Amira Dhalla, Xavier Harding, and Nicole Shadowen 
Thursday, December 17
8am PT / 11am ET / 4pm BST 

Here's Xavier's headshot; I should have the rest today & tomorrow. 

![Xavier](https://user-images.githubusercontent.com/11045250/101644050-c1297f80-3a02-11eb-908e-e6ad8caafa0a.jpg)

**Comment by KevZawacki** [comment]
Here's Jen's headshot: 
![jen_caltrider](https://user-images.githubusercontent.com/11045250/101649349-c8ec2280-3a08-11eb-8a8c-9dfd99ae122c.jpg)

**Comment by natalieworth** [comment]
Hey @KevZawacki are these all finalized? Do we have Amira and Nicole's headshots?

**Comment by KevZawacki** [comment]
Hi @natalieworth, the participants are finalized. I'm still waiting for Amira and Nicole to email their headshots -- I'll add them here as soon as I have them.

**Comment by natalieworth** [comment]
Okie thanks, Kevin!!

**Comment by natalieworth** [comment]
I can start on these now and just add their headshots this afternoon/ tmrw when we get them

**Comment by KevZawacki** [comment]
Thank you, @natalieworth. Here's Amira's headshot; now just waiting on Nicole. 
![Amira - headshot](https://user-images.githubusercontent.com/11045250/101854409-7d806400-3b2f-11eb-9ff4-1f8f76bd19f9.png)

**Comment by KevZawacki** [comment]
Hi @natalieworth & @jamilasnell, below is our final headshot. Thank you for your patience! 
![Nicole](https://user-images.githubusercontent.com/11045250/101944479-c92c1f80-3bba-11eb-9d84-714f63f37e22.jpg)

**Comment by natalieworth** [comment]
Hey @KevZawacki 

I've added in Nicole's image and [the exports are all in here](https://drive.google.com/open?id=1TykSFmxbZFruUOsXaRrnYfFFq3x9WB2L&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

Let me know if you need anything else for this.

Cheers.

**Comment by sabrinang** [comment]
@natalieworth request via Audrey on slack:
> is it possible to get the time zone updated for UK? It should say GMT (BST is British Summer Time)

**Comment by natalieworth** [comment]
Thanks Sabs! I've updated for you @audreymofo. [File is in here](https://drive.google.com/open?id=1TykSFmxbZFruUOsXaRrnYfFFq3x9WB2L&authuser=natalie%40mozillafoundation.org&usp=drive_fs).
