### ISSUE TITLE
Digital Holiday card for MoFo staff

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#712]
Via Amanda:

> Reaching out on behalf of Lainie and the Social Committee! Looking to have designed a simple holiday e-greeting card/digital card (the message would come from Exec and/or Leadership Team) and Mark can send it in his email at eoy to all MoFo team

We could re-purpose some of the holiday designs from last year or this year.

**Comment by natalieworth** [comment]
Sent this to Amanda and she will have approval of one or feedback for Monday
https://redpen.io/p/bc9fd65b36a738cc9d

**Comment by natalieworth** [comment]
[Final Export is in here](https://spark.adobe.com/post/gAgTiWZO34qmu/)
