### ISSUE TITLE
#DearInternet - Quote Cards for Social (Report Back)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#713]
We want some "quote cards" with text from some of our submissions when we get through them - they should be super simple and using on top of existing Dear Internet backgrounds. These are images for social media channels.

Audrey should have the content mid this week and we can put them out next week

**Comment by sabrinang** [comment]
Note: Get more specs from Audrey or Airtable

**Comment by sabrinang** [comment]
From AirTable: We're sorting through stories and want to share some of them back on social using some images. More context in previous doc: https://docs.google.com/document/d/19ka3kxriFKdu3HRWfW74gLJ_yMl3ZLJsaUfu2kCnjak/edit

**Comment by jamilasnell** [comment]
were you able to get the specs from Audrey?

**Comment by sabrinang** [comment]
@jamilasnell Yes I got the copy/specs, they are a instagram story/twitter fleet series (9 panel), instagram posts (4) and tweets (8).

**Comment by jamilasnell** [comment]
Perfect! On the airtable ticket, she put a due date of today (12/14), have you talked to her about pushing it back? If not, I can message her.

**Comment by sabrinang** [comment]
I wasn't aware of that specific due date, I got the rest of the content this morning so started today so I can prioritize this now. I heard this morning it was going out "over the holiday break" but wasn't sure on timing specifics but I will have them done by end of sprint _(publication stuff has been coming up so I didn't start on this last week)_

@jamilasnell can you get some clarity on timing expectations? that would be helpful!

**Comment by sabrinang** [comment]
@AudreyMoFo Ready for review on redpen here: https://redpen.io/p/ca392c69ebd8830992

**Comment by Audreymofo** [comment]
Sabrina these are excellent! Thank you! Please send the google drive link and I'll post the story and fleet today!

**Comment by sabrinang** [comment]
Phase 2 social assets are exported in gdrive here: https://drive.google.com/open?id=1Ft8qEPLd5dbhCx0y_BwmakzhOAYOIFow&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
@Audreymofo Let me know if there are anything else you need or we good to close the ticket?

**Comment by Audreymofo** [comment]
That's fine, please close
