### ISSUE TITLE
Mozilla News Beat: December 18, 2020

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#715]
Placeholder ticket for Dec 18, 2020 Mozilla News Beat.

**Comment by jamilasnell** [comment]
Is this still blocked? Did you get what you needed from Xavier to launch this?

**Comment by natalieworth** [comment]
[Final files from Nancy are in here](https://drive.google.com/drive/folders/1GUzNldmYXfAka29YMi-8SOxTwe88uagy?usp=sharing)
