### ISSUE TITLE
Prep for Kristina's onboarding

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#72]

**Comment by vazquez** [comment]
If you need any help on this, let me know :)

**Comment by cassiemc** [comment]
Cool thanks @vazquez! I'm going to go off of a template @valiantry created for her team and adapt as needed. I'll definitely rely on you to do some process / culture introduction with her and I'm open if you have other ideas as well... We can chat about it tomorrow.

**Comment by cassiemc** [comment]
I started adding links to the (adapted) engagement onboarding doc to have more of a design focus: https://docs.google.com/spreadsheets/d/1eLhQEI3dPv9zOr88KrQ8yVhNZ4buOUUMNdQRrynGlKU/edit#gid=0 

@vazquez Are you able to review this and add anything I might've missed? (I'll figure out who can do what in terms of meetings and send out meeting invites by end of week).

**Comment by vazquez** [comment]
- I added a new resource for the org chart that Mandy worked on. It's easier to navigate around.
- Should setting up Egencia be a checkpoint? I remember it took me a bit of time to get that set up when I was hired.
- Should we set up a walkthrough of the Google Drive? We can also make sure that Kristina has all the assets and apps necessary (fonts, Photoshop, Illustrator, Sketch)

**Comment by cassiemc** [comment]
Great suggestions thanks so much @vazquez!

**Comment by cassiemc** [comment]
This is done. Final doc for Kristina is here: https://docs.google.com/spreadsheets/d/12bh1d7mXKM-4NYSs5aCwVRdUKNaEX2Zk2Gqvximjan0/edit#gid=0

The template for On-boarding is here: https://docs.google.com/spreadsheets/d/1eLhQEI3dPv9zOr88KrQ8yVhNZ4buOUUMNdQRrynGlKU/edit#gid=0
