### ISSUE TITLE
Petition/ Campaign Deliverable

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#720]
### Intro

In the past, petition/ campaign deliverables have been a creative way for the Advocacy team to deliver petition signatures or results to companies and signees. It's a way to place pressure on companies or policies to change while providing feedback on results—and Mozilla's role—for our audience.

We're wanting to brainstorm some possible options for petition deliverables and also close the feedback loop on petition results for signees.

*I'll meet with Kaili this week and I will post further details/update the to-do list here when I have more information.

### To-do
Meet with Kaili
Gather benchmarks
Slide presentation with benchmarks and possible deliverable options for 2021

**Comment by kristinashu** [comment]
Info about a possible real petition delivery is [here](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recUaiMXHYdpe3oGf?blocks=hide).

**Comment by natalieworth** [comment]
Have research, notes, and ideas for this in 2021 in a google slide deck here.

I'll leave this open/ move into next tic and go over with team and Kaili when we're back in the new year.

**Comment by kristinashu** [comment]
Oh I don't see the link to the deck?

**Comment by natalieworth** [comment]
Oh ooops! Sorry I forgot to attach the link. Friday pre-holiday brain 🧠😭😫 :
https://docs.google.com/presentation/d/1GuXJgymcFcx4sA1sl_sFRBByzYM-Xe9Z1JuoWrUsnxQ/edit?usp=sharing

**Comment by natalieworth** [comment]
Going to discuss this in Crit on Thursday.

**Comment by natalieworth** [comment]
Showed this in crit and shared it with Kaili. I'm going to close this tic for now as Kaili is setting up a meeting with her and potentially Jon to go over low budget strategies for petition deliveries and to tell us about her experience/background in it a bit. (Will be super helpful).
