### ISSUE TITLE
Localized assets for IDFA petition

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Design#722]
![image](https://user-images.githubusercontent.com/1294206/102479104-5dcccc80-4056-11eb-9f89-8ee755e6fb85.png)

Hi, we’re going to localize the IDFA petition & email ([RASCI here](https://docs.google.com/document/d/10sZjEBHJQtPv2H5awNRV38yJcxlNd_k20cxA54xLsxw/edit#)), and will try to get it launched before the break, as this will have a positive impact on fundraising. We would need the asset above in French, German & Spanish as an email header and I should be able to provide translations later today or tomorrow.

@kristinashu can you help triaging this one please?

Thanks!

(btw, just noticed that http://bit.ly/mozdesignbrief is a dead link)

**Comment by kristinashu** [comment]
@TheoChevalier please ping @natalieworth once you have the translated "Thank Apple for Protecting Your Privacy" text.

> (btw, just noticed that http://bit.ly/mozdesignbrief is a dead link)

We use this link now https://mzl.la/request

**Comment by TheoChevalier** [comment]
@natalieworth  Here are the translations!

FR `Remerciez Apple pour la protection de votre vie privée`
DE `Danken Sie Apple für den Schutz Ihrer Daten`
ES `Dale las gracias a Apple por proteger tu privacidad`

**Comment by natalieworth** [comment]
Hey @TheoChevalier , I have the [drafts in Redpen here](https://redpen.io/p/pe39dd1028e6b811df)

If they're all good/ no errors, I have the final files exported [at 1x and 2x in here](https://drive.google.com/open?id=1YXi8LNt7AuG3iD45hxNFfuOeaZhTFUes&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

**Comment by TheoChevalier** [comment]
Hi @natalieworth, thanks, they look good!
The only issue is that they don’t seem to be optimized for email, would it be possible to optimize them like this one? https://image.e.mozilla.org/lib/fe9915707361037e75/m/6/856638ab-2d30-4a71-bfb4-7ef87b73da16.jpg

Thank you!

**Comment by natalieworth** [comment]
Hey @TheoChevalier [Let me know if these would work](https://drive.google.com/open?id=1_Bie4fZsDZI5tGj8FkWhI5JlJAxCh87-&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

I made them a little larger in resolution so they're less blurry, but file size is still small (around 70kb each)

**Comment by TheoChevalier** [comment]
Thanks @natalieworth, they look great in emails! Going live with these!
