### ISSUE TITLE
Figma Migration Plan

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#723]
We are planning to switch tools from sketch/abstract to figma. Let's come up with a plan on: 
- how we structure and organize the assets we use for our web properties in figma
- how we can coordinate these components with devs so it's aligned and coordinated with the design system
- how we can best set up our files too if we are crossing over to storybook

**Comment by kristinashu** [comment]
Sabs, I'm going to remove the "needs discussion" tag since I feel that tags means that the ticket is blocked because we need to talk about e.g. at stand. Whereas for this ticket, yes you need to talk with other people about it but those discussions **is** the work for this ticket. Hope that makes sense :)

**Comment by kristinashu** [comment]
Also, I think Nancy is going to be way too busy this upcoming sprint so I'm going to un-assign her (although hopefully she can help in the future) and assign myself.

**Comment by kristinashu** [comment]
Set up a meeting for Feb 3 to kick this off with devs. Moving this ticket to next sprint.

**Comment by sabrinang** [comment]
@kristinashu I made a google doc with ideas looking into figma migration / design system (WIP): https://docs.google.com/document/d/1IkzUlr1l97NEte8MtW7bPNhlANib4sQUiMZP7eeIe54/edit?usp=sharing

**Comment by sabrinang** [comment]
We also took notes in design / dev doc so it has meeting notes and ideas: https://docs.google.com/document/d/1GGfXpHIh0PLrIeO4QOYxMg0o0O6AJ1P47vCBAI1Id-g/edit#

Next step to create the figma library outline and organization plan.

**Comment by kristinashu** [comment]
Thinking about this more... perhaps our design/dev meeting was enough for this ticket and you could open a new ticket for creating the figma library outline.

**Comment by sabrinang** [comment]
I created a new ticket for library outline here: https://github.com/MozillaFoundation/Design/issues/765
