### ISSUE TITLE
Trustworthy AI Whitepaper Marketing Assets

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#725]
Capture context what the project is, what assets has been made for it, who the audience its for, what assets are needed and how the assets will be used etc. Consider handoff with something like gslides where we can document and share?

**Comment by jamilasnell** [comment]
@natalieworth @kristinashu any updates on this? Has the agency completed this task for today's due date? Thank you!

**Comment by kristinashu** [comment]
Not at all. We still don't any enough info to even approach the agency with this project. This ticket is to be worked on this upcoming sprint. We still need to talk about this project at Fab Forward. @jamilasnell have you reached out to Lindsay at all, maybe invite her to FF meeting?

**Comment by jamilasnell** [comment]
Ahh please excuse my comment, I mixed up the deadline with another request. Deadline for this is actually the 15th!

**Comment by kristinashu** [comment]
No worries. I think everyone has a little holiday brain still!

Jam has just shared [the graphics request form](https://docs.google.com/document/d/1gtbNe_Jqj_FVm0IpZt_bSFxy7C8STC_1lq8JmBWdRdg/edit) that Lindsay filled out. It has clarified a lot of the request. Let's all chat at sprint planning to see if we think we can do this ourselves or not. Although I still think we should create a 'hub' of all our T.A.I assets.

**Comment by kristinashu** [comment]
Doesn't look like this will be too much work so Natalie can do it. @natalieworth will reach out to Lindsay Dearlove and Audrey about it clarify the deadline and if the copy should be in the graphic or not.

**Comment by natalieworth** [comment]
I've sent to Audrey and Lindsay for review and have the [first versions in Redpen here](https://redpen.io/p/am4aea60c06351b438).

**Comment by natalieworth** [comment]
I've sent these to Audrey and Lindsay and [exported the final graphics here](https://drive.google.com/drive/folders/1bDyGDs-GdAFbaa3ORLcMA1v0d1OVCGJF?usp=sharing).

[Working file is here](https://drive.google.com/drive/folders/1b4DZCQRSKWtWTJnFkri-Fc7hQrL8EVUK?usp=sharing).
