### ISSUE TITLE
[PNI] V-Day Toys and Apps Marketing planning

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#726]
Kickoff and capture context what the project is, what assets has been made for it, who the audience its for, what assets are needed and how the assets will be used etc. Consider handoff with something like gslides where we can document and share?

**Comment by kristinashu** [comment]
There have been a couple kick-off meetings. Notes are [here](https://docs.google.com/document/d/1Bcr5HYtukLi79kp75PPCP-YzvPoJq16V5WM3QisAP2Y/edit#).

A few highlights:
- No website updated are needed
- Pretty standard assets for website, email, social , ads will be needed
- Lindsay would like to stick with the 3-d emoji style but v-day it up

@natalieworth you've been invited to the next meeting (today's was at 7am!). Up to you if you want to create the graphics or if we should hire P&G. Either way tho, you should gather all the requirements and guide the direction.

My suggested todos:
- [ ] Gather all the assets is here https://github.com/MozillaFoundation/Design/issues/736
- [ ] Fill out the [graphics request](https://docs.google.com/document/d/1Q1VraPc5e9uTD6eR7C2WQZMyP1yxz77nBFtGdeyxBNM/edit?usp=sharing) form with Lindsay and Audrey (really list out **all** possible graphics needed - fo'mo homepage hero, PNI hero, OG images for categories, email, blog posts.... localisation...) 
- [ ] Outline of Github tickets needed and their deadlines
- [ ] Open tickets for them - including an epic

**Comment by kristinashu** [comment]
cc @jamilasnell since she's also involved with this work!

**Comment by natalieworth** [comment]
So based on last years Valentine's guide, assets included:

- Valentine's day specific banner 
- Foundation homepage feature image
- Instagram post (1:1)
- Twitter (1:91:1)
- Blog Image


New assets to include this year

- Foundation hero image
- Gifs
- Instagram story
- Any advertising materials?
- Email?

@audreymofo and Lindsay, do you know what we would need for any advertising?

[Here are the files from last year for reference](https://drive.google.com/open?id=1iNXBJa5c8lS_Wrw4NiRj9Txovg1JyyTs&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

**Comment by natalieworth** [comment]
Met with Audrey and Lindsay this morning to talk about direction and brainstorm ideas.

[Ideas and notes are in this doc.](https://docs.google.com/document/d/1Bcr5HYtukLi79kp75PPCP-YzvPoJq16V5WM3QisAP2Y/edit?ts=5ffdec14#)

Next steps are to work on briefs (Audrey/Lindsay) and I will work on directions for the sex toy and dating app themes.

**Comment by natalieworth** [comment]
Lindsay has created [the design brief](https://docs.google.com/document/d/19Bu1meUVlyqKGSd13qOjR82tp4QkqBr1d8BLWSvDSb8/edit) outlining our audience, assets, and a small brainstorm around 1 possible direction.

Moving the assets that need to be created into [a new ticket here](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/739)
