### ISSUE TITLE
T.A.I Twitter Chat Graphics - Jan 5

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#727]
via Audrey in [Airtable](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/reccdMSfA5o7pCDwu?blocks=hide)

[Copy Doc ](https://docs.google.com/document/d/1_IkmWAaQQu-YfTG_x6GMSZFEYqA24Gp_PoUbmvZLEWA/edit#)

- [x] General graphic for Twitter post 1.91:1
- [x] Twitter post graphic 1.91:1 for each question

**Comment by sabrinang** [comment]
@natalieworth If you need reference to previous TAI assets:

- working file for [TAI publication banner graphics](https://drive.google.com/open?id=1F1i1Ki12I-6F5osnBP2Z_znhj3Y3I79x&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- working file for [fundraising AI campaign graphics](https://drive.google.com/open?id=1VTRg1Od4YXWtZ450As20uu0AOEOCmrWt&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- working file for [TAI email graphics](https://drive.google.com/open?id=1_GuvXs1fzSW98I6D30UF0JQvVnEPXlCK&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

**Comment by kristinashu** [comment]
Oooh thank you Sabs!

**Comment by natalieworth** [comment]
@audreymofo [Have the files here for review ](https://redpen.io/p/fy9225d9bb40c7e1c3)

**Comment by Audreymofo** [comment]
Looks super, thanks @natalieworth !
