### ISSUE TITLE
Mozilla News Beat: January 8, 2021

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#728]
Placeholder ticket for Jan 8, 2021 Mozilla News Beat

**Comment by kristinashu** [comment]
I think a simple version of this went out. Probably good to close this ticket?

**Comment by nancyt1** [comment]
Yeah, files were [here](https://drive.google.com/drive/folders/14KP0AYzsguW4JbHnRDL4LeYy3iWg8mDk?usp=sharing), just in case.
