### ISSUE TITLE
Plan for new email design templates

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#730]
See notes here https://docs.google.com/document/d/1tZ79op1I5hJXx2qRSPmbNa2Avs3umxNMgUgo6gSYb00/edit#

**Comment by kristinashu** [comment]
@jamilasnell can you please add the specs and timeline here?

**Comment by jamilasnell** [comment]
Heard from Steph: "I did get a sorta spec sheet, it is geared more for coding but that may help the designers. Lauren and I are looking to potentially putting together a meeting between Acoustic email coders for the designers. I'll let you know when I know more. https://help.goacoustic.com/hc/en-us/articles/360043609413-HTML-quick-reference-for-email"

Don't know what the timeline would be but hopefully would know more tomorrow

**Comment by jamilasnell** [comment]
@anilkanji Please let us know what is the expected timeline

**Comment by anilkanji** [comment]
Let's move forward with this @jamilasnell - the deadline Stephanie had shared was 2/28.

**Comment by kristinashu** [comment]
New deadline is mid/end of March. With this new deadline, I think @nancyt1 might be able to work on this. We'll meet tomorrow to discuses possible next steps.

**Comment by kristinashu** [comment]
I've created a plan here https://docs.google.com/document/d/1tZ79op1I5hJXx2qRSPmbNa2Avs3umxNMgUgo6gSYb00/edit# and opened an epic and two tickets for next sprint.
