### ISSUE TITLE
AI Explainer Art Direction

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#731]
Audrey has started production with the video contractor on the first series of video for the Mozilla Explains series. We are going to be working with a video producer and (hopefully) an animator. This ticket is for tracking the art direction of the videos to make sure it is in line with Sabrina's T.AI graphics and the Foundation branding. 

@natalieworth will be responsible for the direction and providing assets and feedback for the contractors

Next steps for this ticket:
- [x] Gather benchmarks for the animation style we want for Becca's video (video 1)
- [x] Figure out opening bumper (do we have budget for Eugene to do this) and provide direction for that
- [x] After Tyler adjusts the videos based on Audrey's feedback, I will provide brand assets and direction

cc @audreymofo

**Comment by natalieworth** [comment]
I have the working file delivered from the contractor for the first 2 Explainer videos.

Next steps:
- Add AI-specific ident at the beginning of the video
- update the background colours so it is more Foundation branded
- update the typography to our typefaces
- add any additional lower thirds/ captions if necessary

**Comment by natalieworth** [comment]
There is still the 1st video in the series coming, so noting this is P2 for now (after PNI assets/ Apple IFDA work). 

Also moving to next sprint.

**Comment by kristinashu** [comment]
Is this getting moved to next sprint?

**Comment by natalieworth** [comment]
Yeah, didn't have time to finish it and there were still issues with the 2nd file, so I'm going to have to send things to the contractor instead.

**Comment by kristinashu** [comment]
Ok then, so is there any work left to do for this ticket? Maybe it's just about reviewing and giving feedback to the contractor?

**Comment by natalieworth** [comment]
Updated the description of this ticket and timing. Moving into the next sprint and will connect with Audrey on Monday.

**Comment by natalieworth** [comment]
I've sent the .[ai backgrounds to Audrey](https://drive.google.com/drive/folders/10wtRAHTK57rm_7T3E1TvpQ_4f4MeNdSb?usp=sharing) to handoff to the animator.

The style frame examples are in [a google doc here](https://docs.google.com/presentation/d/1yVIfB9f8HRVotwGRsyaygUNkZcmFzIHPFamgg0oG3_c/edit#slide=id.gbcb8d458ef_0_80).

I need to still get feedback on the Mozilla explains opening text, so will add the bumper file when I have it.

**Comment by natalieworth** [comment]
Also the third video cut from Tyler is [here](https://drive.google.com/file/d/1vicRMAfeUfBq9Un0vdebKt-a9ZxxesSK/view).

**Comment by natalieworth** [comment]
1st bumper example is here.

**Comment by natalieworth** [comment]
This is almost done! Update: I'm working on fixing the opening bumper (adding in the Mozilla logo) and then providing frame instructions to send to the video contractor.

**Comment by natalieworth** [comment]
The opening bumper is here and I've sent the video art direction slides to Audrey to pass off to the contractors:

[Opening bumper](https://drive.google.com/file/d/11IQ9RRZ8fnqKF63fAj1BpzJahNOcmFoL/view?usp=sharing)
[Working file](https://drive.google.com/open?id=10ZPBinKU1O6ts3zRwtUxAL2c8SFBt7Be&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

[Google slides style frames](https://docs.google.com/presentation/d/1yVIfB9f8HRVotwGRsyaygUNkZcmFzIHPFamgg0oG3_c/edit?usp=sharing)


For reference, the video will have the opening 'mozilla explains' bumper, but (since the videos are quite long) we can just end with the full mozilla logo on black.
