### ISSUE TITLE
Apple Petition Delivery: IDFA thank you video

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#732]
### Intro

In 2021, Advocacy will be presenting Apple with our signatures collected from 2020/ email. 

Will talk with Kaili and update this ticket with more information

### Links
[Airtable link is in here](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recUaiMXHYdpe3oGf?blocks=hide)

**Comment by natalieworth** [comment]
I met with Kaili this morning. She's provided more context for me and we're thinking that a short 30-second video would be best for delivery to Apple and something that could be used for press/ social. Kaili is putting together a content doc and I will create a storyboard with text/ graphics to share. 

Due to time/ resources and Advocacy's schedule on wanting to get this out early in the year, a video with Kaili's airdrop idea feels viable—but we can brainstorm more in future. :)

**Comment by natalieworth** [comment]
Currently working on the rough draft of this with a voice-over in After Effects. Since the date and deadline has been pushed back a bit, I'm going to move this into next sprint.

**Comment by natalieworth** [comment]
Also just noting, we're aiming to have this done before January 28th.

**Comment by kristinashu** [comment]
@natalieworth is the English version done? Did you open a new ticket for the localised versions?

**Comment by natalieworth** [comment]
@kristinashu English version's almost done, just waiting for approval. Did localized versions get approved? Jam said to hold off til we were certain there was time, but I can let Theo know if we do have time next sprint?

**Comment by natalieworth** [comment]
This is done! Video and social files [are in here](https://drive.google.com/open?id=1PWbg31xgSPodb44nSEFAsqukDr2ZAE4G&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

**Comment by kristinashu** [comment]
Awesome! I saw it on Insta this morning! 

Does it still need to be localised tho? If so please open a ticket for that and link it to this one.
