### ISSUE TITLE
[MozFest] Meet Design Contractor & Onboard Style Guide

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#733]
Lucie Click will set up a meeting to go over style guide with the recently hired mozfest design contractor. This is a placeholder ticket as we don't know when it will be.

**Comment by sabrinang** [comment]
During the meeting with  @LucieClick-MFHouse I will go over:

- [ ] context and walkthrough the [Mozilla Festival 2021 - Style Guide](https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit?usp=sharing) slide deck 
- [ ] grant access slides and assets to Lucie + Contractor
- [ ] walkthrough google drive folders
- [ ] walkthrough any supplemental brand stuff to be aware of https://foundation.mozilla.org/en/docs/brand/

Other: 

- [ ] check with @kristinashu what the [Collaboration Process](https://docs.google.com/presentation/d/1rtYVRyyZ4zKByCdpLzBL-F03oB2-r-dCNonAK78MPZI/edit#slide=id.g7f18615b03_0_6) _(slide 40)_ expectations are since it is indicated in the deck
- [ ] check expectations of involvement from both Lucie/Kristina

**Comment by kristinashu** [comment]
@LucieClick-MFHouse do you have a timeline and list of deliverables the contractor will be making? Just want to get a better sense of how much and what type of work there will be for the contractor.

We'll chat more at the meeting but my initial thoughts around expectations are:
- Sabrina to meet with Lucie and the contractor on a set cadence (e.g. once a week). This is were Sabrina will give feedback and/or approvals. The idea being that this will time-box Sabrina's time and reduce the amount of her context shifting between her may other projects.
- Sabrina will review and give feedback on a few key assets at the start to make sure the contractor is on the right track.
- Sabrina needs to give final approval on every asset before they go live.

**Comment by kristinashu** [comment]
[Link to assets doc](https://docs.google.com/document/d/1fLd0i8R3JPjH7dI3D79MNKGt4kdedbSlfuTz3JqBIEE/edit?ts=5fa1baf2#heading=h.a76fn87xf4k1)
