### ISSUE TITLE
[Brand] Theme Page: Mozilla Festival 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#734]
Create a MozFest specific theme/niche specific wagtail brand page on /brand for reference that we can point contractors and collaborators too.

Planning has been done in style guide 2.0 doc: https://docs.google.com/document/d/1OLw5RGlHIXN1E8W40eg2iYD3AvNIUzB0UhS8jDCriTA/edit#

I've started on an outline here: https://docs.google.com/document/d/16EBs6D241IxbxGI3WwEfHBwWayVEovr2wKAFoOwG62s/edit?usp=sharing

related issue: https://github.com/MozillaFoundation/Design/issues/724

**Comment by sabrinang** [comment]
@kristinashu Mozilla Festival theme page is ready for review _(wagtail page set on private)_: https://foundation.mozilla.org/en/docs/brand/design/theme-page-mozilla-festival/ 

Thanks for some feedback earlier—the page consists of content pulled from other parts of the brand pages _(logos, colour, photography)_ and for more annual specific visual components, expression and inspiration it links to the style guide gslide since it is well documented in there already. Please review copy, links and structure.

After the page is reviewed/live, I can start removing the MozFest specific brand aspects from the other pages.

**Comment by kristinashu** [comment]
This looks great Sabs! So nice to have everything in one spot. 

My only feedback would be to remove the language specification from the urls e.g. write https://www.mozillafestival.org/ instead of https://www.mozillafestival.org/en/. This is generally good practice anytime we use a url so that we don't force a language on a user.

**Comment by sabrinang** [comment]
@kristinashu Good catch, I removed /en from URL. I published the page and removed MozFest specific contents other pages such as logos, color, reference and template pages.

Can you do a quick review I didn't miss anything else that needs to be cleaned up on the other pages?

**Comment by kristinashu** [comment]
Looks good! We'll have to re-think the "Agency and Contractor Assets" page but that's definitely out of scope for this ticket.
