### ISSUE TITLE
[Brand] Theme Page: Trustworthy AI

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#735]
Create a Trustworthy AI specific theme/niche specific wagtail brand page on /brand for reference that we can point contractors and collaborators too.

Planning has been done in style guide 2.0 doc: https://docs.google.com/document/d/1OLw5RGlHIXN1E8W40eg2iYD3AvNIUzB0UhS8jDCriTA/edit#

I've started on an outline here: https://docs.google.com/document/d/1hRPAzljfdv35_2xtcWIMBaoCzGdU3wagKmvRYh0Dy1A/edit?usp=sharing

related issue: https://github.com/MozillaFoundation/Design/issues/724

**Comment by sabrinang** [comment]
@kristinashu TAI theme page ready for review here _(wagtail page set on private)_: https://foundation.mozilla.org/en/docs/brand/design/theme-page-trustworthy-ai/

Please review the copy, links _(exp: should redpen links be excluded/included or if anything is missing)_ , expression board _(does it need anything else?)_ and structure. 

Trustworthy AI doesn't have any unique palettes or type etc. outside of what is on the brand pages so no old/duplicate references had been changed.

**Comment by kristinashu** [comment]
This is excellent! Love the intro and the moodboard. I think the redpen links are very useful, there a nice quick way to see view graphics.

Two thoughts, feel free to ignore!

I wonder if the redpen links should be grouped with the working files. I.e. the "Fundraising AI campaign" redpen link directly after the "Fundraising AI campaign graphic" drive folder link?

This might be crazy but could all the AI files be grouped into one master .ai file??? I feel like for making future assets it would be helpful to have everything in one place but the file could get crazy big. And I'm also not sure what this would mean for the drive folder structure.

**Comment by sabrinang** [comment]
Thanks for the feedback! 

- Great idea, I made redpen shortcut links in their corresponding folder so the links aren't messy on the page and they are all grouped together
- Not crazy but I think this one might be tricky since it shows up across various aspects of work and projects with style vairaints derived from MoFo patterns/gradient over the years. Yeah it isn't ideal for past stuff but I think as we move forward we can be more deliberate by organizing according to themes TAI with a master ai if that is what we want to do as a team so we know how and where we are store it in the drive. For what we have now, I think links are okay since that is how it was sorted across the drive. 

If we are working on TAI more in the future I think there could be a focus clean up if you think it will save us time and is a priority with what is upcoming. Also discussing drive organization structure so we have a shared understanding of where/how we want to store TAI things in the future can help with this too.

**Comment by kristinashu** [comment]
That sounds good Sabs, thanks!

**Comment by sabrinang** [comment]
👍 https://foundation.mozilla.org/en/docs/brand/design/theme-page-trustworthy-ai/ 
Page is published and public now — closing!
