### ISSUE TITLE
PNI 2020 Valentine's Day Art Direction

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#738]
### Intro

The 2021 PNI Valentine's Edition will focus again on sex toys with the addition of popular dating apps. We'll be creating the marketing assets internally, but need to establish the art direction for the assets. In our brainstorm meeting, Audrey and Lindsay provided a rough [outline of ideas that they liked on page 5](https://docs.google.com/document/d/19Bu1meUVlyqKGSd13qOjR82tp4QkqBr1d8BLWSvDSb8/edit) (continuing on the emoji theme)—but there is room to explore other directions and we still need to establish a direction for the app assets.

cc: @nancyt1 

#Links

[Art direction slide doc is here](https://docs.google.com/presentation/d/1Z5CdO_jhB4N6_A5Rm6cWlfzZjynTnrbe6eBk0rBlUIs/edit)

[Design brief from Lindsay is here](https://docs.google.com/document/d/19Bu1meUVlyqKGSd13qOjR82tp4QkqBr1d8BLWSvDSb8/edit).

For reference, here are our notes from the PNI [Valentine's day brainstorm group](https://docs.google.com/document/d/11pU2aB0traXMYv2ZSrfS_J9FVbI0T8e8pvitvA_UT8M/edit?usp=sharing).

**Comment by kristinashu** [comment]
Designs are [here](https://redpen.io/p/fs5bd39d3a73a9ef72). @natalieworth do you have a deadline for when the direction needs to be decided on?

**Comment by natalieworth** [comment]
@kristinashu we're going with the 1st direction (sultry purple w/ emojis and romantic type)—Lindsay has shared them with Carys and just waiting to hear back from her.

**Comment by natalieworth** [comment]
Talked to Lindsay about this, this morning, and she said Carys had some feedback—so need to discuss with team and adjust.

**Comment by natalieworth** [comment]
Final [art direction doc is here](https://docs.google.com/presentation/d/1Z5CdO_jhB4N6_A5Rm6cWlfzZjynTnrbe6eBk0rBlUIs/edit#slide=id.gae62332e25_0_87) and we have moved onto starting creative explorations.

**Comment by natalieworth** [comment]
@kristinashu do you think this tic is good to close since we've started creative?

**Comment by kristinashu** [comment]
Yeah I guess it's good to close since no new creative directions will be made!

**Comment by kristinashu** [comment]
Oh and they all look amazing 🍑🍑🍑
