### ISSUE TITLE
help design this graphic / table 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/Design#74]
Hey @lovegushwa or anyone else, 
would you be able to help design this table ? 

<img width="656" alt="table for the recos" src="https://cloud.githubusercontent.com/assets/8261945/9475968/df644bfa-4b61-11e5-845b-832c61a9efcb.png">

**Comment by cassiemc** [comment]
@LauraReynal when do you need this by?

**Comment by lovegushwa** [comment]
@cassiemc yes, I'm going to help @LauraReynal with it this afternoon. (I should have a draft for her tomorrow.)

**Comment by cassiemc** [comment]
Ok cool i'll add it to the Aug28 milestone and assign to you @lovegushwa

**Comment by LauraReynal** [comment]
@lovegushwa thanks for the design. I love it it's beautiful. 

Can we close this ticket?

**Comment by lovegushwa** [comment]
Yes! Thank you @LauraReynal :)
