### ISSUE TITLE
Gather Products for PNI Valentine's Day Edition 2021

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#740]
Gather and edit the products for the updated PNI Valentine's launch.

Product list TBD/ I'll talk to Jen when it's finalized.

[Last years products and the PSD file are here](https://drive.google.com/open?id=1q48nv7emk1cMbGbc-dQ9QCoAnGALpAHs&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

[Products for this year are in here](https://docs.google.com/spreadsheets/d/1mndAPx0jB1yrBJpYcu7tSn-IkssHggl0B9Eujevc2nA/edit?usp=sharing)

**Comment by natalieworth** [comment]
@nancyt1 Has gotten a start on gathering the products here and is adding them to our Valentine's folder [in here](https://drive.google.com/open?id=1ylt56YRkykbIp2mtLRlENuRScakCKfLq&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

Had some difficulty in finding good photos or png's for some, but we'll experiment or keep searching if needed :)

**Comment by natalieworth** [comment]
Nancy's gathered and edited the products 🙏 and [they're in the drive here](https://drive.google.com/open?id=1yo5ZT7vxXgTi1x6bqPR4jCzflp9Bg4YG&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

cc @nancyt1 @caltrider @jamilasnell

**Comment by kristinashu** [comment]
Those dolls 😭 🙈 😭

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by natalieworth** [comment]
@kristinashu I think so! I'll close and reopen if we need any changes. The dolls are eery lol.
