### ISSUE TITLE
[MozFest] Contractor Support

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#746]
Support design contractor related requests.

- Give design feedback to contractors on design assets (bee agency, heyheydehaus etc.)
- Review MozFest slack (grant access, unblock, give feedback etc.)

**Comment by sabrinang** [comment]
Met with heyhey and mozfest team this morning:

- [ ] write email feedback for Steph responding to book demo

**Comment by sabrinang** [comment]
@kristinashu can you review this [feedback](https://docs.google.com/document/d/1KSfRsD9qMBF7bwnWr-ERxgxj1n4WLS37MV21sGCoCIM/edit?usp=sharing) before I send?

**Comment by kristinashu** [comment]
Very thoughtful advice Sabs! One thought is that if you have any key points of feedback you could possibly highlight those a little more - either by touching on them at the start or by making them bold or coloring them.

**Comment by sabrinang** [comment]
Thanks for reviewing and the feedback - highlighting is a great idea I'll do that and send 👍

**Comment by sabrinang** [comment]
Note: support that happened this week

- granted access (for Varinia) via mozfest slack
- reviewed social images (for Bas) via mozfest slack
- gave feedback for web book (for Steph) via email

**Comment by sabrinang** [comment]
Note: support that happened this week
- made style guide share settings publicly available (request from Steph) via slack
- grant access (for Mariska) via google drive email
- space icon access (for a tech for social activism wrangler who requested) via google drive email
- instagram story review (for Bas) via MozFest slack

This support is continued next sprint here: https://github.com/MozillaFoundation/Design/issues/752
