### ISSUE TITLE
Add illustration of Kristina to build/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#75]
@sabrinang, are you up to the challenge? @vazquez can you implement once Sabrina has created the asset?

**Comment by vazquez** [comment]
No problem implementing :+1:

**Comment by sabrinang** [comment]
Yup up for the challenge - I will creep and illustrate :D

**Comment by cassiemc** [comment]
Woot! :bomb: :zap: :100: thumbs-up

**Comment by cassiemc** [comment]
@sabrinang is super busy with Thimble launch stuff so I think we can do this in Kristina's first heartbeat.

**Comment by sabrinang** [comment]
:eyes: I've been observing and sketching :dancer: 
Illustration process will most likely continue next week after Sept 10 (on PTO)
<img width="1440" alt="screen shot 2015-09-03 at 1 59 56 pm" src="https://cloud.githubusercontent.com/assets/2492510/9671556/8be48de4-5248-11e5-822d-b759a9c59ac9.png">

**Comment by cassiemc** [comment]
haha this rocks @sabrinang! @kristinashu did you know you were being watched? ;)
I'll update the milestone.

**Comment by kristinashu** [comment]
Haha sneaky! Thanks @sabrinang this is amazing.

**Comment by cassiemc** [comment]
@sabrinang just has to finish the hair! moving to next milestone.

**Comment by cassiemc** [comment]
@sabrinang should we mark this as wont-fix, and file a new issue to make a more generic pattern of faces? might be hard to keep up with new faces over time.

**Comment by cassiemc** [comment]
Marking as won't-fix. New issue filed #106
