### ISSUE TITLE
Localize Apple IFDA video

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#750]
### Intro

Ticket for localizing the Apple IFDA video.

We will add translated subtitles to the video.

### Links
Original EN version of the video is in here #732 

cc: @TheoChevalier

**Comment by TheoChevalier** [comment]
Hey @natalieworth, here are the translations! https://docs.google.com/document/d/1qnRpTSOgWoQ-rV4MCPUvdc5sFhEQd77Liv0ZJJKF25c/edit?usp=sharing

Note: some of the screens have changed after localization has started, so I’ve manually highlighted in the doc what I was certain of for what’s missing.

**Comment by natalieworth** [comment]
Hey @TheoChevalier [I have added in the localized captions](https://drive.google.com/open?id=1znlGYz55l5n7WqrV2xTRosNO4vKi_L4J&authuser=natalie%40mozillafoundation.org&usp=drive_fs). I was wonder (due to my time and some added costs) if we could keep the English words in the actual footage (e.g. the beginning where it says 'Mozilla has called on Apple', etc.)? If I translate the text within the actual video, instead of as captions, I think that counts as a 'new end product' for the music and voice over licenses...so we'd get charged for 3 more versions which would be a bit pricey.

**Comment by TheoChevalier** [comment]
> Hey @TheoChevalier [I have added in the localized captions](https://drive.google.com/open?id=1znlGYz55l5n7WqrV2xTRosNO4vKi_L4J&authuser=natalie%40mozillafoundation.org&usp=drive_fs). I was wonder (due to my time and some added costs) if we could keep the English words in the actual footage (e.g. the beginning where it says 'Mozilla has called on Apple', etc.)? If I translate the text within the actual video, instead of as captions, I think that counts as a 'new end product' for the music and voice over licenses...so we'd get charged for 3 more versions which would be a bit pricey.

Hey Natalie, thanks!
Re text of the video, that’s not ideal but I think it’s totally acceptable given the constraints, so let’s keep the videos as is.
I think we should be a great thing to keep in mind for future projects (I had no idea this would incur such costs) and try to find workarounds ahead of time :)

Also I’ve watched the videos, and they look good to me, I don’t think going through additional feedback from the vendor will be necessary, so feel free to start uploading them (or let me know who I could ping to get them uploaded!)
Also I will have the title “Thank you, Apple for Standing Strong for Privacy.” and description localized tomorrow, so we will be able to use this on YouTube as well

**Comment by natalieworth** [comment]
These are done and I've sent these to Audrey to upload to YouTube tomorrow morning. Going to close this ticket for now—but reopen if we need any additional changes. Thanks!
