### ISSUE TITLE
[Publications] Insights Data Futures Support

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#751]
Provide support for insights or data futures publication work.
Related issues from previous sprint: #6073 #6120
__________________

**Data Visualization Images**
- [ ] Interactive images/visualizations. Insights team has a contractor (Christian Laesser) who will create them. The responsibility of our team is to make sure we can integrate those on Wagtail pages - as discussed via Slack, we will integrate them in our site as static images and have a link to go to the interactive site (ideally we can host the site within Mozilla) - _we have a meeting on Feb 1 regarding this_
__________________
### Deadline

From Kasia:
• Publication date is still to be coordinated with the Data Futures Lab team but **we are aiming to have things ready in google doc form the week of Feb 17** .
• This means we would start loading the content into the **online and PDF templates from Feb 18**.
• We are aiming at a launch date on **Feb 24**.
__________________

**Comment by taisdesouzalessa** [comment]
@sabrinang added deadline to the ticket :)

**Comment by taisdesouzalessa** [comment]
Saw this comment from Kasia [on this doc](https://docs.google.com/document/d/1bzD4TlLp1EhdjjiBkCc4W7cKmQpI72-x3tP9hhH7wLc/edit?usp=sharing):

"Also I am considering  having both of our publications in one template following the research questions (similarly to how it is now: What is this? Who is trying? What can go wrong? Who is helping? Who needs this? Recommendations and Library) so it is more coherent and seen as one big piece and not separate studies (essentially it is one big landscape analysis and we’re following a roadmap)."

I tagged you @sabrinang on the same doc so you are on the loop. Adding it here too - to document it in the right thread.

**Comment by sabrinang** [comment]
@taisdesouzalessa thank you for surfacing that comment for context of how the publications tie together!

**Comment by kristinashu** [comment]
Sounds like this won't be ready for review until next sprint so I will move this ticket to our next milestone.
