### ISSUE TITLE
[User testing] Usertesting.com alternatives 

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#755]
_____
WAITING: pinged Heather and Gloria via Slack to hear their thoughts about UserZoom
_____

**Background:**
Figure out what is the best user testing platform for MoFo. Is it usertesting.com? Is it userzoom.com a good alternative ? Any others?

**To do:**
- [x] Connect with MoCo on that: some people used userzoom.com - (talk to Heather, mi-GA-thee or Gloria, see Slack thread in userreseach channel)
- [x] Look at benchmarks
- [x] Create a list of pros and cons
- [x] Present options to Kristina
- ~~[x] Do an A/B test on platforms: rerun page tests in UserZoom and compare quality.~~

**Comment by taisdesouzalessa** [comment]
Did a light research and found [this comparison table](https://www.trustradius.com/compare-products/usertesting-vs-userzoom). From there it seems UserTesting is slightly better than UserZoom (those are the companies I've seen mentioned the most in UX forums and groups).

**Considering Mozilla Foundations' needs, User Testing may be a better option because:**
• MoCo already uses that (and we could potentially get a seat with them)
• We've used the tool a few times and the interface is very easy to use, plus data gathering is simple.
• We've obtained results very quickly (in a matter of hours) and they were high quality tests.
•  They now have card sorting as one of their test options

The con is that they don't allow a big variety of tests (UserZoom seems to have tree testing  and click testing as additional features) - not offered by UserTesting. Plus UserZoom seems a bit cheaper.

@kristinashu I commented on Slack too but maybe we could give UserZoom a try using the 14 day trial? Wonder if there is a project we could test there to get a better opinion on the tool and its usefulness to us.

**Comment by taisdesouzalessa** [comment]
Unfortunately we can't use their recruitment in the free trial mode. They charge $15/user. I pinged Heather and Gloria (MoCo) to hear their thoughts on UserZoom. Will update here when I get answers.

**Comment by taisdesouzalessa** [comment]
After chatting via Slack with Heather and Gloria + having the opportunity to explore the platform a bit (they gave me access to their UserZoom) it seems to be a better option for the Foundation.
Mainly because it allows us to do a variety of tests (I can see the click test and tree testing being useful for future iterations of PNI, for instance). I feel it may be worth it a try, even though I felt strongly about UserTesting before...

**Next step:** gather Kristina's thoughts on it

**Comment by kristinashu** [comment]
Good! I think it'd be great if we signed up for UserZoom for 6-12 months to really test it out. Do you know if they provide a discount for not profits? No worries if they don't, but worth asking!

**Comment by taisdesouzalessa** [comment]
I sent them a message. I guess this ticket can be closed? Decision is made and now we are in touch with them. Follow up ticket:  #778
