### ISSUE TITLE
IH Gifs

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#756]
### Intro

Audrey's requested 4 gifs for the IHR. The [brief for these is here](https://docs.google.com/document/d/1WBTfO--txjYto-049ofAif7ztpoWpOk96AclLGimas4/edit).

**Comment by kristinashu** [comment]
@nancyt1 might have some time to work on this. Nancy, if you decide to take this one please meet with @natalieworth and Audrey to brief you on it.

**Comment by nancyt1** [comment]
Got some direction and uploaded some first drafts to the [drive](https://drive.google.com/drive/folders/1pCOJCr_IqR9yH4FhByapBA9K6TlY-pTF).

**Comment by natalieworth** [comment]
@nancyt1 These are looking awesome! I think only thing for me, is would we be able to change [this one](https://drive.google.com/file/d/1ec5-h_sfZSicDlOOUO9KPCYhlNT0qkEY/view?usp=sharing) to Zilla?

**Comment by kristinashu** [comment]
@nancyt1 I know you've been busy with email so no rush on this ticket but I am curious how much work is left to do on it?

**Comment by nancyt1** [comment]
@kristinashu I updated a gif today and sent to Audrey, I'm just waiting for feedback now.

**Comment by kristinashu** [comment]
Sweet!
