### ISSUE TITLE
Update the privacy ding text on PNI to *Nunito

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#759]
### Intro

Placeholder ticket to update the PNI ding text to Zilla or nunito.

**Comment by natalieworth** [comment]
https://redpen.io/p/fo7102e83cdd52453b

**Comment by natalieworth** [comment]
I tried 2 PNI ding options, one in Zilla and one in zilla:
https://redpen.io/p/rm4062c93ea16c22cd

**Comment by natalieworth** [comment]
The consensus seems to be Nunito!!

The PNI ding is also localized, so those languages will also have to each have the ding updated to nunito (once I export).

**Comment by natalieworth** [comment]
Need to add the localized ding versions.

**Comment by kristinashu** [comment]
@natalieworth seems like this is very close to being done! Will you be able to finish it this sprint, i.e. today lol?

**Comment by natalieworth** [comment]
Yep! I've got these done! :D

![Screen Shot 2021-04-13 at 8.46.47 AM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/e40d1746-5521-449b-ab4d-89603a9262e1)

**Comment by natalieworth** [comment]
[Dings are in here in RedPen](https://redpen.io/mj18facb2e843167d5) for reference and I can open a dev ticket for this too.

[Working file is here](https://drive.google.com/open?id=153Ktux1tQKNMa-Mq35ssD8-ePEXzQkWz&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
