### ISSUE TITLE
Design Ministry of Fun illustration/logo

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#76]
Requirement: It should be SUPER FUN!!! :sparkles::balloon::cookie::ghost:
cc @secretrobotron @LauraReynal

**Comment by lovegushwa** [comment]
Here we go! (this should be fun.)

**Comment by LauraReynal** [comment]
@lovegushwa attachment ?

**Comment by lovegushwa** [comment]
![screen shot 2015-09-21 at 2 11 38 pm](https://cloud.githubusercontent.com/assets/12228435/10005196/bf30a162-606a-11e5-8edb-5e3fcd59cd3c.png)
@LauraReynal ... What you don't use bing for fun?

**Comment by cassiemc** [comment]
Going to add @lovegushwa as a mentor for this, and remove as assignee. Let's see if we can get any contributors to help out. :)

**Comment by kristinashu** [comment]
Closing this ticket, we're trying to move away from creating more and more logos. Please feel free to reopen if anyone feels it is still relevant.
