### ISSUE TITLE
[Staff Call Presentation] Outline content for presentation

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#761]
**Background:**
As discussed on Design Huddle, prepare an outline of the Design team presentation to be showed at the staff call.

**References:**
Brainstormed ideas in the [Design Huddle Doc](https://docs.google.com/document/d/14jCcjRCqVlFXMSwhGuw-xKpZoQWbJlbxu11S5u-sEZg/edit?usp=sharing)
Also, is there a fun way we can present this? Any benchmarks?

**To do:**
- [x] draft the presentation outline
- [x] refine the chosen outline
- [ ] show to team for feedback
- [ ] hand it to Nat, who will do the slides

**Comment by taisdesouzalessa** [comment]
@kristinashu not sure if this fits into this or next sprint.

**Comment by kristinashu** [comment]
Thank you so much for opening this! If we can, it'd be good to get a head start on it this this sprint.

**Comment by kristinashu** [comment]
[Started a wip doc here.](https://docs.google.com/document/d/1UVe1iI40K9jHbCb6JdiLx94Gjn7ow5AxiGlkWatSAYc/edit#)

**Comment by taisdesouzalessa** [comment]
Thanks for the doc, Kristina! Love how you were thinking in terms of storylines. Added an extra storyline and my suggestion for next step is to open up to the team to choose one of the paths so we can refine. What do you think?

**Comment by taisdesouzalessa** [comment]
As discussed we're going with Storyline 1. **Next step:** Taís to add some refinement to the presentation before opening up to broader team.

**Comment by taisdesouzalessa** [comment]
Developed [storyline here](https://docs.google.com/document/d/1UVe1iI40K9jHbCb6JdiLx94Gjn7ow5AxiGlkWatSAYc/edit?usp=sharing).

@kristinashu I opened a new ticket to track the 2nd stage of this work, which is to get team feedback and create the slides. [Work being tracked here](https://github.com/MozillaFoundation/Design/issues/773). Closing this ticket.
