### ISSUE TITLE
[Email templates] Audit & benchmarks

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#763]
Part I of [Epic] Email design templates #762

- [x] Create a Google slide deck to compile all background and process work, it should includ

- Audit of our current emails to get a sense of our content and needs. E.g. Double opt in after first signing up, welcome email, News Beat, MozFest, Petition, IHR...
- Benchmarks / landscape analysis of good email designs and best practices. E.g. screenshots from nice email examples, articles about best practices, mofo’s previous attempts at re-design, Firefox and moco emails…

**Comment by nancyt1** [comment]
Started the [slide deck](https://docs.google.com/presentation/d/1wlaI9cUZSAv4yTEiD0AL4i3VpoODqGZ5ZLfuxbLFGJA/edit#slide=id.gbf9a6dd3d6_0_863), compiled all the current emails we send, and started benchmarking.

**Comment by kristinashu** [comment]
This is great Nancy! GIFs FTW! 

One additional thought I had was to find some benchmarks or best practices related to fundraising/non-profits as well as advocacy campaigns.

**Comment by nancyt1** [comment]
Wrapped up [audit and benchmarks](https://docs.google.com/presentation/d/1wlaI9cUZSAv4yTEiD0AL4i3VpoODqGZ5ZLfuxbLFGJA/edit#slide=id.gbf9a6dd3d6_0_863), now getting feedback.
