### ISSUE TITLE
[Email templates] Requirements 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#764]
Part II of [Epic] Email design templates #762 

Blocked by - [Email templates] Audit & benchmarks #763

- [x] Add to Google slides or create a new Google doc and write out requirements for email templates. Possible content to include
  - List of key stakeholders E.g. Xavier, Marc, Kaili, Kristina G…
  - Requirements E.g.
   Must include Mozilla logo
   Fonts, colours, and buttons align with MoFo branding
   Must be responsive
   Must be able to localise for different languages
   Multiple templates options depending on the content
   White background (recommendation) 
   Black footer (recommendation)
  Footer content e.g. links to Instagram...
  ….

- [ ] Get feedback on proposed requirements E.g. email team, design team, and key stakeholders

**Comment by nancyt1** [comment]
Started compiling requirements [here](https://docs.google.com/presentation/d/1wlaI9cUZSAv4yTEiD0AL4i3VpoODqGZ5ZLfuxbLFGJA/edit#slide=id.gc03aa2aaad_0_207)

**Comment by nancyt1** [comment]
Finished the requirements [slide](https://docs.google.com/presentation/d/1wlaI9cUZSAv4yTEiD0AL4i3VpoODqGZ5ZLfuxbLFGJA/edit#slide=id.gc03aa2aaad_0_207). 
Potentially documenting this somewhere else like /docs as well .
