### ISSUE TITLE
Figma library outline + organization plan

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#765]
Follow up to figma migration plan https://github.com/MozillaFoundation/Design/issues/723

Create a document that captures a Figma library outline and organization plan. This will help describe and plan how we structure and organize assets we use for our web properties in Figma. 

Things to consider:
- inventory audit of current state of design elements and tokens (visual design and in code)
- structure with atomic design principles, shareability and development coordination in mind
- file best practices and maintenance 
- coordinate with devs on design system

**Comment by kristinashu** [comment]
Sabs, once you have the outline we could consider hiring P&G to do the grunt work. I understand that us creating the library and key pages would help us learn the ins/outs of Figma but we an still learn that as we go with 'real' projects.

**Comment by kristinashu** [comment]
@sabrinang have you been able to start on this at all? No pressure if you haven't, I just wonder if we should try a new approach?

**Comment by sabrinang** [comment]
I got started on an audit structure but will break this into smaller tickets. I'll also need to touch base with a dev to get a better understanding of how our library is currently reflected in code.

**Comment by sabrinang** [comment]
Chatted with Mavis this afternoon and filed issue to get a list cms page type info from devs to inform templates we want https://github.com/mozilla/foundation.mozilla.org/issues/6549

**Comment by sabrinang** [comment]
This sprint we had a few [design library planning conversations](https://docs.google.com/document/d/1w5svaIGFg5-LshiQw47P0WHvYW51O9pwzfbjg_dbfVE/edit?usp=sharing):
- Apr 14 — discussion of audit stage and call for collab at design/dev sync
- Apr 15 — syncing process and continue design/dev chat with Mavis & Ben 
- Apr 15 — typography topic and relation to design library at design crit arose
- Apr 19 — continued discussion about typography with Nancy, Natalie, Daniel & Kristina
- Apr 20 — sync with devs before Mavis mat leave and process collab with Daniel chat with Mavis & Daniel
- Apr 21 — context discussion and reference file to protocol design library with Ryan (MoCo) & Kristina

I got the [audit spreadsheet](https://docs.google.com/spreadsheets/d/1-5kdUg0RExSj_jU6iQqeVg22oGTjRSY3AZZ-U8UcnTM/edit?usp=sharing) set up and will continue getting into doing inventory itself (coordinating with Daniel) next sprint. I can file this as an issue as it is the initial step in the process _(from [figma migration ideas doc](https://docs.google.com/document/d/1IkzUlr1l97NEte8MtW7bPNhlANib4sQUiMZP7eeIe54/edit?usp=sharing))._

**Comment by sabrinang** [comment]
Created a brief and roadmap ticket #765

Token naming and audit spreadsheet here: https://docs.google.com/spreadsheets/d/1-5kdUg0RExSj_jU6iQqeVg22oGTjRSY3AZZ-U8UcnTM/edit#gid=101195698
