### ISSUE TITLE
Resize graphics for Net Neutrality

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#767]
via Kaili in [Airtable](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recOnO0yqUC1oHBj2?blocks=hide)

Re-size [this older graphic](https://drive.google.com/drive/u/0/folders/15nUpqy_ufS10-AKJX-ElmzbwYAiEgKE3) to different sizes.

**Comment by natalieworth** [comment]
Resized and [sent these](https://drive.google.com/open?id=10toIbBX7VXFgiNzYcoHfAGxY-BzuIDSy&authuser=natalie%40mozillafoundation.org&usp=drive_fs) to Kaili.

[Working file is in here.](https://drive.google.com/open?id=10ZEX8g-fCNKlg0BPixLsI-FIKdmYMKE3&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
