### ISSUE TITLE
[Staff Call Presentation] Slides

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#768]
Based on the content outline in #761 - design slides for the presentation.

Natalie will lead this but with content input from everyone.

**Comment by kristinashu** [comment]
Rough presentation outline is [here](https://docs.google.com/document/d/1UVe1iI40K9jHbCb6JdiLx94Gjn7ow5AxiGlkWatSAYc/edit?ts=602704e7#) and we're gathering feedback on it now.

**Comment by natalieworth** [comment]
@kristinashu is it too early to start on slides?

**Comment by kristinashu** [comment]
I don't think it's too early! But please adapt the content as you see fit!

**Comment by natalieworth** [comment]
I got a rough outline of [the slides here](https://docs.google.com/presentation/d/1mQkhE4Tv68pm_rZmKHGZq5C0CISgnsMy174Fbd-UmkU/edit?usp=sharing). I'm thinking we could each add in the information/ images for our areas once we've each written the content?

**Comment by kristinashu** [comment]
These are awesome Nat! I think this ticket is good to close and then refinement of the slides can happen in https://github.com/MozillaFoundation/Design/issues/769

**Comment by natalieworth** [comment]
Okie sweet :D
