### ISSUE TITLE
Design the list of Mofo Vocabulary to help onboarding

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#77]
Mentor: @LauraReynal

With Zannah's help and many other people I pulled together a list of Mozilla-specific vocabulary words. https://etherpad.mozilla.org/glossary-of-mysterious-moz-terms

It'd be awesome to see this list+definitions designed in a fun, engaging, colorful way. Initially we might want to consider some room for growth / adjustment, but I don't see this list changing much over the long term, once the dust settles. Potentially it's something moco could use or add to as well? Might be cool if it lived online!

Anyone up for taking a stab at this? @kristinashu @sabrinang @vazquez @flukeout @lovegushwa

**Comment by cassiemc** [comment]
WOO! glad you are up for this @kristinashu. One thing I should do on this and all the other ```good-first-bugs``` is to add a mentor – kinda standard in open source to assign a person to whom the assignee can run anything by, ask questions, get set-up, etc. Wondering if @LauraReynal is up for taking on that mentor role, since you guys are d-buds now???

**Comment by LauraReynal** [comment]
yes definitely @kristinashu and I have our first d-buds next week

**Comment by kristinashu** [comment]
Excellent, thank you!

**Comment by kristinashu** [comment]
I'm thinking of creating this in Thimble. Each term could have a different background colour, an icon and the text description. Each term would stack on top of each other to create a simple one page site.

I will mock up a couple example terms this heartbeat then hopefully try building them out in Thimble next heartbeat.

**Comment by cassiemc** [comment]
sounds excellent @kristinashu, excited to see it!

**Comment by kristinashu** [comment]
Here's where I'm at with the comp https://redpen.io/p/ua07f141d44ded7cec

I decided to scrap the icon idea since there are so many terms. One page was getting pretty long so I've split it up into sections. The menu would be sticky so users can click through to a different section at any time.

I also might play off the dictionary idea and add whether it's a noun, verb, adjective... and the phonetic pronunciation but I'm not sure it will work for every term.

**Comment by cassiemc** [comment]
This is awesome! I'll comment on the redpen on Monday, so good to see it coming along @kristinashu  :+1:

**Comment by cassiemc** [comment]
@kristinashu left a few comments, but my main thing on the design here is that I'd think a much less vertical layout would work better here so that it's easier to scan. I like the colorful, energetic quality and your idea about riffing off a dictionary text style, would just want to make it slightly more usable.

**Comment by kristinashu** [comment]
Will work on shortening the vertical length (maybe with a side bar or accordions) next heartbeat.

**Comment by cassiemc** [comment]
@kristinashu if you need to break this ticket into smaller ones so we can inch it forward each heartbeat, please do (it's generally better to close small issues than roll over large ones each heartbeat).

**Comment by cassiemc** [comment]
@kristinashu maybe for time's sake this is better designed as an image? I'd love to see @flukeout or @vazquez or anyone else who wants to practice their frontend skillz step in to collaborate with you, but not sure that's possible given time constraints.

Will move to the next milestone 'til we figure out how we can close this.

**Comment by cassiemc** [comment]
Moving this to the backlog.

**Comment by cassiemc** [comment]
Moving OUT of backlog – turns out that milestone isn't helpful! This is something @mandyrawls and Michael Aukland had brainstormed in thinking about how HR docs could be streamlined and beautified, so maybe worth reaching out to them if we ever pick this up again.
