### ISSUE TITLE
[Staff Call Presentation] Team feedback and Design Work

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#773]
**Background:**
Now that we have the [refined version ](https://docs.google.com/document/d/1UVe1iI40K9jHbCb6JdiLx94Gjn7ow5AxiGlkWatSAYc/edit?usp=sharing)of our Staff Call presentation is time to open it to team feedback + start preparing the slides.

**Deadline:** MoFo monthly call is on Feb 25th so it has to be ready a couple of days before that.

**To do:**
- [ ] show to team for feedback
- [ ] teammates to develop their part of the presentation
- [ ] define who will be the main speaker (highlighted in pink)
- [ ] Design the slides. **Lead:** Natalie

@kristinashu adding you here to triage that. I assigned everybody.

**Comment by jamilasnell** [comment]
For meeting and practice

**Comment by kristinashu** [comment]
Sorry, I change my mind.... let's just use [Staff Call Presentation] Prep #769 and [Staff Call Presentation] Slides #768
