### ISSUE TITLE
[Publications] Update How-To Page

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#774]
After more testing and feedback, update the https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/ page.

- Link to publication sample demo https://foundation.mozilla.org/en/docs/how-do-i-wagtail/grimms-fairy-tales-demo/
- Address collection of QA feedback from Nancy's doc: https://docs.google.com/document/d/136l3IIV2HTdG3cJMxtAZLgRRA4lEdrpoe5mUbdIhT_Q/edit?usp=sharing

**Comment by sabrinang** [comment]
I've updated publication how-to page contents, see draft here: https://foundation.mozilla.org/cms/pages/1436/edit/preview/
- publication demo has been linked (from top and line at bottom)
- 'get started' info moved towards top framing two page types
- table of contents, summary has updated images and explained more
- added images for 2x image, call out, table and footnotes all separately with more descriptive text
- image text mini for additional help section

I've addressed points in Nancy's QA doc, but some points made are broader wagtail points (such as image handling, collections, tagging, alt text practices; publish/private/draft view modes etc.) that I didn't address as it felt more broad for scope of publications.

**Comment by sabrinang** [comment]
@kristinashu updated draft https://foundation.mozilla.org/cms/pages/1436/edit/preview/ for review? 
I can update if you have any feedback and can publish updated version if things look good.

**Comment by kristinashu** [comment]
This looks good Sabs! It's nice and concise. I also like the tips section!

**Comment by sabrinang** [comment]
Thank you! Now published live: https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/
