### ISSUE TITLE
Export gifs for Twitter

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#776]
Placeholder ticket to make giphy stickers accessible on Twitter.

**Comment by kristinashu** [comment]
This might be the same as this https://github.com/MozillaFoundation/Design/issues/784

**Comment by natalieworth** [comment]
@kristinashu Saweeet! Yes! @nancyt1 's  got it <3 Ty Nancy!

**Comment by natalieworth** [comment]
@kristinashu Saweeet! Yes! @nancyt1 's  got it <3 Ty Nancy!
