### ISSUE TITLE
Graphics for platform policy tracker blog posts

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#777]
Based on Platform policy tracker microsite https://github.com/mozilla/foundation.mozilla.org/issues/6225

### Todo
- [x] Create three related but different thumbnail graphics for the blog posts

### Background
- Stakeholders: Jon & Kaili
- Deadline: aiming for March 3
- [Copy doc for blog posts](https://docs.google.com/document/d/11WwMiBNygUOboxYpbXRA0GBV6nk8cTFt574x1ZLDcBg/edit)
- Thumbnails will appear on this hub https://foundation.mozilla.org/en/campaigns/election-integrity-and-platform-accountability-v2/

### Image ideas from Kaili
- Blog 1: A mini version of the timeline
- Blog 2: Something similar to the images from our Twitter & Facebook trend-type recommendation campaign is the fall, but with less red and blue (you can see those thumbnails at the bottom of the page here): https://foundation.mozilla.org/en/blog/mozilla-urges-facebook-and-twitter-halt-dangerous-recommendations/
- Blog 3: a take on this theme with TikTok added: https://foundation.mozilla.org/en/campaigns/eu-misinformation/ (this could also be good for the headline banner.

### Related graphics
- Kaili likes this misinfo one for the banner hub (see below)
- Hub will also link to the blog post that is US Elections Related (see below)

![image](https://user-images.githubusercontent.com/1068783/109540475-59218d00-7a77-11eb-8b49-fa4b6e03085c.png)

<img width="314" alt="image" src="https://user-images.githubusercontent.com/1068783/109540717-b61d4300-7a77-11eb-8974-b4b06af3051b.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1068783/109540755-c2a19b80-7a77-11eb-8fe5-48d715344701.png">

**Comment by natalieworth** [comment]
[Started on these](https://redpen.io/p/un55395d78e2a3e905) and sent to Kaili for first round of review

**Comment by kristinashu** [comment]
These look very slick! Perfect tone for the content. 

If Kaili is happy with the general direction then we'll also need a banner for the top of the page (to replace the beige one, so it matches better).

**Comment by natalieworth** [comment]
[Redpen designs are in here](https://redpen.io/pde281b928c531334e)

[Thumbnail/ Blog images are in here](https://drive.google.com/open?id=13TnRRVTjiWQzxY-Q5Ied6YFeh6yOf_YV&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

[Banners are in here](https://drive.google.com/open?id=13WXpS3jTq6uM3buY_3tyZHSwcWuVB6A_&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

[Working files are in here](https://drive.google.com/open?id=13YkYKFmLaiFdKewv5enwUJTS_ozKxh5w&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

I've sent these to Kaili to add to the site.

**Comment by natalieworth** [comment]
Sorry, last thing is Jon hasn't seen the banner and may have some changes, so almost done!

**Comment by kristinashu** [comment]
Awesome Nat! Sorry, we will also need the share graphic for the hub - to match the new banner.

**Comment by natalieworth** [comment]
No worries :), I've added [a social OG image into the exports here](https://drive.google.com/open?id=13Z5mTxY-rGKgGwIIAWefWQLgWHetcGGJ&authuser=natalie%40mozillafoundation.org&usp=drive_fs).

**Comment by kristinashu** [comment]
Lots of "I love it" and "fantastic" being thrown around about these! This should be good to close.
