### ISSUE TITLE
[Email templates] Initial template design & exploration

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#780]
Start exploring some initial design directions based on the information gathered in [the deck](https://docs.google.com/presentation/d/1wlaI9cUZSAv4yTEiD0AL4i3VpoODqGZ5ZLfuxbLFGJA/edit#slide=id.gbf9a6dd3d6_0_863).

Goal for this ticket to get share some initial designs with the design team for feedback.

Refining and finalizing the designs to share with the email team and stakeholders will be done next sprint.

**Comment by nancyt1** [comment]
Started exploring some designs in [Figma](https://www.figma.com/file/XFShf6u1arpZsWprZjomHx/Email-Templates?node-id=0%3A1)

**Comment by kristinashu** [comment]
Looking good! You could also share these in slack tomorrow with the other designers!

**Comment by kristinashu** [comment]
I've opened a ticket for next sprint to continue with the designs https://github.com/MozillaFoundation/Design/issues/790. Feel free to close this one when you feel like it.
