### ISSUE TITLE
[Publications] Case Study (Evangelize Impact Beacon)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#786]
_Placeholder ticket_

Publications could be a potential case study candidate for our evangelism impact beacon videos. It may be a good way to reflect and recap this project, metric, analytics etc.

**Comment by kristinashu** [comment]
@sabrinang @taisdesouzalessa does this https://github.com/mozilla/foundation.mozilla.org/issues/6276 represent this work?

**Comment by sabrinang** [comment]
@kristinashu No, I put this an a placeholder for the next video we can make that could be about publications case study. So it is different from the IA refresh case study. I can move from this sprint as we have the other to work on.

**Comment by kristinashu** [comment]
Ah right, thank you!

**Comment by kristinashu** [comment]
This can happen as part of https://github.com/mozilla/foundation.mozilla.org/issues/8505
