### ISSUE TITLE
Public by Default Narrative Illustrations

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#788]
### Intro

Kaili has been working on a long-form piece of content written by Sara Benincasa. This is a good opportunity to test out our longer-form narrative content plans accompanied by narrative illustrations.

References
[Huffington Post's Highline](https://www.huffpost.com/highline)
[The Boat](https://www.sbs.com.au/theboat/)

### Links
[Draft gdoc of content is in here](https://docs.google.com/document/d/1tehcMf1uiMNtI9a_QA8eBrDZSU2HqM_NZpwdtnD0KuM/edit)

**Comment by natalieworth** [comment]
We talked in Slack, but I'll note it here that my blue-sky-thinking would be to have full image widths on certain blog pages—which would require dev support. For now though, I'll just focus on the illustrations and then I can also mockup some different versions of how this could progress in the future with dev help :)

**Comment by natalieworth** [comment]
[Also noting Wagtail draft page is here](https://foundation.mozilla.org/cms/pages/1947/edit/)

**Comment by kristinashu** [comment]
@natalieworth how is this going? When you've finished with it could you please give Kaili an FYI on how long you spent on it? I'd like to start educating stakeholders on how long things take. Seems like there impression is that this type of stuff takes like 1 hour when it certainly doesn't.

**Comment by natalieworth** [comment]
Illustrations are good to go and just adding to the blog!
https://redpen.io/p/tb6ab73751e050885d

**Comment by natalieworth** [comment]
Showed in crit and Kaili was happy with these/ no changes needed. These are finished and I've added them to the blog. Final exports and working files are in here:
 https://drive.google.com/open?id=146-1yC1xww4W9RZRAurUJBbyZ7CkG9D-&authuser=natalie%40mozillafoundation.org&usp=drive_fs
