### ISSUE TITLE
[User Testing] Usertesting.com

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#789]
### Intro

Since we want to have usertesting.com, I sent an email to Raja with some follow up questions:
• Do you know if the cost includes the recruiting as well? We want to use their panel instead of recruiting ourselves.
• Also, do you know how many studies per year we can do with this budget?

### To do
- [ ] wait for Raja's reply
- [ ] organize the contract/next steps: @kristinashu would you be able to take a lead on this? I have no idea on how I can help, please let me  know.
- [ ] Let UserZoom know we won't be using their platform atm

**Comment by kristinashu** [comment]
I don't think we would have a formal contract for this. I believe usertesting.com would bill moco and then moco can bill us through our cost center. Ethan is aware of the possible bill coming in. I don't think there is anything else for us to do as far as billing goes. If there is, I'm sure someone at moco will let us know but I don't think we need to chaise down anyone to pay them.

Perhaps you can ping Raja in slack to ask him about recruitment and number of tests? And let him know that we think usertesting with moco will be better for us than userzoom so we would ideally like to go with that.

**Comment by taisdesouzalessa** [comment]
Pinged Raja, will post answer here once I have.

**Comment by kristinashu** [comment]
Sounds good, thank you!

**Comment by taisdesouzalessa** [comment]
I'll send you the answer via email, @kristinashu! Price is actually lower and  the number of studies are 10-12 studies (8 participants each study). I guess this is good to close \0/.

**Comment by kristinashu** [comment]
Sweet!
