### ISSUE TITLE
Add the design brief link to Build/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#79]
We want to add the link to the final design brief google doc template to http://build.webmaker.org/design
(should get sorted this heartbeat in issue #20)

@vazquez can you help us out with this next heartbeat?

**Comment by vazquez** [comment]
Of course :)

**Comment by cassiemc** [comment]
Final document is here: https://docs.google.com/a/mozilla.com/document/d/1H4rDTT7zdvOFhGlgMDIuRLlTRlAxMsU_-mUehv_iEZU/edit?usp=sharing

Shortlink: http://bit.ly/mozdesignbrief
