### ISSUE TITLE
[Email templates] Template designs

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#790]
Continuation of [Email templates] Initial template design & exploration #780

Iterate designs based on feedback from the design team, narrow down the directions, create mobile comps for selected versions. 

Prep to share with email and stakeholders.

**Comment by nancyt1** [comment]
Prepped for feedback in [Figma](https://www.figma.com/proto/XFShf6u1arpZsWprZjomHx/Email-Templates?node-id=565%3A7204&viewport=1052%2C235%2C0.10208901762962341&scaling=scale-down-width&page-id=565%3A7149)
