### ISSUE TITLE
[Brand] Create Typeform Templates

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#798]
We have a typeform account and component in wagtail where staff can embed these forms on our pages.

- [x] Create and add branded typeform templates in our typeform gallery for staff to access and use.
- [x] Document on /brand these exist (example: [/brand/templates/](https://foundation.mozilla.org/en/docs/brand/templates/))

**Comment by sabrinang** [comment]
Note: ask Kaili for review as well

**Comment by kristinashu** [comment]
The patterns look lovely and thank you for added a section to /brand. I think they might be offset by a ~1 pixel tho. I've attached a close up screen cap that shows a thin while line on the left side.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/1068783/117918212-7d7fbe00-b29f-11eb-83b5-03a39e8cfd1c.png">

I've asked about the login in [Airtable](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/rec4Cau8wWLO0PuVB?blocks=hide). If Anil/Ben don't reply tomorrow morning then I'll start a thread in Slack. I've also requested 1Password account so I can sign in and check it out.

**Comment by sabrinang** [comment]
I've updated the graphics so the line should not appear anymore

**Comment by kristinashu** [comment]
I've logged into Typeform and can see the templates! I think all that is left to close this ticket is to let Audrey, Kaili, and Anil know that you've add some designs.

**Comment by sabrinang** [comment]
Awesome! I @mentioned each of them in mofo-wagtail slack channel.
