### ISSUE TITLE
[Email templates] Get feedback on the designs

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#799]
Follow up from - [Email templates] Template designs #790

Share the designs with the design team, email team, and key stakeholders for feedback.

Gather all the feedback and implement changes.

**Comment by kristinashu** [comment]
@nancyt1 how's this going? I believe you've gathered all the feedback but have you updated the designs based on that feedback yet?

**Comment by nancyt1** [comment]
Updated designs based on feedback, in the [ready for dev page](https://www.figma.com/file/XFShf6u1arpZsWprZjomHx/Email-Templates?node-id=628%3A0)
