### ISSUE TITLE
Write chapter on Process

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#8]
Process
* Design review
* Hand-off
* File sharing & organization
* Prototypes
* User testing
* Quality assurance
* Data and design

These are a work-in-progress as we test optimal solutions. Some ideas floated over here: MozillaFoundation/plan#108

**Comment by xmatthewx** [comment]
Moved my text from pull request to the wiki. https://github.com/MozillaFoundation/Design/wiki/Process. There and ready for anyone to edit and improve.
