### ISSUE TITLE
[Email templates] user testing

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#800]
Based on design in - [Email templates] Template designs #790

Define the goals of the test, hypotheses, and write the test for usertesting.com to gather qualitative data about the email refresh.

**Comment by taisdesouzalessa** [comment]
Unassigning myself. I will do a brown bag on user testing.

**Comment by kristinashu** [comment]
Moving this to next sprint since the brownbag isn't happening until the end of this sprint.

**Comment by nancyt1** [comment]
Started writing up the user testing plan in a [google doc](https://docs.google.com/document/d/1D0qsGrYZJaJK9PREK4J9Fj4pTL4xFadVUTRz9PTic0Q/edit?usp=sharing)

**Comment by nancyt1** [comment]
Interviewed Jamila today for final feedback and it's ready to run for real.
