### ISSUE TITLE
Design recap Q1 2021

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#801]
Check out all our recap decks [here](https://drive.google.com/drive/folders/1Qunbhvtqdd_ytEfRCKOR5h3P0-EYh36Y?usp=sharing).

I've started one for [2021 here](https://docs.google.com/presentation/d/1vyH9vKs7uqB83MUFmZ5Yk7g-HDZ-tMJuAqTzy2-c5aw/edit?usp=sharing). I've added two new templates specific to the recap deck to try and streamline our image sizes. Please add others that you can think of.

As a way to bring other staff into this, it is called "Design Collaboration" so that it is more inclusive and meaningful to other teams as well. I'd love to add in a layer of analytics to encourage other staff to reflect back on their work and see how impactful it was in terms of "engagement" (i.e. reaching a lot of people). 

### Goals & Audience
- Celebrate and remissness about all the work we do
- Show both the depth and breadth of our work 
  - Depth: Highlight a few key projects to show our impact
  - Breath: all the things, show how we touch on a lot of different types of work all across to org
- Share with Ashley, Anil, and the rest of the org to show off both the importance of our contributions but also how much we have achieved
- Use it to guide planning - what types of work do we do, what did we enjoy working on the most, where did we have the most impact

### Process
- Everyone add the projects they worked on
- Organize it as you see fit
- Update the slide template - "nothing is precious" :)
- Add relevant data (analytics, quotes, press...)
- Share with others

### Deadline
- End of this sprint

**Comment by taisdesouzalessa** [comment]
Added my Q1 projects there. Unassigning myself.

**Comment by sabrinang** [comment]
I added six slides/projects to the Q1 recap deck, I left the results/impact <tbd> for now but will fill in later on!

**Comment by kristinashu** [comment]
Thank you @taisdesouzalessa @sabrinang for adding in your projects, looks good!

@natalieworth @nancyt1 do you think you'll get to this this sprint or should be carry over to next, I suspect it will carry over!

**Comment by nancyt1** [comment]
Added in my projects!

**Comment by natalieworth** [comment]
Hey @kristinashu my stuff's in there now :) Ty
