### ISSUE TITLE
Test and improve newsletter sign-up text

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#807]
Will has identified and requested that we improve the sign-up text in our newsletter sections to include more specific asks.

The proposed initial copy is  "'get smarter about your online life' -- which a. is a correct description of the expert/informative nature of our mailing stream (PNI, IHR, etc.), and b. promises a benefit to the new subscriber in exchange for letting us into their inboxes."

### Links
[Airtable link is here](https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/recV78f369QS1vLPW?blocks=hide)

**Comment by kristinashu** [comment]
Designer to meet with Anil about this but for now I believe we will do a quick fix of updating the text to what Will has suggested:

> Help shape the future of the web for the public good. 

> Join our Mozilla News email list to get action alerts & internet tips right to your inbox.

Todo
- [ ] Ping Anil for added context
- [ ] Identify all the places on the site where it would need to be updates
- [ ] Have this text translated
- [ ] Mock it up
- [ ] Open a ticket for implementation

**Comment by kristinashu** [comment]
@benhohner did you turn this into a dev ticket?

**Comment by KalobTaulien** [comment]
@kristinashu I opened a ticket for this here: https://github.com/mozilla/foundation.mozilla.org/issues/6831 — I'm not going to close _this_ ticket though in case you still need it.

**Comment by kristinashu** [comment]
Thank you!
