### ISSUE TITLE
[D&D graphics] Vaccine passport 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#808]
[blocked by content]

**Comment by jamilasnell** [comment]
Here is the filled out doc: 
https://docs.google.com/document/d/19hXffVP59Dj-3Hhee-J4ivs05apUHt-EZs4Wh08Mvng/edit

**Comment by kristinashu** [comment]
@jamilasnell assigning this to you. Please add the headshots once you have all of them.

**Comment by kristinashu** [comment]
I went on youtube this morning and saw this. So I guess this it done?

![Screen Shot 2021-04-01 at 7 14 08 AM](https://user-images.githubusercontent.com/1068783/113308737-50f97f00-92bb-11eb-84c7-8e9b4572ac1a.jpg)

**Comment by jamilasnell** [comment]
Jon says that this image was made without their knowledge and they still want the graphic to be worked on. The profile pics are now in the graphics request form so we can start working on this request now!

**Comment by natalieworth** [comment]
I based it on the non-Mozfest time D&D visuals: https://drive.google.com/open?id=14Xy3FcpnnziFT2YiVnpFFzS3J3DZhhIu&authuser=natalie%40mozillafoundation.org&usp=drive_fs

**Comment by natalieworth** [comment]
I'll Slack to Jon and Audrey and the [Redpen is here
](https://redpen.io/p/xzf5c3dd913300f7ca)

**Comment by kristinashu** [comment]
So much better :)
