### ISSUE TITLE
Interview YI Intern candidates

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#81]
We have received some excellent resumes from intern candidates in Vancouver. 

Looking for interview help. Who's game? @lovegushwa @kristinashu @flukeout @sabrinang @vazquez 

(note: you'll have to read the IHO (Intern Host Organizations) handbook in advance of the interview: http://cl.ly/d4WZ

**Comment by flukeout** [comment]
Sure, I'm game!

**Comment by cassiemc** [comment]
Thanks @flukeout! Our first interview is on Monday by Skype. I'll keep you posted.

**Comment by cassiemc** [comment]
First interview down. Next interview Thursday.

**Comment by cassiemc** [comment]
Done! Natalie will be starting Sept 28 :)
