### ISSUE TITLE
Create Graphs for Net Neutrality

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#810]
[Epic is here](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/802)

We'll be creating graphics and the style for the Net Neutrality campaign.

cc @nancyt1

**Comment by kristinashu** [comment]
Graphs are here https://redpen.io/p/vmd0f747f9341e96e0 and they're rad! Is there anything left to do for this?

**Comment by nancyt1** [comment]
Graphs are export[ here](https://drive.google.com/drive/u/0/folders/1XUUE-AuX-a_1CIORSu8Iic8h5EtET-uH)
