### ISSUE TITLE
Net Neutrality: Create Instagram graphics for timeline

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#811]
[Epic is here](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/802)
Create Instagram graphics for the timeline. More information will be updated when we get content.

**Comment by nancyt1** [comment]
Waiting on content from Audrey

**Comment by nancyt1** [comment]
Copy was [added](https://docs.google.com/document/d/1uDqP0iQLuOnc3w594oaU1oBFTeqh_r8-NkuxYjQzeA8/edit)

**Comment by nancyt1** [comment]
Uploaded to[ redpen](https://redpen.io/p/vmd0f747f9341e96e0) for review.

**Comment by nancyt1** [comment]
Exported instagram graphics to the [drive](https://drive.google.com/drive/u/0/folders/1WkAaqz3XSL1JE4BewpY9bn6JMa9rBb9U)
