### ISSUE TITLE
Net Neutrality: Create graphics for MVP Wagtail page

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#812]
We will need 16:9 or 16:6 graphics for the wagtail page on Net Neutrality. They should use the same style and direction of the graphs and campaign.

cc @nancyt1

**Comment by kristinashu** [comment]
Draft page is here https://foundation.mozilla.org/cms/pages/2015/edit/ and redpen is here https://redpen.io/p/vmd0f747f9341e96e0. Is there anything left to do for this?

**Comment by nancyt1** [comment]
Files exported to [drive](https://drive.google.com/drive/u/0/folders/1XUTZYacq5O9EEF29AbzqJpF8gr1M8Ch5) and mocked up in [wagtail](https://foundation.mozilla.org/en/campaigns/net-neutrality-timeline/); pw:net
