### ISSUE TITLE
[Due Wednesday 28th] Apple opt-out localised graphics

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#826]
Via Kaili but also please consult Audrey for social.

Partners have created the EN graphics here https://drive.google.com/drive/folders/1t9EOu3fiaYIhFU_sYlKEA83jaivSmkBN

We will be emailing in EN on Apr 28 and should update the colors and fonts to match our brand. 

### Deadline Tue Apr 27
- [x] Start a thread with Kaili and Audrey to say that you're working on it now
- [x] Update selected graphics with our fonts and colours
- [x] Update older blog posts with the new graphics

### Deadline Wed Apr 28
Graphic 1 : "Mozilla TW.png" to be used on ShareProgress for Twitter & Facebook
- [x] DE
- [x] ES
- [x] FR
- [x] PT 

### Deadline Fri Apr 30

Will also need to localize these graphics
Graphic 2: "Mozilla square.png" (which is similar to the previous one, just with a different layout) to be used in the email.
- [x] DE
- [x] ES
- [x] FR
- [x] PT 

Graphic 3: "Email button.png" to be used in the wagtail page.
- [x] DE
- [x] ES
- [x] FR
- [x] PT 

@TheoChevalier should have translations ready on Wednesday.

**Comment by jamilasnell** [comment]
Also need to update past blog with the correct colors/fonts to match brand

**Comment by TheoChevalier** [comment]
@kristinashu @nancyt1 

Hey folks, I’ve got translations ready slightly early, here they are! https://docs.google.com/document/d/1ZJ5J2hBRPpBbQlIx-8mAw-Ak7MBMeT_x8im0IpWJorE/edit?usp=sharing

I’ve put English at the top so that it’s easier to see which translation matches with which English string (I’ve used the same format for all languages). Since graphics 1 & 2 are sharing the exact same copy, I’ve grouped them

**Comment by kristinashu** [comment]
Amazing, thank you Theo! And thank you Jamila for update the title - I like it!

**Comment by nancyt1** [comment]
Exports of the EN email header and some of the localized graphics are in the [drive](https://drive.google.com/drive/folders/1mowh0suIkhkT_yFdubftZKfT82QoF2Am).

**Comment by TheoChevalier** [comment]
Thanks @nancyt1!
Just one small thing to fix in French for graphic 1 & 2, could you move « to the next line please? Like this:

Cliquez sur
« Demander à l’app

The TL;DR of the French typographic rule is we need to keep `« + space + word` and `word + space + »` on the same line (the space is a non-breaking space)

**Comment by nancyt1** [comment]
Ah thank you @TheoChevalier! I've updated it and uploaded to the [drive](https://drive.google.com/drive/folders/1mowh0suIkhkT_yFdubftZKfT82QoF2Am).

**Comment by TheoChevalier** [comment]
Thank you! Looking great :)

**Comment by nancyt1** [comment]
Old blogs seem to be updated and all assets uploaded to drive.
