### ISSUE TITLE
[Email Templates] QA & Dev support

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#827]
[Feedback Doc](https://docs.google.com/document/d/1p0VCAB9xpQ5bOGcT-usTJiloI_2IgKFiD-6cmLmWRec/edit#heading=h.kcl1j3nyej8z)

- [x] Review email tests from Brandon (incl. mobile and other browsers)
- [x] Make sure everything matches design and design in figma gets updated
- [x] Give feedback

**Comment by nancyt1** [comment]
Will sent over [renders](https://everest.validity.com/design/share/26ec8465657eef/) of the welcome email he finished and I gave some notes, but everything looked good. Zilla and Nunito won't show up for most non-Mac users though.

**Comment by kristinashu** [comment]
😊

**Comment by nancyt1** [comment]
Collecting feedback in to this [doc](https://docs.google.com/document/d/1p0VCAB9xpQ5bOGcT-usTJiloI_2IgKFiD-6cmLmWRec/edit?usp=sharing)

**Comment by nancyt1** [comment]
Gave my feedback to Brandon in the doc and he's implemented everything and says he will copy the code into the other templates. He said he'll have me review some of the other templates when he's done and will also send to Kristina and Anil to review but we can launch the new designs soon hopefully!

**Comment by nancyt1** [comment]
Will continue QA in ticket #1094
