### ISSUE TITLE
Storytelling Wagtail Compontent: Embedded Audio

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#830]
### Intro
Finalize the design and look into functionality/ embedded design options for an audio component on the Wagtail blog page.

### Links
[Redpen is here](https://redpen.io/p/wu5fe36cd1366a0cad)

**Comment by kristinashu** [comment]
Note how IHR has just done this here https://2020.internethealthreport.org/sounds/

**Comment by kristinashu** [comment]
Please link to the implementation ticket here once you've opened it!

**Comment by natalieworth** [comment]
![Screen Shot 2021-05-10 at 7.36.35 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/cc98140f-0e40-48ef-810f-6680922a3a13)

The above design is our 'ideal' design if we are able to host audio ourselves on Wagtail. But, if that is out of scope, using Sound Cloud embedding is also an option. I tried to see how 'customizable' it was—but I wasn't able to get anything to change in my hacky CSS.
