### ISSUE TITLE
RegretsReporter shareout: Finalize copy

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#836]
###Intro
Need to finalize the copy of the RegretsReporter landing page with Audrey and Brandi.

[Working document is here.](https://docs.google.com/document/d/1pn8CUywtNo2J3rIlgfIKqCyJor1UiiLGqziHzVi_muI/edit?usp=sharing)

**Carrying this ticket (with updates) into this sprint. Previous planning [ticket for this is here](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/6539) #6539 

####Project from the AI & Content working group:

Create an interactive landing page to share out this content https://docs.google.com/presentation/d/10ZNsVF6hOAGPy4i6Cgx9WiryOiSzX69bUm6MluS740w/edit#slide=id.p

Proposed deadline for project: end of June

### More links
- working group notes https://docs.google.com/document/d/102LP21bcOtiVAIwvbsp2hUl578gdi6ecFpWNfe7TyMg/edit
- Tais' scope notes https://docs.google.com/spreadsheets/d/13TCx3NFTRtKTQ6Nh8_TNitPSoWnDP9MovvEnkW0f3QE/edit?ts=606cd9fc#gid=0
- Project brief https://docs.google.com/document/d/19r7dIkYKe1IRLXV5hH1n0OkSNKkROkcirq2amoQ7-AU/edit

**Comment by natalieworth** [comment]
@kristinashu @jamilasnell I like that this ticket has the links and the next steps in it (content + wireframes). Is it okay if I keep this ticket and carry it over into the new sprint or should I make a new ticket?

**Comment by kristinashu** [comment]
You can carry it over or break it up into smaller tickets.

**Comment by kristinashu** [comment]
Let's close this and pretend it never happened lol. No. I think you've made huge progress on the content by helping to shape the narrative and by pushing back on the copy length and reading level. I don't think there's much more we can do in terms of the copy. THANK YOU BOTH OF YOU!
