### ISSUE TITLE
[Working Group] Strat Comms: Output Deliverables Graphic

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#838]
### Placeholder

Coordinate with Carys to create graphic to describe strat comms outputs/deliverables and where it maps to (this will help track progress)

Related Issue: #805

**Comment by sabrinang** [comment]
Note:
- Carys emailed us 5 days ago she is looking into MoCo agency retainers and that things in flux with MoCo comms and marketing
- Cayrs slacked us today she is working on handoffs and sorting out what it means for the project timeline with 2 key MoCo folks leaving and will try to schedule a call next week or so

**Comment by sabrinang** [comment]
Note: synced with Carys today re:both strat comm tickets and catch up on what is happening with Strat Comms

- There’s lots of changes with MoCo and collaboration was slow moving and tricky to coordinate so there is a potential to pivot to focus on MoFo first
- I asked about how timelines would be impacted and she mentioned text work aim to be ready around August after focus groups are conducted 
- I brought up we should coordinate this with our roadmap where this shows up on our channels specifically evergreen website copy work and where this shows up strengthening our visual brand
- I’ll follow up with Kristina/Jam on what processes are appropriate for next steps and should have a kickoff with Carys re: timeline/scope/brief with Strat Comms plans

**Comment by kristinashu** [comment]
Seems like this project has trickled off. I'm going to close this for now and you can open a new ticket if the work resurfaces.
