### ISSUE TITLE
 [Working Group] Strat Comms: Brand Wishlist

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#839]
### Description 

- Continue the brand wishlist doc (WIP) here: https://docs.google.com/document/d/1b48E8pR74_L5nji9gQ_XphcsIvnEG8DL2BWFfjWpnPw/edit?usp=sharing
- Touchbase with Carys regarding brand wishlist (see when she has availability for 1:1)

Related Issue: #805

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
