### ISSUE TITLE
Replace assets on assets.mozilla.org

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/Design#84]
Old Webmaker assets are on https://assets.mozilla.org/portal/assets/#category/29. Some community members get their assets from there. It should be replaced!

**Comment by cassiemc** [comment]
@vazquez can you help here?

**Comment by vazquez** [comment]
@cassiemc Do you know who handles this in MoCo? I can get in touch with them.

**Comment by cassiemc** [comment]
@sabrinang do you have any contacts off-hand? If not, I can look into it.

**Comment by sabrinang** [comment]
Yeah, I believe it is Ty Flanagan (tflanagan@mozilla.com) who populates the assets portal for the moco creative team.

**Comment by vazquez** [comment]
Update: I've emailed Ty. Waiting to hear back.

**Comment by vazquez** [comment]
I heard back from Ty. I need to email him a ZIP file of the new assets and he will upload them to assets.mozilla.org.
