### ISSUE TITLE
Sticker for supporters 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#841]
Via Jesse in [Airtable](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recXS018ni8sdjEUK?blocks=hide)

> When we send acknowledgment letters to donors it would be nice to include stickers that the donor could use to show their Mozilla pride. In the past, we've only had the generic stickers, but it would be great to have something a little more colorful that says something like "supporter". The goal would be to make the sticker design feel connected to the person's role as a donor. I plan to submit the order via Stickermule and was thinking of a square 3" x3" design with rounded corners, but open to other sizes and design styles.

Proposed deadline is May 21

**Comment by kristinashu** [comment]
@natalieworth did you work on this yesterday?

**Comment by natalieworth** [comment]
Yep! I have some rough options in Redpen here and I've also talked to Jesse.

https://www.pinterest.ca/pin/108016091052059255/

**Comment by kristinashu** [comment]
Looks like that's a link to pinterest. Do you have the redpen link?

**Comment by natalieworth** [comment]
https://redpen.io/p/fu489d6fa0009fb328

**Comment by natalieworth** [comment]
These ones are more reserved/ safe but I talked to Jesse this afternoon and he said that it could be okay to explore something a bit more 'weird'—which is what I was hoping to do for the stickers.

**Comment by kristinashu** [comment]
Looking good! Did you and Jesse decide on a direction? Would be great to close this off today 😭

**Comment by natalieworth** [comment]
[Working files are in here](https://drive.google.com/open?id=16zefUvOzY9okVdWGv6kSVjJDSiJTOnVU&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

[Final file is in here](https://drive.google.com/file/d/170dZ_h8WA12YbJoeQwulxxLUtIoOtMJA/view?usp=sharing)

The team liked and ended up going with the Mozilla supporter direction:

![Screen Shot 2021-06-03 at 4.15.37 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/beb002f6-d515-4def-848e-788b59562b97)
