### ISSUE TITLE
Template graphics for Acting On Shared Purpose template

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#843]
Via Eeva

> We've begun building out the new publication using the lovely new Wagtail template. It will be PW protected as it's intended for Mozillians alone, so we aren't looking to do anything super spicy with it. You can see from the landing page that the hero and boxes are areas where we would love to have some design alignment and, again, this is PW protected so not looking for anything too snazzy, which makes this perfect for some template options, assuming that's an option!

https://foundation.mozilla.org/en/insights/acting-on-shared-purpose/ [viewable to logged in users]

> We are looking for an elegant way of making sure our readers know that this publication is categorized as Mozilla confidential. We are toying with using the headline to communicate this but it doesn't look so great. Maybe this is something we could overlay onto a basic hero image?

Note: I mentioned this is an opportunity for some "template" graphics that would be generic enough for any staff to use for random things.

The look and feel they are going for is "nice and professional."

**Comment by natalieworth** [comment]
I've made a generic banner using the illustration template work. I've shared with Eeva and I also inquired if we could have 'Mozilla Confidential' text and an emoji icon instead of having the confidentiality in the banner.

https://redpen.io/p/ve743f3191b64328b6

**Comment by kristinashu** [comment]
Are you able to wrap this up today?

**Comment by natalieworth** [comment]
hey, yes! I can finish the shared purpose today
