### ISSUE TITLE
Android Campaign - June 9

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#849]
###Links
[Design brief document is here](https://docs.google.com/document/d/1ldSoOgl_-Szo2AnR7IGp0ntQeVwqDtOYdQuau_uaHn8/edit?usp=sharing)

**Comment by natalieworth** [comment]
Meeting with Kaili tomorrow to go over this.

**Comment by natalieworth** [comment]
Met with Kaili and we [filled out the brief here](https://docs.google.com/document/d/1ldSoOgl_-Szo2AnR7IGp0ntQeVwqDtOYdQuau_uaHn8/edit?usp=sharing).

There are still some things that are TBD for it—but Kaili is going to be meeting with Ashley and will provide updates.

cc @jamilasnell @kristinashu

**Comment by kristinashu** [comment]
@natalieworth let's keep this open until it's done. You can put in blocked and in the next sprint.

**Comment by kristinashu** [comment]
I guess this has been unblocked because Jam says that Kaili says this now has a June 9th date https://airtable.com/tblbvJg42knoQuYDw/viwjYLXoMF5pqOnZi/recVIvFColOsWoYZz?blocks=hide

**Comment by kristinashu** [comment]
Going to see if P&G can do this!
