### ISSUE TITLE
[YouTube RegretsReporter shareout] Wireframes for landing page - v1 

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#850]
###Intro
Once the copy is more developed, Natalie and Nancy can begin wireframing the shareout site.

[Working copy document is here.](https://docs.google.com/document/d/1pn8CUywtNo2J3rIlgfIKqCyJor1UiiLGqziHzVi_muI/edit?usp=sharing)

**Carrying this ticket (with updates) into this sprint. Previous planning [ticket for this is here](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/6539) #6539 

####Project from the AI & Content working group:

Create an interactive landing page to share out this content https://docs.google.com/presentation/d/10ZNsVF6hOAGPy4i6Cgx9WiryOiSzX69bUm6MluS740w/edit#slide=id.p

Proposed deadline for project: end of June

### More links
- working group notes https://docs.google.com/document/d/102LP21bcOtiVAIwvbsp2hUl578gdi6ecFpWNfe7TyMg/edit
- Tais' scope notes https://docs.google.com/spreadsheets/d/13TCx3NFTRtKTQ6Nh8_TNitPSoWnDP9MovvEnkW0f3QE/edit?ts=606cd9fc#gid=0
- Project brief https://docs.google.com/document/d/19r7dIkYKe1IRLXV5hH1n0OkSNKkROkcirq2amoQ7-AU/edit

**Comment by natalieworth** [comment]
Nancy has started exploring [a lot of great options in here](https://www.figma.com/file/Mp4TDFJIi02sYvxLDTCknF/YouTubeRegretsReporter-Share-Out)

We met with Brandi and Audrey today. The key takeaways are we need to focus on this being for policymakers and it's okay if it's more text-heavy and explanatory. 

The next steps are:
- talk with Ben and the engineering team about development possibilities
- have a low-fi option that exists on the default publication page and a 'blue-sky' publication option with a landing page and navigation
- propose a 1-page publication option
- how strict is the timeline

**Comment by kristinashu** [comment]
Linking to some of our meeting notes [here](https://docs.google.com/document/d/1SPbtrGhQDs7aSWJt9qx1kqgagGCrouUuDSNUbV2LTrY/edit#). 

The plan right now is for Nancy to continue to explore content layout directions. Sabs to do some rough exploratory sketches today that Nancy can draw inspiration from. 

We'll meet on Tuesday to see how it's going!

**Comment by sabrinang** [comment]
I included a sketch and wireframe in the [figma](https://www.figma.com/file/Mp4TDFJIi02sYvxLDTCknF/YouTubeRegretsReporter-Share-Out?node-id=0%3A1) file you shared earlier today
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/2492510/120054004-45d47e00-bfe2-11eb-82d5-11cf1f3d1cbf.png">


I focused on looking at the structure and sectioning content. I think the main things in the exploration is that:
- **hero narrative area:** this can be more visual and pace out the introductory quote content
- **context informative area:** this is the dense info area so having the stats, visuals and perhaps referencing the browser extension can help break up this area
- **what is a youtube regret area:** I'd section of this area obviously more different than what comes before and after it and it. It mentions the crowdsourced campaign so perhaps it could bring in some visual reference from that. This section doesn't have to be long if we display the examples through scroll animation, carousel etc. 
- **quote block:** this can also be shuffled to following sections if it feels abrupt there (following findings etc.)
- **what we found area:** highlighting that there are four helps gives readers an idea of how much content is to come. You can explore various methods to unpack the four findings (like a ToC, section cards, slideshow, sticky title etc.)
- **recommendations area:** making this a clear takeaway section is good with bold CTA

I didn't get into typography but exploring the treatment and hierarchy will be helpful to emphasize and group similar contents along with sectioning so it can continue to be refined as there are so many awesome ideas in the file already so looking forward to what y'all come up with next. Hope this helps and meet you Tuesday!

**Comment by kristinashu** [comment]
Thanks Sabs! This is super helpful. The page doesn't actually seem that long.

+1 about using typography to create hierarchy, as Nancy has some in some of her mock-ups

The YouTube Regrets area is "optional" so I do think it should be an optional horizontal scroll section

**Comment by kristinashu** [comment]
The general wireframe interaction has been established (horizontal drawers) and the "wireframes" are getting pretty detailed so gonna close this one. Opened a new ticket for "lo-fi comps" here https://github.com/MozillaFoundation/Design/issues/876
