### ISSUE TITLE
[Publications] Design review of TikTok paid political influence publication

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#855]
Related to epic: https://github.com/MozillaFoundation/Design/issues/852

Do a design review of the "TikTok paid political influence research" when the content /graphics is populated in the publications template.

**Comment by natalieworth** [comment]
There's another ticket related to this, so I'm going to close this one and do the design review in the other:
[# 855](https://github.com/MozillaFoundation/Design/issues/855)
