### ISSUE TITLE
[Publications] Onboarding Screenshare Video Walkthrough

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#856]
Related to epic: https://github.com/MozillaFoundation/Design/issues/852

I think having a walkthrough video to supplement staff on publications in addition to https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/ will be useful beyond just this _"TikTok paid political influence research"_ publication. I'm thinking to screen recording and talking over examples could be a beneficial async method for documentation and onboarding.

I can upload the video to google drive and link it in the /how-do-i-wagtail/publications page.

**Comment by sabrinang** [comment]
@kristinashu @natalieworth  Please review this video walk through of the publication pages here in google drive: https://drive.google.com/file/d/1lypG__JsYkyKVmUFAiDkVFzEZHkVXAr1/view?usp=sharing

Natalie please let me know what you think of the content since this is for you and Brandi's initial onboarding.

Once approved, I can link it on https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/ 
Nancy talked about having it hosted on youtube as well and that we can _"unlisted"_ it so it is isn't listed on our channel but still live. This would be a great idea so we could access youtubes chapter features and it is embedded on our site.

**Comment by kristinashu** [comment]
Really informative video Sabs! It's very thorough and I learnt a lot! I am a little worried staff might think the video is long but I think everything in it is needed so you shouldn't cut anything. In retrospect, maybe hosting it on YouTube would be good so that you can add chapters to the video i.e. Images, Tables, Footnotes. You could also share this with Kalob for feedback since he's make a lot of Wagtail videos before! Brandi will also be the perfect tester for this.

**Comment by sabrinang** [comment]
_Note:_ I checked in with Kalob on slack and he had positive feedback and support! I'll keep him in the loop if I make videos like this in the future (no changes recommended)

**Comment by sabrinang** [comment]
- Audrey shared the YouTube upload with me this morning https://www.youtube.com/watch?v=gjZ1h6SqmYg
- I added it to the https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/ page which is embedded near the top with chapters present!
- I shared the materials (non embedded) with Brandi yesterday and she replied today that she is sending it over to Becca who is inputting content into the template _(Becca already has publication knowledge and has been DMing too)_
- Shared this update at engagement team call
- Shared on mofo-wagtail slack channel

@kristinashu is there anything remaining or needs review for this issue?

**Comment by kristinashu** [comment]
Good the close! Love the video and love that you've shared it around.
