### ISSUE TITLE
Blog post design review: Student follow-up on ethical AI MozFest session

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#858]
Via Kaili

> Three Stanford students who hosted a MozFest session about student perspectives on ethical AI have drafted a blog post that we plan to host on our site. There are some formatting challenges so I'd like a design review.

[Content doc.](https://docs.google.com/document/d/1Kz8bM__9wuTEO2wl28wADBqagL1mdfd_YN2ye3A0O74/edit)

**Comment by kristinashu** [comment]
Kaili will be adding the text as a blog post tomorrow. She would like an OG image and recommends it will be related to the https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/ work.

**Comment by sabrinang** [comment]
@kristinashu design review?
I’ve taken inspiration from RCSC to use similar colors, square dot patten and code overlay to be used in this OG graphic:
![MoFo-Blog-Post_Ethical-Considerations@2x](https://user-images.githubusercontent.com/2492510/118570242-9faa8d80-b730-11eb-81b6-354cbfcc210a.jpg)

**Comment by kristinashu** [comment]
R+ this looks great!

**Comment by sabrinang** [comment]
Awesome, files are exported here: https://drive.google.com/open?id=1NILaQh8r9bntFfEzNQCYWfGfs6gPMkY9&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by kristinashu** [comment]
Have you shared it with Kaili as well? She's the stakeholder on this.

**Comment by sabrinang** [comment]
I informed Kaili via slack that I am taking on this issue and also uploaded the image in the blog/promote sections of the [draft](https://foundation.mozilla.org/cms/pages/2125/edit/) she is working on today.
