### ISSUE TITLE
Graphics for Emergency Broadband Benefit campaign - June 10

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#859]
Via Kaili in A&E Slack

Deadline: June 10

How Americans can enroll in EBB (emergency broadband benefit) and a share ask. 

Ping Kaili for more info.

**Comment by kaili09** [comment]
Here's the RASCI https://docs.google.com/document/d/14RD-VoX51255lKFaDDGAri_NCn41DKHRZpgQYzT3Ols/edit

**Comment by kristinashu** [comment]
Seeing if P&G can do this!
