### ISSUE TITLE
Venmo petition delivery 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#861]
Create PDF of signatures.

[Style is similar to this](https://drive.google.com/drive/folders/1X3F4ztoLf6bwv4RLnxS4rEmwNk17w_Rw?usp=sharing). 

[Venmo graphics are here](https://drive.google.com/drive/folders/1NfDQVNx6JZGKPd60jGMV9fg1EbGvlEPA?usp=sharing).

### Needed from Kaili
- [x] Copy for the top of the petition [[use copy from the letter](https://foundation.mozilla.org/en/campaigns/open-letter-to-venmo-make-privacy-the-default/)]
- [x] [List of signatures](https://docs.google.com/spreadsheets/d/1QQydVEfH4aer5aa5UP8hptmsxQHteLkoYWGX7WYf71A/edit#gid=622636871)
- [x] Any additional partner logos if needed [[add EFF](https://drive.google.com/drive/folders/1iqKuz9cSzECQNI-QPC_v7-6lFB5J_d48?usp=sharing)]

**Comment by nancyt1** [comment]
Working files are in the [drive](https://drive.google.com/drive/u/0/folders/1Uv1XUbPBwTSJb7QbsIvM9kCHgso2BegT). It's up for review with Kaili now.

**Comment by nancyt1** [comment]
Export is in the [drive](https://drive.google.com/drive/u/0/folders/1lbeCT7Kvo52k0zlLeggIMls6j6x3zpWD) and handed off to Kaili.

**Comment by kristinashu** [comment]
awesome, thank you nancy!
