### ISSUE TITLE
Explainer Video Thumbnails

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#866]
### Intro

Thumbnails for Audrey and the next Explainer video:

- [x] mozilla.org image
- [x] IGTV grid
- [x] YouTube image
- [x] OG share image

[Thumbnail Drive](https://drive.google.com/drive/folders/14MpzEL5wCDFCSw43qPzhy3rqqIIhp-cC)
[Video Working Files](https://drive.google.com/drive/folders/11FXE6WvNd2x27A7Gs2pfK73AZjrOg-CO)

**Comment by kristinashu** [comment]
Bonus for this ticket is to create a template in Canva.

**Comment by nancyt1** [comment]
Completed thumbnails in [Canva](https://www.canva.com/folder/FAEfeza1moY). Looking into how to set up useful templates now.

**Comment by kristinashu** [comment]
@natalieworth have you / are you able to review these?

**Comment by nancyt1** [comment]
I set up some templates and uploaded some backgrounds for Audrey. Will probably improve on them after getting feedback from Audrey when she makes the next round of the thumbnails.
