### ISSUE TITLE
Write job description for visual designer

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#867]
Everyone to privately draft 3-5 requirements you think are needed for a new design position and share them with me.

Kristina to finalize a posting.

**Comment by sabrinang** [comment]
@kristinashu DM'd my draft requirements to you via slack

**Comment by kristinashu** [comment]
Thank you! It's a mess but I'm working on the post [here](https://docs.google.com/document/d/1Wsy4IZZxBB0pIeM6Ih9xUESVX55Xj-bbjLLaA3f8SHQ/edit#). Will try to polish it up on Monday.

**Comment by kristinashu** [comment]
Thank you everyone for your input! Closing this ticket and I've opened a flow up one here https://github.com/MozillaFoundation/Design/issues/874
