### ISSUE TITLE
AI & Consumer Privacy: Hulu campaign

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#869]
### Intro
Ticket for Hulu campaign. More info TBD

**Comment by kristinashu** [comment]
Kaili linked to [this doc](https://docs.google.com/document/d/19taUiLe7ZDTBATDZTOSgDs0ZN05JAe0fTR5RDH1pUWE/edit) and said Lindsay and Natalie are meeting on Monday to discuss ideas. Hopefully P&G can execute on the ideas.
