### ISSUE TITLE
Fix responsive view of build/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#87]
Currently looks like this, with text cut off on the edges:

<img width="385" alt="screen shot 2015-09-18 at 4 21 10 pm" src="https://cloud.githubusercontent.com/assets/1186326/9970140/5a482c0c-5e21-11e5-994c-3e155efef03b.png">

**Comment by cassiemc** [comment]
cc @vazquez

**Comment by vazquez** [comment]
I know :( this is a big challenge. Based on how the site was initially coded, we would need to refactor most of the html and css in build.wm.org to make this work. The site wasn't intended to be responsive, at least not from the code that is written. Let me take another look to see if we can fix it without a lot of refactoring.

**Comment by cassiemc** [comment]
This doesn't seem like a priority for the design team. I am going to file it as a new issue in the Build repo, and it can be prioritized there if necessary.
