### ISSUE TITLE
[YouTube RegretsReporter shareout] Branding and metaphor

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#870]
Structure of the content on the page is happening here https://github.com/MozillaFoundation/Design/issues/850

This ticket is for exploring and then deciding on the visual direction for the page.

Things to consider:
- YouTube Regrets page https://foundation.mozilla.org/en/campaigns/youtube-regrets/
- RegrestsReport page https://foundation.mozilla.org/en/campaigns/regrets-reporter/
- General Foundaiton branding foundation.mozilla.org/
- Incorporating a metaphor
- [Content doc ](https://docs.google.com/document/d/1pn8CUywtNo2J3rIlgfIKqCyJor1UiiLGqziHzVi_muI/edit#heading=h.6v1ik6cnpxi8)
- [Metaphor brainstorm doc](https://docs.google.com/document/d/1sDBXowOl4_l3MshXO3zknMZOkeeMridypslnYoSShi4/edit?ts=60a7e552)

Output for this ticket should be a presentation with options for designers and stakeholders to choose from.

**Comment by natalieworth** [comment]
I didn't get a chance to finish this but I started a moodboard here: https://www.pinterest.ca/nataliejworth/youtube-regrets/

I was also thinking for something weird/ creepy, I thought there was a regret about a weird Thomas the Tank video. Maybe something 3-d/ with blender could be cool for imagery and they could replace the body image quote with the Thomas the train one so it feels more connected?

[Sketchfab](https://sketchfab.com/3d-models/thomas-the-tank-engine-ba19706bffac40118d2c861d6bdbfb32) has open-source attribution Thomas the Tank Engines that could be cool.

**Comment by kristinashu** [comment]
Nat, always trying to bring the weird ❤️

**Comment by kristinashu** [comment]
Sabrina's moodboard directions are here https://www.figma.com/proto/Mp4TDFJIi02sYvxLDTCknF/YouTubeRegretsReporter-Share-Out?page-id=521%3A0&node-id=879%3A45&scaling=scale-down-width

The pathways (with some factory elements) direction was chosen and Sabrina started to design it out here https://www.figma.com/proto/Mp4TDFJIi02sYvxLDTCknF/YouTubeRegretsReporter-Share-Out?page-id=270%3A0&node-id=1093%3A915&scaling=scale-down-width

Creating the final illustrations and layout will be done here https://github.com/MozillaFoundation/Design/issues/880
