### ISSUE TITLE
Support Dev QA

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#875]
A few tickets from devs will need help with designs review — placeholder ticket

**Comment by sabrinang** [comment]
- working with Daniel to review streamfield new format PRs
- working with Simon on italic typography, style guide update and type alignment

**Comment by sabrinang** [comment]
Reviewing Danie's PR — streamfields now using new format (requested changes)

**Comment by sabrinang** [comment]
- Reviewed revised Daniel's PR — streamfields now using new format (approved)
- Meeting with Simon to discuss design library plans and suggestions on where to start

**Comment by sabrinang** [comment]
- commented on Daniel's PR — full-width image blocks on blog page (needs changes)

**Comment by kristinashu** [comment]
Thank you for working so closely with the devs!
