### ISSUE TITLE
PNI newsletter branding

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#877]
Jen has started a monthly newsletter around PNI products. She's going with the flow and plans to slowly build on top of it. The newsletter content (or parts of it) might expand to social and blog. She has always wanted a "PNI brand" and this is an opportunity to explore that. 

Deadline: first week of Aug

Links
- [Strategy doc](https://docs.google.com/document/d/1cyIqCwxOPKpFVwedMsY9xMijCMOEPJn501ChvhELq9g/edit?ts=60ba7779)
- [First email](https://docs.google.com/document/d/1glGxErQdV3TCiI5aZ9-EzYDa55q7lKzXjVfE1RFkJxM/edit)

Our approach will be to establish the look and feel for the email (header and sometimes some custom graphics within the email), create the first 2-3 emails, and then hand it off to a contractor/agency to produce the future emails directly with Jen. The email content is timely so the content will be changing and news breaks up until the email goes out.

Todo
- [ ] Meet with Jen
- [ ] Propose 2-3 different creative directions
- [ ] Design email with real content
- [ ] Template the format and document it so others can take it over
- [ ] Open up a ticket for the next email
- [ ] Open up a ticket to onboard an external contractor/agency

**Comment by kristinashu** [comment]
Jen is ok with holding of on this until the next next email at the start of Aug.

**Comment by sabrinang** [comment]
- Read the docs in this ticket and PNI docs linked from A&E call last week
- Reached out to Jen via slack and calendar meeting sent to zoom sync on this tomorrow

**Comment by kristinashu** [comment]
Closing this since it's out of date
