### ISSUE TITLE
[YouTube RegretsReporter shareout] PDF template and design review

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#878]
Campaign will need downloadable PDFs for several languages. [See this doc for the timeline.](https://docs.google.com/document/d/17k7cbQnqZdEhbD4VucVmXPnrKiT1MFkYqwqBLxvKsIQ/edit#)

- [x] Finalize copy [(doc is here)](https://docs.google.com/document/d/1NT_SrDQ5gx-m7hipa7opw-C7MaES8OZ_ySIKkiq3u40/edit)
- [x] Create a template based on this https://docs.google.com/document/d/1PTdSrNA7-2LiTmAISEOzWmPEhUZvbDPjaYp2-JFc8T8/edit
- [x] Update chart colors to align with site
- [x] Update it with our YT branding
- [x] Share it with Jesse for content input
- [x] Design review once content is in

**Comment by kristinashu** [comment]
Draft doc is here and is going through reviews now - should be approved by June 25.

**Comment by kristinashu** [comment]
I've done the first past at updating the formatting https://docs.google.com/document/d/1MInuqQtOdxqG6GW3aAGz8kGmg9_B6Xj8QCs05xSs8aQ/edit?usp=sharing.

@sabrinang do you think we should update the dot banner with an illustration from the site?

@nancyt1 are you able to properly export the graphs and clean up the YT screen caps?

**Comment by sabrinang** [comment]
Added illustrations to corresponding areas in the report and left the dotted banner at top as is:
![YouTubeRegretsReport_HeaderPDF](https://user-images.githubusercontent.com/2492510/123730577-6eeb6700-d84b-11eb-8463-b8154881033a.png)

![YouTubeRegretsReport_WhatisaRegretPDF](https://user-images.githubusercontent.com/2492510/123730576-6e52d080-d84b-11eb-98b4-80ba38f91683.png)

![YouTubeRegretsReport_FindingsPDF@2x](https://user-images.githubusercontent.com/2492510/123730571-6bf07680-d84b-11eb-849c-884840bd3278.png)

![YouTubeRegretsReport_RecommendationsPDF](https://user-images.githubusercontent.com/2492510/123730892-fa64f800-d84b-11eb-88f6-f99f7d8b4021.png)

**Comment by kristinashu** [comment]
Amazing, thank you Sabs! And thank you Nancy for updating the graphs!
