### ISSUE TITLE
[YouTube RegretsReporter shareout] Press & Marketing assets

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#879]
Graphics requests
- [x] Stills for Kevin for the press release (deadline Jun 29) [[design files](https://drive.google.com/drive/folders/1Yyi49U2_hMHV6DT1202-r_xET26C5wYv?usp=sharing)]
- [x] OG image
- [x] Homepage hero
- [x] Email: [Email RASCI ](https://docs.google.com/document/d/18Eg-kt64MlUbOjO5h3XowsOb3nB_dMNxtE4lE_g03cU/edit?disco=AAAANM_dgmw&ts=60dc6f6e)(deadline Jul 7) - I think this is going to be the video and the contractor will export the image
- [x] Social for Audrey: [doc](https://docs.google.com/document/d/1MtptS52C-1IYsOV11Kva9kas2CyR4wE9EWGv9p9v_zo/edit) (deadline Jul 7)
- [x] Xavier's How To blog post: OG and in body screenshots, [Blog Copy Doc](https://docs.google.com/document/d/1fmwh0nKFOolxHhR_J2AJPiVjpREs1SIq2SF3KkxnW5c/edit) (deadline Jul 7) (might need graphics for Insta later)

**Comment by kristinashu** [comment]
I've updated this ticket and will add to it as we get more info. Note that aside from Kevin's press release, everything else can be done in the first half of next sprint.

**Comment by kristinashu** [comment]
Started on the blog graphics https://redpen.io/p/jwa3c5863948020af0

**Comment by nancyt1** [comment]
Exported all assets to [drive](https://drive.google.com/drive/u/0/folders/1Y4LR6-eUOhYVaRYaEx5VIwNN2eRnYe13). Seeing if there's any last min feedback.

[Redpen is here](https://redpen.io/p/soc45f1e639a363b62)

**Comment by kristinashu** [comment]
This is done and looks amazing https://redpen.io/p/soc45f1e639a363b62! 

![screencapture-foundation-mozilla-org-en-2021-07-07-08_58_40](https://user-images.githubusercontent.com/1068783/124792330-c3ed4400-df01-11eb-8a6e-847b79644dc5.png)
![image](https://user-images.githubusercontent.com/1068783/124792716-1d557300-df02-11eb-8134-3f5779795240.png)
![image](https://user-images.githubusercontent.com/1068783/124792815-365e2400-df02-11eb-9d27-dc4eb0af68f6.png)
