### ISSUE TITLE
[YouTube RegretsReporter shareout] Design QA for Devs

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#885]
placeholder ticket for QAing design with devs

**Comment by kristinashu** [comment]
I'm gonna say this is done! We first put notes in [this doc](https://docs.google.com/document/d/1iW4yyjqDJ_sX43kFA0I8C99hVh1KoZT1CYBw9R7DlgU/edit?ts=60e5c4e6) and then opened tickets https://github.com/mozilla/foundation.mozilla.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22Youtube+Regrets%22. Devs are working on them and I'm doing PR reviews.
