### ISSUE TITLE
[YouTube Report Findings] Clean up files and document 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#888]
This ticket is to create time and space to wrap up the YouTube project. Up to @nancyt1 @sabrinang how you want to use the time. 

Nancy and I mentioned cleaning up the Figma file and structure it in an "ideal" state (i.e. how it would have been built in Figma had we had more time). It's also an opportunity to test out at a smaller scale, how we'd like to structure Figma for fo'mo.

Perhaps investigation why the Illustrator file was so computer crushing :)

Also making sure to document the site and assets in our recap deck!

**Comment by sabrinang** [comment]
We started a doc and noted things we discussed and to-dos: https://docs.google.com/document/d/1B-YVXr51jmPW6ecbtCt2G-FpLO6LthK7CtVx0b1N8Jo/edit?usp=sharing

**Comment by nancyt1** [comment]
Reorganized the Figma file, explored components, and added context, links, images to the [recap deck](https://docs.google.com/presentation/d/1vyH9vKs7uqB83MUFmZ5Yk7g-HDZ-tMJuAqTzy2-c5aw/edit#slide=id.ge4bb982a9e_0_0).

**Comment by kristinashu** [comment]
Figma file looked nice and clean, even the devs were impressed! 

Recap deck also looks lovely!
