### ISSUE TITLE
Mozilla News Beat/News Byte: July 30, 2021

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#890]
Working file in this [Folder](https://drive.google.com/drive/u/0/folders/1Jb9nK7xCYqp9R1xtHsW73D89B36Ajzr1)
- [x] Copy/paste emojis in from rasci
- [x] Scale down emojis 60% for blog
- [x] Update news quiz questions and emoji on the first slide (insta story)
- [x] Make sure dates in insta story and thumbnail are correct
- [x] Export blog & email emojis, instagram stories, thumbnail, and email header into folders
- [x] Share link to drive in news beat slack

Xavier can answer any questions if you have any (:

**Comment by sabrinang** [comment]
Assets exported here: https://drive.google.com/open?id=1Jb9nK7xCYqp9R1xtHsW73D89B36Ajzr1&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
