### ISSUE TITLE
[New hire] Prep for interviews & interview

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#893]
Follow up from - Review portfolios and prep for interviews #881

- [x] Write out interview questions
- [x] Interview candidates 
- [x] [Fill out rubric](https://docs.google.com/spreadsheets/d/1WaTgYU1aNMq5gFcXt_yKKY1TDvzoUhbsIH7iVOIMlL0/edit#gid=1163900155)

**Comment by sabrinang** [comment]
@kristinashu  I've prepped an interview questions doc (adapted material I've used before) and took notes for each candidate Letter/CV/Portfolio near the bottom as well: https://docs.google.com/document/d/15jAAXPiTSxbAV9eMdUSVJoecmreBFkWq_TEO6TSGuXQ/edit?usp=sharing

Will we be in a group conducting the interview or individual?

**Comment by nancyt1** [comment]
Added a few of my notes to Sabrina's doc under each candidate. I didn't have a lot to add, the interview questions were already so comprehensive! :O

**Comment by sabrinang** [comment]
We've met with the candidates this week and debriefed. I've submitted my rubrics to Mitali.

**Comment by nancyt1** [comment]
Submitted my rubrics as well!

**Comment by kristinashu** [comment]
Yay thank you both!
