### ISSUE TITLE
YouTube graphic in German 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#894]
Via Jon

Reuse last years YouTube Regrets but translated selected ones to German
- [ ] Graphic for Twitter post 

@TheoChevalier will provide the translated text

Working files https://drive.google.com/drive/folders/1iqhkYq8UH0LOhBgp_C4rYkYTkvhv8a9c

Deadline Aug 4

**Comment by TheoChevalier** [comment]
Hey @kristinashu, I’ll have translations ready by Monday morning! I’ll update this ticket

**Comment by TheoChevalier** [comment]
Hey there, here are the translations!

![5@2x](https://user-images.githubusercontent.com/1294206/127872906-0f6536cd-4321-4ed4-80f9-f4d04bc24f05.jpg)

Sie bereuen etwas auf YouTube?
Nehmen Sie an unserer Kampagne teil.
Jetzt installieren
---

![6@2x](https://user-images.githubusercontent.com/1294206/127872945-e0b2d89b-2887-4420-9fb5-67f316148d84.jpg)

Schonmal bei YouTube auf die schiefe Bahn geraten?
Helfen Sie bei unserer Untersuchung.
RegretsReporter herunterladen
---

**Comment by kristinashu** [comment]
Here are the graphics in Redpen https://redpen.io/p/znd6db39c8f657ef3f and as PNGs  https://drive.google.com/drive/folders/1g61E6Bh-qfszZe0HBTCagBo3bej4gjPC?usp=sharing
