### ISSUE TITLE
Figma Design Library: Grid & Layout

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#895]
Create and document styles in Figma file.

- figma frames used for 5 sizes
- grid styles for 5 sizes
- columns component for 5 sizes that contain various width combinations
- spacers component
- sizing design tokens in plug-in
- spacing tokens in plug-in
- document vertical spacing, horizontal spacing, padding and margin usage notes

Related to issues: #765 & https://github.com/mozilla/foundation.mozilla.org/issues/6952

**Comment by sabrinang** [comment]
Figma page here: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/?node-id=312%3A354

**Figma Frames (default ones to select from):**
- Desktop 1440x1024 for extra large viewport
- MacBook 1152x700 for for large viewport
- iPad Pro 11” 834x1194 for medium viewport
- iPhone 8 (rotated)  667x375 for small viewport
- iPhone 8 375x667 for extra small viewport

**Grid Styles:**
- Extra Large Grid for Wide Desktop (≥1200px) — 12 column; container width 1132px; column width 65px; gutter 32px
- Large Grid for Desktop (1200px≥992px)  — 12 column; container width 952px; column width 50px; gutter 32px
- Medium Grid for Tablet (992px≥768px) — 12 column; container width 712px; column width 30px; gutter 32px
- Small Grid for Mobile Landscape (768px≥576px) — 12 column; container width 532px; column width 15px; gutter 32px
- Extra Small Grid for Mobile Portrait (576px≥) — 12 column; container width 364px; column width 1px; gutter 32px

**Column Component:**
- Extra Large Columns 
- Large Columns
- Medium Columns
- Small Columns
- Extra Small Columns
   - Each matches corresponding container width and 32 gutter (12 column; 6 column; 4 column; 3 column; 2 column; five 2 column variants; 1 column)

**Spacers Component:**
- Spacer 1 — 4px (0.25 rem)
- Spacer 2 — 8px (0.5 rem)
- Spacer 3 — 16px (1 rem)
- Spacer 4 — 24px (1.5 rem)
- Spacer 5 — 32px (2 rem)
- Spacer 6 — 48px (3 rem)

**Figma Design Tokens Plugin:**
- Sizing tokens created 1-6
- Spacing tokens created 1-6
<img width="390" alt="image" src="https://user-images.githubusercontent.com/2492510/127401288-894d4eab-60a6-437a-add6-297be7a63de6.png">
Note: design tokens sizing and spacing can be applied to anything with Auto Layout


**Vertical spacing, Horizontal spacing, Padding and Margin:**
- this section needs more feedback on how we document it in the figma file 

_________________

Ready for review and feedback. Check with designers what is missing from grid and layout section (anything that should be documented to help usage). Review with Simon this matches what we have in code.

**Comment by sabrinang** [comment]
From @fessehaye dev feedback to align with rem measurements, I made some updates to the figma file:

**Grid Styles:**
- Extra Large Grid for Wide Desktop (≥1200px) — 12 column; container width 1120px; column width 64px; gutter 32px
- Large Grid for Desktop (1200px≥992px) — 12 column; container width 928px; column width 48px; gutter 32px
- Medium Grid for Tablet (992px≥768px) — 12 column; container width 736px; column width 32px; gutter 32px
- Small Grid for Mobile Landscape (768px≥576px) — 12 column; container width 544px; column width 16px; gutter 32px

**Spacers Component:**
- Spacer 0 — 0px (0 rem)
- Spacer px — 1px
- Spacer 2.5 — 12px (0.75 rem)

**Figma Design Tokens Plugin:**
- Sizing tokens created for 0 & px
- Spacing tokens created 0 & px

**Note:** I'm having issues defining "2.5" as a design token in the plugin as it uses "." as dot-seperated names so it couldn't be added to the plugin unless we define it without a ".". Also commented on PR https://github.com/mozilla/foundation.mozilla.org/pull/7175#pullrequestreview-725777917 
_____________________________

I've separated them into these sections:
- Figma Frames & Grid Styles
- Figma Components
- Design Tokens (Plug-in) and referenced https://docs.tokens.studio/tokens/documentation-tokens to create the living token documentation

I've omitted documentation on vertical spacing, horizontal spacing, padding and margin as I think it is more helpful to note it with the corresponding component or element instead as they vary for each.

@kristinashu ready for review and if there is anything else needed for this grid & layout section let me know.

**Comment by kristinashu** [comment]
Very thorough and pixel perfect @sabrinang!

I am just curious how the grid will be used in our typical workflow. I am more used to using this sort of Layout Grid view. Is that still possible or is there a new system now? Or will this grid be used to set up that Layout Grid?

![Screen Shot 2021-08-10 at 9 51 31 AM](https://user-images.githubusercontent.com/1068783/128901395-0c1c3f5f-c03f-43a5-8c1c-bd8cb844076e.png)

![Screen Shot 2021-08-10 at 9 51 24 AM](https://user-images.githubusercontent.com/1068783/128901387-16fd07f0-a9d6-4e39-bab7-5e8c6e450943.png)

**Comment by kristinashu** [comment]
@nancyt1 to review and test out the plug-in!

**Comment by sabrinang** [comment]
Update RE: issues defining "2.5" as a design token in the plugin as it uses "." as dot-seperated names 

Discussed with @fessehaye for https://github.com/mozilla/foundation.mozilla.org/pull/7175#pullrequestreview-725777917 as well that we will use whole numbers to avoid decimals rounding it to `3` and using names up to `7`. I've updated the figma component and design tokens in the plugin as well. I'm not sure why the live token documentation wasn't auto updating when I update the name but it's updated now.

**Comment by sabrinang** [comment]
@kristina I think the workflow would be similar where you'd add a frame (there's a bunch by default in figma):
<img width="331" alt="image" src="https://user-images.githubusercontent.com/2492510/128945094-55be26f0-b222-4ae2-bee3-3ba3d0149971.png">
Then select the Layout grid to apply (defined 5 grid styles):
<img width="307" alt="image" src="https://user-images.githubusercontent.com/2492510/128945177-0e95c160-2d74-491f-8524-7c889f333eae.png">

The columns component is there for reference for proportions if needed.

**Comment by nancyt1** [comment]
So thorough! Everything looked good; I tested the plugin and it works and is usable for me. Go Sabs! :D
