### ISSUE TITLE
MozFest 2022 lock-up

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#896]
Via @marcwalsh https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recf06AILZawzN3V0?blocks=hide

Todo
- [x] Check-in with Marc
- [x] Create a new 2022 lock-up
- [ ] Organize Drive folder
- [ ] Review the style guide and make sure everything is up to date

**Comment by sabrinang** [comment]
Lockups exported in google drive here: https://drive.google.com/open?id=1Qh6w2LOBha5WkC7l4ZpdKQ8wklC0ylr2&authuser=sabrina%40mozillafoundation.org&usp=drive_fs 

Closing and continuing documentation in #905
