### ISSUE TITLE
Fix formatting on design brief

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#90]
I'd like to bold the questions and add H1s so that a completed design brief is easier to read. I requested edit access from @lovegushwa

**Comment by lovegushwa** [comment]
@cassiemc @flukeout 

Hi @cassiemc , you should be able to edit.

**Comment by cassiemc** [comment]
This is done. Made it easier to read and fill out as a template. Check it out here: http://bit.ly/mozdesignbrief
