### ISSUE TITLE
Figma Design Library: Color

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#901]
Create and document styles in Figma.

- capture existing colors as color styles and design tokens
- clean up color range and naming conventions (exp. following 05, 20, 40, 60, 80 suffixes)
- clean up palettes (exp. consolidate PNI, MozFest etc. brand, UI colors etc.)
- expand colors to include other [mozilla colors](https://mozilla.design/mozilla/color/)
- expand colors that are usable for data visualizations
- document dark mode previews
- document any Web Content Accessibility Guidelines (WCAG) notes

Related to issue #765 & https://github.com/mozilla/foundation.mozilla.org/issues/6952 & https://github.com/mozilla/foundation.mozilla.org/issues/6985

**Comment by sabrinang** [comment]
- Created and documented styles in Figma: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/?node-id=312%3A541
- Captured existing colors as design tokens: https://github.com/MozillaFoundation/Design/blob/master/systems/tokens.json
- Captured existing colors as color styles: Use [Figma Tokens](https://jansix.at/resources/figma-tokens) plug-in _"Create styles"_ feature to use as Figma Color Styles
- Cleaned up color range and naming conventions (exp. following 05, 20, 40, 60, 80 suffixes): Using ordered value for scaling conventions for our range and names are documented in [design audit tokens tab spreadsheet](https://docs.google.com/spreadsheets/d/1-5kdUg0RExSj_jU6iQqeVg22oGTjRSY3AZZ-U8UcnTM/edit#gid=101195698)
- Palettes recommendation: Use alias tokens/tier 2 to add additional semantics to color choice that reference our colors. For example, when creating a palette create a new set of alias tokens and choose the closest from our set _(example: reference purple-60 to define a pni-purple)_. If there is a new color consider if a existing color can be aliased or introduce it as a different set (tier 2)
- Expanded colors to include other [mozilla colors](https://mozilla.design/mozilla/color/): Incorporated their neon blue, neon green, dark purple, lemon yellow and dark green but with simplified names and with scale range. 
- Included blurb about color impairment and to use data wrapper theme color for data visualizations
- Document any Web Content Accessibility Guidelines (WCAG) notes: Recommended to use a contrast checker and vision checker for the context you are using it in. This can get more specific in contexts color is used in our we document our WCAG considerations in the component we make themselves.
  - More work around accessibility and "dark mode" to be done in more specific context outside of color

**Comment by sabrinang** [comment]
Note: Files may be referencing the Figma "Color Styles" so those are not cleaned up yet. Check with designers about color decisions are curated palettes (example: PNI & Festival)

**Comment by sabrinang** [comment]
We discussed at yesterdays design huddle that:
1) For specific palettes _(example: PNI & Festival)_
Since PNI is going through updates we do not need to define them now but when we update them we can choose the best matches from our defined tokens and give them alias name. The designer who is working on the project can determine with colors will actually be used on the web/UI and if new ones are necessary _(note that colors in illustration/svgs do not need to be defined as tokens if not referenced elsewhere)_.

2) Cleaning up Color Styles (in Figma)
There were existing and duplicate sets of colors previously and discussed with designers it is okay to remove making them aware that it will disconnect previous references if they are using the library. I've removed the old styles and created styles from the token themselves via the Figma Token plugin. 

There is a relationship between Figma Token colors and Color Styles when they share the same name but it may be different if it is referenced from a library and not local. There is a note that using colors from Figma Tokens plug-in vs. Color Styles native to Figma on the [plug-in docs](https://docs.tokens.studio/tokens/color-tokens):

>  You might want to apply color or text tokens with the plugin, instead of using Figma's native style feature. This has a downside, which is that when the style is not local (but in a library) the plugin can't apply that style currently and will fall back to the hex value. I would advise you to use the plugin for color and text styles only as a manager of Figma Styles. That way you and your designers would keep using Styles but use the plugin to manage/create them (and have all the benefits of aliases etc). For theme swapping it's recommended to use Figma's Swap library feature.

**Comment by sabrinang** [comment]
So if it’s suggested to use the Plugin for color and text styles only as a manager of Figma Styles then we should discuss and agree on an approach that works for us on on how we use color.

**Ideas:**

Your Local Doc 
- Go to Libraries > `WIP Mozilla Foundation Design Style Library` > use colors imported from library
- No colors live in local doc (referenced via library)

The Library Doc
- Use Figma Tokens to manage/create Figma Color Styles (so it's synced with tokens repo and have all the benefits of aliases etc.)
- I’m thinking this 🚧WIP doc is getting messy during construction, do we want a separate doc where more things are landed/ready to use (like how we wanted components separate, to have a separate styles as well)?

Establish guidelines we want to follow as a team

**Comment by sabrinang** [comment]
I think it'd be good to wrap up some discussions to agree on how we use color at an upcoming jam/huddle. Otherwise my progress and ideas are ready for review/feedback @kristinashu

**Comment by kristinashu** [comment]
Excellent research, decision making, and documentation! Sounds good to discuss how we should apply the colors during next weeks jam. But this is huge process!

**Comment by sabrinang** [comment]
We decided to keep the same `WIP Mozilla Foundation Design Style Library` doc and publish only the section that's ready _(check boxes for removing old colors and adding new colors)_.
- this change is captured in Version history _(left a description of change helps make it obvious looking in the history)_
- other files may still see old color name or hex but if you select your page elements you can repick color from the updated styles to replace the old one as we discussed
- I will let Simon know that the figma library is now synced with new defined design tokens

Note: As this definition retrofits/incorporates existing colors to create a set that aligns with what exists further accessibility testing and color family harmony can be done and to be documented. Aspects to audit and refine maybe a bit tedious but we can evolve through usage and some aspects to be evaluated can include color space (compare RGB colors of equal HSL luminosity values and balance their actual perceived luminance), contrast ratios (especially with type and any data viz usage), value steps and color harmony as a set.

__________________
**Quick visual overview of what was removed and expanded:**
![color-update](https://user-images.githubusercontent.com/2492510/165388043-e5d3efa1-e2e1-403a-b833-95218129eb73.jpg)



Articles and tailwind references https://palettte.app/ which I used as my main choice to interpolate colors based in HSV
- This app was more straight forward working with existing colors even though it only has linear interpolation I found it simplified fine tuning values
- Other useful tools https://colorbox.io and https://lyft-colorbox.herokuapp.com/ may be useful if we dive deeper into color refinement as well in the future.
- Also used https://www.color-hex.com/ sometimes for more specific color value information

References:
https://medium.com/thinking-design/adaptive-color-in-design-systems-7bcd2e664fa0 (overview theory and resources)
https://uxplanet.org/designing-systematic-colors-b5d2605b15c (more technical approach to a building new color sets)
https://tailwindcss.com/docs/customizing-colors#generating-colors

**Comment by sabrinang** [comment]
@kristinashu R? Anything else to add for colors?

- I noted our library approach as we discussed this morning. 
- I also included a note about what to consider in the future as we use it (mainly around accessibility) and some resources/references I used in my process.

**Comment by kristinashu** [comment]
Amazing, R+! This is very thorough and everyone is in the loop!
