### ISSUE TITLE
Add relevant files to Thimble project folder

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#91]
There is nothing in the Thimble project folder on Drive. @flukeout and @sabrinang can you guys add relevant working files (including the promo artwork)? Idea is that if someone looks there they can find everything they need to start designing right away.

**Comment by cassiemc** [comment]
Assigning to @flukeout and @sabrinang to follow.

**Comment by cassiemc** [comment]
Reassigning to @sabrinang this week since @flukeout is at a work week.

**Comment by sabrinang** [comment]
I've added all the thimbles file I have into Google Drive > Design Assets > _PROJECTS > Mozilla Thimble

**Comment by cassiemc** [comment]
Passing the assignment onto @flukeout now.

**Comment by cassiemc** [comment]
@flukeout update por favor, have you done this yet?

**Comment by flukeout** [comment]
Done! It's syncing now so should show up soon :checkered_flag:
