### ISSUE TITLE
Handraiser: creative concepting meeting

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#912]
This projected originated in a Working Group ([planning doc](https://docs.google.com/document/d/1fDb-I2c5at9Nv6iX_LE3ToSK2OG-15lLtbuwjEei71w/edit) & [meeting notes](https://docs.google.com/document/d/146nKO9_i0u2-H9Jf-9Y2L7w1M_sbDhal5Rrqh2-eZpw/edit#heading=h.b26v6optvycp)).

Jon and Anil are leading this project and is working with the agency Forward Action. This project has been blocked by some technical issues aligning with our email system as well as some policy issues around using Facebook. This work is progressing and creative is ready to move forward.

### Workshop 1: Planning (done!)
- Pre-meeting links: review the principles of a handraiser programme in the [Essential Guide to Handraisers](https://drive.google.com/file/d/1kSH337iFgE4ReHfK9An9KjoG18v-KG3e/view) and [this blog](https://forwardaction.uk/2020/10/digital-fundraising-handraisers/)
Audrey references this moco campaign
- [Agenda](https://docs.google.com/document/d/15s1ZIxi0vLV3X7A3_62Xa239Z9p3XpfV_9me7tIfW2o/edit)
- [Video recording](https://mozilla.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c7da18f0-75f4-4917-8281-ad9d0101bbc0)
- [Mural board](https://app.mural.co/t/hellohello8989/m/hellohello8989/1629897843484/c5241eba10dfc9437c9a3e05e9102eb338dd53ba?sender=hello1438)

### Workshop 2: Creative Direction (coming up Thurs Sept 23)
- [Agenda](https://docs.google.com/document/d/14PX-n5KADYlc0zhqWVQKsvOCpec7hQzvBWDqq6yEH0U/edit#heading=h.galgrkv0qt77) which includes links to Mural board and some example handraisers that should be reviewed ahead of the call
- [Headlines](https://docs.google.com/document/d/1edOCl9L5JeBy7SmMj1Vge8WQxTYf2NDlCO9R5vDghKw/edit) that came out of the creative direction working session with Forward Action

**Comment by beccaklam** [comment]
Next steps are for Mozilla to select three headlines to take forward and write copy to accompany said headlines to test. Forward Action has asked for this copy by next Wednesday (Sept 29) and are hoping to book a review session on Thursday (Sept 30).

**Comment by kristinashu** [comment]
Closing this ticket since it is old and out of date.
