### ISSUE TITLE
[AI + Bias] Breaking Bias — Series 3 Assets

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#921]
Links: 
- [Drive Folder](https://drive.google.com/drive/folders/10EyekAcxTGE-nmF2JfCRFnTli9QZpJx_)
- [Draft Docs](https://docs.google.com/document/d/1VBNIRcdPQ7XGRR06EsnPTadRQiWIKwLRV94FLYp0Zkg/edit)

**To do:**
- [ ] Reach out to Xavier to discuss a more regular timeline for design work

**Deliverables:**
- [x] Blog Image
- [ ] Instagram Story 3x ([Content from Audrey](https://docs.google.com/document/d/1CPcbE9GtkaZ03aXw5Agqp-JVm7NS6Ne4r8QI_cAMkhM/edit))

**Comment by nancyt1** [comment]
Blog approved to be published soon, I need to edit 2 images to say "Disinformation"

Instagram content is on the way but probably will come after blog is published.

**Comment by kristinashu** [comment]
It's nice to see this is happening!
