### ISSUE TITLE
Re-size Rapid Response library images for Insta Stories

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#925]
Audrey would like the [graphics created by P&G](https://drive.google.com/drive/folders/1Scw-GOFOuB3I8S8zy9AUtuVzVSMIr__a?usp=sharing) re-size to fit IG story size 1080px by 1920px.

- [x] Ping Audrey to full understand her needs (does she want the the image as is or more as a background texture she could put text over-top?)
- [x] Do the production work
- [ ] Share with Audrey for feedback, perhaps she could test them in Canva

No deadline for this.

**Comment by sabrinang** [comment]
Shared redpen for feedback last week, Audrey has reviewed the graphics and is good with them.  
The earlier graphics in the set are less busy for gifs etc. and the latter images have more visual interest to accompany text — both types would be useful. I've excluded any missing assets from P&G anyway to wrap up this work.

Files exported in gdrive here: https://drive.google.com/drive/folders/1UfhH3rMXi41IgF91_Ib43O5nmmoZ9YCI?usp=sharing

**Comment by kristinashu** [comment]
Awesome, thank you Sabs! P&G has updated the Misinfo graphics as a test and it seems to work for me. They'll be updating the others as well. Thanks for flagging! Glad it wasn't a blocker tho.
