### ISSUE TITLE
[PNI Holiday Marketing] Production of All Ads

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#929]
Epic: [#918](https://github.com/MozillaFoundation/Design/issues/918)

 Make all of the assets compiled in #931
Create ads in Olly's styles, and the 2 new directions

### Deliverables:
- [x]  Twitter Ads
    - [x]  1200 x 628
    - [x]  1080 x 1080
- [x]  Pinterest Ads (1000x1500), 1:1 or vertical 2:3 or 9:16
- [x]  Reddit
    - [x]  Card Image: 1200 x 628. 3mb max
    - [x]  Thumbnail: 400 x 300, 500kb max

**Comment by beccaklam** [comment]
[Redpen](https://redpen.io/p/jx451d3b0dfad8e3d9) with the first draft of ads

**Comment by beccaklam** [comment]
All the assets listed in #931, as well as the OG and Promo images, have been made and uploaded [here](https://drive.google.com/file/d/1-3nrwRRPgkLBc-OpV9cHCKGF96pZeEbK/view?usp=sharing).

**Comment by beccaklam** [comment]
@nancyt1 I think this is good to close?

**Comment by nancyt1** [comment]
[Link to drive](https://drive.google.com/drive/folders/1MQkWRpGXsYFUE_lkZPIr1ntYaGffKxct) where all the assets will live, but yeah, good to close!
