### ISSUE TITLE
Add teach site files to Drive

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#93]
@sabrinang @kristinashu there are no design files for the Teach site on Drive, can you update them there so any contributor could get started without asking for files?

**Comment by sabrinang** [comment]
I've been using this gdrive folder for Mozilla Learning Network assets so far: 
https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eR2dpNnJXRTR1UVU&usp=sharing

I will plan to relocate and organize these into the main Design Assets gdrive and to also separate the thimble assets found in here to the Thimble project folder for related to #91 as well

**Comment by cassiemc** [comment]
@sabrinang Update please?

**Comment by sabrinang** [comment]
I've added all the MLN files I have into Google Drive > Design Assets > _PROJECTS > Mozilla Learning Network  
(not all have synced due to lack of google drive space - I reached 30 gb limit)

**Comment by cassiemc** [comment]
@sabrinang Status update on storage increase? Can we close this yet?

**Comment by sabrinang** [comment]
I got updated with more space and will organize the teach/MLN files to the design folder by Monday EOD

**Comment by cassiemc** [comment]
Woot, thanks @sabrinang!

**Comment by cassiemc** [comment]
@sabrinang doing some final cleanup, files are synced, plans to close by EOD today.

**Comment by sabrinang** [comment]
Files have been synced to Design Assets > _PROJECTS > Mozilla Learning Network
