### ISSUE TITLE
[Fundraising] CTA banner refresh for Websites

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#930]
Update donation call-to-action banners for end-of-year fundraising. This will be on foundation.mozilla.org and mozilla.org.

**Banners deadline:** Nov 23 - 30 Giving Tuesday and then Dec 20-31.

**Previous examples:**
- Botton, sticky, overlay https://redpen.io/p/fg819743a72e4b7e82 
- Top, not sticky, pushes content down https://redpen.io/bn196d177e6fa06b32 

**Things to consider:**
- mock-up to make sure it’s ok that two donate buttons are so close to each other
- appears on homepage only or on every page that is the first page someone lands on?
- note that the “Donate” button just links out to the donate page

**Next steps:**
- Check-in meeting with design & dev
- Anil to check-in on timeline
- Anil to check-in with moco
- Anil to get copy

For moco, similar to https://github.com/mozilla/bedrock/issues/6693#
- Anil is checking with moco to see if they can implement this

**Comment by sabrinang** [comment]
Figma mockups https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=9%3A65 shared in the slack group for feedback yesterday

**Comment by sabrinang** [comment]
@kristinashu for design review

### mozilla.org banner (MoCo)
Figma files: [mockups](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A270) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A270&node-id=116%3A274&viewport=241%2C48%2C0.09&scaling=scale-down&starting-point-node-id=116%3A274&show-proto-sidebar=1)
Banner images in google drive: [light banner](https://drive.google.com/open?id=1V_e1rJLlTNdt16sGHuSw8LEwEcO7pdjd&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) & [dark banner](https://drive.google.com/open?id=1Vc3YDs6_z1zWj96VDQCVpLDNIB7uUqyp&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

### foundation.mozilla.org banner (MoFo)
Figma [mockups](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A271) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A271&node-id=116%3A386&viewport=241%2C48%2C0.11&scaling=scale-down&starting-point-node-id=116%3A386&show-proto-sidebar=1)
Banner images in google drive: [blue banner](https://drive.google.com/open?id=1VcBPsENRH-VcJT8IFPlPhzJ2xZpRb9xg&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) & [dark banner](https://drive.google.com/open?id=1Vc3YDs6_z1zWj96VDQCVpLDNIB7uUqyp&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

_________________

- I also exported mockup jpg here for reference if needed: https://drive.google.com/open?id=1VdNWZdgWYyDxk9Ocyco9TeU-nrjYKQ0C&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- Copy taken from the 'No Testing' section here: https://docs.google.com/document/d/1r2Ft9tvEZLzgBPQE3HzECTUhCMBlNiSvWyFJCJOKsTQ/edit?usp=sharing

**Comment by kristinashu** [comment]
Looking good! For MoCo, I'm curious why there is both a light and dark version? For MoFo, I'm curious why there are two banner options are included? My preference for both is the dark blue version since it is the most legible, but what do you think?

**Comment by sabrinang** [comment]
I was thinking that Giving Tuesday and Year End was to look different for users so it didn't look the same for both donate asks to attract donors if they didn't notice the word change so I've included two options for each. I included both light/dark for mozilla.org since I wasn't familiar when they use black or blue buttons and if one would drive more donations than the other so I covered both (I had a light version for MoFo exploration too but it didn't look as strong in context next to our dark hero).

I'm assuming we can't test multiple then (since the copy said no testing actually) so we can go the dark blue one. I'll work on refining the files

**Comment by kristinashu** [comment]
Ok that makes sense, I just wasn't sure that it would be clear to devs which one to use.

**Comment by sabrinang** [comment]
@kristinashu for re-review

I revised both to use Giving Tuesday copy and blue banner style to simplify. 

### mozilla.org banner (MoCo)
Figma files: [mockups](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A270) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A270&node-id=116%3A625&viewport=501%2C48%2C0.25&scaling=scale-down&starting-point-node-id=116%3A625&show-proto-sidebar=1)
Banner image in google drive: [blue banner](https://drive.google.com/open?id=1VcBPsENRH-VcJT8IFPlPhzJ2xZpRb9xg&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
_Note: mozilla.org butttons revised to white primary instead of blue/black to stand out against blue banner._

### foundation.mozilla.org banner (MoFo)
Figma [mockups](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A271) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A271&node-id=116%3A386&viewport=241%2C48%2C0.11&scaling=scale-down&starting-point-node-id=116%3A386&show-proto-sidebar=1)
Banner images in google drive: [blue banner](https://drive.google.com/open?id=1VcBPsENRH-VcJT8IFPlPhzJ2xZpRb9xg&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

_________________

- Mockup jpg and banner exported in drive if needed: https://drive.google.com/open?id=1VdNWZdgWYyDxk9Ocyco9TeU-nrjYKQ0C&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- Used Giving Tuesday copy from 'No Testing' section for mockups here: https://docs.google.com/document/d/1r2Ft9tvEZLzgBPQE3HzECTUhCMBlNiSvWyFJCJOKsTQ/edit?usp=sharing

**Comment by kristinashu** [comment]
Awesome! Thank you!
