### ISSUE TITLE
[PNI Marketing] Production of Share Images

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#932]
- [x] Make all of the assets compiled in #931

Produce assets for general OG as well as each category

### Deliverables in Olly's Style (Becca)
- [x]  OG Share Image (1200x638)
- [x]  Promo Image (1200x628)
- [x] Localized versions:
     - [x] DE: * Datenschutz nicht inbegriffen
     - [x] ES: *privacidad no incluida
     - [x] FR: *confidentialité non incluse
     - [x] fy-NL: *privacy net ynbegrepen
     - [x] NL: *privacy niet inbegrepen
     - [x] PT: *privacidade não incluída
     - [x] PL: *Prywatność do nabycia osobno

### Deliverables in 3D Style (Nancy)
- [x] Page Banner (1984x567)
- [ ] Large Thumbnail (800x450)?
- [x] Email??

**Comment by beccaklam** [comment]
All the assets listed in #931, as well as the OG and Promo images, have been made and uploaded [here](https://drive.google.com/file/d/1-3nrwRRPgkLBc-OpV9cHCKGF96pZeEbK/view?usp=sharing).

**Comment by nancyt1** [comment]
Finished all assets and linked them below, yay!
Link to [Promo Images](https://drive.google.com/drive/u/0/folders/1R_HTnjGw2Llws9mghtBJwayKmCbKTPeI)
Link to [OG Images](https://drive.google.com/drive/u/0/folders/1SU4otqqyZY_3JVOrjPPIkrMF_-xtIdgR)
Link to [email headers](https://drive.google.com/drive/u/0/folders/1vRn2P8rP5J2ejlX62V4iGtvGllSkrzw3)
Link to [Hero images](https://drive.google.com/drive/u/0/folders/1RweqVYlSWgWzu_uTg5wDbW9Mkccre0no)

**Comment by kristinashu** [comment]
Most of this is now live! Is it good to close?

![giphy](https://user-images.githubusercontent.com/1068783/142046777-2e1733e5-6cba-4fca-b056-8d61d282a685.gif)
