### ISSUE TITLE
[YouTube Regrets] Marketing Assets Draft

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Design#936]
Create marketing assets for the launch of the new YouTube RegretsReporter Extension.
Time line for assets is:

> Draft by: Nov 15
> Review: Nov 16
> Revision: Nov 17
> Final review: Nov 19

- [x] First draft
- [x] Submit for review

**Comment by beccaklam** [comment]
Asked Lindsay for which assets she wants updated, waiting to hear back!

**Comment by beccaklam** [comment]
Moving this to the next sprint because I won't get the new copy until I'm back from PTO.

**Comment by beccaklam** [comment]
Confirming [these are the assets needed](https://redpen.io/p/wpcccce987c35da2e3) and that no changes are needed.

**Comment by beccaklam** [comment]
From Lindsay: For the product, we should change the CTA - something like: Take back control of your recommendations

**Comment by beccaklam** [comment]
Links to assets that they want reproduced: 

- https://twitter.com/mozilla/status/1314616606090317827

- https://twitter.com/mozilla/status/1309219076384808960

**Comment by beccaklam** [comment]
[Redpen assets here!](https://redpen.io/p/wpcccce987c35da2e3)

**Comment by kristinashu** [comment]
I think the drafts are done and you can finalize them here https://github.com/mozilla/foundation.mozilla.org/issues/7666. If so then is this good to close?
