### ISSUE TITLE
[Miscelaneous] small and unplanned design requests for Sprint Oct 25 - Nov 5

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#938]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by nancyt1** [comment]
Reviewed Canva post for Audrey. **Time Spent:** _30mins_

**Comment by kristinashu** [comment]
Looks like this was a light one! I opened a separate ticket for PNI content entry https://github.com/MozillaFoundation/Design/issues/944
