### ISSUE TITLE
MoFo Design Audit

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#94]
Collecting and comparing examples of design issues across our Foundation properties that will inform upcoming branding initiatives.

**This would include *(but not limited to)*:**
- Mozilla Advocacy
- Mozilla Science Lab
- Knight-Mozilla Open News
- Mozilla Webmaker
- Mozilla Thimble
- Mozilla X-Ray Goggles
- Mozilla Learning Network
- Mozilla Festival
- Mozilla Clubs & Maker Party
- Hive Networks
 - Mozilla Gigabit Fund *(not sure if this work is being integrated into hive or is still separate with the new NSF grant received in September)*

**Other extended properties to note:**
- Foundation page (https://www.mozilla.org/en-US/foundation/)
- Parts of properties that may direct elsewhere:
  - various blogs (i.e. - https://blog.webmaker.org/, https://blog.mozilla.org/netpolicy/, https://www.mozillascience.org/blog)  
 - various discussion tools (i.e. - https://discourse.webmaker.org/, https://forum.mozillascience.org/)
 - various log-ins

**Attributes to review:**
- [x] headers
- [x] footers
- [x] grid / responsive layouts
- [x] illustration
- [x] photography
- [x] iconography
- [x] typography
- [x] colors
- [x] buttons
- [ ] labels
- [x] treatment/placement of logo

**Comment by lovegushwa** [comment]
@sabrinang I also did a bit of digging around MOCO properties and I wonder if we should have a tiny MOCO side audit? https://www.mozilla.org/en-US/firefox/os/2.0/ for example.

**Comment by sabrinang** [comment]
@lovegushwa yeah I think that is definitely an informative exercise to do as well! I'll look into it on the side :mag:

**Comment by cassiemc** [comment]
@lovegushwa to help out here.

**Comment by sabrinang** [comment]
The audit is a continuing work in progress due to the extensive nature of it we may need to strategically break this ticket up so it would be more specific and useful. Here is a overview of the audit so far any may of these pieces can be found in the branding jam doc:
![mozilla-foundation_audit-progress](https://cloud.githubusercontent.com/assets/2492510/10255053/9219873a-68fc-11e5-9ed8-43d2b1624110.png)

There are some legacy examples included as reference but included to consider the holistic picture of where are properties were at and where they may be headed (may be better to label and annotate in specific break out tickets instead). 

Let's touch base on how to approach this after our branding jam discussions continue.

**Comment by cassiemc** [comment]
@sabrinang Seems like we should do this consistently with what's been accomplished in the [Teach Design Audit](https://github.com/mozilla/teach.mozilla.org/issues/1260). Here's a checklist, which I'll copy to the top comment:

- [x] headers
- [x] footers
- [x] grid / responsive layouts
- [ ] illustration
- [ ] photography
- [ ] iconography
- [ ] typography
- [ ] colors
- [ ] buttons
- [ ] labels
- [ ] treatment/placement of logo

@sabrinang @lovegushwa Does this seem like the right list to try and document? Am I missing anything? This can be a template/lens of sorts that we can use to look at various properties.

Once we check off all these things and have them documented in the [Branding Jam document]( https://docs.google.com/presentation/d/1H2Q9lOXVYz-XnHKmM2eaAApy007QihzjixlUB2cLc50/edit#slide=id.g6f509ac88_7_19) we can close this issue.

**Comment by cassiemc** [comment]
@lovegushwa I'd love for you to drive this issue. Are you game?

**Comment by lovegushwa** [comment]
@cassiemc yes I can drive this.

**Comment by cassiemc** [comment]
@lovegushwa I think we should put this on hiatus until Dec/Jan, after the EOY campaign.

**Comment by cassiemc** [comment]
@lovegushwa Passing this off to @kristinashu for this heartbeat. I'll invite you to our kickoff though we so we can knowledge transfer! In the meantime can you link any assets you've created here?

**Comment by cassiemc** [comment]
@sabrinang is pulling together a style / guidelines template, also based on @vazquez's work on Webmaker. Let's use that as a final form for this as well.

**Comment by cassiemc** [comment]
@kristinashu has made great progress on this. Hoping to close for this Friday, Feb 12. Work so far: https://docs.google.com/presentation/d/13v_Rr2ypxscqSZWksLAzc5TZ8NRy0MuGSP9yK-FEKFo/edit#slide=id.g10a9224583_1_124

**Comment by kristinashu** [comment]
Think I'm just about done https://docs.google.com/a/mozilla.com/presentation/d/13v_Rr2ypxscqSZWksLAzc5TZ8NRy0MuGSP9yK-FEKFo/edit?usp=sharing

**Comment by cassiemc** [comment]
@kristinashu You are right, it's very close, but we need to add a bit more depth to the document. Having screenshots that aren't annotated in some way isn't satisfying the objective of this bug to understand how/why design decisions are made or understanding the impact on our audiences or the scale of work it will take to align them more closely together. If you can address a my couple of comments in the deck today, we should still be good to close this on time. 

As part of https://github.com/MozillaFoundation/plan/issues/685 I'm going to start a spreadsheet that is more comparative and less visual, but essentially takes what you've done here and puts it side by side, for an easier overview to know where things need updating and aligning. Starting as a second tab in the [Communications inventory](https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=2008361845) doc.

**Comment by cassiemc** [comment]
@kristinashu addressed my comments, thanks!! So happy to close this and move onto phase 2. We'll be updating another view of the Communications inventory that mirrors results from this visual audit here. That work will be happening here: https://github.com/MozillaFoundation/plan/issues/685
