### ISSUE TITLE
Net Neutrality graphic for Call Power [due before Nov 15]

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#940]
Via Kaili: We will be launching an email in the coming weeks on Nov 15 to support President Biden’s nominations to the FCC as part of our net neutrality work and I’ll need a graphic for the webpage (will be using the Call Power snippet that Pomax has been building).

We can re-use this style https://redpen.io/p/vmd0f747f9341e96e0 but add in a phone icon.

Dimensions should be for the campaign page in wagtail (either a campaign or banner page type) and an OG share image (that will be used for both the wagtail page and Share Progress).

[Email copy doc.](https://docs.google.com/document/d/1ZoOOGJFLDHnalU5dyNw9eGU8ZC6_q-tlt2GwFpjH_e8/edit)

**Comment by nancyt1** [comment]
Asset and working file lives [here](https://drive.google.com/drive/u/0/folders/1F_iaPnCNBSlAsugHxAKoe58i-mcAmfz1)!
