### ISSUE TITLE
[Fundraising] #dearinternet 2.0 planning

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#942]
Refresh #dearinternet for 2021

- create a top banner on MoFo & MoCo site for EOY
- work with Anna on copy
   - call for new stories?
   - prep assets so they will be easy to update?
- confirm all the copy is editable in the CMS

**Comment by kristinashu** [comment]
John will provide copy on Monday and then we can update it in the CMS. He will also provide copy for Typeform, which either Anil or we could update.

**Comment by sabrinang** [comment]
Copy doc from John via slack thread: https://docs.google.com/document/d/19n_Inp7bfe-GEhvf5jyPHN0hsKZy8v7CfCnJEPUlP58/edit?usp=sharing

**Comment by sabrinang** [comment]
Copy updated and live on: https://foundation.mozilla.org/en/campaigns/dearinternet/
- let them know on slack thread and that the meta description still has 2020 in it

**Comment by sabrinang** [comment]
Worked on some MoFo dearinternet banners here: https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=293%3A462
- @kristinashu for design review and if you have a preferred style?
- I adapted copy for the banner from the updated page copy (do I get Anna or John to review copy?)
- Will this need a MoCo version too? I can adapt the banner after direction is reviewed

**Comment by kristinashu** [comment]
They all look gorgeous Sabs! I left some comments in Figma but overall I prefer the second version since I think it is the most legible. 

Since this is more about the website, I would lean towards asking Anna for copy but maybe you could cc John as well?

Yes, if you think it could be adapted for moco then please go for it so it's all aligned!

**Comment by sabrinang** [comment]
Dates to go live: December 20-31, 2021

**Comment by sabrinang** [comment]
@kristinashu for re-review

### mozilla.org banner (MoCo)
Figma files: [mockup page](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A270) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A270&node-id=317%3A526&viewport=287%2C48%2C0.16&scaling=scale-down&starting-point-node-id=317%3A526&show-proto-sidebar=1)
Banner image in google drive: [MoCo banner](https://drive.google.com/open?id=1WJsmFbDW3pRP-R6pBsRr5dQCHviiZsCz&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

### foundation.mozilla.org banner (MoFo)
Figma [mockup page](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A271) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A271&node-id=327%3A582&viewport=287%2C48%2C0.22&scaling=scale-down&starting-point-node-id=327%3A582&show-proto-sidebar=1)
Banner images in google drive: [MoFo banner](https://drive.google.com/open?id=1W92ljfva7puOuvbRN-eZgdkCKnegCb7-&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

___________________________

- Used Year-End copy from 'No Testing' section of copy doc: https://docs.google.com/document/d/1r2Ft9tvEZLzgBPQE3HzECTUhCMBlNiSvWyFJCJOKsTQ/edit?usp=sharing
- cleaned up figma file to place frames in corresponding website page Q4 update and moved old frames in explorations
- google drive link with working file and assets: https://drive.google.com/open?id=1W3nBXaQQvIEgl_P8rfdbHankTTK9A3er&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by kristinashu** [comment]
R+ on the design!

**Comment by sabrinang** [comment]
Shared in fundraising slack channel for Juan/Anil to review

**Comment by sabrinang** [comment]
- asked (anil/anna) in slack thread about UTM for 2021eoy related to DearInternet page

**Comment by sabrinang** [comment]
- updated dearinternet donate links with UTM info from Anna
- repinged Juan/Anil via slack thread to review banners by Monday so we have them ready for next sprint

**Comment by sabrinang** [comment]
- reached out to MoFo devs via slack and filed implementation issue https://github.com/mozilla/foundation.mozilla.org/issues/7981
- reached out to MoCo Dan cc'd Anil/Kristina via email to initiate design update

continuing follow up and support in #954
