### ISSUE TITLE
[Miscelaneous] small and unplanned design requests for Sprint Nov 8-22

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#943]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by nancyt1** [comment]
Design reviewed a slide deck for Lindsay. **Time Spent:** _45min._

Edited a PNI asset for Lindsay. **Time Spent:** _30mins_

**Comment by nancyt1** [comment]
News Quiz assets. **Time Spent:** _30mins_

Created localized pni email headers. **Time Spent:** _30mins_

**Comment by kristinashu** [comment]
I'm glad the quiz didn't take too long. Thank you for doing all of these Nancy!
