### ISSUE TITLE
[Fundraising] Miscellaneous End-of-Year Graphics

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#946]
Placeholder Ticket

- [x] Donate campaign page https://donate.mozilla.org/en-US/2021eoy/ before Nov 29 (Anil & Juan)
- [x] Maybe Pocket before Dec 24, need dimensions and specs (Lindsay)

**Comment by sabrinang** [comment]
**Assets for Pocket**
- a minimum 300 pixel wide logo
- a 300x300 pixel (2x/Retina) placement image

@kristinashu design review?
I've cropped the blue donate banner to align with the rest of the campaign, redpen here: https://redpen.io/p/py8f867b21eedf430e

Assets on google drive: https://drive.google.com/open?id=1WDlYxCKPcdxT5s0acg94tdi4uia87uBi&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by kristinashu** [comment]
R+ 
It's was helpful to see the in-situ email example and the tight cropping makes it feel nice and dynamic!

**Comment by sabrinang** [comment]
Great thank you! 

- I shared the assets with Lindsay via slack thread
- Also, waiting for cms access to donate pages to be able to help adjust images

**Comment by sabrinang** [comment]
Updated https://donate.mozilla.org/en-US/2021eoy/ to blue style to match campaign banners

**Comment by kristinashu** [comment]
Nice! The text is very legible and I like how the color matches the buttons!

**Comment by sabrinang** [comment]
Any follow up will happen in #954 — closing
