### ISSUE TITLE
Design File for all MoFo Logos 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#95]
Collect all Foundation logos and organize them all in one vector (.ai) file.

**Comment by cassiemc** [comment]
@sabrinang Have you had a chance to look at this yet?

**Comment by sabrinang** [comment]
@cassiemc Yeah, the logo collecting is in progress:
<img width="1440" alt="screen shot 2015-09-24 at 3 17 35 pm" src="https://cloud.githubusercontent.com/assets/2492510/10088436/a504d774-62cf-11e5-9036-c728de0eec31.png">
 I will collect the final few logo vectors and then resize and organize them all so they are balanced and comparable

**Comment by cassiemc** [comment]
Fantastic thanks @sabrinang!

**Comment by sabrinang** [comment]
<img width="1440" alt="screen shot 2015-09-25 at 4 41 05 pm" src="https://cloud.githubusercontent.com/assets/2492510/10114345/457ddd16-63a4-11e5-9a99-80e4fc26ea43.png">

For the horizontal lockups, it is tricky to size them equality as there are inconsistencies in type sizes to logo ratio throughout.

Design Assets > Assets > Logos > Mozilla-Foundation_Logos.ai - Located here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNlFGV2pXV1lMODQ/view?usp=sharing

**Comment by cassiemc** [comment]
:+1:
