### ISSUE TITLE
[PNI Holiday Marketing] Header graphic for blog post "Amazon Echo, Google Nest, or Apple Homepod: Which is the least creepy/invasive?"

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#957]
[Draft Doc](https://docs.google.com/document/d/1-V_k7w2CAp3LNePzIQkO-Y36dFRBna6r4BIF_Bi_FAo/edit#)
Drive Folder

**Comment by kristinashu** [comment]
@nancyt1 do you know if this is still going to happen?
