### ISSUE TITLE
Fix cover of Chicago Report

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#96]
For the Chicago Report cover I cut out sabrina's head from the image to overlap the letters, but now it is appearing off-color. I could fake it just by cutting out along the line of the graphic behind her (the angle of the orange line) but I'd like to know why this is happening and fix it properly. 

/cc @lovegushwa Do you know?
/cc @laurareynal

![chicago-cover](https://cloud.githubusercontent.com/assets/1186326/10019133/9688d726-6109-11e5-897e-b650abb01371.png)

**Comment by cassiemc** [comment]
I exported two versions – one for print and one for viewing online, I wonder if maybe the print version is posted online so it's converting the CMYK photos to RGB, causing the difference? The cutout is a transparent PNG

**Comment by LauraReynal** [comment]
Cassie, in my drive folder, the online version appears like that since the beginning. 

Maybe we should export again?

**Comment by LauraReynal** [comment]
On a side note, we also need to blurr elements of a picture page 42. 
I received 2 comments about that picture (a phone)
- we can see on top a conversation group called cohiee eaters. Apparently it means something really bad and we should blurr it.
- We can see a name on that phone "Kendall" and we should blurr it out as well. 

do you know how to do it @lovegushwa @cassiemc ? 
I usually use an online tool for blurring, but It's not been really good.

**Comment by cassiemc** [comment]
@LauraReynal I have fixed these now! New files are here: https://drive.google.com/a/mozilla.com/folderview?id=0BzfN9sXlOXt1X200OHFQQkx6V1k&usp=sharing

I recommend you let people choose between two links: for viewing online, and for printing. They use two different color profiles and are different resolutions/sizes (96mb vs 13mb), so much better to give the viewer that choice. The online version now is separated into page by page so it's easier to read. Blurring is fixed. Cover is fixed.

@LauraReynal can you update links then close this?

**Comment by LauraReynal** [comment]
Are you thinking about something like  mzl.la/chicago-online & mzl.la/chicago-print ?

**Comment by cassiemc** [comment]
Or mzl.la/chicago (the online version) & mzl.la/chicago-print. Would predominantly share the online version since you say people don't really print it. (if you'd like you could just not share the print one?)

**Comment by cassiemc** [comment]
Laura, the new online version with spreads is here: https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1YXBUY0hXd2VKSmM/view?usp=sharing

**Comment by lovegushwa** [comment]
@cassiemc would try using transparent .psd rather than .png ... Photoshop files seem to work best with transparent backgrounds. Also it could be caused by the transparency flattener settings when exporting a PDF.

**Comment by cassiemc** [comment]
This is done. Thanks all
