### ISSUE TITLE
[Design System] Storing and Syncing Design Tokens

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#968]
Discussed with @fessehaye 

**Storage Location**
We need to find a location where we can store design tokens:
- so they are accessible to the team for both design and development
- consider github as it allows our design decisions to live in the same place as your code lives and we would be able to version control it

**Sync & Usasge**
We need to figure out a process of syncing design tokens in our workflow:
- for design, we plan to use the [figma token](https://docs.tokens.studio/) plugins but we need to store the tokens so they are accessible across all our projects. They also have a [github sync](https://docs.tokens.studio/sync/github) option now introduced a few months ago
- figure out how we can keep tokens up to date from either the github repo and design plug-in to sync design/dev workflow

**Comment by fessehaye** [comment]
tokens are stored in `systems/tokens.json`

@sabrinang and I tested that the figma tokens push and sync to latest tokens

If people need to have access to the sync features they will need to make github personal token explained here: https://docs.tokens.studio/sync/github#3-generate-your-personal-access-token
