### ISSUE TITLE
Copy for research site MVP

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#97]
Write copy for landing page.

Based on thoughts in https://github.com/MozillaFoundation/plan/issues/553
and wireframes https://redpen.io/p/oj84c5335720112e06

**Comment by LauraReynal** [comment]
@LauraReynal

**Comment by cassiemc** [comment]
@LauraReynal I don't imagine you'll be able to finish this by tomorrow given your prep for Indonesia. Am I wrong? Updating the milestone to reflect that but please put it back if I'm mistaken.

**Comment by cassiemc** [comment]
Moving this to backlog, not sure what current plans are for the research site.

**Comment by LauraReynal** [comment]
Hey @cassiemc thanks for hosting this ticket. I'll close this and team tag with bobby to make this happen pre-orlando.
