### ISSUE TITLE
YouTube Regrets: Illustration Layer Order

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#979]
I noticed the illustration layer for the bottom element is behind the platform but the video/cube should be in front _(like in the PDF image exports)_:
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/2492510/151635690-b38e82c5-2d91-4c0a-80e3-212c28598922.png">

This export may have been used elsewhere as well but can be updated.

**Comment by kristinashu** [comment]
Closing this ticket since it is old.
