### ISSUE TITLE
Comps for research site MVP

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#98]
Based on thoughts in MozillaFoundation/plan#553
and wireframes https://redpen.io/p/oj84c5335720112e06
Copy will come from https://github.com/MozillaFoundation/Design/issues/97

**Comment by kristinashu** [comment]
cc @LauraReynal

**Comment by cassiemc** [comment]
@kristinashu I am going to remove this from the milestone given recent discussions re the scope of the research site.

**Comment by LauraReynal** [comment]
Hey team, thanks for the help on this ticket. Im closing it because Bobby is going to lead this task and get something online by Orlando.
