### ISSUE TITLE
Images for Platform Recommender Systems report

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#980]
Max G and Eeva would like some graphics for their report which is in draft [here](https://foundation.mozilla.org/cms/pages/16459/). They would like to reuse this [3D social media](https://drive.google.com/drive/folders/11pXWRMN0RABDa_eYcqwne_tPcXcR06_K) direction ([working files are here](https://drive.google.com/drive/folders/1elMNYvSuKhYXOfHkcyvcPdGD0t-cVzyt)) and with numbers, something like https://foundation.mozilla.org/en/campaigns/tiktok-political-ads/. Max has [drafted it here](https://docs.google.com/presentation/d/1cB52pKF1pIwx2Mm3INoG0c1FektZZCpnRxCrNNOf9Zc/edit#slide=id.g11173c1d393_0_0) to help communicate this.

Assets needed are:
- [x] - One hero image for the publication PDF itself
- [x] - A banner for the publication page
- [x] - A banner for the landing page (banner template)
- [ ] - A thumbnail image for the link to the publication page on the landing page
- [x] - Thumbnail number images for the table of contents on the publication page 

They are ok with the same images being used, just at different dimensions. 

There is no fixed deadline but illustrations are blocking the launch of this report :)

**Comment by kristinashu** [comment]
Eeva clarified where the landing page and publication will be on the site:
- Landing (banner) page: https://foundation.mozilla.org/cms/pages/16622/edit/
- Publication page: https://foundation.mozilla.org/cms/pages/16459/edit/

**Comment by nancyt1** [comment]
Link to [drive](https://drive.google.com/drive/u/0/folders/1XQ_kGm0JB2lSUcYBcx1czXQFYjKqpzLW) with all the assets. 
Also sent them an email with the link and to let me know if it needs any adjustment.
