### ISSUE TITLE
[Misc] small and unplanned design requests for FEB 14 sprint

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#985]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by sabrinang** [comment]
MozFest tasks — _50 minutes_

- check and reply old ticket https://github.com/mozilla/foundation.mozilla.org/issues/7643 
- review [folder](https://drive.google.com/open?id=1ys1d29OMBJi18pKZ6Nr28_Wo0lpG0lOc&authuser=untamedsoul%40gmail.com&usp=drive_fs) and test slide decks for fringe, mozfest and pixlr photo filter template 
- review livestream assets, title cards, sponsor backdrop [redpen](https://redpen.io/p/wud270835246149c27)
- review [redpen gifs](https://redpen.io/p/fh752234d09189f409) for Mariska 
- reply slack threads

**Comment by nancyt1** [comment]
Created an [instagram](https://drive.google.com/drive/u/0/folders/1yOC-8tUTlNWJa8Iiwuaex4gPVw-iHM_M) post for social shopping for audrey. **Time Spent:** _1.5 hr_

**Comment by sabrinang** [comment]
- Review PR https://github.com/mozilla/foundation.mozilla.org/pull/8248 — _25 minutes_

**Comment by nancyt1** [comment]
Updated encryption [post](https://drive.google.com/drive/u/0/folders/11m1j1njFuSANIkIuhE4mFDmchvtUI8eA) for audrey. **Time Spent:** _40min_

**Comment by sabrinang** [comment]
MozFest reviews — _30 minutes_
- review [various](https://redpen.io/p/ze6290f12f4bbdc1b9) redpens 
- review promotional video [drafts](https://www.dropbox.com/t/nfvGrYWWazrvXcsB)
- slack replies Naomi/Bas

**Comment by sabrinang** [comment]
MozFest — _13 minutes_

- review twitter ads and title card [redpen](https://redpen.io/p/cre4f8463bbe2ff9a7)
- check slack threads for updates
