### ISSUE TITLE
[Blog Improvements] Design author pages

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#992]

**Comment by nancyt1** [comment]
Can i get [page](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements?node-id=732%3A68977) reviewed as well?

**Comment by nancyt1** [comment]
Can i get [page](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements?node-id=732%3A68977) reviewed as well? @kristinashu

**Comment by kristinashu** [comment]
Looks good, approved!
