### ISSUE TITLE
Update documentation on Wagtail with new social media guidelines

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#998]
Update this [page](https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/) with info from [Agency Deck](https://docs.google.com/presentation/d/1WxyQLgbQAYccRl-9X3PPhi3ROXd4sy1PuqfLU_YMXrw/edit#slide=id.g1172a141d12_0_0) once it's finalized
[Current Documentation](https://docs.google.com/document/d/1S3gh0ZE2kzskOGTjP7PLjfXYNhQGrF0QhKRbN764YsA/edit)

- [x] Create a doc with draft content to review
- [x] Create image assets
- [x] Add content to wagtail
- [x] Publish

**Comment by kristinashu** [comment]
Here is a related ticket https://github.com/MozillaFoundation/Design/issues/478 - I'm going to close that one but please review it as part of this ticket.

**Comment by nancyt1** [comment]
Started drafting outline of visual guidelines in this [doc](https://docs.google.com/document/d/1S3gh0ZE2kzskOGTjP7PLjfXYNhQGrF0QhKRbN764YsA/edit#bookmark=id.jr1yn0txya8f) that was used for the current page

**Comment by nancyt1** [comment]
Published [wagtail page ](https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/)with all assets and current copy. I'll reach out to audrey and designers again to get final feedback, make sure things are formatted right, and make sure all images are large enough.

Looking through ticket #528, it'd be good to link to additional documentation on brand voice for social and how to share on social but that might be getting too in the weeds of content for this guideline page, which focuses more on the visual creation. _(But if we wanted to expand the scope of this documentation, it would be helpful to have a single source of truth for all things social/content)_

**Comment by kristinashu** [comment]
w00t! And I agree, brand voice is out of scope for us.

**Comment by nancyt1** [comment]
[Page](https://foundation.mozilla.org/en/docs/brand/brand-identity/social-media/) is live! I'll make followup edits as they come in.
