### ISSUE TITLE
[Misc] small and unplanned design requests for Mar 14 sprint

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#999]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

**Comment by kristinashu** [comment]
@sabrinang @nancyt1 @beccaklam write a sentence or two about your the key project you're working on for a tl;dr staff update. Feel free to link out to more info. Deadline: Morning of Friday March 18.

**Comment by beccaklam** [comment]
Had to design for some edge cases for the Interactive Report navigation. Time spent: _3 hours_
